// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.internet.udp.OutgoingPacket.0.2
import * as dsdlRuntime from "../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.internet.udp.OutgoingPacket";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 0;
export const DSDL_VERSION_MINOR = 2;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "variable-array";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

// This message carries UDP packets from a node on the local bus to a remote host on the Internet or a LAN.
//
// Any node can broadcast a message of this type.
//
// All nodes that are capable of communication with the Internet or a LAN should subscribe to messages
// of this type and forward the payload to the indicated host and port using exactly one UDP datagram
// per message (i.e. additional fragmentation is to be avoided). Such nodes will be referred to as
// "modem nodes".
//
// It is expected that some systems will have more than one modem node available.
// Each modem node is supposed to forward every message it sees, which will naturally create
// some degree of modular redundancy and fault tolerance. The remote host should therefore be able to
// properly handle possibly duplicated messages from different source addresses, in addition to
// possible duplications introduced by the UDP/IP protocol itself. There are at least two obvious
// strategies that can be employed by the remote host:
//
//   - Accept only the first message, ignore duplicates. This approach requires that the UDP stream
//     should contain some metadata necessary for the remote host to determine the source and ordering
//     of each received datum. This approach works best for periodic data, such as telemetry, where
//     the sender does not expect any responses.
//
//   - Process all messages, including duplicates. This approach assumes that the remote host acts
//     as a server, processing all received requests and providing responses to each. This arrangement
//     implies that the client may receive duplicated responses. It is therefore the client's
//     responsibility to resolve the possible ambiguity. An obvious solution is to accept the first
//     arrived response and ignore the later ones.
//
// Applications are free to choose whatever redundancy management strategy works best for them.
//
// If the source node expects that the remote host will send some data back, it shall explicitly notify
// the modem nodes about this, so that they could prepare to perform reverse forwarding when the
// expected data arrives from the remote host. The technique of reverse forwarding is known in
// networking as IP Masquerading, or (in general) Network Address Translation (NAT). The notification
// is performed by means of setting one of the corresponding flags defined below.
//
// In order to be able to match datagrams received from remote hosts and the local nodes they should
// be forwarded to, modem nodes are required to keep certain metadata about outgoing datagrams. Such
// metadata is stored in a data structure referred to as "NAT table", where every entry would normally
// contain at least the following fields:
//   - The local UDP port number that was used to send the outgoing datagram from.
//     Per RFC 4787, the port number is chosen by the modem node automatically.
//   - The node-ID of the local node that has sent the outgoing datagram.
//   - Value of the field session_id defined below.
//   - Possibly some other data, depending on the implementation.
//
// The modem nodes are required to keep each NAT table entry for at least NAT_ENTRY_MIN_TTL seconds
// since the last reverse forwarding action was performed. Should the memory resources of the modem node
// be exhausted, it is allowed to remove old NAT entries earlier, following the policy of least recent use.
//
// Having received a UDP packet from a remote host, the modem node would check the NAT table in order
// to determine where on the Cyphal bus the received data should be forwarded to. If the NAT table
// contains no matches, the received data should be silently dropped. If a match is found, the
// modem node will forward the data to the recipient node using the service HandleIncomingPacket.
// If the service invocation times out, the modem node is permitted to remove the corresponding entry from
// the NAT table immediately (but it is not required). This will ensure that the modem nodes will not be
// tasked with translations for client nodes that are no longer online or are unreachable.
// Additionally, client nodes will be able to hint the modem nodes to remove translation entries they no
// longer need by simply refusing to respond to the corresponding service invocation. Please refer to
// the definition of that service data type for a more in-depth review of the reverse forwarding process.
//
// Modem nodes can also perform traffic shaping, if needed, by means of delaying or dropping UDP
// datagrams that exceed the quota.
//
// To summarize, a typical data exchange occurrence should amount to the following actions:
//
//   - A local Cyphal node broadcasts a message of type OutgoingPacket with the payload it needs
//     to forward. If the node expects the remote host to send any data back, it sets the masquerading flag.
//
//   - Every modem node on the bus receives the message and performs the following actions:
//
//       - The domain name is resolved, unless the destination address provided in the message
//         is already an IP address, in which case this step should be skipped.
//
//       - The domain name to IP address mapping is added to the local DNS cache, although this
//         part is entirely implementation defined and is not required.
//
//       - The masquerading flag is checked. If it is set, a new entry is added to the NAT table.
//         If such entry already existed, its expiration timeout is reset. If no such entry existed
//         and a new one cannot be added because of memory limitations, the least recently used
//         (i.e. oldest) entry of the NAT table is replaced with the new one.
//
//       - The payload is forwarded to the determined IP address.
//
//   - At this point, direct forwarding is complete. Should any of the modem nodes receive an incoming
//     packet, they would attempt to perform a reverse forwarding according to the above provided algorithm.
//
// It is recommended to use the lowest transport priority level when broadcasting messages of this type,
// in order to avoid interference with a real-time traffic on the bus. Usage of higher priority levels is
// unlikely to be practical because the latency and throughput limitations introduced by the on-board radio
// communication equipment are likely to vastly exceed those of the local CAN bus.
export interface OutgoingPacket {
  // This field is set to an arbitrary value by the transmitting node in order to be able to match the response
  // with the locally kept context. The function of this field is virtually identical to that of UDP/IP port
  // numbers. This value can be set to zero safely if the sending node does not have multiple contexts to
  // distinguish between.
  session_id: number;
  // UDP destination port number.
  destination_port: number;
  // Domain name or IP address where the payload should be forwarded to.
  // Note that broadcast addresses are allowed here, for example, 255.255.255.255.
  // Broadcasting with masquerading enabled works the same way as unicasting with masquerading enabled: the modem
  // node should take care to channel all traffic arriving at the opened port from any source to the node that
  // requested masquerading.
  // The full domain name length may not exceed 253 octets, according to the DNS specification.
  // Cyphal imposes a stricter length limit in order to reduce the memory and traffic burden on the bus: 45 characters.
  // 45 characters is the amount of space that is required to represent the longest possible form of an IPv6 address
  // (an IPv4-mapped IPv6 address). Examples:
  //   "forum.opencyphal.org"                          - domain name
  //   "192.168.1.1"                                   - IPv4 address
  //   "2001:0db8:85a3:0000:0000:8a2e:0370:7334"       - IPv6 address, full form
  //   "2001:db8:85a3::8a2e:370:7334"                  - IPv6 address, same as above, short form (preferred)
  //   "ABCD:ABCD:ABCD:ABCD:ABCD:ABCD:192.168.158.190" - IPv4-mapped IPv6, full form (length limit, 45 characters)
  destination_address: Array<number>;
  // Expect data back (i.e., instruct the modem to use the NAT table).
  use_masquerading: boolean;
  // Use Datagram Transport Layer Security. Drop the packet if DTLS is not supported.
  use_dtls: boolean;
  // Effective payload. This data will be forwarded to the remote host verbatim.
  // UDP packets that contain more than 508 bytes of payload may be dropped by some types of
  // communication equipment. Refer to RFC 791 and 2460 for an in-depth review.
  payload: Array<number>;
}

// [second]
// Modem nodes are required to keep the NAT table entries alive for at least this amount of time, unless the
// table is overflowed, in which case they are allowed to remove least recently used entries in favor of
// newer ones. Modem nodes are required to be able to accommodate at least 100 entries in the NAT table.
export const OUTGOING_PACKET_NAT_ENTRY_MIN_TTL = 86400;

export function serializeOutgoingPacket(value: OutgoingPacket): Uint8Array {
  const out = new Uint8Array(561);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_internet_udp_OutgoingPacket_0_2 = (capacityBits: number): boolean => 4488 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 65535n ? 65535n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__1__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 65535n ? 65535n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__2__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 255n ? 255n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__6__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 255n ? 255n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__2__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__6__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__2 = (value: number): boolean => (value >= 0) && (value <= 45);
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__6 = (value: number): boolean => (value >= 0) && (value <= 508);

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_internet_udp_OutgoingPacket_0_2(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 16, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__0__ser(value.session_id), true);
  offsetBits += 16;
  dsdlRuntime.writeUnsigned(out, offsetBits, 16, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__1__ser(value.destination_port), true);
  offsetBits += 16;
  const destination_addressArray = value.destination_address;
  if (!Array.isArray(destination_addressArray)) {
    throw new Error("field 'destination_address' expects an array");
  }
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__2(destination_addressArray.length)) {
    throw new Error("field 'destination_address' exceeds max length 45");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 8, Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__2__ser(destination_addressArray.length)), false);
  offsetBits += 8;
  for (let i = 0; i < destination_addressArray.length; ++i) {
    dsdlRuntime.writeUnsigned(out, offsetBits, 8, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__2__ser(destination_addressArray[i]), true);
    offsetBits += 8;
  }
  dsdlRuntime.setBit(out, offsetBits, value.use_masquerading);
  offsetBits += 1;
  dsdlRuntime.setBit(out, offsetBits, value.use_dtls);
  offsetBits += 1;
  for (let _PaddingBit = 0; _PaddingBit < 6; ++_PaddingBit) {
    dsdlRuntime.setBit(out, offsetBits + _PaddingBit, false);
  }
  offsetBits += 6;
  const payloadArray = value.payload;
  if (!Array.isArray(payloadArray)) {
    throw new Error("field 'payload' expects an array");
  }
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__6(payloadArray.length)) {
    throw new Error("field 'payload' exceeds max length 508");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 16, Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__6__ser(payloadArray.length)), false);
  offsetBits += 16;
  for (let i = 0; i < payloadArray.length; ++i) {
    dsdlRuntime.writeUnsigned(out, offsetBits, 8, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__6__ser(payloadArray[i]), true);
    offsetBits += 8;
  }
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeOutgoingPacket(bytes: Uint8Array): { value: OutgoingPacket; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__1__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__2__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__6__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__2__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__6__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__2 = (value: number): boolean => (value >= 0) && (value <= 45);
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__6 = (value: number): boolean => (value >= 0) && (value <= 508);

  const value = {} as OutgoingPacket;
  let offsetBits = 0;
  const session_idRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 16);
  value.session_id = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__0__deser(session_idRaw));
  offsetBits += 16;
  const destination_portRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 16);
  value.destination_port = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__1__deser(destination_portRaw));
  offsetBits += 16;
  const destination_addressLengthRaw = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 8));
  offsetBits += 8;
  const destination_addressLength = Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__2__deser(destination_addressLengthRaw));
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__2(destination_addressLength)) {
    throw new Error("decoded length for field 'destination_address' exceeds max length 45");
  }
  const destination_addressArray: Array<number> = new Array(destination_addressLength);
  for (let i = 0; i < destination_addressLength; ++i) {
    const destination_addressItemRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 8);
    destination_addressArray[i] = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__2__deser(destination_addressItemRaw));
    offsetBits += 8;
  }
  value.destination_address = destination_addressArray;
  value.use_masquerading = dsdlRuntime.getBit(bytes, offsetBits);
  offsetBits += 1;
  value.use_dtls = dsdlRuntime.getBit(bytes, offsetBits);
  offsetBits += 1;
  offsetBits += 6;
  const payloadLengthRaw = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 16));
  offsetBits += 16;
  const payloadLength = Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_internet_udp_OutgoingPacket_0_2__6__deser(payloadLengthRaw));
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_internet_udp_OutgoingPacket_0_2__6(payloadLength)) {
    throw new Error("decoded length for field 'payload' exceeds max length 508");
  }
  const payloadArray: Array<number> = new Array(payloadLength);
  for (let i = 0; i < payloadLength; ++i) {
    const payloadItemRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 8);
    payloadArray[i] = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_internet_udp_OutgoingPacket_0_2__6__deser(payloadItemRaw));
    offsetBits += 8;
  }
  value.payload = payloadArray;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
