# Part of the OpenCyphal project, under the MIT licence
# SPDX-License-Identifier: MIT
#
# rules_dsdl -- generate C from DSDL and hand Bazel ordinary source files.
#
# WHY THERE IS NO TREE ARTIFACT HERE
#
# Bazel insists an action declare its outputs during analysis, before anything runs. The usual answer
# for a generator whose output list is not known until it executes is a tree artifact
# (`declare_directory`), which Bazel supports but `cc_library` consumes poorly -- headers inside one
# are awkward to put on an include path, and the result is a rule that fights the C rules all the way
# down.
#
# None of that is needed, because dsdlc's output names are a function of its input names. One
# definition produces exactly two files, and `<port>.<Name>.<major>.<minor>.dsdl` becomes
# `<Name>_<major>_<minor>.c` and `.h` under the namespace path. So the macros below compute the
# output list in Starlark, declare real files, and hand `cc_library` exactly what it expects.
#
# WHY THESE ARE THREE MACROS AND NOT ONE
#
# Output *names* are derivable, but a definition's dependency *closure* is not: nothing in
# `SensorFrame.1.0.dsdl`'s filename says it reaches `uavcan.time.SynchronizedTimestamp.1.0`, and
# finding out means running the compiler, which analysis cannot do. So `dsdl_c_library` always passes
# `--omit-dependencies` and generates only the definitions it was handed. Anything those definitions
# reach has to be generated by some other target and named in `deps`.
#
# That is what the other two macros are for: `dsdl_support_library` owns the runtime header, and
# `dsdl_builtin_library` owns the standard types. Forgetting one is not silent -- the include it
# should have provided is simply absent and the compile fails on it.
#
# Note that each macro writes into a directory named after its target, so two targets cannot produce
# the same file and Bazel's duplicate-output error never arises here. The division of labour is
# driven by `--omit-dependencies`, not by that.

load("@rules_cc//cc:defs.bzl", "cc_library")

_DSDLC = "@dsdlc//:dsdlc"

def _strip_suffix(value, suffix):
    if not value.endswith(suffix):
        fail("expected {} to end with {}".format(value, suffix))
    return value[:-len(suffix)]

def _definition_stem(basename):
    """`6300.SensorFrame.1.0.dsdl` -> `SensorFrame_1_0`; the port ID prefix is optional."""
    stem = _strip_suffix(basename, ".dsdl")
    parts = stem.split(".")

    # A leading all-digit component is a fixed port ID, which is not part of the type's name.
    if len(parts) > 3 and parts[0].isdigit():
        parts = parts[1:]

    if len(parts) != 3:
        fail(
            "cannot derive an output name from '{}'. ".format(basename) +
            "Expected [<port-id>.]<Name>.<major>.<minor>.dsdl.",
        )
    return "{}_{}_{}".format(parts[0], parts[1], parts[2])

def _namespace_relative_outputs(src, root, outdir):
    """Output paths for one definition, relative to the generated tree.

    `root` names the root namespace directory, so its parent is what output paths are relative to:
    `dsdl/kitbag` + `dsdl/kitbag/sub/Type.1.0.dsdl` -> `kitbag/sub/Type_1_0.{c,h}`.
    """
    parent = root.rsplit("/", 1)[0] if "/" in root else ""
    prefix = parent + "/" if parent else ""
    if not src.startswith(prefix):
        fail("source '{}' is not under the root namespace's parent '{}'".format(src, parent))

    relative = src[len(prefix):]
    directory = relative.rsplit("/", 1)[0] if "/" in relative else ""
    stem = _definition_stem(relative.rsplit("/", 1)[-1])
    base = "{}/{}/{}".format(outdir, directory, stem) if directory else "{}/{}".format(outdir, stem)
    return [base + ".c", base + ".h"]

def _builtin_outputs(type_name, outdir):
    """`uavcan.time.SynchronizedTimestamp.1.0` -> `uavcan/time/SynchronizedTimestamp_1_0.{c,h}`."""
    parts = type_name.split(".")
    if len(parts) < 4:
        fail(
            "'{}' is not a fully qualified versioned type. ".format(type_name) +
            "Expected <namespace>.<Name>.<major>.<minor>, for example " +
            "uavcan.time.SynchronizedTimestamp.1.0.",
        )
    stem = "{}_{}_{}".format(parts[-3], parts[-2], parts[-1])
    base = "{}/{}/{}".format(outdir, "/".join(parts[:-3]), stem)
    return [base + ".c", base + ".h"]

def _package_path(path):
    """Exec-root-relative path of something named relative to the current package."""
    package = native.package_name()
    return path if not package else package + "/" + path

def _generate(name, outdir, outs, arguments, srcs = [], language = "c"):
    native.genrule(
        name = name + "__generate",
        srcs = srcs,
        outs = outs,
        tools = [_DSDLC],
        # Declared outputs are named relative to $(RULEDIR), and they all sit under <name>.gen, so
        # that is exactly what --outdir must be. Handing dsdlc $(RULEDIR) itself would put every file
        # one directory above where Bazel is expecting it.
        cmd = "$(execpath {}) --target-language {} --outdir $(RULEDIR)/{} {}".format(
            _DSDLC,
            language,
            outdir,
            arguments,
        ),
        message = "Generating DSDL C for " + name,
    )

def dsdl_support_library(name, visibility = None):
    """The runtime header, and nothing derived from a definition.

    Exactly one target in a build may own this. Every dsdl_c_library and dsdl_builtin_library should
    depend on it.
    """
    outdir = name + ".gen"
    _generate(
        name,
        outdir,
        outs = [outdir + "/dsdl_runtime.h"],
        arguments = "--generate-support only",
    )
    cc_library(
        name = name,
        hdrs = [outdir + "/dsdl_runtime.h"],
        includes = [outdir],
        visibility = visibility,
    )

def dsdl_builtin_library(name, types, deps = [], visibility = None):
    """Standard types from the catalog compiled into dsdlc, named as `uavcan.node.Heartbeat.1.0`.

    Give shared standard types one owner here. Each namespace is generated with
    --omit-dependencies, so nothing else will produce them, and a type nobody owns shows up as a
    missing include at compile time.

    Dependencies are not resolved for you: list every type you need, transitively. That is the price
    of declaring outputs during analysis, and a missing one fails at compile time with an unresolved
    include rather than silently.
    """
    if not types:
        fail("dsdl_builtin_library({}) needs at least one type".format(name))

    outdir = name + ".gen"
    outs = []
    for type_name in types:
        outs += _builtin_outputs(type_name, outdir)

    selectors = " ".join(["+" + type_name for type_name in types])
    _generate(
        name,
        outdir,
        outs = outs,
        arguments = "--generate-support never --omit-dependencies " + selectors,
    )
    cc_library(
        name = name,
        srcs = [out for out in outs if out.endswith(".c")],
        hdrs = [out for out in outs if out.endswith(".h")],
        includes = [outdir],
        deps = deps,
        visibility = visibility,
    )

def dsdl_obj_library(
        name,
        srcs,
        root,
        builtin_types = [],
        options = [],
        deps = [],
        visibility = None):
    """The same definitions already assembled rather than as sources.

    The `obj` backend lowers the schema to LLVM IR and assembles it, handing back the headers and
    the objects. No C is written and no compiler is invoked, which is what you want when the
    generated code should be built once -- for a target that is not this host, or by a party who
    ships the objects rather than the schema.

    What the definitions reach is assembled too: `--omit-dependencies` is not passed, so there is
    nothing else to link. Both the headers and the objects still have to be declared during
    analysis, and the dependency closure is not derivable from filenames -- so list any standard
    types the definitions reach in `builtin_types`, exactly as for dsdl_builtin_library. A missing
    one is a missing include at compile time, not a silent gap.

    Pass `--target-triple` through `options` to assemble for a target other than the host; the
    objects then only link into a build using that same target.
    """
    if not srcs:
        fail("dsdl_obj_library({}) needs at least one source".format(name))

    outdir = name + ".gen"

    # The support header is published by this backend too, so it is declared here rather than
    # coming from a dsdl_support_library -- an obj target owns its whole interface.
    outs = [outdir + "/dsdl_runtime.h"]
    for src in srcs:
        for out in _namespace_relative_outputs(src, root, outdir):
            outs += [out[:-2] + ".o"] if out.endswith(".c") else [out]
    for type_name in builtin_types:
        for out in _builtin_outputs(type_name, outdir):
            outs += [out[:-2] + ".o"] if out.endswith(".c") else [out]

    targets = " ".join([
        "{}:{}".format(_package_path(root), src[len(root) + 1:])
        for src in srcs
    ])

    # No --generate-support: the obj backend publishes its own support header and dsdlc rejects
    # the flag for it.
    _generate(
        name + "_objects",
        outdir,
        outs = outs,
        arguments = "{} {}".format(" ".join(options), targets),
        srcs = srcs,
        language = "obj",
    )

    # A precompiled object is a source as far as cc_library is concerned, which is what lets the
    # objects be linked without an archive to wrap them.
    cc_library(
        name = name,
        srcs = [out for out in outs if out.endswith(".o")],
        hdrs = [out for out in outs if out.endswith(".h")],
        includes = [outdir],
        deps = deps,
        visibility = visibility,
    )

def dsdl_c_library(name, srcs, root, deps = [], visibility = None):
    """One root namespace's own definitions.

    `srcs` are the `.dsdl` files and `root` is the root namespace directory they live under, both
    relative to this package. Dependencies on other namespaces and on standard types go in `deps`,
    as dsdl_c_library and dsdl_builtin_library targets.
    """
    if not srcs:
        fail("dsdl_c_library({}) needs at least one source".format(name))

    outdir = name + ".gen"
    outs = []
    for src in srcs:
        outs += _namespace_relative_outputs(src, root, outdir)

    # `<root>:<relative>` addresses one definition without the root inference a bare path would go
    # through -- which resolves to a different root and shifts every output path by a directory.
    targets = " ".join([
        "{}:{}".format(_package_path(root), src[len(root) + 1:])
        for src in srcs
    ])
    _generate(
        name,
        outdir,
        outs = outs,
        arguments = "--generate-support never --omit-dependencies " + targets,
        srcs = srcs,
    )
    cc_library(
        name = name,
        srcs = [out for out in outs if out.endswith(".c")],
        hdrs = [out for out in outs if out.endswith(".h")],
        includes = [outdir],
        deps = deps,
        visibility = visibility,
    )
