# Part of the OpenCyphal project, under the MIT licence
# SPDX-License-Identifier: MIT
#
# Generating a whole namespace as an external repository.
#
# WHY THIS EXISTS ALONGSIDE THE MACROS IN defs.bzl
#
# Those macros generate as build actions, which means every output has to be named during analysis.
# Output *names* are derivable from input names, so that part is free -- but a definition's dependency
# closure is not. `lanyard` reaches twelve standard types, none of them visible in any filename, so
# the caller has to list them by hand and a missing one surfaces as a compile error naming a type
# they never wrote. That does not scale: it was one entry for a four-type namespace and twelve for a
# twenty-four-type one, and the list has to be rediscovered whenever a definition gains a field.
#
# A repository rule runs at fetch time instead, before any BUILD file is loaded. By the time Bazel
# evaluates the generated BUILD file the files are on disk, so `glob()` can simply see them and
# nothing needs declaring. The closure problem disappears rather than being managed.
#
# The trade is that generation is no longer a build action: it is not sandboxed, and it re-runs when
# the repository is refetched rather than when an individual output goes stale. `watch()` is what
# makes that correct, and it has to cover both inputs to the generation -- the definitions dsdlc
# reports, and dsdlc itself. Under the macros in defs.bzl both are ordinary action inputs and Bazel
# digests them for free; here nothing is an action input, so anything not watched is invisible.

# Every glob allows an empty result: a C-only namespace has no .cpp and the obj lane has no sources
# at all, while an empty glob is a hard error by default.
#
# Sources for the source-emitting backends; the objects plus their published headers for `obj`.
# Both are globbed, which is the whole point of generating at fetch time: the files are already on
# disk when this BUILD file is loaded, so nothing has to be named in advance.
_BUILD_TEMPLATE_SOURCES = """# Generated by rules_dsdl. Do not edit.
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = {name},
    srcs = glob(["generated/**/*.c", "generated/**/*.cpp"], allow_empty = True),
    hdrs = glob(["generated/**/*.h", "generated/**/*.hpp"], allow_empty = True),
    includes = ["generated"],
    visibility = ["//visibility:public"],
)
"""

# A precompiled object is a source as far as cc_library is concerned, which is what lets the
# objects be linked without an archive to wrap them.
_BUILD_TEMPLATE_OBJ = """# Generated by rules_dsdl. Do not edit.
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = {name_repr},
    srcs = glob(["generated/**/*.o"], allow_empty = True),
    hdrs = glob(["generated/**/*.h", "generated/**/*.hpp"], allow_empty = True),
    includes = ["generated"],
    visibility = ["//visibility:public"],
)
"""

def _resolve_dsdlc(repository_ctx):
    explicit = repository_ctx.os.environ.get("DSDLC", "")
    if explicit:
        resolved = repository_ctx.path(explicit)
        if not resolved.exists:
            fail("DSDLC is set to '{}', which does not exist.".format(explicit))
        return resolved

    resolved = repository_ctx.which("dsdlc")
    if resolved == None:
        fail(
            "rules_dsdl could not find dsdlc.\\n" +
            "Install llvm-dsdl and put dsdlc on PATH, or set the DSDLC environment variable to its " +
            "absolute path (`common --repo_env=DSDLC=/path/to/dsdlc` in .bazelrc).",
        )
    return resolved

def _run(repository_ctx, dsdlc, arguments, what):
    result = repository_ctx.execute([str(dsdlc)] + arguments, quiet = True)
    if result.return_code != 0:
        fail("rules_dsdl: dsdlc failed while {}.\n{}\n{}".format(what, result.stdout, result.stderr))
    return result

def _dsdl_namespace_repository_impl(repository_ctx):
    dsdlc = _resolve_dsdlc(repository_ctx)

    # Watch the compiler, not just where it was found. `environ` covers DSDLC and PATH changing, but
    # the ordinary case is that neither does: a developer rebuilds dsdlc, or a package upgrade drops
    # a new binary at the same install path. Without this, that build silently serves generated code
    # from the previous compiler -- a dsdlc that cannot even run still yields "up-to-date", because
    # nothing in the graph refers to it. Cheap to get wrong and expensive to notice.
    repository_ctx.watch(dsdlc)

    # The anchor is a file in the calling module whose directory is the reference point for `root`.
    # A label cannot name a directory, so a file inside the workspace is the way to find one; the
    # module's own MODULE.bazel is the obvious choice and needs no extra file to exist.
    anchor = repository_ctx.path(repository_ctx.attr.anchor)
    namespace_root = anchor.dirname.get_child(*repository_ctx.attr.root.split("/"))
    if not namespace_root.exists:
        fail("rules_dsdl: no namespace at {} (root = '{}' relative to {})".format(
            namespace_root,
            repository_ctx.attr.root,
            anchor.dirname,
        ))

    base = [
        "--target-language",
        repository_ctx.attr.language,
        str(namespace_root),
    ] + repository_ctx.attr.options

    # Ask which definitions this namespace actually reads, and watch every one. Without this the
    # repository is only refetched when its own attributes change, so an edited definition would be
    # invisible and the build would serve generated code that no longer matches the schema.
    #
    # dsdlc's answer is used rather than a directory walk because it is the authoritative set: it
    # includes definitions reached through a lookup directory outside the namespace tree, which a
    # walk would miss.
    inputs = _run(repository_ctx, dsdlc, base + ["--list-inputs"], "listing inputs")
    for path in inputs.stdout.strip().split(";"):
        if path:
            repository_ctx.watch(path)

    _run(
        repository_ctx,
        dsdlc,
        base + ["--outdir", str(repository_ctx.path("generated"))],
        "generating",
    )

    name = repository_ctx.attr.library_name or repository_ctx.name
    if repository_ctx.attr.language == "obj":
        content = _BUILD_TEMPLATE_OBJ.format(name_repr = repr(name))
    else:
        content = _BUILD_TEMPLATE_SOURCES.format(name = repr(name))
    repository_ctx.file("BUILD.bazel", content, executable = False)

dsdl_namespace_repository = repository_rule(
    implementation = _dsdl_namespace_repository_impl,
    attrs = {
        "anchor": attr.label(
            default = Label("@@//:MODULE.bazel"),
            doc = "A file in the calling module; `root` is resolved relative to its directory.",
        ),
        "root": attr.string(
            mandatory = True,
            doc = "Root namespace directory, relative to the anchor's directory.",
        ),
        "language": attr.string(default = "c"),
        "library_name": attr.string(
            doc = "Name of the generated cc_library; defaults to the repository name.",
        ),
        "options": attr.string_list(
            doc = "Extra dsdlc flags, passed through verbatim.",
        ),
    },
    environ = ["DSDLC", "PATH"],
    doc = """Generates a whole namespace at fetch time and exposes it as one cc_library.

Everything the namespace reaches is generated, including the standard types from the catalog
compiled into dsdlc, so there is nothing to list and nothing to keep in step. Use this unless you
specifically want generation to happen as a build action -- see defs.bzl for that.
""",
)
