// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.node.port.ID.1.0
import * as dsdlRuntime from "../../../dsdl_runtime";

import { deserializeServiceID, serializeServiceID } from "./service_id_1_0";
import { deserializeSubjectID, serializeSubjectID } from "./subject_id_1_0";
import type { ServiceID } from "./service_id_1_0";
import type { SubjectID } from "./subject_id_1_0";
export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.node.port.ID";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "invalid-bit-length";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

// Used to refer either to a Service or to a Subject.
// The chosen tag identifies the kind of the port, then the numerical ID identifies the port within the kind.
export type ID =
  | { _tag: 0; subject_id: SubjectID; }
  | { _tag: 1; service_id: ServiceID; };


export function serializeID(value: ID): Uint8Array {
  const out = new Uint8Array(3);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_node_port_ID_1_0 = (capacityBits: number): boolean => 24 <= capacityBits;
  const mlir_llvmdsdl_plan_validate_union_tag__uavcan_node_port_ID_1_0 = (tagValue: number): boolean => (tagValue === 0) || (tagValue === 1);
  const mlir_llvmdsdl_plan_union_tag__uavcan_node_port_ID_1_0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_node_port_ID_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  let tag = Math.trunc((value as { _tag: number })._tag);
  if (!mlir_llvmdsdl_plan_validate_union_tag__uavcan_node_port_ID_1_0(tag)) {
    throw new Error("invalid union tag " + tag);
  }
  tag = Number(mlir_llvmdsdl_plan_union_tag__uavcan_node_port_ID_1_0__ser(tag));
  dsdlRuntime.writeUnsigned(out, offsetBits, 8, tag, false);
  offsetBits += 8;
  switch (tag) {
  case 0: {
    const optionValue = (value as Record<string, unknown>).subject_id;
    if (optionValue === undefined) {
      throw new Error("union field 'subject_id' missing for tag 0");
    }
    const subject_idOptionAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    for (let subject_idOptionAlignBit = offsetBits; subject_idOptionAlignBit < subject_idOptionAlignedOffsetBits; ++subject_idOptionAlignBit) {
      dsdlRuntime.setBit(out, subject_idOptionAlignBit, false);
    }
    offsetBits = subject_idOptionAlignedOffsetBits;
    const subject_idBytes = serializeSubjectID(optionValue as SubjectID);
    dsdlRuntime.copyBits(out, offsetBits, subject_idBytes, 0, 16);
    offsetBits += 16;
    break;
  }
  case 1: {
    const optionValue = (value as Record<string, unknown>).service_id;
    if (optionValue === undefined) {
      throw new Error("union field 'service_id' missing for tag 1");
    }
    const service_idOptionAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    for (let service_idOptionAlignBit = offsetBits; service_idOptionAlignBit < service_idOptionAlignedOffsetBits; ++service_idOptionAlignBit) {
      dsdlRuntime.setBit(out, service_idOptionAlignBit, false);
    }
    offsetBits = service_idOptionAlignedOffsetBits;
    const service_idBytes = serializeServiceID(optionValue as ServiceID);
    dsdlRuntime.copyBits(out, offsetBits, service_idBytes, 0, 16);
    offsetBits += 16;
    break;
  }
  default:
    throw new Error("invalid union tag " + tag);
  }
  const alignedOffsetBits = dsdlRuntime.byteLengthForBits(offsetBits) * 8;
  for (let bit = offsetBits; bit < alignedOffsetBits; ++bit) {
    dsdlRuntime.setBit(out, bit, false);
  }
  offsetBits = alignedOffsetBits;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeID(bytes: Uint8Array): { value: ID; consumed: number } {
  const mlir_llvmdsdl_plan_validate_union_tag__uavcan_node_port_ID_1_0 = (tagValue: number): boolean => (tagValue === 0) || (tagValue === 1);
  const mlir_llvmdsdl_plan_union_tag__uavcan_node_port_ID_1_0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  let offsetBits = 0;
  let tag = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 8));
  tag = Number(mlir_llvmdsdl_plan_union_tag__uavcan_node_port_ID_1_0__deser(tag));
  if (!mlir_llvmdsdl_plan_validate_union_tag__uavcan_node_port_ID_1_0(tag)) {
    throw new Error("decoded invalid union tag " + tag);
  }
  offsetBits += 8;
  let value: ID;
  switch (tag) {
  case 0: {
    offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    let optionValue: SubjectID;
    const subject_idBytes = dsdlRuntime.extractBits(bytes, offsetBits, 16);
    optionValue = deserializeSubjectID(subject_idBytes).value;
    offsetBits += 16;
    value = { _tag: 0, subject_id: optionValue } as ID;
    break;
  }
  case 1: {
    offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    let optionValue: ServiceID;
    const service_idBytes = dsdlRuntime.extractBits(bytes, offsetBits, 16);
    optionValue = deserializeServiceID(service_idBytes).value;
    offsetBits += 16;
    value = { _tag: 1, service_id: optionValue } as ID;
    break;
  }
  default:
    throw new Error("decoded invalid union tag " + tag);
  }
  offsetBits = dsdlRuntime.byteLengthForBits(offsetBits) * 8;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
