// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.node.port.SubjectID.1.0
import * as dsdlRuntime from "../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.node.port.SubjectID";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "sub-byte-field";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

// Subject-ID. The ranges are defined by the specification.
export interface SubjectID {
  value: number;
}

export const SUBJECT_ID_MAX = 8191;

export function serializeSubjectID(value: SubjectID): Uint8Array {
  const out = new Uint8Array(2);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_node_port_SubjectID_1_0 = (capacityBits: number): boolean => 16 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_port_SubjectID_1_0__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 8191n ? 8191n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_node_port_SubjectID_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 13, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_port_SubjectID_1_0__0__ser(value.value), true);
  offsetBits += 13;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeSubjectID(bytes: Uint8Array): { value: SubjectID; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_port_SubjectID_1_0__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 8191n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  const value = {} as SubjectID;
  let offsetBits = 0;
  const valueRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 13);
  value.value = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_port_SubjectID_1_0__0__deser(valueRaw));
  offsetBits += 13;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
