// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.file.GetInfo.0.2
import * as dsdlRuntime from "../../dsdl_runtime";

import { deserializeError, serializeError } from "./error_1_0";
import { deserializePath, serializePath } from "./path_2_0";
import type { Error } from "./error_1_0";
import type { Path } from "./path_2_0";
export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.file.GetInfo";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 0;
export const DSDL_VERSION_MINOR = 2;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "invalid-bit-length";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "invalid-bit-length";

// Information about a remote file system entry (file, directory, etc).
export interface GetInfo_Request {
  path: Path;
}


export function serializeGetInfo_Request(value: GetInfo_Request): Uint8Array {
  const out = new Uint8Array(256);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_file_GetInfo_0_2__request = (capacityBits: number): boolean => 2048 <= capacityBits;

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_file_GetInfo_0_2__request(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  const pathAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let pathAlignBit = offsetBits; pathAlignBit < pathAlignedOffsetBits; ++pathAlignBit) {
    dsdlRuntime.setBit(out, pathAlignBit, false);
  }
  offsetBits = pathAlignedOffsetBits;
  const pathBytes = serializePath(value.path);
  dsdlRuntime.copyBits(out, offsetBits, pathBytes, 0, 2048);
  offsetBits += 2048;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeGetInfo_Request(bytes: Uint8Array): { value: GetInfo_Request; consumed: number } {
  const value = {} as GetInfo_Request;
  let offsetBits = 0;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const pathBytes = dsdlRuntime.extractBits(bytes, offsetBits, 2048);
  value.path = deserializePath(pathBytes).value;
  offsetBits += 2048;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}

// Information about a remote file system entry (file, directory, etc).
export interface GetInfo_Response {
  // Result of the operation.
  error: Error;
  // File size in bytes. Should be set to zero for directories.
  size: number;
  // The UNIX Epoch time when the entry was last modified. Zero if unknown.
  unix_timestamp_of_last_modification: number;
  // True if file, false if directory.
  is_file_not_directory: boolean;
  // This is a link to another entry; the above flag indicates the type of the target.
  is_link: boolean;
  // The item can be read by the caller (applies to files and directories).
  is_readable: boolean;
  // The item can be written by the caller (applies to files and directories).
  is_writeable: boolean;
}


export function serializeGetInfo_Response(value: GetInfo_Response): Uint8Array {
  const out = new Uint8Array(13);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_file_GetInfo_0_2__response = (capacityBits: number): boolean => 104 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__2__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 1099511627775n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__3__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 1099511627775n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_file_GetInfo_0_2__response(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  const errorAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let errorAlignBit = offsetBits; errorAlignBit < errorAlignedOffsetBits; ++errorAlignBit) {
    dsdlRuntime.setBit(out, errorAlignBit, false);
  }
  offsetBits = errorAlignedOffsetBits;
  const errorBytes = serializeError(value.error);
  dsdlRuntime.copyBits(out, offsetBits, errorBytes, 0, 16);
  offsetBits += 16;
  dsdlRuntime.writeUnsigned(out, offsetBits, 40, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__2__ser(value.size), false);
  offsetBits += 40;
  dsdlRuntime.writeUnsigned(out, offsetBits, 40, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__3__ser(value.unix_timestamp_of_last_modification), false);
  offsetBits += 40;
  dsdlRuntime.setBit(out, offsetBits, value.is_file_not_directory);
  offsetBits += 1;
  dsdlRuntime.setBit(out, offsetBits, value.is_link);
  offsetBits += 1;
  dsdlRuntime.setBit(out, offsetBits, value.is_readable);
  offsetBits += 1;
  dsdlRuntime.setBit(out, offsetBits, value.is_writeable);
  offsetBits += 1;
  for (let _PaddingBit = 0; _PaddingBit < 4; ++_PaddingBit) {
    dsdlRuntime.setBit(out, offsetBits + _PaddingBit, false);
  }
  offsetBits += 4;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeGetInfo_Response(bytes: Uint8Array): { value: GetInfo_Response; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__2__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 1099511627775n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__3__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 1099511627775n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  const value = {} as GetInfo_Response;
  let offsetBits = 0;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const errorBytes = dsdlRuntime.extractBits(bytes, offsetBits, 16);
  value.error = deserializeError(errorBytes).value;
  offsetBits += 16;
  const sizeRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 40);
  value.size = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__2__deser(sizeRaw));
  offsetBits += 40;
  const unix_timestamp_of_last_modificationRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 40);
  value.unix_timestamp_of_last_modification = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_GetInfo_0_2__response__3__deser(unix_timestamp_of_last_modificationRaw));
  offsetBits += 40;
  value.is_file_not_directory = dsdlRuntime.getBit(bytes, offsetBits);
  offsetBits += 1;
  value.is_link = dsdlRuntime.getBit(bytes, offsetBits);
  offsetBits += 1;
  value.is_readable = dsdlRuntime.getBit(bytes, offsetBits);
  offsetBits += 1;
  value.is_writeable = dsdlRuntime.getBit(bytes, offsetBits);
  offsetBits += 1;
  offsetBits += 4;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}

export type GetInfo = GetInfo_Request;
