// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.file.List.0.2
import * as dsdlRuntime from "../../dsdl_runtime";

import { deserializePath, serializePath } from "./path_2_0";
import type { Path } from "./path_2_0";
export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.file.List";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 0;
export const DSDL_VERSION_MINOR = 2;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "invalid-bit-length";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "invalid-bit-length";

// This service can be used to list a remote directory, one entry per request.
//
// The client should query each entry independently, iterating 'entry_index' from 0 until the last entry.
// When the index reaches the number of elements in the directory, the server will report that there is
// no such entry by returning an empty name.
//
// The field entry_index shall be applied to an ordered list of directory entries (e.g. alphabetically ordered).
// The exact sorting criteria does not matter as long as it provides the same ordering for subsequent service calls.
//
// Observe that this listing operation is fundamentally non-atomic. The caller shall beware of possible race conditions
// and is responsible for handling them properly. Particularly, consider what happens if a new item is inserted into
// the directory between two subsequent calls: if the item happened to be inserted at the index that is lower than the
// index of the next request, the next returned item (or several, if more items were inserted) will repeat the ones
// that were listed earlier. The caller should handle that properly, either by ignoring the repeated items or by
// restarting the listing operation from the beginning (index 0).
export interface List_Request {
  entry_index: number;
  directory_path: Path;
}


export function serializeList_Request(value: List_Request): Uint8Array {
  const out = new Uint8Array(264);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__request = (capacityBits: number): boolean => 2112 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 4294967295n ? 4294967295n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__request(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 32, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__ser(value.entry_index), true);
  offsetBits += 32;
  for (let _PaddingBit = 0; _PaddingBit < 32; ++_PaddingBit) {
    dsdlRuntime.setBit(out, offsetBits + _PaddingBit, false);
  }
  offsetBits += 32;
  const directory_pathAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let directory_pathAlignBit = offsetBits; directory_pathAlignBit < directory_pathAlignedOffsetBits; ++directory_pathAlignBit) {
    dsdlRuntime.setBit(out, directory_pathAlignBit, false);
  }
  offsetBits = directory_pathAlignedOffsetBits;
  const directory_pathBytes = serializePath(value.directory_path);
  dsdlRuntime.copyBits(out, offsetBits, directory_pathBytes, 0, 2048);
  offsetBits += 2048;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeList_Request(bytes: Uint8Array): { value: List_Request; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 4294967295n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  const value = {} as List_Request;
  let offsetBits = 0;
  const entry_indexRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 32);
  value.entry_index = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__deser(entry_indexRaw));
  offsetBits += 32;
  offsetBits += 32;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const directory_pathBytes = dsdlRuntime.extractBits(bytes, offsetBits, 2048);
  value.directory_path = deserializePath(directory_pathBytes).value;
  offsetBits += 2048;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}

// This service can be used to list a remote directory, one entry per request.
//
// The client should query each entry independently, iterating 'entry_index' from 0 until the last entry.
// When the index reaches the number of elements in the directory, the server will report that there is
// no such entry by returning an empty name.
//
// The field entry_index shall be applied to an ordered list of directory entries (e.g. alphabetically ordered).
// The exact sorting criteria does not matter as long as it provides the same ordering for subsequent service calls.
//
// Observe that this listing operation is fundamentally non-atomic. The caller shall beware of possible race conditions
// and is responsible for handling them properly. Particularly, consider what happens if a new item is inserted into
// the directory between two subsequent calls: if the item happened to be inserted at the index that is lower than the
// index of the next request, the next returned item (or several, if more items were inserted) will repeat the ones
// that were listed earlier. The caller should handle that properly, either by ignoring the repeated items or by
// restarting the listing operation from the beginning (index 0).
export interface List_Response {
  // The base name of the referenced entry, i.e., relative to the outer directory.
  // The outer directory path is not included to conserve bandwidth.
  // Empty if such entry does not exist.
  //
  // For example, suppose there is a file "/foo/bar/baz.bin". Listing the directory with the path "/foo/bar/" (the slash
  // at the end is optional) at the index 0 will return "baz.bin". Listing the same directory at the index 1 (or any
  // higher) will return an empty name "", indicating that the caller has reached the end of the list.
  entry_base_name: Path;
}


export function serializeList_Response(value: List_Response): Uint8Array {
  const out = new Uint8Array(260);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__response = (capacityBits: number): boolean => 2080 <= capacityBits;

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__response(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  for (let _PaddingBit = 0; _PaddingBit < 32; ++_PaddingBit) {
    dsdlRuntime.setBit(out, offsetBits + _PaddingBit, false);
  }
  offsetBits += 32;
  const entry_base_nameAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let entry_base_nameAlignBit = offsetBits; entry_base_nameAlignBit < entry_base_nameAlignedOffsetBits; ++entry_base_nameAlignBit) {
    dsdlRuntime.setBit(out, entry_base_nameAlignBit, false);
  }
  offsetBits = entry_base_nameAlignedOffsetBits;
  const entry_base_nameBytes = serializePath(value.entry_base_name);
  dsdlRuntime.copyBits(out, offsetBits, entry_base_nameBytes, 0, 2048);
  offsetBits += 2048;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeList_Response(bytes: Uint8Array): { value: List_Response; consumed: number } {
  const value = {} as List_Response;
  let offsetBits = 0;
  offsetBits += 32;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const entry_base_nameBytes = dsdlRuntime.extractBits(bytes, offsetBits, 2048);
  value.entry_base_name = deserializePath(entry_base_nameBytes).value;
  offsetBits += 2048;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}

export type List = List_Request;
