// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.si.unit.angle.WideVector3.1.0
import * as dsdlRuntime from "../../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.si.unit.angle.WideVector3";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = true;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "eligible";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

export interface WideVector3 {
  radian: Array<number>;
}


export function serializeWideVector3(value: WideVector3): Uint8Array {
  const out = new Uint8Array(24);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_si_unit_angle_WideVector3_1_0 = (capacityBits: number): boolean => 192 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_angle_WideVector3_1_0__0__ser = (value: number): number => value;

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_si_unit_angle_WideVector3_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  const radianArray = value.radian;
  if (!Array.isArray(radianArray) || radianArray.length !== 3) {
    throw new Error("field 'radian' expects exactly 3 elements");
  }
  for (let i = 0; i < 3; ++i) {
    dsdlRuntime.writeFloat(out, offsetBits, 64, mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_angle_WideVector3_1_0__0__ser(radianArray[i]));
    offsetBits += 64;
  }
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeWideVector3(bytes: Uint8Array): { value: WideVector3; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_angle_WideVector3_1_0__0__deser = (value: number): number => value;

  const value = {} as WideVector3;
  let offsetBits = 0;
  const radianArray: Array<number> = new Array(3);
  for (let i = 0; i < 3; ++i) {
    const radianItemRaw = dsdlRuntime.readFloat(bytes, offsetBits, 64);
    radianArray[i] = mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_angle_WideVector3_1_0__0__deser(radianItemRaw);
    offsetBits += 64;
  }
  value.radian = radianArray;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
