// Generated by llvmdsdl 0.2.3 (Rust backend).
// Source: uavcan.time.TimeSystem.0.1
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(deprecated)]

/// Time system enumeration.
/// The time system shall be the same for all masters in the network.
/// It cannot be changed while the network is running.
#[derive(Clone, Debug, PartialEq)]
pub struct uavcan_time_TimeSystem {
    pub value: u8,
}

impl Default for uavcan_time_TimeSystem {
    fn default() -> Self {
        Self {
            value: 0,
        }
    }
}

impl uavcan_time_TimeSystem {
    pub const FULL_NAME: &'static str = "uavcan.time.TimeSystem";
    pub const IS_DEPRECATED: bool = false;
    pub const FULL_NAME_AND_VERSION: &'static str = "uavcan.time.TimeSystem.0.1";
    pub const EXTENT_BYTES: usize = 1;
    pub const SERIALIZATION_BUFFER_SIZE_BYTES: usize = 1;
    pub const ZOH_ALIAS_ELIGIBLE: bool = false;
    pub const ZOH_ALIAS_REASON: &'static str = "sub-byte-field";
    pub const __LLVMDSDL_MEMORY_MODE: crate::dsdl_runtime::DsdlMemoryMode = crate::dsdl_runtime::DsdlMemoryMode::MaxInline;
    pub const __LLVMDSDL_INLINE_THRESHOLD_BYTES: usize = 256usize;
    /// Monotonic time since boot.
    /// Monotonic time is a time reference that doesn't change rate or make leaps.
    pub const MONOTONIC_SINCE_BOOT: u64 = 0;
    /// International Atomic Time; https://en.wikipedia.org/wiki/International_Atomic_Time.
    /// The timestamp value contains the number of microseconds elapsed since 1970-01-01T00:00:00Z TAI.
    /// TAI is always a fixed integer number of seconds ahead of GPS time.
    /// Systems that use GPS time as a reference should convert that to TAI by adding the fixed difference.
    /// GPS time is not supported for reasons of consistency across different positioning systems and applications.
    pub const TAI: u64 = 1;
    /// Application-specific time system of unknown properties.
    pub const APPLICATION_SPECIFIC: u64 = 15;

    pub fn serialize(&self, buffer: &mut [u8]) -> core::result::Result<usize, i8> {
        let mut offset_bits: usize = 0;
        let mlir_llvmdsdl_plan_capacity_check__uavcan_time_TimeSystem_0_1 = |capacity_bits: i64| -> i8 {
            if 8i64 > capacity_bits {
                -crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
            } else {
                crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS
            }
        };
        let mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_TimeSystem_0_1__0__ser = |value: u64| -> u64 { value & 15u64 };
        let _err_capacity = mlir_llvmdsdl_plan_capacity_check__uavcan_time_TimeSystem_0_1(buffer.len().saturating_mul(8) as i64);
        if _err_capacity != crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS {
            return Err(_err_capacity);
        }
        let _err0_ = crate::dsdl_runtime::set_uxx(buffer, offset_bits, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_TimeSystem_0_1__0__ser(self.value as u64), 4u8);
        if _err0_ < 0 { return Err(_err0_); }
        offset_bits += 4;
        while (offset_bits % 8usize) != 0 {
            let _err1_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
            if _err1_ < 0 { return Err(_err1_); }
            offset_bits += 1;
        }
        Ok(offset_bits / 8)
    }

    pub fn deserialize(&mut self, buffer: &[u8]) -> core::result::Result<usize, i8> {
        let capacity_bytes = buffer.len();
        let capacity_bits = capacity_bytes.saturating_mul(8);

        let mut offset_bits: usize = 0;
        let mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_TimeSystem_0_1__0__deser = |value: u64| -> u64 { value & 15u64 };
        let _raw2_ = crate::dsdl_runtime::get_u8(buffer, offset_bits, 4u8) as u64;
        self.value = mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_TimeSystem_0_1__0__deser(_raw2_) as u8;
        offset_bits += 4;
        offset_bits = (offset_bits + 7) & !7usize;
        Ok(crate::dsdl_runtime::choose_min(offset_bits, capacity_bits) / 8)
    }

    pub fn deserialize_with_consumed(&mut self, buffer: &[u8]) -> (i8, usize) {
        match self.deserialize(buffer) {
            Ok(consumed) => (0, consumed),
            Err(rc) => (rc, buffer.len()),
        }
    }

    pub fn try_deserialize_view<'a>(buffer: &'a [u8]) -> core::result::Result<(&'a [u8], usize), i8> {
        if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = "big") {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;
        if buffer.len() < required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);
        }
        Ok((&buffer[..required], required))
    }

    pub fn try_serialize_view(view_bytes: &[u8], buffer: &mut [u8]) -> core::result::Result<usize, i8> {
        if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = "big") {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;
        if view_bytes.len() != required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        if buffer.len() < required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);
        }
        buffer[..required].copy_from_slice(&view_bytes[..required]);
        Ok(required)
    }

    pub fn to_bytes(&self) -> core::result::Result<crate::dsdl_runtime::DsdlVec<u8>, i8> {
        let mut buffer = crate::dsdl_runtime::DsdlVec::<u8>::with_capacity(Self::SERIALIZATION_BUFFER_SIZE_BYTES);
        buffer.resize(Self::SERIALIZATION_BUFFER_SIZE_BYTES, 0u8);
        let used = self.serialize(&mut buffer)?;
        buffer.truncate(used);
        Ok(buffer)
    }

    pub fn from_bytes(buffer: &[u8]) -> core::result::Result<(Self, usize), i8> {
        let mut out = Self::default();
        let used = out.deserialize(buffer)?;
        Ok((out, used))
    }
}

