// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.metatransport.udp.Frame.0.1
import * as dsdlRuntime from "../../../dsdl_runtime";

import { deserializeSynchronizedTimestamp, serializeSynchronizedTimestamp } from "../../time/synchronized_timestamp_1_0";
import { deserializeEndpoint, serializeEndpoint } from "./endpoint_0_1";
import type { SynchronizedTimestamp } from "../../time/synchronized_timestamp_1_0";
import type { Endpoint } from "./endpoint_0_1";
export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.metatransport.udp.Frame";
export const DSDL_IS_DEPRECATED = true;
export const DSDL_VERSION_MAJOR = 0;
export const DSDL_VERSION_MINOR = 1;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "invalid-bit-length";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

// A generic UDP/IP frame.
// Jumboframes are supported in the interest of greater application compatibility.
/**
 * @deprecated uavcan.metatransport.udp.Frame.0.1 is marked @deprecated in its DSDL
 *   definition and is scheduled for removal; migrate to a newer version
 *   of this type.
 */
export interface Frame {
  timestamp: SynchronizedTimestamp;
  source: Endpoint;
  destination: Endpoint;
  data: Array<number>;
}

// Max jumbo frame 9 KiB, IP header min 20 B, UDP header 8 B.
export const FRAME_MTU = 9188;

export function serializeFrame(value: Frame): Uint8Array {
  const out = new Uint8Array(9262);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_udp_Frame_0_1 = (capacityBits: number): boolean => 74096 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_metatransport_udp_Frame_0_1__7__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 255n ? 255n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_metatransport_udp_Frame_0_1__7__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_metatransport_udp_Frame_0_1__7 = (value: number): boolean => (value >= 0) && (value <= 9188);

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_udp_Frame_0_1(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  const timestampAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let timestampAlignBit = offsetBits; timestampAlignBit < timestampAlignedOffsetBits; ++timestampAlignBit) {
    dsdlRuntime.setBit(out, timestampAlignBit, false);
  }
  offsetBits = timestampAlignedOffsetBits;
  const timestampBytes = serializeSynchronizedTimestamp(value.timestamp);
  dsdlRuntime.copyBits(out, offsetBits, timestampBytes, 0, 56);
  offsetBits += 56;
  for (let _PaddingBit = 0; _PaddingBit < 8; ++_PaddingBit) {
    dsdlRuntime.setBit(out, offsetBits + _PaddingBit, false);
  }
  offsetBits += 8;
  const sourceAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let sourceAlignBit = offsetBits; sourceAlignBit < sourceAlignedOffsetBits; ++sourceAlignBit) {
    dsdlRuntime.setBit(out, sourceAlignBit, false);
  }
  offsetBits = sourceAlignedOffsetBits;
  const sourceBytes = serializeEndpoint(value.source);
  dsdlRuntime.copyBits(out, offsetBits, sourceBytes, 0, 256);
  offsetBits += 256;
  const destinationAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let destinationAlignBit = offsetBits; destinationAlignBit < destinationAlignedOffsetBits; ++destinationAlignBit) {
    dsdlRuntime.setBit(out, destinationAlignBit, false);
  }
  offsetBits = destinationAlignedOffsetBits;
  const destinationBytes = serializeEndpoint(value.destination);
  dsdlRuntime.copyBits(out, offsetBits, destinationBytes, 0, 256);
  offsetBits += 256;
  const dataArray = value.data;
  if (!Array.isArray(dataArray)) {
    throw new Error("field 'data' expects an array");
  }
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_metatransport_udp_Frame_0_1__7(dataArray.length)) {
    throw new Error("field 'data' exceeds max length 9188");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 16, Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_metatransport_udp_Frame_0_1__7__ser(dataArray.length)), false);
  offsetBits += 16;
  for (let i = 0; i < dataArray.length; ++i) {
    dsdlRuntime.writeUnsigned(out, offsetBits, 8, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_metatransport_udp_Frame_0_1__7__ser(dataArray[i]), true);
    offsetBits += 8;
  }
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeFrame(bytes: Uint8Array): { value: Frame; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_metatransport_udp_Frame_0_1__7__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_metatransport_udp_Frame_0_1__7__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_metatransport_udp_Frame_0_1__7 = (value: number): boolean => (value >= 0) && (value <= 9188);

  const value = {} as Frame;
  let offsetBits = 0;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const timestampBytes = dsdlRuntime.extractBits(bytes, offsetBits, 56);
  value.timestamp = deserializeSynchronizedTimestamp(timestampBytes).value;
  offsetBits += 56;
  offsetBits += 8;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const sourceBytes = dsdlRuntime.extractBits(bytes, offsetBits, 256);
  value.source = deserializeEndpoint(sourceBytes).value;
  offsetBits += 256;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const destinationBytes = dsdlRuntime.extractBits(bytes, offsetBits, 256);
  value.destination = deserializeEndpoint(destinationBytes).value;
  offsetBits += 256;
  const dataLengthRaw = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 16));
  offsetBits += 16;
  const dataLength = Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_metatransport_udp_Frame_0_1__7__deser(dataLengthRaw));
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_metatransport_udp_Frame_0_1__7(dataLength)) {
    throw new Error("decoded length for field 'data' exceeds max length 9188");
  }
  const dataArray: Array<number> = new Array(dataLength);
  for (let i = 0; i < dataLength; ++i) {
    const dataItemRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 8);
    dataArray[i] = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_metatransport_udp_Frame_0_1__7__deser(dataItemRaw));
    offsetBits += 8;
  }
  value.data = dataArray;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
