// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.primitive.array.Bit.1.0
import * as dsdlRuntime from "../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.primitive.array.Bit";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "sub-byte-field";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

// 2048 bits + 11 bit length + 4 bit padding = 2064 bits = 258 bytes
export interface Bit {
  value: Array<boolean>;
}


export function serializeBit(value: Bit): Uint8Array {
  const out = new Uint8Array(258);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_array_Bit_1_0 = (capacityBits: number): boolean => 2064 <= capacityBits;
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Bit_1_0__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Bit_1_0__0 = (value: number): boolean => (value >= 0) && (value <= 2048);

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_array_Bit_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  const valueArray = value.value;
  if (!Array.isArray(valueArray)) {
    throw new Error("field 'value' expects an array");
  }
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Bit_1_0__0(valueArray.length)) {
    throw new Error("field 'value' exceeds max length 2048");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 16, Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Bit_1_0__0__ser(valueArray.length)), false);
  offsetBits += 16;
  for (let i = 0; i < valueArray.length; ++i) {
    dsdlRuntime.setBit(out, offsetBits, valueArray[i]);
    offsetBits += 1;
  }
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeBit(bytes: Uint8Array): { value: Bit; consumed: number } {
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Bit_1_0__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Bit_1_0__0 = (value: number): boolean => (value >= 0) && (value <= 2048);

  const value = {} as Bit;
  let offsetBits = 0;
  const valueLengthRaw = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 16));
  offsetBits += 16;
  const valueLength = Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Bit_1_0__0__deser(valueLengthRaw));
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Bit_1_0__0(valueLength)) {
    throw new Error("decoded length for field 'value' exceeds max length 2048");
  }
  const valueArray: Array<boolean> = new Array(valueLength);
  for (let i = 0; i < valueLength; ++i) {
    valueArray[i] = dsdlRuntime.getBit(bytes, offsetBits);
    offsetBits += 1;
  }
  value.value = valueArray;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
