// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.primitive.array.Natural64.1.0
import * as dsdlRuntime from "../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.primitive.array.Natural64";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "variable-array";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

export interface Natural64 {
  value: Array<bigint>;
}


export function serializeNatural64(value: Natural64): Uint8Array {
  const out = new Uint8Array(257);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_array_Natural64_1_0 = (capacityBits: number): boolean => 2056 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_primitive_array_Natural64_1_0__0__ser = (value: number | bigint): number | bigint => value;
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Natural64_1_0__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Natural64_1_0__0 = (value: number): boolean => (value >= 0) && (value <= 32);

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_array_Natural64_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  const valueArray = value.value;
  if (!Array.isArray(valueArray)) {
    throw new Error("field 'value' expects an array");
  }
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Natural64_1_0__0(valueArray.length)) {
    throw new Error("field 'value' exceeds max length 32");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 8, Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Natural64_1_0__0__ser(valueArray.length)), false);
  offsetBits += 8;
  for (let i = 0; i < valueArray.length; ++i) {
    dsdlRuntime.writeUnsigned(out, offsetBits, 64, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_primitive_array_Natural64_1_0__0__ser(valueArray[i]), true);
    offsetBits += 64;
  }
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeNatural64(bytes: Uint8Array): { value: Natural64; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_primitive_array_Natural64_1_0__0__deser = (value: number | bigint): number | bigint => value;
  const mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Natural64_1_0__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Natural64_1_0__0 = (value: number): boolean => (value >= 0) && (value <= 32);

  const value = {} as Natural64;
  let offsetBits = 0;
  const valueLengthRaw = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 8));
  offsetBits += 8;
  const valueLength = Number(mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Natural64_1_0__0__deser(valueLengthRaw));
  if (!mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Natural64_1_0__0(valueLength)) {
    throw new Error("decoded length for field 'value' exceeds max length 32");
  }
  const valueArray: Array<bigint> = new Array(valueLength);
  for (let i = 0; i < valueLength; ++i) {
    const valueItemRaw = dsdlRuntime.readUnsignedBigInt(bytes, offsetBits, 64);
    valueArray[i] = BigInt(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_primitive_array_Natural64_1_0__0__deser(valueItemRaw));
    offsetBits += 64;
  }
  value.value = valueArray;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
