// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.si.sample.length.WideVector3.1.0

package length

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
	pkg_uavcan_time "llvmdsdl_generated/uavcan/time"
)

const WIDE_VECTOR3_FULL_NAME = "uavcan.si.sample.length.WideVector3"
const WIDE_VECTOR3_IS_DEPRECATED = false
const WIDE_VECTOR3_FULL_NAME_AND_VERSION = "uavcan.si.sample.length.WideVector3.1.0"
const WIDE_VECTOR3_EXTENT_BYTES = 31
const WIDE_VECTOR3_SERIALIZATION_BUFFER_SIZE_BYTES = 31
const WIDE_VECTOR3_ZOH_ALIAS_ELIGIBLE = false
const WIDE_VECTOR3_ZOH_ALIAS_REASON = "invalid-bit-length"

type WideVector3 struct {
	Timestamp pkg_uavcan_time.SynchronizedTimestamp
	Meter     [3]float64
}

func (obj *WideVector3) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_si_sample_length_WideVector3_1_0 := func(capacityBits int64) int8 {
		if 248 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_length_WideVector3_1_0__2__ser := func(value float64) float64 { return value }
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_si_sample_length_WideVector3_1_0(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	for (offsetBits % 8) != 0 {
		_err0_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err0_ < 0 {
			return _err0_, 0
		}
		offsetBits++
	}
	_sizeBytes1_ := 7
	_start2_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_end3_ := dsdlruntime.ChooseMin(_start2_+_sizeBytes1_, len(buffer))
	_rc4_, _consumed5_ := obj.Timestamp.Serialize(buffer[_start2_:_end3_])
	if _rc4_ < 0 {
		return _rc4_, 0
	}
	_sizeBytes1_ = _consumed5_
	offsetBits += _sizeBytes1_ * 8
	for _index6_ := 0; _index6_ < 3; _index6_++ {
		_err7_ := dsdlruntime.SetF64(buffer, offsetBits, mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_length_WideVector3_1_0__2__ser(float64(obj.Meter[_index6_])))
		if _err7_ < 0 {
			return _err7_, 0
		}
		offsetBits += 64
	}
	for (offsetBits % 8) != 0 {
		_err8_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err8_ < 0 {
			return _err8_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *WideVector3) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_length_WideVector3_1_0__2__deser := func(value float64) float64 { return value }
	offsetBits = (offsetBits + 7) & ^7
	_start9_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_rc10_, _consumed11_ := obj.Timestamp.Deserialize(buffer[_start9_:len(buffer)])
	if _rc10_ < 0 {
		return _rc10_, 0
	}
	offsetBits += _consumed11_ * 8
	_count12_ := 3
	for _index13_ := 0; _index13_ < _count12_; _index13_++ {
		obj.Meter[_index13_] = mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_length_WideVector3_1_0__2__deser(dsdlruntime.GetF64(buffer, offsetBits))
		offsetBits += 64
	}
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}
