// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.file.List.0.2

package file

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const LIST_REQUEST_FULL_NAME = "uavcan.file.List.Request"
const LIST_REQUEST_IS_DEPRECATED = false
const LIST_REQUEST_FULL_NAME_AND_VERSION = "uavcan.file.List.Request.0.2"
const LIST_REQUEST_EXTENT_BYTES = 300
const LIST_REQUEST_SERIALIZATION_BUFFER_SIZE_BYTES = 264
const LIST_REQUEST_ZOH_ALIAS_ELIGIBLE = false
const LIST_REQUEST_ZOH_ALIAS_REASON = "invalid-bit-length"

// This service can be used to list a remote directory, one entry per request.
//
// The client should query each entry independently, iterating 'entry_index' from 0 until the last entry.
// When the index reaches the number of elements in the directory, the server will report that there is
// no such entry by returning an empty name.
//
// The field entry_index shall be applied to an ordered list of directory entries (e.g. alphabetically ordered).
// The exact sorting criteria does not matter as long as it provides the same ordering for subsequent service calls.
//
// Observe that this listing operation is fundamentally non-atomic. The caller shall beware of possible race conditions
// and is responsible for handling them properly. Particularly, consider what happens if a new item is inserted into
// the directory between two subsequent calls: if the item happened to be inserted at the index that is lower than the
// index of the next request, the next returned item (or several, if more items were inserted) will repeat the ones
// that were listed earlier. The caller should handle that properly, either by ignoring the repeated items or by
// restarting the listing operation from the beginning (index 0).
type List_Request struct {
	EntryIndex    uint32
	DirectoryPath Path
}

func (obj *List_Request) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__request := func(capacityBits int64) int8 {
		if 2112 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__ser := func(value uint64) uint64 {
		if value > uint64(4294967295) {
			return uint64(4294967295)
		}
		return value
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__request(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_err0_ := dsdlruntime.SetUxx(buffer, offsetBits, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__ser(uint64(obj.EntryIndex)), 32)
	if _err0_ < 0 {
		return _err0_, 0
	}
	offsetBits += 32
	_err1_ := dsdlruntime.SetUxx(buffer, offsetBits, 0, 32)
	if _err1_ < 0 {
		return _err1_, 0
	}
	offsetBits += 32
	for (offsetBits % 8) != 0 {
		_err2_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err2_ < 0 {
			return _err2_, 0
		}
		offsetBits++
	}
	_sizeBytes3_ := 256
	_start4_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_end5_ := dsdlruntime.ChooseMin(_start4_+_sizeBytes3_, len(buffer))
	_rc6_, _consumed7_ := obj.DirectoryPath.Serialize(buffer[_start4_:_end5_])
	if _rc6_ < 0 {
		return _rc6_, 0
	}
	_sizeBytes3_ = _consumed7_
	offsetBits += _sizeBytes3_ * 8
	for (offsetBits % 8) != 0 {
		_err8_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err8_ < 0 {
			return _err8_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *List_Request) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__deser := func(value uint64) uint64 { return value & uint64(4294967295) }
	_raw9_ := uint64(dsdlruntime.GetU64(buffer, offsetBits, 32))
	obj.EntryIndex = uint32(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_file_List_0_2__request__0__deser(_raw9_))
	offsetBits += 32
	offsetBits += 32
	offsetBits = (offsetBits + 7) & ^7
	_start10_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_rc11_, _consumed12_ := obj.DirectoryPath.Deserialize(buffer[_start10_:len(buffer)])
	if _rc11_ < 0 {
		return _rc11_, 0
	}
	offsetBits += _consumed12_ * 8
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}

const LIST_RESPONSE_FULL_NAME = "uavcan.file.List.Response"
const LIST_RESPONSE_IS_DEPRECATED = false
const LIST_RESPONSE_FULL_NAME_AND_VERSION = "uavcan.file.List.Response.0.2"
const LIST_RESPONSE_EXTENT_BYTES = 300
const LIST_RESPONSE_SERIALIZATION_BUFFER_SIZE_BYTES = 260
const LIST_RESPONSE_ZOH_ALIAS_ELIGIBLE = false
const LIST_RESPONSE_ZOH_ALIAS_REASON = "invalid-bit-length"

// This service can be used to list a remote directory, one entry per request.
//
// The client should query each entry independently, iterating 'entry_index' from 0 until the last entry.
// When the index reaches the number of elements in the directory, the server will report that there is
// no such entry by returning an empty name.
//
// The field entry_index shall be applied to an ordered list of directory entries (e.g. alphabetically ordered).
// The exact sorting criteria does not matter as long as it provides the same ordering for subsequent service calls.
//
// Observe that this listing operation is fundamentally non-atomic. The caller shall beware of possible race conditions
// and is responsible for handling them properly. Particularly, consider what happens if a new item is inserted into
// the directory between two subsequent calls: if the item happened to be inserted at the index that is lower than the
// index of the next request, the next returned item (or several, if more items were inserted) will repeat the ones
// that were listed earlier. The caller should handle that properly, either by ignoring the repeated items or by
// restarting the listing operation from the beginning (index 0).
type List_Response struct {
	// The base name of the referenced entry, i.e., relative to the outer directory.
	// The outer directory path is not included to conserve bandwidth.
	// Empty if such entry does not exist.
	//
	// For example, suppose there is a file "/foo/bar/baz.bin". Listing the directory with the path "/foo/bar/" (the slash
	// at the end is optional) at the index 0 will return "baz.bin". Listing the same directory at the index 1 (or any
	// higher) will return an empty name "", indicating that the caller has reached the end of the list.
	EntryBaseName Path
}

func (obj *List_Response) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__response := func(capacityBits int64) int8 {
		if 2080 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_file_List_0_2__response(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_err0_ := dsdlruntime.SetUxx(buffer, offsetBits, 0, 32)
	if _err0_ < 0 {
		return _err0_, 0
	}
	offsetBits += 32
	for (offsetBits % 8) != 0 {
		_err1_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err1_ < 0 {
			return _err1_, 0
		}
		offsetBits++
	}
	_sizeBytes2_ := 256
	_start3_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_end4_ := dsdlruntime.ChooseMin(_start3_+_sizeBytes2_, len(buffer))
	_rc5_, _consumed6_ := obj.EntryBaseName.Serialize(buffer[_start3_:_end4_])
	if _rc5_ < 0 {
		return _rc5_, 0
	}
	_sizeBytes2_ = _consumed6_
	offsetBits += _sizeBytes2_ * 8
	for (offsetBits % 8) != 0 {
		_err7_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err7_ < 0 {
			return _err7_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *List_Response) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	offsetBits += 32
	offsetBits = (offsetBits + 7) & ^7
	_start8_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_rc9_, _consumed10_ := obj.EntryBaseName.Deserialize(buffer[_start8_:len(buffer)])
	if _rc9_ < 0 {
		return _rc9_, 0
	}
	offsetBits += _consumed10_ * 8
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}

type List = List_Request

const LIST_ZOH_ALIAS_ELIGIBLE = LIST_REQUEST_ZOH_ALIAS_ELIGIBLE
const LIST_ZOH_ALIAS_REASON = LIST_REQUEST_ZOH_ALIAS_REASON
