// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.file.Modify.1.1

package file

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const MODIFY_REQUEST_FULL_NAME = "uavcan.file.Modify.Request"
const MODIFY_REQUEST_IS_DEPRECATED = false
const MODIFY_REQUEST_FULL_NAME_AND_VERSION = "uavcan.file.Modify.Request.1.1"
const MODIFY_REQUEST_EXTENT_BYTES = 600
const MODIFY_REQUEST_SERIALIZATION_BUFFER_SIZE_BYTES = 516
const MODIFY_REQUEST_ZOH_ALIAS_ELIGIBLE = false
const MODIFY_REQUEST_ZOH_ALIAS_REASON = "sub-byte-field"

// Manipulate a remote file system entry. Applies to files, directories, and links alike.
// If the remote entry is a directory, all nested entries will be affected, too.
//
// The server should perform all operations atomically, unless atomicity is not supported by
// the underlying file system.
//
// Atomic copying can be effectively employed by remote nodes before reading or after writing
// the file to minimize the possibility of race conditions.
// For example, before reading a large file from the server, the cilent might opt to create
// a temporary copy of it first, then read the copy, and delete it upon completion. Likewise,
// a similar strategy can be employed for writing, where the file is first written at a
// temporary location, and then moved to its final destination. These approaches, however,
// may lead to creation of dangling temporary files if the client failed to dispose of them
// properly, so that risk should be taken into account.
//
// Move/Copy
//
//	Specify the source path and the destination path.
//	If the source does not exist, the operation will fail.
//	Set the preserve_source flag to copy rather than move.
//	If the destination exists and overwrite_destination is not set, the operation will fail.
//	If the target path includes non-existent directories, they will be created (like "mkdir -p").
//
// Touch
//
//	Specify the destination path and make the source path empty.
//	If the path exists (file/directory/link), its modification time will be updated.
//	If the path does not exist, an empty file will be created.
//	If the target path includes non-existent directories, they will be created (like "mkdir -p").
//	Flags are ignored.
//
// Remove
//
//	Specify the source path (file/directory/link) and make the destination path empty.
//	Fails if the path does not exist.
//	Flags are ignored.
type Modify_Request struct {
	// Do not remove the source. Used to copy instead of moving.
	PreserveSource bool
	// If the destination exists, remove it beforehand.
	OverwriteDestination bool
	Source               Path
	Destination          Path
}

func (obj *Modify_Request) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_file_Modify_1_1__request := func(capacityBits int64) int8 {
		if 4128 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_file_Modify_1_1__request(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_err0_ := dsdlruntime.SetBit(buffer, offsetBits, obj.PreserveSource)
	if _err0_ < 0 {
		return _err0_, 0
	}
	offsetBits += 1
	_err1_ := dsdlruntime.SetBit(buffer, offsetBits, obj.OverwriteDestination)
	if _err1_ < 0 {
		return _err1_, 0
	}
	offsetBits += 1
	_err2_ := dsdlruntime.SetUxx(buffer, offsetBits, 0, 30)
	if _err2_ < 0 {
		return _err2_, 0
	}
	offsetBits += 30
	for (offsetBits % 8) != 0 {
		_err3_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err3_ < 0 {
			return _err3_, 0
		}
		offsetBits++
	}
	_sizeBytes4_ := 256
	_start5_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_end6_ := dsdlruntime.ChooseMin(_start5_+_sizeBytes4_, len(buffer))
	_rc7_, _consumed8_ := obj.Source.Serialize(buffer[_start5_:_end6_])
	if _rc7_ < 0 {
		return _rc7_, 0
	}
	_sizeBytes4_ = _consumed8_
	offsetBits += _sizeBytes4_ * 8
	for (offsetBits % 8) != 0 {
		_err9_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err9_ < 0 {
			return _err9_, 0
		}
		offsetBits++
	}
	_sizeBytes10_ := 256
	_start11_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_end12_ := dsdlruntime.ChooseMin(_start11_+_sizeBytes10_, len(buffer))
	_rc13_, _consumed14_ := obj.Destination.Serialize(buffer[_start11_:_end12_])
	if _rc13_ < 0 {
		return _rc13_, 0
	}
	_sizeBytes10_ = _consumed14_
	offsetBits += _sizeBytes10_ * 8
	for (offsetBits % 8) != 0 {
		_err15_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err15_ < 0 {
			return _err15_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *Modify_Request) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	obj.PreserveSource = dsdlruntime.GetBit(buffer, offsetBits)
	offsetBits += 1
	obj.OverwriteDestination = dsdlruntime.GetBit(buffer, offsetBits)
	offsetBits += 1
	offsetBits += 30
	offsetBits = (offsetBits + 7) & ^7
	_start16_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_rc17_, _consumed18_ := obj.Source.Deserialize(buffer[_start16_:len(buffer)])
	if _rc17_ < 0 {
		return _rc17_, 0
	}
	offsetBits += _consumed18_ * 8
	offsetBits = (offsetBits + 7) & ^7
	_start19_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_rc20_, _consumed21_ := obj.Destination.Deserialize(buffer[_start19_:len(buffer)])
	if _rc20_ < 0 {
		return _rc20_, 0
	}
	offsetBits += _consumed21_ * 8
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}

const MODIFY_RESPONSE_FULL_NAME = "uavcan.file.Modify.Response"
const MODIFY_RESPONSE_IS_DEPRECATED = false
const MODIFY_RESPONSE_FULL_NAME_AND_VERSION = "uavcan.file.Modify.Response.1.1"
const MODIFY_RESPONSE_EXTENT_BYTES = 48
const MODIFY_RESPONSE_SERIALIZATION_BUFFER_SIZE_BYTES = 2
const MODIFY_RESPONSE_ZOH_ALIAS_ELIGIBLE = false
const MODIFY_RESPONSE_ZOH_ALIAS_REASON = "invalid-bit-length"

// Manipulate a remote file system entry. Applies to files, directories, and links alike.
// If the remote entry is a directory, all nested entries will be affected, too.
//
// The server should perform all operations atomically, unless atomicity is not supported by
// the underlying file system.
//
// Atomic copying can be effectively employed by remote nodes before reading or after writing
// the file to minimize the possibility of race conditions.
// For example, before reading a large file from the server, the cilent might opt to create
// a temporary copy of it first, then read the copy, and delete it upon completion. Likewise,
// a similar strategy can be employed for writing, where the file is first written at a
// temporary location, and then moved to its final destination. These approaches, however,
// may lead to creation of dangling temporary files if the client failed to dispose of them
// properly, so that risk should be taken into account.
//
// Move/Copy
//
//	Specify the source path and the destination path.
//	If the source does not exist, the operation will fail.
//	Set the preserve_source flag to copy rather than move.
//	If the destination exists and overwrite_destination is not set, the operation will fail.
//	If the target path includes non-existent directories, they will be created (like "mkdir -p").
//
// Touch
//
//	Specify the destination path and make the source path empty.
//	If the path exists (file/directory/link), its modification time will be updated.
//	If the path does not exist, an empty file will be created.
//	If the target path includes non-existent directories, they will be created (like "mkdir -p").
//	Flags are ignored.
//
// Remove
//
//	Specify the source path (file/directory/link) and make the destination path empty.
//	Fails if the path does not exist.
//	Flags are ignored.
type Modify_Response struct {
	Error Error
}

func (obj *Modify_Response) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_file_Modify_1_1__response := func(capacityBits int64) int8 {
		if 16 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_file_Modify_1_1__response(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	for (offsetBits % 8) != 0 {
		_err0_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err0_ < 0 {
			return _err0_, 0
		}
		offsetBits++
	}
	_sizeBytes1_ := 2
	_start2_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_end3_ := dsdlruntime.ChooseMin(_start2_+_sizeBytes1_, len(buffer))
	_rc4_, _consumed5_ := obj.Error.Serialize(buffer[_start2_:_end3_])
	if _rc4_ < 0 {
		return _rc4_, 0
	}
	_sizeBytes1_ = _consumed5_
	offsetBits += _sizeBytes1_ * 8
	for (offsetBits % 8) != 0 {
		_err6_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err6_ < 0 {
			return _err6_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *Modify_Response) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	offsetBits = (offsetBits + 7) & ^7
	_start7_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_rc8_, _consumed9_ := obj.Error.Deserialize(buffer[_start7_:len(buffer)])
	if _rc8_ < 0 {
		return _rc8_, 0
	}
	offsetBits += _consumed9_ * 8
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}

type Modify = Modify_Request

const MODIFY_ZOH_ALIAS_ELIGIBLE = MODIFY_REQUEST_ZOH_ALIAS_ELIGIBLE
const MODIFY_ZOH_ALIAS_REASON = MODIFY_REQUEST_ZOH_ALIAS_REASON
