//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements C++ backend code emission from lowered DSDL modules.
///
/// The implementation translates lowered section plans into C++ encode and decode routines plus supporting type
/// wrappers.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/CppEmitter.h"
#include "llvmdsdl/CodeGen/EmbeddedRuntimeSources.h"

#include <llvm/ADT/StringRef.h>
#include <llvm/Support/Error.h>
#include <cassert>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <optional>
#include <sstream>
#include <unordered_map>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <system_error>
#include <variant>

#include "llvmdsdl/CodeGen/ArrayWirePlan.h"
#include "llvmdsdl/CodeGen/CodegenDiagnosticText.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionDependencies.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/CodeGen/EmitStep.h"
#include "llvmdsdl/CodeGen/EmitTrace.h"
#include "llvmdsdl/CodeGen/HelperBindingRender.h"
#include "llvmdsdl/CodeGen/HelperSymbolResolver.h"
#include "llvmdsdl/CodeGen/LoweredRenderIR.h"
#include "llvmdsdl/CodeGen/LoweredFactsLookup.h"
#include "llvmdsdl/CodeGen/MlirLoweredFacts.h"
#include "llvmdsdl/CodeGen/NamingPolicy.h"
#include "llvmdsdl/CodeGen/HelperBindingNaming.h"
#include "llvmdsdl/CodeGen/NativeEmitterTraversal.h"
#include "llvmdsdl/CodeGen/NativeFunctionSkeleton.h"
#include "llvmdsdl/CodeGen/SerDesHelperDescriptors.h"
#include "llvmdsdl/CodeGen/StorageTypeTokens.h"
#include "llvmdsdl/CodeGen/TypeStorage.h"
#include "llvmdsdl/CodeGen/WireLayoutFacts.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/CodeGen/SectionHelperBindingPlan.h"
#include "llvmdsdl/CodeGen/SerDesStatementPlan.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/BitLengthSet.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Support/Rational.h"
#include "llvmdsdl/Version.h"
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl
{
class DiagnosticEngine;

namespace
{

std::string sanitizeMacroToken(std::string token)
{
    for (char& c : token)
    {
        if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '_'))
        {
            c = '_';
        }
        else
        {
            c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
        }
    }
    if (!token.empty() && std::isdigit(static_cast<unsigned char>(token.front())))
    {
        token.insert(token.begin(), '_');
    }
    return token;
}

std::string headerFileName(const DiscoveredDefinition& info)
{
    return llvm::formatv("{0}_{1}_{2}.hpp", info.shortName, info.majorVersion, info.minorVersion).str();
}

std::string headerGuard(const DiscoveredDefinition& info)
{
    std::string g = "LLVMDSDL_CPP_" + info.fullName + "_" + std::to_string(info.majorVersion) + "_" +
                    std::to_string(info.minorVersion) + "_HPP";
    for (char& c : g)
    {
        if (!std::isalnum(static_cast<unsigned char>(c)))
        {
            c = '_';
        }
        else
        {
            c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
        }
    }
    return g;
}

std::string valueToCppExpr(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(ConstantLiteralLanguage::Cpp, value, makeConstantTypeInfo(type));
}

std::string unsignedStorageType(const std::uint32_t bitLength)
{
    return renderUnsignedStorageToken(StorageTokenLanguage::Cpp, bitLength);
}

std::string signedStorageType(const std::uint32_t bitLength)
{
    return renderSignedStorageToken(StorageTokenLanguage::Cpp, bitLength);
}

std::string unsignedGetter(const std::uint32_t bitLength)
{
    return "dsdl_runtime_get_u" + std::string(scalarWidthSuffix(bitLength));
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return llvm::formatv("// Generated by llvmdsdl {0} ({1}).", llvmdsdl::kVersionString, detail).str();
}

void emitAttachedDocCpp(std::ostringstream& out, const int indent, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        out << std::string(static_cast<std::size_t>(indent) * 2U, ' ') << "// " << line.text << '\n';
    }
}

std::string cppNamespacePath(const std::vector<std::string>& components)
{
    std::string out;
    for (const auto& component : components)
    {
        if (!out.empty())
        {
            out += "::";
        }
        out += codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, component);
    }
    return out;
}

void emitNamespaceOpen(std::ostringstream& out, const std::vector<std::string>& components)
{
    if (components.empty())
    {
        return;
    }
    for (const auto& component : components)
    {
        out << "namespace " << codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, component) << " {\n";
    }
    out << "\n";
}

void emitNamespaceClose(std::ostringstream& out, const std::vector<std::string>& components)
{
    if (components.empty())
    {
        return;
    }
    out << "\n";
    for (auto it = components.rbegin(); it != components.rend(); ++it)
    {
        out << "} // namespace " << codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, *it) << "\n";
    }
}

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule& semantic, const bool emitDeprecationAttributes)
        : index_(semantic)
        , emitDeprecationAttributes_(emitDeprecationAttributes)
    {
        for (const auto& def : semantic.definitions)
        {
            versionCountByFullName_[def.info.fullName] += 1U;
        }
    }

    /// @brief True when `@deprecated` definitions should carry a language-native attribute.
    bool emitDeprecationAttributes() const
    {
        return emitDeprecationAttributes_;
    }

    /// @brief Attaches an emit-order trace sink (for the emit-order verifier). Null (default) disables tracing at zero cost.
    void setTraceSink(EmitTraceSink* const sink) { traceSink_ = sink; }

    /// @brief Records one abstract emit op into the attached sink (no-op when unattached).
    template <typename PayloadT = std::int64_t>
    void trace(const EmitTraceOp op, const PayloadT payload = -1) const
    {
        emitTrace(traceSink_, op, static_cast<std::int64_t>(payload));
    }

    /// @brief Marks the start of one (type, direction) trace segment (no-op when unattached).
    void traceSection(const std::string& canonicalName, const EmitTraceDirection direction) const
    {
        emitTraceSection(traceSink_, canonicalName, direction);
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

    std::string cppTypeName(const DiscoveredDefinition& info) const
    {
        std::string out = codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, info.shortName);
        const auto  it  = versionCountByFullName_.find(info.fullName);
        if (it != versionCountByFullName_.end() && it->second > 1U)
        {
            out += "_" + std::to_string(info.majorVersion) + "_" + std::to_string(info.minorVersion);
        }
        return out;
    }

    std::string cppTypeName(const SemanticDefinition& def) const
    {
        return cppTypeName(def.info);
    }

    std::string cppTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return cppTypeName(*def);
        }

        std::string out = codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, ref.shortName);
        out += "_" + std::to_string(ref.majorVersion) + "_" + std::to_string(ref.minorVersion);
        return out;
    }

    std::string cppQualifiedTypeName(const SemanticDefinition& def) const
    {
        std::string out = "::";
        const auto  ns  = cppNamespacePath(def.info.namespaceComponents);
        if (!ns.empty())
        {
            out += ns + "::";
        }
        out += cppTypeName(def);
        return out;
    }

    std::string cppQualifiedTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return cppQualifiedTypeName(*def);
        }

        std::string out = "::";
        const auto  ns  = cppNamespacePath(ref.namespaceComponents);
        if (!ns.empty())
        {
            out += ns + "::";
        }
        out += cppTypeName(ref);
        return out;
    }

    std::string relativeHeaderPath(const SemanticDefinition& def) const
    {
        std::filesystem::path p;
        for (const auto& ns : def.info.namespaceComponents)
        {
            p /= ns;
        }
        p /= headerFileName(def.info);
        return p.generic_string();
    }

private:
    DefinitionIndex                              index_;
    std::unordered_map<std::string, std::size_t> versionCountByFullName_;
    EmitTraceSink*                               traceSink_ = nullptr;
    bool                                         emitDeprecationAttributes_{false};
};

void emitLine(std::ostringstream& out, const int indent, const std::string& line)
{
    out << std::string(static_cast<std::size_t>(indent) * 2U, ' ') << line << '\n';
}

enum class CppFlavor
{
    Std,
    Pmr,
    Autosar,
};

bool isPmrFlavor(const CppFlavor flavor)
{
    return flavor == CppFlavor::Pmr;
}

bool isAutosarFlavor(const CppFlavor flavor)
{
    return flavor == CppFlavor::Autosar;
}

class FunctionBodyEmitter final
{
public:
    explicit FunctionBodyEmitter(const EmitterContext& ctx, const CppFlavor flavor)
        : ctx_(ctx)
        , flavor_(flavor)
    {
    }

    /// @brief Records one abstract emit op via the shared EmitterContext sink (no-op when unattached).
    template <typename PayloadT = std::int64_t>
    void trace(const EmitTraceOp op, const PayloadT payload = -1) const
    {
        ctx_.trace(op, payload);
    }

    void emitSerializeFunction(std::ostringstream&              out,
                               const std::string&               typeName,
                               const SemanticSection&           section,
                               const LoweredSectionFacts* const sectionFacts)
    {
        emitLine(out,
                 0,
                 "inline std::int8_t " + typeName + "__serialize_(const " + typeName +
                     "* const obj, std::uint8_t* const buffer, std::size_t* const "
                     "inout_buffer_size_bytes" +
                     (isPmrFlavor(flavor_) ? ", ::llvmdsdl::cpp::MemoryResource* const memory_resource" : "") + ")");
        emitLine(out, 0, "{");
        emitLine(out, 1, "if ((obj == nullptr) || (buffer == nullptr) || (inout_buffer_size_bytes == nullptr)) {");
        emitLine(out, 2, "return static_cast<std::int8_t>(-DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
        emitLine(out, 1, "}");
        if (isPmrFlavor(flavor_))
        {
            emitLine(out,
                     1,
                     "::llvmdsdl::cpp::MemoryResource* const effective_memory_resource = "
                     "(memory_resource != nullptr) ? memory_resource : obj->_memory_resource;");
            emitLine(out, 1, "(void)effective_memory_resource;");
        }
        emitLine(out, 1, "const std::size_t capacity_bytes = *inout_buffer_size_bytes;");
        emitLine(out, 1, "std::size_t offset_bits = 0U;");
        const auto emitted = emitNativeFunctionSkeleton(
            section,
            sectionFacts,
            HelperBindingDirection::Serialize,
            NativeFunctionSkeletonCallbacks{
                [this, &out](const SectionHelperBindingPlan& helperBindings) {
                    emitSerializeMlirHelperBindings(out, helperBindings, 1);
                },
                [&out](const std::string& missingHelperRequirement) {
                    emitLine(out, 1, "/* missing lowered helper contract: " + missingHelperRequirement + " */");
                    emitLine(out,
                             1,
                             "return static_cast<std::int8_t>("
                             "-DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
                },
                [this, &out](const SectionHelperBindingPlan& helperBindings) {
                    const auto capacityHelper = helperBindingName(helperBindings.capacityCheck->symbol);
                    const auto errCapacity    = nextName("err_capacity");
                    emitLine(out,
                             1,
                             "const std::int8_t " + errCapacity + " = " + capacityHelper +
                                 "(static_cast<std::int64_t>(capacity_bytes * 8U));");
                    emitLine(out, 1, "if (" + errCapacity + " != static_cast<std::int8_t>(DSDL_RUNTIME_SUCCESS)) {");
                    emitLine(out, 2, "return " + errCapacity + ";");
                    emitLine(out, 1, "}");
                },
                [this, &out, &section, sectionFacts](const LoweredBodyRenderIR& renderIR) {
                    NativeEmitterTraversalCallbacks callbacks;
                    callbacks.onUnionDispatch = [this, &out, &section, sectionFacts, &renderIR](
                                                    const std::vector<PlannedFieldStep>& unionBranches) {
                        emitSerializeUnion(out,
                                           section,
                                           unionBranches,
                                           "obj",
                                           1,
                                           sectionFacts,
                                           renderIR.helperBindings);
                    };
                    callbacks.onFieldAlignment = [this, &out](const std::int64_t alignmentBits) {
                        emitAlignSerialize(out, alignmentBits, 1);
                    };
                    callbacks.onField = [this, &out](const PlannedFieldStep& fieldStep) {
                        const auto* const field = fieldStep.field;
                        emitSerializeValue(out,
                                           field->resolvedType,
                                           "obj->" + codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, field->name),
                                           1,
                                           fieldStep.arrayLengthPrefixBits,
                                           fieldStep.fieldFacts);
                    };
                    callbacks.onPaddingAlignment = [this, &out](const std::int64_t alignmentBits) {
                        emitAlignSerialize(out, alignmentBits, 1);
                    };
                    callbacks.onPadding = [this, &out](const PlannedFieldStep& fieldStep) {
                        const auto* const field = fieldStep.field;
                        emitSerializePadding(out, field->resolvedType, 1);
                    };
                    return callbacks;
                },
                [this, &out]() {
                    emitAlignSerialize(out, 8, 1);
                    emitLine(out,
                             1,
                             "*inout_buffer_size_bytes = "
                             "static_cast<std::size_t>(offset_bits / 8U);");
                    emitLine(out, 1, "return static_cast<std::int8_t>(DSDL_RUNTIME_SUCCESS);");
                }});
        if (!emitted)
        {
            emitLine(out, 0, "}");
            out << "\n";
            return;
        }
        emitLine(out, 0, "}");
        out << "\n";
    }

    void emitDeserializeFunction(std::ostringstream&              out,
                                 const std::string&               typeName,
                                 const SemanticSection&           section,
                                 const LoweredSectionFacts* const sectionFacts)
    {
        emitLine(out,
                 0,
                 "inline std::int8_t " + typeName + "__deserialize_(" + typeName +
                     "* const out_obj, const std::uint8_t* buffer, std::size_t* const "
                     "inout_buffer_size_bytes" +
                     (isPmrFlavor(flavor_) ? ", ::llvmdsdl::cpp::MemoryResource* const memory_resource" : "") + ")");
        emitLine(out, 0, "{");
        emitLine(out,
                 1,
                 "if ((out_obj == nullptr) || (inout_buffer_size_bytes == nullptr) || ((buffer == nullptr) && (0U != "
                 "*inout_buffer_size_bytes))) {");
        emitLine(out, 2, "return static_cast<std::int8_t>(-DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
        emitLine(out, 1, "}");
        if (isPmrFlavor(flavor_))
        {
            emitLine(out,
                     1,
                     "::llvmdsdl::cpp::MemoryResource* const effective_memory_resource = "
                     "(memory_resource != nullptr) ? memory_resource : out_obj->_memory_resource;");
            emitLine(out, 1, "(void)effective_memory_resource;");
            emitLine(out,
                     1,
                     "if (effective_memory_resource != nullptr) { "
                     "out_obj->set_memory_resource(effective_memory_resource); }");
        }
        emitLine(out, 1, "if (buffer == nullptr) {");
        emitLine(out, 2, "buffer = reinterpret_cast<const std::uint8_t*>(\"\");");
        emitLine(out, 1, "}");
        emitLine(out, 1, "const std::size_t capacity_bytes = *inout_buffer_size_bytes;");
        emitLine(out, 1, "const std::size_t capacity_bits = capacity_bytes * 8U;");
        emitLine(out, 1, "std::size_t offset_bits = 0U;");
        const auto emitted = emitNativeFunctionSkeleton(
            section,
            sectionFacts,
            HelperBindingDirection::Deserialize,
            NativeFunctionSkeletonCallbacks{
                [this, &out](const SectionHelperBindingPlan& helperBindings) {
                    emitDeserializeMlirHelperBindings(out, helperBindings, 1);
                },
                [&out](const std::string& missingHelperRequirement) {
                    emitLine(out, 1, "/* missing lowered helper contract: " + missingHelperRequirement + " */");
                    emitLine(out,
                             1,
                             "return static_cast<std::int8_t>("
                             "-DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
                },
                nullptr,
                [this, &out, &section, sectionFacts](const LoweredBodyRenderIR& renderIR) {
                    NativeEmitterTraversalCallbacks callbacks;
                    callbacks.onUnionDispatch = [this, &out, &section, sectionFacts, &renderIR](
                                                    const std::vector<PlannedFieldStep>& unionBranches) {
                        emitDeserializeUnion(out,
                                             section,
                                             unionBranches,
                                             "out_obj",
                                             1,
                                             sectionFacts,
                                             renderIR.helperBindings);
                    };
                    callbacks.onFieldAlignment = [this, &out](const std::int64_t alignmentBits) {
                        emitAlignDeserialize(out, alignmentBits, 1);
                    };
                    callbacks.onField = [this, &out](const PlannedFieldStep& fieldStep) {
                        const auto* const field = fieldStep.field;
                        emitDeserializeValue(out,
                                             field->resolvedType,
                                             "out_obj->" +
                                                 codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, field->name),
                                             1,
                                             fieldStep.arrayLengthPrefixBits,
                                             fieldStep.fieldFacts);
                    };
                    callbacks.onPaddingAlignment = [this, &out](const std::int64_t alignmentBits) {
                        emitAlignDeserialize(out, alignmentBits, 1);
                    };
                    callbacks.onPadding = [this, &out](const PlannedFieldStep& fieldStep) {
                        const auto* const field = fieldStep.field;
                        emitDeserializePadding(out, field->resolvedType, 1);
                    };
                    return callbacks;
                },
                [this, &out]() {
                    emitAlignDeserialize(out, 8, 1);
                    emitLine(out,
                             1,
                             "*inout_buffer_size_bytes = "
                             "static_cast<std::size_t>(dsdl_runtime_choose_min(offset_bits, "
                             "capacity_bits) / 8U);");
                    emitLine(out, 1, "return static_cast<std::int8_t>(DSDL_RUNTIME_SUCCESS);");
                }});
        if (!emitted)
        {
            emitLine(out, 0, "}");
            out << "\n";
            return;
        }
        emitLine(out, 0, "}");
        out << "\n";
    }

private:
    const EmitterContext& ctx_;
    CppFlavor             flavor_{CppFlavor::Std};
    std::size_t           id_{0};

    std::string nextName(const std::string& prefix)
    {
        return "_" + prefix + std::to_string(id_++) + "_";
    }

    std::string helperBindingName(const std::string& helperSymbol) const
    {
        return renderHelperBindingIdentifier(CodegenNamingLanguage::Cpp, helperSymbol);
    }

    void emitSerializeMlirHelperBindings(std::ostringstream&             out,
                                         const SectionHelperBindingPlan& plan,
                                         const int                       indent)
    {
        for (const auto& line : renderSectionHelperBindings(
                 plan,
                 HelperBindingRenderLanguage::Cpp,
                 ScalarBindingRenderDirection::Serialize,
                 [this](const std::string& symbol) { return helperBindingName(symbol); },
                 /*emitCapacityCheck=*/true))
        {
            emitLine(out, indent, line);
        }
    }

    void emitDeserializeMlirHelperBindings(std::ostringstream&             out,
                                           const SectionHelperBindingPlan& plan,
                                           const int                       indent)
    {
        for (const auto& line : renderSectionHelperBindings(
                 plan,
                 HelperBindingRenderLanguage::Cpp,
                 ScalarBindingRenderDirection::Deserialize,
                 [this](const std::string& symbol) { return helperBindingName(symbol); },
                 /*emitCapacityCheck=*/false))
        {
            emitLine(out, indent, line);
        }
    }

    std::string containerElementType(const SemanticFieldType& type) const
    {
        switch (type.scalarCategory)
        {
        case SemanticScalarCategory::Bool:
            return "bool";
        case SemanticScalarCategory::Byte:
        case SemanticScalarCategory::Utf8:
        case SemanticScalarCategory::UnsignedInt:
            return unsignedStorageType(type.bitLength);
        case SemanticScalarCategory::SignedInt:
            return signedStorageType(type.bitLength);
        case SemanticScalarCategory::Float:
            return type.bitLength == 64U ? "double" : "float";
        case SemanticScalarCategory::Void:
            return "std::uint8_t";
        case SemanticScalarCategory::Composite:
            if (type.compositeType)
            {
                return ctx_.cppQualifiedTypeName(*type.compositeType);
            }
            return "std::uint8_t";
        }
        return "std::uint8_t";
    }

    void emitAlignSerialize(std::ostringstream& out, const std::int64_t alignmentBits, const int indent)
    {
        if (alignmentBits <= 1)
        {
            return;
        }
        trace(EmitTraceOp::Align, alignmentBits);
        const auto alignedOffset = nextName("aligned_offset");
        const auto bitIndex      = nextName("align_bit");
        const auto err           = nextName("err");
        emitLine(out,
                 indent,
                 "const std::size_t " + alignedOffset + " = (offset_bits + " + std::to_string(alignmentBits - 1) +
                     "U) & ~(std::size_t)" + std::to_string(alignmentBits - 1) + "U;");
        emitLine(out,
                 indent,
                 "for (std::size_t " + bitIndex + " = offset_bits; " + bitIndex + " < " + alignedOffset + "; ++" +
                     bitIndex + ") {");
        emitLine(out,
                 indent + 1,
                 "const std::int8_t " + err + " = dsdl_runtime_set_bit(buffer, capacity_bytes, " + bitIndex +
                     ", false);");
        emitLine(out, indent + 1, "if (" + err + " < 0) {");
        emitLine(out, indent + 2, "return " + err + ";");
        emitLine(out, indent + 1, "}");
        emitLine(out, indent, "}");
        emitLine(out, indent, "offset_bits = " + alignedOffset + ";");
    }

    void emitAlignDeserialize(std::ostringstream& out, const std::int64_t alignmentBits, const int indent)
    {
        if (alignmentBits <= 1)
        {
            return;
        }
        trace(EmitTraceOp::Align, alignmentBits);
        emitLine(out,
                 indent,
                 "offset_bits = (offset_bits + " + std::to_string(alignmentBits - 1) + "U) & ~(std::size_t)" +
                     std::to_string(alignmentBits - 1) + "U;");
    }

    void emitSerializePadding(std::ostringstream& out, const SemanticFieldType& type, const int indent)
    {
        if (type.bitLength == 0)
        {
            return;
        }
        trace(EmitTraceOp::Pad, type.bitLength);
        const auto err = nextName("err");
        emitLine(out,
                 indent,
                 "const std::int8_t " + err + " = dsdl_runtime_set_uxx(buffer, capacity_bytes, offset_bits, 0U, " +
                     std::to_string(type.bitLength) + "U);");
        emitLine(out, indent, "if (" + err + " < 0) {");
        emitLine(out, indent + 1, "return " + err + ";");
        emitLine(out, indent, "}");
        trace(EmitTraceOp::Advance, type.bitLength);
        emitLine(out, indent, "offset_bits += " + std::to_string(type.bitLength) + "U;");
    }

    void emitDeserializePadding(std::ostringstream& out, const SemanticFieldType& type, const int indent)
    {
        if (type.bitLength == 0)
        {
            return;
        }
        trace(EmitTraceOp::Pad, type.bitLength);
        trace(EmitTraceOp::Advance, type.bitLength);
        emitLine(out, indent, "offset_bits += " + std::to_string(type.bitLength) + "U;");
    }

    /// @brief C++ spelling of the shared union-prologue steps (see EmitStep.h).
    ///
    /// Dispatch is an if / else-if chain (not a switch), so the case spelling is
    /// stateful via the shared renderer's firstCase flag, and the bad-tag default
    /// is the trailing `else` arm.
    class UnionSpelling final : public UnionSectionSpelling
    {
    public:
        UnionSpelling(FunctionBodyEmitter&            owner,
                      std::ostringstream&             out,
                      const std::string&              objRef,
                      const int                       indent,
                      const std::int64_t              tagBits,
                      const SectionHelperBindingPlan& helperBindings)
            : owner_(owner)
            , out_(out)
            , objRef_(objRef)
            , indent_(indent)
            , tagBits_(tagBits)
            , helperBindings_(helperBindings)
        {
        }

        void spellSerializeValidateTag() override
        {
            const auto validateHelper = owner_.helperBindingName(helperBindings_.unionTagValidate->symbol);
            const auto validateErr    = owner_.nextName("err_union_tag");
            owner_.trace(EmitTraceOp::ValidateTag);
            emitLine(out_,
                     indent_,
                     "const std::int8_t " + validateErr + " = " + validateHelper + "(static_cast<std::int64_t>(" +
                         objRef_ + "->_tag_));");
            emitLine(out_, indent_, "if (" + validateErr + " != static_cast<std::int8_t>(DSDL_RUNTIME_SUCCESS)) {");
            emitLine(out_, indent_ + 1, "return " + validateErr + ";");
            emitLine(out_, indent_, "}");
        }

        void spellSerializeWriteMaskedTag() override
        {
            const auto tagHelper = owner_.helperBindingName(helperBindings_.unionTagMask->symbol);
            const auto tagExpr   = tagHelper + "(static_cast<std::uint64_t>(" + objRef_ + "->_tag_))";
            const auto tagErr    = owner_.nextName("err");
            owner_.trace(EmitTraceOp::MaskTag);
            owner_.trace(EmitTraceOp::WriteTag, tagBits_);
            emitLine(out_,
                     indent_,
                     "const std::int8_t " + tagErr + " = dsdl_runtime_set_uxx(buffer, capacity_bytes, offset_bits, " +
                         tagExpr + ", " + std::to_string(tagBits_) + "U);");
            emitLine(out_, indent_, "if (" + tagErr + " < 0) {");
            emitLine(out_, indent_ + 1, "return " + tagErr + ";");
            emitLine(out_, indent_, "}");
        }

        void spellDeserializeReadMaskStoreTag() override
        {
            const auto rawTag = owner_.nextName("tag_raw");
            owner_.trace(EmitTraceOp::ReadTag, tagBits_);
            emitLine(out_,
                     indent_,
                     "const std::uint64_t " + rawTag + " = static_cast<std::uint64_t>(" +
                         unsignedGetter(static_cast<std::uint32_t>(tagBits_)) +
                         "(buffer, capacity_bytes, offset_bits, " + std::to_string(tagBits_) + "U));");
            const auto tagHelper = owner_.helperBindingName(helperBindings_.unionTagMask->symbol);
            owner_.trace(EmitTraceOp::MaskTag);
            owner_.trace(EmitTraceOp::StoreTag);
            emitLine(out_,
                     indent_,
                     objRef_ + "->_tag_ = static_cast<" +
                         unsignedStorageType(static_cast<std::uint32_t>(tagBits_)) + ">(" + tagHelper + "(" + rawTag +
                         "));");
        }

        void spellDeserializeValidateTag() override
        {
            const auto validateHelper = owner_.helperBindingName(helperBindings_.unionTagValidate->symbol);
            const auto validateErr    = owner_.nextName("err_union_tag");
            owner_.trace(EmitTraceOp::ValidateTag);
            emitLine(out_,
                     indent_,
                     "const std::int8_t " + validateErr + " = " + validateHelper + "(static_cast<std::int64_t>(" +
                         objRef_ + "->_tag_));");
            emitLine(out_, indent_, "if (" + validateErr + " != static_cast<std::int8_t>(DSDL_RUNTIME_SUCCESS)) {");
            emitLine(out_, indent_ + 1, "return " + validateErr + ";");
            emitLine(out_, indent_, "}");
        }

        void spellAdvanceTag() override
        {
            owner_.trace(EmitTraceOp::Advance, tagBits_);
            emitLine(out_, indent_, "offset_bits += " + std::to_string(tagBits_) + "U;");
        }

        void spellBeginDispatch() override
        {
            // The if / else-if chain has no opening construct; SWITCH is abstract here.
            owner_.trace(EmitTraceOp::Switch);
        }

        void spellBeginCase(const std::int64_t optionIndex, const bool firstCase) override
        {
            owner_.trace(EmitTraceOp::Case, optionIndex);
            emitLine(out_,
                     indent_,
                     std::string(firstCase ? "if" : "else if") + " (" + objRef_ +
                         "->_tag_ == " + std::to_string(optionIndex) + "U) {");
        }

        void spellEndCase() override { emitLine(out_, indent_, "}"); }

        void spellBadTagDefault() override
        {
            owner_.trace(EmitTraceOp::DefaultBadTag);
            emitLine(out_, indent_, "else {");
            emitLine(out_,
                     indent_ + 1,
                     "return static_cast<std::int8_t>(-DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG);");
            emitLine(out_, indent_, "}");
        }

        void spellEndDispatch() override
        {
            // The trailing else arm closed itself; nothing further.
        }

    private:
        FunctionBodyEmitter&            owner_;
        std::ostringstream&             out_;
        const std::string&              objRef_;
        const int                       indent_;
        const std::int64_t              tagBits_;
        const SectionHelperBindingPlan& helperBindings_;
    };

    void emitSerializeUnion(std::ostringstream&                  out,
                            const SemanticSection&               section,
                            const std::vector<PlannedFieldStep>& unionBranches,
                            const std::string&                   objRef,
                            const int                            indent,
                            const LoweredSectionFacts* const     sectionFacts,
                            const SectionHelperBindingPlan&      helperBindings)
    {
        const auto    tagBits = resolveUnionTagBits(section, sectionFacts);
        UnionSpelling spelling(*this, out, objRef, indent, static_cast<std::int64_t>(tagBits), helperBindings);
        std::vector<UnionCaseRender> cases;
        cases.reserve(unionBranches.size());
        for (const auto& step : unionBranches)
        {
            const auto& field = *step.field;
            cases.push_back(UnionCaseRender{field.unionOptionIndex, [this, &out, &objRef, indent, &step, &field]() {
                                                const auto member =
                                                    codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, field.name);
                                                emitAlignSerialize(out, field.resolvedType.alignmentBits, indent + 1);
                                                emitSerializeValue(out,
                                                                   field.resolvedType,
                                                                   objRef + "->" + member,
                                                                   indent + 1,
                                                                   step.arrayLengthPrefixBits,
                                                                   step.fieldFacts);
                                            }});
        }
        renderUnionSection(EmitTraceDirection::Serialize, cases, spelling);
    }

    void emitDeserializeUnion(std::ostringstream&                  out,
                              const SemanticSection&               section,
                              const std::vector<PlannedFieldStep>& unionBranches,
                              const std::string&                   objRef,
                              const int                            indent,
                              const LoweredSectionFacts* const     sectionFacts,
                              const SectionHelperBindingPlan&      helperBindings)
    {
        const auto    tagBits = resolveUnionTagBits(section, sectionFacts);
        UnionSpelling spelling(*this, out, objRef, indent, static_cast<std::int64_t>(tagBits), helperBindings);
        std::vector<UnionCaseRender> cases;
        cases.reserve(unionBranches.size());
        for (const auto& step : unionBranches)
        {
            const auto& field = *step.field;
            cases.push_back(UnionCaseRender{field.unionOptionIndex, [this, &out, &objRef, indent, &step, &field]() {
                                                const auto member =
                                                    codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, field.name);
                                                emitAlignDeserialize(out, field.resolvedType.alignmentBits, indent + 1);
                                                emitDeserializeValue(out,
                                                                     field.resolvedType,
                                                                     objRef + "->" + member,
                                                                     indent + 1,
                                                                     step.arrayLengthPrefixBits,
                                                                     step.fieldFacts);
                                            }});
        }
        renderUnionSection(EmitTraceDirection::Deserialize, cases, spelling);
    }

    /// @brief C++ spelling of the shared recursive field-body steps (see EmitStep.h).
    ///
    /// Leaf statement idioms only; all cross-group and recursive ordering comes
    /// from renderFieldSteps. Fixed arrays are std::array, so the D2 length guard
    /// is type-system-subsumed (spellFixedArrayLenCheck is a documented no-op),
    /// and fixed bool arrays take the D3 bulk-copy fast path via
    /// trySpellArrayBulkFastPath. PMR flavor differences stay inside this class.
    class FieldSpelling final : public FieldStepSpelling
    {
    public:
        FieldSpelling(FunctionBodyEmitter&         owner,
                      std::ostringstream&          out,
                      const int                    indent,
                      const HelperBindingDirection direction)
            : owner_(owner)
            , out_(out)
            , indent_(indent)
            , direction_(direction)
        {
        }

        void spellPad(const FieldEmitStep& step) override
        {
            if (direction_ == HelperBindingDirection::Serialize)
            {
                owner_.emitSerializePadding(out_, step.type, indent_);
            }
            else
            {
                owner_.emitDeserializePadding(out_, step.type, indent_);
            }
        }

        void spellScalarSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            switch (step.kind)
            {
            case FieldStepKind::ScalarBool: {
                const auto err = owner_.nextName("err");
                owner_.trace(EmitTraceOp::WriteScalarBool, 1);
                emitLine(out_,
                         indent_,
                         "const std::int8_t " + err +
                             " = dsdl_runtime_set_bit(buffer, capacity_bytes, offset_bits, " + expr + ");");
                emitLine(out_, indent_, "if (" + err + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + err + ";");
                emitLine(out_, indent_, "}");
                owner_.trace(EmitTraceOp::Advance, 1);
                emitLine(out_, indent_, "offset_bits += 1U;");
                break;
            }
            case FieldStepKind::ScalarUint: {
                std::string valueExpr = "static_cast<std::uint64_t>(" + expr + ")";
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = owner_.helperBindingName(step.scalarHelperSymbol);
                valueExpr         = helper + "(" + valueExpr + ")";
                const auto err    = owner_.nextName("err");
                owner_.trace(EmitTraceOp::WriteScalarUint, step.bits);
                emitLine(out_,
                         indent_,
                         "const std::int8_t " + err +
                             " = dsdl_runtime_set_uxx(buffer, capacity_bytes, offset_bits, " + valueExpr + ", " +
                             std::to_string(step.bits) + "U);");
                emitLine(out_, indent_, "if (" + err + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + err + ";");
                emitLine(out_, indent_, "}");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + "U;");
                break;
            }
            case FieldStepKind::ScalarSint: {
                std::string valueExpr = "static_cast<std::int64_t>(" + expr + ")";
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = owner_.helperBindingName(step.scalarHelperSymbol);
                valueExpr         = helper + "(" + valueExpr + ")";
                const auto err    = owner_.nextName("err");
                owner_.trace(EmitTraceOp::WriteScalarSint, step.bits);
                emitLine(out_,
                         indent_,
                         "const std::int8_t " + err +
                             " = dsdl_runtime_set_ixx(buffer, capacity_bytes, offset_bits, " + valueExpr + ", " +
                             std::to_string(step.bits) + "U);");
                emitLine(out_, indent_, "if (" + err + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + err + ";");
                emitLine(out_, indent_, "}");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + "U;");
                break;
            }
            case FieldStepKind::ScalarFloat: {
                const auto  err            = owner_.nextName("err");
                const auto  floatType      = std::string(step.bits == 64 ? "double" : "float");
                std::string normalizedExpr = "static_cast<" + floatType + ">(" + expr + ")";
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = owner_.helperBindingName(step.scalarHelperSymbol);
                normalizedExpr    = helper + "(" + normalizedExpr + ")";
                std::string call;
                if (step.bits == 16)
                {
                    call = "dsdl_runtime_set_f16(buffer, capacity_bytes, offset_bits, " + normalizedExpr + ")";
                }
                else if (step.bits == 32)
                {
                    call = "dsdl_runtime_set_f32(buffer, capacity_bytes, offset_bits, " + normalizedExpr + ")";
                }
                else
                {
                    call = "dsdl_runtime_set_f64(buffer, capacity_bytes, offset_bits, " + normalizedExpr + ")";
                }
                owner_.trace(EmitTraceOp::WriteScalarFloat, step.bits);
                emitLine(out_, indent_, "const std::int8_t " + err + " = " + call + ";");
                emitLine(out_, indent_, "if (" + err + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + err + ";");
                emitLine(out_, indent_, "}");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + "U;");
                break;
            }
            default:
                assert(false && "not a scalar step");
                break;
            }
        }

        void spellScalarDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            switch (step.kind)
            {
            case FieldStepKind::ScalarBool:
                owner_.trace(EmitTraceOp::ReadScalarBool, 1);
                emitLine(out_, indent_, expr + " = dsdl_runtime_get_bit(buffer, capacity_bytes, offset_bits);");
                owner_.trace(EmitTraceOp::Advance, 1);
                emitLine(out_, indent_, "offset_bits += 1U;");
                break;
            case FieldStepKind::ScalarUint: {
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = owner_.helperBindingName(step.scalarHelperSymbol);
                const auto raw    = owner_.nextName("raw");
                owner_.trace(EmitTraceOp::ReadScalarUint, step.bits);
                emitLine(out_,
                         indent_,
                         "const std::uint64_t " + raw + " = static_cast<std::uint64_t>(" +
                             unsignedGetter(static_cast<std::uint32_t>(step.bits)) +
                             "(buffer, capacity_bytes, offset_bits, " + std::to_string(step.bits) + "U));");
                emitLine(out_,
                         indent_,
                         expr + " = static_cast<" + unsignedStorageType(static_cast<std::uint32_t>(step.bits)) +
                             ">(" + helper + "(" + raw + "));");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + "U;");
                break;
            }
            case FieldStepKind::ScalarSint: {
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = owner_.helperBindingName(step.scalarHelperSymbol);
                const auto raw    = owner_.nextName("raw");
                owner_.trace(EmitTraceOp::ReadScalarSint, step.bits);
                emitLine(out_,
                         indent_,
                         "const std::int64_t " + raw + " = static_cast<std::int64_t>(" +
                             unsignedGetter(static_cast<std::uint32_t>(step.bits)) +
                             "(buffer, capacity_bytes, offset_bits, " + std::to_string(step.bits) + "U));");
                emitLine(out_,
                         indent_,
                         expr + " = static_cast<" + signedStorageType(static_cast<std::uint32_t>(step.bits)) + ">(" +
                             helper + "(" + raw + "));");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + "U;");
                break;
            }
            case FieldStepKind::ScalarFloat: {
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = owner_.helperBindingName(step.scalarHelperSymbol);
                owner_.trace(EmitTraceOp::ReadScalarFloat, step.bits);
                if (step.bits == 16)
                {
                    emitLine(out_,
                             indent_,
                             expr + " = static_cast<float>(" + helper +
                                 "(static_cast<float>(dsdl_runtime_get_f16(buffer, capacity_bytes, "
                                 "offset_bits))));");
                }
                else if (step.bits == 32)
                {
                    emitLine(out_,
                             indent_,
                             expr + " = static_cast<float>(" + helper +
                                 "(static_cast<float>(dsdl_runtime_get_f32(buffer, capacity_bytes, "
                                 "offset_bits))));");
                }
                else
                {
                    emitLine(out_,
                             indent_,
                             expr + " = static_cast<double>(" + helper +
                                 "(static_cast<double>(dsdl_runtime_get_f64(buffer, capacity_bytes, "
                                 "offset_bits))));");
                }
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + "U;");
                break;
            }
            default:
                assert(false && "not a scalar step");
                break;
            }
        }

        void spellFixedArrayLenCheck(const FieldEmitStep& step, const std::string& expr) override
        {
            // D2: C++ fixed arrays are std::array; the exact-length guard is subsumed
            // by the type system, so there is no emit site.
            (void) step;
            (void) expr;
        }

        bool trySpellArrayBulkFastPath(const FieldEmitStep&         step,
                                       const std::string&           expr,
                                       const HelperBindingDirection direction) override
        {
            // D3: fixed bool arrays are bit-copied wholesale instead of looping.
            if (step.kind != FieldStepKind::FixedArray ||
                step.children.front().kind != FieldStepKind::ScalarBool)
            {
                return false;
            }
            const auto countExpr = std::to_string(step.capacity) + "U";
            if (direction == HelperBindingDirection::Serialize)
            {
                const auto source = expr + ".data()";
                owner_.trace(EmitTraceOp::BulkCopy, step.capacity);
                emitLine(out_,
                         indent_,
                         "dsdl_runtime_copy_bits(&buffer[0], offset_bits, " + countExpr + ", " + source + ", 0U);");
                owner_.trace(EmitTraceOp::Advance, step.capacity);
                emitLine(out_, indent_, "offset_bits += " + countExpr + ";");
            }
            else
            {
                const auto target = expr + ".data()";
                owner_.trace(EmitTraceOp::BulkCopy, step.capacity);
                emitLine(out_,
                         indent_,
                         "dsdl_runtime_get_bits(" + target +
                             ", &buffer[0], capacity_bytes, "
                             "offset_bits, " +
                             countExpr + ");");
                owner_.trace(EmitTraceOp::Advance, step.capacity);
                emitLine(out_, indent_, "offset_bits += " + countExpr + ";");
            }
            return true;
        }

        void spellVariableArrayLenSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            assert(step.arrayHelpers.has_value());
            assert(!step.arrayHelpers->validateSymbol.empty());
            const auto validateHelper = owner_.helperBindingName(step.arrayHelpers->validateSymbol);
            const auto validateRc     = owner_.nextName("len_rc");
            owner_.trace(EmitTraceOp::LenValidate, step.prefixBits);
            emitLine(out_,
                     indent_,
                     "const std::int8_t " + validateRc + " = " + validateHelper + "(static_cast<std::int64_t>(" +
                         expr + ".size()));");
            emitLine(out_, indent_, "if (" + validateRc + " < 0) {");
            emitLine(out_, indent_ + 1, "return " + validateRc + ";");
            emitLine(out_, indent_, "}");

            std::string prefixExpr = "static_cast<std::uint64_t>(" + expr + ".size())";
            assert(!step.arrayHelpers->prefixSymbol.empty());
            const auto serPrefixHelper = owner_.helperBindingName(step.arrayHelpers->prefixSymbol);
            prefixExpr                 = serPrefixHelper + "(" + prefixExpr + ")";
            const auto err             = owner_.nextName("err");
            owner_.trace(EmitTraceOp::LenWrite, step.prefixBits);
            emitLine(out_,
                     indent_,
                     "const std::int8_t " + err + " = dsdl_runtime_set_uxx(buffer, capacity_bytes, offset_bits, " +
                         prefixExpr + ", " + std::to_string(step.prefixBits) + "U);");
            emitLine(out_, indent_, "if (" + err + " < 0) {");
            emitLine(out_, indent_ + 1, "return " + err + ";");
            emitLine(out_, indent_, "}");
            owner_.trace(EmitTraceOp::Advance, step.prefixBits);
            emitLine(out_, indent_, "offset_bits += " + std::to_string(step.prefixBits) + "U;");
        }

        std::string spellVariableArrayLenDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            const auto rawCountVar = owner_.nextName("count_raw");
            owner_.trace(EmitTraceOp::LenRead, step.prefixBits);
            emitLine(out_,
                     indent_,
                     "const std::uint64_t " + rawCountVar + " = static_cast<std::uint64_t>(" +
                         unsignedGetter(step.prefixBits) + "(buffer, capacity_bytes, offset_bits, " +
                         std::to_string(step.prefixBits) + "U));");
            owner_.trace(EmitTraceOp::Advance, step.prefixBits);
            emitLine(out_, indent_, "offset_bits += " + std::to_string(step.prefixBits) + "U;");
            std::string countRawExpr = rawCountVar;
            assert(step.arrayHelpers.has_value());
            assert(!step.arrayHelpers->prefixSymbol.empty());
            const auto deserPrefixHelper = owner_.helperBindingName(step.arrayHelpers->prefixSymbol);
            countRawExpr                 = deserPrefixHelper + "(" + countRawExpr + ")";
            const auto countVar          = owner_.nextName("count");
            emitLine(out_,
                     indent_,
                     "const std::size_t " + countVar + " = static_cast<std::size_t>(" + countRawExpr + ");");

            assert(!step.arrayHelpers->validateSymbol.empty());
            const auto validateHelper = owner_.helperBindingName(step.arrayHelpers->validateSymbol);
            const auto validateRc     = owner_.nextName("len_rc");
            owner_.trace(EmitTraceOp::LenValidate, step.prefixBits);
            emitLine(out_,
                     indent_,
                     "const std::int8_t " + validateRc + " = " + validateHelper + "(static_cast<std::int64_t>(" +
                         countVar + "));");
            emitLine(out_, indent_, "if (" + validateRc + " < 0) {");
            emitLine(out_, indent_ + 1, "return " + validateRc + ";");
            emitLine(out_, indent_, "}");
            if (isPmrFlavor(owner_.flavor_))
            {
                const auto tmpVar = owner_.nextName("tmp");
                emitLine(out_,
                         indent_,
                         "std::pmr::vector<" + owner_.containerElementType(step.type) + "> " + tmpVar +
                             "(effective_memory_resource != nullptr ? effective_memory_resource : "
                             "::llvmdsdl::cpp::default_memory_resource());");
                emitLine(out_, indent_, tmpVar + ".resize(" + countVar + ");");
                emitLine(out_, indent_, expr + " = std::move(" + tmpVar + ");");
            }
            else
            {
                emitLine(out_, indent_, expr + ".resize(" + countVar + ");");
            }

            if (isPmrFlavor(owner_.flavor_) && step.type.scalarCategory == SemanticScalarCategory::Composite)
            {
                const auto initIndex = owner_.nextName("i");
                emitLine(out_,
                         indent_,
                         "for (std::size_t " + initIndex + " = 0U; " + initIndex + " < " + countVar + "; ++" +
                             initIndex + ") {");
                emitLine(out_,
                         indent_ + 1,
                         expr + "[" + initIndex + "].set_memory_resource(effective_memory_resource);");
                emitLine(out_, indent_, "}");
            }

            return countVar;
        }

        std::string spellFixedArrayCountDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            // std::array needs no storage prep; the loop bounds on the capacity literal.
            (void) expr;
            return std::to_string(step.capacity) + "U";
        }

        std::string spellBeginElemLoopSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            const auto index = owner_.nextName("index");
            const auto bound = step.kind == FieldStepKind::VariableArray
                                   ? (expr + ".size()")
                                   : std::to_string(step.capacity) + "U";
            owner_.trace(EmitTraceOp::ElemLoop);
            emitLine(out_,
                     indent_,
                     "for (std::size_t " + index + " = 0U; " + index + " < " + bound + "; ++" + index + ") {");
            ++indent_;
            return expr + "[" + index + "]";
        }

        std::string spellBeginElemLoopDeserialize(const FieldEmitStep& step,
                                                  const std::string&   expr,
                                                  const std::string&   countExpr) override
        {
            (void) step;
            const auto index = owner_.nextName("index");
            owner_.trace(EmitTraceOp::ElemLoop);
            emitLine(out_,
                     indent_,
                     "for (std::size_t " + index + " = 0U; " + index + " < " + countExpr + "; ++" + index + ") {");
            ++indent_;
            return expr + "[" + index + "]";
        }

        void spellEndElemLoopSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            (void) step;
            (void) expr;
            --indent_;
            emitLine(out_, indent_, "}");
        }

        void spellEndElemLoopDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            (void) step;
            (void) expr;
            --indent_;
            emitLine(out_, indent_, "}");
        }

        void spellCompositeSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            if (!step.type.compositeType)
            {
                emitLine(out_, indent_, "return static_cast<std::int8_t>(-DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
                return;
            }

            owner_.trace(step.type.compositeSealed ? EmitTraceOp::CompositeInline
                                                   : EmitTraceOp::CompositeDelimHeader);
            const auto nestedType = owner_.ctx_.cppQualifiedTypeName(*step.type.compositeType);
            auto       sizeVar    = owner_.nextName("size_bytes");
            auto       errVar     = owner_.nextName("err");

            if (!step.type.compositeSealed)
            {
                emitLine(out_, indent_, "offset_bits += 32U;  // Delimiter header");
            }

            emitLine(out_,
                     indent_,
                     "std::size_t " + sizeVar + " = " + std::to_string((step.type.bitLengthSet.max() + 7) / 8) +
                         "U;");
            if (!step.type.compositeSealed)
            {
                const auto remaining = owner_.nextName("remaining");
                emitLine(out_,
                         indent_,
                         "const std::size_t " + remaining +
                             " = capacity_bytes - dsdl_runtime_choose_min(offset_bits / 8U, capacity_bytes);");
                assert(!step.delimiterValidateSymbol.empty());
                const auto helper     = owner_.helperBindingName(step.delimiterValidateSymbol);
                const auto validateRc = owner_.nextName("rc");
                emitLine(out_,
                         indent_,
                         "const std::int8_t " + validateRc + " = " + helper + "(static_cast<std::int64_t>(" +
                             sizeVar + "), static_cast<std::int64_t>(" + remaining + "));");
                emitLine(out_, indent_, "if (" + validateRc + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + validateRc + ";");
                emitLine(out_, indent_, "}");
            }
            emitLine(out_,
                     indent_,
                     "std::int8_t " + errVar + " = " + nestedType + "__serialize_(&" + expr +
                         ", &buffer[offset_bits / 8U], &" + sizeVar +
                         (isPmrFlavor(owner_.flavor_) ? ", effective_memory_resource" : "") + ");");
            emitLine(out_, indent_, "if (" + errVar + " < 0) {");
            emitLine(out_, indent_ + 1, "return " + errVar + ";");
            emitLine(out_, indent_, "}");

            if (!step.type.compositeSealed)
            {
                auto hdrErr = owner_.nextName("err");
                emitLine(out_,
                         indent_,
                         "const std::int8_t " + hdrErr +
                             " = dsdl_runtime_set_uxx(buffer, capacity_bytes, offset_bits - 32U, "
                             "static_cast<std::uint64_t>(" +
                             sizeVar + "), 32U);");
                emitLine(out_, indent_, "if (" + hdrErr + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + hdrErr + ";");
                emitLine(out_, indent_, "}");
            }

            emitLine(out_, indent_, "offset_bits += " + sizeVar + " * 8U;");
        }

        void spellCompositeDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            if (!step.type.compositeType)
            {
                emitLine(out_, indent_, "return static_cast<std::int8_t>(-DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
                return;
            }

            owner_.trace(step.type.compositeSealed ? EmitTraceOp::CompositeInline
                                                   : EmitTraceOp::CompositeDelimHeader);
            const auto nestedType = owner_.ctx_.cppQualifiedTypeName(*step.type.compositeType);
            auto       sizeVar    = owner_.nextName("size_bytes");
            auto       errVar     = owner_.nextName("err");

            if (!step.type.compositeSealed)
            {
                emitLine(out_,
                         indent_,
                         "std::size_t " + sizeVar +
                             " = static_cast<std::size_t>(dsdl_runtime_get_u32(buffer, capacity_bytes, "
                             "offset_bits, "
                             "32U));");
                emitLine(out_, indent_, "offset_bits += 32U;");
                emitLine(out_,
                         indent_,
                         "const std::size_t _remaining_" + std::to_string(owner_.id_) +
                             " = capacity_bytes - dsdl_runtime_choose_min(offset_bits / 8U, capacity_bytes);");
                const auto remVar = "_remaining_" + std::to_string(owner_.id_);
                ++owner_.id_;
                assert(!step.delimiterValidateSymbol.empty());
                const auto helper     = owner_.helperBindingName(step.delimiterValidateSymbol);
                const auto validateRc = owner_.nextName("rc");
                emitLine(out_,
                         indent_,
                         "const std::int8_t " + validateRc + " = " + helper + "(static_cast<std::int64_t>(" +
                             sizeVar + "), static_cast<std::int64_t>(" + remVar + "));");
                emitLine(out_, indent_, "if (" + validateRc + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + validateRc + ";");
                emitLine(out_, indent_, "}");
                const auto consumed = owner_.nextName("consumed");
                emitLine(out_, indent_, "std::size_t " + consumed + " = " + sizeVar + ";");
                emitLine(out_,
                         indent_,
                         "const std::int8_t " + errVar + " = " + nestedType + "__deserialize_(&" + expr +
                             ", &buffer[offset_bits / 8U], &" + consumed +
                             (isPmrFlavor(owner_.flavor_) ? ", effective_memory_resource" : "") + ");");
                emitLine(out_, indent_, "if (" + errVar + " < 0) {");
                emitLine(out_, indent_ + 1, "return " + errVar + ";");
                emitLine(out_, indent_, "}");
                emitLine(out_, indent_, "offset_bits += " + sizeVar + " * 8U;");
                return;
            }

            emitLine(out_,
                     indent_,
                     "std::size_t " + sizeVar +
                         " = capacity_bytes - dsdl_runtime_choose_min(offset_bits / 8U, capacity_bytes);");
            emitLine(out_,
                     indent_,
                     "const std::int8_t " + errVar + " = " + nestedType + "__deserialize_(&" + expr +
                         ", &buffer[offset_bits / 8U], &" + sizeVar +
                         (isPmrFlavor(owner_.flavor_) ? ", effective_memory_resource" : "") + ");");
            emitLine(out_, indent_, "if (" + errVar + " < 0) {");
            emitLine(out_, indent_ + 1, "return " + errVar + ";");
            emitLine(out_, indent_, "}");
            emitLine(out_, indent_, "offset_bits += " + sizeVar + " * 8U;");
        }

    private:
        FunctionBodyEmitter&         owner_;
        std::ostringstream&          out_;
        int                          indent_;
        const HelperBindingDirection direction_;
    };

    void emitSerializeValue(std::ostringstream&                out,
                            const SemanticFieldType&           type,
                            const std::string&                 expr,
                            const int                          indent,
                            const std::optional<std::uint32_t> arrayLengthPrefixBitsOverride = std::nullopt,
                            const LoweredFieldFacts* const     fieldFacts                    = nullptr)
    {
        const auto steps =
            buildFieldEmitSteps(type, fieldFacts, arrayLengthPrefixBitsOverride, HelperBindingDirection::Serialize);
        FieldSpelling spelling(*this, out, indent, HelperBindingDirection::Serialize);
        renderFieldSteps(steps, expr, HelperBindingDirection::Serialize, spelling);
    }

    void emitDeserializeValue(std::ostringstream&                out,
                              const SemanticFieldType&           type,
                              const std::string&                 expr,
                              const int                          indent,
                              const std::optional<std::uint32_t> arrayLengthPrefixBitsOverride = std::nullopt,
                              const LoweredFieldFacts* const     fieldFacts                    = nullptr)
    {
        const auto steps =
            buildFieldEmitSteps(type, fieldFacts, arrayLengthPrefixBitsOverride, HelperBindingDirection::Deserialize);
        FieldSpelling spelling(*this, out, indent, HelperBindingDirection::Deserialize);
        renderFieldSteps(steps, expr, HelperBindingDirection::Deserialize, spelling);
    }
};

std::string cppTypeFromFieldType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "bool";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
        return unsignedStorageType(type.bitLength);
    case SemanticScalarCategory::SignedInt:
        return signedStorageType(type.bitLength);
    case SemanticScalarCategory::Float:
        if (type.bitLength == 64U)
        {
            return "double";
        }
        return "float";
    case SemanticScalarCategory::Void:
        return "std::uint8_t";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.cppQualifiedTypeName(*type.compositeType);
        }
        return "std::uint8_t";
    }
    return "std::uint8_t";
}

void emitArrayMetadata(std::ostringstream& out, const std::string& typeName, const SemanticSection& section)
{
    for (const auto& field : section.fields)
    {
        if (field.isPadding || field.resolvedType.arrayKind == ArrayKind::None)
        {
            continue;
        }
        const auto fieldName = sanitizeMacroToken(field.name);
        emitLine(out,
                 1,
                 "static constexpr std::size_t " + fieldName +
                     "_ARRAY_CAPACITY = " + std::to_string(field.resolvedType.arrayCapacity) + "U;");
        emitLine(out,
                 1,
                 "static constexpr bool " + fieldName + "_ARRAY_IS_VARIABLE_LENGTH = " +
                     std::string(isVariableArray(field.resolvedType.arrayKind) ? "true" : "false") + ";");
    }
}

void emitFunctionPrototypes(std::ostringstream& out, const std::string& typeName, const CppFlavor flavor)
{
    emitLine(out, 0, "struct " + typeName + ";");
    emitLine(out,
             0,
             "inline std::int8_t " + typeName + "__serialize_(const " + typeName +
                 "* obj, std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes" +
                 (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* memory_resource" : "") + ");");
    emitLine(out,
             0,
             "inline std::int8_t " + typeName + "__deserialize_(" + typeName +
                 "* out_obj, const std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes" +
                 (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* memory_resource" : "") + ");");
    emitLine(out,
             0,
             "inline std::int8_t " + typeName +
                 "__try_deserialize_view_(const std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes, "
                 "const std::uint8_t** out_view_bytes);");
    emitLine(out,
             0,
             "inline std::int8_t " + typeName +
                 "__try_serialize_view_(const std::uint8_t* view_bytes, std::size_t view_size_bytes, "
                 "std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes);");
    out << "\n";
}

void emitSectionStruct(std::ostringstream&    out,
                       const std::string&     typeName,
                       const std::string&     fullName,
                       std::uint32_t          majorVersion,
                       std::uint32_t          minorVersion,
                       const SemanticSection& section,
                       const EmitterContext&  ctx,
                       const CppFlavor        flavor,
                       const AttachedDoc&     typeDoc,
                       const LoweredSectionFacts* const sectionFacts)
{
    emitAttachedDocCpp(out, 0, typeDoc);
    const std::string structAttribute =
        (section.deprecated && ctx.emitDeprecationAttributes()) ? "[[deprecated]] " : "";
    emitLine(out, 0, "struct " + structAttribute + typeName + " {");

    std::size_t              emitted = 0;
    std::vector<std::string> variableArrayMembers;
    std::vector<std::string> compositeScalarMembers;
    std::vector<std::string> compositeFixedArrayMembers;
    std::vector<std::string> compositeVariableArrayMembers;

    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }

        const auto member   = codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, field.name);
        const auto baseType = cppTypeFromFieldType(field.resolvedType, ctx);
        emitAttachedDocCpp(out, 1, field.doc);

        if (field.resolvedType.arrayKind == ArrayKind::None)
        {
            emitLine(out, 1, baseType + " " + member + "{};");
            if (isPmrFlavor(flavor) && field.resolvedType.scalarCategory == SemanticScalarCategory::Composite)
            {
                compositeScalarMembers.push_back(member);
            }
            ++emitted;
            continue;
        }

        if (field.resolvedType.arrayKind == ArrayKind::Fixed)
        {
            if (field.resolvedType.scalarCategory == SemanticScalarCategory::Bool)
            {
                emitLine(out,
                         1,
                         "std::array<std::uint8_t, (" + std::to_string(field.resolvedType.arrayCapacity) +
                             "U + 7U) / 8U> " + member + "{};");
            }
            else
            {
                emitLine(out,
                         1,
                         "std::array<" + baseType + ", " + std::to_string(field.resolvedType.arrayCapacity) + "U> " +
                             member + "{};");
            }
            if (isPmrFlavor(flavor) && field.resolvedType.scalarCategory == SemanticScalarCategory::Composite)
            {
                compositeFixedArrayMembers.push_back(member);
            }
            ++emitted;
            continue;
        }

        if (isPmrFlavor(flavor))
        {
            emitLine(out,
                     1,
                     "std::pmr::vector<" +
                         std::string(field.resolvedType.scalarCategory == SemanticScalarCategory::Bool ? "bool"
                                                                                                       : baseType) +
                         "> " + member + "{};");
            variableArrayMembers.push_back(member);
            if (field.resolvedType.scalarCategory == SemanticScalarCategory::Composite)
            {
                compositeVariableArrayMembers.push_back(member);
            }
        }
        else if (isAutosarFlavor(flavor))
        {
            emitLine(out,
                     1,
                     "::llvmdsdl::cpp::autosar::BoundedVector<" +
                         std::string(field.resolvedType.scalarCategory == SemanticScalarCategory::Bool ? "bool"
                                                                                                       : baseType) +
                         ", " + std::to_string(field.resolvedType.arrayCapacity) + "U> " + member + "{};");
        }
        else
        {
            emitLine(out,
                     1,
                     "std::vector<" +
                         std::string(field.resolvedType.scalarCategory == SemanticScalarCategory::Bool ? "bool"
                                                                                                       : baseType) +
                         "> " + member + "{};");
        }
        ++emitted;
    }

    if (section.isUnion)
    {
        // Tag storage must match the wire tag width (uint8 for <=256 options, uint16 for
        // 257..65536, etc.); a hardcoded uint8 truncates a wide tag and mis-dispatches.
        emitLine(out, 1, unsignedStorageType(resolveUnionTagBits(section, sectionFacts)) + " _tag_{0U};");
        ++emitted;
    }

    if (isPmrFlavor(flavor))
    {
        emitLine(out,
                 1,
                 "::llvmdsdl::cpp::MemoryResource* _memory_resource{::llvmdsdl::cpp::default_memory_resource()};");
        emitLine(out, 1, typeName + "() = default;");
        emitLine(out,
                 1,
                 "explicit " + typeName +
                     "(::llvmdsdl::cpp::MemoryResource* memory_resource) { set_memory_resource(memory_resource); }");
        emitLine(out, 1, "void set_memory_resource(::llvmdsdl::cpp::MemoryResource* memory_resource) {");
        emitLine(out,
                 2,
                 "_memory_resource = (memory_resource != nullptr) ? memory_resource : "
                 "::llvmdsdl::cpp::default_memory_resource();");
        for (const auto& member : variableArrayMembers)
        {
            emitLine(out, 2, member + " = decltype(" + member + ")(_memory_resource);");
        }
        for (const auto& member : compositeScalarMembers)
        {
            emitLine(out, 2, member + ".set_memory_resource(_memory_resource);");
        }
        for (const auto& member : compositeFixedArrayMembers)
        {
            const auto i = codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, member + "_index");
            emitLine(out, 2, "for (std::size_t " + i + " = 0U; " + i + " < " + member + ".size(); ++" + i + ") {");
            emitLine(out, 3, member + "[" + i + "].set_memory_resource(_memory_resource);");
            emitLine(out, 2, "}");
        }
        for (const auto& member : compositeVariableArrayMembers)
        {
            const auto i = codegenSanitizeIdentifier(CodegenNamingLanguage::Cpp, member + "_index");
            emitLine(out, 2, "for (std::size_t " + i + " = 0U; " + i + " < " + member + ".size(); ++" + i + ") {");
            emitLine(out, 3, member + "[" + i + "].set_memory_resource(_memory_resource);");
            emitLine(out, 2, "}");
        }
        emitLine(out, 1, "}");
        ++emitted;
    }

    if (emitted == 0)
    {
        emitLine(out, 1, "std::uint8_t _dummy_{0U};");
    }

    emitLine(out, 1, "static constexpr const char* FULL_NAME = \"" + fullName + "\";");
    emitLine(out,
             1,
             "static constexpr bool IS_DEPRECATED = " + std::string(section.deprecated ? "true" : "false") + ";");
    emitLine(out,
             1,
             "static constexpr const char* FULL_NAME_AND_VERSION = \"" + fullName + "." + std::to_string(majorVersion) +
                 "." + std::to_string(minorVersion) + "\";");
    emitLine(out,
             1,
             "static constexpr std::size_t EXTENT_BYTES = " + std::to_string(section.extentBits.value_or(0) / 8) +
                 "U;");
    emitLine(out,
             1,
             "static constexpr std::size_t SERIALIZATION_BUFFER_SIZE_BYTES = " +
                 std::to_string((section.serializationBufferSizeBits + 7) / 8) + "U;");
    const bool zohAliasEligible = sectionFacts != nullptr && sectionFacts->zohAliasEligible;
    const std::string zohAliasReason =
        (sectionFacts != nullptr && !sectionFacts->zohAliasReason.empty()) ? sectionFacts->zohAliasReason : "not-proven";
    emitLine(out,
             1,
             std::string("static constexpr bool ZOH_ALIAS_ELIGIBLE = ") + (zohAliasEligible ? "true;" : "false;"));
    emitLine(out, 1, "static constexpr const char* ZOH_ALIAS_REASON = \"" + zohAliasReason + "\";");
    if (section.isUnion)
    {
        std::size_t optionCount = 0;
        for (const auto& f : section.fields)
        {
            if (!f.isPadding)
            {
                ++optionCount;
            }
        }
        emitLine(out, 1, "static constexpr std::size_t UNION_OPTION_COUNT = " + std::to_string(optionCount) + "U;");
    }

    for (const auto& c : section.constants)
    {
        emitAttachedDocCpp(out, 1, c.doc);
        emitLine(out,
                 1,
                 "static constexpr auto " + sanitizeMacroToken(c.name) + " = " + valueToCppExpr(c.type, c.value) + ";");
    }

    emitArrayMetadata(out, typeName, section);

    emitLine(out,
             1,
             "LLVMDSDL_NODISCARD inline std::int8_t serialize(std::uint8_t* buffer, std::size_t* "
             "inout_buffer_size_bytes) "
             "const {");
    if (isPmrFlavor(flavor))
    {
        emitLine(out,
                 2,
                 "return " + typeName + "__serialize_(this, buffer, inout_buffer_size_bytes, _memory_resource);");
    }
    else
    {
        emitLine(out, 2, "return " + typeName + "__serialize_(this, buffer, inout_buffer_size_bytes);");
    }
    emitLine(out, 1, "}");

    emitLine(out,
             1,
             "LLVMDSDL_NODISCARD inline std::int8_t deserialize(const std::uint8_t* buffer, std::size_t* "
             "inout_buffer_size_bytes) {");
    if (isPmrFlavor(flavor))
    {
        emitLine(out,
                 2,
                 "return " + typeName + "__deserialize_(this, buffer, inout_buffer_size_bytes, _memory_resource);");
    }
    else
    {
        emitLine(out, 2, "return " + typeName + "__deserialize_(this, buffer, inout_buffer_size_bytes);");
    }
    emitLine(out, 1, "}");

    emitLine(out,
             1,
             "LLVMDSDL_NODISCARD static inline std::int8_t try_deserialize_view(const std::uint8_t* buffer, "
             "std::size_t* inout_buffer_size_bytes, const std::uint8_t** out_view_bytes) {");
    emitLine(out, 2, "return " + typeName + "__try_deserialize_view_(buffer, inout_buffer_size_bytes, out_view_bytes);");
    emitLine(out, 1, "}");
    emitLine(out,
             1,
             "LLVMDSDL_NODISCARD static inline std::int8_t try_serialize_view(const std::uint8_t* view_bytes, "
             "std::size_t view_size_bytes, std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes) {");
    emitLine(out,
             2,
             "return " + typeName +
                 "__try_serialize_view_(view_bytes, view_size_bytes, buffer, inout_buffer_size_bytes);");
    emitLine(out, 1, "}");

    if (isPmrFlavor(flavor))
    {
        emitLine(out,
                 1,
                 "LLVMDSDL_NODISCARD inline std::int8_t serialize(std::uint8_t* buffer, std::size_t* "
                 "inout_buffer_size_bytes, ::llvmdsdl::cpp::MemoryResource* memory_resource) const {");
        emitLine(out,
                 2,
                 "return " + typeName + "__serialize_(this, buffer, inout_buffer_size_bytes, memory_resource);");
        emitLine(out, 1, "}");

        emitLine(out,
                 1,
                 "LLVMDSDL_NODISCARD inline std::int8_t deserialize(const std::uint8_t* buffer, std::size_t* "
                 "inout_buffer_size_bytes, ::llvmdsdl::cpp::MemoryResource* memory_resource) {");
        emitLine(out,
                 2,
                 "return " + typeName + "__deserialize_(this, buffer, inout_buffer_size_bytes, memory_resource);");
        emitLine(out, 1, "}");
    }

    emitLine(out, 0, "};");
    out << "\n";
}

void emitViewFunctions(std::ostringstream& out, const std::string& typeName)
{
    emitLine(out,
             0,
             "inline std::int8_t " + typeName +
                 "__try_deserialize_view_(const std::uint8_t* const buffer, std::size_t* const "
                 "inout_buffer_size_bytes, const std::uint8_t** const out_view_bytes)");
    emitLine(out, 0, "{");
    emitLine(out, 1, "if ((buffer == nullptr) || (inout_buffer_size_bytes == nullptr) || (out_view_bytes == nullptr)) {");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "*out_view_bytes = nullptr;");
    emitLine(out, 1, "constexpr std::size_t required = " + typeName + "::SERIALIZATION_BUFFER_SIZE_BYTES;");
    emitLine(out, 1, "if (*inout_buffer_size_bytes < required) {");
    emitLine(out, 2, "*inout_buffer_size_bytes = required;");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "#if defined(LLVMDSDL_TARGET_ENDIANNESS_BIG)");
    emitLine(out, 2, "*inout_buffer_size_bytes = 0U;");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    emitLine(out, 1, "#else");
    emitLine(out, 2, "if (" + typeName + "::ZOH_ALIAS_ELIGIBLE) {");
    emitLine(out, 3, "*out_view_bytes = buffer;");
    emitLine(out, 3, "*inout_buffer_size_bytes = required;");
    emitLine(out, 3, "return DSDL_RUNTIME_SUCCESS;");
    emitLine(out, 2, "}");
    emitLine(out, 2, "*inout_buffer_size_bytes = 0U;");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    emitLine(out, 1, "#endif");
    emitLine(out, 0, "}");
    out << "\n";

    emitLine(out,
             0,
             "inline std::int8_t " + typeName +
                 "__try_serialize_view_(const std::uint8_t* const view_bytes, const std::size_t view_size_bytes, "
                 "std::uint8_t* const buffer, std::size_t* const inout_buffer_size_bytes)");
    emitLine(out, 0, "{");
    emitLine(out, 1, "if ((view_bytes == nullptr) || (buffer == nullptr) || (inout_buffer_size_bytes == nullptr)) {");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "constexpr std::size_t required = " + typeName + "::SERIALIZATION_BUFFER_SIZE_BYTES;");
    emitLine(out, 1, "if (view_size_bytes != required) {");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (*inout_buffer_size_bytes < required) {");
    emitLine(out, 2, "*inout_buffer_size_bytes = required;");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "#if defined(LLVMDSDL_TARGET_ENDIANNESS_BIG)");
    emitLine(out, 2, "*inout_buffer_size_bytes = 0U;");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    emitLine(out, 1, "#else");
    emitLine(out, 2, "if (" + typeName + "::ZOH_ALIAS_ELIGIBLE) {");
    emitLine(out, 3, "std::memcpy(buffer, view_bytes, required);");
    emitLine(out, 3, "*inout_buffer_size_bytes = required;");
    emitLine(out, 3, "return DSDL_RUNTIME_SUCCESS;");
    emitLine(out, 2, "}");
    emitLine(out, 2, "*inout_buffer_size_bytes = 0U;");
    emitLine(out, 2, "return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    emitLine(out, 1, "#endif");
    emitLine(out, 0, "}");
    out << "\n";
}

void emitSection(std::ostringstream&              out,
                 const EmitterContext&            ctx,
                 const SemanticDefinition&        def,
                 const std::string&               typeName,
                 const std::string&               fullName,
                 const SemanticSection&           section,
                 const CppFlavor                  flavor,
                 const AttachedDoc&               typeDoc,
                 const LoweredSectionFacts* const sectionFacts)
{
    emitFunctionPrototypes(out, typeName, flavor);
    emitSectionStruct(out,
                      typeName,
                      fullName,
                      def.info.majorVersion,
                      def.info.minorVersion,
                      section,
                      ctx,
                      flavor,
                      docWithDeprecationNotice(typeDoc, section.deprecated, def.info.fullName, def.info.majorVersion, def.info.minorVersion),
                      sectionFacts);

    const auto canonicalSectionName = fullName + "." + std::to_string(def.info.majorVersion) + "." +
                                      std::to_string(def.info.minorVersion);
    FunctionBodyEmitter bodyEmitter(ctx, flavor);
    ctx.traceSection(canonicalSectionName, EmitTraceDirection::Serialize);
    bodyEmitter.emitSerializeFunction(out, typeName, section, sectionFacts);
    ctx.traceSection(canonicalSectionName, EmitTraceDirection::Deserialize);
    bodyEmitter.emitDeserializeFunction(out, typeName, section, sectionFacts);
    emitViewFunctions(out, typeName);
}

llvm::Expected<std::string> loadCRuntimeHeader()
{
    if (const auto data = embedded_runtime::find("dsdl_runtime.h"))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "embedded runtime source missing: dsdl_runtime.h");
}

llvm::Expected<std::string> loadCppRuntimeHeader(const CppFlavor flavor)
{
    const std::string_view relativeRuntimeHeader =
        isAutosarFlavor(flavor) ? "cpp/autosar/dsdl_runtime.hpp" : "cpp/dsdl_runtime.hpp";
    if (const auto data = embedded_runtime::find(relativeRuntimeHeader))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "embedded runtime source missing: %s",
                                   std::string(relativeRuntimeHeader).c_str());
}

std::string renderHeader(const SemanticDefinition& def,
                         const EmitterContext&     ctx,
                         const CppFlavor           flavor,
                         const LoweredFactsMap&    loweredFacts)
{
    std::ostringstream out;
    const auto         guard        = headerGuard(def.info);
    const auto         baseTypeName = ctx.cppTypeName(def);

    out << generatedCommentLine("C++ backend") << "\n";
    out << "// Source: " << def.info.fullName << "." << def.info.majorVersion << "." << def.info.minorVersion << "\n\n";
    out << "#ifndef " << guard << "\n";
    out << "#define " << guard << "\n\n";
    out << "#include <array>\n";
    out << "#include <cstddef>\n";
    out << "#include <cstdint>\n";
    out << "#include <cstring>\n";
    out << "#include <utility>\n";
    if (!isAutosarFlavor(flavor))
    {
        out << "#include <vector>\n";
    }
    if (isPmrFlavor(flavor))
    {
        out << "#include <memory_resource>\n";
    }
    out << "#include \"dsdl_runtime.hpp\"\n";

    for (const auto& depRef : collectDefinitionCompositeDependencies(def))
    {
        if (const auto* dep = ctx.find(depRef))
        {
            out << "#include \"" << ctx.relativeHeaderPath(*dep) << "\"\n";
        }
    }
    out << "\n";

    // Generated code must never warn about itself; see the C backend for the three ways a deprecated
    // type is referenced from within its own generated file. The region closes before the include
    // guard, so user code naming the type still gets the diagnostic.
    if (ctx.emitDeprecationAttributes())
    {
        out << "#pragma GCC diagnostic push\n";
        out << "#pragma GCC diagnostic ignored \"-Wdeprecated-declarations\"\n\n";
    }

    emitNamespaceOpen(out, def.info.namespaceComponents);

    if (def.isService)
    {
        const auto requestType  = baseTypeName + "__Request";
        const auto responseType = baseTypeName + "__Response";

        emitLine(out, 0, "constexpr const char* " + baseTypeName + "_FULL_NAME = \"" + def.info.fullName + "\";");
        emitLine(out,
                 0,
                 "constexpr const char* " + baseTypeName + "_FULL_NAME_AND_VERSION = \"" + def.info.fullName + "." +
                     std::to_string(def.info.majorVersion) + "." + std::to_string(def.info.minorVersion) + "\";");
        out << "\n";

        emitSection(out,
                    ctx,
                    def,
                    requestType,
                    def.info.fullName + ".Request",
                    def.request,
                    flavor,
                    def.doc,
                    lookupLoweredSectionFacts(loweredFacts, def, "request"));
        if (def.response)
        {
            emitSection(out,
                        ctx,
                        def,
                        responseType,
                        def.info.fullName + ".Response",
                        *def.response,
                        flavor,
                        def.doc,
                        lookupLoweredSectionFacts(loweredFacts, def, "response"));
        }

        emitLine(out, 0, "using " + baseTypeName + " = " + requestType + ";");
        emitLine(out,
                 0,
                 "constexpr std::size_t " + baseTypeName + "_EXTENT_BYTES = " + requestType + "::EXTENT_BYTES;");
        emitLine(out,
                 0,
                 "constexpr std::size_t " + baseTypeName + "_SERIALIZATION_BUFFER_SIZE_BYTES = " + requestType +
                     "::SERIALIZATION_BUFFER_SIZE_BYTES;");
        emitLine(out,
                 0,
                 "constexpr bool " + baseTypeName + "_ZOH_ALIAS_ELIGIBLE = " + requestType + "::ZOH_ALIAS_ELIGIBLE;");
        emitLine(out,
                 0,
                 "constexpr const char* " + baseTypeName + "_ZOH_ALIAS_REASON = " + requestType + "::ZOH_ALIAS_REASON;");
        out << "\n";

        emitLine(out,
                 0,
                 "inline std::int8_t " + baseTypeName + "__serialize_(const " + baseTypeName +
                     "* const obj, std::uint8_t* const buffer, std::size_t* const "
                     "inout_buffer_size_bytes" +
                     (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* const memory_resource" : "") + ")");
        emitLine(out, 0, "{");
        emitLine(out,
                 1,
                 "return " + requestType + "__serialize_(reinterpret_cast<const " + requestType +
                     "*>(obj), buffer, inout_buffer_size_bytes" + (isPmrFlavor(flavor) ? ", memory_resource" : "") +
                     ");");
        emitLine(out, 0, "}");
        out << "\n";

        emitLine(out,
                 0,
                 "inline std::int8_t " + baseTypeName + "__deserialize_(" + baseTypeName +
                     "* const out_obj, const std::uint8_t* buffer, std::size_t* const "
                     "inout_buffer_size_bytes" +
                     (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* const memory_resource" : "") + ")");
        emitLine(out, 0, "{");
        emitLine(out,
                 1,
                 "return " + requestType + "__deserialize_(reinterpret_cast<" + requestType +
                     "*>(out_obj), buffer, inout_buffer_size_bytes" + (isPmrFlavor(flavor) ? ", memory_resource" : "") +
                     ");");
        emitLine(out, 0, "}");
        out << "\n";

        emitLine(out,
                 0,
                 "inline std::int8_t " + baseTypeName +
                     "__try_deserialize_view_(const std::uint8_t* const buffer, std::size_t* const "
                     "inout_buffer_size_bytes, const std::uint8_t** const out_view_bytes)");
        emitLine(out, 0, "{");
        emitLine(out,
                 1,
                 "return " + requestType + "__try_deserialize_view_(buffer, inout_buffer_size_bytes, out_view_bytes);");
        emitLine(out, 0, "}");
        out << "\n";

        emitLine(out,
                 0,
                 "inline std::int8_t " + baseTypeName +
                     "__try_serialize_view_(const std::uint8_t* const view_bytes, const std::size_t view_size_bytes, "
                     "std::uint8_t* const buffer, std::size_t* const inout_buffer_size_bytes)");
        emitLine(out, 0, "{");
        emitLine(out,
                 1,
                 "return " + requestType +
                     "__try_serialize_view_(view_bytes, view_size_bytes, buffer, inout_buffer_size_bytes);");
        emitLine(out, 0, "}");
    }
    else
    {
        emitSection(out,
                    ctx,
                    def,
                    baseTypeName,
                    def.info.fullName,
                    def.request,
                    flavor,
                    def.doc,
                    lookupLoweredSectionFacts(loweredFacts, def, ""));
    }

    emitNamespaceClose(out, def.info.namespaceComponents);
    if (ctx.emitDeprecationAttributes())
    {
        out << "\n#pragma GCC diagnostic pop\n";
    }
    out << "\n#endif /* " << guard << " */\n";
    return out.str();
}

llvm::Error emitProfile(const SemanticModule&                  semantic,
                        const std::filesystem::path&           outRoot,
                        const CppFlavor                        flavor,
                        const LoweredFactsMap&                 loweredFacts,
                        const CppEmitOptions&                  options,
                        const std::unordered_set<std::string>& selectedTypeKeys,
                        EmitTraceSink* const                   traceSink)
{
    auto cRuntime = loadCRuntimeHeader();
    if (!cRuntime)
    {
        return cRuntime.takeError();
    }
    if (auto err = writeGeneratedFile(outRoot / "dsdl_runtime.h",
                                      generatedCommentLine("C runtime scaffold for C++ backend") + "\n\n" + *cRuntime,
                                      options.writePolicy))
    {
        return err;
    }

    auto cppRuntime = loadCppRuntimeHeader(flavor);
    if (!cppRuntime)
    {
        return cppRuntime.takeError();
    }
    if (auto err = writeGeneratedFile(outRoot / "dsdl_runtime.hpp",
                                      generatedCommentLine("C++ runtime scaffold") + "\n\n" + *cppRuntime,
                                      options.writePolicy))
    {
        return err;
    }

    EmitterContext ctx(semantic, options.emitDeprecationAttributes);
    ctx.setTraceSink(traceSink);
    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys))
        {
            continue;
        }
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def.info)};

        std::filesystem::path dir = outRoot;
        for (const auto& ns : def.info.namespaceComponents)
        {
            dir /= ns;
        }
        if (auto err = writeGeneratedFile(dir / headerFileName(def.info),
                                          renderHeader(def, ctx, flavor, loweredFacts),
                                          options.writePolicy,
                                          requiredTypeKeys))
        {
            return err;
        }
    }

    return llvm::Error::success();
}

}  // namespace

llvm::Error emitCpp(const SemanticModule& semantic,
                    mlir::ModuleOp        module,
                    const CppEmitOptions& options,
                    DiagnosticEngine&     diagnostics,
                    EmitTraceSink*        traceSink)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }
    const auto mlirCoverageDiagnostic = codegen_diagnostic_text::mlirSchemaCoverageValidationFailedForEmission("C++");
    LoweredFactsMap loweredFacts;
    if (!collectLoweredFactsFromMlir(semantic,
                                     module,
                                     diagnostics,
                                     "C++",
                                     &loweredFacts,
                                     options.optimizeLoweredSerDes))
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "%s", mlirCoverageDiagnostic.c_str());
    }

    std::filesystem::path outRoot(options.outDir);
    const auto            selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    if (options.profile == CppProfile::Std)
    {
        return emitProfile(semantic, outRoot, CppFlavor::Std, loweredFacts, options, selectedTypeKeys, traceSink);
    }
    if (options.profile == CppProfile::Pmr)
    {
        return emitProfile(semantic, outRoot, CppFlavor::Pmr, loweredFacts, options, selectedTypeKeys, traceSink);
    }
    if (options.profile == CppProfile::Autosar)
    {
        return emitProfile(semantic, outRoot, CppFlavor::Autosar, loweredFacts, options, selectedTypeKeys, traceSink);
    }

    if (auto err =
            emitProfile(semantic, outRoot / "std", CppFlavor::Std, loweredFacts, options, selectedTypeKeys, traceSink))
    {
        return err;
    }
    return emitProfile(semantic, outRoot / "pmr", CppFlavor::Pmr, loweredFacts, options, selectedTypeKeys, traceSink);
}

}  // namespace llvmdsdl
