//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements Rust backend code emission from lowered DSDL modules.
///
/// The file maps lowering facts to Rust data types and serdes routines across supported runtime profiles.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/EmbeddedRuntimeSources.h"
#include "llvmdsdl/CodeGen/RustEmitter.h"

#include <llvm/ADT/StringRef.h>
#include <llvm/Support/Error.h>
#include <cassert>
#include <filesystem>
#include <fstream>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <unordered_map>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <system_error>
#include <utility>
#include <variant>

#include "llvmdsdl/CodeGen/ArrayWirePlan.h"
#include "llvmdsdl/CodeGen/CodegenDiagnosticText.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionDependencies.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/CodeGen/EmitStep.h"
#include "llvmdsdl/CodeGen/EmitTrace.h"
#include "llvmdsdl/CodeGen/HelperBindingRender.h"
#include "llvmdsdl/CodeGen/HelperSymbolResolver.h"
#include "llvmdsdl/CodeGen/LoweredRenderIR.h"
#include "llvmdsdl/CodeGen/LoweredFactsLookup.h"
#include "llvmdsdl/CodeGen/MlirLoweredFacts.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/HelperBindingNaming.h"
#include "llvmdsdl/CodeGen/NativeEmitterTraversal.h"
#include "llvmdsdl/CodeGen/NativeFunctionSkeleton.h"
#include "llvmdsdl/CodeGen/SerDesHelperDescriptors.h"
#include "llvmdsdl/CodeGen/StorageTypeTokens.h"
#include "llvmdsdl/CodeGen/TypeStorage.h"
#include "llvmdsdl/CodeGen/WireLayoutFacts.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/CodeGen/SectionHelperBindingPlan.h"
#include "llvmdsdl/CodeGen/SerDesStatementPlan.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/BitLengthSet.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Support/Rational.h"
#include "llvmdsdl/Version.h"
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl
{
class DiagnosticEngine;

namespace
{

std::string rustMemoryModeVariantPath(const RustEmitOptions& options)
{
    if (options.memoryMode == RustMemoryMode::InlineThenPool)
    {
        return "crate::dsdl_runtime::DsdlMemoryMode::InlineThenPool";
    }
    return "crate::dsdl_runtime::DsdlMemoryMode::MaxInline";
}

std::string unsignedStorageType(const std::uint32_t bitLength)
{
    return renderUnsignedStorageToken(StorageTokenLanguage::Rust, bitLength);
}

std::string signedStorageType(const std::uint32_t bitLength)
{
    return renderSignedStorageToken(StorageTokenLanguage::Rust, bitLength);
}

std::string rustConstValue(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(ConstantLiteralLanguage::Rust, value, makeConstantTypeInfo(type));
}

void emitLine(std::ostringstream& out, const int indent, const std::string& line)
{
    out << std::string(static_cast<std::size_t>(indent) * 4U, ' ') << line << '\n';
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return "// Generated by llvmdsdl " + std::string(llvmdsdl::kVersionString) + " (" + detail.str() + ").";
}

void emitAttachedDocRust(std::ostringstream& out, const int indent, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        emitLine(out, indent, "/// " + line.text);
    }
}

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule& semantic, const TypeNameVersioning typeNameVersioning)
        : index_(semantic)
        , typeNameVersioning_(typeNameVersioning)
    {
    }

    /// @brief Whether generated type names carry the definition's version.
    TypeNameVersioning typeNameVersioning() const
    {
        return typeNameVersioning_;
    }

    /// @brief Attaches an emit-order trace sink (for the emit-order verifier). Null (default) disables tracing at zero
    /// cost.
    void setTraceSink(EmitTraceSink* const sink)
    {
        traceSink_ = sink;
    }

    /// @brief Records one abstract emit op into the attached sink (no-op when unattached).
    template <typename PayloadT = std::int64_t>
    void trace(const EmitTraceOp op, const PayloadT payload = -1) const
    {
        emitTrace(traceSink_, op, static_cast<std::int64_t>(payload));
    }

    /// @brief Marks the start of one (type, direction) trace segment (no-op when unattached).
    void traceSection(const std::string& canonicalName, const EmitTraceDirection direction) const
    {
        emitTraceSection(traceSink_, canonicalName, direction);
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

    static std::string rustModuleName(const DiscoveredDefinition& info)
    {
        return renderDefinitionFileStem(CodegenNamingLanguage::Rust,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion);
    }

    std::string rustTypeName(const DiscoveredDefinition& info) const
    {
        return renderDefinitionTypeName(CodegenNamingLanguage::Rust,
                                        info.namespaceComponents,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion,
                                        typeNameVersioning_);
    }

    std::string rustTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return rustTypeName(def->info);
        }

        DiscoveredDefinition tmp;
        tmp.shortName           = ref.shortName;
        tmp.namespaceComponents = ref.namespaceComponents;
        tmp.majorVersion        = ref.majorVersion;
        tmp.minorVersion        = ref.minorVersion;
        return rustTypeName(tmp);
    }

    std::string rustTypePath(const SemanticTypeRef& ref) const
    {
        std::ostringstream out;
        out << "crate";
        for (const auto& ns : ref.namespaceComponents)
        {
            out << "::" << codegenProjectIdentifier(CodegenNamingLanguage::Rust, IdentifierRole::NamespaceName, ns);
        }

        if (const auto* def = find(ref))
        {
            out << "::" << rustModuleName(def->info) << "::" << rustTypeName(def->info);
            return out.str();
        }

        DiscoveredDefinition tmp;
        tmp.shortName           = ref.shortName;
        tmp.namespaceComponents = ref.namespaceComponents;
        tmp.majorVersion        = ref.majorVersion;
        tmp.minorVersion        = ref.minorVersion;
        out << "::" << rustModuleName(tmp) << "::" << rustTypeName(tmp);
        return out.str();
    }

private:
    DefinitionIndex    index_;
    TypeNameVersioning typeNameVersioning_{TypeNameVersioning::Unversioned};
    EmitTraceSink*     traceSink_ = nullptr;
};

std::string rustFieldBaseType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "bool";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
        return unsignedStorageType(type.bitLength);
    case SemanticScalarCategory::SignedInt:
        return signedStorageType(type.bitLength);
    case SemanticScalarCategory::Float:
        return type.bitLength == 64 ? "f64" : "f32";
    case SemanticScalarCategory::Void:
        return "u8";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.rustTypeName(*type.compositeType);
        }
        return "u8";
    }
    return "u8";
}

std::string rustFieldType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    const auto base = rustFieldBaseType(type, ctx);
    if (type.arrayKind == ArrayKind::None)
    {
        return base;
    }
    return "crate::dsdl_runtime::DsdlVec<" + base + ">";
}

std::string defaultExpr(const SemanticFieldType& type, const EmitterContext& ctx)
{
    if (type.arrayKind != ArrayKind::None)
    {
        return "crate::dsdl_runtime::DsdlVec::new()";
    }

    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "false";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
        return "0";
    case SemanticScalarCategory::SignedInt:
        return "0";
    case SemanticScalarCategory::Float:
        return type.bitLength == 64 ? "0.0f64" : "0.0f32";
    case SemanticScalarCategory::Void:
        return "0";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.rustTypeName(*type.compositeType) + "::default()";
        }
        return "0";
    }
    return "0";
}

class FunctionBodyEmitter final
{
public:
    explicit FunctionBodyEmitter(const EmitterContext&                               ctx,
                                 const std::unordered_map<std::string, std::string>& poolClassConstExprByField)
        : ctx_(ctx)
        , poolClassConstExprByField_(poolClassConstExprByField)
    {
    }

    /// @brief Records one abstract emit op via the shared EmitterContext sink (no-op when unattached).
    template <typename PayloadT = std::int64_t>
    void trace(const EmitTraceOp op, const PayloadT payload = -1) const
    {
        ctx_.trace(op, payload);
    }

    void emitSerialize(std::ostringstream&              out,
                       const std::string&               typeName,
                       const SemanticSection&           section,
                       const LoweredSectionFacts* const sectionFacts)
    {
        const NamingScope fieldScope = makeSectionFieldScope(CodegenNamingLanguage::Rust, section);
        (void) typeName;
        emitLine(out, 1, "pub fn serialize(&self, buffer: &mut [u8]) -> core::result::Result<usize, i8> {");
        emitLine(out, 2, "let mut offset_bits: usize = 0;");
        const auto emitted =
            emitNativeFunctionSkeleton(section,
                                       sectionFacts,
                                       HelperBindingDirection::Serialize,
                                       NativeFunctionSkeletonCallbacks{
                                           [&out](const SectionHelperBindingPlan& helperBindings) {
                                               emitSerializeMlirHelperBindings(out, helperBindings, 2);
                                           },
                                           [&out](const std::string& missingHelperRequirement) {
                                               emitLine(out,
                                                        2,
                                                        "// missing lowered helper contract: " +
                                                            missingHelperRequirement);
                                               emitLine(out,
                                                        2,
                                                        "return "
                                                        "Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_"
                                                        "ARGUMENT);");
                                           },
                                           [&out](const SectionHelperBindingPlan& helperBindings) {
                                               const auto capacityHelper =
                                                   helperBindingName(helperBindings.capacityCheck->symbol);
                                               emitLine(out,
                                                        2,
                                                        "let _err_capacity = " + capacityHelper +
                                                            "(buffer.len().saturating_mul(8) as i64);");
                                               emitLine(out,
                                                        2,
                                                        "if _err_capacity != "
                                                        "crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS {");
                                               emitLine(out, 3, "return Err(_err_capacity);");
                                               emitLine(out, 2, "}");
                                           },
                                           [this, &out, &section, sectionFacts, &fieldScope](
                                               const LoweredBodyRenderIR& renderIR) {
                                               NativeEmitterTraversalCallbacks callbacks;
                                               callbacks.onUnionDispatch =
                                                   [this, &out, &section, sectionFacts, &renderIR](
                                                       const std::vector<PlannedFieldStep>& unionBranches) {
                                                       emitSerializeUnion(out,
                                                                          section,
                                                                          unionBranches,
                                                                          2,
                                                                          sectionFacts,
                                                                          renderIR.helperBindings);
                                                   };
                                               callbacks.onFieldAlignment = [this,
                                                                             &out](const std::int64_t alignmentBits) {
                                                   emitAlignSerialize(out, alignmentBits, 2);
                                               };
                                               callbacks.onField = [this, &out, &fieldScope](
                                                                       const PlannedFieldStep& fieldStep) {
                                                   const auto* const field = fieldStep.field;
                                                   const auto        fieldRef =
                                                       "self." + fieldScope.get(IdentifierRole::FieldName, field->name);
                                                   emitSerializeAny(out,
                                                                    field->resolvedType,
                                                                    fieldRef,
                                                                    2,
                                                                    fieldStep.arrayLengthPrefixBits,
                                                                    fieldStep.fieldFacts);
                                               };
                                               callbacks.onPaddingAlignment = [this,
                                                                               &out](const std::int64_t alignmentBits) {
                                                   emitAlignSerialize(out, alignmentBits, 2);
                                               };
                                               callbacks.onPadding = [this, &out](const PlannedFieldStep& fieldStep) {
                                                   const auto* const field = fieldStep.field;
                                                   emitSerializePadding(out, field->resolvedType, 2);
                                               };
                                               return callbacks;
                                           },
                                           [this, &out]() {
                                               emitAlignSerialize(out, 8, 2);
                                               emitLine(out, 2, "Ok(offset_bits / 8)");
                                           }});
        if (!emitted)
        {
            emitLine(out, 1, "}");
            return;
        }
        emitLine(out, 1, "}");
    }

    void emitDeserialize(std::ostringstream&              out,
                         const std::string&               typeName,
                         const SemanticSection&           section,
                         const LoweredSectionFacts* const sectionFacts)
    {
        const NamingScope fieldScope = makeSectionFieldScope(CodegenNamingLanguage::Rust, section);
        (void) typeName;
        emitLine(out, 1, "pub fn deserialize(&mut self, buffer: &[u8]) -> core::result::Result<usize, i8> {");
        emitLine(out, 2, "let capacity_bytes = buffer.len();");
        emitLine(out, 2, "let capacity_bits = capacity_bytes.saturating_mul(8);\n");
        emitLine(out, 2, "let mut offset_bits: usize = 0;");
        const auto emitted =
            emitNativeFunctionSkeleton(section,
                                       sectionFacts,
                                       HelperBindingDirection::Deserialize,
                                       NativeFunctionSkeletonCallbacks{
                                           [&out](const SectionHelperBindingPlan& helperBindings) {
                                               emitDeserializeMlirHelperBindings(out, helperBindings, 2);
                                           },
                                           [&out](const std::string& missingHelperRequirement) {
                                               emitLine(out,
                                                        2,
                                                        "// missing lowered helper contract: " +
                                                            missingHelperRequirement);
                                               emitLine(out,
                                                        2,
                                                        "return "
                                                        "Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_"
                                                        "ARGUMENT);");
                                           },
                                           nullptr,
                                           [this, &out, &section, sectionFacts, &fieldScope](
                                               const LoweredBodyRenderIR& renderIR) {
                                               NativeEmitterTraversalCallbacks callbacks;
                                               callbacks.onUnionDispatch =
                                                   [this, &out, &section, sectionFacts, &renderIR](
                                                       const std::vector<PlannedFieldStep>& unionBranches) {
                                                       emitDeserializeUnion(out,
                                                                            section,
                                                                            unionBranches,
                                                                            2,
                                                                            sectionFacts,
                                                                            renderIR.helperBindings);
                                                   };
                                               callbacks.onFieldAlignment = [this,
                                                                             &out](const std::int64_t alignmentBits) {
                                                   emitAlignDeserialize(out, alignmentBits, 2);
                                               };
                                               callbacks.onField = [this, &out, &fieldScope](
                                                                       const PlannedFieldStep& fieldStep) {
                                                   const auto* const field = fieldStep.field;
                                                   const auto        fieldRef =
                                                       "self." + fieldScope.get(IdentifierRole::FieldName, field->name);
                                                   emitDeserializeAny(out,
                                                                      field->resolvedType,
                                                                      fieldRef,
                                                                      2,
                                                                      fieldStep.arrayLengthPrefixBits,
                                                                      fieldStep.fieldFacts,
                                                                      poolClassConstExprForField(field->name));
                                               };
                                               callbacks.onPaddingAlignment = [this,
                                                                               &out](const std::int64_t alignmentBits) {
                                                   emitAlignDeserialize(out, alignmentBits, 2);
                                               };
                                               callbacks.onPadding = [this, &out](const PlannedFieldStep& fieldStep) {
                                                   const auto* const field = fieldStep.field;
                                                   emitDeserializePadding(out, field->resolvedType, 2);
                                               };
                                               return callbacks;
                                           },
                                           [this, &out]() {
                                               emitAlignDeserialize(out, 8, 2);
                                               emitLine(out,
                                                        2,
                                                        "Ok(crate::dsdl_runtime::choose_min(offset_bits, "
                                                        "capacity_bits) / 8)");
                                           }});
        if (!emitted)
        {
            emitLine(out, 1, "}");
            return;
        }
        emitLine(out, 1, "}");
        emitLine(out, 0, "");
        emitLine(out, 1, "pub fn deserialize_with_consumed(&mut self, buffer: &[u8]) -> (i8, usize) {");
        emitLine(out, 2, "match self.deserialize(buffer) {");
        emitLine(out, 3, "Ok(consumed) => (0, consumed),");
        emitLine(out, 3, "Err(rc) => (rc, buffer.len()),");
        emitLine(out, 2, "}");
        emitLine(out, 1, "}");
    }

private:
    const EmitterContext&                               ctx_;
    const std::unordered_map<std::string, std::string>& poolClassConstExprByField_;
    std::size_t                                         id_{0};

    std::string poolClassConstExprForField(const std::string& fieldName) const
    {
        const auto it = poolClassConstExprByField_.find(fieldName);
        if (it == poolClassConstExprByField_.end())
        {
            return "crate::dsdl_runtime::AllocationClassId(0u32)";
        }
        return it->second;
    }

    std::string nextName(const std::string& prefix)
    {
        return "_" + prefix + std::to_string(id_++) + "_";
    }

    static std::string helperBindingName(const std::string& helperSymbol)
    {
        return renderHelperBindingIdentifier(CodegenNamingLanguage::Rust, helperSymbol);
    }

    static void emitSerializeMlirHelperBindings(std::ostringstream&             out,
                                                const SectionHelperBindingPlan& plan,
                                                const int                       indent)
    {
        for (const auto& line : renderSectionHelperBindings(
                 plan,
                 HelperBindingRenderLanguage::Rust,
                 ScalarBindingRenderDirection::Serialize,
                 [](const std::string& symbol) { return helperBindingName(symbol); },
                 /*emitCapacityCheck=*/true))
        {
            emitLine(out, indent, line);
        }
    }

    static void emitDeserializeMlirHelperBindings(std::ostringstream&             out,
                                                  const SectionHelperBindingPlan& plan,
                                                  const int                       indent)
    {
        for (const auto& line : renderSectionHelperBindings(
                 plan,
                 HelperBindingRenderLanguage::Rust,
                 ScalarBindingRenderDirection::Deserialize,
                 [](const std::string& symbol) { return helperBindingName(symbol); },
                 /*emitCapacityCheck=*/false))
        {
            emitLine(out, indent, line);
        }
    }

    void emitAlignSerialize(std::ostringstream& out, const std::int64_t alignmentBits, const int indent)
    {
        if (alignmentBits <= 1)
        {
            return;
        }
        trace(EmitTraceOp::Align, alignmentBits);
        const auto err = nextName("err");
        emitLine(out, indent, "while (offset_bits % " + std::to_string(alignmentBits) + "usize) != 0 {");
        emitLine(out, indent + 1, "let " + err + " = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);");
        emitLine(out, indent + 1, "if " + err + " < 0 { return Err(" + err + "); }");
        emitLine(out, indent + 1, "offset_bits += 1;");
        emitLine(out, indent, "}");
    }

    void emitAlignDeserialize(std::ostringstream& out, const std::int64_t alignmentBits, const int indent) const
    {
        if (alignmentBits <= 1)
        {
            return;
        }
        trace(EmitTraceOp::Align, alignmentBits);
        emitLine(out,
                 indent,
                 "offset_bits = (offset_bits + " + std::to_string(alignmentBits - 1) + ") & !" +
                     std::to_string(alignmentBits - 1) + "usize;");
    }

    void emitSerializePadding(std::ostringstream& out, const SemanticFieldType& type, const int indent)
    {
        if (type.bitLength == 0)
        {
            return;
        }
        trace(EmitTraceOp::Pad, type.bitLength);
        const auto err = nextName("err");
        emitLine(out,
                 indent,
                 "let " + err + " = crate::dsdl_runtime::set_uxx(buffer, offset_bits, 0, " +
                     std::to_string(type.bitLength) + "u8);");
        emitLine(out, indent, "if " + err + " < 0 { return Err(" + err + "); }");
        trace(EmitTraceOp::Advance, type.bitLength);
        emitLine(out, indent, "offset_bits += " + std::to_string(type.bitLength) + ";");
    }

    void emitDeserializePadding(std::ostringstream& out, const SemanticFieldType& type, const int indent) const
    {
        if (type.bitLength == 0)
        {
            return;
        }
        trace(EmitTraceOp::Pad, type.bitLength);
        trace(EmitTraceOp::Advance, type.bitLength);
        emitLine(out, indent, "offset_bits += " + std::to_string(type.bitLength) + ";");
    }

    /// @brief Rust spelling of the shared union-prologue steps (see EmitStep.h).
    class UnionSpelling final : public UnionSectionSpelling
    {
    public:
        UnionSpelling(FunctionBodyEmitter&            owner,
                      std::ostringstream&             out,
                      const int                       indent,
                      const std::int64_t              tagBits,
                      const SectionHelperBindingPlan& helperBindings)
            : owner_(owner)
            , out_(out)
            , indent_(indent)
            , tagBits_(tagBits)
            , helperBindings_(helperBindings)
        {
        }

        void spellSerializeValidateTag() override
        {
            const auto validateHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(helperBindings_.unionTagValidate->symbol);
            owner_.trace(EmitTraceOp::ValidateTag);
            emitLine(out_, indent_, "let _err_union_tag = " + validateHelper + "(self._tag_ as i64);");
            emitLine(out_,
                     indent_,
                     "if _err_union_tag != crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS { return Err(_err_union_tag); }");
        }

        void spellSerializeWriteMaskedTag() override
        {
            const auto tagHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(helperBindings_.unionTagMask->symbol);
            const auto tagExpr = tagHelper + "(self._tag_ as u64)";
            const auto tagErr  = owner_.nextName("err");
            owner_.trace(EmitTraceOp::MaskTag);
            owner_.trace(EmitTraceOp::WriteTag, tagBits_);
            emitLine(out_,
                     indent_,
                     "let " + tagErr + " = crate::dsdl_runtime::set_uxx(buffer, offset_bits, " + tagExpr + ", " +
                         std::to_string(tagBits_) + "u8);");
            emitLine(out_, indent_, "if " + tagErr + " < 0 { return Err(" + tagErr + "); }");
        }

        void spellDeserializeReadMaskStoreTag() override
        {
            const auto rawTag = owner_.nextName("tag_raw");
            owner_.trace(EmitTraceOp::ReadTag, tagBits_);
            emitLine(out_,
                     indent_,
                     "let " + rawTag + " = crate::dsdl_runtime::get_u64(buffer, offset_bits, " +
                         std::to_string(tagBits_) + "u8);");
            const auto tagHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(helperBindings_.unionTagMask->symbol);
            owner_.trace(EmitTraceOp::MaskTag);
            owner_.trace(EmitTraceOp::StoreTag);
            emitLine(out_,
                     indent_,
                     "self._tag_ = (" + tagHelper + "(" + rawTag + ")) as " +
                         unsignedStorageType(static_cast<std::uint32_t>(tagBits_)) + ";");
        }

        void spellDeserializeValidateTag() override
        {
            const auto validateHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(helperBindings_.unionTagValidate->symbol);
            owner_.trace(EmitTraceOp::ValidateTag);
            emitLine(out_, indent_, "let _err_union_tag = " + validateHelper + "(self._tag_ as i64);");
            emitLine(out_,
                     indent_,
                     "if _err_union_tag != crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS { return Err(_err_union_tag); }");
        }

        void spellAdvanceTag() override
        {
            owner_.trace(EmitTraceOp::Advance, tagBits_);
            emitLine(out_, indent_, "offset_bits += " + std::to_string(tagBits_) + ";");
        }

        void spellBeginDispatch() override
        {
            owner_.trace(EmitTraceOp::Switch);
            emitLine(out_, indent_, "match self._tag_ {");
        }

        void spellBeginCase(const std::int64_t optionIndex, const bool /*firstCase*/) override
        {
            owner_.trace(EmitTraceOp::Case, optionIndex);
            emitLine(out_, indent_ + 1, std::to_string(optionIndex) + " => {");
        }

        void spellEndCase() override
        {
            emitLine(out_, indent_ + 1, "}");
        }

        void spellBadTagDefault() override
        {
            owner_.trace(EmitTraceOp::DefaultBadTag);
            emitLine(out_,
                     indent_ + 1,
                     "_ => return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG),");
        }

        void spellEndDispatch() override
        {
            emitLine(out_, indent_, "}");
        }

    private:
        FunctionBodyEmitter&            owner_;
        std::ostringstream&             out_;
        const int                       indent_;
        const std::int64_t              tagBits_;
        const SectionHelperBindingPlan& helperBindings_;
    };

    void emitSerializeUnion(std::ostringstream&                  out,
                            const SemanticSection&               section,
                            const std::vector<PlannedFieldStep>& unionBranches,
                            const int                            indent,
                            const LoweredSectionFacts* const     sectionFacts,
                            const SectionHelperBindingPlan&      helperBindings)
    {
        const NamingScope            fieldScope = makeSectionFieldScope(CodegenNamingLanguage::Rust, section);
        const auto                   tagBits    = resolveUnionTagBits(section, sectionFacts);
        UnionSpelling                spelling(*this, out, indent, static_cast<std::int64_t>(tagBits), helperBindings);
        std::vector<UnionCaseRender> cases;
        cases.reserve(unionBranches.size());
        for (const auto& step : unionBranches)
        {
            const auto& field = *step.field;
            cases.push_back(
                UnionCaseRender{field.unionOptionIndex, [this, &out, indent, &step, &field, &fieldScope]() {
                                    emitAlignSerialize(out, field.resolvedType.alignmentBits, indent + 2);
                                    emitSerializeAny(out,
                                                     field.resolvedType,
                                                     "self." + fieldScope.get(IdentifierRole::FieldName, field.name),
                                                     indent + 2,
                                                     step.arrayLengthPrefixBits,
                                                     step.fieldFacts);
                                }});
        }
        renderUnionSection(EmitTraceDirection::Serialize, cases, spelling);
    }

    void emitDeserializeUnion(std::ostringstream&                  out,
                              const SemanticSection&               section,
                              const std::vector<PlannedFieldStep>& unionBranches,
                              const int                            indent,
                              const LoweredSectionFacts* const     sectionFacts,
                              const SectionHelperBindingPlan&      helperBindings)
    {
        const NamingScope            fieldScope = makeSectionFieldScope(CodegenNamingLanguage::Rust, section);
        const auto                   tagBits    = resolveUnionTagBits(section, sectionFacts);
        UnionSpelling                spelling(*this, out, indent, static_cast<std::int64_t>(tagBits), helperBindings);
        std::vector<UnionCaseRender> cases;
        cases.reserve(unionBranches.size());
        for (const auto& step : unionBranches)
        {
            const auto& field = *step.field;
            cases.push_back(
                UnionCaseRender{field.unionOptionIndex, [this, &out, indent, &step, &field, &fieldScope]() {
                                    emitAlignDeserialize(out, field.resolvedType.alignmentBits, indent + 2);
                                    emitDeserializeAny(out,
                                                       field.resolvedType,
                                                       "self." + fieldScope.get(IdentifierRole::FieldName, field.name),
                                                       indent + 2,
                                                       step.arrayLengthPrefixBits,
                                                       step.fieldFacts,
                                                       poolClassConstExprForField(field.name));
                                }});
        }
        renderUnionSection(EmitTraceDirection::Deserialize, cases, spelling);
    }

    /// @brief Rust spelling of the shared recursive field-body steps (see EmitStep.h).
    ///
    /// Leaf statement idioms only; all cross-group and recursive ordering comes
    /// from renderFieldSteps. Constructed per field render with the direction and
    /// (for deserialize) the pool-class expression.
    class FieldSpelling final : public FieldStepSpelling
    {
    public:
        FieldSpelling(FunctionBodyEmitter&         owner,
                      std::ostringstream&          out,
                      const int                    indent,
                      const HelperBindingDirection direction,
                      std::string                  poolClassConstExpr)
            : owner_(owner)
            , out_(out)
            , indent_(indent)
            , direction_(direction)
            , poolClassConstExpr_(std::move(poolClassConstExpr))
        {
        }

        void spellPad(const FieldEmitStep& step) override
        {
            if (direction_ == HelperBindingDirection::Serialize)
            {
                owner_.emitSerializePadding(out_, step.type, indent_);
            }
            else
            {
                owner_.emitDeserializePadding(out_, step.type, indent_);
            }
        }

        void spellScalarSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            switch (step.kind)
            {
            case FieldStepKind::ScalarBool: {
                const auto err = owner_.nextName("err");
                owner_.trace(EmitTraceOp::WriteScalarBool, 1);
                emitLine(out_,
                         indent_,
                         "let " + err + " = crate::dsdl_runtime::set_bit(buffer, offset_bits, " + expr + ");");
                emitLine(out_, indent_, "if " + err + " < 0 { return Err(" + err + "); }");
                owner_.trace(EmitTraceOp::Advance, 1);
                emitLine(out_, indent_, "offset_bits += 1;");
                break;
            }
            case FieldStepKind::ScalarUint: {
                std::string valueExpr = expr + " as u64";
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.scalarHelperSymbol);
                valueExpr         = helper + "(" + valueExpr + ")";

                const auto err = owner_.nextName("err");
                owner_.trace(EmitTraceOp::WriteScalarUint, step.bits);
                emitLine(out_,
                         indent_,
                         "let " + err + " = crate::dsdl_runtime::set_uxx(buffer, offset_bits, " + valueExpr + ", " +
                             std::to_string(step.bits) + "u8);");
                emitLine(out_, indent_, "if " + err + " < 0 { return Err(" + err + "); }");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + ";");
                break;
            }
            case FieldStepKind::ScalarSint: {
                std::string valueExpr = expr + " as i64";
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.scalarHelperSymbol);
                valueExpr         = helper + "(" + valueExpr + ")";

                const auto err = owner_.nextName("err");
                owner_.trace(EmitTraceOp::WriteScalarSint, step.bits);
                emitLine(out_,
                         indent_,
                         "let " + err + " = crate::dsdl_runtime::set_ixx(buffer, offset_bits, " + valueExpr + ", " +
                             std::to_string(step.bits) + "u8);");
                emitLine(out_, indent_, "if " + err + " < 0 { return Err(" + err + "); }");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + ";");
                break;
            }
            case FieldStepKind::ScalarFloat: {
                const auto  err            = owner_.nextName("err");
                const auto  floatType      = std::string(step.bits == 64 ? "f64" : "f32");
                std::string normalizedExpr = expr + " as " + floatType;
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.scalarHelperSymbol);
                normalizedExpr    = helper + "(" + normalizedExpr + ")";
                std::string setCall;
                if (step.bits == 16)
                {
                    setCall = "crate::dsdl_runtime::set_f16(buffer, offset_bits, " + normalizedExpr + ")";
                }
                else if (step.bits == 32)
                {
                    setCall = "crate::dsdl_runtime::set_f32(buffer, offset_bits, " + normalizedExpr + ")";
                }
                else
                {
                    setCall = "crate::dsdl_runtime::set_f64(buffer, offset_bits, " + normalizedExpr + ")";
                }
                owner_.trace(EmitTraceOp::WriteScalarFloat, step.bits);
                emitLine(out_, indent_, "let " + err + " = " + setCall + ";");
                emitLine(out_, indent_, "if " + err + " < 0 { return Err(" + err + "); }");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + ";");
                break;
            }
            default:
                assert(false && "not a scalar step");
                break;
            }
        }

        void spellScalarDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            switch (step.kind)
            {
            case FieldStepKind::ScalarBool:
                owner_.trace(EmitTraceOp::ReadScalarBool, 1);
                emitLine(out_, indent_, expr + " = crate::dsdl_runtime::get_bit(buffer, offset_bits);");
                owner_.trace(EmitTraceOp::Advance, 1);
                emitLine(out_, indent_, "offset_bits += 1;");
                break;
            case FieldStepKind::ScalarUint: {
                const std::string getter =
                    "get_u" + std::string(scalarWidthSuffix(static_cast<std::uint32_t>(step.bits)));
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.scalarHelperSymbol);
                const auto raw    = owner_.nextName("raw");
                owner_.trace(EmitTraceOp::ReadScalarUint, step.bits);
                emitLine(out_,
                         indent_,
                         "let " + raw + " = crate::dsdl_runtime::" + getter + "(buffer, offset_bits, " +
                             std::to_string(step.bits) + "u8) as u64;");
                emitLine(out_,
                         indent_,
                         expr + " = " + helper + "(" + raw + ") as " +
                             unsignedStorageType(static_cast<std::uint32_t>(step.bits)) + ";");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + ";");
                break;
            }
            case FieldStepKind::ScalarSint: {
                const std::string getter =
                    "get_i" + std::string(scalarWidthSuffix(static_cast<std::uint32_t>(step.bits)));
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.scalarHelperSymbol);
                const auto raw    = owner_.nextName("raw");
                owner_.trace(EmitTraceOp::ReadScalarSint, step.bits);
                emitLine(out_,
                         indent_,
                         "let " + raw + " = crate::dsdl_runtime::get_u64(buffer, offset_bits, " +
                             std::to_string(step.bits) + "u8) as i64;");
                emitLine(out_,
                         indent_,
                         expr + " = " + helper + "(" + raw + ") as " +
                             signedStorageType(static_cast<std::uint32_t>(step.bits)) + ";");
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + ";");
                break;
            }
            case FieldStepKind::ScalarFloat: {
                assert(!step.scalarHelperSymbol.empty());
                const auto helper = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.scalarHelperSymbol);
                owner_.trace(EmitTraceOp::ReadScalarFloat, step.bits);
                if (step.bits == 16)
                {
                    emitLine(out_,
                             indent_,
                             expr + " = " + helper +
                                 "(crate::dsdl_runtime::get_f16(buffer, offset_bits) as f32) as f32;");
                }
                else if (step.bits == 32)
                {
                    emitLine(out_,
                             indent_,
                             expr + " = " + helper +
                                 "(crate::dsdl_runtime::get_f32(buffer, offset_bits) as f32) as f32;");
                }
                else
                {
                    emitLine(out_,
                             indent_,
                             expr + " = " + helper +
                                 "(crate::dsdl_runtime::get_f64(buffer, offset_bits) as f64) as f64;");
                }
                owner_.trace(EmitTraceOp::Advance, step.bits);
                emitLine(out_, indent_, "offset_bits += " + std::to_string(step.bits) + ";");
                break;
            }
            default:
                assert(false && "not a scalar step");
                break;
            }
        }

        void spellFixedArrayLenCheck(const FieldEmitStep& step, const std::string& expr) override
        {
            owner_.trace(EmitTraceOp::LenCheck, step.capacity);
            emitLine(out_,
                     indent_,
                     "if " + expr + ".len() != " + std::to_string(step.capacity) +
                         "usize { return "
                         "Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_ARRAY_LENGTH); }");
        }

        void spellVariableArrayLenSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            assert(step.arrayHelpers.has_value());
            assert(!step.arrayHelpers->validateSymbol.empty());
            const auto validateHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(step.arrayHelpers->validateSymbol);
            const auto validateRc = owner_.nextName("len_rc");
            owner_.trace(EmitTraceOp::LenValidate, step.prefixBits);
            emitLine(out_, indent_, "let " + validateRc + " = " + validateHelper + "(" + expr + ".len() as i64);");
            emitLine(out_, indent_, "if " + validateRc + " < 0 { return Err(" + validateRc + "); }");
            std::string prefixExpr = expr + ".len() as u64";
            assert(!step.arrayHelpers->prefixSymbol.empty());
            const auto serPrefixHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(step.arrayHelpers->prefixSymbol);
            prefixExpr     = serPrefixHelper + "(" + prefixExpr + ")";
            const auto err = owner_.nextName("err");
            owner_.trace(EmitTraceOp::LenWrite, step.prefixBits);
            emitLine(out_,
                     indent_,
                     "let " + err + " = crate::dsdl_runtime::set_uxx(buffer, offset_bits, " + prefixExpr + ", " +
                         std::to_string(step.prefixBits) + "u8);");
            emitLine(out_, indent_, "if " + err + " < 0 { return Err(" + err + "); }");
            owner_.trace(EmitTraceOp::Advance, step.prefixBits);
            emitLine(out_, indent_, "offset_bits += " + std::to_string(step.prefixBits) + ";");
        }

        std::string spellVariableArrayLenDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            emitPoolContract(expr);
            const auto count    = owner_.nextName("count");
            const auto rawCount = owner_.nextName("count_raw");
            owner_.trace(EmitTraceOp::LenRead, step.prefixBits);
            emitLine(out_,
                     indent_,
                     "let " + rawCount + " = crate::dsdl_runtime::get_u64(buffer, offset_bits, " +
                         std::to_string(step.prefixBits) + "u8);");
            owner_.trace(EmitTraceOp::Advance, step.prefixBits);
            emitLine(out_, indent_, "offset_bits += " + std::to_string(step.prefixBits) + ";");
            std::string countExpr = rawCount + " as usize";
            assert(step.arrayHelpers.has_value());
            assert(!step.arrayHelpers->prefixSymbol.empty());
            const auto deserPrefixHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(step.arrayHelpers->prefixSymbol);
            countExpr = deserPrefixHelper + "(" + rawCount + ") as usize";
            emitLine(out_, indent_, "let " + count + " = " + countExpr + ";");
            assert(!step.arrayHelpers->validateSymbol.empty());
            const auto validateHelper =
                llvmdsdl::FunctionBodyEmitter::helperBindingName(step.arrayHelpers->validateSymbol);
            const auto validateRc = owner_.nextName("len_rc");
            owner_.trace(EmitTraceOp::LenValidate, step.prefixBits);
            emitLine(out_, indent_, "let " + validateRc + " = " + validateHelper + "(" + count + " as i64);");
            emitLine(out_, indent_, "if " + validateRc + " < 0 { return Err(" + validateRc + "); }");
            emitClearReserve(expr, count);
            return count;
        }

        std::string spellFixedArrayCountDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            emitPoolContract(expr);
            const auto count = owner_.nextName("count");
            emitLine(out_, indent_, "let " + count + " = " + std::to_string(step.capacity) + "usize;");
            emitClearReserve(expr, count);
            return count;
        }

        std::string spellBeginElemLoopSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            const auto index = owner_.nextName("index");
            const auto count =
                step.kind == FieldStepKind::VariableArray ? (expr + ".len()") : std::to_string(step.capacity) + "usize";

            owner_.trace(EmitTraceOp::ElemLoop);
            emitLine(out_, indent_, "for " + index + " in 0.." + count + " {");
            ++indent_;
            return expr + "[" + index + "]";
        }

        std::string spellBeginElemLoopDeserialize(const FieldEmitStep& step,
                                                  const std::string&   expr,
                                                  const std::string&   countExpr) override
        {
            (void) expr;
            const auto index = owner_.nextName("index");
            owner_.trace(EmitTraceOp::ElemLoop);
            emitLine(out_, indent_, "for " + index + " in 0.." + countExpr + " {");
            ++indent_;
            assert(itemVar_.empty() && "DSDL forbids arrays of arrays; loops never nest");
            itemVar_ = owner_.nextName("item");
            emitLine(out_,
                     indent_,
                     "let mut " + itemVar_ + " = " + defaultExpr(step.children.front().type, owner_.ctx_) + ";");
            return itemVar_;
        }

        void spellEndElemLoopSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            (void) step;
            (void) expr;
            --indent_;
            emitLine(out_, indent_, "}");
        }

        void spellEndElemLoopDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            (void) step;
            emitLine(out_, indent_, expr + ".push(" + itemVar_ + ");");
            itemVar_.clear();
            --indent_;
            emitLine(out_, indent_, "}");
        }

        void spellCompositeSerialize(const FieldEmitStep& step, const std::string& expr) override
        {
            owner_.trace(step.type.compositeSealed ? EmitTraceOp::CompositeInline : EmitTraceOp::CompositeDelimHeader);
            const auto sizeVar = owner_.nextName("size_bytes");
            const auto errVar  = owner_.nextName("err");

            if (!step.type.compositeSealed)
            {
                emitLine(out_, indent_, "offset_bits += 32;  // Delimiter header");
            }

            emitLine(out_,
                     indent_,
                     "let mut " + sizeVar + " = " + std::to_string((step.type.bitLengthSet.max() + 7) / 8) + "usize;");
            if (!step.type.compositeSealed)
            {
                emitLine(out_,
                         indent_,
                         "let _remaining = "
                         "buffer.len().saturating_sub(crate::dsdl_runtime::choose_min(offset_bits / 8, "
                         "buffer.len()));");
                assert(!step.delimiterValidateSymbol.empty());
                const auto helper     = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.delimiterValidateSymbol);
                const auto validateRc = owner_.nextName("rc");
                emitLine(out_,
                         indent_,
                         "let " + validateRc + " = " + helper + "(" + sizeVar + " as i64, _remaining as i64);");
                emitLine(out_, indent_, "if " + validateRc + " < 0 { return Err(" + validateRc + "); }");
            }
            emitLine(out_, indent_, "let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());");
            emitLine(out_, indent_, "let _end = _start.saturating_add(" + sizeVar + ").min(buffer.len());");
            emitLine(out_, indent_, "let " + errVar + " = " + expr + ".serialize(&mut buffer[_start.._end]);");
            emitLine(out_, indent_, "match " + errVar + " {");
            emitLine(out_, indent_ + 1, "Ok(v) => " + sizeVar + " = v,");
            emitLine(out_, indent_ + 1, "Err(e) => return Err(e),");
            emitLine(out_, indent_, "}");

            if (!step.type.compositeSealed)
            {
                const auto hdrErr = owner_.nextName("err");
                emitLine(out_,
                         indent_,
                         "let " + hdrErr + " = crate::dsdl_runtime::set_uxx(buffer, offset_bits - 32, " + sizeVar +
                             " as u64, 32u8);");
                emitLine(out_, indent_, "if " + hdrErr + " < 0 { return Err(" + hdrErr + "); }");
            }

            emitLine(out_, indent_, "offset_bits += " + sizeVar + " * 8;");
        }

        void spellCompositeDeserialize(const FieldEmitStep& step, const std::string& expr) override
        {
            owner_.trace(step.type.compositeSealed ? EmitTraceOp::CompositeInline : EmitTraceOp::CompositeDelimHeader);
            const auto sizeVar = owner_.nextName("size_bytes");

            if (!step.type.compositeSealed)
            {
                emitLine(out_,
                         indent_,
                         "let " + sizeVar + " = crate::dsdl_runtime::get_u32(buffer, offset_bits, 32u8) as usize;");
                emitLine(out_, indent_, "offset_bits += 32;");
                emitLine(out_,
                         indent_,
                         "let _remaining = "
                         "capacity_bytes.saturating_sub(crate::dsdl_runtime::choose_min(offset_bits / 8, "
                         "capacity_bytes));");
                assert(!step.delimiterValidateSymbol.empty());
                const auto helper     = llvmdsdl::FunctionBodyEmitter::helperBindingName(step.delimiterValidateSymbol);
                const auto validateRc = owner_.nextName("rc");
                emitLine(out_,
                         indent_,
                         "let " + validateRc + " = " + helper + "(" + sizeVar + " as i64, _remaining as i64);");
                emitLine(out_, indent_, "if " + validateRc + " < 0 { return Err(" + validateRc + "); }");
                emitLine(out_, indent_, "let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());");
                emitLine(out_, indent_, "let _end = _start.saturating_add(" + sizeVar + ").min(buffer.len());");
                emitLine(out_,
                         indent_,
                         "if let Err(e) = " + expr + ".deserialize(&buffer[_start.._end]) { return Err(e); }");
                emitLine(out_, indent_, "offset_bits += " + sizeVar + " * 8;");
                return;
            }

            emitLine(out_, indent_, "let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());");
            emitLine(out_, indent_, "let _slice = &buffer[_start..buffer.len()];");
            emitLine(out_,
                     indent_,
                     "let _consumed = match " + expr +
                         ".deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };\n");
            emitLine(out_, indent_, "offset_bits += _consumed * 8;");
        }

    private:
        void emitPoolContract(const std::string& expr)
        {
            if (!poolClassConstExpr_.empty())
            {
                emitLine(out_,
                         indent_,
                         expr +
                             ".set_memory_contract(crate::dsdl_runtime::VarArrayMemoryContract::new("
                             "Self::__LLVMDSDL_MEMORY_MODE, "
                             "Self::__LLVMDSDL_INLINE_THRESHOLD_BYTES, " +
                             poolClassConstExpr_ + "));");
            }
        }

        void emitClearReserve(const std::string& expr, const std::string& count)
        {
            emitLine(out_, indent_, expr + ".clear();");
            emitLine(out_,
                     indent_,
                     "if Self::__LLVMDSDL_MEMORY_MODE == "
                     "crate::dsdl_runtime::DsdlMemoryMode::InlineThenPool {");
            emitLine(out_, indent_ + 1, "let mut _pool = crate::dsdl_runtime::PassthroughPoolProvider::default();");
            emitLine(out_,
                     indent_ + 1,
                     "if let Err(_alloc_err) = " + expr + ".reserve_with_pool(" + count +
                         ", &mut _pool)"
                         " {");
            emitLine(out_,
                     indent_ + 2,
                     "return Err(-crate::dsdl_runtime::allocation_error_to_runtime_code(_alloc_err));");
            emitLine(out_, indent_ + 1, "}");
            emitLine(out_, indent_, "} else {");
            emitLine(out_, indent_ + 1, expr + ".reserve(" + count + ");");
            emitLine(out_, indent_, "}");
        }

        FunctionBodyEmitter&         owner_;
        std::ostringstream&          out_;
        int                          indent_;
        const HelperBindingDirection direction_;
        const std::string            poolClassConstExpr_;
        std::string                  itemVar_;
    };

    void emitSerializeAny(std::ostringstream&                out,
                          const SemanticFieldType&           type,
                          const std::string&                 expr,
                          const int                          indent,
                          const std::optional<std::uint32_t> arrayLengthPrefixBitsOverride = std::nullopt,
                          const LoweredFieldFacts* const     fieldFacts                    = nullptr)
    {
        const auto steps =
            buildFieldEmitSteps(type, fieldFacts, arrayLengthPrefixBitsOverride, HelperBindingDirection::Serialize);
        FieldSpelling spelling(*this, out, indent, HelperBindingDirection::Serialize, "");
        renderFieldSteps(steps, expr, HelperBindingDirection::Serialize, spelling);
    }

    void emitDeserializeAny(std::ostringstream&                out,
                            const SemanticFieldType&           type,
                            const std::string&                 expr,
                            const int                          indent,
                            const std::optional<std::uint32_t> arrayLengthPrefixBitsOverride = std::nullopt,
                            const LoweredFieldFacts* const     fieldFacts                    = nullptr,
                            const std::string&                 poolClassConstExpr            = "")
    {
        const auto steps =
            buildFieldEmitSteps(type, fieldFacts, arrayLengthPrefixBitsOverride, HelperBindingDirection::Deserialize);
        FieldSpelling spelling(*this, out, indent, HelperBindingDirection::Deserialize, poolClassConstExpr);
        renderFieldSteps(steps, expr, HelperBindingDirection::Deserialize, spelling);
    }
};

std::string rustConstType(const TypeExprAST& type)
{
    const auto* prim = std::get_if<PrimitiveTypeExprAST>(&type.scalar);
    if (!prim)
    {
        return "i64";
    }
    switch (prim->kind)
    {
    case PrimitiveKind::Bool:
        return "bool";
    case PrimitiveKind::Float:
        return "f64";
    case PrimitiveKind::SignedInt:
        return "i64";
    case PrimitiveKind::UnsignedInt:
    case PrimitiveKind::Byte:
    case PrimitiveKind::Utf8:
        return "u64";
    }
    return "i64";
}

std::string rustConstType(const TypeExprAST& type, const Value& value)
{
    if (std::holds_alternative<std::string>(value.data))
    {
        return "&'static str";
    }
    if (std::holds_alternative<bool>(value.data))
    {
        return "bool";
    }
    return rustConstType(type);
}

void emitSectionType(std::ostringstream&              out,
                     const std::string&               typeName,
                     const SemanticSection&           section,
                     const EmitterContext&            ctx,
                     const RustEmitOptions&           options,
                     const std::string&               fullName,
                     std::uint32_t                    majorVersion,
                     std::uint32_t                    minorVersion,
                     const AttachedDoc&               typeDoc,
                     const std::string&               definitionFullName,
                     const LoweredSectionFacts* const sectionFacts)
{
    const NamingScope fieldScope = makeSectionFieldScope(CodegenNamingLanguage::Rust, section);
    std::unordered_map<std::string, std::string>       poolClassConstExprByField;
    std::vector<std::pair<std::string, std::uint32_t>> poolClassConstants;
    std::set<std::string>                              usedPoolConstNames;
    std::uint32_t                                      nextPoolClassId = 1U;
    for (const auto& field : section.fields)
    {
        if (field.isPadding || field.resolvedType.arrayKind == ArrayKind::None)
        {
            continue;
        }
        const std::string baseName =
            "__LLVMDSDL_POOL_CLASS_" +
            codegenProjectIdentifier(CodegenNamingLanguage::Rust, IdentifierRole::ConstantName, field.name);
        std::string constName = baseName;
        for (std::uint32_t suffix = 1U; !usedPoolConstNames.insert(constName).second; ++suffix)
        {
            constName = baseName + "_" + std::to_string(suffix);
        }
        poolClassConstExprByField.emplace(field.name, "Self::" + constName);
        poolClassConstants.emplace_back(constName, nextPoolClassId++);
    }

    emitAttachedDocRust(out,
                        0,
                        docWithDeprecationNotice(typeDoc,
                                                 section.deprecated,
                                                 definitionFullName,
                                                 majorVersion,
                                                 minorVersion));
    if (section.deprecated && options.emitDeprecationAttributes)
    {
        emitLine(out, 0, "#[deprecated]");
    }
    emitLine(out, 0, "#[derive(Clone, Debug, PartialEq)]");
    emitLine(out, 0, "pub struct " + typeName + " {");

    std::size_t fieldCount = 0;
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        ++fieldCount;
        emitAttachedDocRust(out, 1, field.doc);
        emitLine(out,
                 1,
                 "pub " + fieldScope.get(IdentifierRole::FieldName, field.name) + ": " +
                     rustFieldType(field.resolvedType, ctx) + ",");
    }

    if (section.isUnion)
    {
        // The tag storage must match the wire tag width (8 bits for <=256 options,
        // 16 for 257..65536, etc.); a hardcoded u8 truncates a wide tag and mis-dispatches.
        emitLine(out, 1, "pub _tag_: " + unsignedStorageType(resolveUnionTagBits(section, sectionFacts)) + ",");
    }

    if (fieldCount == 0 && !section.isUnion)
    {
        emitLine(out, 1, "pub _dummy_: u8,");
    }
    emitLine(out, 0, "}\n");

    emitLine(out, 0, "impl Default for " + typeName + " {");
    emitLine(out, 1, "fn default() -> Self {");
    emitLine(out, 2, "Self {");
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        if (field.resolvedType.arrayKind != ArrayKind::None)
        {
            const auto  classExprIt = poolClassConstExprByField.find(field.name);
            std::string classExpr   = "crate::dsdl_runtime::AllocationClassId(0u32)";
            if (classExprIt != poolClassConstExprByField.end())
            {
                classExpr = classExprIt->second;
            }
            emitLine(out,
                     3,
                     fieldScope.get(IdentifierRole::FieldName, field.name) +
                         ": crate::dsdl_runtime::DsdlVec::with_contract("
                         "crate::dsdl_runtime::VarArrayMemoryContract::new("
                         "Self::__LLVMDSDL_MEMORY_MODE, "
                         "Self::__LLVMDSDL_INLINE_THRESHOLD_BYTES, " +
                         classExpr + ")),");
            continue;
        }
        emitLine(out,
                 3,
                 fieldScope.get(IdentifierRole::FieldName, field.name) + ": " + defaultExpr(field.resolvedType, ctx) +
                     ",");
    }
    if (section.isUnion)
    {
        emitLine(out, 3, "_tag_: 0,");
    }
    if (fieldCount == 0 && !section.isUnion)
    {
        emitLine(out, 3, "_dummy_: 0,");
    }
    emitLine(out, 2, "}");
    emitLine(out, 1, "}");
    emitLine(out, 0, "}\n");

    emitLine(out, 0, "impl " + typeName + " {");
    emitLine(out, 1, "pub const FULL_NAME: &'static str = \"" + fullName + "\";");
    emitLine(out, 1, std::string("pub const IS_DEPRECATED: bool = ") + (section.deprecated ? "true;" : "false;"));
    emitLine(out,
             1,
             "pub const FULL_NAME_AND_VERSION: &'static str = \"" + fullName + "." + std::to_string(majorVersion) +
                 "." + std::to_string(minorVersion) + "\";");
    emitLine(out, 1, "pub const EXTENT_BYTES: usize = " + std::to_string(section.extentBits.value_or(0) / 8) + ";");
    emitLine(out,
             1,
             "pub const SERIALIZATION_BUFFER_SIZE_BYTES: usize = " +
                 std::to_string((section.serializationBufferSizeBits + 7) / 8) + ";");
    const bool        zohAliasEligible = sectionFacts != nullptr && sectionFacts->zohAliasEligible;
    const std::string zohAliasReason   = (sectionFacts != nullptr && !sectionFacts->zohAliasReason.empty())
                                             ? sectionFacts->zohAliasReason
                                             : "not-proven";
    emitLine(out, 1, std::string("pub const ZOH_ALIAS_ELIGIBLE: bool = ") + (zohAliasEligible ? "true;" : "false;"));
    emitLine(out, 1, "pub const ZOH_ALIAS_REASON: &'static str = \"" + zohAliasReason + "\";");
    emitLine(out,
             1,
             "pub const __LLVMDSDL_MEMORY_MODE: crate::dsdl_runtime::DsdlMemoryMode = " +
                 rustMemoryModeVariantPath(options) + ";");
    emitLine(out,
             1,
             "pub const __LLVMDSDL_INLINE_THRESHOLD_BYTES: usize = " + std::to_string(options.inlineThresholdBytes) +
                 "usize;");
    for (const auto& [constName, classId] : poolClassConstants)
    {
        emitLine(out,
                 1,
                 "pub const " + constName +
                     ": crate::dsdl_runtime::AllocationClassId = crate::dsdl_runtime::AllocationClassId(" +
                     std::to_string(classId) + "u32);");
    }
    if (section.isUnion)
    {
        std::size_t optionCount = 0;
        for (const auto& f : section.fields)
        {
            if (!f.isPadding)
            {
                ++optionCount;
            }
        }
        emitLine(out, 1, "pub const UNION_OPTION_COUNT: usize = " + std::to_string(optionCount) + ";");
    }

    std::vector<std::string> constNames;
    constNames.reserve(section.constants.size());
    for (const auto& c : section.constants)
    {
        constNames.push_back(c.name);
    }
    NamingScope const constScope = makeSectionConstantScope(CodegenNamingLanguage::Rust, section);
    for (const auto& c : section.constants)
    {
        emitAttachedDocRust(out, 1, c.doc);
        emitLine(out,
                 1,
                 "pub const " + constScope.get(IdentifierRole::ConstantName, c.name) + ": " +
                     rustConstType(c.type, c.value) + " = " + rustConstValue(c.type, c.value) + ";");
    }
    out << "\n";

    const auto canonicalSectionName =
        fullName + "." + std::to_string(majorVersion) + "." + std::to_string(minorVersion);
    FunctionBodyEmitter body(ctx, poolClassConstExprByField);
    ctx.traceSection(canonicalSectionName, EmitTraceDirection::Serialize);
    body.emitSerialize(out, typeName, section, sectionFacts);
    out << "\n";
    ctx.traceSection(canonicalSectionName, EmitTraceDirection::Deserialize);
    body.emitDeserialize(out, typeName, section, sectionFacts);
    out << "\n";

    emitLine(out,
             1,
             "pub fn try_deserialize_view<'a>(buffer: &'a [u8]) -> core::result::Result<(&'a [u8], usize), i8> {");
    emitLine(out, 2, "if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = \"big\") {");
    emitLine(out, 3, "return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
    emitLine(out, 2, "}");
    emitLine(out, 2, "let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;");
    emitLine(out, 2, "if buffer.len() < required {");
    emitLine(out, 3, "return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);");
    emitLine(out, 2, "}");
    emitLine(out, 2, "Ok((&buffer[..required], required))");
    emitLine(out, 1, "}\n");

    emitLine(out,
             1,
             "pub fn try_serialize_view(view_bytes: &[u8], buffer: &mut [u8]) -> core::result::Result<usize, i8> {");
    emitLine(out, 2, "if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = \"big\") {");
    emitLine(out, 3, "return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
    emitLine(out, 2, "}");
    emitLine(out, 2, "let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;");
    emitLine(out, 2, "if view_bytes.len() != required {");
    emitLine(out, 3, "return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
    emitLine(out, 2, "}");
    emitLine(out, 2, "if buffer.len() < required {");
    emitLine(out, 3, "return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);");
    emitLine(out, 2, "}");
    emitLine(out, 2, "buffer[..required].copy_from_slice(&view_bytes[..required]);");
    emitLine(out, 2, "Ok(required)");
    emitLine(out, 1, "}\n");

    emitLine(out, 1, "pub fn to_bytes(&self) -> core::result::Result<crate::dsdl_runtime::DsdlVec<u8>, i8> {");
    emitLine(out,
             2,
             "let mut buffer = "
             "crate::dsdl_runtime::DsdlVec::<u8>::with_capacity(Self::SERIALIZATION_BUFFER_SIZE_BYTES);");
    emitLine(out, 2, "buffer.resize(Self::SERIALIZATION_BUFFER_SIZE_BYTES, 0u8);");
    emitLine(out, 2, "let used = self.serialize(&mut buffer)?;");
    emitLine(out, 2, "buffer.truncate(used);");
    emitLine(out, 2, "Ok(buffer)");
    emitLine(out, 1, "}\n");

    emitLine(out, 1, "pub fn from_bytes(buffer: &[u8]) -> core::result::Result<(Self, usize), i8> {");
    emitLine(out, 2, "let mut out = Self::default();");
    emitLine(out, 2, "let used = out.deserialize(buffer)?;");
    emitLine(out, 2, "Ok((out, used))");
    emitLine(out, 1, "}");
    emitLine(out, 0, "}\n");
}

std::string renderDefinitionFile(const SemanticDefinition& def,
                                 const EmitterContext&     ctx,
                                 const LoweredFactsMap&    loweredFacts,
                                 const RustEmitOptions&    options)
{
    std::ostringstream out;
    emitLine(out, 0, generatedCommentLine("Rust backend"));
    emitLine(out,
             0,
             "// Source: " + def.info.fullName + "." + std::to_string(def.info.majorVersion) + "." +
                 std::to_string(def.info.minorVersion));
    emitLine(out, 0, "#![allow(non_camel_case_types)]");
    emitLine(out, 0, "#![allow(non_snake_case)]");
    emitLine(out, 0, "#![allow(non_upper_case_globals)]");
    if (options.emitDeprecationAttributes)
    {
        // Generated code must never warn about itself: the deprecated struct is named by its own impl
        // blocks and derives, and by any struct that holds it as a field. The allow is module-scoped,
        // so a consumer outside this module still gets the lint.
        emitLine(out, 0, "#![allow(deprecated)]");
    }
    out << "\n";

    const auto deps = collectDefinitionCompositeDependencies(def);

    const auto selfKey = loweredTypeKey(def.info.fullName, def.info.majorVersion, def.info.minorVersion);

    for (const auto& depRef : deps)
    {
        if (loweredTypeKey(depRef.fullName, depRef.majorVersion, depRef.minorVersion) == selfKey)
        {
            continue;
        }

        SemanticTypeRef ref = depRef;
        if (const auto* resolved = ctx.find(depRef))
        {
            ref.namespaceComponents = resolved->info.namespaceComponents;
            ref.shortName           = resolved->info.shortName;
        }

        const auto typePath = ctx.rustTypePath(ref);
        const auto rustType = ctx.rustTypeName(ref);
        emitLine(out, 0, "use " + typePath + ";");
        (void) rustType;
    }
    if (!deps.empty())
    {
        out << "\n";
    }

    const auto baseType = ctx.rustTypeName(def.info);

    if (!def.isService)
    {
        emitSectionType(out,
                        baseType,
                        def.request,
                        ctx,
                        options,
                        def.info.fullName,
                        def.info.majorVersion,
                        def.info.minorVersion,
                        def.doc,
                        def.info.fullName,
                        lookupLoweredSectionFacts(loweredFacts, def, ""));
        return out.str();
    }

    const auto reqType  = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::Rust, "request");
    const auto respType = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::Rust, "response");

    emitSectionType(out,
                    reqType,
                    def.request,
                    ctx,
                    options,
                    def.info.fullName + ".Request",
                    def.info.majorVersion,
                    def.info.minorVersion,
                    def.doc,
                    def.info.fullName,
                    lookupLoweredSectionFacts(loweredFacts, def, "request"));

    if (def.response)
    {
        out << "\n";
        emitSectionType(out,
                        respType,
                        *def.response,
                        ctx,
                        options,
                        def.info.fullName + ".Response",
                        def.info.majorVersion,
                        def.info.minorVersion,
                        def.doc,
                        def.info.fullName,
                        lookupLoweredSectionFacts(loweredFacts, def, "response"));
    }

    out << "\n";
    emitLine(out, 0, "pub type " + baseType + " = " + reqType + ";");

    return out.str();
}

llvm::Expected<std::string> loadRustRuntimeFile(const std::string& fileName)
{
    if (const auto data = embedded_runtime::find("rust/" + fileName))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "embedded runtime source missing: rust/%s",
                                   fileName.c_str());
}

std::string renderCargoToml(const RustEmitOptions& options)
{
    const auto rustProfileName = [&options]() -> const char* {
        return options.profile == RustProfile::Std ? "std" : "no-std-alloc";
    };
    const auto rustRuntimeSpecializationName = [&options]() -> const char* {
        return options.runtimeSpecialization == RustRuntimeSpecialization::Fast ? "fast" : "portable";
    };
    const auto rustMemoryModeName = [&options]() -> const char* {
        return options.memoryMode == RustMemoryMode::InlineThenPool ? "inline-then-pool" : "max-inline";
    };

    std::ostringstream out;
    out << "[package]\n";
    out << "name = \"" << options.crateName << "\"\n";
    out << "version = \"" << llvmdsdl::kVersionString << "\"\n";
    out << "edition = \"2021\"\n\n";
    out << "[package.metadata.llvmdsdl]\n";
    out << "generator-version = \"" << llvmdsdl::kVersionString << "\"\n";
    out << "rust-profile = \"" << rustProfileName() << "\"\n";
    out << "rust-runtime-specialization = \"" << rustRuntimeSpecializationName() << "\"\n";
    out << "rust-memory-mode = \"" << rustMemoryModeName() << "\"\n";
    out << "rust-inline-threshold-bytes = " << options.inlineThresholdBytes << "\n\n";

    out << "[lib]\n";
    out << "path = \"src/lib.rs\"\n\n";

    out << "[features]\n";
    std::vector<std::string> defaultFeatures;
    if (options.profile == RustProfile::Std)
    {
        defaultFeatures.emplace_back("std");
    }
    if (options.runtimeSpecialization == RustRuntimeSpecialization::Fast)
    {
        defaultFeatures.emplace_back("runtime-fast");
    }
    out << "default = [";
    for (std::size_t i = 0; i < defaultFeatures.size(); ++i)
    {
        if (i != 0)
        {
            out << ", ";
        }
        out << "\"" << defaultFeatures[i] << "\"";
    }
    out << "]\n";
    out << "std = []\n";
    out << "runtime-fast = []\n";
    return out.str();
}

}  // namespace

llvm::Error emitRust(const SemanticModule&  semantic,
                     mlir::ModuleOp         module,
                     const RustEmitOptions& options,
                     DiagnosticEngine&      diagnostics,
                     EmitTraceSink*         traceSink)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }
    const auto mlirCoverageDiagnostic = codegen_diagnostic_text::mlirSchemaCoverageValidationFailedForEmission("Rust");
    LoweredFactsMap loweredFacts;
    if (!collectLoweredFactsFromMlir(semantic,
                                     module,
                                     diagnostics,
                                     "Rust",
                                     &loweredFacts,
                                     options.optimizeLoweredSerDes))
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "%s", mlirCoverageDiagnostic.c_str());
    }
    std::filesystem::path const outRoot(options.outDir);
    std::filesystem::path const srcRoot          = outRoot / "src";
    const auto                  selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }
    const bool emitSupport = shouldEmitSupport(options.supportGeneration, anyTypeEmitted);

    if (emitSupport)
    {
        if (options.emitCargoToml)
        {
            if (auto err = writeGeneratedFile(outRoot / "Cargo.toml", renderCargoToml(options), options.writePolicy))
            {
                return err;
            }
        }

        auto runtime = loadRustRuntimeFile("dsdl_runtime.rs");
        if (!runtime)
        {
            return runtime.takeError();
        }
        if (auto err = writeGeneratedFile(srcRoot / "dsdl_runtime.rs",
                                          generatedCommentLine("Rust runtime scaffold") + "\n\n" + *runtime,
                                          options.writePolicy))
        {
            return err;
        }

        auto semanticWrappers = loadRustRuntimeFile("dsdl_runtime_semantic_wrappers.rs");
        if (!semanticWrappers)
        {
            return semanticWrappers.takeError();
        }
        if (auto err =
                writeGeneratedFile(srcRoot / "dsdl_runtime_semantic_wrappers.rs",
                                   generatedCommentLine("Rust runtime semantic wrappers") + "\n\n" + *semanticWrappers,
                                   options.writePolicy))
        {
            return err;
        }
    }

    EmitterContext ctx(semantic, options.typeNameVersioning);
    ctx.setTraceSink(traceSink);

    std::map<std::string, std::set<std::string>> dirToSubdirs;
    std::map<std::string, std::set<std::string>> dirToFiles;

    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def.info)};

        std::vector<std::string> ns;
        ns.reserve(def.info.namespaceComponents.size());
        for (const auto& c : def.info.namespaceComponents)
        {
            ns.push_back(codegenProjectIdentifier(CodegenNamingLanguage::Rust, IdentifierRole::NamespaceName, c));
        }

        std::string dirRel;
        std::string parentRel;
        for (const auto& component : ns)
        {
            dirToSubdirs[parentRel].insert(component);
            if (!dirRel.empty())
            {
                dirRel += "/";
            }
            dirRel += component;
            parentRel = dirRel;
        }

        const auto modName = llvmdsdl::EmitterContext::rustModuleName(def.info);
        dirToFiles[dirRel].insert(modName);

        std::filesystem::path dir = srcRoot;
        if (!dirRel.empty())
        {
            dir /= dirRel;
        }
        if (auto err = writeGeneratedFile(dir / (modName + ".rs"),
                                          renderDefinitionFile(def, ctx, loweredFacts, options),
                                          options.writePolicy,
                                          requiredTypeKeys))
        {
            return err;
        }
    }

    std::ostringstream lib;
    emitLine(lib, 0, generatedCommentLine("Rust backend crate root"));
    emitLine(lib, 0, "#![cfg_attr(not(feature = \"std\"), no_std)]");
    emitLine(lib, 0, "#![allow(non_camel_case_types)]");
    emitLine(lib, 0, "#![allow(non_snake_case)]");
    emitLine(lib, 0, "#![allow(non_upper_case_globals)]");
    emitLine(lib, 0, "#[cfg(not(feature = \"std\"))]");
    emitLine(lib, 0, "extern crate alloc;");
    emitLine(lib, 0, "pub mod dsdl_runtime;");

    if (dirToSubdirs.contains(""))
    {
        for (const auto& sub : dirToSubdirs[""])
        {
            emitLine(lib, 0, "pub mod " + sub + ";");
        }
    }
    if (dirToFiles.contains(""))
    {
        for (const auto& file : dirToFiles[""])
        {
            emitLine(lib, 0, "pub mod " + file + ";");
        }
    }

    if (auto err = writeGeneratedFile(srcRoot / "lib.rs", lib.str(), options.writePolicy, options.selectedTypeKeys))
    {
        return err;
    }

    std::set<std::string> dirs;
    for (const auto& [d, _] : dirToSubdirs)
    {
        if (!d.empty())
        {
            dirs.insert(d);
        }
    }
    for (const auto& [d, _] : dirToFiles)
    {
        if (!d.empty())
        {
            dirs.insert(d);
        }
    }

    for (const auto& dirRel : dirs)
    {
        std::ostringstream mod;
        emitLine(mod, 0, generatedCommentLine("Rust backend module index"));
        if (dirToSubdirs.contains(dirRel))
        {
            for (const auto& sub : dirToSubdirs[dirRel])
            {
                emitLine(mod, 0, "pub mod " + sub + ";");
            }
        }
        if (dirToFiles.contains(dirRel))
        {
            for (const auto& file : dirToFiles[dirRel])
            {
                emitLine(mod, 0, "pub mod " + file + ";");
            }
        }

        std::filesystem::path const dir = srcRoot / dirRel;
        if (auto err = writeGeneratedFile(dir / "mod.rs", mod.str(), options.writePolicy, options.selectedTypeKeys))
        {
            return err;
        }
    }

    return llvm::Error::success();
}

}  // namespace llvmdsdl
