//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements TypeScript backend code emission from lowered DSDL modules.
///
/// This file emits TypeScript models, codec entry points, and runtime wiring from lowering contracts.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/TsEmitter.h"

#include <llvm/ADT/StringRef.h>
#include <algorithm>
#include <cctype>
#include <filesystem>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <unordered_map>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <system_error>
#include <utility>
#include <variant>

#include "llvmdsdl/CodeGen/MlirLoweredFacts.h"
#include "llvmdsdl/CodeGen/CodegenDiagnosticText.h"
#include "llvmdsdl/CodeGen/CompositeImportGraph.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/CodeGen/DefinitionPathProjection.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/CodeGen/EmitStep.h"
#include "llvmdsdl/CodeGen/EmitTrace.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/HelperBindingNaming.h"
#include "llvmdsdl/CodeGen/HelperBindingRender.h"
#include "llvmdsdl/CodeGen/LoweredFactsLookup.h"
#include "llvmdsdl/CodeGen/RuntimeHelperBindings.h"
#include "llvmdsdl/CodeGen/ScriptedOperationPlan.h"
#include "llvmdsdl/CodeGen/SectionHelperBindingPlan.h"
#include "llvmdsdl/CodeGen/RuntimeLoweredPlan.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Support/Rational.h"
#include "llvmdsdl/Version.h"
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl
{
class DiagnosticEngine;

namespace
{

std::string tsConstValue(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(ConstantLiteralLanguage::TypeScript, value, makeConstantTypeInfo(type));
}

void emitLine(std::ostringstream& out, const int indent, const std::string& line)
{
    out << std::string(static_cast<std::size_t>(indent) * 2U, ' ') << line << '\n';
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return "// Generated by llvmdsdl " + std::string(llvmdsdl::kVersionString) + " (" + detail.str() + ").";
}

void emitAttachedDocTs(std::ostringstream& out, const int indent, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        emitLine(out, indent, "// " + line.text);
    }
}

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule& semantic, const TypeNameVersioning typeNameVersioning)
        : index_(semantic)
        , typeNameVersioning_(typeNameVersioning)
    {
    }

    /// @brief Whether generated type names carry the definition's version.
    TypeNameVersioning typeNameVersioning() const
    {
        return typeNameVersioning_;
    }

    /// @brief Attaches an emit-order trace sink (for the emit-order verifier). Null (default) disables tracing at zero
    /// cost.
    void setTraceSink(EmitTraceSink* const sink)
    {
        traceSink_ = sink;
    }

    /// @brief Records one abstract emit op into the attached sink (no-op when unattached).
    ///
    /// Const because it appends to the sink pointee, not the pointer, so it is callable on
    /// the `const EmitterContext&` the free render functions receive.
    template <typename PayloadT = std::int64_t>
    void trace(const EmitTraceOp op, const PayloadT payload = -1) const
    {
        emitTrace(traceSink_, op, static_cast<std::int64_t>(payload));
    }

    /// @brief Marks the start of one (type, direction) trace segment (no-op when unattached).
    void traceSection(const std::string& canonicalName, const EmitTraceDirection direction) const
    {
        emitTraceSection(traceSink_, canonicalName, direction);
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

    /// @brief Per-file alias table; see typeName(const SemanticTypeRef&). Mutable for the same
    /// reason `trace` is const: the free render functions are handed a `const EmitterContext&`.
    mutable std::map<std::string, std::string> importAliases_;

    std::string namespacePath(const DiscoveredDefinition& info) const
    {
        return renderNamespaceRelativePath(CodegenNamingLanguage::TypeScript, info.namespaceComponents)
            .generic_string();
    }

    std::string typeName(const DiscoveredDefinition& info) const
    {
        return renderDefinitionTypeName(CodegenNamingLanguage::TypeScript,
                                        info.namespaceComponents,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion,
                                        typeNameVersioning_);
    }

    /// @brief Local name for a *referenced* type in the file currently being emitted.
    ///
    /// @details
    /// Usually the plain versioned name, which is what the import brings in. It differs when one
    /// file references two types that share a short name from different namespaces --
    /// `uavcan.si.unit.angular_velocity.Vector3.1.0` and `uavcan.si.unit.velocity.Vector3.1.0` are
    /// both `Vector3_1_0`, and importing both under that name is a duplicate-identifier error that
    /// stops `tsc` outright. Such types are imported under a namespace-qualified alias instead, and
    /// this is where every reference site picks that alias up: the type annotations, the serialize
    /// and deserialize call names, and the import list all resolve through here, so they cannot
    /// disagree.
    std::string typeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            if (const auto alias = importAliases_.find(importAliasKey(def->info)); alias != importAliases_.end())
            {
                return alias->second;
            }
            return typeName(def->info);
        }

        DiscoveredDefinition tmp;
        tmp.shortName    = ref.shortName;
        tmp.majorVersion = ref.majorVersion;
        tmp.minorVersion = ref.minorVersion;
        return typeName(tmp);
    }

    /// @brief Identity of a definition for alias bookkeeping: unique across namespaces and versions.
    static std::string importAliasKey(const DiscoveredDefinition& info)
    {
        return info.fullName + ":" + std::to_string(info.majorVersion) + "." + std::to_string(info.minorVersion);
    }

    /// @brief Installs the alias table for the file about to be emitted, replacing any previous one.
    void setImportAliases(std::map<std::string, std::string> aliases) const
    {
        importAliases_ = std::move(aliases);
    }

    std::string fileStem(const DiscoveredDefinition& info) const
    {
        return renderVersionedFileStem(CodegenNamingLanguage::TypeScript,
                                       info.shortName,
                                       info.majorVersion,
                                       info.minorVersion);
    }

    std::filesystem::path relativeFilePath(const DiscoveredDefinition& info) const
    {
        return renderRelativeTypeFilePath(CodegenNamingLanguage::TypeScript, info, "ts");
    }

    std::filesystem::path relativeFilePath(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return relativeFilePath(def->info);
        }

        return renderRelativeTypeFilePath(CodegenNamingLanguage::TypeScript, ref, "ts");
    }

private:
    DefinitionIndex    index_;
    TypeNameVersioning typeNameVersioning_{TypeNameVersioning::Unversioned};
    EmitTraceSink*     traceSink_ = nullptr;
};

std::string tsFieldBaseType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "boolean";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
        return "number";
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        if (type.bitLength > 53U)
        {
            return "bigint";
        }
        return "number";
    case SemanticScalarCategory::Float:
    case SemanticScalarCategory::Void:
        return "number";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.typeName(*type.compositeType);
        }
        return "unknown";
    }
    return "unknown";
}

std::string tsFieldType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    const auto base = tsFieldBaseType(type, ctx);
    if (type.arrayKind == ArrayKind::None)
    {
        return base;
    }
    return "Array<" + base + ">";
}

std::string relativeImportPath(const std::filesystem::path& fromFile, const std::filesystem::path& toFile)
{
    const auto  fromDir    = fromFile.parent_path();
    auto        rel        = toFile.lexically_relative(fromDir);
    std::string importPath = rel.generic_string();
    if (importPath.size() >= 3 && importPath.ends_with(".ts"))
    {
        importPath.resize(importPath.size() - 3);
    }
    if (!importPath.empty() && importPath.front() != '.')
    {
        importPath = "./" + importPath;
    }
    return importPath;
}

std::string moduleAliasFromPath(const std::string& modulePath)
{
    std::string alias;
    alias.reserve(modulePath.size() + 8);
    for (char c : modulePath)
    {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            alias.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
        }
        else
        {
            alias.push_back('_');
        }
    }
    // Not a role: the alias comes from --ts-module, so it is a token this generator was handed
    // rather than a DSDL name, and must not pick up a role's case projection.
    return codegenSanitizeIdentifier(CodegenNamingLanguage::TypeScript, alias.empty() ? "module" : alias);
}

void emitSectionConstants(std::ostringstream& out, const std::string& prefix, const SemanticSection& section)
{
    std::vector<std::string> constNames;
    constNames.reserve(section.constants.size());
    for (const auto& constant : section.constants)
    {
        constNames.push_back(constant.name);
    }
    NamingScope constScope = makeSectionConstantScope(CodegenNamingLanguage::TypeScript, section);
    const auto  prefixupper =
        codegenProjectIdentifier(CodegenNamingLanguage::TypeScript, IdentifierRole::ConstantName, prefix);
    for (const auto& constant : section.constants)
    {
        emitAttachedDocTs(out, 0, constant.doc);
        const auto constName = prefixupper + "_" + constScope.get(IdentifierRole::ConstantName, constant.name);
        emitLine(out, 0, "export const " + constName + " = " + tsConstValue(constant.type, constant.value) + ";");
    }
}

/// @brief Collision-free property names for one section's fields.
///
/// snake_casing is many-to-one, so `fooBar` and `foo_bar` both fold to `foo_bar`; without this the
/// object type would declare the same property twice and the (de)serializer would read/write the
/// wrong one. Built from `section.fields` (declaration order) so every emission site agrees.
NamingScope makeTsFieldIdents(const SemanticSection& section)
{
    std::vector<std::string> names;
    for (const auto& field : section.fields)
    {
        if (!field.isPadding)
        {
            names.push_back(field.name);
        }
    }
    return makeSectionFieldScope(CodegenNamingLanguage::TypeScript, section);
}

void emitDeprecationJsDocTs(std::ostringstream& out,
                            const bool          deprecated,
                            const std::string&  fullName,
                            const std::uint32_t majorVersion,
                            const std::uint32_t minorVersion)
{
    if (!deprecated)
    {
        return;
    }
    // The `Deprecated: ` prefix that the shared notice carries for Go's benefit is redundant next to
    // the JSDoc tag, so it is dropped here.
    const std::string notice = deprecationNotice(fullName, majorVersion, minorVersion);
    const std::string prefix = "Deprecated: ";
    const std::string body   = notice.rfind(prefix, 0) == 0 ? notice.substr(prefix.size()) : notice;

    // Wrapped and split across lines for the same reason the notice itself is: a single-line JSDoc
    // block would be twice the width of the code around it. Budget allows for the " * " continuation.
    const auto lines = wrapCommentText(body, 68U);
    out << "/**\n";
    out << " * @deprecated " << lines.front() << "\n";
    for (std::size_t i = 1; i < lines.size(); ++i)
    {
        out << " *   " << lines[i] << "\n";
    }
    out << " */\n";
}

void emitStructSectionType(std::ostringstream&    out,
                           const std::string&     typeName,
                           const SemanticSection& section,
                           const AttachedDoc&     typeDoc,
                           const EmitterContext&  ctx,
                           const std::string&     fullName,
                           const std::uint32_t    majorVersion,
                           const std::uint32_t    minorVersion,
                           const bool             deprecated)
{
    emitAttachedDocTs(out, 0, typeDoc);
    emitDeprecationJsDocTs(out, deprecated, fullName, majorVersion, minorVersion);
    emitLine(out, 0, "export interface " + typeName + " {");
    const NamingScope fieldIdents = makeTsFieldIdents(section);
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        emitAttachedDocTs(out, 1, field.doc);
        const auto fieldName = fieldIdents.get(IdentifierRole::FieldName, field.name);
        emitLine(out, 1, fieldName + ": " + tsFieldType(field.resolvedType, ctx) + ";");
    }
    emitLine(out, 0, "}");
}

void emitUnionSectionType(std::ostringstream&    out,
                          const std::string&     typeName,
                          const SemanticSection& section,
                          const AttachedDoc&     typeDoc,
                          const EmitterContext&  ctx,
                          const std::string&     fullName,
                          const std::uint32_t    majorVersion,
                          const std::uint32_t    minorVersion)
{
    std::vector<const SemanticField*> options;
    for (const auto& field : section.fields)
    {
        if (!field.isPadding)
        {
            options.push_back(&field);
        }
    }

    if (options.empty())
    {
        emitAttachedDocTs(out, 0, typeDoc);
        emitDeprecationJsDocTs(out, section.deprecated, fullName, majorVersion, minorVersion);
        emitLine(out, 0, "export type " + typeName + " = { _tag: number };");
        return;
    }

    emitAttachedDocTs(out, 0, typeDoc);
    emitDeprecationJsDocTs(out, section.deprecated, fullName, majorVersion, minorVersion);
    emitLine(out, 0, "export type " + typeName + " =");
    const NamingScope fieldIdents = makeTsFieldIdents(section);
    for (std::size_t i = 0; i < options.size(); ++i)
    {
        const auto* field = options[i];
        emitAttachedDocTs(out, 0, field->doc);
        const auto         fieldName = fieldIdents.get(IdentifierRole::FieldName, field->name);
        std::ostringstream variant;
        variant << "{ _tag: " << field->unionOptionIndex << "; " << fieldName << ": "
                << tsFieldType(field->resolvedType, ctx) << "; }";
        const auto prefix = i == 0 ? "  | " : "  | ";
        emitLine(out, 0, prefix + variant.str() + (i + 1 == options.size() ? ";" : ""));
    }
}

void emitSectionType(std::ostringstream&    out,
                     const std::string&     typeName,
                     const SemanticSection& section,
                     const AttachedDoc&     typeDoc,
                     const EmitterContext&  ctx,
                     const std::string&     fullName,
                     const std::uint32_t    majorVersion,
                     const std::uint32_t    minorVersion)
{
    if (section.isUnion)
    {
        emitUnionSectionType(out, typeName, section, typeDoc, ctx, fullName, majorVersion, minorVersion);
    }
    else
    {
        emitStructSectionType(out,
                              typeName,
                              section,
                              typeDoc,
                              ctx,
                              fullName,
                              majorVersion,
                              minorVersion,
                              section.deprecated);
    }
}

std::string tsRuntimeSerializeFn(const std::string& typeName)
{
    return "serialize" + typeName;
}

std::string tsRuntimeDeserializeFn(const std::string& typeName)
{
    return "deserialize" + typeName;
}

std::string compositeTypeName(const RuntimeFieldPlan& field, const EmitterContext& ctx)
{
    return field.compositeType ? ctx.typeName(*field.compositeType) : std::string{"unknown_composite"};
}

std::string helperBindingNameTs(const std::string& helperSymbol)
{
    return renderHelperBindingIdentifier(CodegenNamingLanguage::TypeScript, helperSymbol);
}

std::string normalizeTsDeserScalarExpr(const RuntimeFieldPlan&        field,
                                       const RuntimeFieldHelperNames& helpers,
                                       const std::string&             rawExpr)
{
    if (helpers.deserScalar.empty())
    {
        return rawExpr;
    }
    const auto helperCall = helpers.deserScalar + "(" + rawExpr + ")";
    if (field.kind == RuntimeFieldKind::Unsigned || field.kind == RuntimeFieldKind::Signed)
    {
        return field.useBigInt ? ("BigInt(" + helperCall + ")") : ("Number(" + helperCall + ")");
    }
    return helperCall;
}

void emitTsRuntimeSerializeCompositeValue(std::ostringstream&     out,
                                          int                     indent,
                                          const RuntimeFieldPlan& field,
                                          const std::string&      valueExpr,
                                          const EmitterContext&   ctx)
{
    ctx.trace(field.compositeSealed ? EmitTraceOp::CompositeInline : EmitTraceOp::CompositeDelimHeader);
    const auto nestedVar = field.fieldName + "Bytes";
    const auto typeName  = compositeTypeName(field, ctx);
    emitLine(out, indent, "const " + nestedVar + " = " + tsRuntimeSerializeFn(typeName) + "(" + valueExpr + ");");
    if (field.compositeSealed)
    {
        emitLine(out,
                 indent,
                 "dsdlRuntime.copyBits(out, offsetBits, " + nestedVar + ", 0, " + std::to_string(field.bitLength) +
                     ");");
        emitLine(out, indent, "offsetBits += " + std::to_string(field.bitLength) + ";");
        return;
    }

    const auto sizeVar         = field.fieldName + "SizeBytes";
    const auto remainingVar    = field.fieldName + "RemainingBytes";
    const auto maxPayloadBytes = std::to_string((field.compositePayloadMaxBits + 7) / 8);
    emitLine(out, indent, "const " + sizeVar + " = " + nestedVar + ".length;");
    emitLine(out, indent, "if (" + sizeVar + " > " + maxPayloadBytes + ") {");
    emitLine(out,
             indent + 1,
             "throw new Error(\"" +
                 codegen_diagnostic_text::encodedCompositePayloadExceedsMaxPayloadBytes(field.fieldName,
                                                                                        maxPayloadBytes) +
                 "\");");
    emitLine(out, indent, "}");
    emitLine(out,
             indent,
             "const " + remainingVar + " = out.length - Math.min(Math.trunc(offsetBits / 8), out.length);");
    emitLine(out, indent, "if (" + sizeVar + " > " + remainingVar + ") {");
    emitLine(out,
             indent + 1,
             "throw new Error(\"" +
                 codegen_diagnostic_text::encodedCompositePayloadExceedsRemainingBufferSpace(field.fieldName) + "\");");
    emitLine(out, indent, "}");
    emitLine(out, indent, "dsdlRuntime.writeUnsigned(out, offsetBits, 32, " + sizeVar + ", false);");
    emitLine(out, indent, "offsetBits += 32;");
    emitLine(out, indent, "dsdlRuntime.copyBits(out, offsetBits, " + nestedVar + ", 0, " + sizeVar + " * 8);");
    emitLine(out, indent, "offsetBits += " + sizeVar + " * 8;");
}

void emitTsRuntimeDeserializeCompositeValue(std::ostringstream&     out,
                                            int                     indent,
                                            const RuntimeFieldPlan& field,
                                            const std::string&      targetExpr,
                                            const EmitterContext&   ctx,
                                            const std::string&      delimiterValidateHelper = {})
{
    ctx.trace(field.compositeSealed ? EmitTraceOp::CompositeInline : EmitTraceOp::CompositeDelimHeader);
    const auto typeName = compositeTypeName(field, ctx);
    if (field.compositeSealed)
    {
        const auto nestedVar = field.fieldName + "Bytes";
        emitLine(out,
                 indent,
                 "const " + nestedVar + " = dsdlRuntime.extractBits(bytes, offsetBits, " +
                     std::to_string(field.bitLength) + ");");
        emitLine(out, indent, targetExpr + " = " + tsRuntimeDeserializeFn(typeName) + "(" + nestedVar + ").value;");
        emitLine(out, indent, "offsetBits += " + std::to_string(field.bitLength) + ";");
        return;
    }

    const auto sizeVar      = field.fieldName + "SizeBytes";
    const auto remainingVar = field.fieldName + "RemainingBytes";
    const auto startVar     = field.fieldName + "StartByte";
    const auto endVar       = field.fieldName + "EndByte";
    const auto nestedVar    = field.fieldName + "Bytes";
    emitLine(out, indent, "const " + sizeVar + " = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 32));");
    emitLine(out, indent, "offsetBits += 32;");
    emitLine(out,
             indent,
             "const " + remainingVar + " = bytes.length - Math.min(Math.trunc(offsetBits / 8), bytes.length);");
    if (!delimiterValidateHelper.empty())
    {
        emitLine(out, indent, "if (!" + delimiterValidateHelper + "(" + sizeVar + ", " + remainingVar + ")) {");
    }
    else
    {
        emitLine(out, indent, "if (" + sizeVar + " < 0 || " + sizeVar + " > " + remainingVar + ") {");
    }
    emitLine(out,
             indent + 1,
             "throw new Error(\"" +
                 codegen_diagnostic_text::decodedCompositePayloadExceedsRemainingBufferSpace(field.fieldName) + "\");");
    emitLine(out, indent, "}");
    emitLine(out, indent, "const " + startVar + " = Math.min(Math.trunc(offsetBits / 8), bytes.length);");
    emitLine(out, indent, "const " + endVar + " = Math.min(" + startVar + " + " + sizeVar + ", bytes.length);");
    emitLine(out, indent, "const " + nestedVar + " = bytes.subarray(" + startVar + ", " + endVar + ");");
    emitLine(out, indent, targetExpr + " = " + tsRuntimeDeserializeFn(typeName) + "(" + nestedVar + ").value;");
    emitLine(out, indent, "offsetBits += " + sizeVar + " * 8;");
}

void emitTsRuntimeAlignSerialize(std::ostringstream&   out,
                                 int                   indent,
                                 std::int64_t          alignmentBits,
                                 const std::string&    prefix,
                                 const EmitterContext& ctx)
{
    if (alignmentBits <= 1)
    {
        return;
    }
    ctx.trace(EmitTraceOp::Align, alignmentBits);
    const auto alignedVar = prefix + "AlignedOffsetBits";
    const auto bitVar     = prefix + "AlignBit";
    emitLine(out,
             indent,
             "const " + alignedVar + " = Math.trunc((offsetBits + " + std::to_string(alignmentBits - 1) + ") / " +
                 std::to_string(alignmentBits) + ") * " + std::to_string(alignmentBits) + ";");
    emitLine(out,
             indent,
             "for (let " + bitVar + " = offsetBits; " + bitVar + " < " + alignedVar + "; ++" + bitVar + ") {");
    emitLine(out, indent + 1, "dsdlRuntime.setBit(out, " + bitVar + ", false);");
    emitLine(out, indent, "}");
    emitLine(out, indent, "offsetBits = " + alignedVar + ";");
}

void emitTsRuntimeAlignDeserialize(std::ostringstream&   out,
                                   int                   indent,
                                   std::int64_t          alignmentBits,
                                   const EmitterContext& ctx)
{
    if (alignmentBits <= 1)
    {
        return;
    }
    ctx.trace(EmitTraceOp::Align, alignmentBits);
    emitLine(out,
             indent,
             "offsetBits = Math.trunc((offsetBits + " + std::to_string(alignmentBits - 1) + ") / " +
                 std::to_string(alignmentBits) + ") * " + std::to_string(alignmentBits) + ";");
}

void emitTsRuntimeSerializePadding(std::ostringstream&     out,
                                   int                     indent,
                                   const RuntimeFieldPlan& field,
                                   const std::string&      prefix,
                                   const EmitterContext&   ctx)
{
    if (field.bitLength <= 0)
    {
        return;
    }
    ctx.trace(EmitTraceOp::Pad, field.bitLength);
    const auto bitVar = prefix + "PaddingBit";
    emitLine(out,
             indent,
             "for (let " + bitVar + " = 0; " + bitVar + " < " + std::to_string(field.bitLength) + "; ++" + bitVar +
                 ") {");
    emitLine(out, indent + 1, "dsdlRuntime.setBit(out, offsetBits + " + bitVar + ", false);");
    emitLine(out, indent, "}");
    ctx.trace(EmitTraceOp::Advance, field.bitLength);
    emitLine(out, indent, "offsetBits += " + std::to_string(field.bitLength) + ";");
}

void emitTsRuntimeDeserializePadding(std::ostringstream&     out,
                                     int                     indent,
                                     const RuntimeFieldPlan& field,
                                     const EmitterContext&   ctx)
{
    if (field.bitLength <= 0)
    {
        return;
    }
    ctx.trace(EmitTraceOp::Pad, field.bitLength);
    ctx.trace(EmitTraceOp::Advance, field.bitLength);
    emitLine(out, indent, "offsetBits += " + std::to_string(field.bitLength) + ";");
}

/// @brief TypeScript spelling of the shared union-prologue steps (see EmitStep.h).
///
/// The tag mask is spelled as its own statement (D1 spelling freedom); the error
/// channel is `throw`. Helper-conditional guards mirror the pre-template code.
class TsUnionSpelling final : public UnionSectionSpelling
{
public:
    TsUnionSpelling(std::ostringstream&              out,
                    const EmitterContext&            ctx,
                    const RuntimeSectionHelperNames& sectionHelperNames,
                    const std::uint32_t              tagBits,
                    std::string                      dispatchPreamble)
        : out_(out)
        , ctx_(ctx)
        , helperNames_(sectionHelperNames)
        , tagBits_(tagBits)
        , tagBitsStr_(std::to_string(tagBits))
        , dispatchPreamble_(std::move(dispatchPreamble))
    {
    }

    void spellSerializeValidateTag() override
    {
        if (!helperNames_.unionTagValidate.empty())
        {
            ctx_.trace(EmitTraceOp::ValidateTag);
            emitLine(out_, 1, "if (!" + helperNames_.unionTagValidate + "(tag)) {");
            emitLine(out_, 2, "throw new Error(\"" + codegen_diagnostic_text::invalidUnionTagPrefix() + "\" + tag);");
            emitLine(out_, 1, "}");
        }
    }

    void spellSerializeWriteMaskedTag() override
    {
        if (!helperNames_.serUnionTagMask.empty())
        {
            emitLine(out_, 1, "tag = Number(" + helperNames_.serUnionTagMask + "(tag));");
        }
        ctx_.trace(EmitTraceOp::MaskTag);
        ctx_.trace(EmitTraceOp::WriteTag, tagBits_);
        emitLine(out_, 1, "dsdlRuntime.writeUnsigned(out, offsetBits, " + tagBitsStr_ + ", tag, false);");
    }

    void spellDeserializeReadMaskStoreTag() override
    {
        ctx_.trace(EmitTraceOp::ReadTag, tagBits_);
        emitLine(out_, 1, "let tag = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, " + tagBitsStr_ + "));");
        if (!helperNames_.deserUnionTagMask.empty())
        {
            ctx_.trace(EmitTraceOp::MaskTag);
            ctx_.trace(EmitTraceOp::StoreTag);
            emitLine(out_, 1, "tag = Number(" + helperNames_.deserUnionTagMask + "(tag));");
        }
    }

    void spellDeserializeValidateTag() override
    {
        if (!helperNames_.unionTagValidate.empty())
        {
            ctx_.trace(EmitTraceOp::ValidateTag);
            emitLine(out_, 1, "if (!" + helperNames_.unionTagValidate + "(tag)) {");
            emitLine(out_,
                     2,
                     "throw new Error(\"" + codegen_diagnostic_text::decodedInvalidUnionTagPrefix() + "\" + tag);");
            emitLine(out_, 1, "}");
        }
    }

    void spellAdvanceTag() override
    {
        ctx_.trace(EmitTraceOp::Advance, tagBits_);
        emitLine(out_, 1, "offsetBits += " + tagBitsStr_ + ";");
    }

    void spellBeginDispatch() override
    {
        if (!dispatchPreamble_.empty())
        {
            emitLine(out_, 1, dispatchPreamble_);
        }
        ctx_.trace(EmitTraceOp::Switch);
        emitLine(out_, 1, "switch (tag) {");
    }

    void spellBeginCase(const std::int64_t optionIndex, const bool /*firstCase*/) override
    {
        ctx_.trace(EmitTraceOp::Case, optionIndex);
        emitLine(out_, 1, "case " + std::to_string(optionIndex) + ": {");
    }

    void spellEndCase() override
    {
        emitLine(out_, 2, "break;");
        emitLine(out_, 1, "}");
    }

    void spellBadTagDefault() override
    {
        ctx_.trace(EmitTraceOp::DefaultBadTag);
        emitLine(out_, 1, "default:");
        emitLine(out_, 2, "throw new Error(\"" + badTagDiagnosticPrefix_ + "\" + tag);");
    }

    void spellEndDispatch() override
    {
        emitLine(out_, 1, "}");
    }

    /// @brief Selects the bad-tag diagnostic text (serialize vs decoded spelling).
    void setBadTagDiagnosticPrefix(std::string prefix)
    {
        badTagDiagnosticPrefix_ = std::move(prefix);
    }

private:
    std::ostringstream&              out_;
    const EmitterContext&            ctx_;
    const RuntimeSectionHelperNames& helperNames_;
    const std::uint32_t              tagBits_;
    const std::string                tagBitsStr_;
    const std::string                dispatchPreamble_;
    std::string                      badTagDiagnosticPrefix_;
};

/// @brief TypeScript spelling of the shared recursive field-body steps (see EmitStep.h).
///
/// One spelling covers all four contexts (struct/union x serialize/deserialize):
/// the union context differs only in declare-vs-assign store style, diagnostic
/// flag, temp suffixes, and root-expression casts (applied by the caller). Leaf
/// composite/padding idioms delegate to the existing atomic renderers; all
/// cross-group and recursive ordering comes from renderFieldSteps.
class TsFieldSpelling final : public FieldStepSpelling
{
public:
    TsFieldSpelling(std::ostringstream&               out,
                    const EmitterContext&             ctx,
                    const ScriptedFieldOperationPlan& operation,
                    const int                         indent,
                    const bool                        unionContext)
        : out_(out)
        , ctx_(ctx)
        , operation_(operation)
        , indent_(indent)
        , unionContext_(unionContext)
    {
    }

    /// @brief Sets the render direction (padding and store style branch on it).
    void setDirection(const HelperBindingDirection direction)
    {
        direction_ = direction;
    }

    void spellPad(const FieldEmitStep& step) override
    {
        (void) step;
        const auto& field = operation_.body.field;
        if (direction_ == HelperBindingDirection::Serialize)
        {
            const auto label = unionContext_ ? field.fieldName + "Option" : field.fieldName;
            emitTsRuntimeSerializePadding(out_, indent_, field, label, ctx_);
        }
        else
        {
            emitTsRuntimeDeserializePadding(out_, indent_, field, ctx_);
            if (unionContext_)
            {
                emitLine(out_, indent_, "const optionValue = undefined;");
            }
        }
    }

    void spellScalarSerialize(const FieldEmitStep& step, const std::string& expr) override
    {
        const auto& field      = operation_.body.field;
        const auto& helpers    = operation_.body.helpers;
        const auto  bits       = std::to_string(field.bitLength);
        const auto  saturating = field.castMode == CastMode::Saturated ? "true" : "false";
        switch (step.kind)
        {
        case FieldStepKind::ScalarBool:
            ctx_.trace(EmitTraceOp::WriteScalarBool, 1);
            emitLine(out_, indent_, "dsdlRuntime.setBit(out, offsetBits, " + expr + ");");
            break;
        case FieldStepKind::ScalarUint: {
            std::string scalarExpr = expr;
            if (!helpers.serScalar.empty())
            {
                scalarExpr = helpers.serScalar + "(" + scalarExpr + ")";
            }
            ctx_.trace(EmitTraceOp::WriteScalarUint, field.bitLength);
            emitLine(out_,
                     indent_,
                     "dsdlRuntime.writeUnsigned(out, offsetBits, " + bits + ", " + scalarExpr + ", " + saturating +
                         ");");
            break;
        }
        case FieldStepKind::ScalarFloat: {
            std::string scalarExpr = expr;
            if (!helpers.serScalar.empty())
            {
                scalarExpr = helpers.serScalar + "(" + scalarExpr + ")";
            }
            ctx_.trace(EmitTraceOp::WriteScalarFloat, field.bitLength);
            emitLine(out_, indent_, "dsdlRuntime.writeFloat(out, offsetBits, " + bits + ", " + scalarExpr + ");");
            break;
        }
        case FieldStepKind::ScalarSint: {
            std::string scalarExpr = expr;
            if (!helpers.serScalar.empty())
            {
                scalarExpr = helpers.serScalar + "(" + scalarExpr + ")";
            }
            ctx_.trace(EmitTraceOp::WriteScalarSint, field.bitLength);
            emitLine(out_,
                     indent_,
                     "dsdlRuntime.writeSigned(out, offsetBits, " + bits + ", " + scalarExpr + ", " + saturating + ");");
            break;
        }
        default:
            assert(false && "not a scalar step");
            break;
        }
        ctx_.trace(EmitTraceOp::Advance, field.bitLength);
        emitLine(out_, indent_, "offsetBits += " + bits + ";");
    }

    void spellScalarDeserialize(const FieldEmitStep& step, const std::string& expr) override
    {
        const auto& field   = operation_.body.field;
        const auto& helpers = operation_.body.helpers;
        const auto  bits    = std::to_string(field.bitLength);
        switch (step.kind)
        {
        case FieldStepKind::ScalarBool:
            ctx_.trace(EmitTraceOp::ReadScalarBool, 1);
            emitStore(expr, "dsdlRuntime.getBit(bytes, offsetBits)");
            break;
        case FieldStepKind::ScalarUint: {
            const std::string fn     = field.useBigInt ? "readUnsignedBigInt" : "readUnsigned";
            const auto        rawVar = field.fieldName + rawSuffix();
            ctx_.trace(EmitTraceOp::ReadScalarUint, field.bitLength);
            emitLine(out_, indent_, "const " + rawVar + " = dsdlRuntime." + fn + "(bytes, offsetBits, " + bits + ");");
            emitStore(expr, normalizeTsDeserScalarExpr(field, helpers, rawVar));
            break;
        }
        case FieldStepKind::ScalarFloat: {
            const auto rawVar = field.fieldName + rawSuffix();
            ctx_.trace(EmitTraceOp::ReadScalarFloat, field.bitLength);
            emitLine(out_, indent_, "const " + rawVar + " = dsdlRuntime.readFloat(bytes, offsetBits, " + bits + ");");
            emitStore(expr, normalizeTsDeserScalarExpr(field, helpers, rawVar));
            break;
        }
        case FieldStepKind::ScalarSint: {
            const std::string fn     = field.useBigInt ? "readSignedBigInt" : "readSigned";
            const auto        rawVar = field.fieldName + rawSuffix();
            ctx_.trace(EmitTraceOp::ReadScalarSint, field.bitLength);
            emitLine(out_, indent_, "const " + rawVar + " = dsdlRuntime." + fn + "(bytes, offsetBits, " + bits + ");");
            emitStore(expr, normalizeTsDeserScalarExpr(field, helpers, rawVar));
            break;
        }
        default:
            assert(false && "not a scalar step");
            break;
        }
        ctx_.trace(EmitTraceOp::Advance, field.bitLength);
        emitLine(out_, indent_, "offsetBits += " + bits + ";");
    }

    void spellCompositeSerialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        emitTsRuntimeSerializeCompositeValue(out_, indent_, operation_.body.field, expr, ctx_);
    }

    void spellCompositeDeserialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        const auto& field = operation_.body.field;
        if (!inElement_ && unionContext_)
        {
            emitLine(out_, indent_, "let " + expr + ": " + compositeTypeName(field, ctx_) + ";");
        }
        emitTsRuntimeDeserializeCompositeValue(out_,
                                               indent_,
                                               field,
                                               expr,
                                               ctx_,
                                               operation_.body.helpers.delimiterValidate);
    }

    void spellFixedArrayLenCheck(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        const auto& field    = operation_.body.field;
        const auto  cap      = std::to_string(field.arrayCapacity);
        const auto  fieldArr = field.fieldName + "Array";
        emitLine(out_, indent_, "const " + fieldArr + " = " + expr + ";");
        ctx_.trace(EmitTraceOp::LenCheck, field.arrayCapacity);
        emitLine(out_, indent_, "if (!Array.isArray(" + fieldArr + ") || " + fieldArr + ".length !== " + cap + ") {");
        emitLine(out_,
                 indent_ + 1,
                 "throw new Error(\"" +
                     codegen_diagnostic_text::fieldExpectsExactlyElements(field.fieldName, cap, unionContext_) +
                     "\");");
        emitLine(out_, indent_, "}");
    }

    void spellVariableArrayLenSerialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        const auto& field      = operation_.body.field;
        const auto& helpers    = operation_.body.helpers;
        const auto  cap        = std::to_string(field.arrayCapacity);
        const auto  prefixBits = std::to_string(field.arrayLengthPrefixBits);
        const auto  fieldArr   = field.fieldName + "Array";
        emitLine(out_, indent_, "const " + fieldArr + " = " + expr + ";");
        emitLine(out_, indent_, "if (!Array.isArray(" + fieldArr + ")) {");
        emitLine(out_,
                 indent_ + 1,
                 "throw new Error(\"" + codegen_diagnostic_text::fieldExpectsArray(field.fieldName, unionContext_) +
                     "\");");
        emitLine(out_, indent_, "}");
        ctx_.trace(EmitTraceOp::LenValidate, field.arrayLengthPrefixBits);
        if (!helpers.arrayValidate.empty())
        {
            emitLine(out_, indent_, "if (!" + helpers.arrayValidate + "(" + fieldArr + ".length)) {");
            emitLine(out_,
                     indent_ + 1,
                     "throw new Error(\"" +
                         codegen_diagnostic_text::fieldExceedsMaxLength(field.fieldName, cap, unionContext_) + "\");");
            emitLine(out_, indent_, "}");
        }
        else
        {
            emitLine(out_, indent_, "if (" + fieldArr + ".length > " + cap + ") {");
            emitLine(out_,
                     indent_ + 1,
                     "throw new Error(\"" +
                         codegen_diagnostic_text::fieldExceedsMaxLength(field.fieldName, cap, unionContext_) + "\");");
            emitLine(out_, indent_, "}");
        }
        std::string prefixExpr = fieldArr + ".length";
        if (!helpers.serArrayPrefix.empty())
        {
            prefixExpr = "Number(" + helpers.serArrayPrefix + "(" + prefixExpr + "))";
        }
        ctx_.trace(EmitTraceOp::LenWrite, field.arrayLengthPrefixBits);
        emitLine(out_,
                 indent_,
                 "dsdlRuntime.writeUnsigned(out, offsetBits, " + prefixBits + ", " + prefixExpr + ", false);");
        ctx_.trace(EmitTraceOp::Advance, field.arrayLengthPrefixBits);
        emitLine(out_, indent_, "offsetBits += " + prefixBits + ";");
    }

    std::string spellVariableArrayLenDeserialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        (void) expr;
        const auto& field      = operation_.body.field;
        const auto& helpers    = operation_.body.helpers;
        const auto  cap        = std::to_string(field.arrayCapacity);
        const auto  prefixBits = std::to_string(field.arrayLengthPrefixBits);
        const auto  fieldArr   = field.fieldName + "Array";
        const auto  rawLen     = field.fieldName + "LengthRaw";
        ctx_.trace(EmitTraceOp::LenRead, field.arrayLengthPrefixBits);
        emitLine(out_,
                 indent_,
                 "const " + rawLen + " = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, " + prefixBits + "));");
        ctx_.trace(EmitTraceOp::Advance, field.arrayLengthPrefixBits);
        emitLine(out_, indent_, "offsetBits += " + prefixBits + ";");
        const auto normalizedLen = field.fieldName + "Length";
        if (!helpers.deserArrayPrefix.empty())
        {
            emitLine(out_,
                     indent_,
                     "const " + normalizedLen + " = Number(" + helpers.deserArrayPrefix + "(" + rawLen + "));");
        }
        else
        {
            emitLine(out_, indent_, "const " + normalizedLen + " = " + rawLen + ";");
        }
        ctx_.trace(EmitTraceOp::LenValidate, field.arrayLengthPrefixBits);
        if (!helpers.arrayValidate.empty())
        {
            emitLine(out_, indent_, "if (!" + helpers.arrayValidate + "(" + normalizedLen + ")) {");
        }
        else
        {
            emitLine(out_, indent_, "if (" + normalizedLen + " < 0 || " + normalizedLen + " > " + cap + ") {");
        }
        emitLine(out_,
                 indent_ + 1,
                 "throw new Error(\"" +
                     codegen_diagnostic_text::decodedLengthExceedsMaxLength(field.fieldName, cap, unionContext_) +
                     "\");");
        emitLine(out_, indent_, "}");
        emitLine(out_,
                 indent_,
                 "const " + fieldArr + ": Array<" + arrayElemType() + "> = new Array(" + normalizedLen + ");");
        return normalizedLen;
    }

    std::string spellFixedArrayCountDeserialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        (void) expr;
        const auto& field    = operation_.body.field;
        const auto  cap      = std::to_string(field.arrayCapacity);
        const auto  fieldArr = field.fieldName + "Array";
        emitLine(out_, indent_, "const " + fieldArr + ": Array<" + arrayElemType() + "> = new Array(" + cap + ");");
        return cap;
    }

    std::string spellBeginElemLoopSerialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) expr;
        const auto& field    = operation_.body.field;
        const auto  fieldArr = field.fieldName + "Array";
        const auto  bound =
            step.kind == FieldStepKind::VariableArray ? fieldArr + ".length" : std::to_string(field.arrayCapacity);
        ctx_.trace(EmitTraceOp::ElemLoop);
        emitLine(out_, indent_, "for (let i = 0; i < " + bound + "; ++i) {");
        ++indent_;
        inElement_ = true;
        // The union option array came from an `unknown`-typed member, so composite
        // elements carry an explicit cast for the nested serializer call.
        if (unionContext_ && field.kind == RuntimeFieldKind::Composite)
        {
            return fieldArr + "[i] as " + compositeTypeName(field, ctx_);
        }
        return fieldArr + "[i]";
    }

    std::string spellBeginElemLoopDeserialize(const FieldEmitStep& step,
                                              const std::string&   expr,
                                              const std::string&   countExpr) override
    {
        (void) step;
        (void) expr;
        const auto fieldArr = operation_.body.field.fieldName + "Array";
        ctx_.trace(EmitTraceOp::ElemLoop);
        emitLine(out_, indent_, "for (let i = 0; i < " + countExpr + "; ++i) {");
        ++indent_;
        inElement_ = true;
        return fieldArr + "[i]";
    }

    void spellEndElemLoopSerialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        (void) expr;
        inElement_ = false;
        --indent_;
        emitLine(out_, indent_, "}");
    }

    void spellEndElemLoopDeserialize(const FieldEmitStep& step, const std::string& expr) override
    {
        (void) step;
        inElement_ = false;
        --indent_;
        emitLine(out_, indent_, "}");
        emitStore(expr, operation_.body.field.fieldName + "Array");
    }

private:
    /// @brief Root de-target store: union case bodies declare `const optionValue`,
    ///        struct bodies assign the member; element targets always assign.
    void emitStore(const std::string& target, const std::string& valueExpr)
    {
        if (!inElement_ && unionContext_)
        {
            emitLine(out_, indent_, "const " + target + " = " + valueExpr + ";");
        }
        else
        {
            emitLine(out_, indent_, target + " = " + valueExpr + ";");
        }
    }

    std::string rawSuffix() const
    {
        if (inElement_)
        {
            return "ItemRaw";
        }
        return unionContext_ ? "OptionRaw" : "Raw";
    }

    std::string arrayElemType() const
    {
        const auto& field = operation_.body.field;
        return field.kind == RuntimeFieldKind::Bool
                   ? "boolean"
                   : (field.kind == RuntimeFieldKind::Composite ? compositeTypeName(field, ctx_)
                                                                : (field.useBigInt ? "bigint" : "number"));
    }

    std::ostringstream&               out_;
    const EmitterContext&             ctx_;
    const ScriptedFieldOperationPlan& operation_;
    int                               indent_;
    const bool                        unionContext_;
    HelperBindingDirection            direction_{};
    bool                              inElement_{false};
};

/// @brief Root serialize expression for a union option: optionValue with the
///        kind-appropriate cast (the option member is `unknown`-typed).
std::string tsUnionOptionSerializeExpr(const ScriptedFieldOperationPlan& operation, const EmitterContext& ctx)
{
    const auto& field = operation.body.field;
    if (operation.cardinality != ScriptedFieldCardinality::Scalar)
    {
        return "optionValue";
    }
    switch (operation.valueKind)
    {
    case ScriptedFieldValueKind::Bool:
        return "!!optionValue";
    case ScriptedFieldValueKind::Composite:
        return "optionValue as " + compositeTypeName(field, ctx);
    case ScriptedFieldValueKind::Float:
        return "optionValue as number";
    case ScriptedFieldValueKind::Unsigned:
    case ScriptedFieldValueKind::Signed:
        return "optionValue as number | bigint";
    case ScriptedFieldValueKind::Padding:
        break;
    }
    return "optionValue";
}

/// @brief Renders one TS union serialize case body (option guard + aligned field ops).
void emitTsUnionSerializeCaseBody(std::ostringstream&               out,
                                  const EmitterContext&             ctx,
                                  const ScriptedFieldOperationPlan& scriptedField)
{
    const auto& field     = scriptedField.body.field;
    const auto  optionTag = std::to_string(field.unionOptionIndex);
    emitLine(out, 2, "const optionValue = (value as Record<string, unknown>)." + field.fieldName + ";");
    emitLine(out, 2, "if (optionValue === undefined) {");
    emitLine(out,
             3,
             "throw new Error(\"" + codegen_diagnostic_text::unionFieldMissingForTag(field.fieldName, optionTag) +
                 "\");");
    emitLine(out, 2, "}");
    emitTsRuntimeAlignSerialize(out, 2, field.alignmentBits, field.fieldName + "Option", ctx);
    assert(scriptedField.serializeSteps.has_value());
    TsFieldSpelling spelling(out, ctx, scriptedField, 2, /*unionContext=*/true);
    spelling.setDirection(HelperBindingDirection::Serialize);
    renderFieldSteps(*scriptedField.serializeSteps,
                     tsUnionOptionSerializeExpr(scriptedField, ctx),
                     HelperBindingDirection::Serialize,
                     spelling);
}

/// @brief Renders one TS union deserialize case body (aligned field ops + value construction).
void emitTsUnionDeserializeCaseBody(std::ostringstream&               out,
                                    const EmitterContext&             ctx,
                                    const ScriptedFieldOperationPlan& scriptedField,
                                    const std::string&                typeName)
{
    const auto& field     = scriptedField.body.field;
    const auto  optionTag = std::to_string(field.unionOptionIndex);
    emitTsRuntimeAlignDeserialize(out, 2, field.alignmentBits, ctx);
    assert(scriptedField.deserializeSteps.has_value());
    TsFieldSpelling spelling(out, ctx, scriptedField, 2, /*unionContext=*/true);
    spelling.setDirection(HelperBindingDirection::Deserialize);
    renderFieldSteps(*scriptedField.deserializeSteps, "optionValue", HelperBindingDirection::Deserialize, spelling);
    emitLine(out, 2, "value = { _tag: " + optionTag + ", " + field.fieldName + ": optionValue } as " + typeName + ";");
}

/// @brief Canonical (backend-independent) DSDL section label for emit-order trace segments.
/// @param[in] info Discovered definition identity.
/// @param[in] sectionSuffix "" for a message type, ".Request"/".Response" for service halves.
/// @return "full.type.Name[.Request|.Response].major.minor".
std::string canonicalDefinitionName(const DiscoveredDefinition& info, const std::string& sectionSuffix)
{
    return info.fullName + sectionSuffix + "." + std::to_string(info.majorVersion) + "." +
           std::to_string(info.minorVersion);
}

llvm::Error emitTsRuntimeFunctions(std::ostringstream&        out,
                                   const std::string&         typeName,
                                   const std::string&         canonicalSectionName,
                                   const RuntimeSectionPlan&  plan,
                                   const EmitterContext&      ctx,
                                   const SemanticSection&     section,
                                   const LoweredSectionFacts* sectionFacts)
{
    const auto serializeFn   = tsRuntimeSerializeFn(typeName);
    const auto deserializeFn = tsRuntimeDeserializeFn(typeName);
    const auto maxByteLength = (plan.maxBits + 7) / 8;
    const auto serializeHelpers =
        buildSectionHelperBindingPlan(section, sectionFacts, HelperBindingDirection::Serialize);
    const auto deserializeHelpers =
        buildSectionHelperBindingPlan(section, sectionFacts, HelperBindingDirection::Deserialize);

    const RuntimeHelperNameResolver helperNameResolver = [](const std::string& symbol) {
        return helperBindingNameTs(symbol);
    };
    auto operationPlan = buildScriptedSectionOperationPlan(section, plan, sectionFacts, helperNameResolver);
    if (!operationPlan)
    {
        return operationPlan.takeError();
    }
    const NamingScope fieldIdents = makeTsFieldIdents(section);
    for (auto& scriptedField : operationPlan->fields)
    {
        auto&       field        = scriptedField.body.field;
        const auto& semanticName = field.semanticFieldName.empty() ? field.fieldName : field.semanticFieldName;
        field.fieldName          = fieldIdents.get(IdentifierRole::FieldName, semanticName);
    }
    const auto& sectionHelperNames = operationPlan->sectionHelpers;

    const auto emitSerializeHelperBindings = [&]() {
        const auto lines = renderSectionHelperBindings(serializeHelpers,
                                                       HelperBindingRenderLanguage::TypeScript,
                                                       ScalarBindingRenderDirection::Serialize,
                                                       helperNameResolver,
                                                       /*emitCapacityCheck=*/true);
        for (const auto& line : lines)
        {
            emitLine(out, 1, line);
        }
        if (!lines.empty())
        {
            emitLine(out, 1, "");
        }
    };

    const auto emitDeserializeHelperBindings = [&]() {
        const auto lines = renderSectionHelperBindings(deserializeHelpers,
                                                       HelperBindingRenderLanguage::TypeScript,
                                                       ScalarBindingRenderDirection::Deserialize,
                                                       helperNameResolver,
                                                       /*emitCapacityCheck=*/false);
        for (const auto& line : lines)
        {
            emitLine(out, 1, line);
        }
        if (!lines.empty())
        {
            emitLine(out, 1, "");
        }
    };

    if (operationPlan->isUnion)
    {
        const auto tagBits = std::to_string(operationPlan->unionTagBits);
        ctx.traceSection(canonicalSectionName, EmitTraceDirection::Serialize);
        emitLine(out, 0, "export function " + serializeFn + "(value: " + typeName + "): Uint8Array {");
        emitLine(out, 1, "const out = new Uint8Array(" + std::to_string(maxByteLength) + ");");
        emitLine(out, 1, "let offsetBits = 0;");
        emitSerializeHelperBindings();
        if (!sectionHelperNames.capacityCheck.empty())
        {
            emitLine(out, 1, "if (!" + sectionHelperNames.capacityCheck + "(out.length * 8)) {");
            emitLine(out, 2, "throw new Error(\"" + codegen_diagnostic_text::serializationBufferTooSmall() + "\");");
            emitLine(out, 1, "}");
        }
        emitLine(out, 1, "let tag = Math.trunc((value as { _tag: number })._tag);");
        {
            TsUnionSpelling spelling(out, ctx, sectionHelperNames, operationPlan->unionTagBits, "");
            spelling.setBadTagDiagnosticPrefix(codegen_diagnostic_text::invalidUnionTagPrefix());
            std::vector<UnionCaseRender> cases;
            cases.reserve(operationPlan->fields.size());
            for (const auto& scriptedField : operationPlan->fields)
            {
                cases.push_back(
                    UnionCaseRender{scriptedField.body.field.unionOptionIndex, [&out, &ctx, &scriptedField]() {
                                        emitTsUnionSerializeCaseBody(out, ctx, scriptedField);
                                    }});
            }
            renderUnionSection(EmitTraceDirection::Serialize, cases, spelling);
        }
        emitLine(out, 1, "const alignedOffsetBits = dsdlRuntime.byteLengthForBits(offsetBits) * 8;");
        emitLine(out, 1, "for (let bit = offsetBits; bit < alignedOffsetBits; ++bit) {");
        emitLine(out, 2, "dsdlRuntime.setBit(out, bit, false);");
        emitLine(out, 1, "}");
        emitLine(out, 1, "offsetBits = alignedOffsetBits;");
        emitLine(out, 1, "const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);");
        emitLine(out, 1, "return out.subarray(0, usedBytes);");
        emitLine(out, 0, "}");
        emitLine(out, 0, "");

        ctx.traceSection(canonicalSectionName, EmitTraceDirection::Deserialize);
        emitLine(out,
                 0,
                 "export function " + deserializeFn + "(bytes: Uint8Array): { value: " + typeName +
                     "; consumed: number } {");
        emitDeserializeHelperBindings();
        emitLine(out, 1, "let offsetBits = 0;");
        {
            TsUnionSpelling spelling(out,
                                     ctx,
                                     sectionHelperNames,
                                     operationPlan->unionTagBits,
                                     "let value: " + typeName + ";");
            spelling.setBadTagDiagnosticPrefix(codegen_diagnostic_text::decodedInvalidUnionTagPrefix());
            std::vector<UnionCaseRender> cases;
            cases.reserve(operationPlan->fields.size());
            for (const auto& scriptedField : operationPlan->fields)
            {
                cases.push_back(UnionCaseRender{scriptedField.body.field.unionOptionIndex,
                                                [&out, &ctx, &scriptedField, &typeName]() {
                                                    emitTsUnionDeserializeCaseBody(out, ctx, scriptedField, typeName);
                                                }});
            }
            renderUnionSection(EmitTraceDirection::Deserialize, cases, spelling);
        }
        emitLine(out, 1, "offsetBits = dsdlRuntime.byteLengthForBits(offsetBits) * 8;");
        emitLine(out, 1, "const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));");
        emitLine(out, 1, "return { value, consumed };");
        emitLine(out, 0, "}");
        return llvm::Error::success();
    }

    ctx.traceSection(canonicalSectionName, EmitTraceDirection::Serialize);
    emitLine(out, 0, "export function " + serializeFn + "(value: " + typeName + "): Uint8Array {");
    emitLine(out, 1, "const out = new Uint8Array(" + std::to_string(maxByteLength) + ");");
    emitLine(out, 1, "let offsetBits = 0;");
    emitSerializeHelperBindings();
    if (!sectionHelperNames.capacityCheck.empty())
    {
        emitLine(out, 1, "if (!" + sectionHelperNames.capacityCheck + "(out.length * 8)) {");
        emitLine(out, 2, "throw new Error(\"" + codegen_diagnostic_text::serializationBufferTooSmall() + "\");");
        emitLine(out, 1, "}");
    }
    for (const auto& scriptedField : operationPlan->fields)
    {
        const auto& field = scriptedField.body.field;
        emitTsRuntimeAlignSerialize(out, 1, field.alignmentBits, field.fieldName, ctx);
        assert(scriptedField.serializeSteps.has_value());
        TsFieldSpelling spelling(out, ctx, scriptedField, 1, /*unionContext=*/false);
        spelling.setDirection(HelperBindingDirection::Serialize);
        renderFieldSteps(*scriptedField.serializeSteps,
                         "value." + field.fieldName,
                         HelperBindingDirection::Serialize,
                         spelling);
    }
    emitLine(out, 1, "const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);");
    emitLine(out, 1, "return out.subarray(0, usedBytes);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");

    ctx.traceSection(canonicalSectionName, EmitTraceDirection::Deserialize);
    emitLine(out,
             0,
             "export function " + deserializeFn + "(bytes: Uint8Array): { value: " + typeName +
                 "; consumed: number } {");
    emitDeserializeHelperBindings();
    emitLine(out, 1, "const value = {} as " + typeName + ";");
    emitLine(out, 1, "let offsetBits = 0;");
    for (const auto& scriptedField : operationPlan->fields)
    {
        const auto& field = scriptedField.body.field;
        emitTsRuntimeAlignDeserialize(out, 1, field.alignmentBits, ctx);
        assert(scriptedField.deserializeSteps.has_value());
        TsFieldSpelling spelling(out, ctx, scriptedField, 1, /*unionContext=*/false);
        spelling.setDirection(HelperBindingDirection::Deserialize);
        renderFieldSteps(*scriptedField.deserializeSteps,
                         "value." + field.fieldName,
                         HelperBindingDirection::Deserialize,
                         spelling);
    }
    emitLine(out, 1, "const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));");
    emitLine(out, 1, "return { value, consumed };");
    emitLine(out, 0, "}");
    return llvm::Error::success();
}

llvm::Expected<std::string> renderDefinitionFile(const SemanticDefinition& def,
                                                 const EmitterContext&     ctx,
                                                 const LoweredFactsMap&    loweredFacts)
{
    std::ostringstream out;
    emitLine(out, 0, generatedCommentLine("TypeScript backend"));
    emitLine(out,
             0,
             "// Source: " + def.info.fullName + "." + std::to_string(def.info.majorVersion) + "." +
                 std::to_string(def.info.minorVersion));

    const llvm::StringRef      requestSectionKey   = def.isService ? "request" : "";
    const LoweredSectionFacts* requestSectionFacts = lookupLoweredSectionFacts(loweredFacts, def, requestSectionKey);
    auto                       requestRuntimePlan  = buildRuntimeSectionPlan(def.request, requestSectionFacts);
    if (!requestRuntimePlan)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "failed to build TypeScript request runtime plan for '%s': %s",
                                       def.info.fullName.c_str(),
                                       llvm::toString(requestRuntimePlan.takeError()).c_str());
    }
    std::optional<RuntimeSectionPlan> responseRuntimePlanStorage;
    const RuntimeSectionPlan*         responseRuntimePlan = nullptr;
    if (def.response)
    {
        const auto* const responseSectionFacts = lookupLoweredSectionFacts(loweredFacts, def, "response");
        auto              responsePlanOrErr    = buildRuntimeSectionPlan(*def.response, responseSectionFacts);
        if (!responsePlanOrErr)
        {
            return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                           "failed to build TypeScript response runtime plan for '%s': %s",
                                           def.info.fullName.c_str(),
                                           llvm::toString(responsePlanOrErr.takeError()).c_str());
        }
        responseRuntimePlanStorage = std::move(*responsePlanOrErr);
        responseRuntimePlan        = &(*responseRuntimePlanStorage);
    }

    const auto ownerPath = ctx.relativeFilePath(def.info);

    // Disambiguate before anything is rendered.
    //
    // Two types from different namespaces can share a short name -- `uavcan.si.unit.velocity.Vector3`
    // and `uavcan.si.unit.angular_velocity.Vector3` are both `Vector3_1_0` -- and a file that
    // references both would import the same identifier twice, which `tsc` rejects outright as a
    // duplicate identifier. So the referenced set is collected first, short-name clashes are found,
    // and the clashing types are given namespace-qualified local names. Installing the table on the
    // context before any rendering is what keeps the import list, the type annotations, and the
    // serialize/deserialize call names in agreement: they all resolve through ctx.typeName().
    {
        std::map<std::string, std::vector<const DiscoveredDefinition*>> byShortName;
        const auto collectReferenced = [&](const SemanticSection& section) {
            for (const auto& ref : collectCompositeDependencies(section, def.info))
            {
                if (const auto* referenced = ctx.find(ref))
                {
                    auto&      bucket = byShortName[ctx.typeName(referenced->info)];
                    const auto key    = EmitterContext::importAliasKey(referenced->info);
                    const bool seen   = std::any_of(bucket.begin(), bucket.end(), [&](const auto* other) {
                        return EmitterContext::importAliasKey(*other) == key;
                    });
                    if (!seen)
                    {
                        bucket.push_back(&referenced->info);
                    }
                }
            }
        };
        collectReferenced(def.request);
        if (def.response)
        {
            collectReferenced(*def.response);
        }

        std::map<std::string, std::string> aliases;
        for (const auto& [shortName, definitions] : byShortName)
        {
            if (definitions.size() < 2U)
            {
                continue;
            }
            for (const auto* info : definitions)
            {
                // Namespace as a suffix rather than a prefix. The serialize and deserialize call
                // names are built by sticking a verb on the front of this, and a leading lowercase
                // namespace would run the two together -- `deserializeuavcan_si_unit_...`. Keeping
                // the type name where it has always been leaves those readable and leaves the
                // recognisable part of the identifier first.
                std::string qualified = shortName + "__";
                for (const auto& component : info->namespaceComponents)
                {
                    qualified += component + "_";
                }
                qualified.pop_back();
                aliases.emplace(EmitterContext::importAliasKey(*info), qualified);
            }
        }
        ctx.setImportAliases(std::move(aliases));
    }

    std::map<std::string, std::set<std::pair<std::string, std::string>>> importsByModule;
    const auto addSectionImports = [&](const SemanticSection& section) {
        const auto dependencies = collectCompositeDependencies(section, def.info);
        const auto imports      = projectCompositeImports(
            dependencies,
            [&](const SemanticTypeRef& ref) { return relativeImportPath(ownerPath, ctx.relativeFilePath(ref)); },
            [&](const SemanticTypeRef& ref) { return ctx.typeName(ref); });
        for (const auto& importSpec : imports)
        {
            std::string original = importSpec.typeName;
            for (const auto& ref : dependencies)
            {
                if (const auto* referenced = ctx.find(ref);
                    referenced != nullptr && ctx.typeName(ref) == importSpec.typeName)
                {
                    original = ctx.typeName(referenced->info);
                    break;
                }
            }
            importsByModule[importSpec.modulePath].emplace(original, importSpec.typeName);
        }
    };
    addSectionImports(def.request);
    if (def.response)
    {
        addSectionImports(*def.response);
    }

    std::map<std::string, std::set<std::pair<std::string, std::string>>> runtimeImportsByModule;
    const auto addRuntimeImportsForPlan = [&](const RuntimeSectionPlan* const plan) {
        if (plan == nullptr)
        {
            return;
        }
        for (const auto& field : plan->fields)
        {
            if (field.kind != RuntimeFieldKind::Composite || !field.compositeType)
            {
                continue;
            }
            const auto targetPath = ctx.relativeFilePath(*field.compositeType);
            if (targetPath == ownerPath)
            {
                continue;
            }
            const auto  modulePath   = relativeImportPath(ownerPath, targetPath);
            const auto  localName    = compositeTypeName(field, ctx);
            const auto* referenced   = ctx.find(*field.compositeType);
            const auto  originalName = (referenced != nullptr) ? ctx.typeName(referenced->info) : localName;
            runtimeImportsByModule[modulePath].emplace(tsRuntimeSerializeFn(originalName),
                                                       tsRuntimeSerializeFn(localName));
            runtimeImportsByModule[modulePath].emplace(tsRuntimeDeserializeFn(originalName),
                                                       tsRuntimeDeserializeFn(localName));
        }
    };
    addRuntimeImportsForPlan(&(*requestRuntimePlan));
    addRuntimeImportsForPlan(responseRuntimePlan);

    const auto runtimePath = relativeImportPath(ownerPath, std::filesystem::path("dsdl_runtime.ts"));
    emitLine(out, 0, "import * as dsdlRuntime from \"" + runtimePath + "\";");
    emitLine(out, 0, "");

    // `Original as Local`, collapsing to plain `Original` when nothing had to be renamed -- so a
    // file that references no clashing names looks exactly as it did before aliasing existed.
    const auto renderImportList = [](const std::set<std::pair<std::string, std::string>>& names) {
        std::string rendered;
        for (const auto& [original, local] : names)
        {
            if (!rendered.empty())
            {
                rendered += ", ";
            }
            rendered += (original == local) ? original : (original + " as " + local);
        }
        return rendered;
    };

    for (const auto& [modulePath, names] : runtimeImportsByModule)
    {
        emitLine(out, 0, "import { " + renderImportList(names) + " } from \"" + modulePath + "\";");
    }

    for (const auto& [modulePath, names] : importsByModule)
    {
        emitLine(out, 0, "import type { " + renderImportList(names) + " } from \"" + modulePath + "\";");
    }
    const auto baseType = ctx.typeName(def.info);
    emitLine(out, 0, "export const LLVMDSDL_GENERATOR_VERSION = \"" + std::string(llvmdsdl::kVersionString) + "\";");
    emitLine(out, 0, "export const DSDL_FULL_NAME = \"" + def.info.fullName + "\";");
    emitLine(out,
             0,
             "export const DSDL_IS_DEPRECATED = " + std::string(def.request.deprecated ? "true" : "false") + ";");
    emitLine(out, 0, "export const DSDL_VERSION_MAJOR = " + std::to_string(def.info.majorVersion) + ";");
    emitLine(out, 0, "export const DSDL_VERSION_MINOR = " + std::to_string(def.info.minorVersion) + ";");
    const bool        requestZohEligible = requestSectionFacts != nullptr && requestSectionFacts->zohAliasEligible;
    const std::string requestZohReason =
        (requestSectionFacts != nullptr && !requestSectionFacts->zohAliasReason.empty())
            ? requestSectionFacts->zohAliasReason
            : "not-proven";
    emitLine(out,
             0,
             "export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = " + std::string(requestZohEligible ? "true" : "false") +
                 ";");
    emitLine(out, 0, "export const DSDL_REQUEST_ZOH_ALIAS_REASON = \"" + requestZohReason + "\";");
    if (responseRuntimePlan != nullptr)
    {
        const auto* const responseSectionFacts = lookupLoweredSectionFacts(loweredFacts, def, "response");
        const bool responseZohEligible = responseSectionFacts != nullptr && responseSectionFacts->zohAliasEligible;
        const std::string responseZohReason =
            (responseSectionFacts != nullptr && !responseSectionFacts->zohAliasReason.empty())
                ? responseSectionFacts->zohAliasReason
                : "not-proven";
        emitLine(out,
                 0,
                 "export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = " +
                     std::string(responseZohEligible ? "true" : "false") + ";");
        emitLine(out, 0, "export const DSDL_RESPONSE_ZOH_ALIAS_REASON = \"" + responseZohReason + "\";");
    }
    else
    {
        emitLine(out, 0, "export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;");
        emitLine(out, 0, "export const DSDL_RESPONSE_ZOH_ALIAS_REASON = \"not-applicable\";");
    }
    emitLine(out, 0, "");

    if (!def.isService)
    {
        emitSectionType(out,
                        baseType,
                        def.request,
                        def.doc,
                        ctx,
                        def.info.fullName,
                        def.info.majorVersion,
                        def.info.minorVersion);
        emitLine(out, 0, "");
        emitSectionConstants(out, baseType, def.request);
        emitLine(out, 0, "");
        if (auto err = emitTsRuntimeFunctions(out,
                                              baseType,
                                              canonicalDefinitionName(def.info, ""),
                                              *requestRuntimePlan,
                                              ctx,
                                              def.request,
                                              requestSectionFacts))
        {
            return std::move(err);
        }
        return out.str();
    }

    const auto reqType  = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::TypeScript, "request");
    const auto respType = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::TypeScript, "response");

    emitSectionType(out,
                    reqType,
                    def.request,
                    def.doc,
                    ctx,
                    def.info.fullName,
                    def.info.majorVersion,
                    def.info.minorVersion);
    emitLine(out, 0, "");
    emitSectionConstants(out, reqType, def.request);
    emitLine(out, 0, "");
    if (auto err = emitTsRuntimeFunctions(out,
                                          reqType,
                                          canonicalDefinitionName(def.info, ".Request"),
                                          *requestRuntimePlan,
                                          ctx,
                                          def.request,
                                          requestSectionFacts))
    {
        return std::move(err);
    }
    emitLine(out, 0, "");

    if (def.response)
    {
        emitSectionType(out,
                        respType,
                        *def.response,
                        def.doc,
                        ctx,
                        def.info.fullName,
                        def.info.majorVersion,
                        def.info.minorVersion);
        emitLine(out, 0, "");
        emitSectionConstants(out, respType, *def.response);
        emitLine(out, 0, "");
        if (auto err = emitTsRuntimeFunctions(out,
                                              respType,
                                              canonicalDefinitionName(def.info, ".Response"),
                                              *responseRuntimePlan,
                                              ctx,
                                              *def.response,
                                              lookupLoweredSectionFacts(loweredFacts, def, "response")))
        {
            return std::move(err);
        }
        emitLine(out, 0, "");
    }

    emitLine(out, 0, "export type " + baseType + " = " + reqType + ";");
    return out.str();
}

std::string renderPackageJson(const TsEmitOptions& options)
{
    const auto runtimeSpecialization =
        options.runtimeSpecialization == TsRuntimeSpecialization::Fast ? "fast" : "portable";
    std::ostringstream out;
    out << "{\n";
    out << "  \"name\": \"" << options.moduleName << "\",\n";
    out << "  \"version\": \"" << llvmdsdl::kVersionString << "\",\n";
    out << "  \"type\": \"module\",\n";
    out << "  \"llvmdsdl\": {\n";
    out << "    \"generatorVersion\": \"" << llvmdsdl::kVersionString << "\",\n";
    out << "    \"tsRuntimeSpecialization\": \"" << runtimeSpecialization << "\"\n";
    out << "  }\n";
    out << "}\n";
    return out.str();
}

std::string renderTsRuntimeModule(const TsRuntimeSpecialization runtimeSpecialization)
{
    std::ostringstream out;
    emitLine(out, 0, generatedCommentLine("TypeScript runtime scaffold"));
    emitLine(out, 0, "");
    emitLine(out, 0, "function toBigIntValue(value: number | bigint): bigint {");
    emitLine(out, 1, "if (typeof value === \"bigint\") {");
    emitLine(out, 2, "return value;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (!Number.isFinite(value)) {");
    emitLine(out, 2, "return 0n;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return BigInt(Math.trunc(value));");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function maskBits(lenBits: number): bigint {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return 0n;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return (1n << BigInt(lenBits)) - 1n;");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function byteLengthForBits(totalBits: number): number {");
    emitLine(out, 1, "if (totalBits <= 0) {");
    emitLine(out, 2, "return 0;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return Math.floor((totalBits + 7) / 8);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function setRawBit(buf: Uint8Array, offBits: number, bit: boolean): void {");
    emitLine(out, 1, "const byteIndex = Math.floor(offBits / 8);");
    emitLine(out, 1, "const bitIndex = offBits % 8;");
    emitLine(out, 1, "if (byteIndex < 0 || byteIndex >= buf.length) {");
    emitLine(out, 2, "throw new Error(\"" + codegen_diagnostic_text::serializationBufferTooSmall() + "\");");
    emitLine(out, 1, "}");
    emitLine(out, 1, "const mask = 1 << bitIndex;");
    emitLine(out, 1, "if (bit) {");
    emitLine(out, 2, "buf[byteIndex] = (buf[byteIndex] | mask) & 0xff;");
    emitLine(out, 1, "} else {");
    emitLine(out, 2, "buf[byteIndex] = (buf[byteIndex] & (~mask)) & 0xff;");
    emitLine(out, 1, "}");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function getRawBit(buf: Uint8Array, offBits: number): boolean {");
    emitLine(out, 1, "const byteIndex = Math.floor(offBits / 8);");
    emitLine(out, 1, "const bitIndex = offBits % 8;");
    emitLine(out, 1, "if (byteIndex < 0 || byteIndex >= buf.length) {");
    emitLine(out, 2, "return false;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return ((buf[byteIndex] >> bitIndex) & 1) === 1;");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function writeUnsignedBits(");
    emitLine(out, 1, "buf: Uint8Array,");
    emitLine(out, 1, "offBits: number,");
    emitLine(out, 1, "lenBits: number,");
    emitLine(out, 1, "value: bigint");
    emitLine(out, 0, "): void {");
    emitLine(out, 1, "for (let i = 0; i < lenBits; ++i) {");
    emitLine(out, 2, "const bit = ((value >> BigInt(i)) & 1n) === 1n;");
    emitLine(out, 2, "setRawBit(buf, offBits + i, bit);");
    emitLine(out, 1, "}");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function readUnsignedBits(buf: Uint8Array, offBits: number, lenBits: number): bigint {");
    emitLine(out, 1, "let out = 0n;");
    emitLine(out, 1, "for (let i = 0; i < lenBits; ++i) {");
    emitLine(out, 2, "if (getRawBit(buf, offBits + i)) {");
    emitLine(out, 3, "out |= (1n << BigInt(i));");
    emitLine(out, 2, "}");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return out;");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function setBit(buf: Uint8Array, offBits: number, value: boolean): void {");
    emitLine(out, 1, "setRawBit(buf, offBits, !!value);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function getBit(buf: Uint8Array, offBits: number): boolean {");
    emitLine(out, 1, "return getRawBit(buf, offBits);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function copyBits(");
    emitLine(out, 1, "dst: Uint8Array,");
    emitLine(out, 1, "dstOffBits: number,");
    emitLine(out, 1, "src: Uint8Array,");
    emitLine(out, 1, "srcOffBits: number,");
    emitLine(out, 1, "lenBits: number");
    emitLine(out, 0, "): void {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return;");
    emitLine(out, 1, "}");
    if (runtimeSpecialization == TsRuntimeSpecialization::Fast)
    {
        emitLine(out, 1, "if (dst !== src && dstOffBits % 8 === 0 && srcOffBits % 8 === 0 && lenBits % 8 === 0) {");
        emitLine(out, 2, "const dstStart = Math.floor(dstOffBits / 8);");
        emitLine(out, 2, "const srcStart = Math.floor(srcOffBits / 8);");
        emitLine(out, 2, "const byteLen = Math.floor(lenBits / 8);");
        emitLine(out, 2, "if (dstStart >= 0 && srcStart >= 0 &&");
        emitLine(out, 3, "dstStart + byteLen <= dst.length && srcStart + byteLen <= src.length) {");
        emitLine(out, 3, "dst.set(src.subarray(srcStart, srcStart + byteLen), dstStart);");
        emitLine(out, 3, "return;");
        emitLine(out, 2, "}");
        emitLine(out, 1, "}");
    }
    emitLine(out, 1, "for (let i = 0; i < lenBits; ++i) {");
    emitLine(out, 2, "setRawBit(dst, dstOffBits + i, getRawBit(src, srcOffBits + i));");
    emitLine(out, 1, "}");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function extractBits(");
    emitLine(out, 1, "src: Uint8Array,");
    emitLine(out, 1, "srcOffBits: number,");
    emitLine(out, 1, "lenBits: number");
    emitLine(out, 0, "): Uint8Array {");
    if (runtimeSpecialization == TsRuntimeSpecialization::Fast)
    {
        emitLine(out, 1, "if (srcOffBits % 8 === 0 && lenBits % 8 === 0) {");
        emitLine(out, 2, "const srcStart = Math.floor(srcOffBits / 8);");
        emitLine(out, 2, "const byteLen = Math.floor(lenBits / 8);");
        emitLine(out, 2, "if (srcStart >= 0 && srcStart + byteLen <= src.length) {");
        emitLine(out, 3, "return src.slice(srcStart, srcStart + byteLen);");
        emitLine(out, 2, "}");
        emitLine(out, 1, "}");
    }
    emitLine(out, 1, "const out = new Uint8Array(byteLengthForBits(lenBits));");
    emitLine(out, 1, "copyBits(out, 0, src, srcOffBits, lenBits);");
    emitLine(out, 1, "return out;");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function writeUnsigned(");
    emitLine(out, 1, "buf: Uint8Array,");
    emitLine(out, 1, "offBits: number,");
    emitLine(out, 1, "lenBits: number,");
    emitLine(out, 1, "value: number | bigint,");
    emitLine(out, 1, "saturating: boolean");
    emitLine(out, 0, "): void {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "const max = maskBits(lenBits);");
    emitLine(out, 1, "let inValue = toBigIntValue(value);");
    emitLine(out, 1, "if (saturating) {");
    emitLine(out, 2, "if (inValue < 0n) {");
    emitLine(out, 3, "inValue = 0n;");
    emitLine(out, 2, "} else if (inValue > max) {");
    emitLine(out, 3, "inValue = max;");
    emitLine(out, 2, "}");
    emitLine(out, 1, "} else {");
    emitLine(out, 2, "inValue = BigInt.asUintN(lenBits, inValue);");
    emitLine(out, 1, "}");
    emitLine(out, 1, "writeUnsignedBits(buf, offBits, lenBits, inValue);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function writeSigned(");
    emitLine(out, 1, "buf: Uint8Array,");
    emitLine(out, 1, "offBits: number,");
    emitLine(out, 1, "lenBits: number,");
    emitLine(out, 1, "value: number | bigint,");
    emitLine(out, 1, "saturating: boolean");
    emitLine(out, 0, "): void {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "let inValue = toBigIntValue(value);");
    emitLine(out, 1, "if (saturating) {");
    emitLine(out, 2, "const min = -(1n << BigInt(lenBits - 1));");
    emitLine(out, 2, "const max = (1n << BigInt(lenBits - 1)) - 1n;");
    emitLine(out, 2, "if (inValue < min) {");
    emitLine(out, 3, "inValue = min;");
    emitLine(out, 2, "} else if (inValue > max) {");
    emitLine(out, 3, "inValue = max;");
    emitLine(out, 2, "}");
    emitLine(out, 1, "}");
    emitLine(out, 1, "writeUnsignedBits(buf, offBits, lenBits, BigInt.asUintN(lenBits, inValue));");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function float32ToBits(value: number): number {");
    emitLine(out, 1, "const bytes = new ArrayBuffer(4);");
    emitLine(out, 1, "const view = new DataView(bytes);");
    emitLine(out, 1, "view.setFloat32(0, value, true);");
    emitLine(out, 1, "return view.getUint32(0, true);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function bitsToFloat32(bits: number): number {");
    emitLine(out, 1, "const bytes = new ArrayBuffer(4);");
    emitLine(out, 1, "const view = new DataView(bytes);");
    emitLine(out, 1, "view.setUint32(0, bits >>> 0, true);");
    emitLine(out, 1, "return view.getFloat32(0, true);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function float64ToBits(value: number): bigint {");
    emitLine(out, 1, "const bytes = new ArrayBuffer(8);");
    emitLine(out, 1, "const view = new DataView(bytes);");
    emitLine(out, 1, "view.setFloat64(0, value, true);");
    emitLine(out, 1, "return view.getBigUint64(0, true);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function bitsToFloat64(bits: bigint): number {");
    emitLine(out, 1, "const bytes = new ArrayBuffer(8);");
    emitLine(out, 1, "const view = new DataView(bytes);");
    emitLine(out, 1, "view.setBigUint64(0, bits, true);");
    emitLine(out, 1, "return view.getFloat64(0, true);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function float16ToBits(value: number): number {");
    emitLine(out, 1, "if (Number.isNaN(value)) {");
    emitLine(out, 2, "return 0x7e00;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (value === Infinity) {");
    emitLine(out, 2, "return 0x7c00;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (value === -Infinity) {");
    emitLine(out, 2, "return 0xfc00;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "const bits = float32ToBits(value);");
    emitLine(out, 1, "const sign = (bits >>> 16) & 0x8000;");
    emitLine(out, 1, "let exp = ((bits >>> 23) & 0xff) - 127 + 15;");
    emitLine(out, 1, "let mant = bits & 0x7fffff;");
    emitLine(out, 1, "if (exp <= 0) {");
    emitLine(out, 2, "if (exp < -10) {");
    emitLine(out, 3, "return sign;");
    emitLine(out, 2, "}");
    emitLine(out, 2, "mant = (mant | 0x800000) >>> (1 - exp);");
    emitLine(out, 2, "if ((mant & 0x1000) !== 0) {");
    emitLine(out, 3, "mant += 0x2000;");
    emitLine(out, 2, "}");
    emitLine(out, 2, "return sign | (mant >>> 13);");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (exp >= 0x1f) {");
    emitLine(out, 2, "return sign | 0x7c00;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if ((mant & 0x1000) !== 0) {");
    emitLine(out, 2, "mant += 0x2000;");
    emitLine(out, 2, "if ((mant & 0x800000) !== 0) {");
    emitLine(out, 3, "mant = 0;");
    emitLine(out, 3, "exp += 1;");
    emitLine(out, 3, "if (exp >= 0x1f) {");
    emitLine(out, 4, "return sign | 0x7c00;");
    emitLine(out, 3, "}");
    emitLine(out, 2, "}");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return sign | (exp << 10) | (mant >>> 13);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "function bitsToFloat16(bits: number): number {");
    emitLine(out, 1, "const sign = (bits & 0x8000) !== 0 ? -1 : 1;");
    emitLine(out, 1, "const exp = (bits >>> 10) & 0x1f;");
    emitLine(out, 1, "const mant = bits & 0x03ff;");
    emitLine(out, 1, "if (exp === 0) {");
    emitLine(out, 2, "if (mant === 0) {");
    emitLine(out, 3, "return sign * 0;");
    emitLine(out, 2, "}");
    emitLine(out, 2, "return sign * Math.pow(2, -14) * (mant / 1024);");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (exp === 0x1f) {");
    emitLine(out, 2, "return mant === 0 ? sign * Infinity : Number.NaN;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return sign * Math.pow(2, exp - 15) * (1 + (mant / 1024));");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function writeFloat(");
    emitLine(out, 1, "buf: Uint8Array,");
    emitLine(out, 1, "offBits: number,");
    emitLine(out, 1, "lenBits: number,");
    emitLine(out, 1, "value: number");
    emitLine(out, 0, "): void {");
    emitLine(out, 1, "if (lenBits === 16) {");
    emitLine(out, 2, "writeUnsignedBits(buf, offBits, lenBits, BigInt(float16ToBits(value)));");
    emitLine(out, 2, "return;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (lenBits === 32) {");
    emitLine(out, 2, "writeUnsignedBits(buf, offBits, lenBits, BigInt(float32ToBits(value)));");
    emitLine(out, 2, "return;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (lenBits === 64) {");
    emitLine(out, 2, "writeUnsignedBits(buf, offBits, lenBits, float64ToBits(value));");
    emitLine(out, 2, "return;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "throw new Error(\"unsupported float bit length \" + lenBits);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function readFloat(buf: Uint8Array, offBits: number, lenBits: number): number {");
    emitLine(out, 1, "if (lenBits === 16) {");
    emitLine(out, 2, "return bitsToFloat16(Number(readUnsignedBits(buf, offBits, lenBits)));");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (lenBits === 32) {");
    emitLine(out, 2, "return bitsToFloat32(Number(readUnsignedBits(buf, offBits, lenBits)));");
    emitLine(out, 1, "}");
    emitLine(out, 1, "if (lenBits === 64) {");
    emitLine(out, 2, "return bitsToFloat64(readUnsignedBits(buf, offBits, lenBits));");
    emitLine(out, 1, "}");
    emitLine(out, 1, "throw new Error(\"unsupported float bit length \" + lenBits);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function readUnsignedBigInt(");
    emitLine(out, 1, "buf: Uint8Array,");
    emitLine(out, 1, "offBits: number,");
    emitLine(out, 1, "lenBits: number");
    emitLine(out, 0, "): bigint {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return 0n;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return readUnsignedBits(buf, offBits, lenBits);");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function readSignedBigInt(");
    emitLine(out, 1, "buf: Uint8Array,");
    emitLine(out, 1, "offBits: number,");
    emitLine(out, 1, "lenBits: number");
    emitLine(out, 0, "): bigint {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return 0n;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "const raw = readUnsignedBits(buf, offBits, lenBits);");
    emitLine(out, 1, "const signBit = 1n << BigInt(lenBits - 1);");
    emitLine(out, 1, "if ((raw & signBit) !== 0n) {");
    emitLine(out, 2, "return raw - (1n << BigInt(lenBits));");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return raw;");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function readUnsigned(buf: Uint8Array, offBits: number, lenBits: number): number {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return 0;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return Number(readUnsignedBigInt(buf, offBits, lenBits));");
    emitLine(out, 0, "}");
    emitLine(out, 0, "");
    emitLine(out, 0, "export function readSigned(buf: Uint8Array, offBits: number, lenBits: number): number {");
    emitLine(out, 1, "if (lenBits <= 0) {");
    emitLine(out, 2, "return 0;");
    emitLine(out, 1, "}");
    emitLine(out, 1, "return Number(readSignedBigInt(buf, offBits, lenBits));");
    emitLine(out, 0, "}");
    return out.str();
}

}  // namespace

llvm::Error emitTs(const SemanticModule& semantic,
                   mlir::ModuleOp        module,
                   const TsEmitOptions&  options,
                   DiagnosticEngine&     diagnostics,
                   EmitTraceSink*        traceSink)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }

    const auto mlirCoverageDiagnostic =
        codegen_diagnostic_text::mlirSchemaCoverageValidationFailedForEmission("TypeScript");
    LoweredFactsMap loweredFacts;
    if (!collectLoweredFactsFromMlir(semantic,
                                     module,
                                     diagnostics,
                                     "TypeScript",
                                     &loweredFacts,
                                     options.optimizeLoweredSerDes))
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "%s", mlirCoverageDiagnostic.c_str());
    }

    std::filesystem::path outRoot(options.outDir);
    const auto            selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }
    const bool emitSupport = shouldEmitSupport(options.supportGeneration, anyTypeEmitted);

    if (emitSupport)
    {
        if (options.emitPackageJson)
        {
            if (auto err =
                    writeGeneratedFile(outRoot / "package.json", renderPackageJson(options), options.writePolicy))
            {
                return err;
            }
        }
        if (auto err = writeGeneratedFile(outRoot / "dsdl_runtime.ts",
                                          renderTsRuntimeModule(options.runtimeSpecialization),
                                          options.writePolicy))
        {
            return err;
        }
    }

    EmitterContext ctx(semantic, options.typeNameVersioning);
    ctx.setTraceSink(traceSink);

    std::vector<const SemanticDefinition*> ordered;
    ordered.reserve(semantic.definitions.size());
    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        ordered.push_back(&def);
    }
    std::sort(ordered.begin(), ordered.end(), [](const auto* lhs, const auto* rhs) {
        if (lhs->info.fullName != rhs->info.fullName)
        {
            return lhs->info.fullName < rhs->info.fullName;
        }
        if (lhs->info.majorVersion != rhs->info.majorVersion)
        {
            return lhs->info.majorVersion < rhs->info.majorVersion;
        }
        return lhs->info.minorVersion < rhs->info.minorVersion;
    });

    std::vector<std::filesystem::path> generatedRelativePaths;
    generatedRelativePaths.reserve(ordered.size());

    for (const auto* def : ordered)
    {
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def->info)};
        const auto                     relPath = ctx.relativeFilePath(def->info);
        generatedRelativePaths.push_back(relPath);

        const auto fullPath = outRoot / relPath;
        auto       rendered = renderDefinitionFile(*def, ctx, loweredFacts);
        if (!rendered)
        {
            return rendered.takeError();
        }

        if (auto err = writeGeneratedFile(fullPath, *rendered, options.writePolicy, requiredTypeKeys))
        {
            return err;
        }
    }

    std::ostringstream index;
    emitLine(index, 0, generatedCommentLine("TypeScript backend index"));
    std::map<std::string, unsigned> aliasUseCount;
    for (const auto& relPath : generatedRelativePaths)
    {
        std::string modulePath = relPath.generic_string();
        if (modulePath.size() >= 3 && modulePath.ends_with(".ts"))
        {
            modulePath.resize(modulePath.size() - 3);
        }
        std::string alias    = moduleAliasFromPath(modulePath);
        unsigned&   useCount = aliasUseCount[alias];
        if (useCount > 0)
        {
            alias += "_" + std::to_string(useCount);
        }
        ++useCount;

        emitLine(index, 0, "export * as " + alias + " from \"./" + modulePath + "\";");
    }

    if (auto err = writeGeneratedFile(outRoot / "index.ts", index.str(), options.writePolicy, options.selectedTypeKeys))
    {
        return err;
    }

    return llvm::Error::success();
}

}  // namespace llvmdsdl
