// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.node.GetTransportStatistics.0.1

package node

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const GET_TRANSPORT_STATISTICS_REQUEST_FULL_NAME = "uavcan.node.GetTransportStatistics.Request"
const GET_TRANSPORT_STATISTICS_REQUEST_IS_DEPRECATED = false
const GET_TRANSPORT_STATISTICS_REQUEST_FULL_NAME_AND_VERSION = "uavcan.node.GetTransportStatistics.Request.0.1"
const GET_TRANSPORT_STATISTICS_REQUEST_EXTENT_BYTES = 0
const GET_TRANSPORT_STATISTICS_REQUEST_SERIALIZATION_BUFFER_SIZE_BYTES = 0
const GET_TRANSPORT_STATISTICS_REQUEST_ZOH_ALIAS_ELIGIBLE = false
const GET_TRANSPORT_STATISTICS_REQUEST_ZOH_ALIAS_REASON = "empty-layout"

// Returns a set of general low-level transport statistical counters.
// Servers are encouraged but not required to sample the data atomically.
type GetTransportStatistics_Request struct {
	_ uint8
}

func (obj *GetTransportStatistics_Request) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_node_GetTransportStatistics_0_1__request := func(capacityBits int64) int8 {
		if 0 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_node_GetTransportStatistics_0_1__request(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	for (offsetBits % 8) != 0 {
		_err0_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err0_ < 0 {
			return _err0_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *GetTransportStatistics_Request) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}

const GET_TRANSPORT_STATISTICS_RESPONSE_FULL_NAME = "uavcan.node.GetTransportStatistics.Response"
const GET_TRANSPORT_STATISTICS_RESPONSE_IS_DEPRECATED = false
const GET_TRANSPORT_STATISTICS_RESPONSE_FULL_NAME_AND_VERSION = "uavcan.node.GetTransportStatistics.Response.0.1"
const GET_TRANSPORT_STATISTICS_RESPONSE_EXTENT_BYTES = 192
const GET_TRANSPORT_STATISTICS_RESPONSE_SERIALIZATION_BUFFER_SIZE_BYTES = 61
const GET_TRANSPORT_STATISTICS_RESPONSE_ZOH_ALIAS_ELIGIBLE = false
const GET_TRANSPORT_STATISTICS_RESPONSE_ZOH_ALIAS_REASON = "invalid-bit-length"

// Cyphal supports up to triply modular redundant interfaces.
const GET_TRANSPORT_STATISTICS_RESPONSE_MAX_NETWORK_INTERFACES = 3

// Returns a set of general low-level transport statistical counters.
// Servers are encouraged but not required to sample the data atomically.
type GetTransportStatistics_Response struct {
	// Cyphal transfer performance statistics:
	// the number of Cyphal transfers successfully sent, successfully received, and failed.
	// The methods of error counting are implementation-defined.
	TransferStatistics IOStatistics
	// Network interface statistics, separate per interface.
	// E.g., for a doubly redundant transport, this array would contain two elements,
	// the one at the index zero would apply to the first interface, the other to the second interface.
	// The methods of counting are implementation-defined.
	NetworkInterfaceStatistics []IOStatistics
}

func (obj *GetTransportStatistics_Response) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_node_GetTransportStatistics_0_1__response := func(capacityBits int64) int8 {
		if 488 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	mlir_llvmdsdl_plan_array_length_prefix__uavcan_node_GetTransportStatistics_0_1__response__3__ser := func(value uint64) uint64 { return value & uint64(255) }
	mlir_llvmdsdl_plan_validate_array_length__uavcan_node_GetTransportStatistics_0_1__response__3 := func(value int64) int8 {
		if (value < 0) || (value > 3) {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_ARRAY_LENGTH
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_node_GetTransportStatistics_0_1__response(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	for (offsetBits % 8) != 0 {
		_err0_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err0_ < 0 {
			return _err0_, 0
		}
		offsetBits++
	}
	_sizeBytes1_ := 15
	_start2_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_end3_ := dsdlruntime.ChooseMin(_start2_+_sizeBytes1_, len(buffer))
	_rc4_, _consumed5_ := obj.TransferStatistics.Serialize(buffer[_start2_:_end3_])
	if _rc4_ < 0 {
		return _rc4_, 0
	}
	_sizeBytes1_ = _consumed5_
	offsetBits += _sizeBytes1_ * 8
	for (offsetBits % 8) != 0 {
		_err6_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err6_ < 0 {
			return _err6_, 0
		}
		offsetBits++
	}
	_lenRc7_ := mlir_llvmdsdl_plan_validate_array_length__uavcan_node_GetTransportStatistics_0_1__response__3(int64(len(obj.NetworkInterfaceStatistics)))
	if _lenRc7_ < 0 {
		return _lenRc7_, 0
	}
	_err8_ := dsdlruntime.SetUxx(buffer, offsetBits, mlir_llvmdsdl_plan_array_length_prefix__uavcan_node_GetTransportStatistics_0_1__response__3__ser(uint64(len(obj.NetworkInterfaceStatistics))), 8)
	if _err8_ < 0 {
		return _err8_, 0
	}
	offsetBits += 8
	for _index9_ := 0; _index9_ < len(obj.NetworkInterfaceStatistics); _index9_++ {
		_sizeBytes10_ := 46
		_start11_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_end12_ := dsdlruntime.ChooseMin(_start11_+_sizeBytes10_, len(buffer))
		_rc13_, _consumed14_ := obj.NetworkInterfaceStatistics[_index9_].Serialize(buffer[_start11_:_end12_])
		if _rc13_ < 0 {
			return _rc13_, 0
		}
		_sizeBytes10_ = _consumed14_
		offsetBits += _sizeBytes10_ * 8
	}
	for (offsetBits % 8) != 0 {
		_err15_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err15_ < 0 {
			return _err15_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *GetTransportStatistics_Response) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	mlir_llvmdsdl_plan_array_length_prefix__uavcan_node_GetTransportStatistics_0_1__response__3__deser := func(value uint64) uint64 { return value & uint64(255) }
	mlir_llvmdsdl_plan_validate_array_length__uavcan_node_GetTransportStatistics_0_1__response__3 := func(value int64) int8 {
		if (value < 0) || (value > 3) {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_ARRAY_LENGTH
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	offsetBits = (offsetBits + 7) & ^7
	_start16_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
	_rc17_, _consumed18_ := obj.TransferStatistics.Deserialize(buffer[_start16_:len(buffer)])
	if _rc17_ < 0 {
		return _rc17_, 0
	}
	offsetBits += _consumed18_ * 8
	offsetBits = (offsetBits + 7) & ^7
	_countRaw20_ := dsdlruntime.GetU64(buffer, offsetBits, 8)
	offsetBits += 8
	_count19_ := int(mlir_llvmdsdl_plan_array_length_prefix__uavcan_node_GetTransportStatistics_0_1__response__3__deser(_countRaw20_))
	_lenRc21_ := mlir_llvmdsdl_plan_validate_array_length__uavcan_node_GetTransportStatistics_0_1__response__3(int64(_count19_))
	if _lenRc21_ < 0 {
		return _lenRc21_, 0
	}
	obj.NetworkInterfaceStatistics = make([]IOStatistics, _count19_)
	for _index22_ := 0; _index22_ < _count19_; _index22_++ {
		_start23_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_rc24_, _consumed25_ := obj.NetworkInterfaceStatistics[_index22_].Deserialize(buffer[_start23_:len(buffer)])
		if _rc24_ < 0 {
			return _rc24_, 0
		}
		offsetBits += _consumed25_ * 8
	}
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}

type GetTransportStatistics = GetTransportStatistics_Request

const GET_TRANSPORT_STATISTICS_ZOH_ALIAS_ELIGIBLE = GET_TRANSPORT_STATISTICS_REQUEST_ZOH_ALIAS_ELIGIBLE
const GET_TRANSPORT_STATISTICS_ZOH_ALIAS_REASON = GET_TRANSPORT_STATISTICS_REQUEST_ZOH_ALIAS_REASON
