// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.node.Health.1.0

package node

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const HEALTH_FULL_NAME = "uavcan.node.Health"
const HEALTH_IS_DEPRECATED = false
const HEALTH_FULL_NAME_AND_VERSION = "uavcan.node.Health.1.0"
const HEALTH_EXTENT_BYTES = 1
const HEALTH_SERIALIZATION_BUFFER_SIZE_BYTES = 1
const HEALTH_ZOH_ALIAS_ELIGIBLE = false
const HEALTH_ZOH_ALIAS_REASON = "sub-byte-field"

// The component is functioning properly (nominal).
const HEALTH_NOMINAL = 0

// A critical parameter went out of range or the component encountered a minor failure that does not prevent
// the subsystem from performing any of its real-time functions.
const HEALTH_ADVISORY = 1

// The component encountered a major failure and is performing in a degraded mode or outside of its designed limitations.
const HEALTH_CAUTION = 2

// The component suffered a fatal malfunction and is unable to perform its intended function.
const HEALTH_WARNING = 3

// Abstract component health information. If the node performs multiple activities (provides multiple network services),
// its health status should reflect the status of the worst-performing activity (network service).
// Follows:
//
//	https://www.law.cornell.edu/cfr/text/14/23.1322
//	https://www.faa.gov/documentLibrary/media/Advisory_Circular/AC_25.1322-1.pdf section 6
type Health struct {
	Value uint8
}

func (obj *Health) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_node_Health_1_0 := func(capacityBits int64) int8 {
		if 8 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_Health_1_0__0__ser := func(value uint64) uint64 {
		if value > uint64(3) {
			return uint64(3)
		}
		return value
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_node_Health_1_0(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_err0_ := dsdlruntime.SetUxx(buffer, offsetBits, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_Health_1_0__0__ser(uint64(obj.Value)), 2)
	if _err0_ < 0 {
		return _err0_, 0
	}
	offsetBits += 2
	for (offsetBits % 8) != 0 {
		_err1_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err1_ < 0 {
			return _err1_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *Health) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_Health_1_0__0__deser := func(value uint64) uint64 { return value & uint64(3) }
	_raw2_ := uint64(dsdlruntime.GetU64(buffer, offsetBits, 2))
	obj.Value = uint8(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_node_Health_1_0__0__deser(_raw2_))
	offsetBits += 2
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}
