// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.primitive.scalar.Integer64.1.0
import * as dsdlRuntime from "../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.primitive.scalar.Integer64";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = true;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "eligible";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

export interface Integer64 {
  value: bigint;
}


export function serializeInteger64(value: Integer64): Uint8Array {
  const out = new Uint8Array(8);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_scalar_Integer64_1_0 = (capacityBits: number): boolean => 64 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer64_1_0__0__ser = (value: number | bigint): number | bigint => value;

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_scalar_Integer64_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeSigned(out, offsetBits, 64, mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer64_1_0__0__ser(value.value), true);
  offsetBits += 64;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeInteger64(bytes: Uint8Array): { value: Integer64; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer64_1_0__0__deser = (value: number | bigint): number | bigint => value;

  const value = {} as Integer64;
  let offsetBits = 0;
  const valueRaw = dsdlRuntime.readSignedBigInt(bytes, offsetBits, 64);
  value.value = BigInt(mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer64_1_0__0__deser(valueRaw));
  offsetBits += 64;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
