// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.si.unit.mass.Scalar.1.0
import * as dsdlRuntime from "../../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.si.unit.mass.Scalar";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = true;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "eligible";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

export interface Scalar {
  kilogram: number;
}


export function serializeScalar(value: Scalar): Uint8Array {
  const out = new Uint8Array(4);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_si_unit_mass_Scalar_1_0 = (capacityBits: number): boolean => 32 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_mass_Scalar_1_0__0__ser = (value: number): number => value;

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_si_unit_mass_Scalar_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeFloat(out, offsetBits, 32, mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_mass_Scalar_1_0__0__ser(value.kilogram));
  offsetBits += 32;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeScalar(bytes: Uint8Array): { value: Scalar; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_mass_Scalar_1_0__0__deser = (value: number): number => value;

  const value = {} as Scalar;
  let offsetBits = 0;
  const kilogramRaw = dsdlRuntime.readFloat(bytes, offsetBits, 32);
  value.kilogram = mlir_llvmdsdl_plan_scalar_float__uavcan_si_unit_mass_Scalar_1_0__0__deser(kilogramRaw);
  offsetBits += 32;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
