//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements C++ backend code emission from lowered DSDL modules.
///
/// The implementation translates lowered section plans into C++ encode and decode routines plus supporting type
/// wrappers.
///
/// The line-building concatenations here carry NOLINT for
/// performance-inefficient-string-concatenation. Each one spells out a line of generated
/// source, and an append sequence would cost the reader the line itself.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/BodyTranslator.h"
#include "llvmdsdl/CodeGen/EmitCommon.h"
#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/TypeStorage.h"
#include "llvmdsdl/CodeGen/emitter/Cpp.h"
#include "llvmdsdl/CodeGen/EmbeddedRuntimeSources.h"

#include <llvm/ADT/StringRef.h>
#include <llvm/Support/Error.h>
#include <cassert>
#include <cctype>  // IWYU pragma: keep -- libstdc++ reaches this transitively; libc++ needs it named.
#include <filesystem>
#include <optional>
#include <ranges>
#include <sstream>
#include <string>
#include <unordered_set>
#include <vector>
#include <cstddef>
#include <cstdint>

#include "llvmdsdl/CodeGen/CodegenDiagnosticText.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionDependencies.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/CodeGen/LoweredFactsLookup.h"
#include "llvmdsdl/CodeGen/MlirLoweredFacts.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/HelperBindingNaming.h"
#include "llvmdsdl/CodeGen/StorageTypeTokens.h"
#include "llvmdsdl/CodeGen/WireLayoutFacts.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/CodeGen/SourceWriter.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Version.h"
#include "llvmdsdl/IR/DSDLOps.h"
#include "llvmdsdl/IR/DSDLTypes.h"
#include "llvmdsdl/Transforms/PlanSteps.h"
#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/STLExtras.h>
#include <llvm/ADT/StringExtras.h>
#include <llvm/ADT/StringMap.h>
#include <llvm/Support/ErrorHandling.h>
#include <mlir/Dialect/Arith/IR/Arith.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/Attributes.h>
#include <mlir/IR/BuiltinAttributeInterfaces.h>
#include <mlir/IR/BuiltinTypeInterfaces.h>
#include <mlir/IR/BuiltinTypes.h>
#include <mlir/IR/SymbolTable.h>
#include <mlir/IR/Types.h>
#include <mlir/IR/Value.h>
#include <mlir/Support/LLVM.h>
#include <iomanip>
#include <limits>
#include <map>
#include <utility>
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl::emitter::cpp
{

namespace
{

std::string headerFileName(const DiscoveredDefinition& info)
{
    return renderDefinitionFileStem(CodegenNamingLanguage::Cpp, info.shortName, info.majorVersion, info.minorVersion) +
           ".hpp";
}

std::string headerGuard(const DiscoveredDefinition& info)
{
    return renderIncludeGuard(CodegenNamingLanguage::Cpp,
                              "LLVMDSDL_CPP_",
                              info.fullName,
                              info.majorVersion,
                              info.minorVersion,
                              "_HPP");
}

std::string valueToCppExpr(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(ConstantLiteralLanguage::Cpp, value, makeConstantTypeInfo(type));
}

std::string unsignedStorageType(const std::uint32_t bitLength)
{
    return renderUnsignedStorageToken(StorageTokenLanguage::Cpp, bitLength);
}

std::string signedStorageType(const std::uint32_t bitLength)
{
    return renderSignedStorageToken(StorageTokenLanguage::Cpp, bitLength);
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return llvm::formatv("// Generated by llvmdsdl {0} ({1}).", llvmdsdl::kVersionString, detail).str();
}

void emitAttachedDocCpp(SourceWriter& w, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        w.line(line.text.empty() ? std::string{"//"} : "// " + line.text);
    }
}

std::string cppNamespacePath(const std::vector<std::string>& components)
{
    std::string out;
    for (const auto& component : components)
    {
        if (!out.empty())
        {
            out += "::";
        }
        out += codegenProjectIdentifier(CodegenNamingLanguage::Cpp, IdentifierRole::NamespaceName, component);
    }
    return out;
}

void emitNamespaceOpen(SourceWriter& w, const std::vector<std::string>& components)
{
    if (components.empty())
    {
        return;
    }
    for (const auto& component : components)
    {
        w.line("namespace " +
               codegenProjectIdentifier(CodegenNamingLanguage::Cpp, IdentifierRole::NamespaceName, component) + " {");
    }
    w.blank();
}

void emitNamespaceClose(SourceWriter& w, const std::vector<std::string>& components)
{
    if (components.empty())
    {
        return;
    }
    w.blank();
    for (const auto& component : std::views::reverse(components))
    {
        w.line("} // namespace " +
               codegenProjectIdentifier(CodegenNamingLanguage::Cpp, IdentifierRole::NamespaceName, component));
    }
}

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule&    semantic,
                   const bool               emitDeprecationAttributes,
                   const TypeNameVersioning typeNameVersioning)
        : index_(semantic)
        , typeNameVersioning_(typeNameVersioning)
        , emitDeprecationAttributes_(emitDeprecationAttributes)
    {
    }

    /// @brief Whether generated type names carry the definition's version.
    TypeNameVersioning typeNameVersioning() const
    {
        return typeNameVersioning_;
    }

    /// @brief True when `@deprecated` definitions should carry a language-native attribute.
    bool emitDeprecationAttributes() const
    {
        return emitDeprecationAttributes_;
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

    std::string cppTypeName(const DiscoveredDefinition& info) const
    {
        return renderDefinitionTypeName(CodegenNamingLanguage::Cpp,
                                        info.namespaceComponents,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion,
                                        typeNameVersioning_);
    }

    std::string cppTypeName(const SemanticDefinition& def) const
    {
        return cppTypeName(def.info);
    }

    std::string cppTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return cppTypeName(*def);
        }

        // Nothing to count versions against, so assume the name is ambiguous and spell the version.
        // Guessing the other way would name a type that does not exist if there are two.
        return renderDefinitionTypeName(CodegenNamingLanguage::Cpp,
                                        ref.namespaceComponents,
                                        ref.shortName,
                                        ref.majorVersion,
                                        ref.minorVersion,
                                        typeNameVersioning_);
    }

    /// @brief The name @p def's struct is declared under; see renderDeclaredTypeName.
    std::string cppDeclaredTypeName(const SemanticDefinition& def) const
    {
        return renderDeclaredTypeName(cppTypeName(def), def.request.deprecated);
    }

    std::string cppQualifiedTypeName(const SemanticDefinition& def) const
    {
        return qualify(def.info.namespaceComponents, cppTypeName(def));
    }

    std::string cppQualifiedTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return cppQualifiedTypeName(*def);
        }
        return qualify(ref.namespaceComponents, cppTypeName(ref));
    }

    /// @brief The qualified declared name of the definition @p ref names, for spelling its type.
    ///
    /// The public name composes function names; the declared name is what a field or a pointer is
    /// spelled with. A reference that resolves to nothing is spelled with its public name: nothing
    /// says it is deprecated.
    std::string cppQualifiedDeclaredTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return qualify(def->info.namespaceComponents, cppDeclaredTypeName(*def));
        }
        return qualify(ref.namespaceComponents, cppTypeName(ref));
    }

    static std::string relativeHeaderPath(const SemanticDefinition& def)
    {
        std::filesystem::path p;
        for (const auto& ns : def.info.namespaceComponents)
        {
            p /= ns;
        }
        p /= headerFileName(def.info);
        return p.generic_string();
    }

private:
    static std::string qualify(const std::vector<std::string>& namespaceComponents, const std::string& name)
    {
        std::string out = "::";
        const auto  ns  = cppNamespacePath(namespaceComponents);
        if (!ns.empty())
        {
            out += ns + "::";
        }
        out += name;
        return out;
    }

    DefinitionIndex    index_;
    TypeNameVersioning typeNameVersioning_{TypeNameVersioning::Unversioned};
    bool               emitDeprecationAttributes_{false};
};

SourceWriter makeCppWriter(std::ostringstream& out)
{
    return SourceWriter{out, IndentPolicy::spaces(2)};
}

enum class CppFlavor
{
    Std,
    Pmr,
    Autosar,
};

bool isPmrFlavor(const CppFlavor flavor)
{
    return flavor == CppFlavor::Pmr;
}

bool isAutosarFlavor(const CppFlavor flavor)
{
    return flavor == CppFlavor::Autosar;
}

/// @brief The C++ spelling of the plan-body vocabulary, for one schema.
///
/// Members are named from the same scope the struct declaration names them in, built from the
/// schema's own fields and constants; a nested type's entry points are named the way its header
/// declares them. The profiles differ in how a variable-length array is sized and, under `pmr`,
/// in the memory resource a nested call is handed.
///
/// The plan works in `i64`, `i8` for its error codes, `i1` for its tests, and `f32` and `f64`.
/// `i64` is spelled unsigned, which is what the wire arithmetic and the runtime primitives take;
/// the few signed comparisons cast for the comparison alone. `i8` is spelled signed, as the
/// runtime's error codes are.
class CppSpelling final : public BodySpelling
{
public:
    CppSpelling(mlir::ModuleOp           module,
                mlir::dsdl::SchemaOp     schema,
                const CppFlavor          flavor,
                const TypeNameVersioning versioning)
        : symbols_(module)
        , flavor_(flavor)
        , versioning_(versioning)
    {
        const std::string        fullName = schema.getFullName().str();
        const auto               lastDot  = fullName.rfind('.');
        std::vector<std::string> namespaceComponents;
        if (lastDot != std::string::npos)
        {
            namespaceComponents = splitNamespace(fullName.substr(0, lastDot));
        }
        const std::string shortName    = (lastDot == std::string::npos) ? fullName : fullName.substr(lastDot + 1);
        const std::string baseTypeName = renderDefinitionTypeName(CodegenNamingLanguage::Cpp,
                                                                  namespaceComponents,
                                                                  shortName,
                                                                  static_cast<std::uint32_t>(schema.getMajor()),
                                                                  static_cast<std::uint32_t>(schema.getMinor()),
                                                                  versioning);
        if (schema.getBody().empty())
        {
            return;
        }
        for (mlir::dsdl::SerializationPlanOp plan : schema.getBody().front().getOps<mlir::dsdl::SerializationPlanOp>())
        {
            Plan              entry;
            const std::string section = plan.getSection().value_or(llvm::StringRef{}).str();
            entry.typeName =
                baseTypeName +
                (section.empty() ? std::string{} : renderSectionTypeSuffix(CodegenNamingLanguage::Cpp, section));
            entry.declaredName = renderDeclaredTypeName(entry.typeName, schema.getDeprecated());
            entry.unionTagBits = plan.getUnionTagBits().value_or(0);

            // The struct declares its fields, then the array metadata, then the constants, into
            // one scope; the same declarations in the same order name the same identifiers.
            NamingScope                   scope(CodegenNamingLanguage::Cpp);
            std::vector<mlir::dsdl::IOOp> fields;
            if (!plan.getBody().empty())
            {
                for (mlir::dsdl::IOOp io : plan.getBody().front().getOps<mlir::dsdl::IOOp>())
                {
                    if (!io.isPadding())
                    {
                        (void) scope.declare(IdentifierRole::FieldName, io.getName());
                        fields.push_back(io);
                    }
                }
            }
            for (mlir::dsdl::IOOp io : fields)
            {
                if (io.getArrayKind() != "none")
                {
                    for (const auto kind : {ArrayMetadataKind::Capacity, ArrayMetadataKind::IsVariableLength})
                    {
                        (void) scope.declare(IdentifierRole::MacroName,
                                             arrayMetadataName(CodegenNamingLanguage::Cpp, io.getName(), kind));
                    }
                }
            }
            for (mlir::dsdl::ConstantOp constant : schema.getBody().front().getOps<mlir::dsdl::ConstantOp>())
            {
                if (constant.getSection().value_or(llvm::StringRef{}) == section)
                {
                    (void) scope.declare(IdentifierRole::ConstantName, constant.getName());
                }
            }
            for (mlir::dsdl::IOOp io : fields)
            {
                entry.members[io.getName()] = Member{scope.get(IdentifierRole::FieldName, io.getName()), io};
            }
            plans_[planIdentity(schema, plan)] = std::move(entry);
        }
    }

    // Functions.

    std::vector<std::string> openFunction(SourceWriter& w, mlir::func::FuncOp fn) const override
    {
        const auto direction = planBodyDirection(fn);
        if (!direction)
        {
            return openHelper(w, fn);
        }
        const Plan&       plan      = planOf(fn.getArgument(0));
        const bool        serialize = *direction == "serialize";
        const std::string object    = serialize ? "obj" : "out_obj";
        const std::string resource =
            isPmrFlavor(flavor_) ? ", ::llvmdsdl::cpp::MemoryResource* const memory_resource" : "";
        w.line("inline std::int8_t " + plan.typeName + (serialize ? "_serialize_(const " : "_deserialize_(") +
               plan.declaredName + "* const " + object + ", " + (serialize ? "" : "const ") +
               "std::uint8_t* const buffer, std::size_t* const inout_buffer_size_bytes" + resource + ")");
        w.open("{");
        if (isPmrFlavor(flavor_))
        {
            // The plan tests its object for null before it reads it, so the resource it would be
            // read from is taken only when there is an object to take it from.
            w.line("::llvmdsdl::cpp::MemoryResource* const effective_memory_resource = (memory_resource != nullptr) ? "
                   "memory_resource : ((" +
                   object + " != nullptr) ? " + object + "->_memory_resource : nullptr);");
            w.line("(void)effective_memory_resource;");
            if (!serialize)
            {
                w.line("if ((effective_memory_resource != nullptr) && (out_obj != nullptr)) { "
                       "out_obj->set_memory_resource(effective_memory_resource); }");
            }
        }
        return {object, "buffer", "inout_buffer_size_bytes"};
    }

    void closeFunction(SourceWriter& w, mlir::func::FuncOp /*fn*/) const override
    {
        w.close("}");
        w.blank();
    }

    [[nodiscard]] std::string functionName(const llvm::StringRef callee) const override
    {
        return renderHelperBindingIdentifier(CodegenNamingLanguage::Cpp, callee);
    }

    // Statements.

    void declare(SourceWriter&         w,
                 const mlir::Type      type,
                 const llvm::StringRef name,
                 const llvm::StringRef expr) const override
    {
        const std::string spelt = typeName(type);
        if (spelt.back() == '*')
        {
            w.line(spelt + " const " + name.str() + " = " + expr.str() + ";");
        }
        else
        {
            w.line("const " + spelt + " " + name.str() + " = " + expr.str() + ";");
        }
    }

    void declareVariable(SourceWriter&         w,
                         const mlir::Type      type,
                         const llvm::StringRef name,
                         bool /*reassigned*/) const override
    {
        w.line(typeName(type) + " " + name.str() + "{};");
    }

    void assign(SourceWriter& w, const llvm::StringRef name, const llvm::StringRef expr) const override
    {
        w.line(name.str() + " = " + expr.str() + ";");
    }

    void discard(SourceWriter& w, const llvm::StringRef expr) const override
    {
        w.line("(void)" + expr.str() + ";");
    }

    void returnValue(SourceWriter& w, const llvm::StringRef expr) const override
    {
        w.line("return " + expr.str() + ";");
    }

    void openIf(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.open("if (" + condition.str() + ") {");
    }

    void openElse(SourceWriter& w) const override
    {
        w.midway("} else {");
    }

    void openLoop(SourceWriter& w) const override
    {
        w.open("while (true) {");
    }

    void breakUnless(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.open("if (!(" + condition.str() + ")) {");
        w.line("break;");
        w.close("}");
    }

    void openFor(SourceWriter&         w,
                 const llvm::StringRef variable,
                 const llvm::StringRef lower,
                 const llvm::StringRef upper,
                 const llvm::StringRef step) const override
    {
        w.open("for (std::size_t " + variable.str() + " = " + lower.str() + "; " + variable.str() + " < " +
               upper.str() + "; " + variable.str() + " += " + step.str() + ") {");
    }

    void closeBlock(SourceWriter& w) const override
    {
        w.close("}");
    }

    // Values.

    [[nodiscard]] std::string constant(const mlir::TypedAttr value) const override
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerAttr>(value))
        {
            const mlir::Type type = integer.getType();
            if (mlir::isa<mlir::IndexType>(type))
            {
                return std::to_string(integer.getValue().getZExtValue()) + "U";
            }
            const unsigned width = mlir::cast<mlir::IntegerType>(type).getWidth();
            if (width == 1)
            {
                return integer.getValue().isZero() ? "false" : "true";
            }
            const std::int64_t signedValue = integer.getValue().getSExtValue();
            if (width == 64)
            {
                if (signedValue >= 0)
                {
                    return std::to_string(integer.getValue().getZExtValue()) + "ULL";
                }
                return "static_cast<std::uint64_t>(" + signedLiteral(signedValue) + ")";
            }
            return "static_cast<" + typeName(type) + ">(" + std::to_string(signedValue) + ")";
        }
        if (const auto real = mlir::dyn_cast<mlir::FloatAttr>(value))
        {
            const bool         single = real.getType().isF32();
            std::ostringstream stream;
            stream << std::setprecision(single ? 9 : 17) << real.getValueAsDouble();
            std::string text = stream.str();
            if (text.find_first_of(".eEn") == std::string::npos)
            {
                text += ".0";
            }
            return single ? text + "F" : text;
        }
        llvm::report_fatal_error("C++ spelling: a constant of an unexpected kind");
    }

    [[nodiscard]] std::string binary(const BinaryOperator  op,
                                     const llvm::StringRef lhs,
                                     const llvm::StringRef rhs,
                                     const mlir::Type      type) const override
    {
        if (isBool(type))
        {
            switch (op)
            {
            case BinaryOperator::And:
                return "(" + lhs.str() + " && " + rhs.str() + ")";
            case BinaryOperator::Or:
                return "(" + lhs.str() + " || " + rhs.str() + ")";
            case BinaryOperator::Xor:
                return "(" + lhs.str() + " != " + rhs.str() + ")";
            default:
                llvm::report_fatal_error("C++ spelling: an arithmetic operator on a bool");
            }
        }
        const bool signedForm =
            op == BinaryOperator::DivS || op == BinaryOperator::RemS || op == BinaryOperator::ShiftRightS;
        const std::string a          = signedForm ? asSigned(lhs, type) : lhs.str();
        const std::string b          = signedForm ? asSigned(rhs, type) : rhs.str();
        const std::string expression = "(" + a + " " + operatorToken(op) + " " + b + ")";
        // A signed form answers in the signed type; a narrow type answers, after promotion, in
        // `int`. Both come back to the value's own type.
        return (signedForm || isNarrow(type)) ? "static_cast<" + typeName(type) + ">" + expression : expression;
    }

    [[nodiscard]] std::string compare(const Comparison      comparison,
                                      const llvm::StringRef lhs,
                                      const llvm::StringRef rhs,
                                      const mlir::Type      type) const override
    {
        std::string a = lhs.str();
        std::string b = rhs.str();
        switch (comparison)
        {
        case Comparison::Eq:
            return "(" + a + " == " + b + ")";
        case Comparison::Ne:
            return "(" + a + " != " + b + ")";
        case Comparison::LtS:
        case Comparison::LeS:
        case Comparison::GtS:
        case Comparison::GeS:
            if (!isSignedSpelt(type))
            {
                a = asSigned(lhs, type);
                b = asSigned(rhs, type);
            }
            break;
        case Comparison::LtU:
        case Comparison::LeU:
        case Comparison::GtU:
        case Comparison::GeU:
            if (isSignedSpelt(type))
            {
                a = asUnsigned(lhs, type);
                b = asUnsigned(rhs, type);
            }
            break;
        }
        return "(" + a + " " + comparisonToken(comparison) + " " + b + ")";
    }

    [[nodiscard]] std::string select(const llvm::StringRef condition,
                                     const llvm::StringRef ifTrue,
                                     const llvm::StringRef ifFalse,
                                     const mlir::Type      type) const override
    {
        const std::string expression = "(" + condition.str() + " ? " + ifTrue.str() + " : " + ifFalse.str() + ")";
        return isNarrow(type) ? "static_cast<" + typeName(type) + ">" + expression : expression;
    }

    [[nodiscard]] std::string convert(const Conversion      conversion,
                                      const llvm::StringRef value,
                                      const mlir::Type      from,
                                      const mlir::Type      to) const override
    {
        if (conversion == Conversion::SignExtend && !isSignedSpelt(from))
        {
            return "static_cast<" + typeName(to) + ">(" + asSigned(value, from) + ")";
        }
        return "static_cast<" + typeName(to) + ">(" + value.str() + ")";
    }

    [[nodiscard]] std::string call(const llvm::StringRef callee, const llvm::ArrayRef<std::string> args) const override
    {
        return callee.str() + "(" + llvm::join(args, ", ") + ")";
    }

    // The dialect.

    [[nodiscard]] bool spellsInline(mlir::Operation* op) const override
    {
        return mlir::isa<mlir::dsdl::MemberAddrOp, mlir::dsdl::ElementAddrOp, mlir::dsdl::BufferAtOp>(op);
    }

    [[nodiscard]] std::string isNull(mlir::dsdl::IsNullOp op, const ValueNames& names) const override
    {
        return "(" + names(op.getPointer()) + " == nullptr)";
    }

    [[nodiscard]] std::string bufferOrEmpty(mlir::dsdl::BufferOrEmptyOp op, const ValueNames& names) const override
    {
        const std::string buffer = names(op.getBuffer());
        return "((" + buffer + " != nullptr) ? " + buffer + " : reinterpret_cast<const std::uint8_t*>(\"\"))";
    }

    [[nodiscard]] std::string bufferAt(mlir::dsdl::BufferAtOp op, const ValueNames& names) const override
    {
        return "&" + names(op.getBuffer()) + "[" + asSize(names(op.getByteOffset())) + "]";
    }

    [[nodiscard]] std::string loadScalar(mlir::dsdl::LoadScalarOp op, const ValueNames& names) const override
    {
        return "static_cast<" + typeName(op.getValue().getType()) + ">(" + through(names(op.getPointer())) + ")";
    }

    void storeScalar(SourceWriter& w, mlir::dsdl::StoreScalarOp op, const ValueNames& names) const override
    {
        w.line(through(names(op.getPointer())) + " = " + asSize(names(op.getValue())) + ";");
    }

    [[nodiscard]] std::string local(SourceWriter&         w,
                                    mlir::dsdl::LocalOp   op,
                                    const llvm::StringRef name,
                                    const ValueNames&     names) const override
    {
        w.line("std::size_t " + name.str() + " = " + asSize(names(op.getInit())) + ";");
        return "&" + name.str();
    }

    [[nodiscard]] std::string loadMember(mlir::dsdl::LoadMemberOp op, const ValueNames& names) const override
    {
        return "static_cast<" + typeName(op.getValue().getType()) + ">(" +
               memberAccess(op.getObject(), op.getMember(), names) + ")";
    }

    void storeMember(SourceWriter& w, mlir::dsdl::StoreMemberOp op, const ValueNames& names) const override
    {
        const Member member = memberOf(op.getObject(), op.getMember());
        w.line(memberAccess(op.getObject(), op.getMember(), names) + " = " +
               storedValue(names(op.getValue()), scalarType(member.io)) + ";");
    }

    [[nodiscard]] std::string loadElement(mlir::dsdl::LoadElementOp op, const ValueNames& names) const override
    {
        return "static_cast<" + typeName(op.getValue().getType()) + ">(" +
               elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names) + ")";
    }

    void storeElement(SourceWriter& w, mlir::dsdl::StoreElementOp op, const ValueNames& names) const override
    {
        const Member member = memberOf(op.getObject(), op.getMember());
        w.line(elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names) + " = " +
               storedValue(names(op.getValue()), scalarType(member.io)) + ";");
    }

    [[nodiscard]] std::string memberAddr(mlir::dsdl::MemberAddrOp op, const ValueNames& names) const override
    {
        return "&" + memberAccess(op.getObject(), op.getMember(), names);
    }

    [[nodiscard]] std::string elementAddr(mlir::dsdl::ElementAddrOp op, const ValueNames& names) const override
    {
        // A variable-length bool array is a container of bools with no bytes to address; the bit
        // copies that read this address loop over its elements instead.
        if (isBoolContainer(memberOf(op.getObject(), op.getMember())))
        {
            return memberAccess(op.getObject(), op.getMember(), names);
        }
        return "&" + elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names);
    }

    [[nodiscard]] std::string arrayLength(mlir::dsdl::ArrayLengthOp op, const ValueNames& names) const override
    {
        return "static_cast<std::uint64_t>(" + memberAccess(op.getObject(), op.getMember(), names) + ".size())";
    }

    void setArrayLength(SourceWriter& w, mlir::dsdl::SetArrayLengthOp op, const ValueNames& names) const override
    {
        // A count past the capacity is what the plan's validation rejects next; the container is
        // sized within its capacity so that a malformed count never sizes it further.
        const Member      member = memberOf(op.getObject(), op.getMember());
        mlir::dsdl::IOOp  io     = member.io;
        const std::string access = memberAccess(op.getObject(), op.getMember(), names);
        const std::string count  = "dsdl_runtime_choose_min(" + asSize(names(op.getValue())) + ", " +
                                   std::to_string(io.getArrayCapacity()) + "U)";
        if (!isPmrFlavor(flavor_))
        {
            w.line(access + ".resize(" + count + ");");
            return;
        }
        const std::string temporary = fresh("sized");
        w.line("std::pmr::vector<" + containerElementType(io) + "> " + temporary +
               "(effective_memory_resource != nullptr ? effective_memory_resource : "
               "::llvmdsdl::cpp::default_memory_resource());");
        w.line(temporary + ".resize(" + count + ");");
        w.line(access + " = std::move(" + temporary + ");");
        if (io.isComposite())
        {
            const std::string index = fresh("i");
            w.open("for (std::size_t " + index + " = 0U; " + index + " < " + access + ".size(); ++" + index + ") {");
            w.line(access + "[" + index + "].set_memory_resource(effective_memory_resource);");
            w.close("}");
        }
    }

    [[nodiscard]] std::string unionTag(mlir::dsdl::UnionTagOp op, const ValueNames& names) const override
    {
        return "static_cast<std::uint64_t>(" + names(op.getObject()) + "->_tag_)";
    }

    void setUnionTag(SourceWriter& w, mlir::dsdl::SetUnionTagOp op, const ValueNames& names) const override
    {
        const Plan& plan = planOf(op.getObject());
        w.line(names(op.getObject()) + "->_tag_ = static_cast<" +
               unsignedStorageType(static_cast<std::uint32_t>(plan.unionTagBits)) + ">(" + names(op.getValue()) + ");");
    }

    [[nodiscard]] std::string writeBits(mlir::dsdl::WriteBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const auto        width     = static_cast<std::int64_t>(op.getWidth());
        const std::string value     = names(op.getValue());
        const std::string prefix    = names(op.getBuffer()) + ", " + asSize(names(op.getBufferSizeBytes())) + ", " +
                                      asSize(names(op.getBitOffset())) + ", ";
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "dsdl_runtime_set_f" + std::to_string(width) + "(" + prefix + value + ")";
        }
        if (width == 1 && !op.getIsSigned())
        {
            return "dsdl_runtime_set_bit(" + prefix + (isBool(valueType) ? value : "(" + value + " != 0ULL)") + ")";
        }
        if (op.getIsSigned())
        {
            return "dsdl_runtime_set_ixx(" + prefix + asSigned(value, valueType) + ", " + std::to_string(width) + "U)";
        }
        return "dsdl_runtime_set_uxx(" + prefix + value + ", " + std::to_string(width) + "U)";
    }

    [[nodiscard]] std::string readBits(mlir::dsdl::ReadBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const auto        width     = static_cast<std::int64_t>(op.getWidth());
        const std::string prefix    = names(op.getBuffer()) + ", " + asSize(names(op.getBufferSizeBytes())) + ", " +
                                      asSize(names(op.getBitOffset()));
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "dsdl_runtime_get_f" + std::to_string(width) + "(" + prefix + ")";
        }
        const std::string result = typeName(valueType);
        if (width == 1 && !op.getIsSigned())
        {
            return "static_cast<" + result + ">(dsdl_runtime_get_bit(" + prefix + "))";
        }
        // The runtime answers in the narrowest standard width that holds the field; a signed read
        // arrives sign-extended and keeps its value across the widening.
        const unsigned holder = holderWidthFor(width);
        return "static_cast<" + result + ">(dsdl_runtime_get_" + (op.getIsSigned() ? "i" : "u") +
               std::to_string(holder) + "(" + prefix + ", " + std::to_string(width) + "U))";
    }

    void bitWrite(SourceWriter& w, mlir::dsdl::BitWriteOp op, const ValueNames& names) const override
    {
        const std::string destination = names(op.getDestination());
        const std::string offset      = asSize(names(op.getDestinationBitOffset()));
        const std::string width       = asSize(names(op.getWidth()));
        if (const auto container = boolContainerOf(op.getSource(), names))
        {
            const std::string index = fresh("bit");
            const std::string bit   = fresh("value");
            w.open("for (std::size_t " + index + " = 0U; " + index + " < " + width + "; ++" + index + ") {");
            w.line("const std::uint8_t " + bit + " = static_cast<std::uint8_t>(" + container->first + "[" +
                   container->second + " + " + asSize(names(op.getSourceBitOffset())) + " + " + index +
                   "] ? 1U : 0U);");
            w.line("dsdl_runtime_copy_bits(" + destination + ", " + offset + " + " + index + ", 1U, &" + bit +
                   ", 0U);");
            w.close("}");
            return;
        }
        w.line("dsdl_runtime_copy_bits(" + destination + ", " + offset + ", " + width + ", " + names(op.getSource()) +
               ", " + asSize(names(op.getSourceBitOffset())) + ");");
    }

    void bitRead(SourceWriter& w, mlir::dsdl::BitReadOp op, const ValueNames& names) const override
    {
        const std::string buffer = names(op.getBuffer()) + ", " + asSize(names(op.getBufferSizeBytes()));
        const std::string offset = asSize(names(op.getBitOffset()));
        const std::string width  = asSize(names(op.getWidth()));
        if (const auto container = boolContainerOf(op.getDestination(), names))
        {
            const std::string index = fresh("bit");
            w.open("for (std::size_t " + index + " = 0U; " + index + " < " + width + "; ++" + index + ") {");
            w.line(container->first + "[" + container->second + " + " + index + "] = dsdl_runtime_get_bit(" + buffer +
                   ", " + offset + " + " + index + ");");
            w.close("}");
            return;
        }
        w.line("dsdl_runtime_get_bits(" + names(op.getDestination()) + ", " + buffer + ", " + offset + ", " + width +
               ");");
    }

    [[nodiscard]] std::string callSerdes(mlir::dsdl::CallSerdesOp op, const ValueNames& names) const override
    {
        // The callee is the nested type's own body, and the type is the schema that body belongs to.
        auto       body   = symbols_.lookup<mlir::func::FuncOp>(op.getCallee());
        const auto owner  = body ? body->getAttrOfType<mlir::StringAttr>("llvmdsdl.schema_sym") : mlir::StringAttr{};
        auto       schema = owner ? symbols_.lookup<mlir::dsdl::SchemaOp>(owner.getValue()) : mlir::dsdl::SchemaOp{};
        if (!schema)
        {
            llvm::report_fatal_error("C++ spelling: a nested call to a body of no schema in the module");
        }
        const std::string nested = qualifiedTypeName(schema.getFullName(),
                                                     static_cast<std::uint32_t>(schema.getMajor()),
                                                     static_cast<std::uint32_t>(schema.getMinor()));
        return nested + (op.getDirection() == "serialize" ? "_serialize_(" : "_deserialize_(") + names(op.getObject()) +
               ", " + names(op.getBuffer()) + ", " + names(op.getSize()) +
               (isPmrFlavor(flavor_) ? ", effective_memory_resource" : "") + ")";
    }

private:
    struct Member final
    {
        std::string      cppName;
        mlir::dsdl::IOOp io;
    };

    struct Plan final
    {
        std::string             typeName;
        std::string             declaredName;
        std::int64_t            unionTagBits{0};
        llvm::StringMap<Member> members;
    };

    static std::vector<std::string> splitNamespace(const std::string& dotted)
    {
        std::vector<std::string> out;
        std::string              component;
        for (const char c : dotted)
        {
            if (c == '.')
            {
                out.push_back(component);
                component.clear();
            }
            else
            {
                component.push_back(c);
            }
        }
        out.push_back(component);
        return out;
    }

    std::vector<std::string> openHelper(SourceWriter& w, mlir::func::FuncOp fn) const
    {
        std::vector<std::string> parameters;
        std::string              list;
        for (const auto [index, argument] : llvm::enumerate(fn.getArguments()))
        {
            parameters.push_back("p" + std::to_string(index));
            list += (list.empty() ? "" : ", ") + std::string("const ") + typeName(argument.getType()) + " " +
                    parameters.back();
        }
        w.line("inline " + typeName(fn.getResultTypes().front()) + " " + functionName(fn.getSymName()) + "(" + list +
               ")");
        w.open("{");
        return parameters;
    }

    /// @brief The plan the object a pointer names belongs to.
    const Plan& planOf(const mlir::Value object) const
    {
        const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(object.getType());
        const auto identity =
            pointer ? mlir::dyn_cast<mlir::dsdl::ObjectType>(pointer.getPointee()) : mlir::dsdl::ObjectType{};
        const auto found = identity ? plans_.find(identity.getIdentity()) : plans_.end();
        if (found == plans_.end())
        {
            llvm::report_fatal_error("C++ spelling: an object that no plan of this schema describes");
        }
        return found->second;
    }

    Member memberOf(const mlir::Value object, const llvm::StringRef member) const
    {
        const Plan& plan  = planOf(object);
        const auto  found = plan.members.find(member);
        if (found == plan.members.end())
        {
            llvm::report_fatal_error("C++ spelling: a member the schema does not declare: " + member);
        }
        return found->second;
    }

    std::string memberAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        return names(object) + "->" + memberOf(object, member).cppName;
    }

    std::string elementAccess(const mlir::Value     object,
                              const llvm::StringRef member,
                              const std::string&    index,
                              const ValueNames&     names) const
    {
        return memberAccess(object, member, names) + "[" + asSize(index) + "]";
    }

    /// @brief Whether @p member is held as a container of bools rather than as packed bits.
    ///
    /// A fixed bool array is packed into bytes, as in C; a variable-length one is the profile's
    /// container of `bool`.
    static bool isBoolContainer(const Member& member)
    {
        mlir::dsdl::IOOp io = member.io;
        return io.getScalarCategory() == "bool" && io.isVariableArray();
    }

    /// @brief The container expression and element base of a bool container @p address names.
    std::optional<std::pair<std::string, std::string>> boolContainerOf(const mlir::Value address,
                                                                       const ValueNames& names) const
    {
        auto element = address.getDefiningOp<mlir::dsdl::ElementAddrOp>();
        if (!element || !isBoolContainer(memberOf(element.getObject(), element.getMember())))
        {
            return std::nullopt;
        }
        // The address of element `index` at bit offset zero: the run starts that many elements in.
        auto              index = element.getIndex().getDefiningOp<mlir::arith::ConstantOp>();
        const std::string base =
            index ? std::to_string(mlir::cast<mlir::IntegerAttr>(index.getValue()).getValue().getZExtValue()) + "U"
                  : std::string{"0U"};
        return std::make_pair(memberAccess(element.getObject(), element.getMember(), names), base);
    }

    /// @brief The C++ type the struct declares a scalar field or element as.
    static std::string scalarType(mlir::dsdl::IOOp io)
    {
        const llvm::StringRef category = io.getScalarCategory();
        const auto            bits     = static_cast<std::uint32_t>(io.getBitLength());
        if (category == "bool")
        {
            return "bool";
        }
        if (category == "signed")
        {
            return signedStorageType(bits);
        }
        if (category == "float")
        {
            return bits == 64U ? "double" : "float";
        }
        return unsignedStorageType(bits);
    }

    std::string containerElementType(mlir::dsdl::IOOp io) const
    {
        return io.isComposite() ? nestedTypeName(io) : scalarType(io);
    }

    /// @brief The qualified name of the nested type a composite step holds.
    std::string nestedTypeName(mlir::dsdl::IOOp io) const
    {
        return qualifiedTypeName(io.getCompositeFullName().value_or(llvm::StringRef{}),
                                 static_cast<std::uint32_t>(io.getCompositeMajor().value_or(0)),
                                 static_cast<std::uint32_t>(io.getCompositeMinor().value_or(0)));
    }

    /// @brief The qualified public name of the type @p fullName names at @p major.@p minor.
    std::string qualifiedTypeName(const llvm::StringRef fullName,
                                  const std::uint32_t   major,
                                  const std::uint32_t   minor) const
    {
        const auto                     lastDot             = fullName.rfind('.');
        const std::vector<std::string> namespaceComponents = (lastDot == llvm::StringRef::npos)
                                                                 ? std::vector<std::string>{}
                                                                 : splitNamespace(fullName.substr(0, lastDot).str());
        const llvm::StringRef shortName = (lastDot == llvm::StringRef::npos) ? fullName : fullName.substr(lastDot + 1);
        std::string           qualified = "::";
        const auto            ns        = cppNamespacePath(namespaceComponents);
        if (!ns.empty())
        {
            qualified += ns + "::";
        }
        return qualified + renderDefinitionTypeName(CodegenNamingLanguage::Cpp,
                                                    namespaceComponents,
                                                    shortName,
                                                    major,
                                                    minor,
                                                    versioning_);
    }

    /// @brief @p value converted for storage in a field of @p type.
    static std::string storedValue(const std::string& value, const std::string& type)
    {
        if (type == "bool")
        {
            return "(" + value + " != 0ULL)";
        }
        return "static_cast<" + type + ">(" + value + ")";
    }

    // Types.

    static bool isBool(const mlir::Type type)
    {
        return type.isInteger(1);
    }

    /// @brief Whether values of @p type promote to `int` in an expression.
    static bool isNarrow(const mlir::Type type)
    {
        const auto integer = mlir::dyn_cast<mlir::IntegerType>(type);
        return integer && integer.getWidth() > 1 && integer.getWidth() < 32;
    }

    /// @brief Whether @p type is spelled as a signed C++ type.
    static bool isSignedSpelt(const mlir::Type type)
    {
        return type.isInteger(8);
    }

    static unsigned widthOf(const mlir::Type type)
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerType>(type))
        {
            return integer.getWidth();
        }
        return 64U;
    }

    static std::string asSigned(const llvm::StringRef value, const mlir::Type type)
    {
        return "static_cast<" + signedStorageType(widthOf(type)) + ">(" + value.str() + ")";
    }

    static std::string asUnsigned(const llvm::StringRef value, const mlir::Type type)
    {
        return "static_cast<" + unsignedStorageType(widthOf(type)) + ">(" + value.str() + ")";
    }

    static std::string asSize(const std::string& value)
    {
        return "static_cast<std::size_t>(" + value + ")";
    }

    /// @brief The object @p pointer addresses: a local is read by its name.
    static std::string through(const std::string& pointer)
    {
        return pointer.starts_with('&') ? pointer.substr(1) : "*" + pointer;
    }

    std::string typeName(const mlir::Type type) const
    {
        if (mlir::isa<mlir::IndexType>(type))
        {
            return "std::size_t";
        }
        if (type.isF32())
        {
            return "float";
        }
        if (type.isF64())
        {
            return "double";
        }
        if (const auto integer = mlir::dyn_cast<mlir::IntegerType>(type))
        {
            if (integer.getWidth() == 1)
            {
                return "bool";
            }
            return isSignedSpelt(type) ? signedStorageType(integer.getWidth())
                                       : unsignedStorageType(integer.getWidth());
        }
        if (const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(type))
        {
            const std::string qualifier = pointer.getIsConst() ? "const " : "";
            if (mlir::isa<mlir::dsdl::ByteType>(pointer.getPointee()))
            {
                return qualifier + "std::uint8_t*";
            }
            if (mlir::isa<mlir::dsdl::SizeType>(pointer.getPointee()))
            {
                return qualifier + "std::size_t*";
            }
            const auto object = mlir::cast<mlir::dsdl::ObjectType>(pointer.getPointee());
            const auto found  = plans_.find(object.getIdentity());
            if (found != plans_.end())
            {
                return qualifier + found->second.declaredName + "*";
            }
        }
        llvm::report_fatal_error("C++ spelling: a value of a type no plan body carries");
    }

    static std::string signedLiteral(const std::int64_t value)
    {
        if (value == std::numeric_limits<std::int64_t>::min())
        {
            return "(-9223372036854775807LL - 1LL)";
        }
        return std::to_string(value) + "LL";
    }

    static std::string operatorToken(const BinaryOperator op)
    {
        switch (op)
        {
        case BinaryOperator::Add:
            return "+";
        case BinaryOperator::Sub:
            return "-";
        case BinaryOperator::Mul:
            return "*";
        case BinaryOperator::DivU:
        case BinaryOperator::DivS:
            return "/";
        case BinaryOperator::RemU:
        case BinaryOperator::RemS:
            return "%";
        case BinaryOperator::And:
            return "&";
        case BinaryOperator::Or:
            return "|";
        case BinaryOperator::Xor:
            return "^";
        case BinaryOperator::ShiftLeft:
            return "<<";
        case BinaryOperator::ShiftRightU:
        case BinaryOperator::ShiftRightS:
            return ">>";
        }
        return "+";
    }

    static std::string comparisonToken(const Comparison comparison)
    {
        switch (comparison)
        {
        case Comparison::Eq:
            return "==";
        case Comparison::Ne:
            return "!=";
        case Comparison::LtS:
        case Comparison::LtU:
            return "<";
        case Comparison::LeS:
        case Comparison::LeU:
            return "<=";
        case Comparison::GtS:
        case Comparison::GtU:
            return ">";
        case Comparison::GeS:
        case Comparison::GeU:
            return ">=";
        }
        return "==";
    }

    /// @brief A name for a local the spelling introduces on its own, apart from the values.
    std::string fresh(const std::string& stem) const
    {
        return "_" + stem + std::to_string(counter_++) + "_";
    }

    mlir::SymbolTable     symbols_;
    CppFlavor             flavor_;
    TypeNameVersioning    versioning_;
    llvm::StringMap<Plan> plans_;
    mutable std::size_t   counter_{0};
};

std::string cppTypeFromFieldType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "bool";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
        return unsignedStorageType(type.bitLength);
    case SemanticScalarCategory::SignedInt:
        return signedStorageType(type.bitLength);
    case SemanticScalarCategory::Float:
        if (type.bitLength == 64U)
        {
            return "double";
        }
        return "float";
    case SemanticScalarCategory::Void:
        return "std::uint8_t";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.cppQualifiedDeclaredTypeName(*type.compositeType);
        }
        return "std::uint8_t";
    }
    return "std::uint8_t";
}

void emitArrayMetadata(SourceWriter& w, const SemanticSection& section)
{
    const NamingScope constScope = makeSectionConstantScope(CodegenNamingLanguage::Cpp, section);
    for (const auto& field : section.fields)
    {
        if (field.isPadding || field.resolvedType.arrayKind == ArrayKind::None)
        {
            continue;
        }
        const auto named = [&](const ArrayMetadataKind kind) {
            return constScope.get(IdentifierRole::MacroName,
                                  arrayMetadataName(CodegenNamingLanguage::Cpp, field.name, kind));
        };
        w.line("static constexpr std::size_t " + named(ArrayMetadataKind::Capacity) + " = " +
               std::to_string(field.resolvedType.arrayCapacity) + "U;");
        w.line("static constexpr bool " + named(ArrayMetadataKind::IsVariableLength) + " = " +
               std::string(isVariableArray(field.resolvedType.arrayKind) ? "true" : "false") + ";");
    }
}

void emitFunctionPrototypes(SourceWriter&      w,
                            const std::string& typeName,
                            const std::string& declaredName,
                            const CppFlavor    flavor)
{
    w.line("struct " + declaredName + ";");
    w.line("inline std::int8_t " + typeName + "_serialize_(const " + declaredName +
           "* obj, std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes" +
           (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* memory_resource" : "") + ");");
    w.line("inline std::int8_t " + typeName + "_deserialize_(" + declaredName +
           "* out_obj, const std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes" +
           (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* memory_resource" : "") + ");");
    w.line("inline std::int8_t " + typeName +
           "_try_deserialize_view_(const std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes, "
           "const std::uint8_t** out_view_bytes);");
    w.line("inline std::int8_t " + typeName +
           "_try_serialize_view_(const std::uint8_t* view_bytes, std::size_t view_size_bytes, "
           "std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes);");
    w.blank();
}

void emitSectionStruct(SourceWriter&                    w,
                       const std::string&               typeName,
                       const std::string&               declaredName,
                       const std::string&               fullName,
                       std::uint32_t                    majorVersion,
                       std::uint32_t                    minorVersion,
                       const SemanticSection&           section,
                       const EmitterContext&            ctx,
                       const CppFlavor                  flavor,
                       const AttachedDoc&               typeDoc,
                       const LoweredSectionFacts* const sectionFacts)
{
    const NamingScope fieldScope = makeSectionFieldScope(CodegenNamingLanguage::Cpp, section);
    emitAttachedDocCpp(w, typeDoc);
    w.open("struct " + declaredName + " {");

    std::size_t              emitted = 0;
    std::vector<std::string> variableArrayMembers;
    std::vector<std::string> compositeScalarMembers;
    std::vector<std::string> compositeFixedArrayMembers;
    std::vector<std::string> compositeVariableArrayMembers;

    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }

        const auto member   = fieldScope.get(IdentifierRole::FieldName, field.name);
        const auto baseType = cppTypeFromFieldType(field.resolvedType, ctx);
        emitAttachedDocCpp(w, field.doc);

        if (field.resolvedType.arrayKind == ArrayKind::None)
        {
            // NOLINTNEXTLINE(performance-inefficient-string-concatenation)
            w.line(baseType + " " + member + "{};");
            if (isPmrFlavor(flavor) && field.resolvedType.scalarCategory == SemanticScalarCategory::Composite)
            {
                compositeScalarMembers.push_back(member);
            }
            ++emitted;
            continue;
        }

        if (field.resolvedType.arrayKind == ArrayKind::Fixed)
        {
            if (field.resolvedType.scalarCategory == SemanticScalarCategory::Bool)
            {
                w.line("std::array<std::uint8_t, (" + std::to_string(field.resolvedType.arrayCapacity) +
                       "U + 7U) / 8U> " + member + "{};");
            }
            else
            {
                // NOLINTBEGIN(performance-inefficient-string-concatenation)
                w.line("std::array<" + baseType + ", " + std::to_string(field.resolvedType.arrayCapacity) + "U> " +
                       member + "{};");
                // NOLINTEND(performance-inefficient-string-concatenation)
            }
            if (isPmrFlavor(flavor) && field.resolvedType.scalarCategory == SemanticScalarCategory::Composite)
            {
                compositeFixedArrayMembers.push_back(member);
            }
            ++emitted;
            continue;
        }

        if (isPmrFlavor(flavor))
        {
            w.line("std::pmr::vector<" +
                   std::string(field.resolvedType.scalarCategory == SemanticScalarCategory::Bool ? "bool" : baseType) +
                   "> " + member + "{};");
            variableArrayMembers.push_back(member);
            if (field.resolvedType.scalarCategory == SemanticScalarCategory::Composite)
            {
                compositeVariableArrayMembers.push_back(member);
            }
        }
        else if (isAutosarFlavor(flavor))
        {
            w.line("::llvmdsdl::cpp::autosar::BoundedVector<" +
                   std::string(field.resolvedType.scalarCategory == SemanticScalarCategory::Bool ? "bool" : baseType) +
                   ", " + std::to_string(field.resolvedType.arrayCapacity) + "U> " + member + "{};");
        }
        else
        {
            w.line("std::vector<" +
                   std::string(field.resolvedType.scalarCategory == SemanticScalarCategory::Bool ? "bool" : baseType) +
                   "> " + member + "{};");
        }
        ++emitted;
    }

    if (section.isUnion)
    {
        // Tag storage must match the wire tag width (uint8 for <=256 options, uint16 for
        // 257..65536, etc.); a hardcoded uint8 truncates a wide tag and mis-dispatches.
        w.line(unsignedStorageType(resolveUnionTagBits(section, sectionFacts)) + " _tag_{0U};");
        ++emitted;
    }

    if (isPmrFlavor(flavor))
    {
        w.line("::llvmdsdl::cpp::MemoryResource* _memory_resource{::llvmdsdl::cpp::default_memory_resource()};");
        w.line(declaredName + "() = default;");
        w.line("explicit " + declaredName +
               "(::llvmdsdl::cpp::MemoryResource* memory_resource) { set_memory_resource(memory_resource); }");
        w.open("void set_memory_resource(::llvmdsdl::cpp::MemoryResource* memory_resource) {");
        w.line("_memory_resource = (memory_resource != nullptr) ? memory_resource : "
               "::llvmdsdl::cpp::default_memory_resource();");
        for (const auto& member : variableArrayMembers)
        {
            // NOLINTNEXTLINE(performance-inefficient-string-concatenation)
            w.line(member + " = decltype(" + member + ")(_memory_resource);");
        }
        for (const auto& member : compositeScalarMembers)
        {
            w.line(member + ".set_memory_resource(_memory_resource);");
        }
        for (const auto& member : compositeFixedArrayMembers)
        {
            const auto i =
                codegenProjectIdentifier(CodegenNamingLanguage::Cpp, IdentifierRole::LocalName, member + "_index");
            // NOLINTBEGIN(performance-inefficient-string-concatenation)
            w.open("for (std::size_t " + i + " = 0U; " + i + " < " + member + ".size(); ++" + i + ") {");
            w.line(member + "[" + i + "].set_memory_resource(_memory_resource);");
            // NOLINTEND(performance-inefficient-string-concatenation)
            w.close("}");
        }
        for (const auto& member : compositeVariableArrayMembers)
        {
            const auto i =
                codegenProjectIdentifier(CodegenNamingLanguage::Cpp, IdentifierRole::LocalName, member + "_index");
            // NOLINTBEGIN(performance-inefficient-string-concatenation)
            w.open("for (std::size_t " + i + " = 0U; " + i + " < " + member + ".size(); ++" + i + ") {");
            w.line(member + "[" + i + "].set_memory_resource(_memory_resource);");
            // NOLINTEND(performance-inefficient-string-concatenation)
            w.close("}");
        }
        w.close("}");
        ++emitted;
    }

    if (emitted == 0)
    {
        w.line("std::uint8_t _dummy_{0U};");
    }

    w.line("static constexpr const char* FULL_NAME = \"" + fullName + "\";");
    w.line("static constexpr bool IS_DEPRECATED = " + std::string(section.deprecated ? "true" : "false") + ";");
    w.line("static constexpr const char* FULL_NAME_AND_VERSION = \"" + fullName + "." + std::to_string(majorVersion) +
           "." + std::to_string(minorVersion) + "\";");
    w.line("static constexpr std::size_t EXTENT_BYTES = " + std::to_string(section.extentBits.value_or(0) / 8) + "U;");
    w.line("static constexpr std::size_t SERIALIZATION_BUFFER_SIZE_BYTES = " +
           std::to_string((section.serializationBufferSizeBits + 7) / 8) + "U;");
    const bool        zohAliasEligible = sectionFacts != nullptr && sectionFacts->zohAliasEligible;
    const std::string zohAliasReason   = (sectionFacts != nullptr && !sectionFacts->zohAliasReason.empty())
                                             ? sectionFacts->zohAliasReason
                                             : "not-proven";
    w.line(std::string("static constexpr bool ZOH_ALIAS_ELIGIBLE = ") + (zohAliasEligible ? "true;" : "false;"));
    w.line("static constexpr const char* ZOH_ALIAS_REASON = \"" + zohAliasReason + "\";");
    if (section.isUnion)
    {
        std::size_t optionCount = 0;
        for (const auto& f : section.fields)
        {
            if (!f.isPadding)
            {
                ++optionCount;
            }
        }
        w.line("static constexpr std::size_t UNION_OPTION_COUNT = " + std::to_string(optionCount) + "U;");
    }

    // Two DSDL constants can upper-case onto one name; a duplicate `static constexpr` does not

    // compile. The generated statics are claimed by the ConstantName role's policy, so a DSDL

    // constant named FULL_NAME is escaped before it reaches the scope.

    NamingScope const constScope = makeSectionConstantScope(CodegenNamingLanguage::Cpp, section);

    for (const auto& c : section.constants)
    {
        emitAttachedDocCpp(w, c.doc);
        w.line("static constexpr auto " + constScope.get(IdentifierRole::ConstantName, c.name) + " = " +
               valueToCppExpr(c.type, c.value) + ";");
    }

    emitArrayMetadata(w, section);

    w.open("LLVMDSDL_NODISCARD inline std::int8_t serialize(std::uint8_t* buffer, std::size_t* "
           "inout_buffer_size_bytes) "
           "const {");
    if (isPmrFlavor(flavor))
    {
        w.line("return " + typeName + "_serialize_(this, buffer, inout_buffer_size_bytes, _memory_resource);");
    }
    else
    {
        w.line("return " + typeName + "_serialize_(this, buffer, inout_buffer_size_bytes);");
    }
    w.close("}");

    w.open("LLVMDSDL_NODISCARD inline std::int8_t deserialize(const std::uint8_t* buffer, std::size_t* "
           "inout_buffer_size_bytes) {");
    if (isPmrFlavor(flavor))
    {
        w.line("return " + typeName + "_deserialize_(this, buffer, inout_buffer_size_bytes, _memory_resource);");
    }
    else
    {
        w.line("return " + typeName + "_deserialize_(this, buffer, inout_buffer_size_bytes);");
    }
    w.close("}");

    w.open("LLVMDSDL_NODISCARD static inline std::int8_t try_deserialize_view(const std::uint8_t* buffer, "
           "std::size_t* inout_buffer_size_bytes, const std::uint8_t** out_view_bytes) {");
    w.line("return " + typeName + "_try_deserialize_view_(buffer, inout_buffer_size_bytes, out_view_bytes);");
    w.close("}");
    w.open("LLVMDSDL_NODISCARD static inline std::int8_t try_serialize_view(const std::uint8_t* view_bytes, "
           "std::size_t view_size_bytes, std::uint8_t* buffer, std::size_t* inout_buffer_size_bytes) {");
    w.line("return " + typeName +
           "_try_serialize_view_(view_bytes, view_size_bytes, buffer, inout_buffer_size_bytes);");
    w.close("}");

    if (isPmrFlavor(flavor))
    {
        w.open("LLVMDSDL_NODISCARD inline std::int8_t serialize(std::uint8_t* buffer, std::size_t* "
               "inout_buffer_size_bytes, ::llvmdsdl::cpp::MemoryResource* memory_resource) const {");
        w.line("return " + typeName + "_serialize_(this, buffer, inout_buffer_size_bytes, memory_resource);");
        w.close("}");

        w.open("LLVMDSDL_NODISCARD inline std::int8_t deserialize(const std::uint8_t* buffer, std::size_t* "
               "inout_buffer_size_bytes, ::llvmdsdl::cpp::MemoryResource* memory_resource) {");
        w.line("return " + typeName + "_deserialize_(this, buffer, inout_buffer_size_bytes, memory_resource);");
        w.close("}");
    }

    w.close("};");
    w.blank();

    if (section.deprecated)
    {
        w.line("using " + typeName + (ctx.emitDeprecationAttributes() ? " [[deprecated]]" : "") + " = " + declaredName +
               ";");
        w.blank();
    }
}

void emitViewFunctions(SourceWriter& w, const std::string& typeName, const std::string& declaredName)
{
    w.line("inline std::int8_t " + typeName +
           "_try_deserialize_view_(const std::uint8_t* const buffer, std::size_t* const "
           "inout_buffer_size_bytes, const std::uint8_t** const out_view_bytes)");
    w.open("{");
    w.open("if ((buffer == nullptr) || (inout_buffer_size_bytes == nullptr) || (out_view_bytes == nullptr)) {");
    w.line("return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    w.close("}");
    w.line("*out_view_bytes = nullptr;");
    w.line("constexpr std::size_t required = " + declaredName + "::SERIALIZATION_BUFFER_SIZE_BYTES;");
    w.open("if (*inout_buffer_size_bytes < required) {");
    w.line("*inout_buffer_size_bytes = required;");
    w.line("return -DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL;");
    w.close("}");
    w.open("#if defined(LLVMDSDL_TARGET_ENDIANNESS_BIG)");
    w.line("*inout_buffer_size_bytes = 0U;");
    w.line("return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    w.midway("#else");
    w.open("if (" + declaredName + "::ZOH_ALIAS_ELIGIBLE) {");
    w.line("*out_view_bytes = buffer;");
    w.line("*inout_buffer_size_bytes = required;");
    w.line("return DSDL_RUNTIME_SUCCESS;");
    w.close("}");
    w.line("*inout_buffer_size_bytes = 0U;");
    w.line("return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    w.close("#endif");
    w.close("}");
    w.blank();

    w.line("inline std::int8_t " + typeName +
           "_try_serialize_view_(const std::uint8_t* const view_bytes, const std::size_t view_size_bytes, "
           "std::uint8_t* const buffer, std::size_t* const inout_buffer_size_bytes)");
    w.open("{");
    w.open("if ((view_bytes == nullptr) || (buffer == nullptr) || (inout_buffer_size_bytes == nullptr)) {");
    w.line("return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    w.close("}");
    w.line("constexpr std::size_t required = " + declaredName + "::SERIALIZATION_BUFFER_SIZE_BYTES;");
    w.open("if (view_size_bytes != required) {");
    w.line("return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    w.close("}");
    w.open("if (*inout_buffer_size_bytes < required) {");
    w.line("*inout_buffer_size_bytes = required;");
    w.line("return -DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL;");
    w.close("}");
    w.open("#if defined(LLVMDSDL_TARGET_ENDIANNESS_BIG)");
    w.line("*inout_buffer_size_bytes = 0U;");
    w.line("return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    w.midway("#else");
    w.open("if (" + declaredName + "::ZOH_ALIAS_ELIGIBLE) {");
    w.line("std::memcpy(buffer, view_bytes, required);");
    w.line("*inout_buffer_size_bytes = required;");
    w.line("return DSDL_RUNTIME_SUCCESS;");
    w.close("}");
    w.line("*inout_buffer_size_bytes = 0U;");
    w.line("return -DSDL_RUNTIME_ERROR_INVALID_ARGUMENT;");
    w.close("#endif");
    w.close("}");
    w.blank();
}

/// @brief The two bodies `lower-dsdl-bodies` built for one section.
struct SectionBodies final
{
    mlir::func::FuncOp serialize;
    mlir::func::FuncOp deserialize;
};

llvm::Error emitSection(SourceWriter&                    w,
                        const EmitterContext&            ctx,
                        const SemanticDefinition&        def,
                        const std::string&               typeName,
                        const std::string&               fullName,
                        const SemanticSection&           section,
                        const CppFlavor                  flavor,
                        const AttachedDoc&               typeDoc,
                        const LoweredSectionFacts* const sectionFacts,
                        const CppSpelling&               spelling,
                        const SectionBodies&             bodies)
{
    const auto declaredName = renderDeclaredTypeName(typeName, section.deprecated);
    emitFunctionPrototypes(w, typeName, declaredName, flavor);
    emitSectionStruct(w,
                      typeName,
                      declaredName,
                      fullName,
                      def.info.majorVersion,
                      def.info.minorVersion,
                      section,
                      ctx,
                      flavor,
                      docWithDeprecationNotice(typeDoc,
                                               section.deprecated,
                                               def.info.fullName,
                                               def.info.majorVersion,
                                               def.info.minorVersion),
                      sectionFacts);
    if (!bodies.serialize || !bodies.deserialize)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no plan bodies for %s in the lowered module",
                                       fullName.c_str());
    }
    if (auto err = translateFunction(bodies.serialize, spelling, w))
    {
        return err;
    }
    if (auto err = translateFunction(bodies.deserialize, spelling, w))
    {
        return err;
    }
    emitViewFunctions(w, typeName, declaredName);
    return llvm::Error::success();
}

llvm::Expected<std::string> loadCRuntimeHeader()
{
    if (const auto data = embedded_runtime::find("dsdl_runtime.h"))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "embedded runtime source missing: dsdl_runtime.h");
}

llvm::Expected<std::string> loadCppRuntimeHeader(const CppFlavor flavor)
{
    const std::string_view relativeRuntimeHeader =
        isAutosarFlavor(flavor) ? "cpp/autosar/dsdl_runtime.hpp" : "cpp/dsdl_runtime.hpp";
    if (const auto data = embedded_runtime::find(relativeRuntimeHeader))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "embedded runtime source missing: %s",
                                   std::string(relativeRuntimeHeader).c_str());
}

/// @brief The schema of @p def in the lowered module, by identity.
mlir::dsdl::SchemaOp schemaOf(mlir::ModuleOp module, const SemanticDefinition& def)
{
    for (mlir::dsdl::SchemaOp schema : module.getBodyRegion().front().getOps<mlir::dsdl::SchemaOp>())
    {
        if (schema.getFullName() == def.info.fullName &&
            static_cast<std::uint32_t>(schema.getMajor()) == def.info.majorVersion &&
            static_cast<std::uint32_t>(schema.getMinor()) == def.info.minorVersion)
        {
            return schema;
        }
    }
    return {};
}

llvm::Expected<std::string> renderHeader(const SemanticDefinition& def,
                                         const EmitterContext&     ctx,
                                         const CppFlavor           flavor,
                                         const LoweredFactsMap&    loweredFacts,
                                         mlir::ModuleOp            module)
{
    mlir::dsdl::SchemaOp schema = schemaOf(module, def);
    if (!schema)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no schema for %s in the lowered module",
                                       def.info.fullName.c_str());
    }
    const CppSpelling                    spelling(module, schema, flavor, ctx.typeNameVersioning());
    std::vector<mlir::func::FuncOp>      helpers;
    std::map<std::string, SectionBodies> bodies;
    for (const mlir::func::FuncOp fn : schemaFunctions(module, schema.getSymName()))
    {
        const auto direction = planBodyDirection(fn);
        if (!direction)
        {
            helpers.push_back(fn);
            continue;
        }
        const auto     sectionAttr = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        SectionBodies& entry       = bodies[sectionAttr ? sectionAttr.getValue().str() : std::string{}];
        (*direction == "serialize" ? entry.serialize : entry.deserialize) = fn;
    }

    std::ostringstream out;
    SourceWriter       w            = makeCppWriter(out);
    const auto         guard        = headerGuard(def.info);
    const auto         baseTypeName = ctx.cppTypeName(def);

    out << generatedCommentLine("C++ backend") << "\n";
    out << "// Source: " << def.info.fullName << "." << def.info.majorVersion << "." << def.info.minorVersion << "\n\n";
    out << "#ifndef " << guard << "\n";
    out << "#define " << guard << "\n\n";

    // Under the unversioned scheme this type's name carries no version, so two versions of it are
    // one identifier. Generating both is fine -- they are separate headers -- but including both is
    // not, and saying so here beats a cascade of redefinitions from inside generated code.
    if (ctx.typeNameVersioning() == TypeNameVersioning::Unversioned)
    {
        const auto [anyVersion, thisVersion] = renderVersionSentinelMacros(CodegenNamingLanguage::Cpp,
                                                                           def.info.fullName,
                                                                           def.info.majorVersion,
                                                                           def.info.minorVersion);
        out << "#if defined(" << anyVersion << ") && !defined(" << thisVersion << ")\n";
        out << "#  error \"" << def.info.fullName
            << ": two versions of one type in one translation unit, but generated type names are "
               "unversioned. Regenerate with --versioned-type-names to use both.\"\n";
        out << "#endif\n";
        out << "#define " << anyVersion << "\n";
        out << "#define " << thisVersion << "\n\n";
    }

    out << "#include <array>\n";
    out << "#include <cstddef>\n";
    out << "#include <cstdint>\n";
    out << "#include <cstring>\n";
    out << "#include <utility>\n";
    if (!isAutosarFlavor(flavor))
    {
        out << "#include <vector>\n";
    }
    if (isPmrFlavor(flavor))
    {
        out << "#include <memory_resource>\n";
    }
    out << "#include \"dsdl_runtime.hpp\"\n";

    for (const auto& depRef : collectDefinitionCompositeDependencies(def))
    {
        if (const auto* dep = ctx.find(depRef))
        {
            out << "#include \"" << EmitterContext::relativeHeaderPath(*dep) << "\"\n";
        }
    }
    w.blank();

    emitNamespaceOpen(w, def.info.namespaceComponents);

    // The helpers the plans call, ahead of the sections that call them.
    for (const mlir::func::FuncOp helper : helpers)
    {
        if (auto err = translateFunction(helper, spelling, w))
        {
            return std::move(err);
        }
    }

    if (def.isService)
    {
        // A single underscore: C++ reserves any identifier containing `__`, and these name C++
        // structs. The C emitter keeps `__` for its own service section types, where it is legal.
        const auto requestType  = baseTypeName + renderSectionTypeSuffix(CodegenNamingLanguage::Cpp, "request");
        const auto responseType = baseTypeName + renderSectionTypeSuffix(CodegenNamingLanguage::Cpp, "response");
        // The service alias and its wrappers name the request struct, never the request's public
        // name, which is a deprecated alias when the service is.
        const auto        requestDeclared = renderDeclaredTypeName(requestType, def.request.deprecated);
        const std::string aliasAttribute =
            (def.request.deprecated && ctx.emitDeprecationAttributes()) ? " [[deprecated]]" : "";

        w.line("constexpr const char* " + baseTypeName + "_FULL_NAME = \"" + def.info.fullName + "\";");
        w.line("constexpr const char* " + baseTypeName + "_FULL_NAME_AND_VERSION = \"" + def.info.fullName + "." +
               std::to_string(def.info.majorVersion) + "." + std::to_string(def.info.minorVersion) + "\";");
        w.blank();

        if (auto err = emitSection(w,
                                   ctx,
                                   def,
                                   requestType,
                                   def.info.fullName + ".Request",
                                   def.request,
                                   flavor,
                                   def.doc,
                                   lookupLoweredSectionFacts(loweredFacts, def, "request"),
                                   spelling,
                                   bodies["request"]))
        {
            return std::move(err);
        }
        if (def.response)
        {
            if (auto err = emitSection(w,
                                       ctx,
                                       def,
                                       responseType,
                                       def.info.fullName + ".Response",
                                       *def.response,
                                       flavor,
                                       def.doc,
                                       lookupLoweredSectionFacts(loweredFacts, def, "response"),
                                       spelling,
                                       bodies["response"]))
            {
                return std::move(err);
            }
        }

        w.line("using " + baseTypeName + aliasAttribute + " = " + requestDeclared + ";");
        w.line("constexpr std::size_t " + baseTypeName + "_EXTENT_BYTES = " + requestDeclared + "::EXTENT_BYTES;");
        w.line("constexpr std::size_t " + baseTypeName + "_SERIALIZATION_BUFFER_SIZE_BYTES = " + requestDeclared +
               "::SERIALIZATION_BUFFER_SIZE_BYTES;");
        w.line("constexpr bool " + baseTypeName + "_ZOH_ALIAS_ELIGIBLE = " + requestDeclared + "::ZOH_ALIAS_ELIGIBLE;");
        w.line("constexpr const char* " + baseTypeName + "_ZOH_ALIAS_REASON = " + requestDeclared +
               "::ZOH_ALIAS_REASON;");
        w.blank();

        w.line("inline std::int8_t " + baseTypeName + "_serialize_(const " + requestDeclared +
               "* const obj, std::uint8_t* const buffer, std::size_t* const "
               "inout_buffer_size_bytes" +
               (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* const memory_resource" : "") + ")");
        w.open("{");
        w.line("return " + requestType + "_serialize_(obj, buffer, inout_buffer_size_bytes" +
               (isPmrFlavor(flavor) ? ", memory_resource" : "") + ");");
        w.close("}");
        w.blank();

        w.line("inline std::int8_t " + baseTypeName + "_deserialize_(" + requestDeclared +
               "* const out_obj, const std::uint8_t* buffer, std::size_t* const "
               "inout_buffer_size_bytes" +
               (isPmrFlavor(flavor) ? ", ::llvmdsdl::cpp::MemoryResource* const memory_resource" : "") + ")");
        w.open("{");
        w.line("return " + requestType + "_deserialize_(out_obj, buffer, inout_buffer_size_bytes" +
               (isPmrFlavor(flavor) ? ", memory_resource" : "") + ");");
        w.close("}");
        w.blank();

        w.line("inline std::int8_t " + baseTypeName +
               "_try_deserialize_view_(const std::uint8_t* const buffer, std::size_t* const "
               "inout_buffer_size_bytes, const std::uint8_t** const out_view_bytes)");
        w.open("{");
        w.line("return " + requestType + "_try_deserialize_view_(buffer, inout_buffer_size_bytes, out_view_bytes);");
        w.close("}");
        w.blank();

        w.line("inline std::int8_t " + baseTypeName +
               "_try_serialize_view_(const std::uint8_t* const view_bytes, const std::size_t view_size_bytes, "
               "std::uint8_t* const buffer, std::size_t* const inout_buffer_size_bytes)");
        w.open("{");
        w.line("return " + requestType +
               "_try_serialize_view_(view_bytes, view_size_bytes, buffer, inout_buffer_size_bytes);");
        w.close("}");
    }
    else
    {
        if (auto err = emitSection(w,
                                   ctx,
                                   def,
                                   baseTypeName,
                                   def.info.fullName,
                                   def.request,
                                   flavor,
                                   def.doc,
                                   lookupLoweredSectionFacts(loweredFacts, def, ""),
                                   spelling,
                                   bodies[""]))
        {
            return std::move(err);
        }
    }

    emitNamespaceClose(w, def.info.namespaceComponents);
    out << "\n#endif /* " << guard << " */\n";
    return out.str();
}

llvm::Error emitProfile(const SemanticModule&                  semantic,
                        mlir::ModuleOp                         module,
                        const std::filesystem::path&           outRoot,
                        const CppFlavor                        flavor,
                        const LoweredFactsMap&                 loweredFacts,
                        const Options&                         options,
                        const std::unordered_set<std::string>& selectedTypeKeys)
{
    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }

    if (shouldEmitSupport(options.supportGeneration, anyTypeEmitted))
    {
        auto cRuntime = loadCRuntimeHeader();
        if (!cRuntime)
        {
            return cRuntime.takeError();
        }
        if (auto err =
                writeGeneratedFile(outRoot / "dsdl_runtime.h",
                                   generatedCommentLine("C runtime scaffold for C++ backend") + "\n\n" + *cRuntime,
                                   options.writePolicy))
        {
            return err;
        }

        auto cppRuntime = loadCppRuntimeHeader(flavor);
        if (!cppRuntime)
        {
            return cppRuntime.takeError();
        }
        if (auto err = writeGeneratedFile(outRoot / "dsdl_runtime.hpp",
                                          generatedCommentLine("C++ runtime scaffold") + "\n\n" + *cppRuntime,
                                          options.writePolicy))
        {
            return err;
        }
    }

    const EmitterContext ctx(semantic, options.emitDeprecationAttributes, options.typeNameVersioning);
    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def.info)};

        std::filesystem::path dir = outRoot;
        for (const auto& ns : def.info.namespaceComponents)
        {
            dir /= ns;
        }
        auto header = renderHeader(def, ctx, flavor, loweredFacts, module);
        if (!header)
        {
            return header.takeError();
        }
        if (auto err =
                writeGeneratedFile(dir / headerFileName(def.info), *header, options.writePolicy, requiredTypeKeys))
        {
            return err;
        }
    }

    return llvm::Error::success();
}

}  // namespace

llvm::Error emit(const SemanticModule& semantic,
                 mlir::ModuleOp        module,
                 const Options&        options,
                 DiagnosticEngine&     diagnostics)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }
    const auto mlirCoverageDiagnostic = codegen_diagnostic_text::mlirSchemaCoverageValidationFailedForEmission("C++");
    LoweredFactsMap loweredFacts;
    if (!collectLoweredFactsFromMlir(semantic, module, diagnostics, "C++", &loweredFacts))
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "%s", mlirCoverageDiagnostic.c_str());
    }

    std::filesystem::path const outRoot(options.outDir);
    const auto                  selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    if (options.profile == Profile::Std)
    {
        return emitProfile(semantic, module, outRoot, CppFlavor::Std, loweredFacts, options, selectedTypeKeys);
    }
    if (options.profile == Profile::Pmr)
    {
        return emitProfile(semantic, module, outRoot, CppFlavor::Pmr, loweredFacts, options, selectedTypeKeys);
    }
    if (options.profile == Profile::Autosar)
    {
        return emitProfile(semantic, module, outRoot, CppFlavor::Autosar, loweredFacts, options, selectedTypeKeys);
    }

    if (auto err =
            emitProfile(semantic, module, outRoot / "std", CppFlavor::Std, loweredFacts, options, selectedTypeKeys))
    {
        return err;
    }
    return emitProfile(semantic, module, outRoot / "pmr", CppFlavor::Pmr, loweredFacts, options, selectedTypeKeys);
}

}  // namespace llvmdsdl::emitter::cpp
