//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements Python backend code emission from lowered DSDL modules.
///
/// This file emits Python dataclass models and the methods a consumer calls; the serialise and
/// deserialise bodies those wrap are translations of the plan bodies through `PythonSpelling`.
///
/// The line-building concatenations here carry NOLINT for
/// performance-inefficient-string-concatenation. Each one spells out a line of generated
/// source, and an append sequence would cost the reader the line itself.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/BodyTranslator.h"
#include "llvmdsdl/CodeGen/EmitCommon.h"
#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/EmbeddedRuntimeSources.h"
#include "llvmdsdl/CodeGen/emitter/Python.h"

#include <algorithm>
#include <cassert>
#include <llvm/ADT/StringRef.h>
#include <cctype>  // IWYU pragma: keep -- libstdc++ reaches this transitively; libc++ needs it named.
#include <filesystem>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <vector>
#include <cstdint>
#include <system_error>
#include <utility>

#include "llvmdsdl/CodeGen/MlirLoweredFacts.h"
#include "llvmdsdl/CodeGen/CodegenDiagnosticText.h"
#include "llvmdsdl/CodeGen/CompositeImportGraph.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/CodeGen/DefinitionPathProjection.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/HelperBindingNaming.h"
#include "llvmdsdl/CodeGen/LoweredFactsLookup.h"
#include "llvmdsdl/CodeGen/SourceWriter.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Version.h"
#include "llvmdsdl/IR/DSDLOps.h"
#include "llvmdsdl/IR/DSDLTypes.h"
#include "llvmdsdl/Transforms/PlanSteps.h"
#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/STLExtras.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringExtras.h>
#include <llvm/ADT/StringMap.h>
#include <llvm/Support/ErrorHandling.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/IR/BuiltinAttributeInterfaces.h>
#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/BuiltinTypeInterfaces.h>
#include <mlir/IR/BuiltinTypes.h>
#include <mlir/IR/Types.h>
#include <mlir/IR/Value.h>
#include <mlir/Support/LLVM.h>
#include <cmath>
#include <functional>
#include <iomanip>
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl::emitter::python
{

namespace
{

std::string pyConstValue(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(ConstantLiteralLanguage::Python, value, makeConstantTypeInfo(type));
}

/// @brief Collision-free attribute names for one section's fields.
///
/// snake_casing is many-to-one, so `fooBar` and `foo_bar` both fold to `foo_bar`; without this the
/// dataclass would silently declare one attribute for two DSDL fields and the (de)serialiser would
/// read/write the wrong one with no error. Built from `section.fields` order so every site agrees.
NamingScope makePyFieldIdents(const SemanticSection& section)
{
    std::vector<std::string> names;
    for (const auto& field : section.fields)
    {
        if (!field.isPadding)
        {
            names.push_back(field.name);
        }
    }
    // The generated methods a field attribute must not shadow are claimed by the FieldName role's
    // policy, so the scope only has to keep the fields apart from each other.
    return makeSectionFieldScope(CodegenNamingLanguage::Python, section);
}

SourceWriter makePyWriter(std::ostringstream& out)
{
    return SourceWriter{out, IndentPolicy::spaces(4)};
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return "# Generated by llvmdsdl " + std::string(llvmdsdl::kVersionString) + " (" + detail.str() + ").";
}

void emitAttachedDocPy(SourceWriter& w, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        w.line(line.text.empty() ? std::string{"#"} : "# " + line.text);
    }
}

std::string joinDotted(const std::vector<std::string>& parts)
{
    std::string out;
    for (const auto& p : parts)
    {
        if (!out.empty())
        {
            out += ".";
        }
        out += p;
    }
    return out;
}

std::vector<std::string> splitPackageName(const std::string& packageName)
{
    std::vector<std::string> out;
    std::string              current;
    for (char const c : packageName)
    {
        if (c == '.')
        {
            if (!current.empty())
            {
                out.push_back(
                    codegenProjectIdentifier(CodegenNamingLanguage::Python, IdentifierRole::NamespaceName, current));
                current.clear();
            }
            continue;
        }
        current.push_back(c);
    }
    if (!current.empty())
    {
        out.push_back(codegenProjectIdentifier(CodegenNamingLanguage::Python, IdentifierRole::NamespaceName, current));
    }
    if (out.empty())
    {
        out.emplace_back("dsdl_gen");
    }
    return out;
}

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule&    semantic,
                   std::vector<std::string> packageComponents,
                   const TypeNameVersioning typeNameVersioning)
        : packageComponents_(std::move(packageComponents))
        , index_(semantic)
        , typeNameVersioning_(typeNameVersioning)
    {
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

    static std::string namespacePath(const DiscoveredDefinition& info)
    {
        return renderNamespaceRelativePath(CodegenNamingLanguage::Python, info.namespaceComponents).generic_string();
    }

    std::string typeName(const DiscoveredDefinition& info) const
    {
        return renderDefinitionTypeName(CodegenNamingLanguage::Python,
                                        info.namespaceComponents,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion,
                                        typeNameVersioning_);
    }

    std::string typeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return typeName(def->info);
        }

        DiscoveredDefinition tmp;
        tmp.shortName    = ref.shortName;
        tmp.majorVersion = ref.majorVersion;
        tmp.minorVersion = ref.minorVersion;
        return typeName(tmp);
    }

    static std::string fileStem(const DiscoveredDefinition& info)
    {
        return renderVersionedFileStem(CodegenNamingLanguage::Python,
                                       info.shortName,
                                       info.majorVersion,
                                       info.minorVersion);
    }

    static std::filesystem::path relativeFilePath(const DiscoveredDefinition& info)
    {
        return renderRelativeTypeFilePath(CodegenNamingLanguage::Python, info, "py");
    }

    std::filesystem::path relativeFilePath(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return relativeFilePath(def->info);
        }

        return renderRelativeTypeFilePath(CodegenNamingLanguage::Python, ref, "py");
    }

    std::string packageName() const
    {
        return joinDotted(packageComponents_);
    }

    std::filesystem::path packageRootPath() const
    {
        std::filesystem::path out;
        for (const auto& c : packageComponents_)
        {
            out /= c;
        }
        return out;
    }

    std::string modulePath(const DiscoveredDefinition& info) const
    {
        const auto rel = relativeFilePath(info);
        return modulePathFromRelPath(rel);
    }

    std::string modulePath(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return modulePath(def->info);
        }
        return modulePathFromRelPath(relativeFilePath(ref));
    }

private:
    std::string modulePathFromRelPath(const std::filesystem::path& relPath) const
    {
        std::vector<std::string> parts = packageComponents_;
        for (const auto& comp : relPath)
        {
            auto part = comp.string();
            if (part.empty() || part == ".")
            {
                continue;
            }
            if (part.ends_with(".py"))
            {
                part.resize(part.size() - 3);
            }
            parts.push_back(part);
        }
        return joinDotted(parts);
    }

    std::vector<std::string> packageComponents_;
    DefinitionIndex          index_;
    TypeNameVersioning       typeNameVersioning_{TypeNameVersioning::Unversioned};
};

std::string pyFieldBaseType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "bool";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        return "int";
    case SemanticScalarCategory::Float:
        return "float";
    case SemanticScalarCategory::Void:
        return "int";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.typeName(*type.compositeType);
        }
        return "object";
    }
    return "object";
}

std::string pyFieldType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    auto base = pyFieldBaseType(type, ctx);
    if (type.arrayKind == ArrayKind::None)
    {
        return base;
    }
    return "list[" + base + "]";
}

std::string pyElementDefaultExpr(const SemanticFieldType& type, const EmitterContext& ctx);

std::string pyDefaultExpr(const SemanticFieldType& type, const EmitterContext& ctx)
{
    if (type.arrayKind == ArrayKind::Fixed)
    {
        const std::string count = std::to_string(type.arrayCapacity);
        const std::string list  = type.scalarCategory == SemanticScalarCategory::Composite
                                      ? "[" + pyElementDefaultExpr(type, ctx) + " for _ in range(" + count + ")]"
                                      : "[" + pyElementDefaultExpr(type, ctx) + "] * " + count;
        return "field(default_factory=lambda: " + list + ")";
    }
    if (type.arrayKind != ArrayKind::None)
    {
        return "field(default_factory=list)";
    }
    return pyElementDefaultExpr(type, ctx);
}

/// @brief The default of one element of @p type, or of a scalar or object.
std::string pyElementDefaultExpr(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "False";
    case SemanticScalarCategory::Float:
        return "0.0";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.typeName(*type.compositeType) + "()";
        }
        return "None";
    case SemanticScalarCategory::Void:
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        return "0";
    }
    return "None";
}

void emitSectionConstants(SourceWriter& w, const std::string& prefix, const SemanticSection& section)
{
    std::vector<std::string> constNames;
    constNames.reserve(section.constants.size());
    for (const auto& constant : section.constants)
    {
        constNames.push_back(constant.name);
    }
    NamingScope const constScope = makeSectionConstantScope(CodegenNamingLanguage::Python, section);
    const auto        prefixupper =
        codegenProjectIdentifier(CodegenNamingLanguage::Python, IdentifierRole::ConstantName, prefix);
    for (const auto& constant : section.constants)
    {
        emitAttachedDocPy(w, constant.doc);
        const auto constName = prefixupper + "_" + constScope.get(IdentifierRole::ConstantName, constant.name);
        w.line(constName + " = " + pyConstValue(constant.type, constant.value));
    }
}

void emitClassMethods(SourceWriter& w, const std::string& typeName, const SemanticSection& section)
{
    // A value serialises into a buffer of the type's largest size; a deserialisation fills a
    // default-constructed object. Each raises on the code a body answers.
    w.open("def serialize(self) -> bytes:");
    w.line("buffer = bytearray(" + std::to_string((section.serializationBufferSizeBits + 7) / 8) + ")");
    w.line("result = self._serialize_into(memoryview(buffer))");
    w.open("if result < 0:");
    w.line("raise ValueError(error_message(result))");
    w.dedent();
    w.line("return bytes(buffer[:result])");
    w.dedent();
    w.blank();

    w.line("@classmethod");
    w.open("def deserialize(cls, data: bytes | bytearray | memoryview) -> \"" + typeName + "\":");
    w.line("value = cls()");
    w.line("result = value._deserialize_from(memoryview(data))");
    w.open("if result < 0:");
    w.line("raise ValueError(error_message(result))");
    w.dedent();
    w.line("return value");
    w.dedent();
}

void emitStructSectionType(SourceWriter&          w,
                           const std::string&     typeName,
                           const SemanticSection& section,
                           const AttachedDoc&     typeDoc,
                           const EmitterContext&  ctx,
                           const std::string&     fullName,
                           const std::uint32_t    majorVersion,
                           const std::uint32_t    minorVersion)
{
    emitAttachedDocPy(w, docWithDeprecationNotice(typeDoc, section.deprecated, fullName, majorVersion, minorVersion));
    w.line("@dataclass(slots=True)");
    w.open("class " + typeName + ":");

    bool              emittedField = false;
    const NamingScope fieldIdents  = makePyFieldIdents(section);
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        emittedField = true;
        emitAttachedDocPy(w, field.doc);
        const auto        fieldName   = fieldIdents.get(IdentifierRole::FieldName, field.name);
        const std::string defaultExpr = pyDefaultExpr(field.resolvedType, ctx);
        const bool        factory     = field.resolvedType.arrayKind != ArrayKind::None ||
                                        field.resolvedType.scalarCategory == SemanticScalarCategory::Composite;
        w.line(fieldName + ": " + pyFieldType(field.resolvedType, ctx) + " = " +
               (factory && !defaultExpr.starts_with("field(") ? "field(default_factory=lambda: " + defaultExpr + ")"
                                                              : defaultExpr));
    }
    if (emittedField)
    {
        w.blank();
    }
    emitClassMethods(w, typeName, section);
}

void emitUnionSectionType(SourceWriter&          w,
                          const std::string&     typeName,
                          const SemanticSection& section,
                          const AttachedDoc&     typeDoc,
                          const EmitterContext&  ctx,
                          const std::string&     fullName,
                          const std::uint32_t    majorVersion,
                          const std::uint32_t    minorVersion)
{
    emitAttachedDocPy(w, docWithDeprecationNotice(typeDoc, section.deprecated, fullName, majorVersion, minorVersion));
    w.line("@dataclass(slots=True)");
    w.open("class " + typeName + ":");
    w.line("_tag: int = 0");

    const NamingScope fieldIdents = makePyFieldIdents(section);
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        emitAttachedDocPy(w, field.doc);
        const auto fieldName = fieldIdents.get(IdentifierRole::FieldName, field.name);
        w.line(fieldName + ": " + pyFieldType(field.resolvedType, ctx) + " | None = None");
    }

    w.blank();
    emitClassMethods(w, typeName, section);
}

void emitSectionType(SourceWriter&          w,
                     const std::string&     typeName,
                     const SemanticSection& section,
                     const AttachedDoc&     typeDoc,
                     const EmitterContext&  ctx,
                     const std::string&     fullName,
                     const std::uint32_t    majorVersion,
                     const std::uint32_t    minorVersion)
{
    if (section.isUnion)
    {
        emitUnionSectionType(w, typeName, section, typeDoc, ctx, fullName, majorVersion, minorVersion);
    }
    else
    {
        emitStructSectionType(w, typeName, section, typeDoc, ctx, fullName, majorVersion, minorVersion);
    }
}

/// @brief The Python spelling of the plan-body vocabulary, for one schema.
///
/// Every integer of the plan is a Python `int`, which holds the value it stands for: a
/// constant is spelled as that value, and a bigint's bitwise operators read a negative value as
/// its two's complement. A buffer is a `memoryview`, and a pointer into it is a slice of the
/// view. A body is a method of the dataclass that answers the size it used, or the error code,
/// which is negative; the `serialize` and `deserialize` methods a consumer calls wrap it. A
/// deserialise body is handed a default-constructed object, whose fixed arrays and nested
/// objects exist; a union's option is created when the plan sets the tag. Python has no
/// empty block, so a block that spelled no statement closes with `pass`.
class PythonSpelling final : public BodySpelling
{
public:
    /// @brief The name this file gives the type @p fullName names at @p major.@p minor.
    using TypeNameResolver =
        std::function<std::string(llvm::StringRef fullName, std::uint32_t major, std::uint32_t minor)>;

    PythonSpelling(mlir::dsdl::SchemaOp schema, TypeNameResolver typeNameOf)
        : typeNameOf_(std::move(typeNameOf))
    {
        if (schema.getBody().empty())
        {
            return;
        }
        for (mlir::dsdl::SerializationPlanOp plan : schema.getBody().front().getOps<mlir::dsdl::SerializationPlanOp>())
        {
            Plan                          entry;
            NamingScope                   scope(CodegenNamingLanguage::Python);
            std::vector<mlir::dsdl::IOOp> fields;
            if (!plan.getBody().empty())
            {
                for (mlir::dsdl::IOOp io : plan.getBody().front().getOps<mlir::dsdl::IOOp>())
                {
                    if (!io.isPadding())
                    {
                        (void) scope.declare(IdentifierRole::FieldName, io.getName());
                        fields.push_back(io);
                    }
                }
            }
            for (mlir::dsdl::IOOp io : fields)
            {
                entry.members[io.getName()] = Member{scope.get(IdentifierRole::FieldName, io.getName()), io};
                entry.order.push_back(io.getName().str());
            }
            plans_[planIdentity(schema, plan)] = std::move(entry);
        }
    }

    /// @brief The method that serialises the object into a buffer.
    static std::string serializeInto()
    {
        return "_serialize_into";
    }

    /// @brief The method that deserialises the object from a buffer.
    static std::string deserializeFrom()
    {
        return "_deserialize_from";
    }

    // Functions.

    std::vector<std::string> openFunction(SourceWriter& w, mlir::func::FuncOp fn) const override
    {
        const auto direction = planBodyDirection(fn);
        inBody_              = direction.has_value();
        if (!direction)
        {
            std::vector<std::string> parameters;
            std::string              list;
            for (const auto [index, argument] : llvm::enumerate(fn.getArguments()))
            {
                parameters.push_back("p" + std::to_string(index));
                list += (list.empty() ? "" : ", ") + parameters.back() + ": " + typeName(argument.getType());
            }
            open(w,
                 "def " + functionName(fn.getSymName()) + "(" + list + ") -> " + typeName(fn.getResultTypes().front()) +
                     ":");
            return parameters;
        }
        open(w,
             "def " + (*direction == "serialize" ? serializeInto() : deserializeFrom()) +
                 "(self, buffer: memoryview) -> int:");
        // The size a plan is handed by pointer, read at entry and answered at the end.
        line(w, "inout_buffer_size_bytes = len(buffer)");
        return {"self", "buffer", "inout_buffer_size_bytes"};
    }

    void closeFunction(SourceWriter& w, mlir::func::FuncOp /*fn*/) const override
    {
        closeBlock(w);
    }

    [[nodiscard]] std::string functionName(const llvm::StringRef callee) const override
    {
        return renderHelperBindingIdentifier(CodegenNamingLanguage::Python, callee);
    }

    // Statements.

    void declare(SourceWriter& w,
                 const mlir::Type /*type*/,
                 const llvm::StringRef name,
                 const llvm::StringRef expr) const override
    {
        line(w, name.str() + " = " + expr.str());
    }

    void declareVariable(SourceWriter& /*w*/,
                         const mlir::Type /*type*/,
                         const llvm::StringRef /*name*/,
                         const bool /*reassigned*/) const override
    {
        // A Python variable exists from its first assignment, which every path makes.
    }

    void assign(SourceWriter& w, const llvm::StringRef name, const llvm::StringRef expr) const override
    {
        line(w, name.str() + " = " + expr.str());
    }

    void discard(SourceWriter& w, const llvm::StringRef expr) const override
    {
        line(w, expr.str());
    }

    void returnValue(SourceWriter& w, const llvm::StringRef expr) const override
    {
        // A body answers the runtime's error code; its Python signature answers the size used
        // on success and the code, which is negative, on failure.
        if (inBody_)
        {
            open(w, "if " + expr.str() + " == 0:");
            line(w, "return inout_buffer_size_bytes");
            closeBlock(w);
        }
        line(w, "return " + expr.str());
    }

    void openIf(SourceWriter& w, const llvm::StringRef condition) const override
    {
        open(w, "if " + condition.str() + ":");
    }

    void openElse(SourceWriter& w) const override
    {
        if (blockEmpty_)
        {
            w.line("pass");
        }
        w.midway("else:");
        blockEmpty_ = true;
    }

    void openLoop(SourceWriter& w) const override
    {
        open(w, "while True:");
    }

    void breakUnless(SourceWriter& w, const llvm::StringRef condition) const override
    {
        open(w, "if not (" + condition.str() + "):");
        line(w, "break");
        closeBlock(w);
    }

    void openFor(SourceWriter&         w,
                 const llvm::StringRef variable,
                 const llvm::StringRef lower,
                 const llvm::StringRef upper,
                 const llvm::StringRef step) const override
    {
        open(w, "for " + variable.str() + " in range(" + lower.str() + ", " + upper.str() + ", " + step.str() + "):");
    }

    void closeBlock(SourceWriter& w) const override
    {
        if (blockEmpty_)
        {
            w.line("pass");
        }
        w.dedent();
        blockEmpty_ = false;
    }

    // Values.

    [[nodiscard]] std::string constant(const mlir::TypedAttr value) const override
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerAttr>(value))
        {
            const mlir::Type type = integer.getType();
            if (mlir::isa<mlir::IndexType>(type))
            {
                return std::to_string(integer.getValue().getZExtValue());
            }
            if (isBool(type))
            {
                return integer.getValue().isZero() ? "False" : "True";
            }
            // The value the two's complement stands for: an int holds it as such, and the
            // bitwise operators read a negative int as its two's complement.
            return std::to_string(integer.getValue().getSExtValue());
        }
        if (const auto real = mlir::dyn_cast<mlir::FloatAttr>(value))
        {
            const double number = real.getValueAsDouble();
            if (std::isnan(number))
            {
                return "float(\"nan\")";
            }
            if (std::isinf(number))
            {
                return number < 0 ? "-float(\"inf\")" : "float(\"inf\")";
            }
            std::ostringstream stream;
            stream << std::setprecision(17) << number;
            std::string text = stream.str();
            if (text.find_first_of(".e") == std::string::npos)
            {
                text += ".0";
            }
            return text;
        }
        llvm::report_fatal_error("Python spelling: a constant of an unexpected kind");
    }

    [[nodiscard]] std::string binary(const BinaryOperator  op,
                                     const llvm::StringRef lhs,
                                     const llvm::StringRef rhs,
                                     const mlir::Type      type) const override
    {
        if (isBool(type))
        {
            switch (op)
            {
            case BinaryOperator::And:
                return lhs.str() + " and " + rhs.str();
            case BinaryOperator::Or:
                return lhs.str() + " or " + rhs.str();
            case BinaryOperator::Xor:
                return lhs.str() + " != " + rhs.str();
            default:
                llvm::report_fatal_error("Python spelling: an arithmetic operator on a bool");
            }
        }
        return lhs.str() + " " + operatorToken(op) + " " + rhs.str();
    }

    [[nodiscard]] std::string compare(const Comparison      comparison,
                                      const llvm::StringRef lhs,
                                      const llvm::StringRef rhs,
                                      const mlir::Type      type) const override
    {
        std::string a = lhs.str();
        std::string b = rhs.str();
        switch (comparison)
        {
        case Comparison::Eq:
            return a + " == " + b;
        case Comparison::Ne:
            return a + " != " + b;
        case Comparison::LtU:
        case Comparison::LeU:
        case Comparison::GtU:
        case Comparison::GeU:
            // An int is the value its bits stand for; an unsigned comparison against a negative
            // literal reads both as the unsigned 64-bit values the plan compares.
            if (type.isInteger(64) && (lhs.starts_with("-") || rhs.starts_with("-")))
            {
                a = "(" + a + " & 0xFFFFFFFFFFFFFFFF)";
                b = "(" + b + " & 0xFFFFFFFFFFFFFFFF)";
            }
            break;
        default:
            break;
        }
        return a + " " + comparisonToken(comparison) + " " + b;
    }

    [[nodiscard]] std::string select(const llvm::StringRef condition,
                                     const llvm::StringRef ifTrue,
                                     const llvm::StringRef ifFalse,
                                     const mlir::Type /*type*/) const override
    {
        return "(" + ifTrue.str() + " if " + condition.str() + " else " + ifFalse.str() + ")";
    }

    [[nodiscard]] std::string convert(const Conversion /*conversion*/,
                                      const llvm::StringRef value,
                                      const mlir::Type      from,
                                      const mlir::Type      to) const override
    {
        return cast(value.str(), from, to);
    }

    [[nodiscard]] std::string call(const llvm::StringRef callee, const llvm::ArrayRef<std::string> args) const override
    {
        return callee.str() + "(" + llvm::join(args, ", ") + ")";
    }

    // The dialect.

    [[nodiscard]] bool spellsInline(mlir::Operation* op) const override
    {
        return mlir::
            isa<mlir::dsdl::IsNullOp, mlir::dsdl::BufferOrEmptyOp, mlir::dsdl::MemberAddrOp, mlir::dsdl::ElementAddrOp>(
                op);
    }

    [[nodiscard]] std::string isNull(mlir::dsdl::IsNullOp op, const ValueNames& names) const override
    {
        // The object arrives by reference; a buffer and a local are never null.
        const auto pointer = mlir::cast<mlir::dsdl::PtrType>(op.getPointer().getType());
        if (mlir::isa<mlir::dsdl::ObjectType>(pointer.getPointee()))
        {
            return names(op.getPointer()) + " is None";
        }
        return "False";
    }

    [[nodiscard]] std::string bufferOrEmpty(mlir::dsdl::BufferOrEmptyOp op, const ValueNames& names) const override
    {
        return names(op.getBuffer());
    }

    [[nodiscard]] std::string bufferAt(mlir::dsdl::BufferAtOp op, const ValueNames& names) const override
    {
        // The plan bounds its reads and writes itself; the slice is clamped to the buffer.
        const std::string buffer = names(op.getBuffer());
        return buffer + "[min(" + names(op.getByteOffset()) + ", len(" + buffer + ")):]";
    }

    [[nodiscard]] std::string loadScalar(mlir::dsdl::LoadScalarOp op, const ValueNames& names) const override
    {
        return names(op.getPointer());
    }

    void storeScalar(SourceWriter& w, mlir::dsdl::StoreScalarOp op, const ValueNames& names) const override
    {
        line(w, names(op.getPointer()) + " = " + names(op.getValue()));
    }

    [[nodiscard]] std::string local(SourceWriter&         w,
                                    mlir::dsdl::LocalOp   op,
                                    const llvm::StringRef name,
                                    const ValueNames&     names) const override
    {
        line(w, name.str() + " = " + names(op.getInit()));
        return name.str();
    }

    [[nodiscard]] std::string loadMember(mlir::dsdl::LoadMemberOp op, const ValueNames& names) const override
    {
        return loadedValue(memberAccess(op.getObject(), op.getMember(), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeMember(SourceWriter& w, mlir::dsdl::StoreMemberOp op, const ValueNames& names) const override
    {
        line(w,
             memberAccess(op.getObject(), op.getMember(), names) + " = " +
                 storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())));
    }

    [[nodiscard]] std::string loadElement(mlir::dsdl::LoadElementOp op, const ValueNames& names) const override
    {
        return loadedValue(elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeElement(SourceWriter& w, mlir::dsdl::StoreElementOp op, const ValueNames& names) const override
    {
        line(w,
             elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names) + " = " +
                 storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())));
    }

    [[nodiscard]] std::string memberAddr(mlir::dsdl::MemberAddrOp op, const ValueNames& names) const override
    {
        return memberAccess(op.getObject(), op.getMember(), names);
    }

    [[nodiscard]] std::string elementAddr(mlir::dsdl::ElementAddrOp op, const ValueNames& names) const override
    {
        return elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names);
    }

    [[nodiscard]] std::string arrayLength(mlir::dsdl::ArrayLengthOp op, const ValueNames& names) const override
    {
        return "len(" + memberAccess(op.getObject(), op.getMember(), names) + ")";
    }

    void setArrayLength(SourceWriter& w, mlir::dsdl::SetArrayLengthOp op, const ValueNames& names) const override
    {
        // Sized within its capacity -- a count past it is what the plan's validation rejects
        // next -- with default elements for the plan to store into.
        const Member      member = memberOf(op.getObject(), op.getMember());
        mlir::dsdl::IOOp  io     = member.io;
        const std::string count  = fresh("count");
        line(w, count + " = min(" + names(op.getValue()) + ", " + std::to_string(io.getArrayCapacity()) + ")");
        line(w, memberAccess(op.getObject(), op.getMember(), names) + " = " + arrayOf(member, count));
    }

    [[nodiscard]] std::string unionTag(mlir::dsdl::UnionTagOp op, const ValueNames& names) const override
    {
        return "int(" + names(op.getObject()) + "._tag)";
    }

    void setUnionTag(SourceWriter& w, mlir::dsdl::SetUnionTagOp op, const ValueNames& names) const override
    {
        // The object becomes the option the tag names, holding that option's default for the
        // plan to store into: an option that is an object or an array is storage the plan
        // addresses.
        const Plan&       plan   = planOf(op.getObject());
        const std::string object = names(op.getObject());
        const std::string tag    = names(op.getValue());
        line(w, object + "._tag = " + tag);
        bool first = true;
        for (const std::string& name : plan.order)
        {
            const Member&     member = plan.members.find(name)->second;
            mlir::dsdl::IOOp  io     = member.io;
            const std::string test   = "if " + tag + " == " + std::to_string(io.getUnionOptionIndex()) + ":";
            if (first)
            {
                open(w, test);
            }
            else
            {
                w.midway("el" + test);
                blockEmpty_ = true;
            }
            first = false;
            line(w, object + "." + member.pyName + " = " + defaultOf(member));
        }
        if (!first)
        {
            closeBlock(w);
        }
    }

    [[nodiscard]] std::string writeBits(mlir::dsdl::WriteBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string width     = std::to_string(op.getWidth());
        const std::string value     = names(op.getValue());
        const std::string prefix    = names(op.getBuffer()) + ", " + names(op.getBitOffset()) + ", ";
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "dsdl_runtime.write_float(" + prefix + width + ", " + value + ")";
        }
        if (isBool(valueType))
        {
            return "dsdl_runtime.set_bit(" + prefix + value + ")";
        }
        return "dsdl_runtime." + std::string(op.getIsSigned() ? "write_signed(" : "write_unsigned(") + prefix + width +
               ", " + value + ", False)";
    }

    [[nodiscard]] std::string readBits(mlir::dsdl::ReadBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string arguments =
            names(op.getBuffer()) + ", " + names(op.getBitOffset()) + ", " + std::to_string(op.getWidth());
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "dsdl_runtime.read_float(" + arguments + ")";
        }
        const std::string read =
            "dsdl_runtime." + std::string(op.getIsSigned() ? "read_signed(" : "read_unsigned(") + arguments + ")";
        return cast(read, mlir::IntegerType::get(op.getContext(), 64), valueType);
    }

    void bitWrite(SourceWriter& w, mlir::dsdl::BitWriteOp op, const ValueNames& names) const override
    {
        // A bool array is a list of bools, so a run of its bits goes one element at a time.
        const auto        container = boolContainerOf(op.getSource(), names);
        const std::string index     = fresh("bit");
        open(w, "for " + index + " in range(" + names(op.getWidth()) + "):");
        line(w,
             "dsdl_runtime.set_bit(" + names(op.getDestination()) + ", " + names(op.getDestinationBitOffset()) + " + " +
                 index + ", " + container.first + "[" + container.second + " + " + names(op.getSourceBitOffset()) +
                 " + " + index + "])");
        closeBlock(w);
    }

    void bitRead(SourceWriter& w, mlir::dsdl::BitReadOp op, const ValueNames& names) const override
    {
        const auto        container = boolContainerOf(op.getDestination(), names);
        const std::string index     = fresh("bit");
        open(w, "for " + index + " in range(" + names(op.getWidth()) + "):");
        line(w,
             container.first + "[" + container.second + " + " + index + "] = dsdl_runtime.get_bit(" +
                 names(op.getBuffer()) + ", " + names(op.getBitOffset()) + " + " + index + ")");
        closeBlock(w);
    }

    [[nodiscard]] std::string callSerdes(mlir::dsdl::CallSerdesOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("Python spelling: a nested call is a statement");
    }

    void declareCallSerdes(SourceWriter&            w,
                           const llvm::StringRef    name,
                           mlir::dsdl::CallSerdesOp op,
                           const ValueNames&        names) const override
    {
        // The nested value serialises itself into the slice from the buffer's offset, bounded by
        // the size the plan handed in; it answers the size it used or the code, and the size is
        // written back through the local where the plan reads it.
        const bool        serialize = op.getDirection() == "serialize";
        const std::string buffer    = names(op.getBuffer());
        const std::string size      = names(op.getSize());
        const std::string bound     = fresh("bound");
        const std::string result    = fresh("result");
        const bool        read      = isRead(op.getSize());
        line(w, bound + " = min(" + size + ", len(" + buffer + "))");
        line(w,
             result + " = " + names(op.getObject()) + "." + (serialize ? serializeInto() : deserializeFrom()) + "(" +
                 buffer + "[:" + bound + "])");
        if (!name.empty())
        {
            open(w, "if " + result + " < 0:");
            line(w, name.str() + " = " + result);
            openElse(w);
            if (read)
            {
                line(w, size + " = " + result);
            }
            line(w, name.str() + " = 0");
            closeBlock(w);
            return;
        }
        if (read)
        {
            open(w, "if " + result + " >= 0:");
            line(w, size + " = " + result);
            closeBlock(w);
        }
    }

private:
    struct Member final
    {
        std::string      pyName;
        mlir::dsdl::IOOp io;
    };

    struct Plan final
    {
        llvm::StringMap<Member>  members;
        std::vector<std::string> order;
    };

    // Python has no empty block: a block that spelled no statement closes with `pass`.

    void open(SourceWriter& w, const std::string& text) const
    {
        w.open(text);
        blockEmpty_ = true;
    }

    void line(SourceWriter& w, const std::string& text) const
    {
        w.line(text);
        blockEmpty_ = false;
    }

    /// @brief The plan the object a pointer names belongs to.
    const Plan& planOf(const mlir::Value object) const
    {
        const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(object.getType());
        const auto identity =
            pointer ? mlir::dyn_cast<mlir::dsdl::ObjectType>(pointer.getPointee()) : mlir::dsdl::ObjectType{};
        const auto found = identity ? plans_.find(identity.getIdentity()) : plans_.end();
        if (found == plans_.end())
        {
            llvm::report_fatal_error("Python spelling: an object that no plan of this schema describes");
        }
        return found->second;
    }

    Member memberOf(const mlir::Value object, const llvm::StringRef member) const
    {
        const Plan& plan  = planOf(object);
        const auto  found = plan.members.find(member);
        if (found == plan.members.end())
        {
            llvm::report_fatal_error("Python spelling: a member the schema does not declare: " + member);
        }
        return found->second;
    }

    std::string memberAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        return names(object) + "." + memberOf(object, member).pyName;
    }

    std::string elementAccess(const mlir::Value     object,
                              const llvm::StringRef member,
                              const std::string&    index,
                              const ValueNames&     names) const
    {
        return memberAccess(object, member, names) + "[" + index + "]";
    }

    /// @brief Whether the plan reads the size @p pointer addresses back after handing it out.
    static bool isRead(const mlir::Value pointer)
    {
        return llvm::any_of(pointer.getUsers(),
                            [](mlir::Operation* user) { return mlir::isa<mlir::dsdl::LoadScalarOp>(user); });
    }

    /// @brief The container expression and element base of the bool array @p address names.
    std::pair<std::string, std::string> boolContainerOf(const mlir::Value address, const ValueNames& names) const
    {
        auto element = address.getDefiningOp<mlir::dsdl::ElementAddrOp>();
        if (!element)
        {
            llvm::report_fatal_error("Python spelling: a bit copy whose storage is not an array element");
        }
        return std::make_pair(memberAccess(element.getObject(), element.getMember(), names), names(element.getIndex()));
    }

    // Members.

    /// @brief The kind of value a member or element holds.
    enum class Storage : std::uint8_t
    {
        Boolean,
        Integer,
        Float,
        Object,
    };

    static Storage storageOf(const Member& member)
    {
        mlir::dsdl::IOOp      io       = member.io;
        const llvm::StringRef category = io.getScalarCategory();
        if (io.isComposite())
        {
            return Storage::Object;
        }
        if (category == "bool")
        {
            return Storage::Boolean;
        }
        if (category == "float")
        {
            return Storage::Float;
        }
        return Storage::Integer;
    }

    /// @brief The default value of one element of @p member, or of the member when it is no array.
    std::string elementDefault(const Member& member) const
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return "False";
        case Storage::Integer:
            return "0";
        case Storage::Float:
            return "0.0";
        case Storage::Object:
            break;
        }
        mlir::dsdl::IOOp io = member.io;
        return typeNameOf_(io.getCompositeFullName().value_or(llvm::StringRef{}),
                           static_cast<std::uint32_t>(io.getCompositeMajor().value_or(0)),
                           static_cast<std::uint32_t>(io.getCompositeMinor().value_or(0))) +
               "()";
    }

    /// @brief A list of @p count default elements of @p member.
    std::string arrayOf(const Member& member, const std::string& count) const
    {
        if (storageOf(member) == Storage::Object)
        {
            return "[" + elementDefault(member) + " for _ in range(" + count + ")]";
        }
        return "[" + elementDefault(member) + "] * " + count;
    }

    /// @brief The default value of @p member.
    std::string defaultOf(const Member& member) const
    {
        mlir::dsdl::IOOp io = member.io;
        if (!io.isArray())
        {
            return elementDefault(member);
        }
        if (io.isVariableArray())
        {
            return "[]";
        }
        return arrayOf(member, std::to_string(io.getArrayCapacity()));
    }

    /// @brief @p access read as a value of @p type.
    static std::string loadedValue(const std::string& access, const Member& member, const mlir::Type type)
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return isBool(type) ? "bool(" + access + ")" : "int(" + access + ")";
        case Storage::Integer:
            // A number a caller stored may be no integer; it is read as one.
            return isBool(type) ? "(" + access + " != 0)" : "int(" + access + ")";
        case Storage::Float:
            return "float(" + access + ")";
        case Storage::Object:
            break;
        }
        return access;
    }

    /// @brief @p value, of @p type, converted for storage in @p member.
    static std::string storedValue(const std::string& value, const mlir::Type type, const Member& member)
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return isBool(type) ? value : value + " != 0";
        case Storage::Integer:
            return isBool(type) ? "int(" + value + ")" : value;
        case Storage::Float:
        case Storage::Object:
            break;
        }
        return value;
    }

    // Types.

    static bool isBool(const mlir::Type type)
    {
        return type.isInteger(1);
    }

    /// @brief @p value, of @p from, as a value of @p to.
    static std::string cast(const std::string& value, const mlir::Type from, const mlir::Type to)
    {
        if (from == to)
        {
            return value;
        }
        if (isBool(to))
        {
            return "(" + value + " != 0)";
        }
        if (isBool(from))
        {
            return "int(" + value + ")";
        }
        if (to.isInteger(8) && !from.isInteger(8))
        {
            // Truncated to eight bits and read back as the signed value they hold.
            return "(((" + value + " & 0xFF) ^ 0x80) - 0x80)";
        }
        return value;
    }

    static std::string typeName(const mlir::Type type)
    {
        if (mlir::isa<mlir::FloatType>(type))
        {
            return "float";
        }
        if (isBool(type))
        {
            return "bool";
        }
        if (mlir::isa<mlir::IndexType>(type) || mlir::isa<mlir::IntegerType>(type))
        {
            return "int";
        }
        if (const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(type))
        {
            if (mlir::isa<mlir::dsdl::ByteType>(pointer.getPointee()))
            {
                return "memoryview";
            }
            if (mlir::isa<mlir::dsdl::SizeType>(pointer.getPointee()))
            {
                return "int";
            }
        }
        llvm::report_fatal_error("Python spelling: a value of a type no plan body carries");
    }

    static std::string operatorToken(const BinaryOperator op)
    {
        switch (op)
        {
        case BinaryOperator::Add:
            return "+";
        case BinaryOperator::Sub:
            return "-";
        case BinaryOperator::Mul:
            return "*";
        case BinaryOperator::DivU:
        case BinaryOperator::DivS:
            return "//";
        case BinaryOperator::RemU:
        case BinaryOperator::RemS:
            return "%";
        case BinaryOperator::And:
            return "&";
        case BinaryOperator::Or:
            return "|";
        case BinaryOperator::Xor:
            return "^";
        case BinaryOperator::ShiftLeft:
            return "<<";
        case BinaryOperator::ShiftRightU:
        case BinaryOperator::ShiftRightS:
            return ">>";
        }
        llvm::report_fatal_error("Python spelling: an operator of an unexpected kind");
    }

    static std::string comparisonToken(const Comparison comparison)
    {
        switch (comparison)
        {
        case Comparison::Eq:
            return "==";
        case Comparison::Ne:
            return "!=";
        case Comparison::LtS:
        case Comparison::LtU:
            return "<";
        case Comparison::LeS:
        case Comparison::LeU:
            return "<=";
        case Comparison::GtS:
        case Comparison::GtU:
            return ">";
        case Comparison::GeS:
        case Comparison::GeU:
            return ">=";
        }
        llvm::report_fatal_error("Python spelling: a comparison of an unexpected kind");
    }

    /// @brief A name for a value of this spelling's own, distinct from the translator's.
    std::string fresh(const char* const stem) const
    {
        return "_" + std::string(stem) + std::to_string(fresh_++) + "_";
    }

    TypeNameResolver      typeNameOf_;
    llvm::StringMap<Plan> plans_;
    mutable bool          inBody_{false};
    mutable bool          blockEmpty_{false};
    mutable unsigned      fresh_{0};
};

/// @brief The two bodies `lower-dsdl-bodies` built for one section.
struct SectionBodies final
{
    mlir::func::FuncOp serialize;
    mlir::func::FuncOp deserialize;
};

/// @brief The schema of @p def in the lowered module, by identity.
mlir::dsdl::SchemaOp schemaOf(mlir::ModuleOp module, const SemanticDefinition& def)
{
    for (mlir::dsdl::SchemaOp schema : module.getBodyRegion().front().getOps<mlir::dsdl::SchemaOp>())
    {
        if (schema.getFullName() == def.info.fullName &&
            static_cast<std::uint32_t>(schema.getMajor()) == def.info.majorVersion &&
            static_cast<std::uint32_t>(schema.getMinor()) == def.info.minorVersion)
        {
            return schema;
        }
    }
    return {};
}

/// @brief One section: its class with the two bodies and the methods that wrap them, then its
/// constants.
llvm::Error emitSection(SourceWriter&             w,
                        const std::string&        typeName,
                        const SemanticSection&    section,
                        const AttachedDoc&        typeDoc,
                        const EmitterContext&     ctx,
                        const SemanticDefinition& def,
                        const PythonSpelling&     spelling,
                        const SectionBodies&      bodies)
{
    if (!bodies.serialize || !bodies.deserialize)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no plan bodies for %s in the lowered module",
                                       def.info.fullName.c_str());
    }
    emitSectionType(w,
                    typeName,
                    section,
                    typeDoc,
                    ctx,
                    def.info.fullName,
                    def.info.majorVersion,
                    def.info.minorVersion);
    w.blank();
    if (auto err = translateFunction(bodies.serialize, spelling, w))
    {
        return err;
    }
    w.blank();
    if (auto err = translateFunction(bodies.deserialize, spelling, w))
    {
        return err;
    }
    w.dedent();
    if (!section.constants.empty())
    {
        w.blank();
        emitSectionConstants(w, typeName, section);
    }
    return llvm::Error::success();
}

llvm::Expected<std::string> renderDefinitionFile(const SemanticDefinition& def,
                                                 const EmitterContext&     ctx,
                                                 const LoweredFactsMap&    loweredFacts,
                                                 mlir::ModuleOp            module)
{
    mlir::dsdl::SchemaOp schema = schemaOf(module, def);
    if (!schema)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no schema for %s in the lowered module",
                                       def.info.fullName.c_str());
    }

    std::ostringstream out;
    SourceWriter       w = makePyWriter(out);
    w.line(generatedCommentLine("Python backend"));
    w.line("# Source: " + def.info.fullName + "." + std::to_string(def.info.majorVersion) + "." +
           std::to_string(def.info.minorVersion));
    w.line("from __future__ import annotations");
    w.blank();
    w.line("from dataclasses import dataclass, field");
    w.blank();

    std::map<std::string, std::set<std::string>> importsByModule;
    const auto                                   addSectionImports = [&](const SemanticSection& section) {
        const auto dependencies = collectCompositeDependencies(section, def.info);
        const auto imports      = projectCompositeImports(
            dependencies,
            [&](const SemanticTypeRef& ref) { return ctx.modulePath(ref); },
            [&](const SemanticTypeRef& ref) { return ctx.typeName(ref); });
        for (const auto& importSpec : imports)
        {
            importsByModule[importSpec.modulePath].insert(importSpec.typeName);
        }
    };
    addSectionImports(def.request);
    if (def.response)
    {
        addSectionImports(*def.response);
    }

    w.line("from " + ctx.packageName() + "._runtime_loader import runtime as dsdl_runtime, error_message");
    for (const auto& [modulePath, names] : importsByModule)
    {
        std::string importNames;
        for (const auto& name : names)
        {
            if (!importNames.empty())
            {
                importNames += ", ";
            }
            importNames += name;
        }
        // NOLINTNEXTLINE(performance-inefficient-string-concatenation)
        w.line("from " + modulePath + " import " + importNames);
    }

    w.blank();
    const auto baseType = ctx.typeName(def.info);
    w.line("LLVMDSDL_GENERATOR_VERSION = \"" + std::string(llvmdsdl::kVersionString) + "\"");
    w.line("DSDL_FULL_NAME = \"" + def.info.fullName + "\"");
    w.line("DSDL_IS_DEPRECATED = " + std::string(def.request.deprecated ? "True" : "False"));
    w.line("DSDL_VERSION_MAJOR = " + std::to_string(def.info.majorVersion));
    w.line("DSDL_VERSION_MINOR = " + std::to_string(def.info.minorVersion));
    const LoweredSectionFacts* requestSectionFacts =
        lookupLoweredSectionFacts(loweredFacts, def, def.isService ? "request" : "");
    const bool        requestZohEligible = requestSectionFacts != nullptr && requestSectionFacts->zohAliasEligible;
    const std::string requestZohReason =
        (requestSectionFacts != nullptr && !requestSectionFacts->zohAliasReason.empty())
            ? requestSectionFacts->zohAliasReason
            : "not-proven";
    w.line("DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = " + std::string(requestZohEligible ? "True" : "False"));
    w.line("DSDL_REQUEST_ZOH_ALIAS_REASON = \"" + requestZohReason + "\"");
    if (def.response)
    {
        const auto* const responseSectionFacts = lookupLoweredSectionFacts(loweredFacts, def, "response");
        const bool responseZohEligible = responseSectionFacts != nullptr && responseSectionFacts->zohAliasEligible;
        const std::string responseZohReason =
            (responseSectionFacts != nullptr && !responseSectionFacts->zohAliasReason.empty())
                ? responseSectionFacts->zohAliasReason
                : "not-proven";
        w.line("DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = " + std::string(responseZohEligible ? "True" : "False"));
        w.line("DSDL_RESPONSE_ZOH_ALIAS_REASON = \"" + responseZohReason + "\"");
    }
    else
    {
        w.line("DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = False");
        w.line("DSDL_RESPONSE_ZOH_ALIAS_REASON = \"not-applicable\"");
    }
    w.blank();

    // The spelling names a nested type as this file does.
    const PythonSpelling                 spelling(schema,
                                                  [&ctx](const llvm::StringRef fullName,
                                                         const std::uint32_t   major,
                                                         const std::uint32_t   minor) {
                                      SemanticTypeRef ref;
                                      ref.fullName = fullName.str();
                                      llvm::SmallVector<llvm::StringRef> components;
                                      fullName.split(components, '.');
                                      for (const llvm::StringRef component : components)
                                      {
                                          ref.namespaceComponents.push_back(component.str());
                                      }
                                      if (!ref.namespaceComponents.empty())
                                      {
                                          ref.shortName = ref.namespaceComponents.back();
                                          ref.namespaceComponents.pop_back();
                                      }
                                      ref.majorVersion = major;
                                      ref.minorVersion = minor;
                                      return ctx.typeName(ref);
                                                  });
    std::vector<mlir::func::FuncOp>      helpers;
    std::map<std::string, SectionBodies> bodies;
    for (const mlir::func::FuncOp fn : schemaFunctions(module, schema.getSymName()))
    {
        const auto direction = planBodyDirection(fn);
        if (!direction)
        {
            helpers.push_back(fn);
            continue;
        }
        const auto     sectionAttr = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        SectionBodies& entry       = bodies[sectionAttr ? sectionAttr.getValue().str() : std::string{}];
        (*direction == "serialize" ? entry.serialize : entry.deserialize) = fn;
    }
    for (const mlir::func::FuncOp helper : helpers)
    {
        if (auto err = translateFunction(helper, spelling, w))
        {
            return std::move(err);
        }
        w.blank();
    }

    if (!def.isService)
    {
        if (auto err = emitSection(w, baseType, def.request, def.doc, ctx, def, spelling, bodies[""]))
        {
            return std::move(err);
        }
        return out.str();
    }

    const auto reqType  = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::Python, "request");
    const auto respType = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::Python, "response");
    if (auto err = emitSection(w, reqType, def.request, def.doc, ctx, def, spelling, bodies["request"]))
    {
        return std::move(err);
    }
    w.blank();
    if (def.response)
    {
        if (auto err = emitSection(w, respType, *def.response, def.doc, ctx, def, spelling, bodies["response"]))
        {
            return std::move(err);
        }
        w.blank();
    }
    w.line(baseType + " = " + reqType);
    return out.str();
}

llvm::Expected<std::string> loadRuntimeFile(const std::string& fileName)
{
    if (const auto data = embedded_runtime::find("python/" + fileName))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "embedded runtime source missing: python/%s",
                                   fileName.c_str());
}

/// @brief Returns the runtime scaffold file name for a Python specialisation.
/// @param[in] runtimeSpecialization Runtime specialisation profile.
/// @return Source runtime scaffold file name under `runtime/python`.
std::string runtimeFileForSpecialization(const RuntimeSpecialization runtimeSpecialization)
{
    if (runtimeSpecialization == RuntimeSpecialization::Fast)
    {
        return "_dsdl_runtime_fast.py";
    }
    return "_dsdl_runtime.py";
}

/// @brief Renders backend metadata emitted with generated Python artifacts.
/// @param[in] options Python emission options.
/// @return Stable JSON metadata payload.
std::string renderPackageMetadata(const Options& options)
{
    std::ostringstream out;
    out << "{\n";
    out << "  \"llvmdsdl\": {\n";
    out << R"(    "generatorVersion": ")" << llvmdsdl::kVersionString << "\",\n";
    out << R"(    "pythonRuntimeSpecialization": ")";
    out << (options.runtimeSpecialization == RuntimeSpecialization::Fast ? "fast" : "portable");
    out << "\"\n";
    out << "  }\n";
    out << "}\n";
    return out.str();
}

/// @brief Renders `pyproject.toml` metadata for generated Python packages.
/// @param[in] packageName Generated package name.
/// @param[in] rootPackageName Top-level package component used for discovery.
/// @return Minimal installable `pyproject.toml` payload.
std::string renderPyProjectToml(llvm::StringRef packageName, llvm::StringRef rootPackageName)
{
    std::ostringstream out;
    out << "[build-system]\n";
    out << "requires = [\"setuptools>=61\"]\n";
    out << "build-backend = \"setuptools.build_meta\"\n\n";

    out << "[project]\n";
    out << "name = \"" << packageName.str() << "\"\n";
    out << "version = \"" << llvmdsdl::kVersionString << "\"\n";
    out << "description = \"Generated by llvmdsdl\"\n";
    out << "requires-python = \">=3.10\"\n\n";

    out << "[tool.setuptools]\n";
    out << "include-package-data = true\n\n";

    out << "[tool.setuptools.packages.find]\n";
    out << "where = [\".\"]\n";
    out << "include = [\"" << rootPackageName.str() << "*\"]\n\n";

    out << "[tool.setuptools.package-data]\n";
    out << "\"" << packageName.str() << R"(" = ["py.typed", "_dsdl_runtime_accel*.so", )"
        << "\"_dsdl_runtime_accel*.dylib\", \"_dsdl_runtime_accel*.pyd\"]\n";
    return out.str();
}

/// @brief Renders the body of one generated `__init__.py`.
///
/// @details
/// Several Python build backends read a package's docstring and `__version__` as its metadata, and
/// flit refuses outright to package a module without a docstring -- so a package that omits them is
/// one a user cannot build with the backend of their choice.
/// The leading generated-by comment stays where it is: a comment is not a statement, so the
/// docstring is still the module's first statement and still its `__doc__`.
///
/// `__version__` is the generator's version, the version a generated package can claim.
std::string renderInitFile(llvm::StringRef dottedName, const bool isPackageRoot)
{
    std::ostringstream out;
    out << generatedCommentLine("Python backend") << "\n";
    if (isPackageRoot)
    {
        out << R"("""Generated DSDL types, rooted at the `)" << dottedName.str() << "` package.\"\"\"\n";
        out << "\n";
        out << "__version__ = \"" << llvmdsdl::kVersionString << "\"\n";
    }
    else
    {
        out << R"("""Generated DSDL types under `)" << dottedName.str() << "`.\"\"\"\n";
    }
    return out.str();
}

llvm::Error ensureInitFile(const std::filesystem::path&     dir,
                           llvm::StringRef                  dottedName,
                           const bool                       isPackageRoot,
                           std::set<std::filesystem::path>& initializedPackages,
                           const EmitWritePolicy&           writePolicy)
{
    if (!initializedPackages.insert(dir).second)
    {
        return llvm::Error::success();
    }
    std::filesystem::path const initPath = dir / "__init__.py";
    std::error_code             ec;
    if (!std::filesystem::exists(initPath, ec))
    {
        if (auto err = writeGeneratedFile(initPath, renderInitFile(dottedName, isPackageRoot), writePolicy))
        {
            return err;
        }
    }
    return llvm::Error::success();
}

llvm::Error ensurePackageInitChain(const std::filesystem::path&     packageRoot,
                                   llvm::StringRef                  packageName,
                                   const std::filesystem::path&     relDir,
                                   std::set<std::filesystem::path>& initializedPackages,
                                   const EmitWritePolicy&           writePolicy)
{
    std::filesystem::path current = packageRoot;
    std::string           dotted  = packageName.str();
    if (auto err = ensureInitFile(current, dotted, true, initializedPackages, writePolicy))
    {
        return err;
    }

    for (const auto& part : relDir)
    {
        const auto piece = part.string();
        if (piece.empty() || piece == ".")
        {
            continue;
        }
        current /= piece;
        dotted += "." + piece;
        if (auto err = ensureInitFile(current, dotted, false, initializedPackages, writePolicy))
        {
            return err;
        }
    }

    return llvm::Error::success();
}

}  // namespace

llvm::Error emit(const SemanticModule& semantic,
                 mlir::ModuleOp        module,
                 const Options&        options,
                 DiagnosticEngine&     diagnostics)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }

    const auto mlirCoverageDiagnostic =
        codegen_diagnostic_text::mlirSchemaCoverageValidationFailedForEmission("Python");
    LoweredFactsMap loweredFacts;
    if (!collectLoweredFactsFromMlir(semantic, module, diagnostics, "Python", &loweredFacts))
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "%s", mlirCoverageDiagnostic.c_str());
    }

    const auto           packageComponents = splitPackageName(options.packageName);
    const EmitterContext ctx(semantic, packageComponents, options.typeNameVersioning);

    std::filesystem::path const outRoot(options.outDir);
    const auto                  selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }
    const bool emitSupport = shouldEmitSupport(options.supportGeneration, anyTypeEmitted);

    const std::filesystem::path packageRoot = outRoot / ctx.packageRootPath();

    // Shared with the per-definition emission below, which creates any package chain a type needs.
    // Generated modules stay importable under `never` even though the scaffolding is skipped here.
    std::set<std::filesystem::path> initializedPackages;

    if (emitSupport)
    {
        if (auto err = ensurePackageInitChain(packageRoot,
                                              ctx.packageName(),
                                              std::filesystem::path{},
                                              initializedPackages,
                                              options.writePolicy))
        {
            return err;
        }

        auto runtime = loadRuntimeFile(runtimeFileForSpecialization(options.runtimeSpecialization));
        if (!runtime)
        {
            return runtime.takeError();
        }
        if (auto err = writeGeneratedFile(packageRoot / "_dsdl_runtime.py",
                                          generatedCommentLine("Python runtime scaffold") + "\n\n" + *runtime,
                                          options.writePolicy))
        {
            return err;
        }

        auto runtimeLoader = loadRuntimeFile("_runtime_loader.py");
        if (!runtimeLoader)
        {
            return runtimeLoader.takeError();
        }
        if (auto err = writeGeneratedFile(packageRoot / "_runtime_loader.py",
                                          generatedCommentLine("Python runtime loader") + "\n\n" + *runtimeLoader,
                                          options.writePolicy))
        {
            return err;
        }

        if (auto err = writeGeneratedFile(packageRoot / "llvmdsdl_codegen.json",
                                          renderPackageMetadata(options),
                                          options.writePolicy))
        {
            return err;
        }

        if (auto err = writeGeneratedFile(outRoot / "pyproject.toml",
                                          renderPyProjectToml(ctx.packageName(), packageComponents.front()),
                                          options.writePolicy))
        {
            return err;
        }

        if (auto err = writeGeneratedFile(packageRoot / "py.typed", "", options.writePolicy))
        {
            return err;
        }
    }

    std::vector<const SemanticDefinition*> ordered;
    ordered.reserve(semantic.definitions.size());
    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        ordered.push_back(&def);
    }
    std::ranges::sort(ordered, [](const auto* lhs, const auto* rhs) {
        if (lhs->info.fullName != rhs->info.fullName)
        {
            return lhs->info.fullName < rhs->info.fullName;
        }
        if (lhs->info.majorVersion != rhs->info.majorVersion)
        {
            return lhs->info.majorVersion < rhs->info.majorVersion;
        }
        return lhs->info.minorVersion < rhs->info.minorVersion;
    });

    for (const auto* def : ordered)
    {
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def->info)};
        const auto                     relPath  = EmitterContext::relativeFilePath(def->info);
        const auto                     fullPath = packageRoot / relPath;

        if (auto err = ensurePackageInitChain(packageRoot,
                                              ctx.packageName(),
                                              relPath.parent_path(),
                                              initializedPackages,
                                              options.writePolicy))
        {
            return err;
        }

        auto rendered = renderDefinitionFile(*def, ctx, loweredFacts, module);
        if (!rendered)
        {
            return rendered.takeError();
        }

        if (auto err = writeGeneratedFile(fullPath, *rendered, options.writePolicy, requiredTypeKeys))
        {
            return err;
        }
    }

    return llvm::Error::success();
}

}  // namespace llvmdsdl::emitter::python
