//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements Python backend code emission from lowered DSDL modules.
///
/// This file emits Python dataclass models and the methods a consumer calls; the serialise and
/// deserialise bodies those wrap are translations of the plan bodies through `PythonSpelling`.
///
/// The line-building concatenations here carry NOLINT for
/// performance-inefficient-string-concatenation. Each one spells out a line of generated
/// source, and an append sequence would cost the reader the line itself.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/BodyTranslator.h"
#include "llvmdsdl/CodeGen/EmitCommon.h"
#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/EmbeddedSources.h"
#include "llvmdsdl/CodeGen/emitter/Python.h"
#include "llvmdsdl/CodeGen/emitter/PythonPackaging.h"

#include <cstddef>
#include <algorithm>
#include <cassert>
#include <llvm/ADT/StringRef.h>
#include <cctype>  // IWYU pragma: keep -- libstdc++ reaches this transitively; libc++ needs it named.
#include <filesystem>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <vector>
#include <cstdint>
#include <system_error>
#include <utility>

#include "llvmdsdl/CodeGen/ImportSet.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/SchemaLookup.h"
#include "llvmdsdl/CodeGen/InitializerRender.h"
#include "llvmdsdl/CodeGen/TypeMetadata.h"
#include "llvmdsdl/CodeGen/SourceWriter.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Version.h"
#include "llvmdsdl/IR/DSDLOps.h"
#include "llvmdsdl/IR/DSDLTypes.h"
#include "llvmdsdl/Transforms/PlanSteps.h"
#include "llvmdsdl/Transforms/SurfaceTree.h"
#include "llvmdsdl/Support/GeneratedFact.h"
#include "llvmdsdl/Support/LanguageTraits.h"
#include "llvmdsdl/Support/PlanSymbol.h"
#include "llvmdsdl/Support/SurfacePlan.h"
#include "llvmdsdl/Support/Language.h"
#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/STLExtras.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringExtras.h>
#include <llvm/ADT/StringMap.h>
#include <llvm/Support/ErrorHandling.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/IR/BuiltinAttributeInterfaces.h>
#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/BuiltinTypeInterfaces.h>
#include <mlir/IR/BuiltinTypes.h>
#include <mlir/IR/Types.h>
#include <mlir/IR/Value.h>
#include <mlir/Support/LLVM.h>
#include <mlir/IR/OwningOpRef.h>
#include <cmath>
#include <iomanip>
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl::emitter::python
{

namespace
{

std::string pyConstValue(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(Language::Python, value, makeConstantTypeInfo(type));
}

SourceWriter makePyWriter(std::ostringstream& out)
{
    return SourceWriter{out, IndentPolicy::spaces(4)};
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return "# Generated by llvmdsdl " + std::string(llvmdsdl::kVersionString) + " (" + detail.str() + ").";
}

void emitAttachedDocPy(SourceWriter& w, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        w.line(line.text.empty() ? std::string{"#"} : "# " + line.text);
    }
}

/// @brief The key of the definition @p info describes, which its schema and the surface name it by.
std::string keyOf(const DiscoveredDefinition& info)
{
    return renderDefinitionKey(definitionRef(info));
}

/// @brief The key of the definition @p ref names.
std::string keyOf(const SemanticTypeRef& ref)
{
    return renderDefinitionKey(definitionRef(ref));
}

/// @brief The module a file at @p path is, from the output directory: its directories and stem,
///        dotted.
std::string moduleOfPath(llvm::StringRef path)
{
    path.consume_back(languageTraits(Language::Python).composition.fileExtension);
    std::string module = path.str();
    std::ranges::replace(module, '/', '.');
    return module;
}

/// @brief The package whose `__init__.py` is at @p path, from the output directory, dotted.
std::string packageOfInit(const llvm::StringRef path)
{
    return moduleOfPath(path.rsplit('/').first.str() + ".py");
}

/// @brief The names Python's output declares and the files it writes, as the surface declares them.
class PySurface final
{
public:
    explicit PySurface(const SurfaceTree& tree)
        : tree_(tree)
    {
    }

    [[nodiscard]] const SurfaceTree& tree() const
    {
        return tree_;
    }

    /// @brief The module scope the definition keyed @p key is declared in.
    [[nodiscard]] std::size_t file(const llvm::StringRef key) const
    {
        return tree_.definitionScope(key);
    }

    /// @brief The file the definition keyed @p key is written to, from the output directory.
    [[nodiscard]] const std::string& path(const llvm::StringRef key) const
    {
        return tree_.scope(file(key)).path;
    }

    /// @brief The module the definition is declared in, dotted from the package's root.
    [[nodiscard]] std::string module(const llvm::StringRef key) const
    {
        return moduleOfPath(path(key));
    }

    /// @brief The package's own `__init__.py`, from the output directory.
    [[nodiscard]] const std::string& rootFile() const
    {
        return tree_.scope(0).path;
    }

    /// @brief The package, dotted.
    [[nodiscard]] std::string package() const
    {
        return packageOfInit(rootFile());
    }

    /// @brief The name of @p section's type.
    [[nodiscard]] const std::string& typeName(const llvm::StringRef key, const llvm::StringRef section) const
    {
        return tree_.scope(tree_.typeScope(key, section)).name;
    }

    /// @brief The name of the declaration of @p kind in the definition's module for @p member of
    ///        @p section, stating @p fact.
    [[nodiscard]] const std::string& declared(const llvm::StringRef              key,
                                              const SurfaceDeclKind              kind,
                                              const llvm::StringRef              section,
                                              const llvm::StringRef              member = {},
                                              const std::optional<GeneratedFact> fact   = std::nullopt) const
    {
        return tree_.nameOf(file(key), kind, SurfaceEntity{key.str(), section.str(), member.str(), {}}, fact);
    }

    /// @brief The name of the data member of @p section's type that @p member is, or that states
    ///        @p fact; empty where the type declares none, as in an accessors-only run.
    [[nodiscard]] std::string member(const llvm::StringRef              key,
                                     const llvm::StringRef              section,
                                     const llvm::StringRef              member,
                                     const std::optional<GeneratedFact> fact = std::nullopt) const
    {
        const SurfaceDecl* const decl = tree_.find(tree_.typeScope(key, section),
                                                   SurfaceDeclKind::Field,
                                                   SurfaceEntity{key.str(), section.str(), member.str(), {}},
                                                   fact);
        return (decl != nullptr) ? decl->name : std::string{};
    }

    /// @brief The name of the declaration of @p kind that stands for the lowered function @p symbol,
    ///        stating @p fact.
    [[nodiscard]] const std::string& function(const llvm::StringRef              symbol,
                                              const SurfaceDeclKind              kind,
                                              const std::optional<GeneratedFact> fact = std::nullopt) const
    {
        return tree_.nameOf(symbol, kind, fact);
    }

    /// @brief The local name the definition keyed @p key imports the one keyed @p imported under,
    ///        where it imports it.
    [[nodiscard]] const SurfaceDecl* import(const llvm::StringRef key, const llvm::StringRef imported) const
    {
        return tree_.find(file(key), SurfaceDeclKind::Import, SurfaceEntity{imported.str(), {}, {}, {}});
    }

private:
    const SurfaceTree& tree_;
};

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule& semantic, const PySurface& names, const bool accessorsOnly)
        : names_(names)
        , index_(semantic)
        , accessorsOnly_(accessorsOnly)
    {
    }

    /// @brief The names the output declares.
    const PySurface& names() const
    {
        return names_;
    }

    /// @brief Whether the run emits the field accessors and neither the object type nor the serdes.
    bool accessorsOnly() const
    {
        return accessorsOnly_;
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

private:
    const PySurface& names_;
    DefinitionIndex  index_;
    bool             accessorsOnly_{false};
};

/// @brief How one Python file names what it takes from outside itself, recording each import.
///
/// Every symbol the file writes from another module is named here, so the import block written from
/// the set once the file is rendered holds what the file names and nothing else.
class PyFileNames final
{
public:
    PyFileNames(const EmitterContext& ctx, ImportSet& imports, std::string ownKey)
        : ctx_(ctx)
        , imports_(imports)
        , ownKey_(std::move(ownKey))
    {
    }

    [[nodiscard]] const EmitterContext& context() const
    {
        return ctx_;
    }

    /// @brief The class of the definition @p ref, imported from its module under the local name
    ///        claimed for it, unless the module is this file.
    [[nodiscard]] std::string type(const SemanticTypeRef& ref) const
    {
        const PySurface&   names = ctx_.names();
        const std::string  key   = keyOf(ref);
        const std::string& name  = names.typeName(key, {});
        if (key == ownKey_)
        {
            return name;
        }
        const SurfaceDecl* const local = names.import(ownKey_, key);
        return imports_.member(ImportOrigin::Definition,
                               names.module(key),
                               name,
                               (local != nullptr) ? local->name : name);
    }

    /// @brief The class of the type @p fullName names at @p major.@p minor.
    [[nodiscard]] std::string type(const llvm::StringRef fullName,
                                   const std::uint32_t   major,
                                   const std::uint32_t   minor) const
    {
        SemanticTypeRef                    ref;
        llvm::SmallVector<llvm::StringRef> components;
        fullName.split(components, '.');
        for (const llvm::StringRef component : components)
        {
            ref.namespaceComponents.push_back(component.str());
        }
        if (!ref.namespaceComponents.empty())
        {
            ref.shortName = ref.namespaceComponents.back();
            ref.namespaceComponents.pop_back();
        }
        ref.fullName     = fullName.str();
        ref.majorVersion = major;
        ref.minorVersion = minor;
        return type(ref);
    }

    /// @brief The standard library's `dataclasses` member @p name.
    [[nodiscard]] std::string dataclasses(const llvm::StringRef name) const
    {
        return imports_.member(ImportOrigin::Standard, "dataclasses", name);
    }

    /// @brief The standard library's `sys`.
    [[nodiscard]] std::string sys() const
    {
        return imports_.module(ImportOrigin::Standard, "sys", "sys");
    }

    /// @brief The runtime module the bodies call.
    [[nodiscard]] std::string runtime() const
    {
        return imports_.member(ImportOrigin::Runtime, runtimeLoader(), "runtime", "dsdl_runtime");
    }

    /// @brief The runtime's message for an error code.
    [[nodiscard]] std::string errorMessage() const
    {
        return imports_.member(ImportOrigin::Runtime, runtimeLoader(), "error_message");
    }

    /// @brief The runtime's base of every generated class.
    [[nodiscard]] std::string compositeObject() const
    {
        return imports_.member(ImportOrigin::Runtime, runtimeLoader(), "CompositeObject");
    }

    /// @brief The standard library's `typing` member @p name.
    [[nodiscard]] std::string typing(const llvm::StringRef name) const
    {
        return imports_.member(ImportOrigin::Standard, "typing", name);
    }

private:
    [[nodiscard]] std::string runtimeLoader() const
    {
        return ctx_.names().package() + "._runtime_loader";
    }

    const EmitterContext& ctx_;
    ImportSet&            imports_;
    std::string           ownKey_;
};

/// @brief The import block of a Python file that names @p imports: the standard library's, then the
///        package's own, each group closed by a blank line.
/// @brief The line length `ruff` and `black` hold a Python file to by default.
constexpr std::size_t kPythonLineLength = 88;

std::string renderPythonImports(const ImportSet& imports)
{
    // isort's layout: a group per origin, and within one the plain imports ahead of the `from` ones.
    std::string standardPlain;
    std::string standardFrom;
    std::string ownPlain;
    std::string ownFrom;
    for (const ImportedModule& module : imports.modules())
    {
        const bool   standard = module.origin == ImportOrigin::Standard;
        std::string& plain    = standard ? standardPlain : ownPlain;
        std::string& from     = standard ? standardFrom : ownFrom;
        if (!module.binding.empty())
        {
            plain += "import " + module.path + ((module.binding == module.path) ? "" : " as " + module.binding) + "\n";
        }
        if (!module.members.empty())
        {
            std::vector<std::string> names;
            std::string              joined;
            for (const auto& member : module.members)
            {
                names.push_back(member.name + ((member.local == member.name) ? "" : " as " + member.local));
                joined += (joined.empty() ? "" : ", ") + names.back();
            }
            const std::string head = "from " + module.path + " import ";
            if (head.size() + joined.size() <= kPythonLineLength)
            {
                from += head + joined + "\n";
                continue;
            }
            // Too long for a line, it is wrapped as `ruff format` writes it: one name to a line.
            from += head + "(\n";
            for (const std::string& name : names)
            {
                from += "    " + name + ",\n";
            }
            from += ")\n";
        }
    }
    std::string out;
    for (const std::string& group : {standardPlain + standardFrom, ownPlain + ownFrom})
    {
        if (!group.empty())
        {
            out += group + "\n";
        }
    }
    return out;
}

std::string pyFieldBaseType(const SemanticFieldType& type, const PyFileNames& file)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "bool";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        return "int";
    case SemanticScalarCategory::Float:
        return "float";
    case SemanticScalarCategory::Void:
        return "int";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return file.type(*type.compositeType);
        }
        return "object";
    }
    return "object";
}

std::string pyFieldType(const SemanticFieldType& type, const PyFileNames& file)
{
    auto base = pyFieldBaseType(type, file);
    if (type.arrayKind == ArrayKind::None)
    {
        return base;
    }
    return "list[" + base + "]";
}

std::string pyElementDefaultExpr(const SemanticFieldType& type, const PyFileNames& file);

/// @brief The Python literal a stored constant is, for a member of @p type.
std::string pyStoredLiteral(const SemanticFieldType& type, const mlir::TypedAttr value, const PyFileNames& file)
{
    if (const auto integer = mlir::dyn_cast_or_null<mlir::IntegerAttr>(value))
    {
        if (type.scalarCategory == SemanticScalarCategory::Bool)
        {
            return integer.getInt() != 0 ? "True" : "False";
        }
        return std::to_string(integer.getInt());
    }
    if (const auto real = mlir::dyn_cast_or_null<mlir::FloatAttr>(value))
    {
        std::string text = std::to_string(real.getValueAsDouble());
        text.erase(text.find_last_not_of('0') + 1);
        if (text.ends_with('.'))
        {
            text += '0';
        }
        return text;
    }
    return pyElementDefaultExpr(type, file);
}

/// @brief The dataclass default a field takes, as the initialise body states it.
std::string pyDefaultFromBody(const SemanticFieldType& type, const MemberDefault& entry, const PyFileNames& file)
{
    if (entry.kind == MemberDefault::Kind::Scalar)
    {
        return pyStoredLiteral(type, entry.value, file);
    }
    // Every other default is a factory, which `dataclasses.field` takes.
    const std::string factory = file.dataclasses("field") + "(default_factory=";
    switch (entry.kind)
    {
    case MemberDefault::Kind::Scalar:
        break;
    case MemberDefault::Kind::FixedScalarArray:
        return factory + "lambda: [" + pyStoredLiteral(type, entry.value, file) + "] * " + std::to_string(entry.count) +
               ")";
    case MemberDefault::Kind::BoolArray:
        return factory + "lambda: [False] * " + std::to_string(entry.count) + ")";
    case MemberDefault::Kind::FixedCompositeArray:
        return factory + "lambda: [" + pyElementDefaultExpr(type, file) + " for _ in range(" +
               std::to_string(entry.count) + ")])";
    case MemberDefault::Kind::VariableArrayEmpty:
        return factory + "list)";
    case MemberDefault::Kind::Composite:
        return factory + "lambda: " + pyElementDefaultExpr(type, file) + ")";
    case MemberDefault::Kind::View:
        return (type.arrayKind == ArrayKind::Fixed)
                   ? factory + "lambda: [memoryview(b\"\") for _ in range(" + std::to_string(type.arrayCapacity) + ")])"
                   : factory + "lambda: memoryview(b\"\"))";
    }
    return pyElementDefaultExpr(type, file);
}

/// @brief The default of one element of @p type, or of a scalar or object.
std::string pyElementDefaultExpr(const SemanticFieldType& type, const PyFileNames& file)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "False";
    case SemanticScalarCategory::Float:
        return "0.0";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return file.type(*type.compositeType) + "()";
        }
        return "None";
    case SemanticScalarCategory::Void:
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        return "0";
    }
    return "None";
}

/// @brief One section's names, as the surface declares them.
class PySection final
{
public:
    PySection(const PySurface& names, std::string key, std::string section)
        : names_(names)
        , key_(std::move(key))
        , section_(std::move(section))
    {
    }

    /// @brief The name of the section's class.
    [[nodiscard]] const std::string& typeName() const
    {
        return names_.typeName(key_, section_);
    }

    /// @brief The name of the attribute the DSDL field @p member is; empty where the class declares
    ///        none.
    [[nodiscard]] std::string field(const llvm::StringRef member) const
    {
        return names_.member(key_, section_, member);
    }

    /// @brief The name of the attribute the generator adds to state @p fact.
    [[nodiscard]] std::string dataMember(const GeneratedFact fact) const
    {
        return names_.member(key_, section_, {}, fact);
    }

    /// @brief The name of the class attribute stating @p fact.
    [[nodiscard]] const std::string& classAttribute(const GeneratedFact fact) const
    {
        const SurfaceTree& tree = names_.tree();
        return tree.nameOf(tree.typeScope(key_, section_),
                           SurfaceDeclKind::Constant,
                           SurfaceEntity{key_, section_, {}, {}},
                           fact);
    }

    /// @brief The name of the constant holding the tag value of the union option @p member.
    [[nodiscard]] const std::string& option(const llvm::StringRef member) const
    {
        return names_.declared(key_, SurfaceDeclKind::Option, section_, member);
    }

    /// @brief The name of the constant the DSDL constant @p member is.
    [[nodiscard]] const std::string& constant(const llvm::StringRef member) const
    {
        return names_.declared(key_, SurfaceDeclKind::Constant, section_, member);
    }

    [[nodiscard]] const PySurface& names() const
    {
        return names_;
    }

    [[nodiscard]] const std::string& section() const
    {
        return section_;
    }

private:
    const PySurface& names_;
    std::string      key_;
    std::string      section_;
};

/// @brief Declares the tag value that selects each of a union's options.
void emitUnionOptionTags(SourceWriter& w, const PySection& names, const SectionMetadata& metadata)
{
    if (!metadata.isUnion)
    {
        return;
    }
    for (const auto& option : metadata.unionOptions)
    {
        w.line(names.option(option.name) + " = " + std::to_string(option.tag));
    }
}

void emitSectionConstants(SourceWriter& w, const PySection& names, const SemanticSection& section)
{
    for (const auto& constant : section.constants)
    {
        emitAttachedDocPy(w, constant.doc);
        w.line(names.constant(constant.name) + " = " + pyConstValue(constant.type, constant.value));
    }
}

/// @brief Opens a section's class: a dataclass of the runtime's `CompositeObject`, which composes
///        `serialize` and `deserialize` from the class's bodies, stating the size of the buffer
///        `serialize` writes into.
void openClass(SourceWriter& w, const PySection& names, const SemanticSection& section, const PyFileNames& file)
{
    w.line("@" + file.dataclasses("dataclass") + "(slots=True)");
    w.open("class " + names.typeName() + "(" + file.compositeObject() + "):");
    w.line(names.classAttribute(GeneratedFact::SerializationBufferSizeBytes) + ": " + file.typing("ClassVar") +
           "[int] = " + std::to_string((section.serializationBufferSizeBits + 7) / 8));
}

const MemberDefault* memberDefault(const InitializerShape& init, const std::string& name);

void emitStructSectionType(SourceWriter&           w,
                           const InitializerShape& init,
                           const PySection&        names,
                           const SemanticSection&  section,
                           const AttachedDoc&      typeDoc,
                           const PyFileNames&      file,
                           const std::string&      fullName,
                           const std::uint32_t     majorVersion,
                           const std::uint32_t     minorVersion)
{
    const std::string& typeName = names.typeName();
    emitAttachedDocPy(w, docWithDeprecationNotice(typeDoc, section.deprecated, fullName, majorVersion, minorVersion));
    openClass(w, names, section, file);
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        emitAttachedDocPy(w, field.doc);
        const auto  fieldName = names.field(field.name);
        const auto* entry     = memberDefault(init, field.name);
        if (entry == nullptr)
        {
            llvm::report_fatal_error(llvm::Twine("Python: the initialise body of ") + typeName + " does not set '" +
                                     field.name + "'");
        }
        w.line(fieldName + ": " +
               (field.heldAsView
                    ? std::string{(field.resolvedType.arrayKind == ArrayKind::None) ? "memoryview" : "list[memoryview]"}
                    : pyFieldType(field.resolvedType, file)) +
               " = " + pyDefaultFromBody(field.resolvedType, *entry, file));
    }
}

/// @brief The member named @p name in @p init, or null.
const MemberDefault* memberDefault(const InitializerShape& init, const std::string& name)
{
    for (const auto& entry : init.members)
    {
        if (entry.member == name)
        {
            return &entry;
        }
    }
    return nullptr;
}

void emitUnionSectionType(SourceWriter&           w,
                          const InitializerShape& init,
                          const PySection&        names,
                          const SemanticSection&  section,
                          const AttachedDoc&      typeDoc,
                          const PyFileNames&      file,
                          const std::string&      fullName,
                          const std::uint32_t     majorVersion,
                          const std::uint32_t     minorVersion)
{
    const std::string& typeName = names.typeName();
    emitAttachedDocPy(w, docWithDeprecationNotice(typeDoc, section.deprecated, fullName, majorVersion, minorVersion));
    openClass(w, names, section, file);
    // A Python union holds one arm: the tag the body stores, and that arm at the default the body
    // gives it. The other arms are absent, which is what `None` says.
    w.line(names.dataMember(GeneratedFact::UnionTag) + ": int = " + std::to_string(init.unionTag));

    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        emitAttachedDocPy(w, field.doc);
        const auto  fieldName = names.field(field.name);
        const auto* entry     = memberDefault(init, field.name);
        if (entry == nullptr)
        {
            llvm::report_fatal_error(llvm::Twine("Python: the initialise body of ") + typeName + " does not set '" +
                                     field.name + "'");
        }
        const bool selected = std::cmp_equal(field.unionOptionIndex, init.unionTag);
        w.line(fieldName + ": " + pyFieldType(field.resolvedType, file) +
               " | None = " + (selected ? pyDefaultFromBody(field.resolvedType, *entry, file) : "None"));
    }
}

void emitSectionType(SourceWriter&           w,
                     const InitializerShape& init,
                     const PySection&        names,
                     const SemanticSection&  section,
                     const AttachedDoc&      typeDoc,
                     const PyFileNames&      file,
                     const std::string&      fullName,
                     const std::uint32_t     majorVersion,
                     const std::uint32_t     minorVersion)
{
    if (section.isUnion)
    {
        emitUnionSectionType(w, init, names, section, typeDoc, file, fullName, majorVersion, minorVersion);
    }
    else
    {
        emitStructSectionType(w, init, names, section, typeDoc, file, fullName, majorVersion, minorVersion);
    }
}

/// @brief The Python spelling of the plan-body vocabulary, for one schema.
///
/// Every integer of the plan is a Python `int`, which holds the value it stands for: a
/// constant is spelled as that value, and a bigint's bitwise operators read a negative value as
/// its two's complement. A buffer is a `memoryview`, and a pointer into it is a slice of the
/// view. A body is a method of the dataclass that answers the size it used, or the error code,
/// which is negative; the `serialize` and `deserialize` methods a consumer calls wrap it. A
/// deserialise body is handed a default-constructed object, whose fixed arrays and nested
/// objects exist; a union's option is created when the plan sets the tag. Python has no
/// empty block, so a block that spelled no statement closes with `pass`.
class PythonSpelling final : public BodySpelling
{
public:
    PythonSpelling(mlir::dsdl::SchemaOp schema, const PySurface& names, const PyFileNames& file)
        : file_(file)
        , names_(names)
    {
        // A nested call names the nested type's own method, found by the identity of its plan.
        for (const SurfaceScope& scope : names.tree().plan().scopes)
        {
            if ((scope.kind != SurfaceScopeKind::Type) || !scope.of)
            {
                continue;
            }
            if (const std::optional<SchemaSymbol> symbol = parseSchemaSymbol(scope.of->schema))
            {
                types_[planIdentity(symbol->fullName, symbol->major, symbol->minor, scope.of->section)] =
                    NestedType{.section = scope.of->section, .schema = *symbol};
            }
        }
        if (schema.getBody().empty())
        {
            return;
        }
        const std::string key = schema.getSymName().str();
        for (mlir::dsdl::SerializationPlanOp plan : schema.getBody().front().getOps<mlir::dsdl::SerializationPlanOp>())
        {
            const llvm::StringRef section = plan.getSection().value_or(llvm::StringRef{});
            Plan                  entry;
            if (!plan.getBody().empty())
            {
                for (mlir::dsdl::IOOp io : plan.getBody().front().getOps<mlir::dsdl::IOOp>())
                {
                    if (!io.isPadding())
                    {
                        entry.members[io.getName()] = Member{names.member(key, section, io.getName()), io};
                        entry.order.push_back(io.getName().str());
                    }
                }
            }
            // The union's tag, reached by its accessors as a member is: the wire holds it ahead
            // of the option, and no field can be named `_tag_`.
            if (plan.getIsUnion())
            {
                tagSteps_.push_back(unionTagStep(schema->getContext(), plan.getUnionTagBits().value_or(0)));
                entry.members[kPlanUnionTagMember] =
                    Member{names.member(key, section, {}, GeneratedFact::UnionTag), tagSteps_.back().get()};
            }
            plans_[planIdentity(schema, plan)] = std::move(entry);
        }
    }

    // Functions.

    std::vector<std::string> openFunction(SourceWriter& w, mlir::func::FuncOp fn) const override
    {
        const auto direction = planBodyDirection(fn);
        accessor_            = Accessor::None;
        infallible_          = fn->hasAttr("llvmdsdl.infallible");
        if (!direction)
        {
            std::vector<std::string> parameters;
            std::string              list;
            for (const auto [index, argument] : llvm::enumerate(fn.getArguments()))
            {
                parameters.push_back("p" + std::to_string(index));
                list += (list.empty() ? "" : ", ") + parameters.back() + ": " + typeName(argument.getType());
            }
            open(w,
                 "def " + functionName(fn.getSymName()) + "(" + list + ") -> " + typeName(fn.getResultTypes().front()) +
                     ":");
            return parameters;
        }
        if (*direction == "get" || *direction == "set")
        {
            return openAccessor(w, fn, *direction == "get");
        }
        open(w,
             "def " + names_.function(fn.getSymName(), SurfaceDeclKind::Entry) + "(self, buffer: memoryview) -> int:");
        return {"self", "buffer"};
    }

    void closeFunction(SourceWriter& w, mlir::func::FuncOp /*fn*/) const override
    {
        closeBlock(w);
    }

    [[nodiscard]] std::string valueName(const ValueRole       role,
                                        const llvm::StringRef member,
                                        const std::size_t     ordinal) const override
    {
        return snakeValueName(role, member, ordinal);
    }

    [[nodiscard]] llvm::ArrayRef<llvm::StringRef> reservedLocals() const override
    {
        // A body measures with len, clamps with min, and slices a memoryview; the rest are the
        // builtins a body would reach for next. Python has no declaration, so an assignment makes
        // the name local for the whole function and the builtin is gone from its first line.
        static const llvm::StringRef names[] = {"abs",
                                                "all",
                                                "any",
                                                "bin",
                                                "bool",
                                                "bytearray",
                                                "bytes",
                                                "chr",
                                                "dict",
                                                "divmod",
                                                "enumerate",
                                                "filter",
                                                "float",
                                                "format",
                                                "frozenset",
                                                "getattr",
                                                "hash",
                                                "hex",
                                                "id",
                                                "int",
                                                "isinstance",
                                                "issubclass",
                                                "iter",
                                                "len",
                                                "list",
                                                "map",
                                                "max",
                                                "memoryview",
                                                "min",
                                                "next",
                                                "object",
                                                "oct",
                                                "ord",
                                                "pow",
                                                "print",
                                                "range",
                                                "repr",
                                                "reversed",
                                                "round",
                                                "set",
                                                "setattr",
                                                "slice",
                                                "sorted",
                                                "str",
                                                "sum",
                                                "tuple",
                                                "type",
                                                "zip",
                                                // Modules a body reads through, bound by an import
                                                // and looked up like any other name.
                                                "dsdl_runtime",
                                                "sys"};
        return names;
    }

    [[nodiscard]] std::string functionName(const llvm::StringRef callee) const override
    {
        return names_.function(callee, SurfaceDeclKind::Helper);
    }

    // Statements.

    void declare(SourceWriter& w,
                 const mlir::Type /*type*/,
                 const llvm::StringRef name,
                 const llvm::StringRef expr) const override
    {
        line(w, name.str() + " = " + expr.str());
    }

    void declareVariable(SourceWriter& /*w*/,
                         const mlir::Type /*type*/,
                         const llvm::StringRef /*name*/,
                         const bool /*reassigned*/) const override
    {
        // A Python variable exists from its first assignment, which every path makes.
    }

    void assign(SourceWriter& w, const llvm::StringRef name, const llvm::StringRef expr) const override
    {
        line(w, name.str() + " = " + expr.str());
    }

    void discard(SourceWriter& w, const llvm::StringRef expr) const override
    {
        line(w, expr.str());
    }

    /// @brief Opens a getter or a setter: a static method of the class, speaking the member's
    ///        own type. The plan holds an integer as an `int`, which a `bool` value is rebound to;
    ///        an index is an `int` already.
    std::vector<std::string> openAccessor(SourceWriter& w, mlir::func::FuncOp fn, const bool getter) const
    {
        const Accessed        a        = accessed(fn);
        const std::string&    name     = names_.function(fn.getSymName(), SurfaceDeclKind::Accessor);
        mlir::dsdl::IOOp      io       = a.member->io;
        const llvm::StringRef category = io.getScalarCategory();
        std::string           storage  = "int";
        if (category == "bool")
        {
            storage = "bool";
        }
        else if (category == "float")
        {
            storage = "float";
        }
        const bool        composite = getter && mlir::isa<mlir::dsdl::PtrType>(fn.getResultTypes().front());
        const bool        indexed   = fn.getNumArguments() == (getter ? 3U : 4U);
        const std::string index     = indexed ? ", index: int" : "";
        accessor_                   = getter ? Accessor::Getter : Accessor::Setter;
        returnCast_                 = (getter && storage == "bool") ? "bool" : std::string{};
        line(w, "@staticmethod");
        if (composite)
        {
            // The nested type's buffer, as a slice, which carries its own length.
            open(w, "def " + name + "(buffer: memoryview" + index + ") -> memoryview:");
        }
        else if (getter)
        {
            open(w, "def " + name + "(buffer: memoryview" + index + ") -> " + storage + ":");
        }
        else
        {
            open(w, "def " + name + "(buffer: memoryview" + index + ", value: " + storage + ") -> None:");
        }
        std::vector<std::string> parameters{"buffer", "len(buffer)"};
        if (indexed)
        {
            parameters.emplace_back("index");
        }
        if (!getter)
        {
            if (storage != "float")
            {
                line(w, "value = int(value)");
            }
            parameters.emplace_back("value");
        }
        return parameters;
    }

    void returnValue(SourceWriter& w, const llvm::StringRef expr) const override
    {
        // A getter answers the value in the member's own type; a setter answers nothing, and raises
        // where the code it would answer is an error.
        if (accessor_ == Accessor::Getter)
        {
            line(w, returnCast_.empty() ? "return " + expr.str() : "return bool(" + expr.str() + ")");
            return;
        }
        if (accessor_ == Accessor::Setter)
        {
            raiseOn(w, expr);
            return;
        }
        line(w, "return " + expr.str());
    }

    void returnWithSize(SourceWriter& w, const llvm::StringRef error, const llvm::StringRef used) const override
    {
        // The size used, where the code is no error, which is raised.
        raiseOn(w, error);
        line(w, "return " + used.str());
    }

    /// @brief Raises the error @p code states, where it states one: a body the lowering found cannot
    ///        fail raises nothing.
    void raiseOn(SourceWriter& w, const llvm::StringRef code) const
    {
        if (infallible_)
        {
            return;
        }
        open(w, "if " + code.str() + " != 0:");
        line(w, "raise ValueError(" + file_.errorMessage() + "(" + code.str() + "))");
        closeBlock(w);
    }

    [[nodiscard]] std::string bufferLength(mlir::dsdl::BufferLengthOp op, const ValueNames& names) const override
    {
        return "len(" + names(op.getBuffer()) + ")";
    }

    void openIf(SourceWriter& w, const llvm::StringRef condition) const override
    {
        open(w, "if " + condition.str() + ":");
    }

    void openElse(SourceWriter& w) const override
    {
        if (blockEmpty_)
        {
            w.line("pass");
        }
        w.midway("else:");
        blockEmpty_ = true;
    }

    void openLoop(SourceWriter& w) const override
    {
        open(w, "while True:");
    }

    void breakUnless(SourceWriter& w, const llvm::StringRef condition) const override
    {
        open(w, "if not (" + condition.str() + "):");
        line(w, "break");
        closeBlock(w);
    }

    void openFor(SourceWriter&         w,
                 const llvm::StringRef variable,
                 const llvm::StringRef lower,
                 const llvm::StringRef upper,
                 const llvm::StringRef step) const override
    {
        open(w, "for " + variable.str() + " in range(" + lower.str() + ", " + upper.str() + ", " + step.str() + "):");
    }

    void closeBlock(SourceWriter& w) const override
    {
        if (blockEmpty_)
        {
            w.line("pass");
        }
        w.dedent();
        blockEmpty_ = false;
    }

    // Values.

    [[nodiscard]] std::string constant(const mlir::TypedAttr value) const override
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerAttr>(value))
        {
            const mlir::Type type = integer.getType();
            if (mlir::isa<mlir::IndexType>(type))
            {
                return std::to_string(integer.getValue().getZExtValue());
            }
            if (isBool(type))
            {
                return integer.getValue().isZero() ? "False" : "True";
            }
            // The value the two's complement stands for: an int holds it as such, and the
            // bitwise operators read a negative int as its two's complement.
            return std::to_string(integer.getValue().getSExtValue());
        }
        if (const auto real = mlir::dyn_cast<mlir::FloatAttr>(value))
        {
            const double number = real.getValueAsDouble();
            if (std::isnan(number))
            {
                return "float(\"nan\")";
            }
            if (std::isinf(number))
            {
                return number < 0 ? "-float(\"inf\")" : "float(\"inf\")";
            }
            std::ostringstream stream;
            stream << std::setprecision(17) << number;
            std::string text = stream.str();
            if (text.find_first_of(".e") == std::string::npos)
            {
                text += ".0";
            }
            return text;
        }
        llvm::report_fatal_error("Python spelling: a constant of an unexpected kind");
    }

    [[nodiscard]] std::string binary(const BinaryOperator  op,
                                     const llvm::StringRef lhs,
                                     const llvm::StringRef rhs,
                                     const mlir::Type      type) const override
    {
        if (isBool(type))
        {
            switch (op)
            {
            case BinaryOperator::And:
                return lhs.str() + " and " + rhs.str();
            case BinaryOperator::Or:
                return lhs.str() + " or " + rhs.str();
            case BinaryOperator::Xor:
                return lhs.str() + " != " + rhs.str();
            default:
                llvm::report_fatal_error("Python spelling: an arithmetic operator on a bool");
            }
        }
        return lhs.str() + " " + operatorToken(op) + " " + rhs.str();
    }

    [[nodiscard]] std::string logicalNot(const llvm::StringRef expr) const override
    {
        return "not (" + expr.str() + ")";
    }

    [[nodiscard]] std::string compare(const Comparison      comparison,
                                      const llvm::StringRef lhs,
                                      const llvm::StringRef rhs,
                                      const mlir::Type      type) const override
    {
        std::string a = lhs.str();
        std::string b = rhs.str();
        switch (comparison)
        {
        case Comparison::Eq:
            return a + " == " + b;
        case Comparison::Ne:
            return a + " != " + b;
        case Comparison::LtU:
        case Comparison::LeU:
        case Comparison::GtU:
        case Comparison::GeU:
            // An int is the value its bits stand for; an unsigned comparison against a negative
            // literal reads both as the unsigned 64-bit values the plan compares.
            if (type.isInteger(64) && (lhs.starts_with("-") || rhs.starts_with("-")))
            {
                a = "(" + a + " & 0xFFFFFFFFFFFFFFFF)";
                b = "(" + b + " & 0xFFFFFFFFFFFFFFFF)";
            }
            break;
        default:
            break;
        }
        return a + " " + comparisonToken(comparison) + " " + b;
    }

    [[nodiscard]] std::string select(const llvm::StringRef condition,
                                     const llvm::StringRef ifTrue,
                                     const llvm::StringRef ifFalse,
                                     const mlir::Type /*type*/) const override
    {
        return "(" + ifTrue.str() + " if " + condition.str() + " else " + ifFalse.str() + ")";
    }

    [[nodiscard]] std::string convert(const Conversion /*conversion*/,
                                      const llvm::StringRef value,
                                      const mlir::Type      from,
                                      const mlir::Type      to) const override
    {
        return cast(value.str(), from, to);
    }

    [[nodiscard]] std::string call(const llvm::StringRef callee, const llvm::ArrayRef<std::string> args) const override
    {
        return callee.str() + "(" + llvm::join(args, ", ") + ")";
    }

    // The dialect.

    [[nodiscard]] bool spellsInline(mlir::Operation* op) const override
    {
        return mlir::
            isa<mlir::dsdl::IsNullOp, mlir::dsdl::BufferOrEmptyOp, mlir::dsdl::MemberAddrOp, mlir::dsdl::ElementAddrOp>(
                op);
    }

    [[nodiscard]] std::string indexHolds(mlir::dsdl::IndexHoldsOp op, const ValueNames& names) const override
    {
        // An int holds every count; a list holds at most sys.maxsize elements.
        const std::string value = names(op.getValue());
        const std::string sys   = file_.sys();
        return "(-" + sys + ".maxsize - 1 <= " + value + " <= " + sys + ".maxsize)";
    }

    [[nodiscard]] std::string isNotNull(mlir::dsdl::IsNullOp op, const ValueNames& names) const override
    {
        const auto pointer = mlir::cast<mlir::dsdl::PtrType>(op.getPointer().getType());
        if (mlir::isa<mlir::dsdl::ObjectType>(pointer.getPointee()))
        {
            return names(op.getPointer()) + " is not None";
        }
        return "True";
    }

    [[nodiscard]] std::string isNull(mlir::dsdl::IsNullOp op, const ValueNames& names) const override
    {
        // The object arrives by reference; a buffer and a local are never null.
        const auto pointer = mlir::cast<mlir::dsdl::PtrType>(op.getPointer().getType());
        if (mlir::isa<mlir::dsdl::ObjectType>(pointer.getPointee()))
        {
            return names(op.getPointer()) + " is None";
        }
        return "False";
    }

    [[nodiscard]] std::string bufferOrEmpty(mlir::dsdl::BufferOrEmptyOp op, const ValueNames& names) const override
    {
        return names(op.getBuffer());
    }

    [[nodiscard]] std::string bufferAt(mlir::dsdl::BufferAtOp op, const ValueNames& names) const override
    {
        // The plan bounds its reads and writes itself; the slice is clamped to the buffer.
        const std::string buffer = names(op.getBuffer());
        return buffer + "[min(" + names(op.getByteOffset()) + ", len(" + buffer + ")):]";
    }

    [[nodiscard]] std::string loadScalar(mlir::dsdl::LoadScalarOp /*op*/, const ValueNames& /*names*/) const override
    {
        // A body's size reaches Python as its buffer's length and a second result.
        llvm::report_fatal_error("Python spelling: a size pointer reaches Python only folded");
    }

    void storeScalar(SourceWriter& /*w*/, mlir::dsdl::StoreScalarOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("Python spelling: a size pointer reaches Python only folded");
    }

    [[nodiscard]] std::string local(SourceWriter& /*w*/,
                                    mlir::dsdl::LocalOp /*op*/,
                                    const llvm::StringRef /*name*/,
                                    const ValueNames& /*names*/) const override
    {
        // A body's only local is the size of a nested call, which reaches Python folded to
        // `dsdl.call_serdes_sized`.
        llvm::report_fatal_error("Python spelling: a local reaches Python only as a nested call's size");
    }

    [[nodiscard]] std::string loadMember(mlir::dsdl::LoadMemberOp op, const ValueNames& names) const override
    {
        return loadedValue(memberAccess(op.getObject(), op.getMember(), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeMember(SourceWriter& w, mlir::dsdl::StoreMemberOp op, const ValueNames& names) const override
    {
        line(w,
             memberAccess(op.getObject(), op.getMember(), names) + " = " +
                 storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())));
    }

    [[nodiscard]] std::string loadElement(mlir::dsdl::LoadElementOp op, const ValueNames& names) const override
    {
        return loadedValue(elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeElement(SourceWriter& w, mlir::dsdl::StoreElementOp op, const ValueNames& names) const override
    {
        line(w,
             elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names) + " = " +
                 storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())));
    }

    [[nodiscard]] std::string memberAddr(mlir::dsdl::MemberAddrOp op, const ValueNames& names) const override
    {
        return memberAccess(op.getObject(), op.getMember(), names);
    }

    [[nodiscard]] std::string elementAddr(mlir::dsdl::ElementAddrOp op, const ValueNames& names) const override
    {
        return elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names);
    }

    [[nodiscard]] std::string arrayLength(mlir::dsdl::ArrayLengthOp op, const ValueNames& names) const override
    {
        return "len(" + memberAccess(op.getObject(), op.getMember(), names) + ")";
    }

    void setArrayLength(SourceWriter& w, mlir::dsdl::SetArrayLengthOp op, const ValueNames& names) const override
    {
        // Sized to the count the plan validated, with default elements for the plan to store into.
        const Member member = memberOf(op.getObject(), op.getMember());
        line(w, memberAccess(op.getObject(), op.getMember(), names) + " = " + arrayOf(member, names(op.getValue())));
    }

    [[nodiscard]] std::string unionTag(mlir::dsdl::UnionTagOp op, const ValueNames& names) const override
    {
        return "int(" + names(op.getObject()) + "." + unionTagMemberName(Language::Python).str() + ")";
    }

    void setUnionTag(SourceWriter& w, mlir::dsdl::SetUnionTagOp op, const ValueNames& names) const override
    {
        // The object becomes the option the tag names, holding that option's default for the
        // plan to store into: an option that is an object or an array is the storage the plan
        // addresses.
        const Plan&       plan   = planOf(op.getObject());
        const std::string object = names(op.getObject());
        const std::string tag    = names(op.getValue());
        line(w, object + "." + unionTagMemberName(Language::Python).str() + " = " + tag);
        bool first = true;
        for (const std::string& name : plan.order)
        {
            const Member&     member = plan.members.find(name)->second;
            mlir::dsdl::IOOp  io     = member.io;
            const std::string test   = "if " + tag + " == " + std::to_string(io.getUnionOptionIndex()) + ":";
            if (first)
            {
                open(w, test);
            }
            else
            {
                w.midway("el" + test);
                blockEmpty_ = true;
            }
            first = false;
            line(w, object + "." + member.pyName + " = " + defaultOf(member));
        }
        if (!first)
        {
            closeBlock(w);
        }
    }

    [[nodiscard]] std::string writeBits(mlir::dsdl::WriteBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string width     = std::to_string(op.getWidth());
        const std::string value     = names(op.getValue());
        const std::string prefix    = names(op.getBuffer()) + ", " + names(op.getBitOffset()) + ", ";
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return file_.runtime() + ".write_float(" + prefix + width + ", " + value + ")";
        }
        if (isBool(valueType))
        {
            return file_.runtime() + ".set_bit(" + prefix + value + ")";
        }
        return file_.runtime() + (op.getIsSigned() ? ".write_signed(" : ".write_unsigned(") + prefix + width + ", " +
               value + ", False)";
    }

    [[nodiscard]] std::string readBits(mlir::dsdl::ReadBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string arguments =
            names(op.getBuffer()) + ", " + names(op.getBitOffset()) + ", " + std::to_string(op.getWidth());
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return file_.runtime() + ".read_float(" + arguments + ")";
        }
        const std::string read =
            file_.runtime() + (op.getIsSigned() ? ".read_signed(" : ".read_unsigned(") + arguments + ")";
        return cast(read, mlir::IntegerType::get(op.getContext(), 64), valueType);
    }

    void bitWrite(SourceWriter& /*w*/, mlir::dsdl::BitWriteOp /*op*/, const ValueNames& /*names*/) const override
    {
        // A bool array holds a bool per element, so each of its runs reaches Python expanded.
        llvm::report_fatal_error("Python spelling: a bool run reaches Python expanded to dsdl.write_bit");
    }

    void bitRead(SourceWriter& /*w*/, mlir::dsdl::BitReadOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("Python spelling: a bool run reaches Python expanded to dsdl.read_bit");
    }

    void writeBit(SourceWriter& w, mlir::dsdl::WriteBitOp op, const ValueNames& names) const override
    {
        line(w,
             file_.runtime() + ".set_bit(" + names(op.getBuffer()) + ", " + names(op.getBitOffset()) + ", " +
                 names(op.getValue()) + ")");
    }

    [[nodiscard]] std::string readBit(mlir::dsdl::ReadBitOp op, const ValueNames& names) const override
    {
        return file_.runtime() + ".get_bit(" + names(op.getBuffer()) + ", " + names(op.getBitOffset()) + ")";
    }

    void imageRead(SourceWriter& /*w*/, mlir::dsdl::ImageReadOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("Python spelling: a host-image move is not spelled here, and the fold that "
                                 "produces one does not run for this target");
    }

    void imageWrite(SourceWriter& /*w*/, mlir::dsdl::ImageWriteOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("Python spelling: a host-image move is not spelled here, and the fold that "
                                 "produces one does not run for this target");
    }

    // A view member is a slice of the buffer's memoryview, or one element of a list of them.
    /// @brief A view member, or the element of an array of views that @p index names.
    std::string viewTarget(const mlir::Value     object,
                           const llvm::StringRef member,
                           const mlir::Value     index,
                           const ValueNames&     names) const
    {
        return index ? elementAccess(object, member, names(index), names) : memberAccess(object, member, names);
    }

    [[nodiscard]] std::string viewBytes(mlir::dsdl::LoadViewOp op, const ValueNames& names) const override
    {
        return viewTarget(op.getObject(), op.getMember(), op.getIndex(), names);
    }

    [[nodiscard]] std::string viewSize(mlir::dsdl::LoadViewOp op, const ValueNames& names) const override
    {
        return "len(" + viewTarget(op.getObject(), op.getMember(), op.getIndex(), names) + ")";
    }

    void storeView(SourceWriter& w, mlir::dsdl::StoreViewOp op, const ValueNames& names) const override
    {
        const std::string bytes = names(op.getBytes());
        line(w,
             viewTarget(op.getObject(), op.getMember(), op.getIndex(), names) + " = " + bytes + "[:min(" +
                 names(op.getSizeBytes()) + ", len(" + bytes + "))]");
    }

    void clearView(SourceWriter& w, mlir::dsdl::ClearViewOp op, const ValueNames& names) const override
    {
        // A fixed array of views is every element empty; a variable-length one is sized by the plan.
        mlir::dsdl::IOOp io = memberOf(op.getObject(), op.getMember()).io;
        line(w,
             memberAccess(op.getObject(), op.getMember(), names) + " = " +
                 ((io.getArrayKind() == "fixed")
                      ? "[memoryview(b\"\") for _ in range(" + std::to_string(io.getArrayCapacity()) + ")]"
                      : "memoryview(b\"\")"));
    }

    void copyBytes(SourceWriter& w, mlir::dsdl::CopyBytesOp op, const ValueNames& names) const override
    {
        // What the view holds, up to the width, then zeros to the width. The plan's capacity check
        // established the width at the destination.
        const std::string destination = names(op.getDestination());
        const std::string source      = names(op.getSource());
        const std::string width       = std::to_string(op.getBytes());
        line(w, "_n = min(" + names(op.getSourceSizeBytes()) + ", len(" + source + "), " + width + ")");
        line(w, destination + "[:_n] = " + source + "[:_n]");
        line(w, destination + "[_n:" + width + "] = bytes(" + width + " - _n)");
    }

    [[nodiscard]] std::string callSerdes(mlir::dsdl::CallSerdesOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("Python spelling: a nested call reaches Python folded to dsdl.call_serdes_sized");
    }

    void declareCallSerdes(SourceWriter& /*w*/,
                           const llvm::StringRef /*name*/,
                           mlir::dsdl::CallSerdesOp /*op*/,
                           const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("Python spelling: a nested call reaches Python folded to dsdl.call_serdes_sized");
    }

    void declareCallSerdesSized(SourceWriter&                 w,
                                const llvm::StringRef         error,
                                const llvm::StringRef         consumed,
                                mlir::dsdl::CallSerdesSizedOp op,
                                const ValueNames&             names) const override
    {
        // The nested value serialises itself into the slice from the buffer's offset, which ends
        // where the space the plan offers does or the buffer does, and answers what it used or a
        // negative code. What it used means something only where the code is zero, so it holds
        // the answer as it came, and the code is read off it.
        const std::string call = names(op.getObject()) + "." + nestedEntry(op.getObject(), op.getDirection()) + "(" +
                                 names(op.getBuffer()) + "[:" + names(op.getAvailable()) + "])";
        if (consumed.empty() && error.empty())
        {
            discard(w, call);
            return;
        }
        if (consumed.empty())
        {
            declare(w, op.getError().getType(), error, "min(" + call + ", 0)");
            return;
        }
        declare(w, op.getConsumed().getType(), consumed, call);
        if (!error.empty())
        {
            declare(w, op.getError().getType(), error, consumed.str() + " if " + consumed.str() + " < 0 else 0");
        }
    }

private:
    struct Member final
    {
        /// @brief The attribute's name; empty in an accessors-only run, which declares none.
        std::string      pyName;
        mlir::dsdl::IOOp io;
    };

    /// @brief A type a body names, by the definition it is a section of.
    struct NestedType final
    {
        std::string  section;
        SchemaSymbol schema;
    };

    /// @brief The method of the type @p object points at that the body for @p direction is.
    [[nodiscard]] const std::string& nestedEntry(const mlir::Value object, const llvm::StringRef direction) const
    {
        const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(object.getType());
        const auto identity =
            pointer ? mlir::dyn_cast<mlir::dsdl::ObjectType>(pointer.getPointee()) : mlir::dsdl::ObjectType{};
        const auto found = identity ? types_.find(identity.getIdentity()) : types_.end();
        if (found == types_.end())
        {
            llvm::report_fatal_error("Python spelling: an object of a type the surface does not declare");
        }
        const NestedType&  type     = found->second;
        const PlanFunction function = (direction == "serialize") ? PlanFunction::Serialize : PlanFunction::Deserialize;
        return names_.function(renderPlanSymbol(planFunction(type.schema.fullName,
                                                             type.schema.major,
                                                             type.schema.minor,
                                                             type.section,
                                                             function)),
                               SurfaceDeclKind::Entry);
    }

    struct Plan final
    {
        llvm::StringMap<Member>  members;
        std::vector<std::string> order;
    };

    // Python has no empty block: a block that spelled no statement closes with `pass`.

    void open(SourceWriter& w, const std::string& text) const
    {
        w.open(text);
        blockEmpty_ = true;
    }

    void line(SourceWriter& w, const std::string& text) const
    {
        w.line(text);
        blockEmpty_ = false;
    }

    /// @brief The plan the object a pointer names belongs to.
    const Plan& planOf(const mlir::Value object) const
    {
        const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(object.getType());
        const auto identity =
            pointer ? mlir::dyn_cast<mlir::dsdl::ObjectType>(pointer.getPointee()) : mlir::dsdl::ObjectType{};
        const auto found = identity ? plans_.find(identity.getIdentity()) : plans_.end();
        if (found == plans_.end())
        {
            llvm::report_fatal_error("Python spelling: an object that no plan of this schema describes");
        }
        return found->second;
    }

    Member memberOf(const mlir::Value object, const llvm::StringRef member) const
    {
        const Plan& plan  = planOf(object);
        const auto  found = plan.members.find(member);
        if (found == plan.members.end())
        {
            llvm::report_fatal_error("Python spelling: a member the schema does not declare: " + member);
        }
        return found->second;
    }

    std::string memberAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        return names(object) + "." + memberOf(object, member).pyName;
    }

    std::string elementAccess(const mlir::Value     object,
                              const llvm::StringRef member,
                              const std::string&    index,
                              const ValueNames&     names) const
    {
        return memberAccess(object, member, names) + "[" + index + "]";
    }

    // Members.

    /// @brief The kind of value a member or element holds.
    enum class Storage : std::uint8_t
    {
        Boolean,
        Integer,
        Float,
        Object,
    };

    static Storage storageOf(const Member& member)
    {
        mlir::dsdl::IOOp      io       = member.io;
        const llvm::StringRef category = io.getScalarCategory();
        if (io.isComposite())
        {
            return Storage::Object;
        }
        if (category == "bool")
        {
            return Storage::Boolean;
        }
        if (category == "float")
        {
            return Storage::Float;
        }
        return Storage::Integer;
    }

    /// @brief The default value of one element of @p member, or of the member when it is no array.
    std::string elementDefault(const Member& member) const
    {
        if (mlir::dsdl::IOOp{member.io}.getHeldAsView())
        {
            return "memoryview(b\"\")";
        }
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return "False";
        case Storage::Integer:
            return "0";
        case Storage::Float:
            return "0.0";
        case Storage::Object:
            break;
        }
        mlir::dsdl::IOOp io = member.io;
        return file_.type(io.getCompositeFullName().value_or(llvm::StringRef{}),
                          static_cast<std::uint32_t>(io.getCompositeMajor().value_or(0)),
                          static_cast<std::uint32_t>(io.getCompositeMinor().value_or(0))) +
               "()";
    }

    /// @brief A list of @p count default elements of @p member.
    std::string arrayOf(const Member& member, const std::string& count) const
    {
        if (storageOf(member) == Storage::Object)
        {
            return "[" + elementDefault(member) + " for _ in range(" + count + ")]";
        }
        return "[" + elementDefault(member) + "] * " + count;
    }

    /// @brief The default value of @p member.
    std::string defaultOf(const Member& member) const
    {
        mlir::dsdl::IOOp io = member.io;
        if (!io.isArray())
        {
            return elementDefault(member);
        }
        if (io.isVariableArray())
        {
            return "[]";
        }
        return arrayOf(member, std::to_string(io.getArrayCapacity()));
    }

    /// @brief @p access read as a value of @p type.
    static std::string loadedValue(const std::string& access, const Member& member, const mlir::Type type)
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return isBool(type) ? "bool(" + access + ")" : "int(" + access + ")";
        case Storage::Integer:
            // A number a caller stored may be no integer; it is read as one.
            return isBool(type) ? "(" + access + " != 0)" : "int(" + access + ")";
        case Storage::Float:
            return "float(" + access + ")";
        case Storage::Object:
            break;
        }
        return access;
    }

    /// @brief @p value, of @p type, converted for storage in @p member.
    static std::string storedValue(const std::string& value, const mlir::Type type, const Member& member)
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return isBool(type) ? value : value + " != 0";
        case Storage::Integer:
            return isBool(type) ? "int(" + value + ")" : value;
        case Storage::Float:
        case Storage::Object:
            break;
        }
        return value;
    }

    // Types.

    static bool isBool(const mlir::Type type)
    {
        return type.isInteger(1);
    }

    /// @brief @p value, of @p from, as a value of @p to.
    static std::string cast(const std::string& value, const mlir::Type from, const mlir::Type to)
    {
        if (from == to)
        {
            return value;
        }
        if (isBool(to))
        {
            return "(" + value + " != 0)";
        }
        if (isBool(from))
        {
            return "int(" + value + ")";
        }
        if (to.isInteger(8) && !from.isInteger(8))
        {
            // Truncated to eight bits and read back as the signed value they hold.
            return "(((" + value + " & 0xFF) ^ 0x80) - 0x80)";
        }
        return value;
    }

    static std::string typeName(const mlir::Type type)
    {
        if (mlir::isa<mlir::FloatType>(type))
        {
            return "float";
        }
        if (isBool(type))
        {
            return "bool";
        }
        if (mlir::isa<mlir::IndexType>(type) || mlir::isa<mlir::IntegerType>(type))
        {
            return "int";
        }
        if (const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(type))
        {
            if (mlir::isa<mlir::dsdl::ByteType>(pointer.getPointee()))
            {
                return "memoryview";
            }
            if (mlir::isa<mlir::dsdl::SizeType>(pointer.getPointee()))
            {
                return "int";
            }
        }
        llvm::report_fatal_error("Python spelling: a value of a type no plan body carries");
    }

    static std::string operatorToken(const BinaryOperator op)
    {
        switch (op)
        {
        case BinaryOperator::Add:
            return "+";
        case BinaryOperator::Sub:
            return "-";
        case BinaryOperator::Mul:
            return "*";
        case BinaryOperator::DivU:
        case BinaryOperator::DivS:
            return "//";
        case BinaryOperator::RemU:
        case BinaryOperator::RemS:
            return "%";
        case BinaryOperator::And:
            return "&";
        case BinaryOperator::Or:
            return "|";
        case BinaryOperator::Xor:
            return "^";
        case BinaryOperator::ShiftLeft:
            return "<<";
        case BinaryOperator::ShiftRightU:
        case BinaryOperator::ShiftRightS:
            return ">>";
        }
        llvm::report_fatal_error("Python spelling: an operator of an unexpected kind");
    }

    static std::string comparisonToken(const Comparison comparison)
    {
        switch (comparison)
        {
        case Comparison::Eq:
            return "==";
        case Comparison::Ne:
            return "!=";
        case Comparison::LtS:
        case Comparison::LtU:
            return "<";
        case Comparison::LeS:
        case Comparison::LeU:
            return "<=";
        case Comparison::GtS:
        case Comparison::GtU:
            return ">";
        case Comparison::GeS:
        case Comparison::GeU:
            return ">=";
        }
        llvm::report_fatal_error("Python spelling: a comparison of an unexpected kind");
    }

    /// @brief A name for a value of this spelling's own, distinct from the translator's.
    std::string fresh(const char* const stem) const
    {
        return "_" + std::string(stem) + std::to_string(fresh_++) + "_";
    }

    const PyFileNames&    file_;
    llvm::StringMap<Plan> plans_;

    /// @brief The scope the module's helper names are declared into, which keeps two that project
    ///        onto one name apart.
    const PySurface&            names_;
    llvm::StringMap<NestedType> types_;
    /// @brief The tag steps of the union plans, which belong to no plan and live here.
    std::vector<mlir::OwningOpRef<mlir::dsdl::IOOp>> tagSteps_;

    /// @brief The plan and the member an accessor reaches, through its schema and section name.
    struct Accessed final
    {
        const Plan*   plan;
        const Member* member;
    };
    Accessed accessed(mlir::func::FuncOp fn) const
    {
        auto       module     = fn->getParentOfType<mlir::ModuleOp>();
        const auto schemaSym  = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.schema_sym");
        const auto section    = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        const auto memberName = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.member");
        auto       schema =
            schemaSym ? module.lookupSymbol<mlir::dsdl::SchemaOp>(schemaSym.getValue()) : mlir::dsdl::SchemaOp{};
        if (!schema || !memberName)
        {
            llvm::report_fatal_error("Python spelling: an accessor that names no schema or no member");
        }
        const auto plan  = sectionPlan(schema, section ? section.getValue() : llvm::StringRef{});
        const auto found = plans_.find(planIdentity(schema, plan));
        if (found == plans_.end())
        {
            llvm::report_fatal_error("Python spelling: an accessor of a plan this schema does not describe");
        }
        const auto member = found->second.members.find(memberName.getValue());
        if (member == found->second.members.end())
        {
            llvm::report_fatal_error("Python spelling: an accessor of a member the plan does not declare");
        }
        return Accessed{&found->second, &member->second};
    }

    /// @brief Which accessor, if any, the function being opened is; how its return is spelt.
    enum class Accessor : std::uint8_t
    {
        None,
        Getter,
        Setter
    };
    mutable Accessor    accessor_{Accessor::None};
    mutable std::string returnCast_;
    mutable bool        blockEmpty_{false};
    mutable unsigned    fresh_{0};
    /// @brief Whether the function being spelt answers no error, which it then never raises.
    mutable bool infallible_{false};
};

/// @brief The three bodies `lower-dsdl-bodies` built for one section.
struct SectionBodies final
{
    mlir::func::FuncOp serialize;
    mlir::func::FuncOp deserialize;
    mlir::func::FuncOp initialize;
    /// @brief The section's field accessors, getters and setters, in the module's order.
    std::vector<mlir::func::FuncOp> accessors;
};

/// @brief One section: its class with the two bodies and the methods that wrap them, then its
/// constants.
llvm::Error emitSection(SourceWriter&             w,
                        const PySection&          names,
                        const SemanticSection&    section,
                        const SectionMetadata&    metadata,
                        const AttachedDoc&        typeDoc,
                        const PyFileNames&        file,
                        const SemanticDefinition& def,
                        const PythonSpelling&     spelling,
                        const SectionBodies&      bodies,
                        PlanBodyLookups&          lookups)
{
    // An accessors-only run has no bodies: a bare class carries the accessors as static methods.
    if (file.context().accessorsOnly())
    {
        emitAttachedDocPy(w,
                          docWithDeprecationNotice(typeDoc,
                                                   section.deprecated,
                                                   def.info.fullName,
                                                   def.info.majorVersion,
                                                   def.info.minorVersion));
        w.open("class " + names.typeName() + ":");
    }
    else
    {
        if (!bodies.serialize || !bodies.deserialize || !bodies.initialize)
        {
            return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                           "no plan bodies for %s in the lowered module",
                                           def.info.fullName.c_str());
        }
        auto init = readInitializer(bodies.initialize);
        if (!init)
        {
            return init.takeError();
        }
        emitSectionType(w,
                        *init,
                        names,
                        section,
                        typeDoc,
                        file,
                        def.info.fullName,
                        def.info.majorVersion,
                        def.info.minorVersion);
        w.blank();
        if (auto err = translateFunction(bodies.serialize, spelling, w, lookups))
        {
            return err;
        }
        w.blank();
        if (auto err = translateFunction(bodies.deserialize, spelling, w, lookups))
        {
            return err;
        }
    }
    // A wire-flat section's field accessors: each is one read or one write at the field's offset.
    for (const mlir::func::FuncOp accessor : bodies.accessors)
    {
        w.blank();
        if (auto err = translateFunction(accessor, spelling, w, lookups))
        {
            return err;
        }
    }
    w.dedent();
    if (metadata.isUnion)
    {
        w.blank();
        emitUnionOptionTags(w, names, metadata);
    }
    if (!section.constants.empty())
    {
        w.blank();
        emitSectionConstants(w, names, section);
    }
    return llvm::Error::success();
}

llvm::Expected<std::string> renderDefinitionFile(const SemanticDefinition& def,
                                                 const EmitterContext&     ctx,
                                                 mlir::ModuleOp            module,
                                                 PlanBodyLookups&          lookups)
{
    mlir::dsdl::SchemaOp schema = schemaOf(module, def);
    if (!schema)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no schema for %s in the lowered module",
                                       def.info.fullName.c_str());
    }

    std::ostringstream out;
    SourceWriter       head = makePyWriter(out);
    head.line(generatedCommentLine("Python backend"));
    head.line("# Source: " + def.info.fullName + "." + std::to_string(def.info.majorVersion) + "." +
              std::to_string(def.info.minorVersion));
    head.line("from __future__ import annotations");
    head.blank();

    // The file is rendered first and its imports written after, from what it named.
    const PySurface&   names = ctx.names();
    const std::string  key   = keyOf(def.info);
    ImportSet          imports;
    const PyFileNames  file(ctx, imports, key);
    std::ostringstream body;
    SourceWriter       w        = makePyWriter(body);
    const auto         assemble = [&]() -> std::string {
        out << renderPythonImports(imports) << body.str();
        return out.str();
    };
    const auto constant = [&names, &key](const GeneratedFact fact, const llvm::StringRef section = {}) {
        return names.declared(key, SurfaceDeclKind::Constant, section, {}, fact);
    };
    w.line(constant(GeneratedFact::GeneratorVersion) + " = \"" + std::string(llvmdsdl::kVersionString) + "\"");
    w.line(constant(GeneratedFact::FullName) + " = \"" + def.info.fullName + "\"");
    w.line(constant(GeneratedFact::IsDeprecated) + " = " + std::string(def.request.deprecated ? "True" : "False"));
    w.line(constant(GeneratedFact::VersionMajor) + " = " + std::to_string(def.info.majorVersion));
    w.line(constant(GeneratedFact::VersionMinor) + " = " + std::to_string(def.info.minorVersion));
    w.line(constant(GeneratedFact::HasFixedPortId) + " = " + std::string(def.info.fixedPortId ? "True" : "False"));
    if (def.info.fixedPortId)
    {
        w.line(constant(GeneratedFact::FixedPortId) + " = " + std::to_string(*def.info.fixedPortId));
    }
    // Aliasability is a property of a payload, so a service answers for each of its two and a
    // message answers once, under the name of the thing the verdict is about.
    const auto emitLayoutVerdicts = [&w, &constant, schema](const llvm::StringRef section) {
        const mlir::dsdl::SerializationPlanOp plan = sectionPlan(schema, section);
        const AliasVerdict                    flat = wireFlatVerdict(plan);
        w.line(constant(GeneratedFact::WireFlat, section) + " = " + std::string(flat.holds ? "True" : "False"));
        w.line(constant(GeneratedFact::WireFlatReason, section) + " = \"" + flat.reason + "\"");
    };
    if (def.isService)
    {
        emitLayoutVerdicts("request");
        emitLayoutVerdicts("response");
    }
    else
    {
        emitLayoutVerdicts("");
    }
    w.blank();

    // The spelling names a nested type and the runtime as this file does.
    const PythonSpelling                 spelling(schema, names, file);
    std::vector<mlir::func::FuncOp>      helpers;
    std::map<std::string, SectionBodies> bodies;
    for (const mlir::func::FuncOp fn : schemaFunctions(module, schema.getSymName()))
    {
        const auto direction = planBodyDirection(fn);
        if (!direction)
        {
            // A helper nothing calls is left out; an accessors-only run has many.
            if (fn->hasAttr("llvmdsdl.unreferenced"))
            {
                continue;
            }
            helpers.push_back(fn);
            continue;
        }
        const auto     sectionAttr = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        SectionBodies& entry       = bodies[sectionAttr ? sectionAttr.getValue().str() : std::string{}];
        if (*direction == "serialize")
        {
            entry.serialize = fn;
        }
        else if (*direction == "deserialize")
        {
            entry.deserialize = fn;
        }
        else if (*direction == "initialize")
        {
            entry.initialize = fn;
        }
        else if (*direction == "get" || *direction == "set")
        {
            entry.accessors.push_back(fn);
        }
        else
        {
            llvm::report_fatal_error(llvm::Twine("unknown plan body direction '") + *direction + "'");
        }
    }
    for (const mlir::func::FuncOp helper : helpers)
    {
        if (auto err = translateFunction(helper, spelling, w, lookups))
        {
            return std::move(err);
        }
        w.blank();
    }

    if (!def.isService)
    {
        if (auto err = emitSection(w,
                                   PySection(names, key, ""),
                                   def.request,
                                   sectionMetadata(def.info, def.request, schema, ""),
                                   def.doc,
                                   file,
                                   def,
                                   spelling,
                                   bodies[""],
                                   lookups))
        {
            return std::move(err);
        }
        return assemble();
    }

    const PySection request(names, key, "request");
    if (auto err = emitSection(w,
                               request,
                               def.request,
                               sectionMetadata(def.info, def.request, schema, "request"),
                               def.doc,
                               file,
                               def,
                               spelling,
                               bodies["request"],
                               lookups))
    {
        return std::move(err);
    }
    w.blank();
    if (def.response)
    {
        if (auto err = emitSection(w,
                                   PySection(names, key, "response"),
                                   *def.response,
                                   sectionMetadata(def.info, *def.response, schema, "response"),
                                   def.doc,
                                   file,
                                   def,
                                   spelling,
                                   bodies["response"],
                                   lookups))
        {
            return std::move(err);
        }
        w.blank();
    }
    if (const SurfaceDecl* const alias =
            names.tree().find(names.file(key), SurfaceDeclKind::Alias, SurfaceEntity{key, "", "", ""}))
    {
        w.line(alias->name + " = " + request.typeName());
    }
    return assemble();
}

llvm::Expected<std::string> loadRuntimeFile(const std::string& fileName)
{
    if (const auto data = embedded_sources::find("python/" + fileName))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "embedded runtime source missing: python/%s",
                                   fileName.c_str());
}

/// @brief Returns the runtime scaffold file name for a Python specialisation.
/// @param[in] runtimeSpecialization Runtime specialisation profile.
/// @return Source runtime scaffold file name under `runtime/python`.
std::string runtimeFileForSpecialization(const RuntimeSpecialization runtimeSpecialization)
{
    if (runtimeSpecialization == RuntimeSpecialization::Fast)
    {
        return "_dsdl_runtime_fast.py";
    }
    return "_dsdl_runtime.py";
}

/// @brief Renders the body of one generated `__init__.py`.
///
/// @details
/// Several Python build backends read a package's docstring and `__version__` as its metadata, and
/// flit refuses outright to package a module without a docstring -- so a package that omits them is
/// one a user cannot build with the backend of their choice.
/// The leading generated-by comment stays where it is: a comment is not a statement, so the
/// docstring is still the module's first statement and still its `__doc__`.
///
/// `__version__` is the generator's version, the version a generated package can claim.
std::string renderInitFile(llvm::StringRef dottedName, const bool isPackageRoot)
{
    std::ostringstream out;
    out << generatedCommentLine("Python backend") << "\n";
    if (isPackageRoot)
    {
        out << R"("""Generated DSDL types, rooted at the `)" << dottedName.str() << "` package.\"\"\"\n";
        out << "\n";
        out << "__version__ = \"" << llvmdsdl::kVersionString << "\"\n";
    }
    else
    {
        out << R"("""Generated DSDL types under `)" << dottedName.str() << "`.\"\"\"\n";
    }
    return out.str();
}

llvm::Error ensureInitFile(const std::filesystem::path&     outRoot,
                           const llvm::StringRef            path,
                           const bool                       isPackageRoot,
                           std::set<std::filesystem::path>& initializedPackages,
                           const EmitWritePolicy&           writePolicy)
{
    const std::filesystem::path initPath = outRoot / path.str();
    if (!initializedPackages.insert(initPath).second)
    {
        return llvm::Error::success();
    }
    std::error_code ec;
    if (!std::filesystem::exists(initPath, ec))
    {
        if (auto err = writeGeneratedFile(initPath, renderInitFile(packageOfInit(path), isPackageRoot), writePolicy))
        {
            return err;
        }
    }
    return llvm::Error::success();
}

/// @brief Writes the `__init__.py` of the package and of each namespace down to the module scope
///        @p file, where none exists.
llvm::Error ensurePackageInitChain(const std::filesystem::path&     outRoot,
                                   const PySurface&                 names,
                                   const std::optional<std::size_t> file,
                                   std::set<std::filesystem::path>& initializedPackages,
                                   const EmitWritePolicy&           writePolicy)
{
    if (auto err = ensureInitFile(outRoot, names.rootFile(), true, initializedPackages, writePolicy))
    {
        return err;
    }
    if (!file)
    {
        return llvm::Error::success();
    }
    for (const std::size_t scope : names.tree().pathTo(*file))
    {
        const SurfaceScope& namespaceScope = names.tree().scope(scope);
        if (namespaceScope.kind != SurfaceScopeKind::Namespace)
        {
            continue;
        }
        if (auto err = ensureInitFile(outRoot, namespaceScope.path, false, initializedPackages, writePolicy))
        {
            return err;
        }
    }
    return llvm::Error::success();
}

}  // namespace

llvm::Error emit(const SemanticModule& semantic, mlir::ModuleOp module, const Options& options)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }

    auto tree = SurfaceTree::read(module, languageTraits(Language::Python));
    if (!tree)
    {
        return tree.takeError();
    }
    const PySurface      names(*tree);
    const EmitterContext ctx(semantic, names, options.accessorsOnly);

    std::filesystem::path const outRoot(options.outDir);
    const auto                  selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }
    const bool emitSupport = shouldEmitSupport(options.supportGeneration, anyTypeEmitted);

    const std::filesystem::path packageRoot = outRoot / llvm::StringRef(names.rootFile()).rsplit('/').first.str();

    // Shared with the per-definition emission below, which creates any package chain a type needs.
    // Generated modules stay importable under `never` even though the scaffolding is skipped here.
    std::set<std::filesystem::path> initializedPackages;

    if (emitSupport)
    {
        if (auto err = ensurePackageInitChain(outRoot, names, std::nullopt, initializedPackages, options.writePolicy))
        {
            return err;
        }

        auto runtime = loadRuntimeFile(runtimeFileForSpecialization(options.runtimeSpecialization));
        if (!runtime)
        {
            return runtime.takeError();
        }
        if (auto err = writeGeneratedFile(packageRoot / "_dsdl_runtime.py",
                                          generatedCommentLine("Python runtime scaffold") + "\n\n" + *runtime,
                                          options.writePolicy))
        {
            return err;
        }

        auto runtimeLoader = loadRuntimeFile("_runtime_loader.py");
        if (!runtimeLoader)
        {
            return runtimeLoader.takeError();
        }
        if (auto err = writeGeneratedFile(packageRoot / "_runtime_loader.py",
                                          generatedCommentLine("Python runtime loader") + "\n\n" + *runtimeLoader,
                                          options.writePolicy))
        {
            return err;
        }

        if (auto err = writeGeneratedFile(packageRoot / "llvmdsdl_codegen.json",
                                          renderPackageMetadata(options),
                                          options.writePolicy))
        {
            return err;
        }

        if (auto err = writeGeneratedFile(outRoot / "pyproject.toml",
                                          renderPyProjectToml(names.package(),
                                                              llvm::StringRef(names.package()).split('.').first),
                                          options.writePolicy))
        {
            return err;
        }

        if (auto err = writeGeneratedFile(packageRoot / "py.typed", "", options.writePolicy))
        {
            return err;
        }
    }

    std::vector<const SemanticDefinition*> ordered;
    ordered.reserve(semantic.definitions.size());
    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        ordered.push_back(&def);
    }
    std::ranges::sort(ordered, [](const auto* lhs, const auto* rhs) {
        if (lhs->info.fullName != rhs->info.fullName)
        {
            return lhs->info.fullName < rhs->info.fullName;
        }
        if (lhs->info.majorVersion != rhs->info.majorVersion)
        {
            return lhs->info.majorVersion < rhs->info.majorVersion;
        }
        return lhs->info.minorVersion < rhs->info.minorVersion;
    });

    PlanBodyLookups lookups(module);
    for (const auto* def : ordered)
    {
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def->info)};
        const std::string              key = keyOf(def->info);
        if (auto err =
                ensurePackageInitChain(outRoot, names, names.file(key), initializedPackages, options.writePolicy))
        {
            return err;
        }

        auto rendered = renderDefinitionFile(*def, ctx, module, lookups);
        if (!rendered)
        {
            return rendered.takeError();
        }

        if (auto err = writeGeneratedFile(outRoot / names.path(key), *rendered, options.writePolicy, requiredTypeKeys))
        {
            return err;
        }
    }

    return llvm::Error::success();
}

}  // namespace llvmdsdl::emitter::python
