//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Writes the packaging files of a generated Python package.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/emitter/PythonPackaging.h"

#include <sstream>
#include <string>

#include <llvm/ADT/StringRef.h>

#include "llvmdsdl/CodeGen/emitter/Python.h"
#include "llvmdsdl/Support/Language.h"
#include "llvmdsdl/Support/LanguageTraits.h"
#include "llvmdsdl/Version.h"

namespace llvmdsdl::emitter::python
{

std::string renderPackageMetadata(const Options& options)
{
    std::ostringstream out;
    out << "{\n";
    out << "  \"llvmdsdl\": {\n";
    out << R"(    "generatorVersion": ")" << llvmdsdl::kVersionString << "\",\n";
    out << R"(    "pythonRuntimeSpecialization": ")";
    out << (options.runtimeSpecialization == RuntimeSpecialization::Fast ? "fast" : "portable");
    out << "\"\n";
    out << "  }\n";
    out << "}\n";
    return out.str();
}

std::string renderPyProjectToml(llvm::StringRef packageName, llvm::StringRef rootPackageName)
{
    std::ostringstream out;
    out << "[build-system]\n";
    out << "requires = [\"setuptools>=61\"]\n";
    out << "build-backend = \"setuptools.build_meta\"\n\n";

    out << "[project]\n";
    out << "name = \"" << packageName.str() << "\"\n";
    out << "version = \"" << llvmdsdl::kVersionString << "\"\n";
    out << "description = \"Generated by llvmdsdl\"\n";
    out << "requires-python = \">=3.10\"\n\n";

    // The length the output keeps its lines to, stated where the language's formatter reads it.
    if (const unsigned length = languageTraits(Language::Python).composition.lineLength; length > 0)
    {
        out << "[tool.ruff]\n";
        out << "line-length = " << length << "\n\n";
    }

    out << "[tool.setuptools]\n";
    out << "include-package-data = true\n\n";

    out << "[tool.setuptools.packages.find]\n";
    out << "where = [\".\"]\n";
    out << "include = [\"" << rootPackageName.str() << "*\"]\n\n";

    out << "[tool.setuptools.package-data]\n";
    out << "\"" << packageName.str() << R"(" = ["py.typed", "_dsdl_runtime_accel*.so", )"
        << "\"_dsdl_runtime_accel*.dylib\", \"_dsdl_runtime_accel*.pyd\"]\n";
    return out.str();
}

}  // namespace llvmdsdl::emitter::python
