//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements Rust backend code emission from lowered DSDL modules.
///
/// The file maps lowering facts to Rust data types and serdes routines across supported runtime profiles.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/BodyTranslator.h"
#include "llvmdsdl/CodeGen/EmitCommon.h"
#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/EmbeddedRuntimeSources.h"
#include "llvmdsdl/CodeGen/emitter/Rust.h"

#include <llvm/ADT/StringRef.h>
#include <llvm/Support/Error.h>
#include <filesystem>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <utility>
#include <variant>

#include "llvmdsdl/CodeGen/CodegenDiagnosticText.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionDependencies.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/CodeGen/LoweredFactsLookup.h"
#include "llvmdsdl/CodeGen/MlirLoweredFacts.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/HelperBindingNaming.h"
#include "llvmdsdl/CodeGen/StorageTypeTokens.h"
#include "llvmdsdl/CodeGen/TypeStorage.h"
#include "llvmdsdl/CodeGen/WireLayoutFacts.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/CodeGen/SourceWriter.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Version.h"
#include "llvmdsdl/IR/DSDLOps.h"
#include "llvmdsdl/IR/DSDLTypes.h"
#include "llvmdsdl/Transforms/PlanSteps.h"
#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/STLExtras.h>
#include <llvm/ADT/StringExtras.h>
#include <llvm/ADT/StringMap.h>
#include <llvm/Support/ErrorHandling.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/IR/Attributes.h>
#include <mlir/IR/BuiltinAttributeInterfaces.h>
#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/BuiltinTypeInterfaces.h>
#include <mlir/IR/BuiltinTypes.h>
#include <mlir/IR/SymbolTable.h>
#include <mlir/IR/Types.h>
#include <mlir/IR/Value.h>
#include <mlir/Support/LLVM.h>
#include <iomanip>
#include <limits>
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl::emitter::rust
{

namespace
{

std::string rustMemoryModeVariantPath(const Options& options)
{
    if (options.memoryMode == MemoryMode::InlineThenPool)
    {
        return "crate::dsdl_runtime::DsdlMemoryMode::InlineThenPool";
    }
    return "crate::dsdl_runtime::DsdlMemoryMode::MaxInline";
}

std::string unsignedStorageType(const std::uint32_t bitLength)
{
    return renderUnsignedStorageToken(StorageTokenLanguage::Rust, bitLength);
}

std::string signedStorageType(const std::uint32_t bitLength)
{
    return renderSignedStorageToken(StorageTokenLanguage::Rust, bitLength);
}

std::string rustConstValue(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(ConstantLiteralLanguage::Rust, value, makeConstantTypeInfo(type));
}

SourceWriter makeRustWriter(std::ostringstream& out)
{
    return SourceWriter{out, IndentPolicy::spaces(4)};
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return "// Generated by llvmdsdl " + std::string(llvmdsdl::kVersionString) + " (" + detail.str() + ").";
}

void emitAttachedDocRust(SourceWriter& w, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        w.line(line.text.empty() ? std::string{"///"} : "/// " + line.text);
    }
}

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule& semantic, const TypeNameVersioning typeNameVersioning)
        : index_(semantic)
        , typeNameVersioning_(typeNameVersioning)
    {
    }

    /// @brief Whether generated type names carry the definition's version.
    TypeNameVersioning typeNameVersioning() const
    {
        return typeNameVersioning_;
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

    static std::string rustModuleName(const DiscoveredDefinition& info)
    {
        return renderDefinitionFileStem(CodegenNamingLanguage::Rust,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion);
    }

    std::string rustTypeName(const DiscoveredDefinition& info) const
    {
        return renderDefinitionTypeName(CodegenNamingLanguage::Rust,
                                        info.namespaceComponents,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion,
                                        typeNameVersioning_);
    }

    std::string rustTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return rustTypeName(def->info);
        }

        DiscoveredDefinition tmp;
        tmp.shortName           = ref.shortName;
        tmp.namespaceComponents = ref.namespaceComponents;
        tmp.majorVersion        = ref.majorVersion;
        tmp.minorVersion        = ref.minorVersion;
        return rustTypeName(tmp);
    }

    /// @brief The name @p def's struct is declared under; see renderDeclaredTypeName.
    std::string rustDeclaredTypeName(const SemanticDefinition& def) const
    {
        return renderDeclaredTypeName(rustTypeName(def.info), def.request.deprecated);
    }

    /// @brief The declared name of the definition @p ref names, for spelling its type.
    ///
    /// A reference that resolves to nothing is spelled with its public name: nothing says it is
    /// deprecated.
    std::string rustDeclaredTypeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return rustDeclaredTypeName(*def);
        }
        return rustTypeName(ref);
    }

    /// @brief The `use` path of the struct the definition @p ref names.
    std::string rustTypePath(const SemanticTypeRef& ref) const
    {
        std::ostringstream out;
        out << "crate";
        for (const auto& ns : ref.namespaceComponents)
        {
            out << "::" << codegenProjectIdentifier(CodegenNamingLanguage::Rust, IdentifierRole::NamespaceName, ns);
        }

        if (const auto* def = find(ref))
        {
            out << "::" << rustModuleName(def->info) << "::" << rustDeclaredTypeName(*def);
            return out.str();
        }

        DiscoveredDefinition tmp;
        tmp.shortName           = ref.shortName;
        tmp.namespaceComponents = ref.namespaceComponents;
        tmp.majorVersion        = ref.majorVersion;
        tmp.minorVersion        = ref.minorVersion;
        out << "::" << rustModuleName(tmp) << "::" << rustTypeName(tmp);
        return out.str();
    }

private:
    DefinitionIndex    index_;
    TypeNameVersioning typeNameVersioning_{TypeNameVersioning::Unversioned};
};

std::string rustFieldBaseType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "bool";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
        return unsignedStorageType(type.bitLength);
    case SemanticScalarCategory::SignedInt:
        return signedStorageType(type.bitLength);
    case SemanticScalarCategory::Float:
        return type.bitLength == 64 ? "f64" : "f32";
    case SemanticScalarCategory::Void:
        return "u8";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.rustDeclaredTypeName(*type.compositeType);
        }
        return "u8";
    }
    return "u8";
}

std::string rustFieldType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    auto base = rustFieldBaseType(type, ctx);
    if (type.arrayKind == ArrayKind::None)
    {
        return base;
    }
    if (type.arrayKind == ArrayKind::Fixed)
    {
        return "[" + base + "; " + std::to_string(type.arrayCapacity) + "]";
    }
    return "crate::dsdl_runtime::DsdlVec<" + base + ">";
}

std::string scalarDefaultExpr(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "false";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        return "0";
    case SemanticScalarCategory::Float:
        return type.bitLength == 64 ? "0.0f64" : "0.0f32";
    case SemanticScalarCategory::Void:
        return "0";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.rustDeclaredTypeName(*type.compositeType) + "::default()";
        }
        return "0";
    }
    return "0";
}

std::string defaultExpr(const SemanticFieldType& type, const EmitterContext& ctx)
{
    if (type.arrayKind == ArrayKind::Fixed)
    {
        const std::string element = scalarDefaultExpr(type, ctx);
        const std::string count   = std::to_string(type.arrayCapacity);
        // A composite is not `Copy`, so each element is made on its own.
        if (type.scalarCategory == SemanticScalarCategory::Composite)
        {
            return "core::array::from_fn(|_| " + element + ")";
        }
        return "[" + element + "; " + count + "]";
    }
    if (type.arrayKind != ArrayKind::None)
    {
        return "crate::dsdl_runtime::DsdlVec::new()";
    }
    return scalarDefaultExpr(type, ctx);
}

/// @brief The `#[deprecated]` attribute for a definition, carrying the shared notice as its message.
///
/// rustc prints the message after its own diagnostic, so the user sees which DSDL definition is
/// deprecated without opening the generated source. The notice's `Deprecated: ` prefix is Go's and
/// is dropped here: rustc already says "use of deprecated".
std::string rustDeprecatedAttribute(const std::string&  fullName,
                                    const std::uint32_t majorVersion,
                                    const std::uint32_t minorVersion)
{
    const std::string notice  = deprecationNotice(fullName, majorVersion, minorVersion);
    const std::string prefix  = "Deprecated: ";
    const std::string message = notice.starts_with(prefix) ? notice.substr(prefix.size()) : notice;
    return "#[deprecated(note = \"" + message + "\")]";
}

/// @brief The names of the pool-class constants of a section's variable-length arrays, by field.
///
/// The struct declares one constant per variable-length array, and a body's `set_array_length`
/// hands it to the container; both take the names from here so that they cannot disagree.
std::vector<std::pair<std::string, std::string>> poolClassConstantNames(const std::vector<std::string>& fieldNames)
{
    std::vector<std::pair<std::string, std::string>> out;
    std::set<std::string>                            used;
    for (const auto& fieldName : fieldNames)
    {
        const std::string baseName =
            "__LLVMDSDL_POOL_CLASS_" +
            codegenProjectIdentifier(CodegenNamingLanguage::Rust, IdentifierRole::ConstantName, fieldName);
        std::string constName = baseName;
        for (std::uint32_t suffix = 1U; !used.insert(constName).second; ++suffix)
        {
            constName = baseName + "_" + std::to_string(suffix);
        }
        out.emplace_back(fieldName, constName);
    }
    return out;
}

/// @brief The Rust spelling of the plan-body vocabulary, for one schema.
///
/// Members are named from the same scope the struct declaration names them in, built from the
/// schema's own fields. A nested type is never named: a nested call is a method call on the
/// member itself. The plan's `i64` is `u64`, `i8` is `i8`, and the size a plan is handed by
/// pointer is a local `usize`, which is also what a nested call's size becomes. The runtime
/// primitives take slices, so a buffer is a slice and a pointer into it is a sub-slice clamped
/// to the buffer's end.
class RustSpelling final : public BodySpelling
{
public:
    RustSpelling(mlir::ModuleOp module, mlir::dsdl::SchemaOp schema)
        : symbols_(module)
    {
        if (schema.getBody().empty())
        {
            return;
        }
        for (mlir::dsdl::SerializationPlanOp plan : schema.getBody().front().getOps<mlir::dsdl::SerializationPlanOp>())
        {
            Plan entry;
            entry.unionTagBits = plan.getUnionTagBits().value_or(0);
            NamingScope                   scope(CodegenNamingLanguage::Rust);
            std::vector<mlir::dsdl::IOOp> fields;
            std::vector<std::string>      variableArrays;
            if (!plan.getBody().empty())
            {
                for (mlir::dsdl::IOOp io : plan.getBody().front().getOps<mlir::dsdl::IOOp>())
                {
                    if (io.isPadding())
                    {
                        continue;
                    }
                    (void) scope.declare(IdentifierRole::FieldName, io.getName());
                    fields.push_back(io);
                    if (io.isVariableArray())
                    {
                        variableArrays.push_back(io.getName().str());
                    }
                }
            }
            for (const auto& [fieldName, constName] : poolClassConstantNames(variableArrays))
            {
                entry.poolClass[fieldName] = constName;
            }
            for (mlir::dsdl::IOOp io : fields)
            {
                entry.members[io.getName()] = Member{scope.get(IdentifierRole::FieldName, io.getName()), io};
            }
            plans_[planIdentity(schema, plan)] = std::move(entry);
        }
    }

    // Functions.

    std::vector<std::string> openFunction(SourceWriter& w, mlir::func::FuncOp fn) const override
    {
        const auto direction = planBodyDirection(fn);
        inBody_              = direction.has_value();
        if (!direction)
        {
            std::vector<std::string> parameters;
            std::string              list;
            for (const auto [index, argument] : llvm::enumerate(fn.getArguments()))
            {
                parameters.push_back("p" + std::to_string(index));
                list += (list.empty() ? "" : ", ") + parameters.back() + ": " + typeName(argument.getType());
            }
            w.open("fn " + functionName(fn.getSymName()) + "(" + list + ") -> " +
                   typeName(fn.getResultTypes().front()) + " {");
            return parameters;
        }
        const bool serialize = *direction == "serialize";
        w.open(serialize ? "pub fn serialize(&self, buffer: &mut [u8]) -> core::result::Result<usize, i8> {"
                         : "pub fn deserialize(&mut self, buffer: &[u8]) -> core::result::Result<usize, i8> {");
        // The size a plan is handed by pointer, read at entry and written back at the end.
        w.line("let mut inout_buffer_size_bytes: usize = buffer.len();");
        return {"self", "buffer", "inout_buffer_size_bytes"};
    }

    void closeFunction(SourceWriter& w, mlir::func::FuncOp /*fn*/) const override
    {
        w.close("}");
    }

    [[nodiscard]] std::string functionName(const llvm::StringRef callee) const override
    {
        return renderHelperBindingIdentifier(CodegenNamingLanguage::Rust, callee);
    }

    // Statements.

    void declare(SourceWriter&         w,
                 const mlir::Type      type,
                 const llvm::StringRef name,
                 const llvm::StringRef expr) const override
    {
        w.line("let " + name.str() + ": " + typeName(type) + " = " + expr.str() + ";");
    }

    void declareVariable(SourceWriter&         w,
                         const mlir::Type      type,
                         const llvm::StringRef name,
                         const bool            reassigned) const override
    {
        w.line(std::string("let ") + (reassigned ? "mut " : "") + name.str() + ": " + typeName(type) + ";");
    }

    void assign(SourceWriter& w, const llvm::StringRef name, const llvm::StringRef expr) const override
    {
        w.line(name.str() + " = " + expr.str() + ";");
    }

    void discard(SourceWriter& w, const llvm::StringRef expr) const override
    {
        w.line("let _unused = " + expr.str() + ";");
    }

    void returnValue(SourceWriter& w, const llvm::StringRef expr) const override
    {
        // A body answers the runtime's error code; its Rust signature answers the size or the code.
        if (inBody_)
        {
            w.line("if " + expr.str() + " == 0i8 { Ok(inout_buffer_size_bytes) } else { Err(" + expr.str() + ") }");
            return;
        }
        w.line(expr.str());
    }

    void openIf(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.open("if " + condition.str() + " {");
    }

    void openElse(SourceWriter& w) const override
    {
        w.midway("} else {");
    }

    void openLoop(SourceWriter& w) const override
    {
        w.open("loop {");
    }

    void breakUnless(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.line("if !" + condition.str() + " { break; }");
    }

    void openFor(SourceWriter&         w,
                 const llvm::StringRef variable,
                 const llvm::StringRef lower,
                 const llvm::StringRef upper,
                 const llvm::StringRef step) const override
    {
        const std::string range = lower.str() + ".." + upper.str();
        w.open("for " + variable.str() + " in " +
               (step == "1usize" ? range : "(" + range + ").step_by(" + step.str() + ")") + " {");
    }

    void closeBlock(SourceWriter& w) const override
    {
        w.close("}");
    }

    // Values.

    [[nodiscard]] std::string constant(const mlir::TypedAttr value) const override
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerAttr>(value))
        {
            const mlir::Type type = integer.getType();
            if (mlir::isa<mlir::IndexType>(type))
            {
                return std::to_string(integer.getValue().getZExtValue()) + "usize";
            }
            const unsigned width = mlir::cast<mlir::IntegerType>(type).getWidth();
            if (width == 1)
            {
                return integer.getValue().isZero() ? "false" : "true";
            }
            const std::int64_t signedValue = integer.getValue().getSExtValue();
            if (isSignedSpelt(type))
            {
                return std::to_string(signedValue) + typeName(type);
            }
            if (signedValue >= 0)
            {
                return std::to_string(integer.getValue().getZExtValue()) + typeName(type);
            }
            if (signedValue == std::numeric_limits<std::int64_t>::min())
            {
                return "i64::MIN as " + typeName(type);
            }
            return std::to_string(signedValue) + "i64 as " + typeName(type);
        }
        if (const auto real = mlir::dyn_cast<mlir::FloatAttr>(value))
        {
            const bool         single = real.getType().isF32();
            std::ostringstream stream;
            stream << std::setprecision(single ? 9 : 17) << real.getValueAsDouble();
            std::string text = stream.str();
            if (text.find_first_of(".eEn") == std::string::npos)
            {
                text += ".0";
            }
            return text + (single ? "f32" : "f64");
        }
        llvm::report_fatal_error("Rust spelling: a constant of an unexpected kind");
    }

    [[nodiscard]] std::string binary(const BinaryOperator  op,
                                     const llvm::StringRef lhs,
                                     const llvm::StringRef rhs,
                                     const mlir::Type      type) const override
    {
        if (isBool(type))
        {
            switch (op)
            {
            case BinaryOperator::And:
                return lhs.str() + " && " + rhs.str();
            case BinaryOperator::Or:
                return lhs.str() + " || " + rhs.str();
            case BinaryOperator::Xor:
                return lhs.str() + " != " + rhs.str();
            default:
                llvm::report_fatal_error("Rust spelling: an arithmetic operator on a bool");
            }
        }
        // Wrapping arithmetic is the plan's arithmetic; Rust's operators would panic on overflow
        // in a debug build.
        const bool signedForm =
            op == BinaryOperator::DivS || op == BinaryOperator::RemS || op == BinaryOperator::ShiftRightS;
        const bool unsignedForm =
            op == BinaryOperator::DivU || op == BinaryOperator::RemU || op == BinaryOperator::ShiftRightU;
        const bool  recast = (signedForm && !isSignedSpelt(type)) || (unsignedForm && isSignedSpelt(type));
        std::string a      = lhs.str();
        std::string b      = rhs.str();
        if (recast)
        {
            a = "(" + (signedForm ? asSigned(lhs, type) : asUnsigned(lhs, type)) + ")";
            b = signedForm ? asSigned(rhs, type) : asUnsigned(rhs, type);
        }
        std::string expression;
        switch (op)
        {
        case BinaryOperator::Add:
            expression = a + ".wrapping_add(" + b + ")";
            break;
        case BinaryOperator::Sub:
            expression = a + ".wrapping_sub(" + b + ")";
            break;
        case BinaryOperator::Mul:
            expression = a + ".wrapping_mul(" + b + ")";
            break;
        case BinaryOperator::DivU:
        case BinaryOperator::DivS:
            expression = a + ".wrapping_div(" + b + ")";
            break;
        case BinaryOperator::RemU:
        case BinaryOperator::RemS:
            expression = a + ".wrapping_rem(" + b + ")";
            break;
        case BinaryOperator::And:
            expression = a + " & " + b;
            break;
        case BinaryOperator::Or:
            expression = a + " | " + b;
            break;
        case BinaryOperator::Xor:
            expression = a + " ^ " + b;
            break;
        case BinaryOperator::ShiftLeft:
            expression = a + ".wrapping_shl(" + b + " as u32)";
            break;
        case BinaryOperator::ShiftRightU:
        case BinaryOperator::ShiftRightS:
            expression = a + ".wrapping_shr(" + b + " as u32)";
            break;
        }
        return recast ? "(" + expression + ") as " + typeName(type) : expression;
    }

    [[nodiscard]] std::string compare(const Comparison      comparison,
                                      const llvm::StringRef lhs,
                                      const llvm::StringRef rhs,
                                      const mlir::Type      type) const override
    {
        // An unsigned value is never below zero. The plan states that comparison for an empty
        // plan's capacity check, and rustc warns on the operator form of it, so it is spelled as
        // the method it stands for.
        if (!isSignedSpelt(type) && !isBool(type))
        {
            if (comparison == Comparison::GtU && isZero(lhs))
            {
                return rhs.str() + ".lt(&" + lhs.str() + ")";
            }
            if (comparison == Comparison::LtU && isZero(rhs))
            {
                return lhs.str() + ".lt(&" + rhs.str() + ")";
            }
            if (comparison == Comparison::LeU && isZero(lhs))
            {
                return rhs.str() + ".ge(&" + lhs.str() + ")";
            }
            if (comparison == Comparison::GeU && isZero(rhs))
            {
                return lhs.str() + ".ge(&" + rhs.str() + ")";
            }
        }
        std::string a = lhs.str();
        std::string b = rhs.str();
        switch (comparison)
        {
        case Comparison::Eq:
            return a + " == " + b;
        case Comparison::Ne:
            return a + " != " + b;
        case Comparison::LtS:
        case Comparison::LeS:
        case Comparison::GtS:
        case Comparison::GeS:
            if (!isSignedSpelt(type))
            {
                a = "(" + asSigned(lhs, type) + ")";
                b = "(" + asSigned(rhs, type) + ")";
            }
            break;
        case Comparison::LtU:
        case Comparison::LeU:
        case Comparison::GtU:
        case Comparison::GeU:
            if (isSignedSpelt(type))
            {
                a = "(" + asUnsigned(lhs, type) + ")";
                b = "(" + asUnsigned(rhs, type) + ")";
            }
            break;
        }
        return a + " " + comparisonToken(comparison) + " " + b;
    }

    [[nodiscard]] std::string select(const llvm::StringRef condition,
                                     const llvm::StringRef ifTrue,
                                     const llvm::StringRef ifFalse,
                                     const mlir::Type /*type*/) const override
    {
        return "if " + condition.str() + " { " + ifTrue.str() + " } else { " + ifFalse.str() + " }";
    }

    [[nodiscard]] std::string convert(const Conversion      conversion,
                                      const llvm::StringRef value,
                                      const mlir::Type      from,
                                      const mlir::Type      to) const override
    {
        if (conversion == Conversion::SignExtend && !isSignedSpelt(from))
        {
            return asSigned(value, from) + " as " + signedStorageType(widthOf(to)) + " as " + typeName(to);
        }
        return value.str() + " as " + typeName(to);
    }

    [[nodiscard]] std::string call(const llvm::StringRef callee, const llvm::ArrayRef<std::string> args) const override
    {
        return callee.str() + "(" + llvm::join(args, ", ") + ")";
    }

    // The dialect.

    [[nodiscard]] bool spellsInline(mlir::Operation* op) const override
    {
        return mlir::
            isa<mlir::dsdl::IsNullOp, mlir::dsdl::BufferOrEmptyOp, mlir::dsdl::MemberAddrOp, mlir::dsdl::ElementAddrOp>(
                op);
    }

    [[nodiscard]] std::string isNull(mlir::dsdl::IsNullOp /*op*/, const ValueNames& /*names*/) const override
    {
        // A reference, a slice and a local are never null.
        return "false";
    }

    [[nodiscard]] std::string bufferOrEmpty(mlir::dsdl::BufferOrEmptyOp op, const ValueNames& names) const override
    {
        return names(op.getBuffer());
    }

    [[nodiscard]] std::string bufferAt(mlir::dsdl::BufferAtOp op, const ValueNames& names) const override
    {
        // A sub-slice from the offset, clamped to the buffer's end: the plan bounds its reads
        // and writes itself, and a slice past the end would panic before they could.
        const std::string buffer = names(op.getBuffer());
        const auto        result = mlir::cast<mlir::dsdl::PtrType>(op.getAddress().getType());
        return "{ let _start = core::cmp::min(" + asSize(names(op.getByteOffset())) + ", " + buffer + ".len()); " +
               (result.getIsConst() ? "&" : "&mut ") + buffer + "[_start..] }";
    }

    [[nodiscard]] std::string loadScalar(mlir::dsdl::LoadScalarOp op, const ValueNames& names) const override
    {
        return names(op.getPointer()) + " as " + typeName(op.getValue().getType());
    }

    void storeScalar(SourceWriter& w, mlir::dsdl::StoreScalarOp op, const ValueNames& names) const override
    {
        w.line(names(op.getPointer()) + " = " + asSize(names(op.getValue())) + ";");
    }

    [[nodiscard]] std::string local(SourceWriter&         w,
                                    mlir::dsdl::LocalOp   op,
                                    const llvm::StringRef name,
                                    const ValueNames&     names) const override
    {
        // The size a nested call is handed bounds the slice it gets; it is written back only
        // where the plan reads the answer.
        w.line(std::string("let ") + (isRead(op.getAddress()) ? "mut " : "") + name.str() +
               ": usize = " + asSize(names(op.getInit())) + ";");
        return name.str();
    }

    [[nodiscard]] std::string loadMember(mlir::dsdl::LoadMemberOp op, const ValueNames& names) const override
    {
        return memberAccess(op.getObject(), op.getMember(), names) + " as " + typeName(op.getValue().getType());
    }

    void storeMember(SourceWriter& w, mlir::dsdl::StoreMemberOp op, const ValueNames& names) const override
    {
        const Member member = memberOf(op.getObject(), op.getMember());
        w.line(memberAccess(op.getObject(), op.getMember(), names) + " = " +
               storedValue(names(op.getValue()), scalarType(member.io)) + ";");
    }

    [[nodiscard]] std::string loadElement(mlir::dsdl::LoadElementOp op, const ValueNames& names) const override
    {
        return elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names) + " as " +
               typeName(op.getValue().getType());
    }

    void storeElement(SourceWriter& w, mlir::dsdl::StoreElementOp op, const ValueNames& names) const override
    {
        const Member member = memberOf(op.getObject(), op.getMember());
        w.line(elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names) + " = " +
               storedValue(names(op.getValue()), scalarType(member.io)) + ";");
    }

    [[nodiscard]] std::string memberAddr(mlir::dsdl::MemberAddrOp op, const ValueNames& names) const override
    {
        return memberAccess(op.getObject(), op.getMember(), names);
    }

    [[nodiscard]] std::string elementAddr(mlir::dsdl::ElementAddrOp op, const ValueNames& names) const override
    {
        return elementAccess(op.getObject(), op.getMember(), names(op.getIndex()), names);
    }

    [[nodiscard]] std::string arrayLength(mlir::dsdl::ArrayLengthOp op, const ValueNames& names) const override
    {
        return memberAccess(op.getObject(), op.getMember(), names) + ".len() as u64";
    }

    void setArrayLength(SourceWriter& w, mlir::dsdl::SetArrayLengthOp op, const ValueNames& names) const override
    {
        // The container takes the section's memory contract, is sized within its capacity -- a
        // count past it is what the plan's validation rejects next -- and holds default elements
        // for the plan to store into. A pool that cannot provide the storage ends the function.
        const Member      member = memberOf(op.getObject(), op.getMember());
        mlir::dsdl::IOOp  io     = member.io;
        const std::string access = memberAccess(op.getObject(), op.getMember(), names);
        const std::string count  = fresh("count");
        w.line(access +
               ".set_memory_contract(crate::dsdl_runtime::VarArrayMemoryContract::new(Self::__LLVMDSDL_MEMORY_MODE, "
               "Self::__LLVMDSDL_INLINE_THRESHOLD_BYTES, Self::" +
               poolClassOf(op.getObject(), op.getMember()) + "));");
        w.line(access + ".clear();");
        w.line("let " + count + ": usize = core::cmp::min(" + asSize(names(op.getValue())) + ", " +
               std::to_string(io.getArrayCapacity()) + "usize);");
        w.open("if Self::__LLVMDSDL_MEMORY_MODE == crate::dsdl_runtime::DsdlMemoryMode::InlineThenPool {");
        w.line("let mut _pool = crate::dsdl_runtime::PassthroughPoolProvider::default();");
        w.open("if let Err(_alloc_err) = " + access + ".reserve_with_pool(" + count + ", &mut _pool) {");
        w.line("return Err(-crate::dsdl_runtime::allocation_error_to_runtime_code(_alloc_err));");
        w.close("}");
        w.midway("} else {");
        w.line(access + ".reserve(" + count + ");");
        w.close("}");
        w.line(access + ".resize(" + count + ", Default::default());");
    }

    [[nodiscard]] std::string unionTag(mlir::dsdl::UnionTagOp op, const ValueNames& names) const override
    {
        return names(op.getObject()) + "._tag_ as u64";
    }

    void setUnionTag(SourceWriter& w, mlir::dsdl::SetUnionTagOp op, const ValueNames& names) const override
    {
        const Plan& plan = planOf(op.getObject());
        w.line(names(op.getObject()) + "._tag_ = " + names(op.getValue()) + " as " +
               unsignedStorageType(static_cast<std::uint32_t>(plan.unionTagBits)) + ";");
    }

    [[nodiscard]] std::string writeBits(mlir::dsdl::WriteBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const auto        width     = static_cast<std::int64_t>(op.getWidth());
        const std::string value     = names(op.getValue());
        const std::string prefix    = names(op.getBuffer()) + ", " + asSize(names(op.getBitOffset())) + ", ";
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "crate::dsdl_runtime::set_f" + std::to_string(width) + "(" + prefix + value + ")";
        }
        if (width == 1 && !op.getIsSigned())
        {
            return "crate::dsdl_runtime::set_bit(" + prefix + (isBool(valueType) ? value : value + " != 0u64") + ")";
        }
        if (op.getIsSigned())
        {
            return "crate::dsdl_runtime::set_ixx(" + prefix + asSigned(value, valueType) + ", " +
                   std::to_string(width) + "u8)";
        }
        return "crate::dsdl_runtime::set_uxx(" + prefix + value + ", " + std::to_string(width) + "u8)";
    }

    [[nodiscard]] std::string readBits(mlir::dsdl::ReadBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const auto        width     = static_cast<std::int64_t>(op.getWidth());
        const std::string prefix    = names(op.getBuffer()) + ", " + asSize(names(op.getBitOffset()));
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "crate::dsdl_runtime::get_f" + std::to_string(width) + "(" + prefix + ")";
        }
        const std::string result = typeName(valueType);
        if (width == 1 && !op.getIsSigned())
        {
            return "crate::dsdl_runtime::get_bit(" + prefix + ") as " + result;
        }
        // The runtime answers in the narrowest standard width that holds the field; a signed read
        // arrives sign-extended and keeps its value across the widening.
        const unsigned holder = holderWidthFor(width);
        return "crate::dsdl_runtime::get_" + std::string(op.getIsSigned() ? "i" : "u") + std::to_string(holder) + "(" +
               prefix + ", " + std::to_string(width) + "u8) as " + result;
    }

    void bitWrite(SourceWriter& w, mlir::dsdl::BitWriteOp op, const ValueNames& names) const override
    {
        // A bool array is a container of bools, so a run of its bits goes one element at a time.
        const auto        container = boolContainerOf(op.getSource(), names);
        const std::string index     = fresh("bit");
        w.open("for " + index + " in 0.." + asSize(names(op.getWidth())) + " {");
        w.line("let _ = crate::dsdl_runtime::set_bit(" + names(op.getDestination()) + ", " +
               asSize(names(op.getDestinationBitOffset())) + " + " + index + ", " + container.first + "[" +
               container.second + " + " + asSize(names(op.getSourceBitOffset())) + " + " + index + "]);");
        w.close("}");
    }

    void bitRead(SourceWriter& w, mlir::dsdl::BitReadOp op, const ValueNames& names) const override
    {
        const auto        container = boolContainerOf(op.getDestination(), names);
        const std::string index     = fresh("bit");
        w.open("for " + index + " in 0.." + asSize(names(op.getWidth())) + " {");
        w.line(container.first + "[" + container.second + " + " + index + "] = crate::dsdl_runtime::get_bit(" +
               names(op.getBuffer()) + ", " + asSize(names(op.getBitOffset())) + " + " + index + ");");
        w.close("}");
    }

    [[nodiscard]] std::string callSerdes(mlir::dsdl::CallSerdesOp op, const ValueNames& names) const override
    {
        // The nested value serialises itself into the slice from the buffer's offset, bounded by
        // the size the plan handed in; its answer is the size it used, which the plan reads back
        // through the local. The bound is taken before the slice is, so the length read ends first.
        const bool        serialize = op.getDirection() == "serialize";
        const std::string buffer    = names(op.getBuffer());
        const std::string size      = names(op.getSize());
        const std::string slice     = "{ let _len = core::cmp::min(" + size + ", " + buffer + ".len()); " +
                                      (serialize ? "&mut " : "&") + buffer + "[.._len] }";
        const std::string used = isRead(op.getSize()) ? "Ok(_used) => { " + size + " = _used; 0i8 }" : "Ok(_) => 0i8,";
        return "match " + names(op.getObject()) + (serialize ? ".serialize(" : ".deserialize(") + slice + ") { " +
               used + " Err(_code) => _code }";
    }

private:
    struct Member final
    {
        std::string      rustName;
        mlir::dsdl::IOOp io;
    };

    struct Plan final
    {
        std::int64_t                 unionTagBits{0};
        llvm::StringMap<Member>      members;
        llvm::StringMap<std::string> poolClass;
    };

    /// @brief The plan the object a pointer names belongs to.
    const Plan& planOf(const mlir::Value object) const
    {
        const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(object.getType());
        const auto identity =
            pointer ? mlir::dyn_cast<mlir::dsdl::ObjectType>(pointer.getPointee()) : mlir::dsdl::ObjectType{};
        const auto found = identity ? plans_.find(identity.getIdentity()) : plans_.end();
        if (found == plans_.end())
        {
            llvm::report_fatal_error("Rust spelling: an object that no plan of this schema describes");
        }
        return found->second;
    }

    Member memberOf(const mlir::Value object, const llvm::StringRef member) const
    {
        const Plan& plan  = planOf(object);
        const auto  found = plan.members.find(member);
        if (found == plan.members.end())
        {
            llvm::report_fatal_error("Rust spelling: a member the schema does not declare: " + member);
        }
        return found->second;
    }

    std::string poolClassOf(const mlir::Value object, const llvm::StringRef member) const
    {
        const Plan& plan  = planOf(object);
        const auto  found = plan.poolClass.find(member);
        if (found == plan.poolClass.end())
        {
            llvm::report_fatal_error("Rust spelling: a length set on a member that is not a variable-length array: " +
                                     member);
        }
        return found->second;
    }

    std::string memberAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        return names(object) + "." + memberOf(object, member).rustName;
    }

    std::string elementAccess(const mlir::Value     object,
                              const llvm::StringRef member,
                              const std::string&    index,
                              const ValueNames&     names) const
    {
        return memberAccess(object, member, names) + "[" + asSize(index) + "]";
    }

    /// @brief The container expression and element base of the bool array @p address names.
    std::pair<std::string, std::string> boolContainerOf(const mlir::Value address, const ValueNames& names) const
    {
        auto element = address.getDefiningOp<mlir::dsdl::ElementAddrOp>();
        if (!element)
        {
            llvm::report_fatal_error("Rust spelling: a bit copy whose storage is not an array element");
        }
        return std::make_pair(memberAccess(element.getObject(), element.getMember(), names),
                              asSize(names(element.getIndex())));
    }

    /// @brief Whether the plan reads the size @p pointer addresses back after handing it out.
    static bool isRead(const mlir::Value pointer)
    {
        return llvm::any_of(pointer.getUsers(),
                            [](mlir::Operation* user) { return mlir::isa<mlir::dsdl::LoadScalarOp>(user); });
    }

    /// @brief The Rust type the struct declares a scalar field or element as.
    static std::string scalarType(mlir::dsdl::IOOp io)
    {
        const llvm::StringRef category = io.getScalarCategory();
        const auto            bits     = static_cast<std::uint32_t>(io.getBitLength());
        if (category == "bool")
        {
            return "bool";
        }
        if (category == "signed")
        {
            return signedStorageType(bits);
        }
        if (category == "float")
        {
            return bits == 64U ? "f64" : "f32";
        }
        return unsignedStorageType(bits);
    }

    /// @brief @p value converted for storage in a field of @p type.
    static std::string storedValue(const std::string& value, const std::string& type)
    {
        if (type == "bool")
        {
            return value + " != 0u64";
        }
        return value + " as " + type;
    }

    // Types.

    static bool isBool(const mlir::Type type)
    {
        return type.isInteger(1);
    }

    /// @brief Whether @p literal is the zero constant of an unsigned type.
    static bool isZero(const llvm::StringRef literal)
    {
        return literal.starts_with("0u") || literal == "0usize";
    }

    /// @brief Whether @p type is spelled as a signed Rust type.
    static bool isSignedSpelt(const mlir::Type type)
    {
        return type.isInteger(8);
    }

    static unsigned widthOf(const mlir::Type type)
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerType>(type))
        {
            return integer.getWidth();
        }
        return 64U;
    }

    static std::string asSigned(const llvm::StringRef value, const mlir::Type type)
    {
        return value.str() + " as " + signedStorageType(widthOf(type));
    }

    static std::string asUnsigned(const llvm::StringRef value, const mlir::Type type)
    {
        return value.str() + " as " + unsignedStorageType(widthOf(type));
    }

    static std::string asSize(const std::string& value)
    {
        return value + " as usize";
    }

    static std::string typeName(const mlir::Type type)
    {
        if (mlir::isa<mlir::IndexType>(type))
        {
            return "usize";
        }
        if (type.isF32())
        {
            return "f32";
        }
        if (type.isF64())
        {
            return "f64";
        }
        if (const auto integer = mlir::dyn_cast<mlir::IntegerType>(type))
        {
            if (integer.getWidth() == 1)
            {
                return "bool";
            }
            return isSignedSpelt(type) ? signedStorageType(integer.getWidth())
                                       : unsignedStorageType(integer.getWidth());
        }
        if (const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(type))
        {
            if (mlir::isa<mlir::dsdl::ByteType>(pointer.getPointee()))
            {
                return pointer.getIsConst() ? "&[u8]" : "&mut [u8]";
            }
            if (mlir::isa<mlir::dsdl::SizeType>(pointer.getPointee()))
            {
                return "usize";
            }
        }
        llvm::report_fatal_error("Rust spelling: a value of a type no plan body carries");
    }

    static std::string comparisonToken(const Comparison comparison)
    {
        switch (comparison)
        {
        case Comparison::Eq:
            return "==";
        case Comparison::Ne:
            return "!=";
        case Comparison::LtS:
        case Comparison::LtU:
            return "<";
        case Comparison::LeS:
        case Comparison::LeU:
            return "<=";
        case Comparison::GtS:
        case Comparison::GtU:
            return ">";
        case Comparison::GeS:
        case Comparison::GeU:
            return ">=";
        }
        return "==";
    }

    /// @brief A name for a local the spelling introduces on its own, apart from the values.
    std::string fresh(const std::string& stem) const
    {
        return "_" + stem + std::to_string(counter_++) + "_";
    }

    mlir::SymbolTable     symbols_;
    llvm::StringMap<Plan> plans_;
    mutable std::size_t   counter_{0};
    mutable bool          inBody_{false};
};

std::string rustConstType(const TypeExprAST& type)
{
    const auto* prim = std::get_if<PrimitiveTypeExprAST>(&type.scalar);
    if (!prim)
    {
        return "i64";
    }
    switch (prim->kind)
    {
    case PrimitiveKind::Bool:
        return "bool";
    case PrimitiveKind::Float:
        return "f64";
    case PrimitiveKind::SignedInt:
        return "i64";
    case PrimitiveKind::UnsignedInt:
    case PrimitiveKind::Byte:
    case PrimitiveKind::Utf8:
        return "u64";
    }
    return "i64";
}

std::string rustConstType(const TypeExprAST& type, const Value& value)
{
    if (std::holds_alternative<std::string>(value.data))
    {
        return "&'static str";
    }
    if (std::holds_alternative<bool>(value.data))
    {
        return "bool";
    }
    return rustConstType(type);
}

/// @brief The two bodies `lower-dsdl-bodies` built for one section.
struct SectionBodies final
{
    mlir::func::FuncOp serialize;
    mlir::func::FuncOp deserialize;
};

llvm::Error emitSectionType(SourceWriter&                    w,
                            const std::string&               typeName,
                            const SemanticSection&           section,
                            const EmitterContext&            ctx,
                            const Options&                   options,
                            const std::string&               fullName,
                            std::uint32_t                    majorVersion,
                            std::uint32_t                    minorVersion,
                            const AttachedDoc&               typeDoc,
                            const std::string&               definitionFullName,
                            const LoweredSectionFacts* const sectionFacts,
                            const RustSpelling&              spelling,
                            const SectionBodies&             bodies)
{
    const NamingScope        fieldScope = makeSectionFieldScope(CodegenNamingLanguage::Rust, section);
    std::vector<std::string> variableArrayFields;
    for (const auto& field : section.fields)
    {
        if (!field.isPadding && isVariableArray(field.resolvedType.arrayKind))
        {
            variableArrayFields.push_back(field.name);
        }
    }
    std::unordered_map<std::string, std::string>       poolClassConstExprByField;
    std::vector<std::pair<std::string, std::uint32_t>> poolClassConstants;
    std::uint32_t                                      nextPoolClassId = 1U;
    for (const auto& [fieldName, constName] : poolClassConstantNames(variableArrayFields))
    {
        poolClassConstExprByField.emplace(fieldName, "Self::" + constName);
        poolClassConstants.emplace_back(constName, nextPoolClassId++);
    }

    const auto declaredName = renderDeclaredTypeName(typeName, section.deprecated);
    emitAttachedDocRust(w,
                        docWithDeprecationNotice(typeDoc,
                                                 section.deprecated,
                                                 definitionFullName,
                                                 majorVersion,
                                                 minorVersion));
    w.line("#[derive(Clone, Debug, PartialEq)]");
    w.open("pub struct " + declaredName + " {");

    std::size_t fieldCount = 0;
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        ++fieldCount;
        emitAttachedDocRust(w, field.doc);
        w.line("pub " + fieldScope.get(IdentifierRole::FieldName, field.name) + ": " +
               rustFieldType(field.resolvedType, ctx) + ",");
    }

    if (section.isUnion)
    {
        // The tag storage must match the wire tag width (8 bits for <=256 options,
        // 16 for 257..65536, etc.); a hardcoded u8 truncates a wide tag and mis-dispatches.
        w.line("pub _tag_: " + unsignedStorageType(resolveUnionTagBits(section, sectionFacts)) + ",");
    }

    if (fieldCount == 0 && !section.isUnion)
    {
        w.line("pub _dummy_: u8,");
    }
    w.close("}");
    w.blank();

    if (section.deprecated)
    {
        if (options.emitDeprecationAttributes)
        {
            w.line(rustDeprecatedAttribute(definitionFullName, majorVersion, minorVersion));
        }
        w.line("pub type " + typeName + " = " + declaredName + ";");
        w.blank();
    }

    w.open("impl Default for " + declaredName + " {");
    w.open("fn default() -> Self {");
    w.open("Self {");
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        if (isVariableArray(field.resolvedType.arrayKind))
        {
            w.line(fieldScope.get(IdentifierRole::FieldName, field.name) +
                   ": crate::dsdl_runtime::DsdlVec::with_contract("
                   "crate::dsdl_runtime::VarArrayMemoryContract::new("
                   "Self::__LLVMDSDL_MEMORY_MODE, "
                   "Self::__LLVMDSDL_INLINE_THRESHOLD_BYTES, " +
                   poolClassConstExprByField.at(field.name) + ")),");
            continue;
        }
        w.line(fieldScope.get(IdentifierRole::FieldName, field.name) + ": " + defaultExpr(field.resolvedType, ctx) +
               ",");
    }
    if (section.isUnion)
    {
        w.line("_tag_: 0,");
    }
    if (fieldCount == 0 && !section.isUnion)
    {
        w.line("_dummy_: 0,");
    }
    w.close("}");
    w.close("}");
    w.close("}");
    w.blank();

    w.open("impl " + declaredName + " {");
    w.line("pub const FULL_NAME: &'static str = \"" + fullName + "\";");
    w.line(std::string("pub const IS_DEPRECATED: bool = ") + (section.deprecated ? "true;" : "false;"));
    w.line("pub const FULL_NAME_AND_VERSION: &'static str = \"" + fullName + "." + std::to_string(majorVersion) + "." +
           std::to_string(minorVersion) + "\";");
    w.line("pub const EXTENT_BYTES: usize = " + std::to_string(section.extentBits.value_or(0) / 8) + ";");
    w.line("pub const SERIALIZATION_BUFFER_SIZE_BYTES: usize = " +
           std::to_string((section.serializationBufferSizeBits + 7) / 8) + ";");
    const bool        zohAliasEligible = sectionFacts != nullptr && sectionFacts->zohAliasEligible;
    const std::string zohAliasReason   = (sectionFacts != nullptr && !sectionFacts->zohAliasReason.empty())
                                             ? sectionFacts->zohAliasReason
                                             : "not-proven";
    w.line(std::string("pub const ZOH_ALIAS_ELIGIBLE: bool = ") + (zohAliasEligible ? "true;" : "false;"));
    w.line("pub const ZOH_ALIAS_REASON: &'static str = \"" + zohAliasReason + "\";");
    w.line("pub const __LLVMDSDL_MEMORY_MODE: crate::dsdl_runtime::DsdlMemoryMode = " +
           rustMemoryModeVariantPath(options) + ";");
    w.line("pub const __LLVMDSDL_INLINE_THRESHOLD_BYTES: usize = " + std::to_string(options.inlineThresholdBytes) +
           "usize;");
    for (const auto& [constName, classId] : poolClassConstants)
    {
        w.line("pub const " + constName +
               ": crate::dsdl_runtime::AllocationClassId = crate::dsdl_runtime::AllocationClassId(" +
               std::to_string(classId) + "u32);");
    }
    if (section.isUnion)
    {
        std::size_t optionCount = 0;
        for (const auto& f : section.fields)
        {
            if (!f.isPadding)
            {
                ++optionCount;
            }
        }
        w.line("pub const UNION_OPTION_COUNT: usize = " + std::to_string(optionCount) + ";");
    }

    std::vector<std::string> constNames;
    constNames.reserve(section.constants.size());
    for (const auto& c : section.constants)
    {
        constNames.push_back(c.name);
    }
    NamingScope const constScope = makeSectionConstantScope(CodegenNamingLanguage::Rust, section);
    for (const auto& c : section.constants)
    {
        emitAttachedDocRust(w, c.doc);
        w.line("pub const " + constScope.get(IdentifierRole::ConstantName, c.name) + ": " +
               rustConstType(c.type, c.value) + " = " + rustConstValue(c.type, c.value) + ";");
    }
    w.blank();

    if (!bodies.serialize || !bodies.deserialize)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no plan bodies for %s in the lowered module",
                                       fullName.c_str());
    }
    if (auto err = translateFunction(bodies.serialize, spelling, w))
    {
        return err;
    }
    w.blank();
    if (auto err = translateFunction(bodies.deserialize, spelling, w))
    {
        return err;
    }
    w.blank();
    w.open("pub fn deserialize_with_consumed(&mut self, buffer: &[u8]) -> (i8, usize) {");
    w.open("match self.deserialize(buffer) {");
    w.line("Ok(consumed) => (0, consumed),");
    w.line("Err(rc) => (rc, buffer.len()),");
    w.close("}");
    w.close("}");
    w.blank();

    w.open("pub fn try_deserialize_view<'a>(buffer: &'a [u8]) -> core::result::Result<(&'a [u8], usize), i8> {");
    w.open("if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = \"big\") {");
    w.line("return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
    w.close("}");
    w.line("let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;");
    w.open("if buffer.len() < required {");
    w.line("return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);");
    w.close("}");
    w.line("Ok((&buffer[..required], required))");
    w.close("}");
    w.blank();

    w.open("pub fn try_serialize_view(view_bytes: &[u8], buffer: &mut [u8]) -> core::result::Result<usize, i8> {");
    w.open("if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = \"big\") {");
    w.line("return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
    w.close("}");
    w.line("let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;");
    w.open("if view_bytes.len() != required {");
    w.line("return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);");
    w.close("}");
    w.open("if buffer.len() < required {");
    w.line("return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);");
    w.close("}");
    w.line("buffer[..required].copy_from_slice(&view_bytes[..required]);");
    w.line("Ok(required)");
    w.close("}");
    w.blank();

    w.open("pub fn to_bytes(&self) -> core::result::Result<crate::dsdl_runtime::DsdlVec<u8>, i8> {");
    w.line("let mut buffer = "
           "crate::dsdl_runtime::DsdlVec::<u8>::with_capacity(Self::SERIALIZATION_BUFFER_SIZE_BYTES);");
    w.line("buffer.resize(Self::SERIALIZATION_BUFFER_SIZE_BYTES, 0u8);");
    w.line("let used = self.serialize(&mut buffer)?;");
    w.line("buffer.truncate(used);");
    w.line("Ok(buffer)");
    w.close("}");
    w.blank();

    w.open("pub fn from_bytes(buffer: &[u8]) -> core::result::Result<(Self, usize), i8> {");
    w.line("let mut out = Self::default();");
    w.line("let used = out.deserialize(buffer)?;");
    w.line("Ok((out, used))");
    w.close("}");
    w.close("}");
    w.blank();
    return llvm::Error::success();
}

/// @brief The schema of @p def in the lowered module, by identity.
mlir::dsdl::SchemaOp schemaOf(mlir::ModuleOp module, const SemanticDefinition& def)
{
    for (mlir::dsdl::SchemaOp schema : module.getBodyRegion().front().getOps<mlir::dsdl::SchemaOp>())
    {
        if (schema.getFullName() == def.info.fullName &&
            static_cast<std::uint32_t>(schema.getMajor()) == def.info.majorVersion &&
            static_cast<std::uint32_t>(schema.getMinor()) == def.info.minorVersion)
        {
            return schema;
        }
    }
    return {};
}

llvm::Expected<std::string> renderDefinitionFile(const SemanticDefinition& def,
                                                 const EmitterContext&     ctx,
                                                 const LoweredFactsMap&    loweredFacts,
                                                 const Options&            options,
                                                 mlir::ModuleOp            module)
{
    mlir::dsdl::SchemaOp schema = schemaOf(module, def);
    if (!schema)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no schema for %s in the lowered module",
                                       def.info.fullName.c_str());
    }
    const RustSpelling                   spelling(module, schema);
    std::vector<mlir::func::FuncOp>      helpers;
    std::map<std::string, SectionBodies> bodies;
    for (const mlir::func::FuncOp fn : schemaFunctions(module, schema.getSymName()))
    {
        const auto direction = planBodyDirection(fn);
        if (!direction)
        {
            helpers.push_back(fn);
            continue;
        }
        const auto     sectionAttr = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        SectionBodies& entry       = bodies[sectionAttr ? sectionAttr.getValue().str() : std::string{}];
        (*direction == "serialize" ? entry.serialize : entry.deserialize) = fn;
    }

    std::ostringstream out;
    SourceWriter       w = makeRustWriter(out);
    w.line(generatedCommentLine("Rust backend"));
    w.line("// Source: " + def.info.fullName + "." + std::to_string(def.info.majorVersion) + "." +
           std::to_string(def.info.minorVersion));
    w.line("#![allow(non_camel_case_types)]");
    w.line("#![allow(non_snake_case)]");
    w.line("#![allow(non_upper_case_globals)]");
    out << "\n";

    const auto deps = collectDefinitionCompositeDependencies(def);

    const auto selfKey = loweredTypeKey(def.info.fullName, def.info.majorVersion, def.info.minorVersion);

    for (const auto& depRef : deps)
    {
        if (loweredTypeKey(depRef.fullName, depRef.majorVersion, depRef.minorVersion) == selfKey)
        {
            continue;
        }

        SemanticTypeRef ref = depRef;
        if (const auto* resolved = ctx.find(depRef))
        {
            ref.namespaceComponents = resolved->info.namespaceComponents;
            ref.shortName           = resolved->info.shortName;
        }

        const auto typePath = ctx.rustTypePath(ref);
        const auto rustType = ctx.rustTypeName(ref);
        w.line("use " + typePath + ";");
        (void) rustType;
    }
    if (!deps.empty())
    {
        out << "\n";
    }

    // The helpers the plans call, ahead of the types whose bodies call them.
    for (const mlir::func::FuncOp helper : helpers)
    {
        if (auto err = translateFunction(helper, spelling, w))
        {
            return std::move(err);
        }
        w.blank();
    }

    const auto baseType = ctx.rustTypeName(def.info);

    if (!def.isService)
    {
        if (auto err = emitSectionType(w,
                                       baseType,
                                       def.request,
                                       ctx,
                                       options,
                                       def.info.fullName,
                                       def.info.majorVersion,
                                       def.info.minorVersion,
                                       def.doc,
                                       def.info.fullName,
                                       lookupLoweredSectionFacts(loweredFacts, def, ""),
                                       spelling,
                                       bodies[""]))
        {
            return std::move(err);
        }
        return out.str();
    }

    const auto reqType  = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::Rust, "request");
    const auto respType = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::Rust, "response");

    if (auto err = emitSectionType(w,
                                   reqType,
                                   def.request,
                                   ctx,
                                   options,
                                   def.info.fullName + ".Request",
                                   def.info.majorVersion,
                                   def.info.minorVersion,
                                   def.doc,
                                   def.info.fullName,
                                   lookupLoweredSectionFacts(loweredFacts, def, "request"),
                                   spelling,
                                   bodies["request"]))
    {
        return std::move(err);
    }

    if (def.response)
    {
        out << "\n";
        if (auto err = emitSectionType(w,
                                       respType,
                                       *def.response,
                                       ctx,
                                       options,
                                       def.info.fullName + ".Response",
                                       def.info.majorVersion,
                                       def.info.minorVersion,
                                       def.doc,
                                       def.info.fullName,
                                       lookupLoweredSectionFacts(loweredFacts, def, "response"),
                                       spelling,
                                       bodies["response"]))
        {
            return std::move(err);
        }
    }

    out << "\n";
    if (def.request.deprecated && options.emitDeprecationAttributes)
    {
        w.line(rustDeprecatedAttribute(def.info.fullName, def.info.majorVersion, def.info.minorVersion));
    }
    w.line("pub type " + baseType + " = " + renderDeclaredTypeName(reqType, def.request.deprecated) + ";");

    return out.str();
}

llvm::Expected<std::string> loadRustRuntimeFile(const std::string& fileName)
{
    if (const auto data = embedded_runtime::find("rust/" + fileName))
    {
        return std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "embedded runtime source missing: rust/%s",
                                   fileName.c_str());
}

std::string renderCargoToml(const Options& options)
{
    const auto rustProfileName = [&options]() -> const char* {
        return options.profile == Profile::Std ? "std" : "no-std-alloc";
    };
    const auto rustRuntimeSpecializationName = [&options]() -> const char* {
        return options.runtimeSpecialization == RuntimeSpecialization::Fast ? "fast" : "portable";
    };
    const auto rustMemoryModeName = [&options]() -> const char* {
        return options.memoryMode == MemoryMode::InlineThenPool ? "inline-then-pool" : "max-inline";
    };

    std::ostringstream out;
    out << "[package]\n";
    out << "name = \"" << options.crateName << "\"\n";
    out << "version = \"" << llvmdsdl::kVersionString << "\"\n";
    out << "edition = \"2021\"\n\n";
    out << "[package.metadata.llvmdsdl]\n";
    out << "generator-version = \"" << llvmdsdl::kVersionString << "\"\n";
    out << "rust-profile = \"" << rustProfileName() << "\"\n";
    out << "rust-runtime-specialization = \"" << rustRuntimeSpecializationName() << "\"\n";
    out << "rust-memory-mode = \"" << rustMemoryModeName() << "\"\n";
    out << "rust-inline-threshold-bytes = " << options.inlineThresholdBytes << "\n\n";

    out << "[lib]\n";
    out << "path = \"src/lib.rs\"\n\n";

    out << "[features]\n";
    std::vector<std::string> defaultFeatures;
    if (options.profile == Profile::Std)
    {
        defaultFeatures.emplace_back("std");
    }
    if (options.runtimeSpecialization == RuntimeSpecialization::Fast)
    {
        defaultFeatures.emplace_back("runtime-fast");
    }
    out << "default = [";
    for (std::size_t i = 0; i < defaultFeatures.size(); ++i)
    {
        if (i != 0)
        {
            out << ", ";
        }
        out << "\"" << defaultFeatures[i] << "\"";
    }
    out << "]\n";
    out << "std = []\n";
    out << "runtime-fast = []\n";
    return out.str();
}

}  // namespace

llvm::Error emit(const SemanticModule& semantic,
                 mlir::ModuleOp        module,
                 const Options&        options,
                 DiagnosticEngine&     diagnostics)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }
    const auto mlirCoverageDiagnostic = codegen_diagnostic_text::mlirSchemaCoverageValidationFailedForEmission("Rust");
    LoweredFactsMap loweredFacts;
    if (!collectLoweredFactsFromMlir(semantic, module, diagnostics, "Rust", &loweredFacts))
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "%s", mlirCoverageDiagnostic.c_str());
    }
    std::filesystem::path const outRoot(options.outDir);
    std::filesystem::path const srcRoot          = outRoot / "src";
    const auto                  selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }
    const bool emitSupport = shouldEmitSupport(options.supportGeneration, anyTypeEmitted);

    if (emitSupport)
    {
        if (options.emitCargoToml)
        {
            if (auto err = writeGeneratedFile(outRoot / "Cargo.toml", renderCargoToml(options), options.writePolicy))
            {
                return err;
            }
        }

        auto runtime = loadRustRuntimeFile("dsdl_runtime.rs");
        if (!runtime)
        {
            return runtime.takeError();
        }
        if (auto err = writeGeneratedFile(srcRoot / "dsdl_runtime.rs",
                                          generatedCommentLine("Rust runtime scaffold") + "\n\n" + *runtime,
                                          options.writePolicy))
        {
            return err;
        }

        auto semanticWrappers = loadRustRuntimeFile("dsdl_runtime_semantic_wrappers.rs");
        if (!semanticWrappers)
        {
            return semanticWrappers.takeError();
        }
        if (auto err =
                writeGeneratedFile(srcRoot / "dsdl_runtime_semantic_wrappers.rs",
                                   generatedCommentLine("Rust runtime semantic wrappers") + "\n\n" + *semanticWrappers,
                                   options.writePolicy))
        {
            return err;
        }
    }

    const EmitterContext ctx(semantic, options.typeNameVersioning);

    std::map<std::string, std::set<std::string>> dirToSubdirs;
    std::map<std::string, std::set<std::string>> dirToFiles;

    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def.info)};

        std::vector<std::string> ns;
        ns.reserve(def.info.namespaceComponents.size());
        for (const auto& c : def.info.namespaceComponents)
        {
            ns.push_back(codegenProjectIdentifier(CodegenNamingLanguage::Rust, IdentifierRole::NamespaceName, c));
        }

        std::string dirRel;
        std::string parentRel;
        for (const auto& component : ns)
        {
            dirToSubdirs[parentRel].insert(component);
            if (!dirRel.empty())
            {
                dirRel += "/";
            }
            dirRel += component;
            parentRel = dirRel;
        }

        const auto modName = EmitterContext::rustModuleName(def.info);
        dirToFiles[dirRel].insert(modName);

        std::filesystem::path dir = srcRoot;
        if (!dirRel.empty())
        {
            dir /= dirRel;
        }
        auto file = renderDefinitionFile(def, ctx, loweredFacts, options, module);
        if (!file)
        {
            return file.takeError();
        }
        if (auto err = writeGeneratedFile(dir / (modName + ".rs"), *file, options.writePolicy, requiredTypeKeys))
        {
            return err;
        }
    }

    std::ostringstream lib;
    SourceWriter       libW = makeRustWriter(lib);
    libW.line(generatedCommentLine("Rust backend crate root"));
    libW.line("#![cfg_attr(not(feature = \"std\"), no_std)]");
    libW.line("#![allow(non_camel_case_types)]");
    libW.line("#![allow(non_snake_case)]");
    libW.line("#![allow(non_upper_case_globals)]");
    libW.line("#[cfg(not(feature = \"std\"))]");
    libW.line("extern crate alloc;");
    libW.line("pub mod dsdl_runtime;");

    if (dirToSubdirs.contains(""))
    {
        for (const auto& sub : dirToSubdirs[""])
        {
            libW.line("pub mod " + sub + ";");
        }
    }
    if (dirToFiles.contains(""))
    {
        for (const auto& file : dirToFiles[""])
        {
            libW.line("pub mod " + file + ";");
        }
    }

    if (auto err = writeGeneratedFile(srcRoot / "lib.rs", lib.str(), options.writePolicy, options.selectedTypeKeys))
    {
        return err;
    }

    std::set<std::string> dirs;
    for (const auto& [d, _] : dirToSubdirs)
    {
        if (!d.empty())
        {
            dirs.insert(d);
        }
    }
    for (const auto& [d, _] : dirToFiles)
    {
        if (!d.empty())
        {
            dirs.insert(d);
        }
    }

    for (const auto& dirRel : dirs)
    {
        std::ostringstream mod;
        SourceWriter       modW = makeRustWriter(mod);
        modW.line(generatedCommentLine("Rust backend module index"));
        if (dirToSubdirs.contains(dirRel))
        {
            for (const auto& sub : dirToSubdirs[dirRel])
            {
                modW.line("pub mod " + sub + ";");
            }
        }
        if (dirToFiles.contains(dirRel))
        {
            for (const auto& file : dirToFiles[dirRel])
            {
                modW.line("pub mod " + file + ";");
            }
        }

        std::filesystem::path const dir = srcRoot / dirRel;
        if (auto err = writeGeneratedFile(dir / "mod.rs", mod.str(), options.writePolicy, options.selectedTypeKeys))
        {
            return err;
        }
    }

    return llvm::Error::success();
}

}  // namespace llvmdsdl::emitter::rust
