//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements TypeScript backend code emission from lowered DSDL modules.
///
/// This file emits TypeScript models and the entry points a consumer calls; the serialise and
/// deserialise bodies those wrap are translations of the plan bodies through `TsSpelling`.
///
/// The line-building concatenations here carry NOLINT for
/// performance-inefficient-string-concatenation. Each one spells out a line of generated
/// source, and an append sequence would cost the reader the line itself.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/BodyTranslator.h"
#include "llvmdsdl/CodeGen/EmitCommon.h"
#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/SourceWriter.h"
#include "llvmdsdl/CodeGen/EmbeddedSources.h"
#include "llvmdsdl/CodeGen/emitter/Ts.h"

#include <algorithm>
#include <cassert>
#include <llvm/ADT/StringRef.h>
#include <cctype>
#include <filesystem>
#include <map>
#include <optional>
#include <sstream>
#include <string>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <utility>

#include "llvmdsdl/CodeGen/ImportSet.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/SchemaLookup.h"
#include "llvmdsdl/CodeGen/InitializerRender.h"
#include "llvmdsdl/CodeGen/TypeMetadata.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Version.h"
#include "llvmdsdl/IR/DSDLOps.h"
#include "llvmdsdl/IR/DSDLTypes.h"
#include "llvmdsdl/Transforms/PlanSteps.h"
#include "llvmdsdl/Transforms/SurfaceTree.h"
#include "llvmdsdl/Support/GeneratedFact.h"
#include "llvmdsdl/Support/LanguageTraits.h"
#include "llvmdsdl/Support/PlanSymbol.h"
#include "llvmdsdl/Support/SurfacePlan.h"
#include "llvmdsdl/Support/Language.h"
#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/STLExtras.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringExtras.h>
#include <llvm/ADT/StringMap.h>
#include <llvm/Support/ErrorHandling.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/IR/BuiltinAttributeInterfaces.h>
#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/BuiltinTypeInterfaces.h>
#include <mlir/IR/BuiltinTypes.h>
#include <mlir/IR/Types.h>
#include <mlir/IR/Value.h>
#include <mlir/Support/LLVM.h>
#include <mlir/IR/OwningOpRef.h>
#include <cmath>
#include <iomanip>
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl::emitter::ts
{

namespace
{

std::string tsConstValue(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(Language::TypeScript, value, makeConstantTypeInfo(type));
}

SourceWriter makeTsWriter(std::ostringstream& out)
{
    return SourceWriter{out, IndentPolicy::spaces(2)};
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return "// Generated by llvmdsdl " + std::string(llvmdsdl::kVersionString) + " (" + detail.str() + ").";
}

void emitAttachedDocTs(SourceWriter& w, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        w.line(line.text.empty() ? std::string{"//"} : "// " + line.text);
    }
}

/// @brief The key of the definition @p info describes, which its schema and the surface name it by.
std::string keyOf(const DiscoveredDefinition& info)
{
    return renderDefinitionKey(definitionRef(info));
}

/// @brief The key of the definition @p ref names.
std::string keyOf(const SemanticTypeRef& ref)
{
    return renderDefinitionKey(definitionRef(ref));
}

/// @brief The symbol of the message @p ref's body that does @p function.
std::string bodyOf(const SemanticTypeRef& ref, const PlanFunction function)
{
    return renderPlanSymbol(planFunction(ref.fullName, ref.majorVersion, ref.minorVersion, {}, function));
}

/// @brief The names TypeScript's output declares and the files it writes, as the surface declares
///        them.
class TsSurface final
{
public:
    explicit TsSurface(const SurfaceTree& tree)
        : tree_(tree)
    {
    }

    [[nodiscard]] const SurfaceTree& tree() const
    {
        return tree_;
    }

    /// @brief The module scope the definition keyed @p key is declared in.
    [[nodiscard]] std::size_t file(const llvm::StringRef key) const
    {
        return tree_.definitionScope(key);
    }

    /// @brief The file the definition keyed @p key is written to, from the output directory.
    [[nodiscard]] const std::string& path(const llvm::StringRef key) const
    {
        return tree_.scope(file(key)).path;
    }

    /// @brief The name of @p section's type.
    [[nodiscard]] const std::string& typeName(const llvm::StringRef key, const llvm::StringRef section) const
    {
        return tree_.scope(tree_.typeScope(key, section)).name;
    }

    /// @brief The name of the declaration of @p kind in the definition's module for @p member of
    ///        @p section, stating @p fact.
    [[nodiscard]] const std::string& declared(const llvm::StringRef              key,
                                              const SurfaceDeclKind              kind,
                                              const llvm::StringRef              section,
                                              const llvm::StringRef              member = {},
                                              const std::optional<GeneratedFact> fact   = std::nullopt) const
    {
        return tree_.nameOf(file(key), kind, SurfaceEntity{key.str(), section.str(), member.str(), {}}, fact);
    }

    /// @brief The name of the property of @p section's type that @p member is, or that states
    ///        @p fact; empty where the type declares none, as in an accessors-only run.
    [[nodiscard]] std::string member(const llvm::StringRef              key,
                                     const llvm::StringRef              section,
                                     const llvm::StringRef              member,
                                     const std::optional<GeneratedFact> fact = std::nullopt) const
    {
        const SurfaceDecl* const decl = tree_.find(tree_.typeScope(key, section),
                                                   SurfaceDeclKind::Field,
                                                   SurfaceEntity{key.str(), section.str(), member.str(), {}},
                                                   fact);
        return (decl != nullptr) ? decl->name : std::string{};
    }

    /// @brief The name of the declaration of @p kind that stands for the lowered function @p symbol,
    ///        stating @p fact.
    [[nodiscard]] const std::string& function(const llvm::StringRef              symbol,
                                              const SurfaceDeclKind              kind,
                                              const std::optional<GeneratedFact> fact = std::nullopt) const
    {
        return tree_.nameOf(symbol, kind, fact);
    }

    /// @brief The local name the definition keyed @p key imports the type of the one keyed
    ///        @p imported under, or its body @p function; null where it imports none.
    [[nodiscard]] const SurfaceDecl* import(const llvm::StringRef key,
                                            const llvm::StringRef imported,
                                            const llvm::StringRef function = {}) const
    {
        return tree_.find(file(key), SurfaceDeclKind::Import, SurfaceEntity{imported.str(), {}, {}, function.str()});
    }

private:
    const SurfaceTree& tree_;
};

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule& semantic, const TsSurface& names, const bool accessorsOnly)
        : names_(names)
        , index_(semantic)
        , accessorsOnly_(accessorsOnly)
    {
    }

    /// @brief The names the output declares.
    const TsSurface& names() const
    {
        return names_;
    }

    /// @brief Whether the run emits the field accessors and neither the object type nor the serdes.
    bool accessorsOnly() const
    {
        return accessorsOnly_;
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

private:
    const TsSurface& names_;
    DefinitionIndex  index_;
    bool             accessorsOnly_{false};
};

std::string relativeImportPath(const std::filesystem::path& fromFile, const std::filesystem::path& toFile);

/// @brief How one TypeScript file names what it takes from other modules, recording each import.
///
/// Every symbol the file writes from another module is named here, so the imports written from the
/// set once the file is rendered hold what the file names and nothing else. A nested definition's
/// interface is named in type positions and imported as a type; its functions are values.
class TsFileNames final
{
public:
    TsFileNames(const EmitterContext& ctx, ImportSet& imports, std::string ownKey)
        : ctx_(ctx)
        , imports_(imports)
        , ownKey_(std::move(ownKey))
    {
    }

    [[nodiscard]] const EmitterContext& context() const
    {
        return ctx_;
    }

    /// @brief The runtime module the bodies and entry points call.
    [[nodiscard]] std::string runtime() const
    {
        return imports_.module(ImportOrigin::Runtime,
                               relativeImportPath(ownPath(), std::filesystem::path("dsdl_runtime.ts")),
                               "dsdlRuntime");
    }

    /// @brief The interface of the definition @p ref, imported from its module under the local name
    ///        the file gives it, unless the module is this file.
    [[nodiscard]] std::string type(const SemanticTypeRef& ref) const
    {
        const TsSurface&   names = ctx_.names();
        const std::string  key   = keyOf(ref);
        const std::string& name  = names.typeName(key, {});
        if (key == ownKey_)
        {
            return name;
        }
        const SurfaceDecl* const local = names.import(ownKey_, key);
        return imports_.member(ImportOrigin::Definition,
                               relativeImportPath(ownPath(), names.path(key)),
                               name,
                               (local != nullptr) ? local->name : name,
                               ImportUse::Type);
    }

    /// @brief The function the body @p symbol of the definition keyed @p key is, imported as
    ///        @ref type imports its interface.
    [[nodiscard]] std::string function(const llvm::StringRef key, const llvm::StringRef symbol) const
    {
        const TsSurface&   names = ctx_.names();
        const std::string& name  = names.function(symbol, SurfaceDeclKind::Entry);
        if (key == ownKey_)
        {
            return name;
        }
        const SurfaceDecl* const local = names.import(ownKey_, key, symbol);
        return imports_.member(ImportOrigin::Definition,
                               relativeImportPath(ownPath(), names.path(key)),
                               name,
                               (local != nullptr) ? local->name : name,
                               ImportUse::Value);
    }

    /// @brief The factory of the definition @p ref.
    [[nodiscard]] std::string make(const SemanticTypeRef& ref) const
    {
        return function(keyOf(ref), bodyOf(ref, PlanFunction::Initialize));
    }

private:
    [[nodiscard]] std::filesystem::path ownPath() const
    {
        return ctx_.names().path(ownKey_);
    }

    const EmitterContext& ctx_;
    ImportSet&            imports_;
    std::string           ownKey_;
};

/// @brief The imports of a TypeScript file that names @p imports: the runtime as a namespace, then a
///        blank line, then each module's values and then each module's types.
std::string renderTsImports(const ImportSet& imports)
{
    std::string runtime;
    std::string values;
    std::string types;
    for (const ImportedModule& module : imports.modules())
    {
        if (!module.binding.empty())
        {
            runtime += "import * as " + module.binding + " from \"" + module.path + "\";\n";
        }
        std::string valueList;
        std::string typeList;
        for (const ImportedMember& member : module.members)
        {
            std::string& list = (member.use == ImportUse::Type) ? typeList : valueList;
            list +=
                (list.empty() ? "" : ", ") + member.name + ((member.local == member.name) ? "" : " as " + member.local);
        }
        if (!valueList.empty())
        {
            values += "import { " + valueList + " } from \"" + module.path + "\";\n";
        }
        if (!typeList.empty())
        {
            types += "import type { " + typeList + " } from \"" + module.path + "\";\n";
        }
    }
    return runtime + "\n" + values + types;
}

std::string tsFieldBaseType(const SemanticFieldType& type, const TsFileNames& file)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "boolean";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
        return "number";
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        if (type.bitLength > 53U)
        {
            return "bigint";
        }
        return "number";
    case SemanticScalarCategory::Float:
    case SemanticScalarCategory::Void:
        return "number";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return file.type(*type.compositeType);
        }
        return "unknown";
    }
    return "unknown";
}

std::string tsFieldType(const SemanticFieldType& type, const TsFileNames& file)
{
    auto base = tsFieldBaseType(type, file);
    if (type.arrayKind == ArrayKind::None)
    {
        return base;
    }
    return "Array<" + base + ">";
}

std::string relativeImportPath(const std::filesystem::path& fromFile, const std::filesystem::path& toFile)
{
    const auto  fromDir    = fromFile.parent_path();
    auto        rel        = toFile.lexically_relative(fromDir);
    std::string importPath = rel.generic_string();
    if (importPath.size() >= 3 && importPath.ends_with(".ts"))
    {
        importPath.resize(importPath.size() - 3);
    }
    if (!importPath.empty() && importPath.front() != '.')
    {
        importPath = "./" + importPath;
    }
    return importPath;
}

std::string moduleAliasFromPath(const std::string& modulePath)
{
    std::string alias;
    alias.reserve(modulePath.size() + 8);
    for (char const c : modulePath)
    {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            alias.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
        }
        else
        {
            alias.push_back('_');
        }
    }
    // Not a role: the alias comes from --ts-module, so it is a token this generator was handed
    // rather than a DSDL name, and must not pick up a role's case projection.
    return codegenSanitizeIdentifier(Language::TypeScript, alias.empty() ? "module" : alias);
}

/// @brief One section's names, as the surface declares them.
class TsSection final
{
public:
    TsSection(const TsSurface& names, std::string key, std::string section)
        : names_(names)
        , key_(std::move(key))
        , section_(std::move(section))
    {
    }

    /// @brief The name of the section's type.
    [[nodiscard]] const std::string& typeName() const
    {
        return names_.typeName(key_, section_);
    }

    /// @brief The name of the property the DSDL field @p member is; empty where the type declares
    ///        none.
    [[nodiscard]] std::string field(const llvm::StringRef member) const
    {
        return names_.member(key_, section_, member);
    }

    /// @brief The name of the property the generator adds to state @p fact.
    [[nodiscard]] std::string dataMember(const GeneratedFact fact) const
    {
        return names_.member(key_, section_, {}, fact);
    }

    /// @brief The name of the constant holding the tag value of the union option @p member.
    [[nodiscard]] const std::string& option(const llvm::StringRef member) const
    {
        return names_.declared(key_, SurfaceDeclKind::Option, section_, member);
    }

    /// @brief The name of the constant the DSDL constant @p member is.
    [[nodiscard]] const std::string& constant(const llvm::StringRef member) const
    {
        return names_.declared(key_, SurfaceDeclKind::Constant, section_, member);
    }

    [[nodiscard]] const TsSurface& names() const
    {
        return names_;
    }

private:
    const TsSurface& names_;
    std::string      key_;
    std::string      section_;
};

/// @brief Declares the tag value that selects each of a union's options.
void emitUnionOptionTags(SourceWriter& w, const TsSection& names, const SectionMetadata& metadata)
{
    if (!metadata.isUnion)
    {
        return;
    }
    for (const auto& option : metadata.unionOptions)
    {
        w.line("export const " + names.option(option.name) + " = " + std::to_string(option.tag) + ";");
    }
}

void emitSectionConstants(SourceWriter& w, const TsSection& names, const SemanticSection& section)
{
    for (const auto& constant : section.constants)
    {
        emitAttachedDocTs(w, constant.doc);
        w.line("export const " + names.constant(constant.name) + " = " + tsConstValue(constant.type, constant.value) +
               ";");
    }
}

void emitDeprecationJsDocTs(SourceWriter&       w,
                            const bool          deprecated,
                            const std::string&  fullName,
                            const std::uint32_t majorVersion,
                            const std::uint32_t minorVersion)
{
    if (!deprecated)
    {
        return;
    }
    // The `Deprecated: ` prefix that the shared notice carries for Go's benefit is redundant next to
    // the JSDoc tag, so it is dropped here.
    const std::string notice = deprecationNotice(fullName, majorVersion, minorVersion);
    const std::string prefix = "Deprecated: ";
    const std::string body   = notice.starts_with(prefix) ? notice.substr(prefix.size()) : notice;

    // Wrapped and split across lines for the same reason the notice itself is: a single-line JSDoc
    // block would be twice the width of the code around it. Budget allows for the " * " continuation.
    const auto lines = wrapCommentText(body, 68U);
    w.line("/**");
    w.line(" * @deprecated " + lines.front());
    for (std::size_t i = 1; i < lines.size(); ++i)
    {
        w.line(" *   " + lines[i]);
    }
    w.line(" */");
}

void emitStructSectionType(SourceWriter&          w,
                           const TsSection&       names,
                           const SemanticSection& section,
                           const AttachedDoc&     typeDoc,
                           const TsFileNames&     file,
                           const std::string&     fullName,
                           const std::uint32_t    majorVersion,
                           const std::uint32_t    minorVersion,
                           const bool             deprecated)
{
    emitAttachedDocTs(w, typeDoc);
    emitDeprecationJsDocTs(w, deprecated, fullName, majorVersion, minorVersion);

    // A definition with no field is an object with no property, and `interface X {}` does not say
    // that: TypeScript reads an empty interface as a constraint nothing fails, so a number or a
    // string satisfies it. `Record<string, never>` is the type of an object that has no property.
    const std::string& typeName = names.typeName();
    const bool         anyField = llvm::any_of(section.fields, [](const auto& field) { return !field.isPadding; });
    if (!anyField)
    {
        w.line("export type " + typeName + " = Record<string, never>;");
        return;
    }

    w.open("export interface " + typeName + " {");
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        emitAttachedDocTs(w, field.doc);
        w.line(names.field(field.name) + ": " +
               (field.heldAsView
                    ? std::string{(field.resolvedType.arrayKind == ArrayKind::None) ? "Uint8Array" : "Uint8Array[]"}
                    : tsFieldType(field.resolvedType, file)) +
               ";");
    }
    w.close("}");
}

void emitUnionSectionType(SourceWriter&          w,
                          const TsSection&       names,
                          const SemanticSection& section,
                          const AttachedDoc&     typeDoc,
                          const TsFileNames&     file,
                          const std::string&     fullName,
                          const std::uint32_t    majorVersion,
                          const std::uint32_t    minorVersion)
{
    std::vector<const SemanticField*> options;
    for (const auto& field : section.fields)
    {
        if (!field.isPadding)
        {
            options.push_back(&field);
        }
    }

    const std::string& typeName = names.typeName();
    const std::string  tag      = names.dataMember(GeneratedFact::UnionTag);
    if (options.empty())
    {
        emitAttachedDocTs(w, typeDoc);
        emitDeprecationJsDocTs(w, section.deprecated, fullName, majorVersion, minorVersion);
        w.line("export type " + typeName + " = { " + tag + ": number };");
        return;
    }

    emitAttachedDocTs(w, typeDoc);
    emitDeprecationJsDocTs(w, section.deprecated, fullName, majorVersion, minorVersion);
    w.line("export type " + typeName + " =");
    for (std::size_t i = 0; i < options.size(); ++i)
    {
        const auto* field = options[i];
        emitAttachedDocTs(w, field->doc);
        std::ostringstream variant;
        variant << "{ " << tag << ": " << field->unionOptionIndex << "; " << names.field(field->name) << ": "
                << tsFieldType(field->resolvedType, file) << "; }";
        const auto* const prefix = "  | ";
        w.line(prefix + variant.str() + (i + 1 == options.size() ? ";" : ""));
    }
}

void emitSectionType(SourceWriter&          w,
                     const TsSection&       names,
                     const SemanticSection& section,
                     const AttachedDoc&     typeDoc,
                     const TsFileNames&     file,
                     const std::string&     fullName,
                     const std::uint32_t    majorVersion,
                     const std::uint32_t    minorVersion)
{
    if (section.isUnion)
    {
        emitUnionSectionType(w, names, section, typeDoc, file, fullName, majorVersion, minorVersion);
    }
    else
    {
        emitStructSectionType(w,
                              names,
                              section,
                              typeDoc,
                              file,
                              fullName,
                              majorVersion,
                              minorVersion,
                              section.deprecated);
    }
}

/// @brief The TypeScript spelling of the plan-body vocabulary, for one schema.
///
/// The plan's `i64` is `bigint`, its `i8` and an index are `number`, and `i1` is `boolean`. A
/// constant is the value it stands for, and a bigint carries the plan's arithmetic without
/// wrapping. A buffer is a `Uint8Array`, and a pointer into it is a subarray clamped to the
/// buffer's end. A body is an exported function of the object and the buffer that answers the
/// size it used, or the error code, which is negative; the entry points a consumer calls wrap
/// it. A deserialise body is handed an empty object, so the storage a member address names is
/// created where it is first addressed. A union is one of its option objects, so an option is
/// reached through the object cast to the option's shape.
class TsSpelling final : public BodySpelling
{
public:
    TsSpelling(mlir::dsdl::SchemaOp schema, const TsSurface& names, const TsFileNames& file)
        : file_(file)
        , names_(names)
    {
        if (schema.getBody().empty())
        {
            return;
        }
        const std::string key = schema.getSymName().str();
        for (mlir::dsdl::SerializationPlanOp plan : schema.getBody().front().getOps<mlir::dsdl::SerializationPlanOp>())
        {
            const llvm::StringRef section = plan.getSection().value_or(llvm::StringRef{});
            Plan                  entry;
            entry.typeName = names.typeName(key, section);
            entry.isUnion  = plan.getIsUnion();
            if (!plan.getBody().empty())
            {
                for (mlir::dsdl::IOOp io : plan.getBody().front().getOps<mlir::dsdl::IOOp>())
                {
                    if (!io.isPadding())
                    {
                        entry.members[io.getName()] = Member{names.member(key, section, io.getName()), io};
                    }
                }
            }
            // The union's tag, reached by its accessors as a member is: the wire holds it ahead
            // of the option, and no field can be named `_tag_`.
            if (plan.getIsUnion())
            {
                tagSteps_.push_back(unionTagStep(schema->getContext(), plan.getUnionTagBits().value_or(0)));
                entry.members[kPlanUnionTagMember] =
                    Member{names.member(key, section, {}, GeneratedFact::UnionTag), tagSteps_.back().get()};
            }
            plans_[planIdentity(schema, plan)] = std::move(entry);
        }
    }

    // Functions.

    std::vector<std::string> openFunction(SourceWriter& w, mlir::func::FuncOp fn) const override
    {
        const auto direction = planBodyDirection(fn);
        deserialize_         = direction.has_value() && *direction == "deserialize";
        accessor_            = Accessor::None;
        if (direction && (*direction == "get" || *direction == "set"))
        {
            return openAccessor(w, fn, *direction == "get");
        }
        if (!direction)
        {
            std::vector<std::string> parameters;
            std::string              list;
            for (const auto [index, argument] : llvm::enumerate(fn.getArguments()))
            {
                parameters.push_back("p" + std::to_string(index));
                list += (list.empty() ? "" : ", ") + parameters.back() + ": " + typeName(argument.getType());
            }
            w.open("function " + functionName(fn.getSymName()) + "(" + list +
                   "): " + typeName(fn.getResultTypes().front()) + " {");
            return parameters;
        }
        const Plan& plan = planOf(fn.getArgument(0));
        w.open("export function " + names_.function(fn.getSymName(), SurfaceDeclKind::Entry) +
               "(obj: " + plan.typeName + ", buffer: Uint8Array): number {");
        // A body of a definition with no fields reads nothing of its buffer, and the entry point's
        // signature is every body's.
        if (!readsArgument(fn, 1))
        {
            w.line("void buffer;");
        }
        return {"obj", "buffer"};
    }

    void closeFunction(SourceWriter& w, mlir::func::FuncOp /*fn*/) const override
    {
        w.close("}");
    }

    [[nodiscard]] std::string valueName(const ValueRole       role,
                                        const llvm::StringRef member,
                                        const std::size_t     ordinal) const override
    {
        return camelValueName(role, member, ordinal);
    }

    [[nodiscard]] llvm::ArrayRef<llvm::StringRef> reservedLocals() const override
    {
        // A body constructs bigints and typed arrays and clamps through Math, each by its global
        // name. The lower-cased ones matter most: a camel-cased role lands in that shape.
        static const llvm::StringRef names[] = {"Array",
                                                "BigInt",
                                                "Boolean",
                                                "DataView",
                                                "Error",
                                                "Float32Array",
                                                "Float64Array",
                                                "Infinity",
                                                "JSON",
                                                "Map",
                                                "Math",
                                                "NaN",
                                                "Number",
                                                "Object",
                                                "Set",
                                                "String",
                                                "Symbol",
                                                "Uint8Array",
                                                "Uint16Array",
                                                "Uint32Array",
                                                "globalThis",
                                                "isFinite",
                                                "isNaN",
                                                "parseFloat",
                                                "parseInt",
                                                "undefined",
                                                // The runtime module, reached by its import name.
                                                "dsdlRuntime"};
        return names;
    }

    [[nodiscard]] std::string functionName(const llvm::StringRef callee) const override
    {
        return names_.function(callee, SurfaceDeclKind::Helper);
    }

    // Statements.

    void declare(SourceWriter& w,
                 const mlir::Type /*type*/,
                 const llvm::StringRef name,
                 const llvm::StringRef expr) const override
    {
        w.line("const " + name.str() + " = " + expr.str() + ";");
    }

    void declareVariable(SourceWriter&         w,
                         const mlir::Type      type,
                         const llvm::StringRef name,
                         const bool /*reassigned*/) const override
    {
        w.line("let " + name.str() + ": " + typeName(type) + ";");
    }

    void assign(SourceWriter& w, const llvm::StringRef name, const llvm::StringRef expr) const override
    {
        w.line(name.str() + " = " + expr.str() + ";");
    }

    void discard(SourceWriter& w, const llvm::StringRef expr) const override
    {
        w.line("void " + expr.str() + ";");
    }

    /// @brief Opens a getter or a setter: an exported function named after the type and the
    ///        member, as the bodies are, speaking the member's own type. The plan holds an
    ///        integer in a `bigint`: the size is the buffer's own length as one, an expression
    ///        rather than a local; an index, and a `number` or a `boolean` member, are rebound at
    ///        entry and a getter's answer is converted at the return.
    std::vector<std::string> openAccessor(SourceWriter& w, mlir::func::FuncOp fn, const bool getter) const
    {
        const Accessed     a         = accessed(fn);
        const Storage      storage   = storageOf(*a.member);
        const std::string& name      = names_.function(fn.getSymName(), SurfaceDeclKind::Accessor);
        const bool         composite = getter && mlir::isa<mlir::dsdl::PtrType>(fn.getResultTypes().front());
        const bool         indexed   = fn.getNumArguments() == (getter ? 3U : 4U);
        const std::string  index     = indexed ? ", elementIndex: number" : "";
        const bool         rebind    = (storage == Storage::Number) || (storage == Storage::Boolean);
        accessor_                    = getter ? Accessor::Getter : Accessor::Setter;
        returnCast_.clear();
        if (composite)
        {
            // The nested type's buffer, as a subarray, which carries its own length.
            w.open("export function " + name + "(buffer: Uint8Array" + index + "): Uint8Array {");
        }
        else if (getter)
        {
            if (storage == Storage::Number)
            {
                returnCast_ = "Number";
            }
            else if (storage == Storage::Boolean)
            {
                returnCast_ = "boolean";
            }
            w.open("export function " + name + "(buffer: Uint8Array" + index + "): " + elementTsType(*a.member) + " {");
        }
        else
        {
            w.open("export function " + name + "(buffer: Uint8Array" + index + ", " +
                   (rebind ? "memberValue: " : "value: ") + elementTsType(*a.member) + "): number {");
        }
        std::vector<std::string> parameters{"buffer", "BigInt(buffer.length)"};
        if (indexed)
        {
            w.line("const index: bigint = BigInt(elementIndex);");
            parameters.emplace_back("index");
        }
        if (!getter)
        {
            if (storage == Storage::Number)
            {
                w.line("const value: bigint = BigInt(memberValue);");
            }
            else if (storage == Storage::Boolean)
            {
                w.line("const value: bigint = memberValue ? 1n : 0n;");
            }
            parameters.emplace_back("value");
        }
        return parameters;
    }

    void returnValue(SourceWriter& w, const llvm::StringRef expr) const override
    {
        // A getter answers the value in the member's own type; a setter answers the code alone.
        if (accessor_ == Accessor::Getter)
        {
            if (returnCast_ == "Number")
            {
                w.line("return Number(" + expr.str() + ");");
            }
            else if (returnCast_ == "boolean")
            {
                w.line("return " + expr.str() + " !== 0n;");
            }
            else
            {
                w.line("return " + expr.str() + ";");
            }
            return;
        }
        if (accessor_ == Accessor::Setter)
        {
            w.line("return " + expr.str() + ";");
            return;
        }
        w.line("return " + expr.str() + ";");
    }

    void returnWithSize(SourceWriter& w, const llvm::StringRef error, const llvm::StringRef used) const override
    {
        // The size used on success, and the code, which is negative, on failure.
        w.open("if (" + error.str() + " === 0) {");
        w.line("return " + used.str() + ";");
        w.close("}");
        w.line("return " + error.str() + ";");
    }

    [[nodiscard]] std::string bufferLength(mlir::dsdl::BufferLengthOp op, const ValueNames& names) const override
    {
        return "BigInt(" + names(op.getBuffer()) + ".length)";
    }

    void openIf(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.open("if (" + condition.str() + ") {");
    }

    void openElse(SourceWriter& w) const override
    {
        w.midway("} else {");
    }

    void openLoop(SourceWriter& w) const override
    {
        w.open("for (;;) {");
    }

    void breakUnless(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.open("if (!(" + condition.str() + ")) {");
        w.line("break;");
        w.close("}");
    }

    void openFor(SourceWriter&         w,
                 const llvm::StringRef variable,
                 const llvm::StringRef lower,
                 const llvm::StringRef upper,
                 const llvm::StringRef step) const override
    {
        w.open("for (let " + variable.str() + " = " + lower.str() + "; " + variable.str() + " < " + upper.str() + "; " +
               variable.str() + " += " + step.str() + ") {");
    }

    void closeBlock(SourceWriter& w) const override
    {
        w.close("}");
    }

    // Values.

    [[nodiscard]] std::string constant(const mlir::TypedAttr value) const override
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerAttr>(value))
        {
            const mlir::Type type = integer.getType();
            if (mlir::isa<mlir::IndexType>(type))
            {
                return std::to_string(integer.getValue().getZExtValue());
            }
            if (isBool(type))
            {
                return integer.getValue().isZero() ? "false" : "true";
            }
            // The value the two's complement stands for: a bigint holds it as such, and the
            // bitwise operators read a negative bigint as its two's complement.
            const std::string digits = std::to_string(integer.getValue().getSExtValue());
            return isBig(type) ? digits + "n" : digits;
        }
        if (const auto real = mlir::dyn_cast<mlir::FloatAttr>(value))
        {
            const double number = real.getValueAsDouble();
            if (std::isnan(number))
            {
                return "Number.NaN";
            }
            if (std::isinf(number))
            {
                return number < 0 ? "-Infinity" : "Infinity";
            }
            std::ostringstream stream;
            stream << std::setprecision(17) << number;
            return stream.str();
        }
        llvm::report_fatal_error("TypeScript spelling: a constant of an unexpected kind");
    }

    [[nodiscard]] std::string binary(const BinaryOperator  op,
                                     const llvm::StringRef lhs,
                                     const llvm::StringRef rhs,
                                     const mlir::Type      type) const override
    {
        if (isBool(type))
        {
            switch (op)
            {
            case BinaryOperator::And:
                return lhs.str() + " && " + rhs.str();
            case BinaryOperator::Or:
                return lhs.str() + " || " + rhs.str();
            case BinaryOperator::Xor:
                return lhs.str() + " !== " + rhs.str();
            default:
                llvm::report_fatal_error("TypeScript spelling: an arithmetic operator on a bool");
            }
        }
        // A bigint's arithmetic is the plan's; a number's division is rounded to the integer.
        if (!isBig(type) && (op == BinaryOperator::DivU || op == BinaryOperator::DivS))
        {
            return "Math.trunc(" + lhs.str() + " / " + rhs.str() + ")";
        }
        return lhs.str() + " " + operatorToken(op) + " " + rhs.str();
    }

    [[nodiscard]] std::string logicalNot(const llvm::StringRef expr) const override
    {
        return "!(" + expr.str() + ")";
    }

    [[nodiscard]] std::string compare(const Comparison      comparison,
                                      const llvm::StringRef lhs,
                                      const llvm::StringRef rhs,
                                      const mlir::Type      type) const override
    {
        std::string a = lhs.str();
        std::string b = rhs.str();
        switch (comparison)
        {
        case Comparison::Eq:
            return a + " === " + b;
        case Comparison::Ne:
            return a + " !== " + b;
        case Comparison::LtU:
        case Comparison::LeU:
        case Comparison::GtU:
        case Comparison::GeU:
            // A bigint is the value its bits stand for; an unsigned comparison against a
            // negative literal reads both as the unsigned 64-bit values the plan compares.
            if (isBig(type) && (lhs.starts_with("-") || rhs.starts_with("-")))
            {
                a = "BigInt.asUintN(64, " + a + ")";
                b = "BigInt.asUintN(64, " + b + ")";
            }
            break;
        default:
            break;
        }
        return a + " " + comparisonToken(comparison) + " " + b;
    }

    [[nodiscard]] std::string select(const llvm::StringRef condition,
                                     const llvm::StringRef ifTrue,
                                     const llvm::StringRef ifFalse,
                                     const mlir::Type /*type*/) const override
    {
        return condition.str() + " ? " + ifTrue.str() + " : " + ifFalse.str();
    }

    [[nodiscard]] std::string convert(const Conversion /*conversion*/,
                                      const llvm::StringRef value,
                                      const mlir::Type      from,
                                      const mlir::Type      to) const override
    {
        return cast(value.str(), from, to);
    }

    [[nodiscard]] std::string call(const llvm::StringRef callee, const llvm::ArrayRef<std::string> args) const override
    {
        return callee.str() + "(" + llvm::join(args, ", ") + ")";
    }

    // The dialect.

    [[nodiscard]] bool spellsInline(mlir::Operation* op) const override
    {
        if (mlir::isa<mlir::dsdl::IsNullOp, mlir::dsdl::BufferOrEmptyOp>(op))
        {
            return true;
        }
        // An address that creates its storage is evaluated once.
        return !deserialize_ && mlir::isa<mlir::dsdl::MemberAddrOp, mlir::dsdl::ElementAddrOp>(op);
    }

    [[nodiscard]] std::string indexHolds(mlir::dsdl::IndexHoldsOp op, const ValueNames& names) const override
    {
        // An Array holds at most 2^32 - 1 elements, whatever a Number represents.
        const std::string value = names(op.getValue());
        return "(" + value + " >= 0n && " + value + " <= 4294967295n)";
    }

    [[nodiscard]] std::string isNotNull(mlir::dsdl::IsNullOp op, const ValueNames& names) const override
    {
        const auto pointer = mlir::cast<mlir::dsdl::PtrType>(op.getPointer().getType());
        if (mlir::isa<mlir::dsdl::ObjectType>(pointer.getPointee()))
        {
            return names(op.getPointer()) + " != null";
        }
        return "true";
    }

    [[nodiscard]] std::string isNull(mlir::dsdl::IsNullOp op, const ValueNames& names) const override
    {
        // The object arrives by reference and may be missing; a buffer and a local are never null.
        const auto pointer = mlir::cast<mlir::dsdl::PtrType>(op.getPointer().getType());
        if (mlir::isa<mlir::dsdl::ObjectType>(pointer.getPointee()))
        {
            return names(op.getPointer()) + " == null";
        }
        return "false";
    }

    [[nodiscard]] std::string bufferOrEmpty(mlir::dsdl::BufferOrEmptyOp op, const ValueNames& names) const override
    {
        return names(op.getBuffer());
    }

    [[nodiscard]] std::string bufferAt(mlir::dsdl::BufferAtOp op, const ValueNames& names) const override
    {
        // The plan bounds its reads and writes itself; the subarray is clamped to the buffer.
        const std::string buffer = names(op.getBuffer());
        return buffer + ".subarray(Math.min(" + asNumber(op.getByteOffset(), names) + ", " + buffer + ".length))";
    }

    [[nodiscard]] std::string loadScalar(mlir::dsdl::LoadScalarOp /*op*/, const ValueNames& /*names*/) const override
    {
        // A body's size reaches TypeScript as its buffer's length and a second result.
        llvm::report_fatal_error("TypeScript spelling: a size pointer reaches TypeScript only folded");
    }

    void storeScalar(SourceWriter& /*w*/, mlir::dsdl::StoreScalarOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("TypeScript spelling: a size pointer reaches TypeScript only folded");
    }

    [[nodiscard]] std::string local(SourceWriter& /*w*/,
                                    mlir::dsdl::LocalOp /*op*/,
                                    const llvm::StringRef /*name*/,
                                    const ValueNames& /*names*/) const override
    {
        // A body's only local is the size of a nested call, which reaches TypeScript folded to
        // `dsdl.call_serdes_sized`.
        llvm::report_fatal_error("TypeScript spelling: a local reaches TypeScript only as a nested call's size");
    }

    [[nodiscard]] std::string loadMember(mlir::dsdl::LoadMemberOp op, const ValueNames& names) const override
    {
        return loadedValue(memberAccess(op.getObject(), op.getMember(), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeMember(SourceWriter& w, mlir::dsdl::StoreMemberOp op, const ValueNames& names) const override
    {
        w.line(memberAccess(op.getObject(), op.getMember(), names) + " = " +
               storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())) +
               ";");
    }

    [[nodiscard]] std::string loadElement(mlir::dsdl::LoadElementOp op, const ValueNames& names) const override
    {
        return loadedValue(elementAccess(op.getObject(), op.getMember(), asNumber(op.getIndex(), names), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeElement(SourceWriter& w, mlir::dsdl::StoreElementOp op, const ValueNames& names) const override
    {
        w.line(elementAccess(op.getObject(), op.getMember(), asNumber(op.getIndex(), names), names) + " = " +
               storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())) +
               ";");
    }

    [[nodiscard]] std::string memberAddr(mlir::dsdl::MemberAddrOp op, const ValueNames& names) const override
    {
        const Member member = memberOf(op.getObject(), op.getMember());
        std::string  access = memberAccess(op.getObject(), op.getMember(), names);
        if (!deserialize_)
        {
            return access;
        }
        // The storage the address names, created where the plan first addresses it.
        if (isArray(member))
        {
            return "(" + access + " \?\?= [])";
        }
        if (isComposite(member))
        {
            return "(" + access + " \?\?= {} as " + memberTsType(member) + ")";
        }
        return access;
    }

    [[nodiscard]] std::string elementAddr(mlir::dsdl::ElementAddrOp op, const ValueNames& names) const override
    {
        const Member member  = memberOf(op.getObject(), op.getMember());
        std::string  element = elementAccess(op.getObject(), op.getMember(), asNumber(op.getIndex(), names), names);
        if (deserialize_ && isComposite(member))
        {
            return "(" + element + " \?\?= {} as " + elementTsType(member) + ")";
        }
        return element;
    }

    [[nodiscard]] std::string arrayLength(mlir::dsdl::ArrayLengthOp op, const ValueNames& names) const override
    {
        return "BigInt(" + containerAccess(op.getObject(), op.getMember(), names) + ".length)";
    }

    void setArrayLength(SourceWriter& w, mlir::dsdl::SetArrayLengthOp op, const ValueNames& names) const override
    {
        // Sized to the count the plan validated, for the plan to store into.
        const Member member = memberOf(op.getObject(), op.getMember());
        w.line(memberAccess(op.getObject(), op.getMember(), names) + " = new Array<" + elementTsType(member) + ">(" +
               asNumber(op.getValue(), names) + ");");
    }

    [[nodiscard]] std::string unionTag(mlir::dsdl::UnionTagOp op, const ValueNames& names) const override
    {
        return file_.runtime() + ".toBigIntValue(" + names(op.getObject()) + "." +
               memberOf(op.getObject(), kPlanUnionTagMember).tsName + ")";
    }

    void setUnionTag(SourceWriter& w, mlir::dsdl::SetUnionTagOp op, const ValueNames& names) const override
    {
        const std::string tag = memberOf(op.getObject(), kPlanUnionTagMember).tsName;
        w.line("(" + names(op.getObject()) + " as { " + tag + ": number })." + tag + " = " +
               asNumber(op.getValue(), names) + ";");
    }

    [[nodiscard]] std::string writeBits(mlir::dsdl::WriteBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string width     = std::to_string(op.getWidth());
        const std::string value     = names(op.getValue());
        const std::string prefix    = names(op.getBuffer()) + ", " + asNumber(op.getBitOffset(), names) + ", ";
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return file_.runtime() + ".writeFloat(" + prefix + width + ", " + value + ")";
        }
        if (isBool(valueType))
        {
            return file_.runtime() + ".setBit(" + prefix + value + ")";
        }
        return file_.runtime() + "." + std::string(op.getIsSigned() ? "writeSigned(" : "writeUnsigned(") + prefix +
               width + ", " + value + ", false)";
    }

    [[nodiscard]] std::string readBits(mlir::dsdl::ReadBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string arguments =
            names(op.getBuffer()) + ", " + asNumber(op.getBitOffset(), names) + ", " + std::to_string(op.getWidth());
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return file_.runtime() + ".readFloat(" + arguments + ")";
        }
        const std::string read = file_.runtime() + "." +
                                 std::string(op.getIsSigned() ? "readSignedBigInt(" : "readUnsignedBigInt(") +
                                 arguments + ")";
        return cast(read, mlir::IntegerType::get(op.getContext(), 64), valueType);
    }

    void bitWrite(SourceWriter& /*w*/, mlir::dsdl::BitWriteOp /*op*/, const ValueNames& /*names*/) const override
    {
        // A bool array holds a bool per element, so each of its runs reaches TypeScript expanded.
        llvm::report_fatal_error("TypeScript spelling: a bool run reaches TypeScript expanded to dsdl.write_bit");
    }

    void bitRead(SourceWriter& /*w*/, mlir::dsdl::BitReadOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("TypeScript spelling: a bool run reaches TypeScript expanded to dsdl.read_bit");
    }

    void writeBit(SourceWriter& w, mlir::dsdl::WriteBitOp op, const ValueNames& names) const override
    {
        w.line(file_.runtime() + ".setBit(" + names(op.getBuffer()) + ", " + asNumber(op.getBitOffset(), names) + ", " +
               names(op.getValue()) + ");");
    }

    [[nodiscard]] std::string readBit(mlir::dsdl::ReadBitOp op, const ValueNames& names) const override
    {
        return file_.runtime() + ".getBit(" + names(op.getBuffer()) + ", " + asNumber(op.getBitOffset(), names) + ")";
    }

    void imageRead(SourceWriter& /*w*/, mlir::dsdl::ImageReadOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("TypeScript spelling: a host-image move is not spelled here, and the fold that "
                                 "produces one does not run for this target");
    }

    void imageWrite(SourceWriter& /*w*/, mlir::dsdl::ImageWriteOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("TypeScript spelling: a host-image move is not spelled here, and the fold that "
                                 "produces one does not run for this target");
    }

    // A view member is a subarray of the buffer, or one element of an array of them.
    /// @brief A view member, or the element of an array of views that @p index names.
    std::string viewTarget(const mlir::Value     object,
                           const llvm::StringRef member,
                           const mlir::Value     index,
                           const ValueNames&     names) const
    {
        return index ? elementAccess(object, member, asNumber(index, names), names)
                     : memberAccess(object, member, names);
    }

    [[nodiscard]] std::string viewBytes(mlir::dsdl::LoadViewOp op, const ValueNames& names) const override
    {
        return viewTarget(op.getObject(), op.getMember(), op.getIndex(), names);
    }

    [[nodiscard]] std::string viewSize(mlir::dsdl::LoadViewOp op, const ValueNames& names) const override
    {
        return "BigInt(" + viewTarget(op.getObject(), op.getMember(), op.getIndex(), names) + ".length)";
    }

    void storeView(SourceWriter& w, mlir::dsdl::StoreViewOp op, const ValueNames& names) const override
    {
        const std::string bytes = names(op.getBytes());
        w.line(viewTarget(op.getObject(), op.getMember(), op.getIndex(), names) + " = " + bytes +
               ".subarray(0, Math.min(" + asNumber(op.getSizeBytes(), names) + ", " + bytes + ".length));");
    }

    void clearView(SourceWriter& w, mlir::dsdl::ClearViewOp op, const ValueNames& names) const override
    {
        // A fixed array of views is every element empty; a variable-length one is sized by the plan.
        mlir::dsdl::IOOp io = memberOf(op.getObject(), op.getMember()).io;
        w.line(memberAccess(op.getObject(), op.getMember(), names) + " = " +
               ((io.getArrayKind() == "fixed")
                    ? "Array.from({ length: " + std::to_string(io.getArrayCapacity()) + " }, () => new Uint8Array(0))"
                    : "new Uint8Array(0)") +
               ";");
    }

    void copyBytes(SourceWriter& w, mlir::dsdl::CopyBytesOp op, const ValueNames& names) const override
    {
        // What the view holds, up to the width, then zeros to the width. The plan's capacity check
        // established the width at the destination.
        const std::string destination = names(op.getDestination());
        const std::string source      = names(op.getSource());
        const std::string width       = std::to_string(op.getBytes());
        const std::string copied      = fresh("copied");
        w.line("const " + copied + " = Math.min(" + asNumber(op.getSourceSizeBytes(), names) + ", " + source +
               ".length, " + width + ");");
        w.line(destination + ".set(" + source + ".subarray(0, " + copied + "), 0);");
        w.line(destination + ".fill(0, " + copied + ", " + width + ");");
    }

    [[nodiscard]] std::string callSerdes(mlir::dsdl::CallSerdesOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error(
            "TypeScript spelling: a nested call reaches TypeScript folded to dsdl.call_serdes_sized");
    }

    void declareCallSerdes(SourceWriter& /*w*/,
                           const llvm::StringRef /*name*/,
                           mlir::dsdl::CallSerdesOp /*op*/,
                           const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error(
            "TypeScript spelling: a nested call reaches TypeScript folded to dsdl.call_serdes_sized");
    }

    void declareCallSerdesSized(SourceWriter&                 w,
                                const llvm::StringRef         error,
                                const llvm::StringRef         consumed,
                                mlir::dsdl::CallSerdesSizedOp op,
                                const ValueNames&             names) const override
    {
        // The nested value serialises itself into the subarray from the buffer's offset, which ends
        // where the space the plan offers does or the buffer does, and answers what it used or a
        // negative code. What it used means something only where the code is zero, so it holds
        // the answer as it came, and the code is read off it.
        const std::string buffer = names(op.getBuffer());
        const std::string call =
            nestedFunction(op) + "(" + names(op.getObject()) + ", " + buffer + ".subarray(0, " +
            cast(names(op.getAvailable()), op.getAvailable().getType(), mlir::IndexType::get(op.getContext())) + "))";
        if (consumed.empty() && error.empty())
        {
            discard(w, call);
            return;
        }
        if (consumed.empty())
        {
            declare(w, op.getError().getType(), error, "Math.min(" + call + ", 0)");
            return;
        }
        declare(w, op.getConsumed().getType(), consumed, call);
        if (!error.empty())
        {
            declare(w, op.getError().getType(), error, consumed.str() + " < 0 ? " + consumed.str() + " : 0");
        }
    }

private:
    struct Member final
    {
        std::string      tsName;
        mlir::dsdl::IOOp io;
    };

    struct Plan final
    {
        std::string             typeName;
        bool                    isUnion{false};
        llvm::StringMap<Member> members;
    };

    /// @brief The plan the object a pointer names belongs to.
    const Plan& planOf(const mlir::Value object) const
    {
        const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(object.getType());
        const auto identity =
            pointer ? mlir::dyn_cast<mlir::dsdl::ObjectType>(pointer.getPointee()) : mlir::dsdl::ObjectType{};
        const auto found = identity ? plans_.find(identity.getIdentity()) : plans_.end();
        if (found == plans_.end())
        {
            llvm::report_fatal_error("TypeScript spelling: an object that no plan of this schema describes");
        }
        return found->second;
    }

    Member memberOf(const mlir::Value object, const llvm::StringRef member) const
    {
        const Plan& plan  = planOf(object);
        const auto  found = plan.members.find(member);
        if (found == plan.members.end())
        {
            llvm::report_fatal_error("TypeScript spelling: a member the schema does not declare: " + member);
        }
        return found->second;
    }

    /// @brief The body function of the nested type a call names.
    std::string nestedFunction(mlir::dsdl::CallSerdesSizedOp op) const
    {
        const std::optional<PlanSymbol> callee = parsePlanSymbol(op.getCallee());
        if (!callee)
        {
            llvm::report_fatal_error("TypeScript spelling: a nested call to a function that is no body");
        }
        return file_.function(renderSchemaSymbol(callee->schema), op.getCallee());
    }

    /// @brief The member as the object declares it; an option through the object cast to its shape.
    std::string memberAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        const Plan&  plan  = planOf(object);
        const Member found = memberOf(object, member);
        if (plan.isUnion)
        {
            return "(" + names(object) + " as { " + found.tsName + ": " + memberTsType(found) + " })." + found.tsName;
        }
        return names(object) + "." + found.tsName;
    }

    /// @brief An array member, which a deserialise body creates where it first addresses it.
    std::string containerAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        const std::string access = memberAccess(object, member, names);
        return deserialize_ ? "(" + access + " \?\?= [])" : access;
    }

    std::string elementAccess(const mlir::Value     object,
                              const llvm::StringRef member,
                              const std::string&    index,
                              const ValueNames&     names) const
    {
        return containerAccess(object, member, names) + "[" + index + "]";
    }

    // Members.

    static bool isArray(const Member& member)
    {
        mlir::dsdl::IOOp io = member.io;
        return io.isArray();
    }

    static bool isComposite(const Member& member)
    {
        mlir::dsdl::IOOp io = member.io;
        return io.isComposite();
    }

    /// @brief The kind of value a member or element holds.
    enum class Storage : std::uint8_t
    {
        Boolean,
        Number,
        BigInt,
        Float,
        Object,
    };

    static Storage storageOf(const Member& member)
    {
        mlir::dsdl::IOOp      io       = member.io;
        const llvm::StringRef category = io.getScalarCategory();
        if (io.isComposite())
        {
            return Storage::Object;
        }
        if (category == "bool")
        {
            return Storage::Boolean;
        }
        if (category == "float")
        {
            return Storage::Float;
        }
        // A number holds an integer exactly to 53 bits; a wider field is a bigint.
        return io.getBitLength() > 53 ? Storage::BigInt : Storage::Number;
    }

    /// @brief The TypeScript type of one element of @p member, or of the member when it is no array.
    std::string elementTsType(const Member& member) const
    {
        if (mlir::dsdl::IOOp{member.io}.getHeldAsView())
        {
            return "Uint8Array";
        }
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return "boolean";
        case Storage::Number:
        case Storage::Float:
            return "number";
        case Storage::BigInt:
            return "bigint";
        case Storage::Object:
            break;
        }
        return file_.type(typeRefOf(member.io));
    }

    std::string memberTsType(const Member& member) const
    {
        return isArray(member) ? "Array<" + elementTsType(member) + ">" : elementTsType(member);
    }

    /// @brief @p access read as a value of @p type.
    [[nodiscard]] std::string loadedValue(const std::string& access, const Member& member, const mlir::Type type) const
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            if (isBool(type))
            {
                return access;
            }
            return isBig(type) ? "(" + access + " ? 1n : 0n)" : "(" + access + " ? 1 : 0)";
        case Storage::BigInt:
            return isBig(type) ? access : "Number(" + access + ")";
        case Storage::Number:
            // A number a caller stored may be no integer; the runtime rounds it to one.
            return isBig(type) ? file_.runtime() + ".toBigIntValue(" + access + ")" : "Math.trunc(" + access + ")";
        case Storage::Float:
        case Storage::Object:
            break;
        }
        return access;
    }

    /// @brief @p value, of @p type, converted for storage in @p member.
    static std::string storedValue(const std::string& value, const mlir::Type type, const Member& member)
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            if (isBool(type))
            {
                return value;
            }
            return isBig(type) ? value + " !== 0n" : value + " !== 0";
        case Storage::BigInt:
            return isBig(type) ? value : "BigInt(" + value + ")";
        case Storage::Number:
            if (isBig(type))
            {
                return "Number(" + value + ")";
            }
            return isBool(type) ? "(" + value + " ? 1 : 0)" : value;
        case Storage::Float:
        case Storage::Object:
            break;
        }
        return value;
    }

    // Types.

    static bool isBool(const mlir::Type type)
    {
        return type.isInteger(1);
    }

    /// @brief Whether @p type is the plan's `i64`, a bigint.
    static bool isBig(const mlir::Type type)
    {
        return type.isInteger(64);
    }

    /// @brief @p value, of @p from, as a value of @p to.
    static std::string cast(const std::string& value, const mlir::Type from, const mlir::Type to)
    {
        if (from == to)
        {
            return value;
        }
        if (isBool(to))
        {
            return "(" + value + (isBig(from) ? " !== 0n)" : " !== 0)");
        }
        if (isBig(to))
        {
            return isBool(from) ? "(" + value + " ? 1n : 0n)" : "BigInt(" + value + ")";
        }
        if (isBool(from))
        {
            return "(" + value + " ? 1 : 0)";
        }
        if (isBig(from))
        {
            return to.isInteger(8) ? "Number(BigInt.asIntN(8, " + value + "))" : "Number(" + value + ")";
        }
        return value;
    }

    /// @brief @p value as a number, which an offset, a size and an index are.
    static std::string asNumber(const mlir::Value value, const ValueNames& names)
    {
        return cast(names(value), value.getType(), mlir::IndexType::get(value.getContext()));
    }

    static std::string typeName(const mlir::Type type)
    {
        if (mlir::isa<mlir::IndexType>(type) || mlir::isa<mlir::FloatType>(type))
        {
            return "number";
        }
        if (const auto integer = mlir::dyn_cast<mlir::IntegerType>(type))
        {
            if (integer.getWidth() == 1)
            {
                return "boolean";
            }
            return integer.getWidth() == 64 ? "bigint" : "number";
        }
        if (const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(type))
        {
            if (mlir::isa<mlir::dsdl::ByteType>(pointer.getPointee()))
            {
                return "Uint8Array";
            }
            if (mlir::isa<mlir::dsdl::SizeType>(pointer.getPointee()))
            {
                return "number";
            }
        }
        llvm::report_fatal_error("TypeScript spelling: a value of a type no plan body carries");
    }

    static std::string operatorToken(const BinaryOperator op)
    {
        switch (op)
        {
        case BinaryOperator::Add:
            return "+";
        case BinaryOperator::Sub:
            return "-";
        case BinaryOperator::Mul:
            return "*";
        case BinaryOperator::DivU:
        case BinaryOperator::DivS:
            return "/";
        case BinaryOperator::RemU:
        case BinaryOperator::RemS:
            return "%";
        case BinaryOperator::And:
            return "&";
        case BinaryOperator::Or:
            return "|";
        case BinaryOperator::Xor:
            return "^";
        case BinaryOperator::ShiftLeft:
            return "<<";
        case BinaryOperator::ShiftRightU:
        case BinaryOperator::ShiftRightS:
            return ">>";
        }
        llvm::report_fatal_error("TypeScript spelling: an operator of an unexpected kind");
    }

    static std::string comparisonToken(const Comparison comparison)
    {
        switch (comparison)
        {
        case Comparison::Eq:
            return "===";
        case Comparison::Ne:
            return "!==";
        case Comparison::LtS:
        case Comparison::LtU:
            return "<";
        case Comparison::LeS:
        case Comparison::LeU:
            return "<=";
        case Comparison::GtS:
        case Comparison::GtU:
            return ">";
        case Comparison::GeS:
        case Comparison::GeU:
            return ">=";
        }
        llvm::report_fatal_error("TypeScript spelling: a comparison of an unexpected kind");
    }

    /// @brief A name for a value of this spelling's own, distinct from the translator's.
    std::string fresh(const char* const stem) const
    {
        return "_" + std::string(stem) + std::to_string(fresh_++) + "_";
    }

    const TsFileNames&    file_;
    const TsSurface&      names_;
    llvm::StringMap<Plan> plans_;
    /// @brief The tag steps of the union plans, which belong to no plan and live here.
    std::vector<mlir::OwningOpRef<mlir::dsdl::IOOp>> tagSteps_;

    /// @brief The plan and the member an accessor reaches, through its schema and section name.
    struct Accessed final
    {
        const Plan*   plan;
        const Member* member;
    };
    Accessed accessed(mlir::func::FuncOp fn) const
    {
        auto       module     = fn->getParentOfType<mlir::ModuleOp>();
        const auto schemaSym  = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.schema_sym");
        const auto section    = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        const auto memberName = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.member");
        auto       schema =
            schemaSym ? module.lookupSymbol<mlir::dsdl::SchemaOp>(schemaSym.getValue()) : mlir::dsdl::SchemaOp{};
        if (!schema || !memberName)
        {
            llvm::report_fatal_error("TypeScript spelling: an accessor that names no schema or no member");
        }
        const auto plan  = sectionPlan(schema, section ? section.getValue() : llvm::StringRef{});
        const auto found = plans_.find(planIdentity(schema, plan));
        if (found == plans_.end())
        {
            llvm::report_fatal_error("TypeScript spelling: an accessor of a plan this schema does not describe");
        }
        const auto member = found->second.members.find(memberName.getValue());
        if (member == found->second.members.end())
        {
            llvm::report_fatal_error("TypeScript spelling: an accessor of a member the plan does not declare");
        }
        return Accessed{&found->second, &member->second};
    }

    /// @brief Which accessor, if any, the function being opened is; how its return is spelt.
    enum class Accessor : std::uint8_t
    {
        None,
        Getter,
        Setter
    };
    mutable Accessor    accessor_{Accessor::None};
    mutable std::string returnCast_;
    mutable bool        deserialize_{false};
    mutable unsigned    fresh_{0};
};

/// @brief The symbol of @p function.
llvm::StringRef symbolOf(mlir::func::FuncOp function)
{
    return function.getSymName();
}

/// @brief The three bodies `lower-dsdl-bodies` built for one section.
struct SectionBodies final
{
    mlir::func::FuncOp serialize;
    mlir::func::FuncOp deserialize;
    mlir::func::FuncOp initialize;
    /// @brief The section's field accessors, getters and setters, in the module's order.
    std::vector<mlir::func::FuncOp> accessors;
};

/// @brief The entry points a consumer calls, which wrap the translated bodies: a value serialises
/// into a buffer of the type's largest size, and a deserialisation fills an empty object.
void emitEntryPoints(SourceWriter&          w,
                     const TsSection&       names,
                     const SemanticSection& section,
                     const TsFileNames&     file,
                     const SectionBodies&   bodies)
{
    const TsSurface&   surface     = names.names();
    const std::string& typeName    = names.typeName();
    const std::string  raise       = "throw new Error(" + file.runtime() + ".errorMessage(result));";
    const auto         bufferBytes = (section.serializationBufferSizeBits + 7) / 8;
    w.open("export function " +
           surface.function(symbolOf(bodies.serialize), SurfaceDeclKind::Wrapper, GeneratedFact::WireImage) +
           "(value: " + typeName + "): Uint8Array {");
    w.line("const buffer = new Uint8Array(" + std::to_string(bufferBytes) + ");");
    w.line("const result = " + surface.function(symbolOf(bodies.serialize), SurfaceDeclKind::Entry) +
           "(value, buffer);");
    w.open("if (result < 0) {");
    w.line(raise);
    w.close("}");
    w.line("return buffer.subarray(0, result);");
    w.close("}");
    w.blank();
    w.open("export function " +
           surface.function(symbolOf(bodies.deserialize), SurfaceDeclKind::Wrapper, GeneratedFact::FromWireImage) +
           "(bytes: Uint8Array): { value: " + typeName + "; consumed: number } {");
    w.line("const value = " + surface.function(symbolOf(bodies.initialize), SurfaceDeclKind::Entry) + "();");
    w.line("const result = " + surface.function(symbolOf(bodies.deserialize), SurfaceDeclKind::Entry) +
           "(value, bytes);");
    w.open("if (result < 0) {");
    w.line(raise);
    w.close("}");
    w.line("return { value, consumed: result };");
    w.close("}");
}

/// @brief The literal a stored constant is, for a member of @p type.
std::string tsStoredLiteral(const SemanticFieldType& type, const mlir::TypedAttr value)
{
    if (const auto integer = mlir::dyn_cast_or_null<mlir::IntegerAttr>(value))
    {
        if (type.scalarCategory == SemanticScalarCategory::Bool)
        {
            return integer.getInt() != 0 ? "true" : "false";
        }
        // A 64-bit member is a bigint in the interface; the rest are numbers.
        const bool big = type.bitLength > 53;
        return std::to_string(integer.getInt()) + (big ? "n" : "");
    }
    if (const auto real = mlir::dyn_cast_or_null<mlir::FloatAttr>(value))
    {
        std::string text = std::to_string(real.getValueAsDouble());
        text.erase(text.find_last_not_of('0') + 1);
        if (text.ends_with('.'))
        {
            text += '0';
        }
        return text;
    }
    llvm::report_fatal_error("TypeScript: an initialise body stored a value that is neither integer nor float");
}

/// @brief The value a member takes in the factory's literal, as the initialise body states it.
std::string tsDefaultFromBody(const SemanticField& field, const MemberDefault& entry, const TsFileNames& file)
{
    const auto& type   = field.resolvedType;
    const auto  nested = [&]() { return type.compositeType ? file.make(*type.compositeType) + "()" : "{}"; };
    switch (entry.kind)
    {
    case MemberDefault::Kind::Scalar:
        return tsStoredLiteral(type, entry.value);
    case MemberDefault::Kind::VariableArrayEmpty:
        return "[]";
    case MemberDefault::Kind::FixedScalarArray: {
        SemanticFieldType element = type;
        element.arrayKind         = ArrayKind::None;
        return "new Array<" + tsFieldType(element, file) + ">(" + std::to_string(entry.count) + ").fill(" +
               tsStoredLiteral(type, entry.value) + ")";
    }
    case MemberDefault::Kind::BoolArray:
        return "new Array<boolean>(" + std::to_string(entry.count) + ").fill(false)";
    case MemberDefault::Kind::FixedCompositeArray:
        return "Array.from({ length: " + std::to_string(entry.count) + " }, () => " + nested() + ")";
    case MemberDefault::Kind::Composite:
        return nested();
    case MemberDefault::Kind::View:
        return (type.arrayKind == ArrayKind::Fixed)
                   ? "Array.from({ length: " + std::to_string(type.arrayCapacity) + " }, () => new Uint8Array(0))"
                   : "new Uint8Array(0)";
    }
    return "undefined";
}

/// @brief The factory: the type at its defaults, as an object literal read off the initialise body.
///
/// A union is one arm, so the literal is the arm the body's tag selects at the default the body
/// gives it; the other arms have no place in the value.
void emitMakeFunction(SourceWriter&           w,
                      const TsSection&        names,
                      const std::string&      make,
                      const SemanticSection&  section,
                      const InitializerShape& init,
                      const TsFileNames&      file)
{
    const std::string& typeName = names.typeName();
    const auto         entryOf  = [&](const SemanticField& field) -> const MemberDefault& {
        for (const auto& entry : init.members)
        {
            if (entry.member == field.name)
            {
                return entry;
            }
        }
        llvm::report_fatal_error(llvm::Twine("TypeScript: the initialise body of ") + typeName + " does not set '" +
                                 field.name + "'");
    };
    w.open("export function " + make + "(): " + typeName + " {");
    if (section.isUnion)
    {
        std::string arm;
        for (const auto& field : section.fields)
        {
            if (!field.isPadding && std::cmp_equal(field.unionOptionIndex, init.unionTag))
            {
                arm = ", " + names.field(field.name) + ": " + tsDefaultFromBody(field, entryOf(field), file);
            }
        }
        w.line("return { " + names.dataMember(GeneratedFact::UnionTag) + ": " + std::to_string(init.unionTag) + arm +
               " };");
    }
    else
    {
        w.open("return {");
        for (const auto& field : section.fields)
        {
            if (field.isPadding)
            {
                continue;
            }
            w.line(names.field(field.name) + ": " + tsDefaultFromBody(field, entryOf(field), file) + ",");
        }
        w.close("};");
    }
    w.close("}");
}

/// @brief One section: its type, its constants, its three bodies and the entry points that wrap them.
llvm::Error emitSection(SourceWriter&             w,
                        const TsSection&          names,
                        const SemanticSection&    section,
                        const SectionMetadata&    metadata,
                        const AttachedDoc&        typeDoc,
                        const TsFileNames&        file,
                        const SemanticDefinition& def,
                        const TsSpelling&         spelling,
                        const SectionBodies&      bodies,
                        PlanBodyLookups&          lookups)
{
    // The object type and its factory, which an accessors-only run leaves out.
    if (!file.context().accessorsOnly())
    {
        if (!bodies.serialize || !bodies.deserialize || !bodies.initialize)
        {
            return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                           "no plan bodies for %s in the lowered module",
                                           metadata.fullName.c_str());
        }
        auto init = readInitializer(bodies.initialize);
        if (!init)
        {
            return init.takeError();
        }
        emitSectionType(w,
                        names,
                        section,
                        typeDoc,
                        file,
                        def.info.fullName,
                        def.info.majorVersion,
                        def.info.minorVersion);
        w.blank();
        emitMakeFunction(w,
                         names,
                         names.names().function(symbolOf(bodies.initialize), SurfaceDeclKind::Entry),
                         section,
                         *init,
                         file);
        w.blank();
    }
    emitUnionOptionTags(w, names, metadata);
    emitSectionConstants(w, names, section);
    w.blank();
    if (!file.context().accessorsOnly())
    {
        if (auto err = translateFunction(bodies.serialize, spelling, w, lookups))
        {
            return err;
        }
        w.blank();
        if (auto err = translateFunction(bodies.deserialize, spelling, w, lookups))
        {
            return err;
        }
    }
    // A wire-flat section's field accessors: each is one read or one write at the field's offset.
    for (const mlir::func::FuncOp accessor : bodies.accessors)
    {
        w.blank();
        if (auto err = translateFunction(accessor, spelling, w, lookups))
        {
            return err;
        }
    }
    if (!file.context().accessorsOnly())
    {
        w.blank();
        emitEntryPoints(w, names, section, file, bodies);
    }
    return llvm::Error::success();
}

llvm::Expected<std::string> renderDefinitionFile(const SemanticDefinition& def,
                                                 const EmitterContext&     ctx,
                                                 mlir::ModuleOp            module,
                                                 PlanBodyLookups&          lookups)
{
    mlir::dsdl::SchemaOp schema = schemaOf(module, def);
    if (!schema)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no schema for %s in the lowered module",
                                       def.info.fullName.c_str());
    }

    // The declarations and bodies first, naming what they take from other modules as they write it;
    // the imports are written after, from what was named.
    const TsSurface&                     names = ctx.names();
    const std::string                    key   = keyOf(def.info);
    ImportSet                            imports;
    const TsFileNames                    file(ctx, imports, key);
    const TsSpelling                     spelling(schema, names, file);
    std::vector<mlir::func::FuncOp>      helpers;
    std::map<std::string, SectionBodies> bodies;
    for (const mlir::func::FuncOp fn : schemaFunctions(module, schema.getSymName()))
    {
        const auto direction = planBodyDirection(fn);
        if (!direction)
        {
            // A helper nothing calls is left out; an accessors-only run has many.
            if (fn->hasAttr("llvmdsdl.unreferenced"))
            {
                continue;
            }
            helpers.push_back(fn);
            continue;
        }
        const auto     sectionAttr = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        SectionBodies& entry       = bodies[sectionAttr ? sectionAttr.getValue().str() : std::string{}];
        if (*direction == "serialize")
        {
            entry.serialize = fn;
        }
        else if (*direction == "deserialize")
        {
            entry.deserialize = fn;
        }
        else if (*direction == "initialize")
        {
            entry.initialize = fn;
        }
        else if (*direction == "get" || *direction == "set")
        {
            entry.accessors.push_back(fn);
        }
        else
        {
            llvm::report_fatal_error(llvm::Twine("unknown plan body direction '") + *direction + "'");
        }
    }

    std::ostringstream head;
    {
        SourceWriter hw = makeTsWriter(head);
        hw.line(generatedCommentLine("TypeScript backend"));
        hw.line("// Source: " + def.info.fullName + "." + std::to_string(def.info.majorVersion) + "." +
                std::to_string(def.info.minorVersion));
    }
    std::ostringstream out;
    SourceWriter       w        = makeTsWriter(out);
    const auto         assemble = [&]() { return head.str() + renderTsImports(imports) + out.str(); };

    const auto constant = [&names, &key](const GeneratedFact fact, const llvm::StringRef section = {}) {
        return "export const " + names.declared(key, SurfaceDeclKind::Constant, section, {}, fact) + " = ";
    };
    w.line(constant(GeneratedFact::GeneratorVersion) + "\"" + std::string(llvmdsdl::kVersionString) + "\";");
    w.line(constant(GeneratedFact::FullName) + "\"" + def.info.fullName + "\";");
    w.line(constant(GeneratedFact::IsDeprecated) + std::string(def.request.deprecated ? "true" : "false") + ";");
    w.line(constant(GeneratedFact::VersionMajor) + std::to_string(def.info.majorVersion) + ";");
    w.line(constant(GeneratedFact::VersionMinor) + std::to_string(def.info.minorVersion) + ";");
    w.line(constant(GeneratedFact::HasFixedPortId) + std::string(def.info.fixedPortId ? "true" : "false") + ";");
    if (def.info.fixedPortId)
    {
        w.line(constant(GeneratedFact::FixedPortId) + std::to_string(*def.info.fixedPortId) + ";");
    }
    // Aliasability is a property of a payload, so a service answers for each of its two and a
    // message answers once, under the name of the thing the verdict is about.
    const auto emitLayoutVerdicts = [&w, &constant, schema](const llvm::StringRef section) {
        const mlir::dsdl::SerializationPlanOp plan = sectionPlan(schema, section);
        const AliasVerdict                    flat = wireFlatVerdict(plan);
        w.line(constant(GeneratedFact::WireFlat, section) + std::string(flat.holds ? "true" : "false") + ";");
        w.line(constant(GeneratedFact::WireFlatReason, section) + "\"" + flat.reason + "\";");
    };
    if (def.isService)
    {
        emitLayoutVerdicts("request");
        emitLayoutVerdicts("response");
    }
    else
    {
        emitLayoutVerdicts("");
    }
    w.blank();

    for (const mlir::func::FuncOp helper : helpers)
    {
        if (auto err = translateFunction(helper, spelling, w, lookups))
        {
            return std::move(err);
        }
        w.blank();
    }

    if (!def.isService)
    {
        if (auto err = emitSection(w,
                                   TsSection(names, key, ""),
                                   def.request,
                                   sectionMetadata(def.info, def.request, schema, ""),
                                   def.doc,
                                   file,
                                   def,
                                   spelling,
                                   bodies[""],
                                   lookups))
        {
            return std::move(err);
        }
        return assemble();
    }

    const TsSection request(names, key, "request");
    if (auto err = emitSection(w,
                               request,
                               def.request,
                               sectionMetadata(def.info, def.request, schema, "request"),
                               def.doc,
                               file,
                               def,
                               spelling,
                               bodies["request"],
                               lookups))
    {
        return std::move(err);
    }
    w.blank();

    if (def.response)
    {
        if (auto err = emitSection(w,
                                   TsSection(names, key, "response"),
                                   *def.response,
                                   sectionMetadata(def.info, *def.response, schema, "response"),
                                   def.doc,
                                   file,
                                   def,
                                   spelling,
                                   bodies["response"],
                                   lookups))
        {
            return std::move(err);
        }
        w.blank();
    }

    // The alias names the request's object type, which an accessors-only run does not emit.
    const SurfaceDecl* const alias =
        names.tree().find(names.file(key), SurfaceDeclKind::Alias, SurfaceEntity{key, "", "", ""});
    if (!ctx.accessorsOnly() && (alias != nullptr))
    {
        w.line("export type " + alias->name + " = " + request.typeName() + ";");
    }
    return assemble();
}

std::string renderPackageJson(const Options& options)
{
    const auto* const runtimeSpecialization =
        options.runtimeSpecialization == RuntimeSpecialization::Fast ? "fast" : "portable";
    std::ostringstream out;
    out << "{\n";
    out << R"(  "name": ")" << options.moduleName << "\",\n";
    out << R"(  "version": ")" << llvmdsdl::kVersionString << "\",\n";
    out << "  \"type\": \"module\",\n";
    out << "  \"llvmdsdl\": {\n";
    out << R"(    "generatorVersion": ")" << llvmdsdl::kVersionString << "\",\n";
    out << R"(    "tsRuntimeSpecialization": ")" << runtimeSpecialization << "\"\n";
    out << "  }\n";
    out << "}\n";
    return out.str();
}

/// @brief The runtime the generated modules call, for @p runtimeSpecialization, from the source
///        carried in this binary.
llvm::Expected<std::string> loadTsRuntimeModule(const RuntimeSpecialization runtimeSpecialization)
{
    const std::string key =
        (runtimeSpecialization == RuntimeSpecialization::Fast) ? "ts/dsdl_runtime_fast.ts" : "ts/dsdl_runtime.ts";
    if (const auto data = embedded_sources::find(key))
    {
        return generatedCommentLine("TypeScript runtime scaffold") + "\n\n" + std::string(*data);
    }
    return llvm::createStringError(llvm::inconvertibleErrorCode(), "embedded runtime source missing: %s", key.c_str());
}

}  // namespace

llvm::Error emit(const SemanticModule& semantic, mlir::ModuleOp module, const Options& options)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }

    std::filesystem::path const outRoot(options.outDir);
    const auto                  selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }
    const bool emitSupport = shouldEmitSupport(options.supportGeneration, anyTypeEmitted);

    if (emitSupport)
    {
        if (options.emitPackageJson)
        {
            if (auto err =
                    writeGeneratedFile(outRoot / "package.json", renderPackageJson(options), options.writePolicy))
            {
                return err;
            }
        }
        auto runtime = loadTsRuntimeModule(options.runtimeSpecialization);
        if (!runtime)
        {
            return runtime.takeError();
        }
        if (auto err = writeGeneratedFile(outRoot / "dsdl_runtime.ts", *runtime, options.writePolicy))
        {
            return err;
        }
    }

    auto tree = SurfaceTree::read(module, languageTraits(Language::TypeScript));
    if (!tree)
    {
        return tree.takeError();
    }
    const TsSurface      names(*tree);
    const EmitterContext ctx(semantic, names, options.accessorsOnly);

    std::vector<const SemanticDefinition*> ordered;
    ordered.reserve(semantic.definitions.size());
    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        ordered.push_back(&def);
    }
    std::ranges::sort(ordered, [](const auto* lhs, const auto* rhs) {
        if (lhs->info.fullName != rhs->info.fullName)
        {
            return lhs->info.fullName < rhs->info.fullName;
        }
        if (lhs->info.majorVersion != rhs->info.majorVersion)
        {
            return lhs->info.majorVersion < rhs->info.majorVersion;
        }
        return lhs->info.minorVersion < rhs->info.minorVersion;
    });

    std::vector<std::string> generatedRelativePaths;
    generatedRelativePaths.reserve(ordered.size());
    PlanBodyLookups lookups(module);

    for (const auto* def : ordered)
    {
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def->info)};
        const std::string&             relPath = names.path(keyOf(def->info));
        generatedRelativePaths.push_back(relPath);

        const auto fullPath = outRoot / relPath;
        auto       rendered = renderDefinitionFile(*def, ctx, module, lookups);
        if (!rendered)
        {
            return rendered.takeError();
        }

        if (auto err = writeGeneratedFile(fullPath, *rendered, options.writePolicy, requiredTypeKeys))
        {
            return err;
        }
    }

    std::ostringstream index;
    SourceWriter       indexW = makeTsWriter(index);
    indexW.line(generatedCommentLine("TypeScript backend index"));
    std::map<std::string, unsigned> aliasUseCount;
    for (const auto& relPath : generatedRelativePaths)
    {
        std::string modulePath = relPath;
        if (modulePath.size() >= 3 && modulePath.ends_with(".ts"))
        {
            modulePath.resize(modulePath.size() - 3);
        }
        std::string alias    = moduleAliasFromPath(modulePath);
        unsigned&   useCount = aliasUseCount[alias];
        if (useCount > 0)
        {
            alias += "_" + std::to_string(useCount);
        }
        ++useCount;

        // NOLINTNEXTLINE(performance-inefficient-string-concatenation)
        indexW.line("export * as " + alias + " from \"./" + modulePath + "\";");
    }

    if (auto err = writeGeneratedFile(outRoot / "index.ts", index.str(), options.writePolicy, options.selectedTypeKeys))
    {
        return err;
    }

    return llvm::Error::success();
}

}  // namespace llvmdsdl::emitter::ts
