//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Implements TypeScript backend code emission from lowered DSDL modules.
///
/// This file emits TypeScript models and the entry points a consumer calls; the serialise and
/// deserialise bodies those wrap are translations of the plan bodies through `TsSpelling`.
///
/// The line-building concatenations here carry NOLINT for
/// performance-inefficient-string-concatenation. Each one spells out a line of generated
/// source, and an append sequence would cost the reader the line itself.
///
//===----------------------------------------------------------------------===//

#include "llvmdsdl/CodeGen/BodyTranslator.h"
#include "llvmdsdl/CodeGen/EmitCommon.h"
#include "llvmdsdl/CodeGen/SectionNaming.h"
#include "llvmdsdl/CodeGen/SourceWriter.h"
#include "llvmdsdl/CodeGen/emitter/Ts.h"

#include <algorithm>
#include <cassert>
#include <llvm/ADT/StringRef.h>
#include <cctype>
#include <filesystem>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <string>
#include <vector>
#include <cstddef>
#include <cstdint>
#include <utility>

#include "llvmdsdl/CodeGen/CodegenDiagnosticText.h"
#include "llvmdsdl/CodeGen/CompositeImportGraph.h"
#include "llvmdsdl/CodeGen/ConstantLiteralRender.h"
#include "llvmdsdl/CodeGen/DefinitionIndex.h"
#include "llvmdsdl/CodeGen/DefinitionPathProjection.h"
#include "llvmdsdl/Support/DefinitionNaming.h"
#include "llvmdsdl/Support/NamingPolicy.h"
#include "llvmdsdl/CodeGen/HelperBindingNaming.h"
#include "llvmdsdl/CodeGen/SchemaLookup.h"
#include "llvm/Support/Error.h"
#include "llvm/Support/raw_ostream.h"
#include "llvmdsdl/Frontend/AST.h"
#include "llvmdsdl/Semantics/Evaluator.h"
#include "llvmdsdl/Semantics/Model.h"
#include "llvmdsdl/Version.h"
#include "llvmdsdl/IR/DSDLOps.h"
#include "llvmdsdl/IR/DSDLTypes.h"
#include "llvmdsdl/Transforms/PlanSteps.h"
#include <llvm/ADT/ArrayRef.h>
#include <llvm/ADT/STLExtras.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/ADT/StringExtras.h>
#include <llvm/ADT/StringMap.h>
#include <llvm/Support/ErrorHandling.h>
#include <mlir/Dialect/Func/IR/FuncOps.h>
#include <mlir/IR/BuiltinAttributeInterfaces.h>
#include <mlir/IR/BuiltinAttributes.h>
#include <mlir/IR/BuiltinTypeInterfaces.h>
#include <mlir/IR/BuiltinTypes.h>
#include <mlir/IR/SymbolTable.h>
#include <mlir/IR/Types.h>
#include <mlir/IR/Value.h>
#include <mlir/Support/LLVM.h>
#include <cmath>
#include <functional>
#include <iomanip>
#include "mlir/IR/BuiltinOps.h"

namespace llvmdsdl::emitter::ts
{

namespace
{

std::string tsConstValue(const TypeExprAST& type, const Value& value)
{
    return renderConstantLiteral(ConstantLiteralLanguage::TypeScript, value, makeConstantTypeInfo(type));
}

SourceWriter makeTsWriter(std::ostringstream& out)
{
    return SourceWriter{out, IndentPolicy::spaces(2)};
}

std::string generatedCommentLine(llvm::StringRef detail)
{
    return "// Generated by llvmdsdl " + std::string(llvmdsdl::kVersionString) + " (" + detail.str() + ").";
}

void emitAttachedDocTs(SourceWriter& w, const AttachedDoc& doc)
{
    for (const auto& line : doc.lines)
    {
        w.line(line.text.empty() ? std::string{"//"} : "// " + line.text);
    }
}

class EmitterContext final
{
public:
    EmitterContext(const SemanticModule& semantic, const TypeNameVersioning typeNameVersioning)
        : index_(semantic)
        , typeNameVersioning_(typeNameVersioning)
    {
    }

    /// @brief Whether generated type names carry the definition's version.
    TypeNameVersioning typeNameVersioning() const
    {
        return typeNameVersioning_;
    }

    const SemanticDefinition* find(const SemanticTypeRef& ref) const
    {
        return index_.find(ref);
    }

    static std::string namespacePath(const DiscoveredDefinition& info)
    {
        return renderNamespaceRelativePath(CodegenNamingLanguage::TypeScript, info.namespaceComponents)
            .generic_string();
    }

    std::string typeName(const DiscoveredDefinition& info) const
    {
        return renderDefinitionTypeName(CodegenNamingLanguage::TypeScript,
                                        info.namespaceComponents,
                                        info.shortName,
                                        info.majorVersion,
                                        info.minorVersion,
                                        typeNameVersioning_);
    }

    /// @brief Local name for a *referenced* type in the file currently being emitted.
    ///
    /// @details
    /// Usually the plain versioned name the import brings in. It differs when one
    /// file references two types that share a short name from different namespaces --
    /// `uavcan.si.unit.angular_velocity.Vector3.1.0` and `uavcan.si.unit.velocity.Vector3.1.0` are
    /// both `Vector3_1_0`, and importing both under that name is a duplicate-identifier error that
    /// stops `tsc` outright. Such types are imported under a namespace-qualified alias instead, and
    /// this is where every reference site picks that alias up: the type annotations, the serialise
    /// and deserialise call names, and the import list all resolve through here, so they cannot
    /// disagree.
    std::string typeName(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            if (const auto alias = importAliases_.find(importAliasKey(def->info)); alias != importAliases_.end())
            {
                return alias->second;
            }
            return typeName(def->info);
        }

        DiscoveredDefinition tmp;
        tmp.shortName    = ref.shortName;
        tmp.majorVersion = ref.majorVersion;
        tmp.minorVersion = ref.minorVersion;
        return typeName(tmp);
    }

    /// @brief Identity of a definition for alias bookkeeping: unique across namespaces and versions.
    static std::string importAliasKey(const DiscoveredDefinition& info)
    {
        return info.fullName + ":" + std::to_string(info.majorVersion) + "." + std::to_string(info.minorVersion);
    }

    /// @brief Installs the alias table for the file about to be emitted, replacing any previous one.
    void setImportAliases(std::map<std::string, std::string> aliases) const
    {
        importAliases_ = std::move(aliases);
    }

    static std::string fileStem(const DiscoveredDefinition& info)
    {
        return renderVersionedFileStem(CodegenNamingLanguage::TypeScript,
                                       info.shortName,
                                       info.majorVersion,
                                       info.minorVersion);
    }

    static std::filesystem::path relativeFilePath(const DiscoveredDefinition& info)
    {
        return renderRelativeTypeFilePath(CodegenNamingLanguage::TypeScript, info, "ts");
    }

    std::filesystem::path relativeFilePath(const SemanticTypeRef& ref) const
    {
        if (const auto* def = find(ref))
        {
            return relativeFilePath(def->info);
        }

        return renderRelativeTypeFilePath(CodegenNamingLanguage::TypeScript, ref, "ts");
    }

private:
    /// @brief Per-file alias table; see typeName(const SemanticTypeRef&). Mutable because the free
    /// render functions are handed a `const EmitterContext&`.
    mutable std::map<std::string, std::string> importAliases_;

    DefinitionIndex    index_;
    TypeNameVersioning typeNameVersioning_{TypeNameVersioning::Unversioned};
};

std::string tsFieldBaseType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    switch (type.scalarCategory)
    {
    case SemanticScalarCategory::Bool:
        return "boolean";
    case SemanticScalarCategory::Byte:
    case SemanticScalarCategory::Utf8:
        return "number";
    case SemanticScalarCategory::UnsignedInt:
    case SemanticScalarCategory::SignedInt:
        if (type.bitLength > 53U)
        {
            return "bigint";
        }
        return "number";
    case SemanticScalarCategory::Float:
    case SemanticScalarCategory::Void:
        return "number";
    case SemanticScalarCategory::Composite:
        if (type.compositeType)
        {
            return ctx.typeName(*type.compositeType);
        }
        return "unknown";
    }
    return "unknown";
}

std::string tsFieldType(const SemanticFieldType& type, const EmitterContext& ctx)
{
    auto base = tsFieldBaseType(type, ctx);
    if (type.arrayKind == ArrayKind::None)
    {
        return base;
    }
    return "Array<" + base + ">";
}

std::string relativeImportPath(const std::filesystem::path& fromFile, const std::filesystem::path& toFile)
{
    const auto  fromDir    = fromFile.parent_path();
    auto        rel        = toFile.lexically_relative(fromDir);
    std::string importPath = rel.generic_string();
    if (importPath.size() >= 3 && importPath.ends_with(".ts"))
    {
        importPath.resize(importPath.size() - 3);
    }
    if (!importPath.empty() && importPath.front() != '.')
    {
        importPath = "./" + importPath;
    }
    return importPath;
}

std::string moduleAliasFromPath(const std::string& modulePath)
{
    std::string alias;
    alias.reserve(modulePath.size() + 8);
    for (char const c : modulePath)
    {
        if (std::isalnum(static_cast<unsigned char>(c)) || c == '_')
        {
            alias.push_back(static_cast<char>(std::tolower(static_cast<unsigned char>(c))));
        }
        else
        {
            alias.push_back('_');
        }
    }
    // Not a role: the alias comes from --ts-module, so it is a token this generator was handed
    // rather than a DSDL name, and must not pick up a role's case projection.
    return codegenSanitizeIdentifier(CodegenNamingLanguage::TypeScript, alias.empty() ? "module" : alias);
}

void emitSectionConstants(SourceWriter& w, const std::string& prefix, const SemanticSection& section)
{
    std::vector<std::string> constNames;
    constNames.reserve(section.constants.size());
    for (const auto& constant : section.constants)
    {
        constNames.push_back(constant.name);
    }
    NamingScope const constScope = makeSectionConstantScope(CodegenNamingLanguage::TypeScript, section);
    const auto        prefixupper =
        codegenProjectIdentifier(CodegenNamingLanguage::TypeScript, IdentifierRole::ConstantName, prefix);
    for (const auto& constant : section.constants)
    {
        emitAttachedDocTs(w, constant.doc);
        const auto constName = prefixupper + "_" + constScope.get(IdentifierRole::ConstantName, constant.name);
        w.line("export const " + constName + " = " + tsConstValue(constant.type, constant.value) + ";");
    }
}

/// @brief Collision-free property names for one section's fields.
///
/// snake_casing is many-to-one, so `fooBar` and `foo_bar` both fold to `foo_bar`; without this the
/// object type would declare the same property twice and the (de)serialiser would read/write the
/// wrong one. Built from `section.fields` (declaration order) so every emission site agrees.
NamingScope makeTsFieldIdents(const SemanticSection& section)
{
    std::vector<std::string> names;
    for (const auto& field : section.fields)
    {
        if (!field.isPadding)
        {
            names.push_back(field.name);
        }
    }
    return makeSectionFieldScope(CodegenNamingLanguage::TypeScript, section);
}

void emitDeprecationJsDocTs(SourceWriter&       w,
                            const bool          deprecated,
                            const std::string&  fullName,
                            const std::uint32_t majorVersion,
                            const std::uint32_t minorVersion)
{
    if (!deprecated)
    {
        return;
    }
    // The `Deprecated: ` prefix that the shared notice carries for Go's benefit is redundant next to
    // the JSDoc tag, so it is dropped here.
    const std::string notice = deprecationNotice(fullName, majorVersion, minorVersion);
    const std::string prefix = "Deprecated: ";
    const std::string body   = notice.starts_with(prefix) ? notice.substr(prefix.size()) : notice;

    // Wrapped and split across lines for the same reason the notice itself is: a single-line JSDoc
    // block would be twice the width of the code around it. Budget allows for the " * " continuation.
    const auto lines = wrapCommentText(body, 68U);
    w.line("/**");
    w.line(" * @deprecated " + lines.front());
    for (std::size_t i = 1; i < lines.size(); ++i)
    {
        w.line(" *   " + lines[i]);
    }
    w.line(" */");
}

void emitStructSectionType(SourceWriter&          w,
                           const std::string&     typeName,
                           const SemanticSection& section,
                           const AttachedDoc&     typeDoc,
                           const EmitterContext&  ctx,
                           const std::string&     fullName,
                           const std::uint32_t    majorVersion,
                           const std::uint32_t    minorVersion,
                           const bool             deprecated)
{
    emitAttachedDocTs(w, typeDoc);
    emitDeprecationJsDocTs(w, deprecated, fullName, majorVersion, minorVersion);
    w.open("export interface " + typeName + " {");
    const NamingScope fieldIdents = makeTsFieldIdents(section);
    for (const auto& field : section.fields)
    {
        if (field.isPadding)
        {
            continue;
        }
        emitAttachedDocTs(w, field.doc);
        const auto fieldName = fieldIdents.get(IdentifierRole::FieldName, field.name);
        w.line(fieldName + ": " + tsFieldType(field.resolvedType, ctx) + ";");
    }
    w.close("}");
}

void emitUnionSectionType(SourceWriter&          w,
                          const std::string&     typeName,
                          const SemanticSection& section,
                          const AttachedDoc&     typeDoc,
                          const EmitterContext&  ctx,
                          const std::string&     fullName,
                          const std::uint32_t    majorVersion,
                          const std::uint32_t    minorVersion)
{
    std::vector<const SemanticField*> options;
    for (const auto& field : section.fields)
    {
        if (!field.isPadding)
        {
            options.push_back(&field);
        }
    }

    if (options.empty())
    {
        emitAttachedDocTs(w, typeDoc);
        emitDeprecationJsDocTs(w, section.deprecated, fullName, majorVersion, minorVersion);
        w.line("export type " + typeName + " = { _tag: number };");
        return;
    }

    emitAttachedDocTs(w, typeDoc);
    emitDeprecationJsDocTs(w, section.deprecated, fullName, majorVersion, minorVersion);
    w.line("export type " + typeName + " =");
    const NamingScope fieldIdents = makeTsFieldIdents(section);
    for (std::size_t i = 0; i < options.size(); ++i)
    {
        const auto* field = options[i];
        emitAttachedDocTs(w, field->doc);
        const auto         fieldName = fieldIdents.get(IdentifierRole::FieldName, field->name);
        std::ostringstream variant;
        variant << "{ _tag: " << field->unionOptionIndex << "; " << fieldName << ": "
                << tsFieldType(field->resolvedType, ctx) << "; }";
        const auto* const prefix = "  | ";
        w.line(prefix + variant.str() + (i + 1 == options.size() ? ";" : ""));
    }
}

void emitSectionType(SourceWriter&          w,
                     const std::string&     typeName,
                     const SemanticSection& section,
                     const AttachedDoc&     typeDoc,
                     const EmitterContext&  ctx,
                     const std::string&     fullName,
                     const std::uint32_t    majorVersion,
                     const std::uint32_t    minorVersion)
{
    if (section.isUnion)
    {
        emitUnionSectionType(w, typeName, section, typeDoc, ctx, fullName, majorVersion, minorVersion);
    }
    else
    {
        emitStructSectionType(w,
                              typeName,
                              section,
                              typeDoc,
                              ctx,
                              fullName,
                              majorVersion,
                              minorVersion,
                              section.deprecated);
    }
}

std::string tsRuntimeSerializeFn(const std::string& typeName)
{
    return "serialize" + typeName;
}

std::string tsRuntimeDeserializeFn(const std::string& typeName)
{
    return "deserialize" + typeName;
}

/// @brief The TypeScript spelling of the plan-body vocabulary, for one schema.
///
/// The plan's `i64` is `bigint`, its `i8` and an index are `number`, and `i1` is `boolean`. A
/// constant is the value it stands for, and a bigint carries the plan's arithmetic without
/// wrapping. A buffer is a `Uint8Array`, and a pointer into it is a subarray clamped to the
/// buffer's end. A body is an exported function of the object and the buffer that answers the
/// size it used, or the error code, which is negative; the entry points a consumer calls wrap
/// it. A deserialise body is handed an empty object, so the storage a member address names is
/// created where it is first addressed. A union is one of its option objects, so an option is
/// reached through the object cast to the option's shape.
class TsSpelling final : public BodySpelling
{
public:
    /// @brief The name this file gives the type @p fullName names at @p major.@p minor.
    using TypeNameResolver =
        std::function<std::string(llvm::StringRef fullName, std::uint32_t major, std::uint32_t minor)>;

    TsSpelling(mlir::ModuleOp module, mlir::dsdl::SchemaOp schema, TypeNameResolver typeNameOf)
        : symbols_(module)
        , typeNameOf_(std::move(typeNameOf))
    {
        if (schema.getBody().empty())
        {
            return;
        }
        for (mlir::dsdl::SerializationPlanOp plan : schema.getBody().front().getOps<mlir::dsdl::SerializationPlanOp>())
        {
            Plan entry;
            entry.isUnion = plan.getIsUnion();
            NamingScope                   scope(CodegenNamingLanguage::TypeScript);
            std::vector<mlir::dsdl::IOOp> fields;
            if (!plan.getBody().empty())
            {
                for (mlir::dsdl::IOOp io : plan.getBody().front().getOps<mlir::dsdl::IOOp>())
                {
                    if (!io.isPadding())
                    {
                        (void) scope.declare(IdentifierRole::FieldName, io.getName());
                        fields.push_back(io);
                    }
                }
            }
            for (mlir::dsdl::IOOp io : fields)
            {
                entry.members[io.getName()] = Member{scope.get(IdentifierRole::FieldName, io.getName()), io};
            }
            plans_[planIdentity(schema, plan)] = std::move(entry);
        }
    }

    /// @brief Names the TypeScript type each plan's bodies are functions of.
    void setTypeName(const llvm::StringRef identity, const std::string& typeName)
    {
        const auto found = plans_.find(identity);
        if (found != plans_.end())
        {
            found->second.typeName = typeName;
        }
    }

    /// @brief The body function that serialises a value of @p typeName into a buffer.
    static std::string serializeInto(const std::string& typeName)
    {
        return "serialize" + typeName + "Into";
    }

    /// @brief The body function that deserialises a value of @p typeName from a buffer.
    static std::string deserializeFrom(const std::string& typeName)
    {
        return "deserialize" + typeName + "From";
    }

    // Functions.

    std::vector<std::string> openFunction(SourceWriter& w, mlir::func::FuncOp fn) const override
    {
        const auto direction = planBodyDirection(fn);
        inBody_              = direction.has_value();
        deserialize_         = direction.has_value() && *direction == "deserialize";
        if (!direction)
        {
            std::vector<std::string> parameters;
            std::string              list;
            for (const auto [index, argument] : llvm::enumerate(fn.getArguments()))
            {
                parameters.push_back("p" + std::to_string(index));
                list += (list.empty() ? "" : ", ") + parameters.back() + ": " + typeName(argument.getType());
            }
            w.open("function " + functionName(fn.getSymName()) + "(" + list +
                   "): " + typeName(fn.getResultTypes().front()) + " {");
            return parameters;
        }
        const Plan& plan = planOf(fn.getArgument(0));
        w.open("export function " + (deserialize_ ? deserializeFrom(plan.typeName) : serializeInto(plan.typeName)) +
               "(obj: " + plan.typeName + ", buffer: Uint8Array): number {");
        // The size a plan is handed by pointer, read at entry and answered at the end.
        w.line("let inoutBufferSizeBytes = buffer.length;");
        return {"obj", "buffer", "inoutBufferSizeBytes"};
    }

    void closeFunction(SourceWriter& w, mlir::func::FuncOp /*fn*/) const override
    {
        w.close("}");
    }

    [[nodiscard]] std::string functionName(const llvm::StringRef callee) const override
    {
        return renderHelperBindingIdentifier(CodegenNamingLanguage::TypeScript, callee);
    }

    // Statements.

    void declare(SourceWriter& w,
                 const mlir::Type /*type*/,
                 const llvm::StringRef name,
                 const llvm::StringRef expr) const override
    {
        w.line("const " + name.str() + " = " + expr.str() + ";");
    }

    void declareVariable(SourceWriter&         w,
                         const mlir::Type      type,
                         const llvm::StringRef name,
                         const bool /*reassigned*/) const override
    {
        w.line("let " + name.str() + ": " + typeName(type) + ";");
    }

    void assign(SourceWriter& w, const llvm::StringRef name, const llvm::StringRef expr) const override
    {
        w.line(name.str() + " = " + expr.str() + ";");
    }

    void discard(SourceWriter& w, const llvm::StringRef expr) const override
    {
        w.line("void " + expr.str() + ";");
    }

    void returnValue(SourceWriter& w, const llvm::StringRef expr) const override
    {
        // A body answers the runtime's error code; its TypeScript signature answers the size
        // used on success and the code, which is negative, on failure.
        if (inBody_)
        {
            w.open("if (" + expr.str() + " === 0) {");
            w.line("return inoutBufferSizeBytes;");
            w.close("}");
        }
        w.line("return " + expr.str() + ";");
    }

    void openIf(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.open("if (" + condition.str() + ") {");
    }

    void openElse(SourceWriter& w) const override
    {
        w.midway("} else {");
    }

    void openLoop(SourceWriter& w) const override
    {
        w.open("for (;;) {");
    }

    void breakUnless(SourceWriter& w, const llvm::StringRef condition) const override
    {
        w.open("if (!(" + condition.str() + ")) {");
        w.line("break;");
        w.close("}");
    }

    void openFor(SourceWriter&         w,
                 const llvm::StringRef variable,
                 const llvm::StringRef lower,
                 const llvm::StringRef upper,
                 const llvm::StringRef step) const override
    {
        w.open("for (let " + variable.str() + " = " + lower.str() + "; " + variable.str() + " < " + upper.str() + "; " +
               variable.str() + " += " + step.str() + ") {");
    }

    void closeBlock(SourceWriter& w) const override
    {
        w.close("}");
    }

    // Values.

    [[nodiscard]] std::string constant(const mlir::TypedAttr value) const override
    {
        if (const auto integer = mlir::dyn_cast<mlir::IntegerAttr>(value))
        {
            const mlir::Type type = integer.getType();
            if (mlir::isa<mlir::IndexType>(type))
            {
                return std::to_string(integer.getValue().getZExtValue());
            }
            if (isBool(type))
            {
                return integer.getValue().isZero() ? "false" : "true";
            }
            // The value the two's complement stands for: a bigint holds it as such, and the
            // bitwise operators read a negative bigint as its two's complement.
            const std::string digits = std::to_string(integer.getValue().getSExtValue());
            return isBig(type) ? digits + "n" : digits;
        }
        if (const auto real = mlir::dyn_cast<mlir::FloatAttr>(value))
        {
            const double number = real.getValueAsDouble();
            if (std::isnan(number))
            {
                return "Number.NaN";
            }
            if (std::isinf(number))
            {
                return number < 0 ? "-Infinity" : "Infinity";
            }
            std::ostringstream stream;
            stream << std::setprecision(17) << number;
            return stream.str();
        }
        llvm::report_fatal_error("TypeScript spelling: a constant of an unexpected kind");
    }

    [[nodiscard]] std::string binary(const BinaryOperator  op,
                                     const llvm::StringRef lhs,
                                     const llvm::StringRef rhs,
                                     const mlir::Type      type) const override
    {
        if (isBool(type))
        {
            switch (op)
            {
            case BinaryOperator::And:
                return lhs.str() + " && " + rhs.str();
            case BinaryOperator::Or:
                return lhs.str() + " || " + rhs.str();
            case BinaryOperator::Xor:
                return lhs.str() + " !== " + rhs.str();
            default:
                llvm::report_fatal_error("TypeScript spelling: an arithmetic operator on a bool");
            }
        }
        // A bigint's arithmetic is the plan's; a number's division is rounded to the integer.
        if (!isBig(type) && (op == BinaryOperator::DivU || op == BinaryOperator::DivS))
        {
            return "Math.trunc(" + lhs.str() + " / " + rhs.str() + ")";
        }
        return lhs.str() + " " + operatorToken(op) + " " + rhs.str();
    }

    [[nodiscard]] std::string compare(const Comparison      comparison,
                                      const llvm::StringRef lhs,
                                      const llvm::StringRef rhs,
                                      const mlir::Type      type) const override
    {
        std::string a = lhs.str();
        std::string b = rhs.str();
        switch (comparison)
        {
        case Comparison::Eq:
            return a + " === " + b;
        case Comparison::Ne:
            return a + " !== " + b;
        case Comparison::LtU:
        case Comparison::LeU:
        case Comparison::GtU:
        case Comparison::GeU:
            // A bigint is the value its bits stand for; an unsigned comparison against a
            // negative literal reads both as the unsigned 64-bit values the plan compares.
            if (isBig(type) && (lhs.starts_with("-") || rhs.starts_with("-")))
            {
                a = "BigInt.asUintN(64, " + a + ")";
                b = "BigInt.asUintN(64, " + b + ")";
            }
            break;
        default:
            break;
        }
        return a + " " + comparisonToken(comparison) + " " + b;
    }

    [[nodiscard]] std::string select(const llvm::StringRef condition,
                                     const llvm::StringRef ifTrue,
                                     const llvm::StringRef ifFalse,
                                     const mlir::Type /*type*/) const override
    {
        return condition.str() + " ? " + ifTrue.str() + " : " + ifFalse.str();
    }

    [[nodiscard]] std::string convert(const Conversion /*conversion*/,
                                      const llvm::StringRef value,
                                      const mlir::Type      from,
                                      const mlir::Type      to) const override
    {
        return cast(value.str(), from, to);
    }

    [[nodiscard]] std::string call(const llvm::StringRef callee, const llvm::ArrayRef<std::string> args) const override
    {
        return callee.str() + "(" + llvm::join(args, ", ") + ")";
    }

    // The dialect.

    [[nodiscard]] bool spellsInline(mlir::Operation* op) const override
    {
        if (mlir::isa<mlir::dsdl::IsNullOp, mlir::dsdl::BufferOrEmptyOp>(op))
        {
            return true;
        }
        // An address that creates its storage is evaluated once.
        return !deserialize_ && mlir::isa<mlir::dsdl::MemberAddrOp, mlir::dsdl::ElementAddrOp>(op);
    }

    [[nodiscard]] std::string isNull(mlir::dsdl::IsNullOp op, const ValueNames& names) const override
    {
        // The object arrives by reference and may be missing; a buffer and a local are never null.
        const auto pointer = mlir::cast<mlir::dsdl::PtrType>(op.getPointer().getType());
        if (mlir::isa<mlir::dsdl::ObjectType>(pointer.getPointee()))
        {
            return names(op.getPointer()) + " == null";
        }
        return "false";
    }

    [[nodiscard]] std::string bufferOrEmpty(mlir::dsdl::BufferOrEmptyOp op, const ValueNames& names) const override
    {
        return names(op.getBuffer());
    }

    [[nodiscard]] std::string bufferAt(mlir::dsdl::BufferAtOp op, const ValueNames& names) const override
    {
        // The plan bounds its reads and writes itself; the subarray is clamped to the buffer.
        const std::string buffer = names(op.getBuffer());
        return buffer + ".subarray(Math.min(" + asNumber(op.getByteOffset(), names) + ", " + buffer + ".length))";
    }

    [[nodiscard]] std::string loadScalar(mlir::dsdl::LoadScalarOp op, const ValueNames& names) const override
    {
        return cast(names(op.getPointer()), mlir::IndexType::get(op.getContext()), op.getValue().getType());
    }

    void storeScalar(SourceWriter& w, mlir::dsdl::StoreScalarOp op, const ValueNames& names) const override
    {
        w.line(names(op.getPointer()) + " = " + asNumber(op.getValue(), names) + ";");
    }

    [[nodiscard]] std::string local(SourceWriter&         w,
                                    mlir::dsdl::LocalOp   op,
                                    const llvm::StringRef name,
                                    const ValueNames&     names) const override
    {
        w.line("let " + name.str() + " = " + asNumber(op.getInit(), names) + ";");
        return name.str();
    }

    [[nodiscard]] std::string loadMember(mlir::dsdl::LoadMemberOp op, const ValueNames& names) const override
    {
        return loadedValue(memberAccess(op.getObject(), op.getMember(), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeMember(SourceWriter& w, mlir::dsdl::StoreMemberOp op, const ValueNames& names) const override
    {
        w.line(memberAccess(op.getObject(), op.getMember(), names) + " = " +
               storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())) +
               ";");
    }

    [[nodiscard]] std::string loadElement(mlir::dsdl::LoadElementOp op, const ValueNames& names) const override
    {
        return loadedValue(elementAccess(op.getObject(), op.getMember(), asNumber(op.getIndex(), names), names),
                           memberOf(op.getObject(), op.getMember()),
                           op.getValue().getType());
    }

    void storeElement(SourceWriter& w, mlir::dsdl::StoreElementOp op, const ValueNames& names) const override
    {
        w.line(elementAccess(op.getObject(), op.getMember(), asNumber(op.getIndex(), names), names) + " = " +
               storedValue(names(op.getValue()), op.getValue().getType(), memberOf(op.getObject(), op.getMember())) +
               ";");
    }

    [[nodiscard]] std::string memberAddr(mlir::dsdl::MemberAddrOp op, const ValueNames& names) const override
    {
        const Member member = memberOf(op.getObject(), op.getMember());
        std::string  access = memberAccess(op.getObject(), op.getMember(), names);
        if (!deserialize_)
        {
            return access;
        }
        // The storage the address names, created where the plan first addresses it.
        if (isArray(member))
        {
            return "(" + access + " \?\?= [])";
        }
        if (isComposite(member))
        {
            return "(" + access + " \?\?= {} as " + memberTsType(member) + ")";
        }
        return access;
    }

    [[nodiscard]] std::string elementAddr(mlir::dsdl::ElementAddrOp op, const ValueNames& names) const override
    {
        const Member member  = memberOf(op.getObject(), op.getMember());
        std::string  element = elementAccess(op.getObject(), op.getMember(), asNumber(op.getIndex(), names), names);
        if (deserialize_ && isComposite(member))
        {
            return "(" + element + " \?\?= {} as " + elementTsType(member) + ")";
        }
        return element;
    }

    [[nodiscard]] std::string arrayLength(mlir::dsdl::ArrayLengthOp op, const ValueNames& names) const override
    {
        return "BigInt(" + containerAccess(op.getObject(), op.getMember(), names) + ".length)";
    }

    void setArrayLength(SourceWriter& w, mlir::dsdl::SetArrayLengthOp op, const ValueNames& names) const override
    {
        // Sized within its capacity -- a count past it is what the plan's validation rejects
        // next -- for the plan to store into.
        const Member      member = memberOf(op.getObject(), op.getMember());
        mlir::dsdl::IOOp  io     = member.io;
        const std::string count  = fresh("count");
        w.line("const " + count + " = Math.min(" + asNumber(op.getValue(), names) + ", " +
               std::to_string(io.getArrayCapacity()) + ");");
        w.line(memberAccess(op.getObject(), op.getMember(), names) + " = new Array<" + elementTsType(member) + ">(" +
               count + ");");
    }

    [[nodiscard]] std::string unionTag(mlir::dsdl::UnionTagOp op, const ValueNames& names) const override
    {
        return "dsdlRuntime.toBigIntValue(" + names(op.getObject()) + "._tag)";
    }

    void setUnionTag(SourceWriter& w, mlir::dsdl::SetUnionTagOp op, const ValueNames& names) const override
    {
        w.line("(" + names(op.getObject()) + " as { _tag: number })._tag = " + asNumber(op.getValue(), names) + ";");
    }

    [[nodiscard]] std::string writeBits(mlir::dsdl::WriteBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string width     = std::to_string(op.getWidth());
        const std::string value     = names(op.getValue());
        const std::string prefix    = names(op.getBuffer()) + ", " + asNumber(op.getBitOffset(), names) + ", ";
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "dsdlRuntime.writeFloat(" + prefix + width + ", " + value + ")";
        }
        if (isBool(valueType))
        {
            return "dsdlRuntime.setBit(" + prefix + value + ")";
        }
        return "dsdlRuntime." + std::string(op.getIsSigned() ? "writeSigned(" : "writeUnsigned(") + prefix + width +
               ", " + value + ", false)";
    }

    [[nodiscard]] std::string readBits(mlir::dsdl::ReadBitsOp op, const ValueNames& names) const override
    {
        const mlir::Type  valueType = op.getValue().getType();
        const std::string arguments =
            names(op.getBuffer()) + ", " + asNumber(op.getBitOffset(), names) + ", " + std::to_string(op.getWidth());
        if (mlir::isa<mlir::FloatType>(valueType))
        {
            return "dsdlRuntime.readFloat(" + arguments + ")";
        }
        const std::string read = "dsdlRuntime." +
                                 std::string(op.getIsSigned() ? "readSignedBigInt(" : "readUnsignedBigInt(") +
                                 arguments + ")";
        return cast(read, mlir::IntegerType::get(op.getContext(), 64), valueType);
    }

    void bitWrite(SourceWriter& w, mlir::dsdl::BitWriteOp op, const ValueNames& names) const override
    {
        // A bool array is an array of booleans, so a run of its bits goes one element at a time.
        const auto        container = boolContainerOf(op.getSource(), names);
        const std::string index     = fresh("bit");
        w.open("for (let " + index + " = 0; " + index + " < " + asNumber(op.getWidth(), names) + "; ++" + index +
               ") {");
        w.line("dsdlRuntime.setBit(" + names(op.getDestination()) + ", " +
               asNumber(op.getDestinationBitOffset(), names) + " + " + index + ", " + container.first + "[" +
               container.second + " + " + asNumber(op.getSourceBitOffset(), names) + " + " + index + "]);");
        w.close("}");
    }

    void bitRead(SourceWriter& w, mlir::dsdl::BitReadOp op, const ValueNames& names) const override
    {
        const auto        container = boolContainerOf(op.getDestination(), names);
        const std::string index     = fresh("bit");
        w.open("for (let " + index + " = 0; " + index + " < " + asNumber(op.getWidth(), names) + "; ++" + index +
               ") {");
        w.line(container.first + "[" + container.second + " + " + index + "] = dsdlRuntime.getBit(" +
               names(op.getBuffer()) + ", " + asNumber(op.getBitOffset(), names) + " + " + index + ");");
        w.close("}");
    }

    [[nodiscard]] std::string callSerdes(mlir::dsdl::CallSerdesOp /*op*/, const ValueNames& /*names*/) const override
    {
        llvm::report_fatal_error("TypeScript spelling: a nested call is a statement");
    }

    void declareCallSerdes(SourceWriter&            w,
                           const llvm::StringRef    name,
                           mlir::dsdl::CallSerdesOp op,
                           const ValueNames&        names) const override
    {
        // The nested value serialises itself into the subarray from the buffer's offset, bounded
        // by the size the plan handed in; it answers the size it used or the code, and the size
        // is written back through the local where the plan reads it.
        const std::string buffer = names(op.getBuffer());
        const std::string size   = names(op.getSize());
        const std::string bound  = fresh("bound");
        const std::string result = fresh("result");
        const bool        read   = isRead(op.getSize());
        w.line("const " + bound + " = Math.min(" + size + ", " + buffer + ".length);");
        w.line("const " + result + " = " + nestedFunction(op) + "(" + names(op.getObject()) + ", " + buffer +
               ".subarray(0, " + bound + "));");
        if (!name.empty())
        {
            w.line("let " + name.str() + ": number;");
            w.open("if (" + result + " < 0) {");
            w.line(name.str() + " = " + result + ";");
            w.midway("} else {");
            if (read)
            {
                w.line(size + " = " + result + ";");
            }
            w.line(name.str() + " = 0;");
            w.close("}");
            return;
        }
        if (read)
        {
            w.open("if (" + result + " >= 0) {");
            w.line(size + " = " + result + ";");
            w.close("}");
        }
    }

private:
    struct Member final
    {
        std::string      tsName;
        mlir::dsdl::IOOp io;
    };

    struct Plan final
    {
        std::string             typeName;
        bool                    isUnion{false};
        llvm::StringMap<Member> members;
    };

    /// @brief The plan the object a pointer names belongs to.
    const Plan& planOf(const mlir::Value object) const
    {
        const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(object.getType());
        const auto identity =
            pointer ? mlir::dyn_cast<mlir::dsdl::ObjectType>(pointer.getPointee()) : mlir::dsdl::ObjectType{};
        const auto found = identity ? plans_.find(identity.getIdentity()) : plans_.end();
        if (found == plans_.end())
        {
            llvm::report_fatal_error("TypeScript spelling: an object that no plan of this schema describes");
        }
        return found->second;
    }

    Member memberOf(const mlir::Value object, const llvm::StringRef member) const
    {
        const Plan& plan  = planOf(object);
        const auto  found = plan.members.find(member);
        if (found == plan.members.end())
        {
            llvm::report_fatal_error("TypeScript spelling: a member the schema does not declare: " + member);
        }
        return found->second;
    }

    /// @brief The body function of the nested type a call names.
    std::string nestedFunction(mlir::dsdl::CallSerdesOp op) const
    {
        auto       body   = symbols_.lookup<mlir::func::FuncOp>(op.getCallee());
        const auto owner  = body ? body->getAttrOfType<mlir::StringAttr>("llvmdsdl.schema_sym") : mlir::StringAttr{};
        auto       schema = owner ? symbols_.lookup<mlir::dsdl::SchemaOp>(owner.getValue()) : mlir::dsdl::SchemaOp{};
        if (!schema)
        {
            llvm::report_fatal_error("TypeScript spelling: a nested call to a body of no schema in the module");
        }
        const std::string nested = typeNameOf_(schema.getFullName(),
                                               static_cast<std::uint32_t>(schema.getMajor()),
                                               static_cast<std::uint32_t>(schema.getMinor()));
        return op.getDirection() == "serialize" ? serializeInto(nested) : deserializeFrom(nested);
    }

    /// @brief The member as the object declares it; an option through the object cast to its shape.
    std::string memberAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        const Plan&  plan  = planOf(object);
        const Member found = memberOf(object, member);
        if (plan.isUnion)
        {
            return "(" + names(object) + " as { " + found.tsName + ": " + memberTsType(found) + " })." + found.tsName;
        }
        return names(object) + "." + found.tsName;
    }

    /// @brief An array member, which a deserialise body creates where it first addresses it.
    std::string containerAccess(const mlir::Value object, const llvm::StringRef member, const ValueNames& names) const
    {
        const std::string access = memberAccess(object, member, names);
        return deserialize_ ? "(" + access + " \?\?= [])" : access;
    }

    std::string elementAccess(const mlir::Value     object,
                              const llvm::StringRef member,
                              const std::string&    index,
                              const ValueNames&     names) const
    {
        return containerAccess(object, member, names) + "[" + index + "]";
    }

    /// @brief Whether the plan reads the size @p pointer addresses back after handing it out.
    static bool isRead(const mlir::Value pointer)
    {
        return llvm::any_of(pointer.getUsers(),
                            [](mlir::Operation* user) { return mlir::isa<mlir::dsdl::LoadScalarOp>(user); });
    }

    /// @brief The container expression and element base of the bool array @p address names.
    std::pair<std::string, std::string> boolContainerOf(const mlir::Value address, const ValueNames& names) const
    {
        auto element = address.getDefiningOp<mlir::dsdl::ElementAddrOp>();
        if (!element)
        {
            llvm::report_fatal_error("TypeScript spelling: a bit copy whose storage is not an array element");
        }
        return std::make_pair(containerAccess(element.getObject(), element.getMember(), names),
                              asNumber(element.getIndex(), names));
    }

    // Members.

    static bool isArray(const Member& member)
    {
        mlir::dsdl::IOOp io = member.io;
        return io.isArray();
    }

    static bool isComposite(const Member& member)
    {
        mlir::dsdl::IOOp io = member.io;
        return io.isComposite();
    }

    /// @brief The kind of value a member or element holds.
    enum class Storage : std::uint8_t
    {
        Boolean,
        Number,
        BigInt,
        Float,
        Object,
    };

    static Storage storageOf(const Member& member)
    {
        mlir::dsdl::IOOp      io       = member.io;
        const llvm::StringRef category = io.getScalarCategory();
        if (io.isComposite())
        {
            return Storage::Object;
        }
        if (category == "bool")
        {
            return Storage::Boolean;
        }
        if (category == "float")
        {
            return Storage::Float;
        }
        // A number holds an integer exactly to 53 bits; a wider field is a bigint.
        return io.getBitLength() > 53 ? Storage::BigInt : Storage::Number;
    }

    /// @brief The TypeScript type of one element of @p member, or of the member when it is no array.
    std::string elementTsType(const Member& member) const
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            return "boolean";
        case Storage::Number:
        case Storage::Float:
            return "number";
        case Storage::BigInt:
            return "bigint";
        case Storage::Object:
            break;
        }
        mlir::dsdl::IOOp io = member.io;
        return typeNameOf_(io.getCompositeFullName().value_or(llvm::StringRef{}),
                           static_cast<std::uint32_t>(io.getCompositeMajor().value_or(0)),
                           static_cast<std::uint32_t>(io.getCompositeMinor().value_or(0)));
    }

    std::string memberTsType(const Member& member) const
    {
        return isArray(member) ? "Array<" + elementTsType(member) + ">" : elementTsType(member);
    }

    /// @brief @p access read as a value of @p type.
    static std::string loadedValue(const std::string& access, const Member& member, const mlir::Type type)
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            if (isBool(type))
            {
                return access;
            }
            return isBig(type) ? "(" + access + " ? 1n : 0n)" : "(" + access + " ? 1 : 0)";
        case Storage::BigInt:
            return isBig(type) ? access : "Number(" + access + ")";
        case Storage::Number:
            // A number a caller stored may be no integer; the runtime rounds it to one.
            return isBig(type) ? "dsdlRuntime.toBigIntValue(" + access + ")" : "Math.trunc(" + access + ")";
        case Storage::Float:
        case Storage::Object:
            break;
        }
        return access;
    }

    /// @brief @p value, of @p type, converted for storage in @p member.
    static std::string storedValue(const std::string& value, const mlir::Type type, const Member& member)
    {
        switch (storageOf(member))
        {
        case Storage::Boolean:
            if (isBool(type))
            {
                return value;
            }
            return isBig(type) ? value + " !== 0n" : value + " !== 0";
        case Storage::BigInt:
            return isBig(type) ? value : "BigInt(" + value + ")";
        case Storage::Number:
            if (isBig(type))
            {
                return "Number(" + value + ")";
            }
            return isBool(type) ? "(" + value + " ? 1 : 0)" : value;
        case Storage::Float:
        case Storage::Object:
            break;
        }
        return value;
    }

    // Types.

    static bool isBool(const mlir::Type type)
    {
        return type.isInteger(1);
    }

    /// @brief Whether @p type is the plan's `i64`, a bigint.
    static bool isBig(const mlir::Type type)
    {
        return type.isInteger(64);
    }

    /// @brief @p value, of @p from, as a value of @p to.
    static std::string cast(const std::string& value, const mlir::Type from, const mlir::Type to)
    {
        if (from == to)
        {
            return value;
        }
        if (isBool(to))
        {
            return "(" + value + (isBig(from) ? " !== 0n)" : " !== 0)");
        }
        if (isBig(to))
        {
            return isBool(from) ? "(" + value + " ? 1n : 0n)" : "BigInt(" + value + ")";
        }
        if (isBool(from))
        {
            return "(" + value + " ? 1 : 0)";
        }
        if (isBig(from))
        {
            return to.isInteger(8) ? "Number(BigInt.asIntN(8, " + value + "))" : "Number(" + value + ")";
        }
        return value;
    }

    /// @brief @p value as a number, which an offset, a size and an index are.
    static std::string asNumber(const mlir::Value value, const ValueNames& names)
    {
        return cast(names(value), value.getType(), mlir::IndexType::get(value.getContext()));
    }

    static std::string typeName(const mlir::Type type)
    {
        if (mlir::isa<mlir::IndexType>(type) || mlir::isa<mlir::FloatType>(type))
        {
            return "number";
        }
        if (const auto integer = mlir::dyn_cast<mlir::IntegerType>(type))
        {
            if (integer.getWidth() == 1)
            {
                return "boolean";
            }
            return integer.getWidth() == 64 ? "bigint" : "number";
        }
        if (const auto pointer = mlir::dyn_cast<mlir::dsdl::PtrType>(type))
        {
            if (mlir::isa<mlir::dsdl::ByteType>(pointer.getPointee()))
            {
                return "Uint8Array";
            }
            if (mlir::isa<mlir::dsdl::SizeType>(pointer.getPointee()))
            {
                return "number";
            }
        }
        llvm::report_fatal_error("TypeScript spelling: a value of a type no plan body carries");
    }

    static std::string operatorToken(const BinaryOperator op)
    {
        switch (op)
        {
        case BinaryOperator::Add:
            return "+";
        case BinaryOperator::Sub:
            return "-";
        case BinaryOperator::Mul:
            return "*";
        case BinaryOperator::DivU:
        case BinaryOperator::DivS:
            return "/";
        case BinaryOperator::RemU:
        case BinaryOperator::RemS:
            return "%";
        case BinaryOperator::And:
            return "&";
        case BinaryOperator::Or:
            return "|";
        case BinaryOperator::Xor:
            return "^";
        case BinaryOperator::ShiftLeft:
            return "<<";
        case BinaryOperator::ShiftRightU:
        case BinaryOperator::ShiftRightS:
            return ">>";
        }
        llvm::report_fatal_error("TypeScript spelling: an operator of an unexpected kind");
    }

    static std::string comparisonToken(const Comparison comparison)
    {
        switch (comparison)
        {
        case Comparison::Eq:
            return "===";
        case Comparison::Ne:
            return "!==";
        case Comparison::LtS:
        case Comparison::LtU:
            return "<";
        case Comparison::LeS:
        case Comparison::LeU:
            return "<=";
        case Comparison::GtS:
        case Comparison::GtU:
            return ">";
        case Comparison::GeS:
        case Comparison::GeU:
            return ">=";
        }
        llvm::report_fatal_error("TypeScript spelling: a comparison of an unexpected kind");
    }

    /// @brief A name for a value of this spelling's own, distinct from the translator's.
    std::string fresh(const char* const stem) const
    {
        return "_" + std::string(stem) + std::to_string(fresh_++) + "_";
    }

    mlir::SymbolTable     symbols_;
    TypeNameResolver      typeNameOf_;
    llvm::StringMap<Plan> plans_;
    mutable bool          inBody_{false};
    mutable bool          deserialize_{false};
    mutable unsigned      fresh_{0};
};

/// @brief The two bodies `lower-dsdl-bodies` built for one section.
struct SectionBodies final
{
    mlir::func::FuncOp serialize;
    mlir::func::FuncOp deserialize;
};

/// @brief The entry points a consumer calls, which wrap the translated bodies: a value serialises
/// into a buffer of the type's largest size, and a deserialisation fills an empty object.
void emitEntryPoints(SourceWriter& w, const std::string& typeName, const SemanticSection& section)
{
    const auto bufferBytes = (section.serializationBufferSizeBits + 7) / 8;
    w.open("export function " + tsRuntimeSerializeFn(typeName) + "(value: " + typeName + "): Uint8Array {");
    w.line("const buffer = new Uint8Array(" + std::to_string(bufferBytes) + ");");
    w.line("const result = " + TsSpelling::serializeInto(typeName) + "(value, buffer);");
    w.open("if (result < 0) {");
    w.line("throw new Error(dsdlRuntime.errorMessage(result));");
    w.close("}");
    w.line("return buffer.subarray(0, result);");
    w.close("}");
    w.blank();
    w.open("export function " + tsRuntimeDeserializeFn(typeName) + "(bytes: Uint8Array): { value: " + typeName +
           "; consumed: number } {");
    w.line("const value = {} as " + typeName + ";");
    w.line("const result = " + TsSpelling::deserializeFrom(typeName) + "(value, bytes);");
    w.open("if (result < 0) {");
    w.line("throw new Error(dsdlRuntime.errorMessage(result));");
    w.close("}");
    w.line("return { value, consumed: result };");
    w.close("}");
}

/// @brief One section: its type, its constants, its two bodies and the entry points that wrap them.
llvm::Error emitSection(SourceWriter&             w,
                        const std::string&        typeName,
                        const SemanticSection&    section,
                        const AttachedDoc&        typeDoc,
                        const EmitterContext&     ctx,
                        const SemanticDefinition& def,
                        const TsSpelling&         spelling,
                        const SectionBodies&      bodies)
{
    emitSectionType(w,
                    typeName,
                    section,
                    typeDoc,
                    ctx,
                    def.info.fullName,
                    def.info.majorVersion,
                    def.info.minorVersion);
    w.blank();
    emitSectionConstants(w, typeName, section);
    w.blank();
    if (!bodies.serialize || !bodies.deserialize)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no plan bodies for %s in the lowered module",
                                       def.info.fullName.c_str());
    }
    if (auto err = translateFunction(bodies.serialize, spelling, w))
    {
        return err;
    }
    w.blank();
    if (auto err = translateFunction(bodies.deserialize, spelling, w))
    {
        return err;
    }
    w.blank();
    emitEntryPoints(w, typeName, section);
    return llvm::Error::success();
}

llvm::Expected<std::string> renderDefinitionFile(const SemanticDefinition& def,
                                                 const EmitterContext&     ctx,
                                                 mlir::ModuleOp            module)
{
    mlir::dsdl::SchemaOp schema = schemaOf(module, def);
    if (!schema)
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                       "no schema for %s in the lowered module",
                                       def.info.fullName.c_str());
    }

    const auto ownerPath = EmitterContext::relativeFilePath(def.info);

    // Disambiguate before anything is rendered.
    //
    // Two types from different namespaces can share a short name -- `uavcan.si.unit.velocity.Vector3`
    // and `uavcan.si.unit.angular_velocity.Vector3` are both `Vector3_1_0` -- and a file that
    // references both would import the same identifier twice, which `tsc` rejects outright as a
    // duplicate identifier. So the referenced set is collected first, short-name clashes are found,
    // and the clashing types are given namespace-qualified local names. Installing the table on the
    // context before any rendering is what keeps the import list, the type annotations, and the
    // serialise/deserialize call names in agreement: they all resolve through ctx.typeName().
    {
        std::map<std::string, std::vector<const DiscoveredDefinition*>> byShortName;
        const auto collectReferenced = [&](const SemanticSection& section) {
            for (const auto& ref : collectCompositeDependencies(section, def.info))
            {
                if (const auto* referenced = ctx.find(ref))
                {
                    auto&      bucket = byShortName[ctx.typeName(referenced->info)];
                    const auto key    = EmitterContext::importAliasKey(referenced->info);
                    const bool seen   = std::ranges::any_of(bucket, [&](const auto* other) {
                        return EmitterContext::importAliasKey(*other) == key;
                    });
                    if (!seen)
                    {
                        bucket.push_back(&referenced->info);
                    }
                }
            }
        };
        collectReferenced(def.request);
        if (def.response)
        {
            collectReferenced(*def.response);
        }

        std::map<std::string, std::string> aliases;
        for (const auto& [shortName, definitions] : byShortName)
        {
            if (definitions.size() < 2U)
            {
                continue;
            }
            for (const auto* info : definitions)
            {
                // Namespace as a suffix rather than a prefix. The serialise and deserialise call
                // names are built by sticking a verb on the front of this, and a leading lowercase
                // namespace would run the two together -- `deserializeuavcan_si_unit_...`. Keeping
                // the type name where it has always been leaves those readable and leaves the
                // recognisable part of the identifier first.
                std::string qualified = shortName + "__";
                for (const auto& component : info->namespaceComponents)
                {
                    qualified += component + "_";
                }
                qualified.pop_back();
                aliases.emplace(EmitterContext::importAliasKey(*info), qualified);
            }
        }
        ctx.setImportAliases(std::move(aliases));
    }

    std::map<std::string, std::set<std::pair<std::string, std::string>>> importsByModule;
    std::map<std::string, std::set<std::pair<std::string, std::string>>> bodyImportsByModule;
    const auto addSectionImports = [&](const SemanticSection& section) {
        const auto dependencies = collectCompositeDependencies(section, def.info);
        const auto imports      = projectCompositeImports(
            dependencies,
            [&](const SemanticTypeRef& ref) { return relativeImportPath(ownerPath, ctx.relativeFilePath(ref)); },
            [&](const SemanticTypeRef& ref) { return ctx.typeName(ref); });
        for (const auto& importSpec : imports)
        {
            std::string original = importSpec.typeName;
            for (const auto& ref : dependencies)
            {
                if (const auto* referenced = ctx.find(ref);
                    referenced != nullptr && ctx.typeName(ref) == importSpec.typeName)
                {
                    original = ctx.typeName(referenced->info);
                    break;
                }
            }
            importsByModule[importSpec.modulePath].emplace(original, importSpec.typeName);
            // The nested type's bodies, which this file's bodies call.
            bodyImportsByModule[importSpec.modulePath].emplace(TsSpelling::serializeInto(original),
                                                               TsSpelling::serializeInto(importSpec.typeName));
            bodyImportsByModule[importSpec.modulePath].emplace(TsSpelling::deserializeFrom(original),
                                                               TsSpelling::deserializeFrom(importSpec.typeName));
        }
    };
    addSectionImports(def.request);
    if (def.response)
    {
        addSectionImports(*def.response);
    }

    // The spelling names a nested type as this file does: through the alias table just installed.
    TsSpelling spelling(module,
                        schema,
                        [&ctx](const llvm::StringRef fullName, const std::uint32_t major, const std::uint32_t minor) {
                            SemanticTypeRef ref;
                            ref.fullName = fullName.str();
                            llvm::SmallVector<llvm::StringRef> components;
                            fullName.split(components, '.');
                            for (const llvm::StringRef component : components)
                            {
                                ref.namespaceComponents.push_back(component.str());
                            }
                            if (!ref.namespaceComponents.empty())
                            {
                                ref.shortName = ref.namespaceComponents.back();
                                ref.namespaceComponents.pop_back();
                            }
                            ref.majorVersion = major;
                            ref.minorVersion = minor;
                            return ctx.typeName(ref);
                        });
    std::vector<mlir::func::FuncOp>      helpers;
    std::map<std::string, SectionBodies> bodies;
    for (const mlir::func::FuncOp fn : schemaFunctions(module, schema.getSymName()))
    {
        const auto direction = planBodyDirection(fn);
        if (!direction)
        {
            helpers.push_back(fn);
            continue;
        }
        const auto     sectionAttr = fn->getAttrOfType<mlir::StringAttr>("llvmdsdl.section");
        SectionBodies& entry       = bodies[sectionAttr ? sectionAttr.getValue().str() : std::string{}];
        (*direction == "serialize" ? entry.serialize : entry.deserialize) = fn;
    }

    const auto baseType = ctx.typeName(def.info);
    const auto reqType  = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::TypeScript, "request");
    const auto respType = baseType + renderSectionTypeSuffix(CodegenNamingLanguage::TypeScript, "response");
    spelling.setTypeName(planIdentity(def.info.fullName, def.info.majorVersion, def.info.minorVersion, {}), baseType);
    spelling.setTypeName(planIdentity(def.info.fullName, def.info.majorVersion, def.info.minorVersion, "request"),
                         reqType);
    spelling.setTypeName(planIdentity(def.info.fullName, def.info.majorVersion, def.info.minorVersion, "response"),
                         respType);

    std::ostringstream out;
    SourceWriter       w = makeTsWriter(out);
    w.line(generatedCommentLine("TypeScript backend"));
    w.line("// Source: " + def.info.fullName + "." + std::to_string(def.info.majorVersion) + "." +
           std::to_string(def.info.minorVersion));
    const auto runtimePath = relativeImportPath(ownerPath, std::filesystem::path("dsdl_runtime.ts"));
    w.line("import * as dsdlRuntime from \"" + runtimePath + "\";");
    w.blank();

    // `Original as Local`, collapsing to plain `Original` when nothing had to be renamed -- so a
    // file that references no clashing names looks exactly as it did before aliasing existed.
    const auto renderImportList = [](const std::set<std::pair<std::string, std::string>>& names) {
        std::string rendered;
        for (const auto& [original, local] : names)
        {
            if (!rendered.empty())
            {
                rendered += ", ";
            }
            // NOLINTNEXTLINE(performance-inefficient-string-concatenation)
            rendered += (original == local) ? original : (original + " as " + local);
        }
        return rendered;
    };

    for (const auto& [modulePath, names] : bodyImportsByModule)
    {
        w.line("import { " + renderImportList(names) + " } from \"" + modulePath + "\";");
    }

    for (const auto& [modulePath, names] : importsByModule)
    {
        w.line("import type { " + renderImportList(names) + " } from \"" + modulePath + "\";");
    }
    w.line("export const LLVMDSDL_GENERATOR_VERSION = \"" + std::string(llvmdsdl::kVersionString) + "\";");
    w.line("export const DSDL_FULL_NAME = \"" + def.info.fullName + "\";");
    w.line("export const DSDL_IS_DEPRECATED = " + std::string(def.request.deprecated ? "true" : "false") + ";");
    w.line("export const DSDL_VERSION_MAJOR = " + std::to_string(def.info.majorVersion) + ";");
    w.line("export const DSDL_VERSION_MINOR = " + std::to_string(def.info.minorVersion) + ";");
    const auto [requestZohEligible, requestZohReason] =
        aliasVerdict(sectionPlan(schema, def.isService ? "request" : ""));
    w.line("export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = " + std::string(requestZohEligible ? "true" : "false") +
           ";");
    w.line("export const DSDL_REQUEST_ZOH_ALIAS_REASON = \"" + requestZohReason + "\";");
    if (def.response)
    {
        const auto [responseZohEligible, responseZohReason] = aliasVerdict(sectionPlan(schema, "response"));
        w.line("export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = " +
               std::string(responseZohEligible ? "true" : "false") + ";");
        w.line("export const DSDL_RESPONSE_ZOH_ALIAS_REASON = \"" + responseZohReason + "\";");
    }
    else
    {
        w.line("export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;");
        w.line("export const DSDL_RESPONSE_ZOH_ALIAS_REASON = \"not-applicable\";");
    }
    w.blank();

    for (const mlir::func::FuncOp helper : helpers)
    {
        if (auto err = translateFunction(helper, spelling, w))
        {
            return std::move(err);
        }
        w.blank();
    }

    if (!def.isService)
    {
        if (auto err = emitSection(w, baseType, def.request, def.doc, ctx, def, spelling, bodies[""]))
        {
            return std::move(err);
        }
        return out.str();
    }

    if (auto err = emitSection(w, reqType, def.request, def.doc, ctx, def, spelling, bodies["request"]))
    {
        return std::move(err);
    }
    w.blank();

    if (def.response)
    {
        if (auto err = emitSection(w, respType, *def.response, def.doc, ctx, def, spelling, bodies["response"]))
        {
            return std::move(err);
        }
        w.blank();
    }

    w.line("export type " + baseType + " = " + reqType + ";");
    return out.str();
}

std::string renderPackageJson(const Options& options)
{
    const auto* const runtimeSpecialization =
        options.runtimeSpecialization == RuntimeSpecialization::Fast ? "fast" : "portable";
    std::ostringstream out;
    out << "{\n";
    out << R"(  "name": ")" << options.moduleName << "\",\n";
    out << R"(  "version": ")" << llvmdsdl::kVersionString << "\",\n";
    out << "  \"type\": \"module\",\n";
    out << "  \"llvmdsdl\": {\n";
    out << R"(    "generatorVersion": ")" << llvmdsdl::kVersionString << "\",\n";
    out << R"(    "tsRuntimeSpecialization": ")" << runtimeSpecialization << "\"\n";
    out << "  }\n";
    out << "}\n";
    return out.str();
}

std::string renderTsRuntimeModule(const RuntimeSpecialization runtimeSpecialization)
{
    std::ostringstream out;
    SourceWriter       w = makeTsWriter(out);
    w.line(generatedCommentLine("TypeScript runtime scaffold"));
    w.blank();
    w.open("export function toBigIntValue(value: number | bigint): bigint {");
    w.open("if (typeof value === \"bigint\") {");
    w.line("return value;");
    w.close("}");
    w.open("if (!Number.isFinite(value)) {");
    w.line("return 0n;");
    w.close("}");
    w.line("return BigInt(Math.trunc(value));");
    w.close("}");
    w.blank();
    w.open("function maskBits(lenBits: number): bigint {");
    w.open("if (lenBits <= 0) {");
    w.line("return 0n;");
    w.close("}");
    w.line("return (1n << BigInt(lenBits)) - 1n;");
    w.close("}");
    w.blank();
    w.open("export function byteLengthForBits(totalBits: number): number {");
    w.open("if (totalBits <= 0) {");
    w.line("return 0;");
    w.close("}");
    w.line("return Math.floor((totalBits + 7) / 8);");
    w.close("}");
    w.blank();
    w.open("export function errorMessage(code: number): string {");
    w.open("switch (code) {");
    w.line("case -2: return \"invalid argument\";");
    w.line("case -3: return \"" + codegen_diagnostic_text::serializationBufferTooSmall() + "\";");
    w.line("case -10: return \"array length out of range\";");
    w.line("case -11: return \"invalid union tag\";");
    w.line("case -12: return \"invalid delimiter header\";");
    w.line("default: return \"serialisation error \" + code;");
    w.close("}");
    w.close("}");
    w.blank();
    w.open("function setRawBit(buf: Uint8Array, offBits: number, bit: boolean): void {");
    w.line("const byteIndex = Math.floor(offBits / 8);");
    w.line("const bitIndex = offBits % 8;");
    w.open("if (byteIndex < 0 || byteIndex >= buf.length) {");
    w.line("throw new Error(\"" + codegen_diagnostic_text::serializationBufferTooSmall() + "\");");
    w.close("}");
    w.line("const mask = 1 << bitIndex;");
    w.open("if (bit) {");
    w.line("buf[byteIndex] = (buf[byteIndex] | mask) & 0xff;");
    w.midway("} else {");
    w.line("buf[byteIndex] = (buf[byteIndex] & (~mask)) & 0xff;");
    w.close("}");
    w.close("}");
    w.blank();
    w.open("function getRawBit(buf: Uint8Array, offBits: number): boolean {");
    w.line("const byteIndex = Math.floor(offBits / 8);");
    w.line("const bitIndex = offBits % 8;");
    w.open("if (byteIndex < 0 || byteIndex >= buf.length) {");
    w.line("return false;");
    w.close("}");
    w.line("return ((buf[byteIndex] >> bitIndex) & 1) === 1;");
    w.close("}");
    w.blank();
    w.open("function writeUnsignedBits(");
    w.line("buf: Uint8Array,");
    w.line("offBits: number,");
    w.line("lenBits: number,");
    w.line("value: bigint");
    w.midway("): void {");
    w.open("for (let i = 0; i < lenBits; ++i) {");
    w.line("const bit = ((value >> BigInt(i)) & 1n) === 1n;");
    w.line("setRawBit(buf, offBits + i, bit);");
    w.close("}");
    w.close("}");
    w.blank();
    w.open("function readUnsignedBits(buf: Uint8Array, offBits: number, lenBits: number): bigint {");
    w.line("let out = 0n;");
    w.open("for (let i = 0; i < lenBits; ++i) {");
    w.open("if (getRawBit(buf, offBits + i)) {");
    w.line("out |= (1n << BigInt(i));");
    w.close("}");
    w.close("}");
    w.line("return out;");
    w.close("}");
    w.blank();
    w.open("export function setBit(buf: Uint8Array, offBits: number, value: boolean): number {");
    w.line("setRawBit(buf, offBits, !!value);");
    w.line("return 0;");
    w.close("}");
    w.blank();
    w.open("export function getBit(buf: Uint8Array, offBits: number): boolean {");
    w.line("return getRawBit(buf, offBits);");
    w.close("}");
    w.blank();
    w.open("export function copyBits(");
    w.line("dst: Uint8Array,");
    w.line("dstOffBits: number,");
    w.line("src: Uint8Array,");
    w.line("srcOffBits: number,");
    w.line("lenBits: number");
    w.midway("): void {");
    w.open("if (lenBits <= 0) {");
    w.line("return;");
    w.close("}");
    if (runtimeSpecialization == RuntimeSpecialization::Fast)
    {
        w.open("if (dst !== src && dstOffBits % 8 === 0 && srcOffBits % 8 === 0 && lenBits % 8 === 0) {");
        w.line("const dstStart = Math.floor(dstOffBits / 8);");
        w.line("const srcStart = Math.floor(srcOffBits / 8);");
        w.line("const byteLen = Math.floor(lenBits / 8);");
        w.open("if (dstStart >= 0 && srcStart >= 0 &&");
        w.line("dstStart + byteLen <= dst.length && srcStart + byteLen <= src.length) {");
        w.line("dst.set(src.subarray(srcStart, srcStart + byteLen), dstStart);");
        w.line("return;");
        w.close("}");
        w.close("}");
    }
    w.open("for (let i = 0; i < lenBits; ++i) {");
    w.line("setRawBit(dst, dstOffBits + i, getRawBit(src, srcOffBits + i));");
    w.close("}");
    w.close("}");
    w.blank();
    w.open("export function extractBits(");
    w.line("src: Uint8Array,");
    w.line("srcOffBits: number,");
    w.line("lenBits: number");
    w.midway("): Uint8Array {");
    if (runtimeSpecialization == RuntimeSpecialization::Fast)
    {
        w.open("if (srcOffBits % 8 === 0 && lenBits % 8 === 0) {");
        w.line("const srcStart = Math.floor(srcOffBits / 8);");
        w.line("const byteLen = Math.floor(lenBits / 8);");
        w.open("if (srcStart >= 0 && srcStart + byteLen <= src.length) {");
        w.line("return src.slice(srcStart, srcStart + byteLen);");
        w.close("}");
        w.close("}");
    }
    w.line("const out = new Uint8Array(byteLengthForBits(lenBits));");
    w.line("copyBits(out, 0, src, srcOffBits, lenBits);");
    w.line("return out;");
    w.close("}");
    w.blank();
    w.open("export function writeUnsigned(");
    w.line("buf: Uint8Array,");
    w.line("offBits: number,");
    w.line("lenBits: number,");
    w.line("value: number | bigint,");
    w.line("saturating: boolean");
    w.midway("): number {");
    w.open("if (lenBits <= 0) {");
    w.line("return 0;");
    w.close("}");
    w.line("const max = maskBits(lenBits);");
    w.line("let inValue = toBigIntValue(value);");
    w.open("if (saturating) {");
    w.open("if (inValue < 0n) {");
    w.line("inValue = 0n;");
    w.midway("} else if (inValue > max) {");
    w.line("inValue = max;");
    w.close("}");
    w.midway("} else {");
    w.line("inValue = BigInt.asUintN(lenBits, inValue);");
    w.close("}");
    w.line("writeUnsignedBits(buf, offBits, lenBits, inValue);");
    w.line("return 0;");
    w.close("}");
    w.blank();
    w.open("export function writeSigned(");
    w.line("buf: Uint8Array,");
    w.line("offBits: number,");
    w.line("lenBits: number,");
    w.line("value: number | bigint,");
    w.line("saturating: boolean");
    w.midway("): number {");
    w.open("if (lenBits <= 0) {");
    w.line("return 0;");
    w.close("}");
    w.line("let inValue = toBigIntValue(value);");
    w.open("if (saturating) {");
    w.line("const min = -(1n << BigInt(lenBits - 1));");
    w.line("const max = (1n << BigInt(lenBits - 1)) - 1n;");
    w.open("if (inValue < min) {");
    w.line("inValue = min;");
    w.midway("} else if (inValue > max) {");
    w.line("inValue = max;");
    w.close("}");
    w.close("}");
    w.line("writeUnsignedBits(buf, offBits, lenBits, BigInt.asUintN(lenBits, inValue));");
    w.line("return 0;");
    w.close("}");
    w.blank();
    w.open("function float32ToBits(value: number): number {");
    w.line("const bytes = new ArrayBuffer(4);");
    w.line("const view = new DataView(bytes);");
    w.line("view.setFloat32(0, value, true);");
    w.line("return view.getUint32(0, true);");
    w.close("}");
    w.blank();
    w.open("function bitsToFloat32(bits: number): number {");
    w.line("const bytes = new ArrayBuffer(4);");
    w.line("const view = new DataView(bytes);");
    w.line("view.setUint32(0, bits >>> 0, true);");
    w.line("return view.getFloat32(0, true);");
    w.close("}");
    w.blank();
    w.open("function float64ToBits(value: number): bigint {");
    w.line("const bytes = new ArrayBuffer(8);");
    w.line("const view = new DataView(bytes);");
    w.line("view.setFloat64(0, value, true);");
    w.line("return view.getBigUint64(0, true);");
    w.close("}");
    w.blank();
    w.open("function bitsToFloat64(bits: bigint): number {");
    w.line("const bytes = new ArrayBuffer(8);");
    w.line("const view = new DataView(bytes);");
    w.line("view.setBigUint64(0, bits, true);");
    w.line("return view.getFloat64(0, true);");
    w.close("}");
    w.blank();
    w.open("function float16ToBits(value: number): number {");
    w.open("if (Number.isNaN(value)) {");
    w.line("return 0x7e00;");
    w.close("}");
    w.open("if (value === Infinity) {");
    w.line("return 0x7c00;");
    w.close("}");
    w.open("if (value === -Infinity) {");
    w.line("return 0xfc00;");
    w.close("}");
    w.line("const bits = float32ToBits(value);");
    w.line("const sign = (bits >>> 16) & 0x8000;");
    w.line("let exp = ((bits >>> 23) & 0xff) - 127 + 15;");
    w.line("let mant = bits & 0x7fffff;");
    w.open("if (exp <= 0) {");
    w.open("if (exp < -10) {");
    w.line("return sign;");
    w.close("}");
    w.line("mant = (mant | 0x800000) >>> (1 - exp);");
    w.open("if ((mant & 0x1000) !== 0) {");
    w.line("mant += 0x2000;");
    w.close("}");
    w.line("return sign | (mant >>> 13);");
    w.close("}");
    w.open("if (exp >= 0x1f) {");
    w.line("return sign | 0x7c00;");
    w.close("}");
    w.open("if ((mant & 0x1000) !== 0) {");
    w.line("mant += 0x2000;");
    w.open("if ((mant & 0x800000) !== 0) {");
    w.line("mant = 0;");
    w.line("exp += 1;");
    w.open("if (exp >= 0x1f) {");
    w.line("return sign | 0x7c00;");
    w.close("}");
    w.close("}");
    w.close("}");
    w.line("return sign | (exp << 10) | (mant >>> 13);");
    w.close("}");
    w.blank();
    w.open("function bitsToFloat16(bits: number): number {");
    w.line("const sign = (bits & 0x8000) !== 0 ? -1 : 1;");
    w.line("const exp = (bits >>> 10) & 0x1f;");
    w.line("const mant = bits & 0x03ff;");
    w.open("if (exp === 0) {");
    w.open("if (mant === 0) {");
    w.line("return sign * 0;");
    w.close("}");
    w.line("return sign * Math.pow(2, -14) * (mant / 1024);");
    w.close("}");
    w.open("if (exp === 0x1f) {");
    w.line("return mant === 0 ? sign * Infinity : Number.NaN;");
    w.close("}");
    w.line("return sign * Math.pow(2, exp - 15) * (1 + (mant / 1024));");
    w.close("}");
    w.blank();
    w.open("export function writeFloat(");
    w.line("buf: Uint8Array,");
    w.line("offBits: number,");
    w.line("lenBits: number,");
    w.line("value: number");
    w.midway("): number {");
    w.open("if (lenBits === 16) {");
    w.line("writeUnsignedBits(buf, offBits, lenBits, BigInt(float16ToBits(value)));");
    w.line("return 0;");
    w.close("}");
    w.open("if (lenBits === 32) {");
    w.line("writeUnsignedBits(buf, offBits, lenBits, BigInt(float32ToBits(value)));");
    w.line("return 0;");
    w.close("}");
    w.open("if (lenBits === 64) {");
    w.line("writeUnsignedBits(buf, offBits, lenBits, float64ToBits(value));");
    w.line("return 0;");
    w.close("}");
    w.line("throw new Error(\"unsupported float bit length \" + lenBits);");
    w.close("}");
    w.blank();
    w.open("export function readFloat(buf: Uint8Array, offBits: number, lenBits: number): number {");
    w.open("if (lenBits === 16) {");
    w.line("return bitsToFloat16(Number(readUnsignedBits(buf, offBits, lenBits)));");
    w.close("}");
    w.open("if (lenBits === 32) {");
    w.line("return bitsToFloat32(Number(readUnsignedBits(buf, offBits, lenBits)));");
    w.close("}");
    w.open("if (lenBits === 64) {");
    w.line("return bitsToFloat64(readUnsignedBits(buf, offBits, lenBits));");
    w.close("}");
    w.line("throw new Error(\"unsupported float bit length \" + lenBits);");
    w.close("}");
    w.blank();
    w.open("export function readUnsignedBigInt(");
    w.line("buf: Uint8Array,");
    w.line("offBits: number,");
    w.line("lenBits: number");
    w.midway("): bigint {");
    w.open("if (lenBits <= 0) {");
    w.line("return 0n;");
    w.close("}");
    w.line("return readUnsignedBits(buf, offBits, lenBits);");
    w.close("}");
    w.blank();
    w.open("export function readSignedBigInt(");
    w.line("buf: Uint8Array,");
    w.line("offBits: number,");
    w.line("lenBits: number");
    w.midway("): bigint {");
    w.open("if (lenBits <= 0) {");
    w.line("return 0n;");
    w.close("}");
    w.line("const raw = readUnsignedBits(buf, offBits, lenBits);");
    w.line("const signBit = 1n << BigInt(lenBits - 1);");
    w.open("if ((raw & signBit) !== 0n) {");
    w.line("return raw - (1n << BigInt(lenBits));");
    w.close("}");
    w.line("return raw;");
    w.close("}");
    w.blank();
    w.open("export function readUnsigned(buf: Uint8Array, offBits: number, lenBits: number): number {");
    w.open("if (lenBits <= 0) {");
    w.line("return 0;");
    w.close("}");
    w.line("return Number(readUnsignedBigInt(buf, offBits, lenBits));");
    w.close("}");
    w.blank();
    w.open("export function readSigned(buf: Uint8Array, offBits: number, lenBits: number): number {");
    w.open("if (lenBits <= 0) {");
    w.line("return 0;");
    w.close("}");
    w.line("return Number(readSignedBigInt(buf, offBits, lenBits));");
    w.close("}");
    return out.str();
}

}  // namespace

llvm::Error emit(const SemanticModule& semantic, mlir::ModuleOp module, const Options& options)
{
    if (options.outDir.empty())
    {
        return llvm::createStringError(llvm::inconvertibleErrorCode(), "output directory is required");
    }

    std::filesystem::path const outRoot(options.outDir);
    const auto                  selectedTypeKeys = makeTypeKeySet(options.selectedTypeKeys);

    // Support artifacts are rendered from content compiled into this binary, so whether to write
    // them is independent of which definitions were selected -- except under `as-needed`, which
    // ties them to there being type code to support.
    bool anyTypeEmitted = false;
    for (const auto& def : semantic.definitions)
    {
        if (shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            anyTypeEmitted = true;
            break;
        }
    }
    const bool emitSupport = shouldEmitSupport(options.supportGeneration, anyTypeEmitted);

    if (emitSupport)
    {
        if (options.emitPackageJson)
        {
            if (auto err =
                    writeGeneratedFile(outRoot / "package.json", renderPackageJson(options), options.writePolicy))
            {
                return err;
            }
        }
        if (auto err = writeGeneratedFile(outRoot / "dsdl_runtime.ts",
                                          renderTsRuntimeModule(options.runtimeSpecialization),
                                          options.writePolicy))
        {
            return err;
        }
    }

    const EmitterContext ctx(semantic, options.typeNameVersioning);

    std::vector<const SemanticDefinition*> ordered;
    ordered.reserve(semantic.definitions.size());
    for (const auto& def : semantic.definitions)
    {
        if (!shouldEmitDefinition(def.info, selectedTypeKeys, options.supportGeneration))
        {
            continue;
        }
        ordered.push_back(&def);
    }
    std::ranges::sort(ordered, [](const auto* lhs, const auto* rhs) {
        if (lhs->info.fullName != rhs->info.fullName)
        {
            return lhs->info.fullName < rhs->info.fullName;
        }
        if (lhs->info.majorVersion != rhs->info.majorVersion)
        {
            return lhs->info.majorVersion < rhs->info.majorVersion;
        }
        return lhs->info.minorVersion < rhs->info.minorVersion;
    });

    std::vector<std::filesystem::path> generatedRelativePaths;
    generatedRelativePaths.reserve(ordered.size());

    for (const auto* def : ordered)
    {
        const std::vector<std::string> requiredTypeKeys{definitionTypeKey(def->info)};
        const auto                     relPath = EmitterContext::relativeFilePath(def->info);
        generatedRelativePaths.push_back(relPath);

        const auto fullPath = outRoot / relPath;
        auto       rendered = renderDefinitionFile(*def, ctx, module);
        if (!rendered)
        {
            return rendered.takeError();
        }

        if (auto err = writeGeneratedFile(fullPath, *rendered, options.writePolicy, requiredTypeKeys))
        {
            return err;
        }
    }

    std::ostringstream index;
    SourceWriter       indexW = makeTsWriter(index);
    indexW.line(generatedCommentLine("TypeScript backend index"));
    std::map<std::string, unsigned> aliasUseCount;
    for (const auto& relPath : generatedRelativePaths)
    {
        std::string modulePath = relPath.generic_string();
        if (modulePath.size() >= 3 && modulePath.ends_with(".ts"))
        {
            modulePath.resize(modulePath.size() - 3);
        }
        std::string alias    = moduleAliasFromPath(modulePath);
        unsigned&   useCount = aliasUseCount[alias];
        if (useCount > 0)
        {
            alias += "_" + std::to_string(useCount);
        }
        ++useCount;

        // NOLINTNEXTLINE(performance-inefficient-string-concatenation)
        indexW.line("export * as " + alias + " from \"./" + modulePath + "\";");
    }

    if (auto err = writeGeneratedFile(outRoot / "index.ts", index.str(), options.writePolicy, options.selectedTypeKeys))
    {
        return err;
    }

    return llvm::Error::success();
}

}  // namespace llvmdsdl::emitter::ts
