// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.si.sample.acceleration.Vector3.1.0
import * as dsdlRuntime from "../../../../dsdl_runtime";

import { deserializeSynchronizedTimestamp, serializeSynchronizedTimestamp } from "../../../time/synchronized_timestamp_1_0";
import type { SynchronizedTimestamp } from "../../../time/synchronized_timestamp_1_0";
export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.si.sample.acceleration.Vector3";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "invalid-bit-length";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

export interface Vector3 {
  timestamp: SynchronizedTimestamp;
  meter_per_second_per_second: Array<number>;
}


export function serializeVector3(value: Vector3): Uint8Array {
  const out = new Uint8Array(19);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_si_sample_acceleration_Vector3_1_0 = (capacityBits: number): boolean => 152 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_acceleration_Vector3_1_0__2__ser = (value: number): number => value;

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_si_sample_acceleration_Vector3_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  const timestampAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  for (let timestampAlignBit = offsetBits; timestampAlignBit < timestampAlignedOffsetBits; ++timestampAlignBit) {
    dsdlRuntime.setBit(out, timestampAlignBit, false);
  }
  offsetBits = timestampAlignedOffsetBits;
  const timestampBytes = serializeSynchronizedTimestamp(value.timestamp);
  dsdlRuntime.copyBits(out, offsetBits, timestampBytes, 0, 56);
  offsetBits += 56;
  const meter_per_second_per_secondArray = value.meter_per_second_per_second;
  if (!Array.isArray(meter_per_second_per_secondArray) || meter_per_second_per_secondArray.length !== 3) {
    throw new Error("field 'meter_per_second_per_second' expects exactly 3 elements");
  }
  for (let i = 0; i < 3; ++i) {
    dsdlRuntime.writeFloat(out, offsetBits, 32, mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_acceleration_Vector3_1_0__2__ser(meter_per_second_per_secondArray[i]));
    offsetBits += 32;
  }
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeVector3(bytes: Uint8Array): { value: Vector3; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_acceleration_Vector3_1_0__2__deser = (value: number): number => value;

  const value = {} as Vector3;
  let offsetBits = 0;
  offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
  const timestampBytes = dsdlRuntime.extractBits(bytes, offsetBits, 56);
  value.timestamp = deserializeSynchronizedTimestamp(timestampBytes).value;
  offsetBits += 56;
  const meter_per_second_per_secondArray: Array<number> = new Array(3);
  for (let i = 0; i < 3; ++i) {
    const meter_per_second_per_secondItemRaw = dsdlRuntime.readFloat(bytes, offsetBits, 32);
    meter_per_second_per_secondArray[i] = mlir_llvmdsdl_plan_scalar_float__uavcan_si_sample_acceleration_Vector3_1_0__2__deser(meter_per_second_per_secondItemRaw);
    offsetBits += 32;
  }
  value.meter_per_second_per_second = meter_per_second_per_secondArray;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
