// Generated by llvmdsdl 0.2.3 (TypeScript runtime scaffold).

function toBigIntValue(value: number | bigint): bigint {
  if (typeof value === "bigint") {
    return value;
  }
  if (!Number.isFinite(value)) {
    return 0n;
  }
  return BigInt(Math.trunc(value));
}

function maskBits(lenBits: number): bigint {
  if (lenBits <= 0) {
    return 0n;
  }
  return (1n << BigInt(lenBits)) - 1n;
}

export function byteLengthForBits(totalBits: number): number {
  if (totalBits <= 0) {
    return 0;
  }
  return Math.floor((totalBits + 7) / 8);
}

function setRawBit(buf: Uint8Array, offBits: number, bit: boolean): void {
  const byteIndex = Math.floor(offBits / 8);
  const bitIndex = offBits % 8;
  if (byteIndex < 0 || byteIndex >= buf.length) {
    throw new Error("serialization buffer too small");
  }
  const mask = 1 << bitIndex;
  if (bit) {
    buf[byteIndex] = (buf[byteIndex] | mask) & 0xff;
  } else {
    buf[byteIndex] = (buf[byteIndex] & (~mask)) & 0xff;
  }
}

function getRawBit(buf: Uint8Array, offBits: number): boolean {
  const byteIndex = Math.floor(offBits / 8);
  const bitIndex = offBits % 8;
  if (byteIndex < 0 || byteIndex >= buf.length) {
    return false;
  }
  return ((buf[byteIndex] >> bitIndex) & 1) === 1;
}

function writeUnsignedBits(
  buf: Uint8Array,
  offBits: number,
  lenBits: number,
  value: bigint
): void {
  for (let i = 0; i < lenBits; ++i) {
    const bit = ((value >> BigInt(i)) & 1n) === 1n;
    setRawBit(buf, offBits + i, bit);
  }
}

function readUnsignedBits(buf: Uint8Array, offBits: number, lenBits: number): bigint {
  let out = 0n;
  for (let i = 0; i < lenBits; ++i) {
    if (getRawBit(buf, offBits + i)) {
      out |= (1n << BigInt(i));
    }
  }
  return out;
}

export function setBit(buf: Uint8Array, offBits: number, value: boolean): void {
  setRawBit(buf, offBits, !!value);
}

export function getBit(buf: Uint8Array, offBits: number): boolean {
  return getRawBit(buf, offBits);
}

export function copyBits(
  dst: Uint8Array,
  dstOffBits: number,
  src: Uint8Array,
  srcOffBits: number,
  lenBits: number
): void {
  if (lenBits <= 0) {
    return;
  }
  for (let i = 0; i < lenBits; ++i) {
    setRawBit(dst, dstOffBits + i, getRawBit(src, srcOffBits + i));
  }
}

export function extractBits(
  src: Uint8Array,
  srcOffBits: number,
  lenBits: number
): Uint8Array {
  const out = new Uint8Array(byteLengthForBits(lenBits));
  copyBits(out, 0, src, srcOffBits, lenBits);
  return out;
}

export function writeUnsigned(
  buf: Uint8Array,
  offBits: number,
  lenBits: number,
  value: number | bigint,
  saturating: boolean
): void {
  if (lenBits <= 0) {
    return;
  }
  const max = maskBits(lenBits);
  let inValue = toBigIntValue(value);
  if (saturating) {
    if (inValue < 0n) {
      inValue = 0n;
    } else if (inValue > max) {
      inValue = max;
    }
  } else {
    inValue = BigInt.asUintN(lenBits, inValue);
  }
  writeUnsignedBits(buf, offBits, lenBits, inValue);
}

export function writeSigned(
  buf: Uint8Array,
  offBits: number,
  lenBits: number,
  value: number | bigint,
  saturating: boolean
): void {
  if (lenBits <= 0) {
    return;
  }
  let inValue = toBigIntValue(value);
  if (saturating) {
    const min = -(1n << BigInt(lenBits - 1));
    const max = (1n << BigInt(lenBits - 1)) - 1n;
    if (inValue < min) {
      inValue = min;
    } else if (inValue > max) {
      inValue = max;
    }
  }
  writeUnsignedBits(buf, offBits, lenBits, BigInt.asUintN(lenBits, inValue));
}

function float32ToBits(value: number): number {
  const bytes = new ArrayBuffer(4);
  const view = new DataView(bytes);
  view.setFloat32(0, value, true);
  return view.getUint32(0, true);
}

function bitsToFloat32(bits: number): number {
  const bytes = new ArrayBuffer(4);
  const view = new DataView(bytes);
  view.setUint32(0, bits >>> 0, true);
  return view.getFloat32(0, true);
}

function float64ToBits(value: number): bigint {
  const bytes = new ArrayBuffer(8);
  const view = new DataView(bytes);
  view.setFloat64(0, value, true);
  return view.getBigUint64(0, true);
}

function bitsToFloat64(bits: bigint): number {
  const bytes = new ArrayBuffer(8);
  const view = new DataView(bytes);
  view.setBigUint64(0, bits, true);
  return view.getFloat64(0, true);
}

function float16ToBits(value: number): number {
  if (Number.isNaN(value)) {
    return 0x7e00;
  }
  if (value === Infinity) {
    return 0x7c00;
  }
  if (value === -Infinity) {
    return 0xfc00;
  }
  const bits = float32ToBits(value);
  const sign = (bits >>> 16) & 0x8000;
  let exp = ((bits >>> 23) & 0xff) - 127 + 15;
  let mant = bits & 0x7fffff;
  if (exp <= 0) {
    if (exp < -10) {
      return sign;
    }
    mant = (mant | 0x800000) >>> (1 - exp);
    if ((mant & 0x1000) !== 0) {
      mant += 0x2000;
    }
    return sign | (mant >>> 13);
  }
  if (exp >= 0x1f) {
    return sign | 0x7c00;
  }
  if ((mant & 0x1000) !== 0) {
    mant += 0x2000;
    if ((mant & 0x800000) !== 0) {
      mant = 0;
      exp += 1;
      if (exp >= 0x1f) {
        return sign | 0x7c00;
      }
    }
  }
  return sign | (exp << 10) | (mant >>> 13);
}

function bitsToFloat16(bits: number): number {
  const sign = (bits & 0x8000) !== 0 ? -1 : 1;
  const exp = (bits >>> 10) & 0x1f;
  const mant = bits & 0x03ff;
  if (exp === 0) {
    if (mant === 0) {
      return sign * 0;
    }
    return sign * Math.pow(2, -14) * (mant / 1024);
  }
  if (exp === 0x1f) {
    return mant === 0 ? sign * Infinity : Number.NaN;
  }
  return sign * Math.pow(2, exp - 15) * (1 + (mant / 1024));
}

export function writeFloat(
  buf: Uint8Array,
  offBits: number,
  lenBits: number,
  value: number
): void {
  if (lenBits === 16) {
    writeUnsignedBits(buf, offBits, lenBits, BigInt(float16ToBits(value)));
    return;
  }
  if (lenBits === 32) {
    writeUnsignedBits(buf, offBits, lenBits, BigInt(float32ToBits(value)));
    return;
  }
  if (lenBits === 64) {
    writeUnsignedBits(buf, offBits, lenBits, float64ToBits(value));
    return;
  }
  throw new Error("unsupported float bit length " + lenBits);
}

export function readFloat(buf: Uint8Array, offBits: number, lenBits: number): number {
  if (lenBits === 16) {
    return bitsToFloat16(Number(readUnsignedBits(buf, offBits, lenBits)));
  }
  if (lenBits === 32) {
    return bitsToFloat32(Number(readUnsignedBits(buf, offBits, lenBits)));
  }
  if (lenBits === 64) {
    return bitsToFloat64(readUnsignedBits(buf, offBits, lenBits));
  }
  throw new Error("unsupported float bit length " + lenBits);
}

export function readUnsignedBigInt(
  buf: Uint8Array,
  offBits: number,
  lenBits: number
): bigint {
  if (lenBits <= 0) {
    return 0n;
  }
  return readUnsignedBits(buf, offBits, lenBits);
}

export function readSignedBigInt(
  buf: Uint8Array,
  offBits: number,
  lenBits: number
): bigint {
  if (lenBits <= 0) {
    return 0n;
  }
  const raw = readUnsignedBits(buf, offBits, lenBits);
  const signBit = 1n << BigInt(lenBits - 1);
  if ((raw & signBit) !== 0n) {
    return raw - (1n << BigInt(lenBits));
  }
  return raw;
}

export function readUnsigned(buf: Uint8Array, offBits: number, lenBits: number): number {
  if (lenBits <= 0) {
    return 0;
  }
  return Number(readUnsignedBigInt(buf, offBits, lenBits));
}

export function readSigned(buf: Uint8Array, offBits: number, lenBits: number): number {
  if (lenBits <= 0) {
    return 0;
  }
  return Number(readSignedBigInt(buf, offBits, lenBits));
}
