// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.primitive.array.Integer64.1.0

package array

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const INTEGER64_FULL_NAME = "uavcan.primitive.array.Integer64"
const INTEGER64_IS_DEPRECATED = false
const INTEGER64_FULL_NAME_AND_VERSION = "uavcan.primitive.array.Integer64.1.0"
const INTEGER64_EXTENT_BYTES = 257
const INTEGER64_SERIALIZATION_BUFFER_SIZE_BYTES = 257
const INTEGER64_ZOH_ALIAS_ELIGIBLE = false
const INTEGER64_ZOH_ALIAS_REASON = "variable-array"

type Integer64 struct {
	Value []int64
}

func (obj *Integer64) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_array_Integer64_1_0 := func(capacityBits int64) int8 {
		if 2056 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_array_Integer64_1_0__0__ser := func(value int64) int64 { return value }
	mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Integer64_1_0__0__ser := func(value uint64) uint64 { return value & uint64(255) }
	mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Integer64_1_0__0 := func(value int64) int8 {
		if (value < 0) || (value > 32) {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_ARRAY_LENGTH
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_array_Integer64_1_0(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_lenRc0_ := mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Integer64_1_0__0(int64(len(obj.Value)))
	if _lenRc0_ < 0 {
		return _lenRc0_, 0
	}
	_err1_ := dsdlruntime.SetUxx(buffer, offsetBits, mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Integer64_1_0__0__ser(uint64(len(obj.Value))), 8)
	if _err1_ < 0 {
		return _err1_, 0
	}
	offsetBits += 8
	for _index2_ := 0; _index2_ < len(obj.Value); _index2_++ {
		_err3_ := dsdlruntime.SetIxx(buffer, offsetBits, mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_array_Integer64_1_0__0__ser(int64(obj.Value[_index2_])), 64)
		if _err3_ < 0 {
			return _err3_, 0
		}
		offsetBits += 64
	}
	for (offsetBits % 8) != 0 {
		_err4_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err4_ < 0 {
			return _err4_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *Integer64) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_array_Integer64_1_0__0__deser := func(value int64) int64 { return value }
	mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Integer64_1_0__0__deser := func(value uint64) uint64 { return value & uint64(255) }
	mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Integer64_1_0__0 := func(value int64) int8 {
		if (value < 0) || (value > 32) {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_ARRAY_LENGTH
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	_countRaw6_ := dsdlruntime.GetU64(buffer, offsetBits, 8)
	offsetBits += 8
	_count5_ := int(mlir_llvmdsdl_plan_array_length_prefix__uavcan_primitive_array_Integer64_1_0__0__deser(_countRaw6_))
	_lenRc7_ := mlir_llvmdsdl_plan_validate_array_length__uavcan_primitive_array_Integer64_1_0__0(int64(_count5_))
	if _lenRc7_ < 0 {
		return _lenRc7_, 0
	}
	obj.Value = make([]int64, _count5_)
	for _index8_ := 0; _index8_ < _count5_; _index8_++ {
		_raw9_ := int64(dsdlruntime.GetU64(buffer, offsetBits, 64))
		obj.Value[_index8_] = int64(mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_array_Integer64_1_0__0__deser(_raw9_))
		offsetBits += 64
	}
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}
