// Generated by llvmdsdl 0.2.3 (Rust backend).
// Source: uavcan.register.Value.1.0
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(deprecated)]

use crate::uavcan::primitive::empty_1_0::uavcan_primitive_Empty;
use crate::uavcan::primitive::string_1_0::uavcan_primitive_String;
use crate::uavcan::primitive::unstructured_1_0::uavcan_primitive_Unstructured;
use crate::uavcan::primitive::array::bit_1_0::uavcan_primitive_array_Bit;
use crate::uavcan::primitive::array::integer16_1_0::uavcan_primitive_array_Integer16;
use crate::uavcan::primitive::array::integer32_1_0::uavcan_primitive_array_Integer32;
use crate::uavcan::primitive::array::integer64_1_0::uavcan_primitive_array_Integer64;
use crate::uavcan::primitive::array::integer8_1_0::uavcan_primitive_array_Integer8;
use crate::uavcan::primitive::array::natural16_1_0::uavcan_primitive_array_Natural16;
use crate::uavcan::primitive::array::natural32_1_0::uavcan_primitive_array_Natural32;
use crate::uavcan::primitive::array::natural64_1_0::uavcan_primitive_array_Natural64;
use crate::uavcan::primitive::array::natural8_1_0::uavcan_primitive_array_Natural8;
use crate::uavcan::primitive::array::real16_1_0::uavcan_primitive_array_Real16;
use crate::uavcan::primitive::array::real32_1_0::uavcan_primitive_array_Real32;
use crate::uavcan::primitive::array::real64_1_0::uavcan_primitive_array_Real64;

/// This union contains all possible value types supported by the register protocol.
/// Numeric types can be either scalars or arrays; the former is a special case of the latter.
#[derive(Clone, Debug, PartialEq)]
pub struct uavcan_register_Value {
    /// Tag 0     Used to represent an undefined value
    pub empty: uavcan_primitive_Empty,
    /// Tag 1     UTF-8 encoded text
    pub string: uavcan_primitive_String,
    /// Tag 2     Raw unstructured binary image
    pub unstructured: uavcan_primitive_Unstructured,
    /// Tag 3     Bit array
    pub bit: uavcan_primitive_array_Bit,
    /// Tag 4
    pub integer64: uavcan_primitive_array_Integer64,
    /// Tag 5
    pub integer32: uavcan_primitive_array_Integer32,
    /// Tag 6
    pub integer16: uavcan_primitive_array_Integer16,
    /// Tag 7
    pub integer8: uavcan_primitive_array_Integer8,
    /// Tag 8
    pub natural64: uavcan_primitive_array_Natural64,
    /// Tag 9
    pub natural32: uavcan_primitive_array_Natural32,
    /// Tag 10
    pub natural16: uavcan_primitive_array_Natural16,
    /// Tag 11
    pub natural8: uavcan_primitive_array_Natural8,
    /// Tag 12    Exactly representable integers: [-2**53,    +2**53]
    pub real64: uavcan_primitive_array_Real64,
    /// Tag 13    Exactly representable integers: [-16777216, +16777216]
    pub real32: uavcan_primitive_array_Real32,
    /// Tag 14    Exactly representable integers: [-2048,     +2048]
    pub real16: uavcan_primitive_array_Real16,
    pub _tag_: u8,
}

impl Default for uavcan_register_Value {
    fn default() -> Self {
        Self {
            empty: uavcan_primitive_Empty::default(),
            string: uavcan_primitive_String::default(),
            unstructured: uavcan_primitive_Unstructured::default(),
            bit: uavcan_primitive_array_Bit::default(),
            integer64: uavcan_primitive_array_Integer64::default(),
            integer32: uavcan_primitive_array_Integer32::default(),
            integer16: uavcan_primitive_array_Integer16::default(),
            integer8: uavcan_primitive_array_Integer8::default(),
            natural64: uavcan_primitive_array_Natural64::default(),
            natural32: uavcan_primitive_array_Natural32::default(),
            natural16: uavcan_primitive_array_Natural16::default(),
            natural8: uavcan_primitive_array_Natural8::default(),
            real64: uavcan_primitive_array_Real64::default(),
            real32: uavcan_primitive_array_Real32::default(),
            real16: uavcan_primitive_array_Real16::default(),
            _tag_: 0,
        }
    }
}

impl uavcan_register_Value {
    pub const FULL_NAME: &'static str = "uavcan.register.Value";
    pub const IS_DEPRECATED: bool = false;
    pub const FULL_NAME_AND_VERSION: &'static str = "uavcan.register.Value.1.0";
    pub const EXTENT_BYTES: usize = 259;
    pub const SERIALIZATION_BUFFER_SIZE_BYTES: usize = 259;
    pub const ZOH_ALIAS_ELIGIBLE: bool = false;
    pub const ZOH_ALIAS_REASON: &'static str = "invalid-bit-length";
    pub const __LLVMDSDL_MEMORY_MODE: crate::dsdl_runtime::DsdlMemoryMode = crate::dsdl_runtime::DsdlMemoryMode::MaxInline;
    pub const __LLVMDSDL_INLINE_THRESHOLD_BYTES: usize = 256usize;
    pub const UNION_OPTION_COUNT: usize = 15;

    pub fn serialize(&self, buffer: &mut [u8]) -> core::result::Result<usize, i8> {
        let mut offset_bits: usize = 0;
        let mlir_llvmdsdl_plan_capacity_check__uavcan_register_Value_1_0 = |capacity_bits: i64| -> i8 {
            if 2072i64 > capacity_bits {
                -crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
            } else {
                crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS
            }
        };
        let mlir_llvmdsdl_plan_validate_union_tag__uavcan_register_Value_1_0 = |tag_value: i64| -> i8 {
            if (tag_value == 0i64) || (tag_value == 1i64) || (tag_value == 2i64) || (tag_value == 3i64) || (tag_value == 4i64) || (tag_value == 5i64) || (tag_value == 6i64) || (tag_value == 7i64) || (tag_value == 8i64) || (tag_value == 9i64) || (tag_value == 10i64) || (tag_value == 11i64) || (tag_value == 12i64) || (tag_value == 13i64) || (tag_value == 14i64) {
                crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS
            } else {
                -crate::dsdl_runtime::DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG
            }
        };
        let mlir_llvmdsdl_plan_union_tag__uavcan_register_Value_1_0__ser = |value: u64| -> u64 { value & 255u64 };
        let _err_capacity = mlir_llvmdsdl_plan_capacity_check__uavcan_register_Value_1_0(buffer.len().saturating_mul(8) as i64);
        if _err_capacity != crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS {
            return Err(_err_capacity);
        }
        let _err_union_tag = mlir_llvmdsdl_plan_validate_union_tag__uavcan_register_Value_1_0(self._tag_ as i64);
        if _err_union_tag != crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS { return Err(_err_union_tag); }
        let _err0_ = crate::dsdl_runtime::set_uxx(buffer, offset_bits, mlir_llvmdsdl_plan_union_tag__uavcan_register_Value_1_0__ser(self._tag_ as u64), 8u8);
        if _err0_ < 0 { return Err(_err0_); }
        offset_bits += 8;
        match self._tag_ {
            0 => {
                while (offset_bits % 8usize) != 0 {
                    let _err1_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err1_ < 0 { return Err(_err1_); }
                    offset_bits += 1;
                }
                let mut _size_bytes2_ = 0usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes2_).min(buffer.len());
                let _err3_ = self.empty.serialize(&mut buffer[_start.._end]);
                match _err3_ {
                    Ok(v) => _size_bytes2_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes2_ * 8;
            }
            1 => {
                while (offset_bits % 8usize) != 0 {
                    let _err4_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err4_ < 0 { return Err(_err4_); }
                    offset_bits += 1;
                }
                let mut _size_bytes5_ = 258usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes5_).min(buffer.len());
                let _err6_ = self.string.serialize(&mut buffer[_start.._end]);
                match _err6_ {
                    Ok(v) => _size_bytes5_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes5_ * 8;
            }
            2 => {
                while (offset_bits % 8usize) != 0 {
                    let _err7_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err7_ < 0 { return Err(_err7_); }
                    offset_bits += 1;
                }
                let mut _size_bytes8_ = 258usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes8_).min(buffer.len());
                let _err9_ = self.unstructured.serialize(&mut buffer[_start.._end]);
                match _err9_ {
                    Ok(v) => _size_bytes8_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes8_ * 8;
            }
            3 => {
                while (offset_bits % 8usize) != 0 {
                    let _err10_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err10_ < 0 { return Err(_err10_); }
                    offset_bits += 1;
                }
                let mut _size_bytes11_ = 258usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes11_).min(buffer.len());
                let _err12_ = self.bit.serialize(&mut buffer[_start.._end]);
                match _err12_ {
                    Ok(v) => _size_bytes11_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes11_ * 8;
            }
            4 => {
                while (offset_bits % 8usize) != 0 {
                    let _err13_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err13_ < 0 { return Err(_err13_); }
                    offset_bits += 1;
                }
                let mut _size_bytes14_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes14_).min(buffer.len());
                let _err15_ = self.integer64.serialize(&mut buffer[_start.._end]);
                match _err15_ {
                    Ok(v) => _size_bytes14_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes14_ * 8;
            }
            5 => {
                while (offset_bits % 8usize) != 0 {
                    let _err16_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err16_ < 0 { return Err(_err16_); }
                    offset_bits += 1;
                }
                let mut _size_bytes17_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes17_).min(buffer.len());
                let _err18_ = self.integer32.serialize(&mut buffer[_start.._end]);
                match _err18_ {
                    Ok(v) => _size_bytes17_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes17_ * 8;
            }
            6 => {
                while (offset_bits % 8usize) != 0 {
                    let _err19_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err19_ < 0 { return Err(_err19_); }
                    offset_bits += 1;
                }
                let mut _size_bytes20_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes20_).min(buffer.len());
                let _err21_ = self.integer16.serialize(&mut buffer[_start.._end]);
                match _err21_ {
                    Ok(v) => _size_bytes20_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes20_ * 8;
            }
            7 => {
                while (offset_bits % 8usize) != 0 {
                    let _err22_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err22_ < 0 { return Err(_err22_); }
                    offset_bits += 1;
                }
                let mut _size_bytes23_ = 258usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes23_).min(buffer.len());
                let _err24_ = self.integer8.serialize(&mut buffer[_start.._end]);
                match _err24_ {
                    Ok(v) => _size_bytes23_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes23_ * 8;
            }
            8 => {
                while (offset_bits % 8usize) != 0 {
                    let _err25_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err25_ < 0 { return Err(_err25_); }
                    offset_bits += 1;
                }
                let mut _size_bytes26_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes26_).min(buffer.len());
                let _err27_ = self.natural64.serialize(&mut buffer[_start.._end]);
                match _err27_ {
                    Ok(v) => _size_bytes26_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes26_ * 8;
            }
            9 => {
                while (offset_bits % 8usize) != 0 {
                    let _err28_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err28_ < 0 { return Err(_err28_); }
                    offset_bits += 1;
                }
                let mut _size_bytes29_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes29_).min(buffer.len());
                let _err30_ = self.natural32.serialize(&mut buffer[_start.._end]);
                match _err30_ {
                    Ok(v) => _size_bytes29_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes29_ * 8;
            }
            10 => {
                while (offset_bits % 8usize) != 0 {
                    let _err31_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err31_ < 0 { return Err(_err31_); }
                    offset_bits += 1;
                }
                let mut _size_bytes32_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes32_).min(buffer.len());
                let _err33_ = self.natural16.serialize(&mut buffer[_start.._end]);
                match _err33_ {
                    Ok(v) => _size_bytes32_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes32_ * 8;
            }
            11 => {
                while (offset_bits % 8usize) != 0 {
                    let _err34_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err34_ < 0 { return Err(_err34_); }
                    offset_bits += 1;
                }
                let mut _size_bytes35_ = 258usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes35_).min(buffer.len());
                let _err36_ = self.natural8.serialize(&mut buffer[_start.._end]);
                match _err36_ {
                    Ok(v) => _size_bytes35_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes35_ * 8;
            }
            12 => {
                while (offset_bits % 8usize) != 0 {
                    let _err37_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err37_ < 0 { return Err(_err37_); }
                    offset_bits += 1;
                }
                let mut _size_bytes38_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes38_).min(buffer.len());
                let _err39_ = self.real64.serialize(&mut buffer[_start.._end]);
                match _err39_ {
                    Ok(v) => _size_bytes38_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes38_ * 8;
            }
            13 => {
                while (offset_bits % 8usize) != 0 {
                    let _err40_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err40_ < 0 { return Err(_err40_); }
                    offset_bits += 1;
                }
                let mut _size_bytes41_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes41_).min(buffer.len());
                let _err42_ = self.real32.serialize(&mut buffer[_start.._end]);
                match _err42_ {
                    Ok(v) => _size_bytes41_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes41_ * 8;
            }
            14 => {
                while (offset_bits % 8usize) != 0 {
                    let _err43_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
                    if _err43_ < 0 { return Err(_err43_); }
                    offset_bits += 1;
                }
                let mut _size_bytes44_ = 257usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _end = _start.saturating_add(_size_bytes44_).min(buffer.len());
                let _err45_ = self.real16.serialize(&mut buffer[_start.._end]);
                match _err45_ {
                    Ok(v) => _size_bytes44_ = v,
                    Err(e) => return Err(e),
                }
                offset_bits += _size_bytes44_ * 8;
            }
            _ => return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG),
        }
        while (offset_bits % 8usize) != 0 {
            let _err46_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
            if _err46_ < 0 { return Err(_err46_); }
            offset_bits += 1;
        }
        Ok(offset_bits / 8)
    }

    pub fn deserialize(&mut self, buffer: &[u8]) -> core::result::Result<usize, i8> {
        let capacity_bytes = buffer.len();
        let capacity_bits = capacity_bytes.saturating_mul(8);

        let mut offset_bits: usize = 0;
        let mlir_llvmdsdl_plan_validate_union_tag__uavcan_register_Value_1_0 = |tag_value: i64| -> i8 {
            if (tag_value == 0i64) || (tag_value == 1i64) || (tag_value == 2i64) || (tag_value == 3i64) || (tag_value == 4i64) || (tag_value == 5i64) || (tag_value == 6i64) || (tag_value == 7i64) || (tag_value == 8i64) || (tag_value == 9i64) || (tag_value == 10i64) || (tag_value == 11i64) || (tag_value == 12i64) || (tag_value == 13i64) || (tag_value == 14i64) {
                crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS
            } else {
                -crate::dsdl_runtime::DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG
            }
        };
        let mlir_llvmdsdl_plan_union_tag__uavcan_register_Value_1_0__deser = |value: u64| -> u64 { value & 255u64 };
        let _tag_raw47_ = crate::dsdl_runtime::get_u64(buffer, offset_bits, 8u8);
        self._tag_ = (mlir_llvmdsdl_plan_union_tag__uavcan_register_Value_1_0__deser(_tag_raw47_)) as u8;
        let _err_union_tag = mlir_llvmdsdl_plan_validate_union_tag__uavcan_register_Value_1_0(self._tag_ as i64);
        if _err_union_tag != crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS { return Err(_err_union_tag); }
        offset_bits += 8;
        match self._tag_ {
            0 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.empty.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            1 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.string.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            2 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.unstructured.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            3 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.bit.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            4 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.integer64.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            5 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.integer32.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            6 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.integer16.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            7 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.integer8.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            8 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.natural64.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            9 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.natural32.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            10 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.natural16.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            11 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.natural8.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            12 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.real64.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            13 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.real32.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            14 => {
                offset_bits = (offset_bits + 7) & !7usize;
                let _start = crate::dsdl_runtime::choose_min(offset_bits / 8, buffer.len());
                let _slice = &buffer[_start..buffer.len()];
                let _consumed = match self.real16.deserialize(_slice) { Ok(v) => v, Err(e) => return Err(e) };

                offset_bits += _consumed * 8;
            }
            _ => return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG),
        }
        offset_bits = (offset_bits + 7) & !7usize;
        Ok(crate::dsdl_runtime::choose_min(offset_bits, capacity_bits) / 8)
    }

    pub fn deserialize_with_consumed(&mut self, buffer: &[u8]) -> (i8, usize) {
        match self.deserialize(buffer) {
            Ok(consumed) => (0, consumed),
            Err(rc) => (rc, buffer.len()),
        }
    }

    pub fn try_deserialize_view<'a>(buffer: &'a [u8]) -> core::result::Result<(&'a [u8], usize), i8> {
        if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = "big") {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;
        if buffer.len() < required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);
        }
        Ok((&buffer[..required], required))
    }

    pub fn try_serialize_view(view_bytes: &[u8], buffer: &mut [u8]) -> core::result::Result<usize, i8> {
        if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = "big") {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;
        if view_bytes.len() != required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        if buffer.len() < required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);
        }
        buffer[..required].copy_from_slice(&view_bytes[..required]);
        Ok(required)
    }

    pub fn to_bytes(&self) -> core::result::Result<crate::dsdl_runtime::DsdlVec<u8>, i8> {
        let mut buffer = crate::dsdl_runtime::DsdlVec::<u8>::with_capacity(Self::SERIALIZATION_BUFFER_SIZE_BYTES);
        buffer.resize(Self::SERIALIZATION_BUFFER_SIZE_BYTES, 0u8);
        let used = self.serialize(&mut buffer)?;
        buffer.truncate(used);
        Ok(buffer)
    }

    pub fn from_bytes(buffer: &[u8]) -> core::result::Result<(Self, usize), i8> {
        let mut out = Self::default();
        let used = out.deserialize(buffer)?;
        Ok((out, used))
    }
}

