#!/usr/bin/env python3
#===----------------------------------------------------------------------===#
#
# Part of the OpenCyphal project, under the MIT licence
# SPDX-License-Identifier: MIT
#
#===----------------------------------------------------------------------===#

"""Embed the language-runtime support sources into a C++ translation unit.

The native/scripted emitters (C, C++, Rust, Go, Python) ship a hand-written
runtime scaffold alongside every generated package. Historically each emitter
read that scaffold from ``${LLVMDSDL_SOURCE_DIR}/runtime/...`` at emit time --
an absolute path baked into the binary at compile time. That path does not
exist on a machine that installed a packaged ``dsdlc``, so five of the six
backends could not run outside a source checkout.

This generator captures the runtime sources *verbatim* into
``EmbeddedRuntimeSources.inc`` as raw string literals plus a lookup table, so
the emitters resolve them from the binary itself with no filesystem access.

Unlike the embedded UAVCAN MLIR catalog -- which requires a *built* ``dsdlc``
to produce and is therefore committed -- this embed only reads files, so CMake
regenerates it at build time (see lib/CodeGen/CMakeLists.txt) with the runtime
sources as dependencies. It is a build product, never committed, and can never
go stale relative to the sources it embeds.

The MANIFEST below is the single source of truth for *which* files are embedded
and is exposed via ``--print-manifest`` so CMake can depend on exactly this set.
Each path is relative to the repository ``runtime/`` directory and must match
the path the corresponding emitter looks up at emit time.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Paths are relative to <repo>/runtime. Keep in lockstep with the emitter
# lookups: CEmitter/CppEmitter (dsdl_runtime.h), CppEmitter (cpp/*.hpp),
# RustEmitter (rust/*.rs), GoEmitter (go/dsdl_runtime.go), PythonEmitter
# (python/*.py). A path here that no emitter reads is dead weight; an emitter
# lookup with no path here fails at emit time with "embedded runtime source
# missing" -- so a mismatch is loud, not silent.
MANIFEST: tuple[str, ...] = (
    "dsdl_runtime.h",
    "cpp/dsdl_runtime.hpp",
    "cpp/autosar/dsdl_runtime.hpp",
    "rust/dsdl_runtime.rs",
    "rust/dsdl_runtime_semantic_wrappers.rs",
    "go/dsdl_runtime.go",
    "python/_dsdl_runtime.py",
    "python/_dsdl_runtime_fast.py",
    "python/_runtime_loader.py",
)

# A raw-string delimiter that must not appear as the closing token )DELIM" in
# any embedded source. Asserted below; picked to be unmistakably ours. The C++
# grammar caps a raw-string delimiter at 16 characters, so keep this short.
DELIMITER = "LLVMDSDL_RT"

HEADER = """\
//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Auto-generated embedded language-runtime support sources.
///
/// Generated by: tools/runtime/generate_embedded_runtime.py
/// Source: runtime/
///
/// DO NOT EDIT MANUALLY. This is a build product regenerated from the files
/// under runtime/; edit those instead.
//===----------------------------------------------------------------------===//

// clang-format off
namespace llvmdsdl::embedded_runtime::detail
{
"""

FOOTER_TEMPLATE = """\
inline constexpr EmbeddedRuntimeEntry kEmbeddedRuntimeFiles[] = {
__ROWS__
};
inline constexpr std::size_t kEmbeddedRuntimeFileCount =
    sizeof(kEmbeddedRuntimeFiles) / sizeof(kEmbeddedRuntimeFiles[0]);
}  // namespace llvmdsdl::embedded_runtime::detail
// clang-format on
"""


def _read_source(runtime_root: Path, rel: str) -> str:
    path = runtime_root / rel
    if not path.is_file():
        raise SystemExit(f"embedded runtime source not found: {path}")
    # Read as bytes and decode strictly: the runtime sources are UTF-8 and a
    # decode surprise here would silently corrupt an embedded scaffold.
    return path.read_bytes().decode("utf-8")


def _emit(runtime_root: Path) -> str:
    if len(DELIMITER) > 16:
        raise SystemExit(
            f"raw-string DELIMITER {DELIMITER!r} exceeds the 16-character C++ limit")
    close_token = f"){DELIMITER}\""
    parts: list[str] = [HEADER]
    parts.append("struct EmbeddedRuntimeEntry final\n{\n"
                 "    std::string_view path;\n"
                 "    std::string_view data;\n"
                 "};\n\n")

    rows: list[str] = []
    for index, rel in enumerate(MANIFEST):
        content = _read_source(runtime_root, rel)
        if close_token in content:
            raise SystemExit(
                f"embedded runtime source {rel!r} contains the raw-string close "
                f"token {close_token!r}; choose a different DELIMITER")
        # No newline is introduced between the raw-string delimiter and the
        # content: the embedded bytes are byte-identical to the source file, so
        # a packaged dsdlc emits exactly what an in-tree dsdlc emits.
        parts.append(
            f"inline constexpr std::string_view kEmbeddedRuntimePath_{index} =\n"
            f"    {_c_string(rel)};\n"
            f"inline constexpr std::string_view kEmbeddedRuntimeData_{index} =\n"
            f"    R\"{DELIMITER}({content}){DELIMITER}\";\n\n")
        rows.append(
            f"    {{kEmbeddedRuntimePath_{index}, kEmbeddedRuntimeData_{index}}},")

    parts.append(FOOTER_TEMPLATE.replace("__ROWS__", "\n".join(rows)))
    return "".join(parts)


def _c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
    return f"\"{escaped}\""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--runtime-root", type=Path,
        default=Path(__file__).resolve().parents[2] / "runtime",
        help="Path to the repository runtime/ directory.")
    parser.add_argument(
        "--output", type=Path,
        help="Destination .inc file, written atomically. The file's mtime is "
             "always refreshed so the build sees it as newer than its inputs "
             "(a stale-output re-run every build otherwise); the embedded "
             "content only changes when a runtime source does.")
    parser.add_argument(
        "--print-manifest", action="store_true",
        help="Print the embedded runtime source paths (relative to runtime/), "
             "one per line, and exit. Used by CMake to compute dependencies.")
    args = parser.parse_args(argv)

    if args.print_manifest:
        for rel in MANIFEST:
            print(rel)
        return 0

    if args.output is None:
        parser.error("--output is required unless --print-manifest is given")

    generated = _emit(args.runtime_root)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    tmp = args.output.with_suffix(args.output.suffix + ".tmp")
    tmp.write_text(generated, encoding="utf-8")
    tmp.replace(args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
