// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.pnp.cluster.RequestVote.1.0
import * as dsdlRuntime from "../../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.pnp.cluster.RequestVote";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "not-sealed";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "sub-byte-field";

// This type is a part of the Raft consensus algorithm. Please refer to the type AppendEntries for details.
export interface RequestVote_Request {
  term: number;
  last_log_term: number;
  // Refer to the Raft paper for explanation.
  last_log_index: number;
}


export function serializeRequestVote_Request(value: RequestVote_Request): Uint8Array {
  const out = new Uint8Array(10);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_pnp_cluster_RequestVote_1_0__request = (capacityBits: number): boolean => 80 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 4294967295n ? 4294967295n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__1__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 4294967295n ? 4294967295n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__2__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 65535n ? 65535n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_pnp_cluster_RequestVote_1_0__request(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 32, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__0__ser(value.term), true);
  offsetBits += 32;
  dsdlRuntime.writeUnsigned(out, offsetBits, 32, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__1__ser(value.last_log_term), true);
  offsetBits += 32;
  dsdlRuntime.writeUnsigned(out, offsetBits, 16, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__2__ser(value.last_log_index), true);
  offsetBits += 16;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeRequestVote_Request(bytes: Uint8Array): { value: RequestVote_Request; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 4294967295n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__1__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 4294967295n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__2__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 65535n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  const value = {} as RequestVote_Request;
  let offsetBits = 0;
  const termRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 32);
  value.term = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__0__deser(termRaw));
  offsetBits += 32;
  const last_log_termRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 32);
  value.last_log_term = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__1__deser(last_log_termRaw));
  offsetBits += 32;
  const last_log_indexRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 16);
  value.last_log_index = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__request__2__deser(last_log_indexRaw));
  offsetBits += 16;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}

// This type is a part of the Raft consensus algorithm. Please refer to the type AppendEntries for details.
export interface RequestVote_Response {
  term: number;
  // Refer to the Raft paper for explanation.
  vote_granted: boolean;
}


export function serializeRequestVote_Response(value: RequestVote_Response): Uint8Array {
  const out = new Uint8Array(5);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_pnp_cluster_RequestVote_1_0__response = (capacityBits: number): boolean => 40 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__response__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const clamped = raw < 0n ? 0n : (raw > 4294967295n ? 4294967295n : raw);
    return (typeof value === "bigint") ? clamped : Number(clamped);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_pnp_cluster_RequestVote_1_0__response(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 32, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__response__0__ser(value.term), true);
  offsetBits += 32;
  dsdlRuntime.setBit(out, offsetBits, value.vote_granted);
  offsetBits += 1;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeRequestVote_Response(bytes: Uint8Array): { value: RequestVote_Response; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__response__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 4294967295n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  const value = {} as RequestVote_Response;
  let offsetBits = 0;
  const termRaw = dsdlRuntime.readUnsigned(bytes, offsetBits, 32);
  value.term = Number(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_pnp_cluster_RequestVote_1_0__response__0__deser(termRaw));
  offsetBits += 32;
  value.vote_granted = dsdlRuntime.getBit(bytes, offsetBits);
  offsetBits += 1;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}

export type RequestVote = RequestVote_Request;
