// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.metatransport.can.ArbitrationID.0.1
import * as dsdlRuntime from "../../../dsdl_runtime";

import { deserializeBaseArbitrationID, serializeBaseArbitrationID } from "./base_arbitration_id_0_1";
import { deserializeExtendedArbitrationID, serializeExtendedArbitrationID } from "./extended_arbitration_id_0_1";
import type { BaseArbitrationID } from "./base_arbitration_id_0_1";
import type { ExtendedArbitrationID } from "./extended_arbitration_id_0_1";
export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.metatransport.can.ArbitrationID";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 0;
export const DSDL_VERSION_MINOR = 1;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "invalid-bit-length";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

// CAN frame arbitration field.
export type ArbitrationID =
  | { _tag: 0; base: BaseArbitrationID; }
  | { _tag: 1; extended: ExtendedArbitrationID; };


export function serializeArbitrationID(value: ArbitrationID): Uint8Array {
  const out = new Uint8Array(5);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_can_ArbitrationID_0_1 = (capacityBits: number): boolean => 40 <= capacityBits;
  const mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_ArbitrationID_0_1 = (tagValue: number): boolean => (tagValue === 0) || (tagValue === 1);
  const mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_ArbitrationID_0_1__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_can_ArbitrationID_0_1(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  let tag = Math.trunc((value as { _tag: number })._tag);
  if (!mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_ArbitrationID_0_1(tag)) {
    throw new Error("invalid union tag " + tag);
  }
  tag = Number(mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_ArbitrationID_0_1__ser(tag));
  dsdlRuntime.writeUnsigned(out, offsetBits, 8, tag, false);
  offsetBits += 8;
  switch (tag) {
  case 0: {
    const optionValue = (value as Record<string, unknown>).base;
    if (optionValue === undefined) {
      throw new Error("union field 'base' missing for tag 0");
    }
    const baseOptionAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    for (let baseOptionAlignBit = offsetBits; baseOptionAlignBit < baseOptionAlignedOffsetBits; ++baseOptionAlignBit) {
      dsdlRuntime.setBit(out, baseOptionAlignBit, false);
    }
    offsetBits = baseOptionAlignedOffsetBits;
    const baseBytes = serializeBaseArbitrationID(optionValue as BaseArbitrationID);
    dsdlRuntime.copyBits(out, offsetBits, baseBytes, 0, 32);
    offsetBits += 32;
    break;
  }
  case 1: {
    const optionValue = (value as Record<string, unknown>).extended;
    if (optionValue === undefined) {
      throw new Error("union field 'extended' missing for tag 1");
    }
    const extendedOptionAlignedOffsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    for (let extendedOptionAlignBit = offsetBits; extendedOptionAlignBit < extendedOptionAlignedOffsetBits; ++extendedOptionAlignBit) {
      dsdlRuntime.setBit(out, extendedOptionAlignBit, false);
    }
    offsetBits = extendedOptionAlignedOffsetBits;
    const extendedBytes = serializeExtendedArbitrationID(optionValue as ExtendedArbitrationID);
    dsdlRuntime.copyBits(out, offsetBits, extendedBytes, 0, 32);
    offsetBits += 32;
    break;
  }
  default:
    throw new Error("invalid union tag " + tag);
  }
  const alignedOffsetBits = dsdlRuntime.byteLengthForBits(offsetBits) * 8;
  for (let bit = offsetBits; bit < alignedOffsetBits; ++bit) {
    dsdlRuntime.setBit(out, bit, false);
  }
  offsetBits = alignedOffsetBits;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeArbitrationID(bytes: Uint8Array): { value: ArbitrationID; consumed: number } {
  const mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_ArbitrationID_0_1 = (tagValue: number): boolean => (tagValue === 0) || (tagValue === 1);
  const mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_ArbitrationID_0_1__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 255n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  let offsetBits = 0;
  let tag = Math.trunc(dsdlRuntime.readUnsigned(bytes, offsetBits, 8));
  tag = Number(mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_ArbitrationID_0_1__deser(tag));
  if (!mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_ArbitrationID_0_1(tag)) {
    throw new Error("decoded invalid union tag " + tag);
  }
  offsetBits += 8;
  let value: ArbitrationID;
  switch (tag) {
  case 0: {
    offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    let optionValue: BaseArbitrationID;
    const baseBytes = dsdlRuntime.extractBits(bytes, offsetBits, 32);
    optionValue = deserializeBaseArbitrationID(baseBytes).value;
    offsetBits += 32;
    value = { _tag: 0, base: optionValue } as ArbitrationID;
    break;
  }
  case 1: {
    offsetBits = Math.trunc((offsetBits + 7) / 8) * 8;
    let optionValue: ExtendedArbitrationID;
    const extendedBytes = dsdlRuntime.extractBits(bytes, offsetBits, 32);
    optionValue = deserializeExtendedArbitrationID(extendedBytes).value;
    offsetBits += 32;
    value = { _tag: 1, extended: optionValue } as ArbitrationID;
    break;
  }
  default:
    throw new Error("decoded invalid union tag " + tag);
  }
  offsetBits = dsdlRuntime.byteLengthForBits(offsetBits) * 8;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
