// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: uavcan.time.SynchronizedTimestamp.1.0
import * as dsdlRuntime from "../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "uavcan.time.SynchronizedTimestamp";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = true;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "eligible";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

// Nested data type used for representing a network-wide synchronized timestamp with microsecond resolution.
// This data type is highly recommended for use both in standard and vendor-specific messages alike.
export interface SynchronizedTimestamp {
  // The number of microseconds that have passed since some arbitrary moment in the past.
  // The moment of origin (i.e., the time base) is defined per-application. The current time base in use
  // can be requested from the time synchronization master, see the corresponding service definition.
  //
  // This value is to never overflow. The value is 56-bit wide because:
  //
  //   - 2^56 microseconds is about 2285 years, which is plenty. A 64-bit microsecond counter would be
  //     unnecessarily wide and its overflow interval of 585 thousand years induces a mild existential crisis.
  //
  //   - Classic-CAN (not FD) transports carry up to 7 bytes of payload per frame.
  //     Time sync messages shall use single-frame transfers, which means that the value can't be wider than 56 bits.
  microsecond: bigint;
}

// Zero means that the time is not known.
export const SYNCHRONIZED_TIMESTAMP_UNKNOWN = 0n;

export function serializeSynchronizedTimestamp(value: SynchronizedTimestamp): Uint8Array {
  const out = new Uint8Array(7);
  let offsetBits = 0;
  const mlir_llvmdsdl_plan_capacity_check__uavcan_time_SynchronizedTimestamp_1_0 = (capacityBits: number): boolean => 56 <= capacityBits;
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_SynchronizedTimestamp_1_0__0__ser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 72057594037927935n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  if (!mlir_llvmdsdl_plan_capacity_check__uavcan_time_SynchronizedTimestamp_1_0(out.length * 8)) {
    throw new Error("serialization buffer too small");
  }
  dsdlRuntime.writeUnsigned(out, offsetBits, 56, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_SynchronizedTimestamp_1_0__0__ser(value.microsecond), false);
  offsetBits += 56;
  const usedBytes = dsdlRuntime.byteLengthForBits(offsetBits);
  return out.subarray(0, usedBytes);
}

export function deserializeSynchronizedTimestamp(bytes: Uint8Array): { value: SynchronizedTimestamp; consumed: number } {
  const mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_SynchronizedTimestamp_1_0__0__deser = (value: number | bigint): number | bigint => {
    const raw = (typeof value === "bigint") ? value : BigInt(Math.trunc(value));
    const masked = raw & 72057594037927935n;
    return (typeof value === "bigint") ? masked : Number(masked);
  };

  const value = {} as SynchronizedTimestamp;
  let offsetBits = 0;
  const microsecondRaw = dsdlRuntime.readUnsignedBigInt(bytes, offsetBits, 56);
  value.microsecond = BigInt(mlir_llvmdsdl_plan_scalar_unsigned__uavcan_time_SynchronizedTimestamp_1_0__0__deser(microsecondRaw));
  offsetBits += 56;
  const consumed = Math.min(bytes.length, dsdlRuntime.byteLengthForBits(offsetBits));
  return { value, consumed };
}
