# Generated by llvmdsdl <LLVMDSDL_VERSION> (Python backend).
# Source: shape.Sample.1.0
from __future__ import annotations

import sys
from dataclasses import dataclass, field
from typing import ClassVar

from dsdl_gen._runtime_loader import CompositeObject, error_message, runtime as dsdl_runtime

# Two fields of one narrow width, a variable-length array and a float.
@dataclass(slots=True)
class Sample(CompositeObject):
    FULL_NAME: ClassVar[str] = "shape.Sample"
    IS_DEPRECATED: ClassVar[bool] = False
    FULL_NAME_AND_VERSION: ClassVar[str] = "shape.Sample.1.0"
    EXTENT_BYTES: ClassVar[int] = 23
    SERIALIZATION_BUFFER_SIZE_BYTES: ClassVar[int] = 23
    WIRE_FLAT: ClassVar[bool] = False
    WIRE_FLAT_REASON: ClassVar[str] = "sub-byte-field"
    HAS_FIXED_PORT_ID: ClassVar[bool] = False
    low: int = 0
    high: int = 0
    samples: list[int] = field(default_factory=list)
    ratio: float = 0.0

    def _serialize_into(self, buffer: memoryview) -> int:
        size = len(buffer)
        v0 = size * 8
        err = self._capacity_check(v0)
        if err != 0:
            raise ValueError(error_message(err))
        low_value = int(self.low)
        value = self._saturate_uint7(low_value)
        dsdl_runtime.write_unsigned(buffer, 0, 7, value, False)
        high_value = int(self.high)
        value_2 = self._saturate_uint7(high_value)
        dsdl_runtime.write_unsigned(buffer, 7, 7, value_2, False)
        samples_count = len(self.samples)
        err_2 = self._validate_samples_length(samples_count)
        if err_2 != 0:
            raise ValueError(error_message(err_2))
        dsdl_runtime.write_unsigned(buffer, 14, 8, samples_count, False)
        for i in range(0, samples_count, 1):
            v1 = i * 16
            v2 = v1 + 22
            samples_value = int(self.samples[i])
            value_3 = self._saturate_uint16(samples_value)
            dsdl_runtime.write_unsigned(buffer, v2, 16, value_3, False)
        v3 = samples_count * 16
        offset = v3 + 22
        ratio_value = float(self.ratio)
        dsdl_runtime.write_float(buffer, offset, 32, ratio_value)
        offset_2 = offset + 32
        dsdl_runtime.write_unsigned(buffer, offset_2, 2, 0, False)
        offset_3 = offset_2 + 2
        v4 = offset_3 // 8
        return v4

    def _deserialize_from(self, buffer: memoryview) -> int:
        size = len(buffer)
        value = dsdl_runtime.read_unsigned(buffer, 0, 7)
        self.low = value
        value_2 = dsdl_runtime.read_unsigned(buffer, 7, 7)
        self.high = value_2
        count = dsdl_runtime.read_unsigned(buffer, 14, 8)
        err = self._validate_samples_length(count)
        if err != 0:
            raise ValueError(error_message(err))
        self.samples = [0] * count
        for i in range(0, count, 1):
            v0 = i * 16
            v1 = v0 + 22
            value_3 = dsdl_runtime.read_unsigned(buffer, v1, 16)
            self.samples[i] = value_3
        v2 = count * 16
        v3 = v2 + 22
        value_4 = dsdl_runtime.read_float(buffer, v3, 32)
        self.ratio = value_4
        v4 = v3 + 39
        v5 = v4 // 8
        v6 = v5 * 8
        v7 = size * 8
        v8 = v6 < v7
        v9 = (v6 if v8 else v7)
        v10 = v9 // 8
        return v10

    def serialize(self) -> bytes:
        v0 = bytearray(23)
        size = self._serialize_into(memoryview(v0).cast("B"))
        return bytes(v0[:size])

    @classmethod
    def deserialize(cls, data: bytes | bytearray | memoryview) -> Sample:
        v0 = cls()
        v0._deserialize_from(memoryview(data).cast("B"))
        return v0

    @staticmethod
    def _capacity_check(p0: int) -> int:
        v0 = p0 < 184
        v1 = (-3 if v0 else 0)
        return v1

    @staticmethod
    def _saturate_uint7(p0: int) -> int:
        v0 = p0 > 127
        v1 = (127 if v0 else p0)
        return v1

    @staticmethod
    def _saturate_uint16(p0: int) -> int:
        v0 = p0 > 65535
        v1 = (65535 if v0 else p0)
        return v1

    @staticmethod
    def _validate_samples_length(p0: int) -> int:
        v0 = p0 < 0
        v1 = p0 > 8
        index_holds = (-sys.maxsize - 1 <= p0 <= sys.maxsize)
        v2 = not index_holds
        v3 = v0 or v1
        v4 = v3 or v2
        v5 = (-10 if v4 else 0)
        return v5
