// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.metatransport.can.Error.0.1

package can

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const ERROR_FULL_NAME = "uavcan.metatransport.can.Error"
const ERROR_IS_DEPRECATED = false
const ERROR_FULL_NAME_AND_VERSION = "uavcan.metatransport.can.Error.0.1"
const ERROR_EXTENT_BYTES = 4
const ERROR_SERIALIZATION_BUFFER_SIZE_BYTES = 4
const ERROR_ZOH_ALIAS_ELIGIBLE = false
const ERROR_ZOH_ALIAS_REASON = "empty-layout"

// CAN bus error report: either an intentionally generated error frame or a disturbance.
type Error struct {
}

func (obj *Error) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_can_Error_0_1 := func(capacityBits int64) int8 {
		if 32 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_can_Error_0_1(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_err0_ := dsdlruntime.SetUxx(buffer, offsetBits, 0, 32)
	if _err0_ < 0 {
		return _err0_, 0
	}
	offsetBits += 32
	for (offsetBits % 8) != 0 {
		_err1_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err1_ < 0 {
			return _err1_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *Error) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	offsetBits += 32
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}
