// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.metatransport.can.Frame.0.2

package can

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const FRAME_FULL_NAME = "uavcan.metatransport.can.Frame"
const FRAME_IS_DEPRECATED = false
const FRAME_FULL_NAME_AND_VERSION = "uavcan.metatransport.can.Frame.0.2"
const FRAME_EXTENT_BYTES = 71
const FRAME_SERIALIZATION_BUFFER_SIZE_BYTES = 71
const FRAME_ZOH_ALIAS_ELIGIBLE = false
const FRAME_ZOH_ALIAS_REASON = "invalid-bit-length"
const FRAME_UNION_OPTION_COUNT = 4

// Classic CAN or CAN FD frame representation. This is the top-level data type in its namespace.
type Frame struct {
	// CAN error (intentional or disturbance)
	Error Error
	// Bit rate switch flag active
	DataFd DataFD
	// Bit rate switch flag not active
	DataClassic DataClassic
	// Bit rate switch flag not active
	RemoteTransmissionRequest RTR
	Tag                       uint8
}

func (obj *Frame) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_can_Frame_0_2 := func(capacityBits int64) int8 {
		if 568 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_Frame_0_2 := func(tagValue int64) int8 {
		if (tagValue == 0) || (tagValue == 1) || (tagValue == 2) || (tagValue == 3) {
			return dsdlruntime.DSDL_RUNTIME_SUCCESS
		}
		return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG
	}
	mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_Frame_0_2__ser := func(value uint64) uint64 { return value & uint64(255) }
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_metatransport_can_Frame_0_2(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	if rc := mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_Frame_0_2(int64(obj.Tag)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_err0_ := dsdlruntime.SetUxx(buffer, offsetBits, mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_Frame_0_2__ser(uint64(obj.Tag)), 8)
	if _err0_ < 0 {
		return _err0_, 0
	}
	offsetBits += 8
	switch obj.Tag {
	case 0:
		for (offsetBits % 8) != 0 {
			_err1_ := dsdlruntime.SetBit(buffer, offsetBits, false)
			if _err1_ < 0 {
				return _err1_, 0
			}
			offsetBits++
		}
		_sizeBytes2_ := 4
		_start3_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_end4_ := dsdlruntime.ChooseMin(_start3_+_sizeBytes2_, len(buffer))
		_rc5_, _consumed6_ := obj.Error.Serialize(buffer[_start3_:_end4_])
		if _rc5_ < 0 {
			return _rc5_, 0
		}
		_sizeBytes2_ = _consumed6_
		offsetBits += _sizeBytes2_ * 8
	case 1:
		for (offsetBits % 8) != 0 {
			_err7_ := dsdlruntime.SetBit(buffer, offsetBits, false)
			if _err7_ < 0 {
				return _err7_, 0
			}
			offsetBits++
		}
		_sizeBytes8_ := 70
		_start9_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_end10_ := dsdlruntime.ChooseMin(_start9_+_sizeBytes8_, len(buffer))
		_rc11_, _consumed12_ := obj.DataFd.Serialize(buffer[_start9_:_end10_])
		if _rc11_ < 0 {
			return _rc11_, 0
		}
		_sizeBytes8_ = _consumed12_
		offsetBits += _sizeBytes8_ * 8
	case 2:
		for (offsetBits % 8) != 0 {
			_err13_ := dsdlruntime.SetBit(buffer, offsetBits, false)
			if _err13_ < 0 {
				return _err13_, 0
			}
			offsetBits++
		}
		_sizeBytes14_ := 14
		_start15_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_end16_ := dsdlruntime.ChooseMin(_start15_+_sizeBytes14_, len(buffer))
		_rc17_, _consumed18_ := obj.DataClassic.Serialize(buffer[_start15_:_end16_])
		if _rc17_ < 0 {
			return _rc17_, 0
		}
		_sizeBytes14_ = _consumed18_
		offsetBits += _sizeBytes14_ * 8
	case 3:
		for (offsetBits % 8) != 0 {
			_err19_ := dsdlruntime.SetBit(buffer, offsetBits, false)
			if _err19_ < 0 {
				return _err19_, 0
			}
			offsetBits++
		}
		_sizeBytes20_ := 5
		_start21_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_end22_ := dsdlruntime.ChooseMin(_start21_+_sizeBytes20_, len(buffer))
		_rc23_, _consumed24_ := obj.RemoteTransmissionRequest.Serialize(buffer[_start21_:_end22_])
		if _rc23_ < 0 {
			return _rc23_, 0
		}
		_sizeBytes20_ = _consumed24_
		offsetBits += _sizeBytes20_ * 8
	default:
		return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG, 0
	}
	for (offsetBits % 8) != 0 {
		_err25_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err25_ < 0 {
			return _err25_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *Frame) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_Frame_0_2 := func(tagValue int64) int8 {
		if (tagValue == 0) || (tagValue == 1) || (tagValue == 2) || (tagValue == 3) {
			return dsdlruntime.DSDL_RUNTIME_SUCCESS
		}
		return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG
	}
	mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_Frame_0_2__deser := func(value uint64) uint64 { return value & uint64(255) }
	_tag26_ := dsdlruntime.GetU64(buffer, offsetBits, 8)
	obj.Tag = uint8(mlir_llvmdsdl_plan_union_tag__uavcan_metatransport_can_Frame_0_2__deser(_tag26_))
	if rc := mlir_llvmdsdl_plan_validate_union_tag__uavcan_metatransport_can_Frame_0_2(int64(obj.Tag)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	offsetBits += 8
	switch obj.Tag {
	case 0:
		offsetBits = (offsetBits + 7) & ^7
		_start27_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_rc28_, _consumed29_ := obj.Error.Deserialize(buffer[_start27_:len(buffer)])
		if _rc28_ < 0 {
			return _rc28_, 0
		}
		offsetBits += _consumed29_ * 8
	case 1:
		offsetBits = (offsetBits + 7) & ^7
		_start30_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_rc31_, _consumed32_ := obj.DataFd.Deserialize(buffer[_start30_:len(buffer)])
		if _rc31_ < 0 {
			return _rc31_, 0
		}
		offsetBits += _consumed32_ * 8
	case 2:
		offsetBits = (offsetBits + 7) & ^7
		_start33_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_rc34_, _consumed35_ := obj.DataClassic.Deserialize(buffer[_start33_:len(buffer)])
		if _rc34_ < 0 {
			return _rc34_, 0
		}
		offsetBits += _consumed35_ * 8
	case 3:
		offsetBits = (offsetBits + 7) & ^7
		_start36_ := dsdlruntime.ChooseMin(offsetBits/8, len(buffer))
		_rc37_, _consumed38_ := obj.RemoteTransmissionRequest.Deserialize(buffer[_start36_:len(buffer)])
		if _rc37_ < 0 {
			return _rc37_, 0
		}
		offsetBits += _consumed38_ * 8
	default:
		return -dsdlruntime.DSDL_RUNTIME_ERROR_REPRESENTATION_BAD_UNION_TAG, 0
	}
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}
