// Generated by llvmdsdl 0.2.3 (Go backend).
// Source: uavcan.primitive.scalar.Integer8.1.0

package scalar

import (
	dsdlruntime "llvmdsdl_generated/dsdlruntime"
)

const INTEGER8_FULL_NAME = "uavcan.primitive.scalar.Integer8"
const INTEGER8_IS_DEPRECATED = false
const INTEGER8_FULL_NAME_AND_VERSION = "uavcan.primitive.scalar.Integer8.1.0"
const INTEGER8_EXTENT_BYTES = 1
const INTEGER8_SERIALIZATION_BUFFER_SIZE_BYTES = 1
const INTEGER8_ZOH_ALIAS_ELIGIBLE = true
const INTEGER8_ZOH_ALIAS_REASON = "eligible"

type Integer8 struct {
	Value int8
}

func (obj *Integer8) Serialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	offsetBits := 0
	mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_scalar_Integer8_1_0 := func(capacityBits int64) int8 {
		if 8 > capacityBits {
			return -dsdlruntime.DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
		}
		return dsdlruntime.DSDL_RUNTIME_SUCCESS
	}
	mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer8_1_0__0__ser := func(value int64) int64 {
		if value < -128 {
			return -128
		}
		if value > 127 {
			return 127
		}
		return value
	}
	if rc := mlir_llvmdsdl_plan_capacity_check__uavcan_primitive_scalar_Integer8_1_0(int64(len(buffer) * 8)); rc != dsdlruntime.DSDL_RUNTIME_SUCCESS {
		return rc, 0
	}
	_err0_ := dsdlruntime.SetIxx(buffer, offsetBits, mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer8_1_0__0__ser(int64(obj.Value)), 8)
	if _err0_ < 0 {
		return _err0_, 0
	}
	offsetBits += 8
	for (offsetBits % 8) != 0 {
		_err1_ := dsdlruntime.SetBit(buffer, offsetBits, false)
		if _err1_ < 0 {
			return _err1_, 0
		}
		offsetBits++
	}
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, offsetBits / 8
}

func (obj *Integer8) Deserialize(buffer []byte) (int8, int) {
	if obj == nil {
		return -dsdlruntime.DSDL_RUNTIME_ERROR_INVALID_ARGUMENT, 0
	}
	capacityBytes := len(buffer)
	capacityBits := capacityBytes * 8
	offsetBits := 0
	mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer8_1_0__0__deser := func(value int64) int64 {
		raw := uint64(value) & uint64(255)
		if (raw & uint64(128)) != 0 {
			return int64(raw | (^uint64(255)))
		}
		return int64(raw)
	}
	_raw2_ := int64(dsdlruntime.GetU64(buffer, offsetBits, 8))
	obj.Value = int8(mlir_llvmdsdl_plan_scalar_signed__uavcan_primitive_scalar_Integer8_1_0__0__deser(_raw2_))
	offsetBits += 8
	offsetBits = (offsetBits + 7) & ^7
	consumedBits := dsdlruntime.ChooseMin(offsetBits, capacityBits)
	return dsdlruntime.DSDL_RUNTIME_SUCCESS, consumedBits / 8
}
