// Generated by llvmdsdl 0.2.3 (Rust backend).
// Source: uavcan.diagnostic.Severity.1.0
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(deprecated)]

/// Generic message severity representation.
#[derive(Clone, Debug, PartialEq)]
pub struct uavcan_diagnostic_Severity {
    /// The severity level ranging from 0 to 7, where low values represent low-severity (unimportant) messages, and
    /// high values represent high-severity (important) messages. Several mnemonics for the severity levels are
    /// defined below. Nodes are advised to implement output filtering mechanisms, allowing users to select
    /// the minimal severity for emitted messages; messages of the selected and higher severity levels will
    /// be published, and messages of lower severity will be suppressed (discarded).
    pub value: u8,
}

impl Default for uavcan_diagnostic_Severity {
    fn default() -> Self {
        Self {
            value: 0,
        }
    }
}

impl uavcan_diagnostic_Severity {
    pub const FULL_NAME: &'static str = "uavcan.diagnostic.Severity";
    pub const IS_DEPRECATED: bool = false;
    pub const FULL_NAME_AND_VERSION: &'static str = "uavcan.diagnostic.Severity.1.0";
    pub const EXTENT_BYTES: usize = 1;
    pub const SERIALIZATION_BUFFER_SIZE_BYTES: usize = 1;
    pub const ZOH_ALIAS_ELIGIBLE: bool = false;
    pub const ZOH_ALIAS_REASON: &'static str = "sub-byte-field";
    pub const __LLVMDSDL_MEMORY_MODE: crate::dsdl_runtime::DsdlMemoryMode = crate::dsdl_runtime::DsdlMemoryMode::MaxInline;
    pub const __LLVMDSDL_INLINE_THRESHOLD_BYTES: usize = 256usize;
    /// Messages of this severity can be used only during development.
    /// They shall not be used in a fielded operational system.
    pub const TRACE: u64 = 0;
    /// Messages that can aid in troubleshooting.
    /// Messages of this severity and lower should be disabled by default.
    pub const DEBUG: u64 = 1;
    /// General informational messages of low importance.
    /// Messages of this severity and lower should be disabled by default.
    pub const INFO: u64 = 2;
    /// General informational messages of high importance.
    /// Messages of this severity and lower should be disabled by default.
    pub const NOTICE: u64 = 3;
    /// Messages reporting abnormalities and warning conditions.
    /// Messages of this severity and higher should be enabled by default.
    pub const WARNING: u64 = 4;
    /// Messages reporting problems and error conditions.
    /// Messages of this severity and higher should be enabled by default.
    pub const ERROR: u64 = 5;
    /// Messages reporting serious problems and critical conditions.
    /// Messages of this severity and higher should be always enabled.
    pub const CRITICAL: u64 = 6;
    /// Notifications of dangerous circumstances that demand immediate attention.
    /// Messages of this severity should be always enabled.
    pub const ALERT: u64 = 7;

    pub fn serialize(&self, buffer: &mut [u8]) -> core::result::Result<usize, i8> {
        let mut offset_bits: usize = 0;
        let mlir_llvmdsdl_plan_capacity_check__uavcan_diagnostic_Severity_1_0 = |capacity_bits: i64| -> i8 {
            if 8i64 > capacity_bits {
                -crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL
            } else {
                crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS
            }
        };
        let mlir_llvmdsdl_plan_scalar_unsigned__uavcan_diagnostic_Severity_1_0__0__ser = |value: u64| -> u64 { if value > 7u64 { 7u64 } else { value } };
        let _err_capacity = mlir_llvmdsdl_plan_capacity_check__uavcan_diagnostic_Severity_1_0(buffer.len().saturating_mul(8) as i64);
        if _err_capacity != crate::dsdl_runtime::DSDL_RUNTIME_SUCCESS {
            return Err(_err_capacity);
        }
        let _err0_ = crate::dsdl_runtime::set_uxx(buffer, offset_bits, mlir_llvmdsdl_plan_scalar_unsigned__uavcan_diagnostic_Severity_1_0__0__ser(self.value as u64), 3u8);
        if _err0_ < 0 { return Err(_err0_); }
        offset_bits += 3;
        while (offset_bits % 8usize) != 0 {
            let _err1_ = crate::dsdl_runtime::set_bit(buffer, offset_bits, false);
            if _err1_ < 0 { return Err(_err1_); }
            offset_bits += 1;
        }
        Ok(offset_bits / 8)
    }

    pub fn deserialize(&mut self, buffer: &[u8]) -> core::result::Result<usize, i8> {
        let capacity_bytes = buffer.len();
        let capacity_bits = capacity_bytes.saturating_mul(8);

        let mut offset_bits: usize = 0;
        let mlir_llvmdsdl_plan_scalar_unsigned__uavcan_diagnostic_Severity_1_0__0__deser = |value: u64| -> u64 { value & 7u64 };
        let _raw2_ = crate::dsdl_runtime::get_u8(buffer, offset_bits, 3u8) as u64;
        self.value = mlir_llvmdsdl_plan_scalar_unsigned__uavcan_diagnostic_Severity_1_0__0__deser(_raw2_) as u8;
        offset_bits += 3;
        offset_bits = (offset_bits + 7) & !7usize;
        Ok(crate::dsdl_runtime::choose_min(offset_bits, capacity_bits) / 8)
    }

    pub fn deserialize_with_consumed(&mut self, buffer: &[u8]) -> (i8, usize) {
        match self.deserialize(buffer) {
            Ok(consumed) => (0, consumed),
            Err(rc) => (rc, buffer.len()),
        }
    }

    pub fn try_deserialize_view<'a>(buffer: &'a [u8]) -> core::result::Result<(&'a [u8], usize), i8> {
        if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = "big") {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;
        if buffer.len() < required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);
        }
        Ok((&buffer[..required], required))
    }

    pub fn try_serialize_view(view_bytes: &[u8], buffer: &mut [u8]) -> core::result::Result<usize, i8> {
        if !Self::ZOH_ALIAS_ELIGIBLE || cfg!(target_endian = "big") {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        let required = Self::SERIALIZATION_BUFFER_SIZE_BYTES;
        if view_bytes.len() != required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_INVALID_ARGUMENT);
        }
        if buffer.len() < required {
            return Err(-crate::dsdl_runtime::DSDL_RUNTIME_ERROR_SERIALIZATION_BUFFER_TOO_SMALL);
        }
        buffer[..required].copy_from_slice(&view_bytes[..required]);
        Ok(required)
    }

    pub fn to_bytes(&self) -> core::result::Result<crate::dsdl_runtime::DsdlVec<u8>, i8> {
        let mut buffer = crate::dsdl_runtime::DsdlVec::<u8>::with_capacity(Self::SERIALIZATION_BUFFER_SIZE_BYTES);
        buffer.resize(Self::SERIALIZATION_BUFFER_SIZE_BYTES, 0u8);
        let used = self.serialize(&mut buffer)?;
        buffer.truncate(used);
        Ok(buffer)
    }

    pub fn from_bytes(buffer: &[u8]) -> core::result::Result<(Self, usize), i8> {
        let mut out = Self::default();
        let used = out.deserialize(buffer)?;
        Ok((out, used))
    }
}

