#!/usr/bin/env python3
#===----------------------------------------------------------------------===#
#
# Part of the OpenCyphal project, under the MIT licence
# SPDX-License-Identifier: MIT
#
#===----------------------------------------------------------------------===#

"""Embed the sources dsdlc carries into a C++ translation unit.

Two kinds of file travel inside the binary: the language-runtime scaffold each
native or scripted emitter writes beside every generated package, and the
built-in vocabulary bindings a backend applies before any ``--vocabulary`` file.
A packaged ``dsdlc`` has no source checkout to read them from.

This generator captures the files *verbatim* into ``EmbeddedSources.inc`` as
raw string literals plus a lookup table keyed by name, so the code resolves them
from the binary itself with no filesystem access.

Unlike the embedded UAVCAN MLIR catalogue -- which requires a *built* ``dsdlc``
to produce and is therefore committed -- this embed only reads files, so CMake
regenerates it at build time (see lib/CodeGen/CMakeLists.txt) with the sources
as dependencies. It is a build product, never committed, and can never go stale
relative to the sources it embeds.

The MANIFEST below is the single source of truth for *which* files are embedded
and is exposed via ``--print-manifest`` so CMake can depend on exactly this set.
Each entry is the key the code looks a file up by and the file's path relative
to the repository root.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Keep in lockstep with the lookups: the C and C++ emitters (dsdl_runtime.h),
# the C++ emitter (cpp/*.hpp), the Rust emitter (rust/*.rs), the Go emitter
# (go/dsdl_runtime.go), the Python emitter (python/*.py), and the vocabulary
# (vocabulary/<language>.yaml). An entry here that nothing looks up is dead
# weight; a lookup with no entry here fails at emit time with "embedded source
# missing" -- so a mismatch is loud, not silent.
MANIFEST: tuple[tuple[str, str], ...] = (
    ("dsdl_runtime.h", "runtime/dsdl_runtime.h"),
    ("cpp/dsdl_runtime.hpp", "runtime/cpp/dsdl_runtime.hpp"),
    ("cpp/autosar/dsdl_runtime.hpp", "runtime/cpp/autosar/dsdl_runtime.hpp"),
    ("rust/dsdl_runtime.rs", "runtime/rust/dsdl_runtime.rs"),
    ("rust/dsdl_runtime_semantic_wrappers.rs",
     "runtime/rust/dsdl_runtime_semantic_wrappers.rs"),
    ("go/dsdl_runtime.go", "runtime/go/dsdl_runtime.go"),
    ("python/_dsdl_runtime.py", "runtime/python/_dsdl_runtime.py"),
    ("python/_dsdl_runtime_fast.py", "runtime/python/_dsdl_runtime_fast.py"),
    ("python/_runtime_loader.py", "runtime/python/_runtime_loader.py"),
    ("vocabulary/cpp.yaml", "vocabulary/cpp.yaml"),
)

# A raw-string delimiter that must not appear as the closing token )DELIM" in
# any embedded source. Asserted below; picked to be unmistakably ours. The C++
# grammar caps a raw-string delimiter at 16 characters, so keep this short.
DELIMITER = "LLVMDSDL_RT"

HEADER = """\
//===----------------------------------------------------------------------===//
//
// Part of the OpenCyphal project, under the MIT licence
// SPDX-License-Identifier: MIT
//
//===----------------------------------------------------------------------===//

//===----------------------------------------------------------------------===//
///
/// @file
/// Auto-generated embedded sources: the language runtimes and the built-in
/// vocabulary bindings.
///
/// Generated by: tools/generate_embedded_sources.py
///
/// A build product regenerated from the files the generator's manifest names.
//===----------------------------------------------------------------------===//

// clang-format off
namespace llvmdsdl::embedded_sources::detail
{
"""

FOOTER_TEMPLATE = """\
inline constexpr EmbeddedEntry kEmbeddedFiles[] = {
__ROWS__
};
inline constexpr std::size_t kEmbeddedFileCount =
    sizeof(kEmbeddedFiles) / sizeof(kEmbeddedFiles[0]);
}  // namespace llvmdsdl::embedded_sources::detail
// clang-format on
"""


def _read_source(source_root: Path, rel: str) -> str:
    path = source_root / rel
    if not path.is_file():
        raise SystemExit(f"embedded source not found: {path}")
    # Read as bytes and decode strictly: the sources are UTF-8 and a decode
    # surprise here would silently corrupt an embedded file.
    return path.read_bytes().decode("utf-8")


def _emit(source_root: Path) -> str:
    if len(DELIMITER) > 16:
        raise SystemExit(
            f"raw-string DELIMITER {DELIMITER!r} exceeds the 16-character C++ limit")
    close_token = f"){DELIMITER}\""
    parts: list[str] = [HEADER]
    parts.append("struct EmbeddedEntry final\n{\n"
                 "    std::string_view key;\n"
                 "    std::string_view data;\n"
                 "};\n\n")

    rows: list[str] = []
    for index, (key, rel) in enumerate(MANIFEST):
        content = _read_source(source_root, rel)
        if close_token in content:
            raise SystemExit(
                f"embedded source {rel!r} contains the raw-string close "
                f"token {close_token!r}; choose a different DELIMITER")
        # No newline is introduced between the raw-string delimiter and the
        # content: the embedded bytes are byte-identical to the source file, so
        # a packaged dsdlc emits exactly what an in-tree dsdlc emits.
        parts.append(
            f"inline constexpr std::string_view kEmbeddedKey_{index} =\n"
            f"    {_c_string(key)};\n"
            f"inline constexpr std::string_view kEmbeddedData_{index} =\n"
            f"    R\"{DELIMITER}({content}){DELIMITER}\";\n\n")
        rows.append(
            f"    {{kEmbeddedKey_{index}, kEmbeddedData_{index}}},")

    parts.append(FOOTER_TEMPLATE.replace("__ROWS__", "\n".join(rows)))
    return "".join(parts)


def _c_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace("\"", "\\\"")
    return f"\"{escaped}\""


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--source-root", type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Path to the repository root.")
    parser.add_argument(
        "--output", type=Path,
        help="Destination .inc file, written atomically. The file's mtime is "
             "always refreshed so the build sees it as newer than its inputs "
             "(a stale-output re-run every build otherwise); the embedded "
             "content only changes when a source does.")
    parser.add_argument(
        "--print-manifest", action="store_true",
        help="Print the embedded files' paths relative to the repository root, "
             "one per line, and exit. Used by CMake to compute dependencies.")
    args = parser.parse_args(argv)

    if args.print_manifest:
        for _key, rel in MANIFEST:
            print(rel)
        return 0

    if args.output is None:
        parser.error("--output is required unless --print-manifest is given")

    generated = _emit(args.source_root)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    tmp = args.output.with_suffix(args.output.suffix + ".tmp")
    tmp.write_text(generated, encoding="utf-8")
    tmp.replace(args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
