// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: fixtures.vendor.UnionTag.1.0
import * as dsdlRuntime from "../../dsdl_runtime";

export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "fixtures.vendor.UnionTag";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_REQUEST_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_REQUEST_ZOH_ALIAS_REASON = "not-fixed-size";
export const DSDL_RESPONSE_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_RESPONSE_ZOH_ALIAS_REASON = "not-applicable";

function mlir_llvmdsdl_plan_capacity_check__fixtures_vendor_UnionTag_1_0(p0: bigint): number {
  const v0 = 24n > p0;
  let v1: number;
  if (v0) {
    v1 = -3;
  } else {
    v1 = 0;
  }
  return v1;
}

function mlir_llvmdsdl_plan_validate_union_tag__fixtures_vendor_UnionTag_1_0(p0: bigint): number {
  const v0 = p0 === 0n;
  const v1 = false || v0;
  const v2 = p0 === 1n;
  const v3 = v1 || v2;
  let v4: number;
  if (v3) {
    v4 = 0;
  } else {
    v4 = -11;
  }
  return v4;
}

function mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__ser(p0: bigint): bigint {
  const v0 = p0 > 255n;
  const v1 = v0 ? 255n : p0;
  return v1;
}

function mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__deser(p0: bigint): bigint {
  const v0 = p0 & 255n;
  return v0;
}

function mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__ser(p0: bigint): bigint {
  const v0 = p0 > 65535n;
  const v1 = v0 ? 65535n : p0;
  return v1;
}

function mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__deser(p0: bigint): bigint {
  const v0 = p0 & 65535n;
  return v0;
}

function mlir_llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__ser(p0: bigint): bigint {
  const v0 = p0 & 255n;
  return v0;
}

function mlir_llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__deser(p0: bigint): bigint {
  const v0 = p0 & 255n;
  return v0;
}

export type UnionTag =
  | { _tag: 0; first: number; }
  | { _tag: 1; second: number; };


export function serializeUnionTagInto(obj: UnionTag, buffer: Uint8Array): number {
  let inoutBufferSizeBytes = buffer.length;
  const v0 = obj == null || false;
  const v1 = v0 || false;
  let err: number;
  if (v1) {
    err = -2;
  } else {
    const size = BigInt(inoutBufferSizeBytes);
    const v2 = size * 8n;
    const err2 = mlir_llvmdsdl_plan_capacity_check__fixtures_vendor_UnionTag_1_0(v2);
    const tag = dsdlRuntime.toBigIntValue(obj._tag);
    const tag2 = mlir_llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__ser(tag);
    const err3 = mlir_llvmdsdl_plan_validate_union_tag__fixtures_vendor_UnionTag_1_0(tag2);
    const v3 = err2 === 0;
    const v4 = v3 ? err3 : err2;
    const v5 = v4 === 0;
    const v6 = v5 ? 8n : 0n;
    let err4: number;
    if (v5) {
      const err5 = dsdlRuntime.writeUnsigned(buffer, Number(0n), 8, tag2, false);
      err4 = err5;
    } else {
      err4 = v4;
    }
    const v7 = tag2 === 0n;
    let offset: bigint;
    let err6: number;
    if (v7) {
      const v8 = err4 === 0;
      let offset2: bigint;
      let err7: number;
      if (v8) {
        const firstValue = dsdlRuntime.toBigIntValue((obj as { first: number }).first);
        const value = mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__ser(firstValue);
        const err8 = dsdlRuntime.writeUnsigned(buffer, Number(v6), 8, value, false);
        const v9 = v6 + 8n;
        offset2 = v9;
        err7 = err8;
      } else {
        offset2 = v6;
        err7 = err4;
      }
      offset = offset2;
      err6 = err7;
    } else {
      offset = v6;
      err6 = err4;
    }
    const v10 = tag2 === 1n;
    let offset3: bigint;
    let err9: number;
    if (v10) {
      const v11 = err6 === 0;
      let offset4: bigint;
      let err10: number;
      if (v11) {
        const secondValue = dsdlRuntime.toBigIntValue((obj as { second: number }).second);
        const value2 = mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__ser(secondValue);
        const err11 = dsdlRuntime.writeUnsigned(buffer, Number(offset), 16, value2, false);
        const v12 = offset + 16n;
        offset4 = v12;
        err10 = err11;
      } else {
        offset4 = offset;
        err10 = err6;
      }
      offset3 = offset4;
      err9 = err10;
    } else {
      offset3 = offset;
      err9 = err6;
    }
    const v13 = err9 === 0;
    if (v13) {
      const v14 = offset3 / 8n;
      inoutBufferSizeBytes = Number(v14);
    }
    err = err9;
  }
  if (err === 0) {
    return inoutBufferSizeBytes;
  }
  return err;
}

export function deserializeUnionTagFrom(obj: UnionTag, buffer: Uint8Array): number {
  let inoutBufferSizeBytes = buffer.length;
  const v0 = obj == null || false;
  let v1: boolean;
  if (v0) {
    v1 = true;
  } else {
    const size = BigInt(inoutBufferSizeBytes);
    const v2 = size !== 0n;
    const v3 = false && v2;
    v1 = v3;
  }
  let err: number;
  if (v1) {
    err = -2;
  } else {
    const size2 = BigInt(inoutBufferSizeBytes);
    const value = dsdlRuntime.readUnsignedBigInt(buffer, Number(0n), 8);
    const tag = mlir_llvmdsdl_plan_union_tag__fixtures_vendor_UnionTag_1_0__deser(value);
    const err2 = mlir_llvmdsdl_plan_validate_union_tag__fixtures_vendor_UnionTag_1_0(tag);
    const v4 = err2 === 0;
    const v5 = v4 ? 8n : 0n;
    if (v4) {
      (obj as { _tag: number })._tag = Number(tag);
    }
    const v6 = tag === 0n;
    let v7: bigint;
    if (v6) {
      const value2 = dsdlRuntime.readUnsignedBigInt(buffer, Number(v5), 8);
      const value3 = mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__0__deser(value2);
      (obj as { first: number }).first = Number(value3);
      const v8 = v5 + 8n;
      v7 = v8;
    } else {
      v7 = v5;
    }
    const v9 = tag === 1n;
    let v10: bigint;
    if (v9) {
      const value4 = dsdlRuntime.readUnsignedBigInt(buffer, Number(v7), 16);
      const value5 = mlir_llvmdsdl_plan_scalar_unsigned__fixtures_vendor_UnionTag_1_0__1__deser(value4);
      (obj as { second: number }).second = Number(value5);
      const v11 = v7 + 16n;
      v10 = v11;
    } else {
      v10 = v7;
    }
    const v12 = v10 + 7n;
    const v13 = v12 / 8n;
    const v14 = v13 * 8n;
    const v15 = size2 * 8n;
    const v16 = v14 < v15;
    const v17 = v16 ? v14 : v15;
    const v18 = err2 === 0;
    if (v18) {
      const v19 = v17 / 8n;
      inoutBufferSizeBytes = Number(v19);
    }
    err = err2;
  }
  if (err === 0) {
    return inoutBufferSizeBytes;
  }
  return err;
}

export function serializeUnionTag(value: UnionTag): Uint8Array {
  const buffer = new Uint8Array(3);
  const result = serializeUnionTagInto(value, buffer);
  if (result < 0) {
    throw new Error(dsdlRuntime.errorMessage(result));
  }
  return buffer.subarray(0, result);
}

export function deserializeUnionTag(bytes: Uint8Array): { value: UnionTag; consumed: number } {
  const value = {} as UnionTag;
  const result = deserializeUnionTagFrom(value, bytes);
  if (result < 0) {
    throw new Error(dsdlRuntime.errorMessage(result));
  }
  return { value, consumed: result };
}
