// Generated by llvmdsdl 0.2.3 (TypeScript backend).
// Source: fixtures.vendor.UsesDelimited.1.0
import * as dsdlRuntime from "../../dsdl_runtime";

import { deserializeDelimitedFrom, makeDelimited, serializeDelimitedInto } from "./delimited_1_0";
import type { Delimited } from "./delimited_1_0";
export const LLVMDSDL_GENERATOR_VERSION = "0.2.3";
export const DSDL_FULL_NAME = "fixtures.vendor.UsesDelimited";
export const DSDL_IS_DEPRECATED = false;
export const DSDL_VERSION_MAJOR = 1;
export const DSDL_VERSION_MINOR = 0;
export const DSDL_HAS_FIXED_PORT_ID = false;
export const DSDL_ZOH_ALIAS_ELIGIBLE = false;
export const DSDL_ZOH_ALIAS_REASON = "composite-field";

function mlir_llvmdsdl_plan_capacity_check__fixtures_vendor_UsesDelimited_1_0(p0: bigint): number {
  const v0 = 96n > p0;
  let v1: number;
  if (v0) {
    v1 = -3;
  } else {
    v1 = 0;
  }
  return v1;
}

function mlir_llvmdsdl_plan_validate_delimiter_header__fixtures_vendor_UsesDelimited_1_0__1(p0: bigint, p1: bigint): number {
  const v0 = p0 < 0n;
  const v1 = p0 > p1;
  const v2 = v0 || v1;
  let v3: number;
  if (v2) {
    v3 = -12;
  } else {
    v3 = 0;
  }
  return v3;
}

export interface UsesDelimited {
  nested: Delimited;
}

export function makeUsesDelimited(): UsesDelimited {
  return {
    nested: makeDelimited(),
  };
}


export function serializeUsesDelimitedInto(obj: UsesDelimited, buffer: Uint8Array): number {
  let inoutBufferSizeBytes = buffer.length;
  const v0 = obj == null || false;
  const v1 = v0 || false;
  let err: number;
  if (v1) {
    err = -2;
  } else {
    const size = BigInt(inoutBufferSizeBytes);
    const v2 = size * 8n;
    const err2 = mlir_llvmdsdl_plan_capacity_check__fixtures_vendor_UsesDelimited_1_0(v2);
    const v3 = err2 === 0;
    let err3: number;
    if (v3) {
      const v4 = size - 4n;
      let nestedSize = Number(v4);
      const v5 = err2 === 0;
      let err4: number;
      if (v5) {
        const nestedBuf = buffer.subarray(Math.min(Number(4n), buffer.length));
        const _bound0_ = Math.min(nestedSize, nestedBuf.length);
        const _result1_ = serializeDelimitedInto(obj.nested, nestedBuf.subarray(0, _bound0_));
        let nestedErr: number;
        if (_result1_ < 0) {
          nestedErr = _result1_;
        } else {
          nestedErr = 0;
        }
        const err5 = mlir_llvmdsdl_plan_validate_delimiter_header__fixtures_vendor_UsesDelimited_1_0__1(1n, v4);
        const v6 = nestedErr === 0;
        const v7 = v6 ? err5 : nestedErr;
        const v8 = v7 === 0;
        let err6: number;
        if (v8) {
          const err7 = dsdlRuntime.writeUnsigned(buffer, Number(0n), 32, 1n, false);
          const v9 = v7 === 0;
          const v10 = v9 ? err7 : v7;
          err6 = v10;
        } else {
          err6 = v7;
        }
        err4 = err6;
      } else {
        err4 = err2;
      }
      err3 = err4;
    } else {
      err3 = err2;
    }
    const v11 = err3 === 0;
    if (v11) {
      inoutBufferSizeBytes = Number(5n);
    }
    err = err3;
  }
  if (err === 0) {
    return inoutBufferSizeBytes;
  }
  return err;
}

export function deserializeUsesDelimitedFrom(obj: UsesDelimited, buffer: Uint8Array): number {
  let inoutBufferSizeBytes = buffer.length;
  const v0 = obj == null || false;
  let rejected: boolean;
  if (v0) {
    rejected = true;
  } else {
    const size = BigInt(inoutBufferSizeBytes);
    const v1 = size !== 0n;
    const v2 = false && v1;
    rejected = v2;
  }
  let err: number;
  if (rejected) {
    err = -2;
  } else {
    const size2 = BigInt(inoutBufferSizeBytes);
    const nestedAddr = (obj.nested ??= {} as Delimited);
    const value = dsdlRuntime.readUnsignedBigInt(buffer, Number(0n), 32);
    const v3 = size2 > 4n;
    const v4 = v3 ? 4n : size2;
    const v5 = size2 - v4;
    let nestedSize = Number(value);
    const err2 = mlir_llvmdsdl_plan_validate_delimiter_header__fixtures_vendor_UsesDelimited_1_0__1(value, v5);
    const v6 = err2 === 0;
    let offset: bigint;
    let err3: number;
    if (v6) {
      const nestedBuf = buffer.subarray(Math.min(Number(v4), buffer.length));
      const _bound2_ = Math.min(nestedSize, nestedBuf.length);
      const _result3_ = deserializeDelimitedFrom(nestedAddr, nestedBuf.subarray(0, _bound2_));
      let nestedErr: number;
      if (_result3_ < 0) {
        nestedErr = _result3_;
      } else {
        nestedErr = 0;
      }
      const v7 = nestedErr === 0;
      let v8: bigint;
      if (v7) {
        const v9 = value * 8n;
        const v10 = v9 + 32n;
        v8 = v10;
      } else {
        v8 = 32n;
      }
      offset = v8;
      err3 = nestedErr;
    } else {
      offset = 32n;
      err3 = err2;
    }
    const v11 = offset + 7n;
    const v12 = v11 / 8n;
    const v13 = v12 * 8n;
    const v14 = size2 * 8n;
    const v15 = v13 < v14;
    const v16 = v15 ? v13 : v14;
    const v17 = err3 === 0;
    if (v17) {
      const v18 = v16 / 8n;
      inoutBufferSizeBytes = Number(v18);
    }
    err = err3;
  }
  if (err === 0) {
    return inoutBufferSizeBytes;
  }
  return err;
}

export function serializeUsesDelimited(value: UsesDelimited): Uint8Array {
  const buffer = new Uint8Array(12);
  const result = serializeUsesDelimitedInto(value, buffer);
  if (result < 0) {
    throw new Error(dsdlRuntime.errorMessage(result));
  }
  return buffer.subarray(0, result);
}

export function deserializeUsesDelimited(bytes: Uint8Array): { value: UsesDelimited; consumed: number } {
  const value = makeUsesDelimited();
  const result = deserializeUsesDelimitedFrom(value, bytes);
  if (result < 0) {
    throw new Error(dsdlRuntime.errorMessage(result));
  }
  return { value, consumed: result };
}
